unit Abre;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, JvSpin, Mask, JvExMask,
  JvToolEdit, ExtCtrls;
  
type
  TfrmAbre=class(TForm)
    lbTitulo: TLabel;
    nbAbre: TNotebook;
    edCodMesa: TJvComboEdit;
    edCgcClie: TJvComboEdit;
    edCodFunc: TJvComboEdit;
    edNumPessoas: TJvSpinEdit;
    edDescrMesa: TEdit;
    edCliente: TEdit;
    edFuncionario: TEdit;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    btOK: TBitBtn;
    btCancelar: TBitBtn;
    Bevel1: TBevel;
    sbCadClie: TSpeedButton;
    procedure FormCreate(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure edCodMesaButtonClick(Sender : TObject);
    procedure edCgcClieButtonClick(Sender : TObject);
    procedure edCodFuncButtonClick(Sender : TObject);
    procedure edCodMesaChange(Sender : TObject);
    procedure edCgcClieChange(Sender : TObject);
    procedure edCodFuncChange(Sender : TObject);
    procedure sbCadClieClick(Sender : TObject);
    procedure _PROC_0068F9D0(Sender : TObject);
    procedure _PROC_0068FA21(Sender : TObject);
    procedure _PROC_0068FBF0(Sender : TObject);
    procedure _PROC_00690155(Sender : TObject);
    procedure _PROC_00690186(Sender : TObject);
    procedure _PROC_0069046D(Sender : TObject);
    procedure _PROC_0069047E(Sender : TObject);
    procedure _PROC_00690489(Sender : TObject);
    procedure _PROC_00690682(Sender : TObject);
    procedure _PROC_00690693(Sender : TObject);
    procedure _PROC_00690815(Sender : TObject);
    procedure _PROC_00690844(Sender : TObject);
    procedure _PROC_0069084C(Sender : TObject);
    procedure _PROC_00690B2F(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmAbre: TfrmAbre;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmAbre.FormCreate(Sender : TObject);
begin
(*
0068FC4C   A130AE7D00             mov     eax, dword ptr [$007DAE30]
0068FC51   8B00                   mov     eax, [eax]
0068FC53   8B1554AE7D00           mov     edx, [$007DAE54]
0068FC59   8B12                   mov     edx, [edx]
0068FC5B   8982DC000000           mov     [edx+$00DC], eax
0068FC61   C782D8000000C0007D00   mov     dword ptr [edx+$00D8], $007D00C0
0068FC6B   C3                     ret

*)
end;

procedure TfrmAbre.FormShow(Sender : TObject);
begin
(*
0068FC6C   55                     push    ebp
0068FC6D   8BEC                   mov     ebp, esp
0068FC6F   33C9                   xor     ecx, ecx
0068FC71   51                     push    ecx
0068FC72   51                     push    ecx
0068FC73   51                     push    ecx
0068FC74   51                     push    ecx
0068FC75   51                     push    ecx
0068FC76   53                     push    ebx
0068FC77   8BD8                   mov     ebx, eax
0068FC79   33C0                   xor     eax, eax
0068FC7B   55                     push    ebp
0068FC7C   682FFD6800             push    $0068FD2F

***** TRY
|
0068FC81   64FF30                 push    dword ptr fs:[eax]
0068FC84   648920                 mov     fs:[eax], esp
0068FC87   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
0068FC8A   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0068FC90   E8A7E2E6FF             call    004FDF3C
0068FC95   837DFC00               cmp     dword ptr [ebp-$04], +$00
0068FC99   7523                   jnz     0068FCBE
0068FC9B   8D55F8                 lea     edx, [ebp-$08]
0068FC9E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0068FCA3   8B00                   mov     eax, [eax]
0068FCA5   8B80B4030000           mov     eax, [eax+$03B4]
0068FCAB   8B08                   mov     ecx, [eax]
0068FCAD   FF5160                 call    dword ptr [ecx+$60]
0068FCB0   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
0068FCB3   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0068FCB9   E812E3E6FF             call    004FDFD0
0068FCBE   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
0068FCC1   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0068FCC7   E870E2E6FF             call    004FDF3C
0068FCCC   837DF400               cmp     dword ptr [ebp-$0C], +$00
0068FCD0   7527                   jnz     0068FCF9
0068FCD2   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
0068FCD5   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0068FCDB   E85CE2E6FF             call    004FDF3C
0068FCE0   8B45EC                 mov     eax, [ebp-$14]
0068FCE3   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007B1A28()
|
0068FCE6   E83D1D1200             call    007B1A28
0068FCEB   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
0068FCEE   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0068FCF4   E8D7E2E6FF             call    004FDFD0
0068FCF9   33C0                   xor     eax, eax
0068FCFB   5A                     pop     edx
0068FCFC   59                     pop     ecx
0068FCFD   59                     pop     ecx
0068FCFE   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068FD01   6836FD6800             push    $0068FD36
0068FD06   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0068FD09   E88E57D7FF             call    0040549C
0068FD0E   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.@LStrClr(void;void);
|
0068FD11   E88657D7FF             call    0040549C
0068FD16   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0068FD19   E87E57D7FF             call    0040549C
0068FD1E   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0068FD21   E87657D7FF             call    0040549C
0068FD26   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068FD29   E86E57D7FF             call    0040549C
0068FD2E   C3                     ret


* Reference to: System.@HandleFinally;
|
0068FD2F   E90450D7FF             jmp     00404D38
0068FD34   EBD0                   jmp     0068FD06

****** END
|
0068FD36   5B                     pop     ebx
0068FD37   8BE5                   mov     esp, ebp
0068FD39   5D                     pop     ebp
0068FD3A   C3                     ret

*)
end;

procedure TfrmAbre.FormCloseQuery(Sender : TObject);
begin
(*
0068FD3C   55                     push    ebp
0068FD3D   8BEC                   mov     ebp, esp
0068FD3F   53                     push    ebx
0068FD40   56                     push    esi
0068FD41   8BF1                   mov     esi, ecx
0068FD43   8BD8                   mov     ebx, eax

* Reference to field TfrmAbre.ModalResult : TModalResult
|
0068FD45   83BB4C02000001         cmp     dword ptr [ebx+$024C], +$01
0068FD4C   7519                   jnz     0068FD67
0068FD4E   8BC3                   mov     eax, ebx

|
0068FD50   E833070000             call    00690488
0068FD55   84C0                   test    al, al
0068FD57   740B                   jz      0068FD64
0068FD59   8BC3                   mov     eax, ebx

|
0068FD5B   E8C0FCFFFF             call    0068FA20
0068FD60   8806                   mov     [esi], al
0068FD62   EB03                   jmp     0068FD67
0068FD64   C60600                 mov     byte ptr [esi], $00
0068FD67   5E                     pop     esi
0068FD68   5B                     pop     ebx
0068FD69   5D                     pop     ebp
0068FD6A   C3                     ret

*)
end;

procedure TfrmAbre.edCodMesaButtonClick(Sender : TObject);
begin
(*
0068FD6C   55                     push    ebp
0068FD6D   8BEC                   mov     ebp, esp
0068FD6F   83C4E8                 add     esp, -$18
0068FD72   53                     push    ebx
0068FD73   33C9                   xor     ecx, ecx
0068FD75   894DE8                 mov     [ebp-$18], ecx
0068FD78   894DEC                 mov     [ebp-$14], ecx
0068FD7B   8BD8                   mov     ebx, eax
0068FD7D   33C0                   xor     eax, eax
0068FD7F   55                     push    ebp
0068FD80   6838FE6800             push    $0068FE38

***** TRY
|
0068FD85   64FF30                 push    dword ptr fs:[eax]
0068FD88   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'código'
|
0068FD8B   B84CFE6800             mov     eax, $0068FE4C
0068FD90   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Descrição'
|
0068FD93   B85CFE6800             mov     eax, $0068FE5C
0068FD98   8945FC                 mov     [ebp-$04], eax
0068FD9B   8D45F8                 lea     eax, [ebp-$08]
0068FD9E   50                     push    eax
0068FD9F   6A01                   push    $01
0068FDA1   6A00                   push    $00

* Possible String Reference to: 'CodMesa'
|
0068FDA3   B870FE6800             mov     eax, $0068FE70
0068FDA8   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Descricao'
|
0068FDAB   B880FE6800             mov     eax, $0068FE80
0068FDB0   8945F4                 mov     [ebp-$0C], eax
0068FDB3   8D55F0                 lea     edx, [ebp-$10]
0068FDB6   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'MESAS'
|
0068FDBB   B894FE6800             mov     eax, $0068FE94

|
0068FDC0   E88F94FAFF             call    00639254
0068FDC5   84C0                   test    al, al
0068FDC7   7454                   jz      0068FE1D
0068FDC9   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0068FDCE   8B00                   mov     eax, [eax]
0068FDD0   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODMESA'
|
0068FDD3   BAA4FE6800             mov     edx, $0068FEA4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068FDD8   E8279EE5FF             call    004E9C04
0068FDDD   8D55EC                 lea     edx, [ebp-$14]
0068FDE0   8B08                   mov     ecx, [eax]
0068FDE2   FF5160                 call    dword ptr [ecx+$60]
0068FDE5   8B55EC                 mov     edx, [ebp-$14]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
0068FDE8   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Mask.TCustomMaskEdit.SetEditText(TCustomMaskEdit;AnsiString);
|
0068FDEE   E87DE0E6FF             call    004FDE70
0068FDF3   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0068FDF8   8B00                   mov     eax, [eax]
0068FDFA   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'DESCRICAO'
|
0068FDFD   BAB4FE6800             mov     edx, $0068FEB4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068FE02   E8FD9DE5FF             call    004E9C04
0068FE07   8D55E8                 lea     edx, [ebp-$18]
0068FE0A   8B08                   mov     ecx, [eax]
0068FE0C   FF5160                 call    dword ptr [ecx+$60]
0068FE0F   8B55E8                 mov     edx, [ebp-$18]

* Reference to control TfrmAbre.edDescrMesa : TEdit
|
0068FE12   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0068FE18   E8DF38E0FF             call    004936FC
0068FE1D   33C0                   xor     eax, eax
0068FE1F   5A                     pop     edx
0068FE20   59                     pop     ecx
0068FE21   59                     pop     ecx
0068FE22   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068FE25   683FFE6800             push    $0068FE3F
0068FE2A   8D45E8                 lea     eax, [ebp-$18]
0068FE2D   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068FE32   E88956D7FF             call    004054C0
0068FE37   C3                     ret


* Reference to: System.@HandleFinally;
|
0068FE38   E9FB4ED7FF             jmp     00404D38
0068FE3D   EBEB                   jmp     0068FE2A

****** END
|
0068FE3F   5B                     pop     ebx
0068FE40   8BE5                   mov     esp, ebp
0068FE42   5D                     pop     ebp
0068FE43   C3                     ret

*)
end;

procedure TfrmAbre.edCgcClieButtonClick(Sender : TObject);
begin
(*
0068FEC0   55                     push    ebp
0068FEC1   8BEC                   mov     ebp, esp
0068FEC3   83C4E0                 add     esp, -$20
0068FEC6   53                     push    ebx
0068FEC7   33C9                   xor     ecx, ecx
0068FEC9   894DE0                 mov     [ebp-$20], ecx
0068FECC   894DE4                 mov     [ebp-$1C], ecx
0068FECF   8BD8                   mov     ebx, eax
0068FED1   33C0                   xor     eax, eax
0068FED3   55                     push    ebp
0068FED4   689CFF6800             push    $0068FF9C

***** TRY
|
0068FED9   64FF30                 push    dword ptr fs:[eax]
0068FEDC   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'CNPJ'
|
0068FEDF   B8B0FF6800             mov     eax, $0068FFB0
0068FEE4   8945F4                 mov     [ebp-$0C], eax

* Possible String Reference to: 'Razão'
|
0068FEE7   B8C0FF6800             mov     eax, $0068FFC0
0068FEEC   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Fantasia'
|
0068FEEF   B8D0FF6800             mov     eax, $0068FFD0
0068FEF4   8945FC                 mov     [ebp-$04], eax
0068FEF7   8D45F4                 lea     eax, [ebp-$0C]
0068FEFA   50                     push    eax
0068FEFB   6A02                   push    $02
0068FEFD   6A00                   push    $00

* Possible String Reference to: 'CGCCLIE'
|
0068FEFF   B8E4FF6800             mov     eax, $0068FFE4
0068FF04   8945E8                 mov     [ebp-$18], eax

* Possible String Reference to: 'RAZAO'
|
0068FF07   B8F4FF6800             mov     eax, $0068FFF4
0068FF0C   8945EC                 mov     [ebp-$14], eax

* Possible String Reference to: 'FANTASIA'
|
0068FF0F   B804006900             mov     eax, $00690004
0068FF14   8945F0                 mov     [ebp-$10], eax
0068FF17   8D55E8                 lea     edx, [ebp-$18]
0068FF1A   B902000000             mov     ecx, $00000002

* Possible String Reference to: 'CLIENTES'
|
0068FF1F   B818006900             mov     eax, $00690018

|
0068FF24   E82B93FAFF             call    00639254
0068FF29   84C0                   test    al, al
0068FF2B   7454                   jz      0068FF81
0068FF2D   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0068FF32   8B00                   mov     eax, [eax]
0068FF34   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CGCCLIE'
|
0068FF37   BAE4FF6800             mov     edx, $0068FFE4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068FF3C   E8C39CE5FF             call    004E9C04
0068FF41   8D55E4                 lea     edx, [ebp-$1C]
0068FF44   8B08                   mov     ecx, [eax]
0068FF46   FF5160                 call    dword ptr [ecx+$60]
0068FF49   8B55E4                 mov     edx, [ebp-$1C]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
0068FF4C   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.SetEditText(TCustomMaskEdit;AnsiString);
|
0068FF52   E819DFE6FF             call    004FDE70
0068FF57   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0068FF5C   8B00                   mov     eax, [eax]
0068FF5E   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'RAZAO'
|
0068FF61   BAF4FF6800             mov     edx, $0068FFF4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068FF66   E8999CE5FF             call    004E9C04
0068FF6B   8D55E0                 lea     edx, [ebp-$20]
0068FF6E   8B08                   mov     ecx, [eax]
0068FF70   FF5160                 call    dword ptr [ecx+$60]
0068FF73   8B55E0                 mov     edx, [ebp-$20]

* Reference to control TfrmAbre.edCliente : TEdit
|
0068FF76   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0068FF7C   E87B37E0FF             call    004936FC
0068FF81   33C0                   xor     eax, eax
0068FF83   5A                     pop     edx
0068FF84   59                     pop     ecx
0068FF85   59                     pop     ecx
0068FF86   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068FF89   68A3FF6800             push    $0068FFA3
0068FF8E   8D45E0                 lea     eax, [ebp-$20]
0068FF91   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068FF96   E82555D7FF             call    004054C0
0068FF9B   C3                     ret


* Reference to: System.@HandleFinally;
|
0068FF9C   E9974DD7FF             jmp     00404D38
0068FFA1   EBEB                   jmp     0068FF8E

****** END
|
0068FFA3   5B                     pop     ebx
0068FFA4   8BE5                   mov     esp, ebp
0068FFA6   5D                     pop     ebp
0068FFA7   C3                     ret

*)
end;

procedure TfrmAbre.edCodFuncButtonClick(Sender : TObject);
begin
(*
00690024   55                     push    ebp
00690025   8BEC                   mov     ebp, esp
00690027   83C4E0                 add     esp, -$20
0069002A   53                     push    ebx
0069002B   33C9                   xor     ecx, ecx
0069002D   894DE0                 mov     [ebp-$20], ecx
00690030   894DE4                 mov     [ebp-$1C], ecx
00690033   8BD8                   mov     ebx, eax
00690035   33C0                   xor     eax, eax
00690037   55                     push    ebp

* Possible String Reference to: 'é.L×ÿëë[‹å]Ã'
|
00690038   6805016900             push    $00690105

***** TRY
|
0069003D   64FF30                 push    dword ptr fs:[eax]
00690040   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'Código'
|
00690043   B81C016900             mov     eax, $0069011C
00690048   8945F4                 mov     [ebp-$0C], eax

* Possible String Reference to: 'Nome'
|
0069004B   B82C016900             mov     eax, $0069012C
00690050   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Fantasia'
|
00690053   B83C016900             mov     eax, $0069013C
00690058   8945FC                 mov     [ebp-$04], eax
0069005B   8D45F4                 lea     eax, [ebp-$0C]
0069005E   50                     push    eax
0069005F   6A02                   push    $02
00690061   6A00                   push    $00

* Possible String Reference to: 'CODFUNC'
|
00690063   B850016900             mov     eax, $00690150
00690068   8945E8                 mov     [ebp-$18], eax

* Possible String Reference to: 'NOME'
|
0069006B   B860016900             mov     eax, $00690160
00690070   8945EC                 mov     [ebp-$14], eax

* Possible String Reference to: 'FANTASIA'
|
00690073   B870016900             mov     eax, $00690170
00690078   8945F0                 mov     [ebp-$10], eax
0069007B   8D55E8                 lea     edx, [ebp-$18]
0069007E   B902000000             mov     ecx, $00000002

* Possible String Reference to: 'FUNCREPR'
|
00690083   B884016900             mov     eax, $00690184

|
00690088   E8C791FAFF             call    00639254
0069008D   84C0                   test    al, al
0069008F   7454                   jz      006900E5
00690091   A1689F7D00             mov     eax, dword ptr [$007D9F68]
00690096   8B00                   mov     eax, [eax]
00690098   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODFUNC'
|
0069009B   BA50016900             mov     edx, $00690150

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006900A0   E85F9BE5FF             call    004E9C04
006900A5   8D55E4                 lea     edx, [ebp-$1C]
006900A8   8B08                   mov     ecx, [eax]
006900AA   FF5160                 call    dword ptr [ecx+$60]
006900AD   8B55E4                 mov     edx, [ebp-$1C]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
006900B0   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.SetEditText(TCustomMaskEdit;AnsiString);
|
006900B6   E8B5DDE6FF             call    004FDE70
006900BB   A1689F7D00             mov     eax, dword ptr [$007D9F68]
006900C0   8B00                   mov     eax, [eax]
006900C2   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'NOME'
|
006900C5   BA60016900             mov     edx, $00690160

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006900CA   E8359BE5FF             call    004E9C04
006900CF   8D55E0                 lea     edx, [ebp-$20]
006900D2   8B08                   mov     ecx, [eax]
006900D4   FF5160                 call    dword ptr [ecx+$60]
006900D7   8B55E0                 mov     edx, [ebp-$20]

* Reference to control TfrmAbre.edFuncionario : TEdit
|
006900DA   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
006900E0   E81736E0FF             call    004936FC

|
006900E5   E86E5E1100             call    007A5F58
006900EA   33C0                   xor     eax, eax
006900EC   5A                     pop     edx
006900ED   59                     pop     ecx
006900EE   59                     pop     ecx
006900EF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
006900F2   680C016900             push    $0069010C
006900F7   8D45E0                 lea     eax, [ebp-$20]
006900FA   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
006900FF   E8BC53D7FF             call    004054C0
00690104   C3                     ret


* Reference to: System.@HandleFinally;
|
00690105   E92E4CD7FF             jmp     00404D38
0069010A   EBEB                   jmp     006900F7

****** END
|
0069010C   5B                     pop     ebx
0069010D   8BE5                   mov     esp, ebp
0069010F   5D                     pop     ebp
00690110   C3                     ret

*)
end;

procedure TfrmAbre.edCodMesaChange(Sender : TObject);
begin
(*
00690190   55                     push    ebp
00690191   8BEC                   mov     ebp, esp
00690193   33C9                   xor     ecx, ecx
00690195   51                     push    ecx
00690196   51                     push    ecx
00690197   51                     push    ecx
00690198   51                     push    ecx
00690199   51                     push    ecx
0069019A   53                     push    ebx
0069019B   8BD8                   mov     ebx, eax
0069019D   33C0                   xor     eax, eax
0069019F   55                     push    ebp
006901A0   6848026900             push    $00690248

***** TRY
|
006901A5   64FF30                 push    dword ptr fs:[eax]
006901A8   648920                 mov     fs:[eax], esp
006901AB   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
006901AE   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006901B4   E883DDE6FF             call    004FDF3C
006901B9   837DFC00               cmp     dword ptr [ebp-$04], +$00
006901BD   7451                   jz      00690210

* Possible String Reference to: 'DESCRICAO'
|
006901BF   685C026900             push    $0069025C
006901C4   8D45F8                 lea     eax, [ebp-$08]
006901C7   50                     push    eax
006901C8   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
006901CB   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006901D1   E866DDE6FF             call    004FDF3C
006901D6   8B45EC                 mov     eax, [ebp-$14]
006901D9   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
006901DC   E83F391100             call    007A3B20
006901E1   8B4DF0                 mov     ecx, [ebp-$10]
006901E4   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'CODMESA = '
|
006901E7   BA70026900             mov     edx, $00690270

* Reference to: System.@LStrCat3;
|
006901EC   E8B755D7FF             call    004057A8
006901F1   8B4DF4                 mov     ecx, [ebp-$0C]

* Possible String Reference to: 'MESAS'
|
006901F4   BA84026900             mov     edx, $00690284
006901F9   33C0                   xor     eax, eax

|
006901FB   E810911100             call    007A9310
00690200   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TfrmAbre.edDescrMesa : TEdit
|
00690203   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690209   E8EE34E0FF             call    004936FC
0069020E   EB0D                   jmp     0069021D
00690210   33D2                   xor     edx, edx

* Reference to control TfrmAbre.edDescrMesa : TEdit
|
00690212   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690218   E8DF34E0FF             call    004936FC
0069021D   33C0                   xor     eax, eax
0069021F   5A                     pop     edx
00690220   59                     pop     ecx
00690221   59                     pop     ecx
00690222   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690225   684F026900             push    $0069024F
0069022A   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0069022D   E86A52D7FF             call    0040549C
00690232   8D45F0                 lea     eax, [ebp-$10]
00690235   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069023A   E88152D7FF             call    004054C0
0069023F   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00690242   E85552D7FF             call    0040549C
00690247   C3                     ret


* Reference to: System.@HandleFinally;
|
00690248   E9EB4AD7FF             jmp     00404D38
0069024D   EBDB                   jmp     0069022A

****** END
|
0069024F   5B                     pop     ebx
00690250   8BE5                   mov     esp, ebp
00690252   5D                     pop     ebp
00690253   C3                     ret

*)
end;

procedure TfrmAbre.edCgcClieChange(Sender : TObject);
begin
(*
0069028C   55                     push    ebp
0069028D   8BEC                   mov     ebp, esp
0069028F   33C9                   xor     ecx, ecx
00690291   51                     push    ecx
00690292   51                     push    ecx
00690293   51                     push    ecx
00690294   51                     push    ecx
00690295   51                     push    ecx
00690296   53                     push    ebx
00690297   8BD8                   mov     ebx, eax
00690299   33C0                   xor     eax, eax
0069029B   55                     push    ebp
0069029C   6844036900             push    $00690344

***** TRY
|
006902A1   64FF30                 push    dword ptr fs:[eax]
006902A4   648920                 mov     fs:[eax], esp
006902A7   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
006902AA   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006902B0   E887DCE6FF             call    004FDF3C
006902B5   837DFC00               cmp     dword ptr [ebp-$04], +$00
006902B9   7451                   jz      0069030C

* Possible String Reference to: 'FANTASIA'
|
006902BB   6858036900             push    $00690358
006902C0   8D45F8                 lea     eax, [ebp-$08]
006902C3   50                     push    eax
006902C4   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
006902C7   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006902CD   E86ADCE6FF             call    004FDF3C
006902D2   8B45EC                 mov     eax, [ebp-$14]
006902D5   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
006902D8   E843381100             call    007A3B20
006902DD   8B4DF0                 mov     ecx, [ebp-$10]
006902E0   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'CGCCLIE = '
|
006902E3   BA6C036900             mov     edx, $0069036C

* Reference to: System.@LStrCat3;
|
006902E8   E8BB54D7FF             call    004057A8
006902ED   8B4DF4                 mov     ecx, [ebp-$0C]

* Possible String Reference to: 'CLIENTES'
|
006902F0   BA80036900             mov     edx, $00690380
006902F5   33C0                   xor     eax, eax

|
006902F7   E814901100             call    007A9310
006902FC   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TfrmAbre.edCliente : TEdit
|
006902FF   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690305   E8F233E0FF             call    004936FC
0069030A   EB0D                   jmp     00690319
0069030C   33D2                   xor     edx, edx

* Reference to control TfrmAbre.edCliente : TEdit
|
0069030E   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690314   E8E333E0FF             call    004936FC
00690319   33C0                   xor     eax, eax
0069031B   5A                     pop     edx
0069031C   59                     pop     ecx
0069031D   59                     pop     ecx
0069031E   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690321   684B036900             push    $0069034B
00690326   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
00690329   E86E51D7FF             call    0040549C
0069032E   8D45F0                 lea     eax, [ebp-$10]
00690331   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00690336   E88551D7FF             call    004054C0
0069033B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0069033E   E85951D7FF             call    0040549C
00690343   C3                     ret


* Reference to: System.@HandleFinally;
|
00690344   E9EF49D7FF             jmp     00404D38
00690349   EBDB                   jmp     00690326

****** END
|
0069034B   5B                     pop     ebx
0069034C   8BE5                   mov     esp, ebp
0069034E   5D                     pop     ebp
0069034F   C3                     ret

*)
end;

procedure TfrmAbre.edCodFuncChange(Sender : TObject);
begin
(*
0069038C   55                     push    ebp
0069038D   8BEC                   mov     ebp, esp
0069038F   33C9                   xor     ecx, ecx
00690391   51                     push    ecx
00690392   51                     push    ecx
00690393   51                     push    ecx
00690394   51                     push    ecx
00690395   51                     push    ecx
00690396   53                     push    ebx
00690397   8BD8                   mov     ebx, eax
00690399   33C0                   xor     eax, eax
0069039B   55                     push    ebp
0069039C   6844046900             push    $00690444

***** TRY
|
006903A1   64FF30                 push    dword ptr fs:[eax]
006903A4   648920                 mov     fs:[eax], esp
006903A7   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
006903AA   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006903B0   E887DBE6FF             call    004FDF3C
006903B5   837DFC00               cmp     dword ptr [ebp-$04], +$00
006903B9   7451                   jz      0069040C

* Possible String Reference to: 'NOME'
|
006903BB   6858046900             push    $00690458
006903C0   8D45F8                 lea     eax, [ebp-$08]
006903C3   50                     push    eax
006903C4   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
006903C7   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006903CD   E86ADBE6FF             call    004FDF3C
006903D2   8B45EC                 mov     eax, [ebp-$14]
006903D5   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
006903D8   E843371100             call    007A3B20
006903DD   8B4DF0                 mov     ecx, [ebp-$10]
006903E0   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'CODFUNC = '
|
006903E3   BA68046900             mov     edx, $00690468

* Reference to: System.@LStrCat3;
|
006903E8   E8BB53D7FF             call    004057A8
006903ED   8B4DF4                 mov     ecx, [ebp-$0C]

* Possible String Reference to: 'FUNCREPR'
|
006903F0   BA7C046900             mov     edx, $0069047C
006903F5   33C0                   xor     eax, eax

|
006903F7   E8148F1100             call    007A9310
006903FC   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TfrmAbre.edFuncionario : TEdit
|
006903FF   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690405   E8F232E0FF             call    004936FC
0069040A   EB0D                   jmp     00690419
0069040C   33D2                   xor     edx, edx

* Reference to control TfrmAbre.edFuncionario : TEdit
|
0069040E   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690414   E8E332E0FF             call    004936FC
00690419   33C0                   xor     eax, eax
0069041B   5A                     pop     edx
0069041C   59                     pop     ecx
0069041D   59                     pop     ecx
0069041E   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690421   684B046900             push    $0069044B
00690426   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
00690429   E86E50D7FF             call    0040549C
0069042E   8D45F0                 lea     eax, [ebp-$10]
00690431   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00690436   E88550D7FF             call    004054C0
0069043B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0069043E   E85950D7FF             call    0040549C
00690443   C3                     ret


* Reference to: System.@HandleFinally;
|
00690444   E9EF48D7FF             jmp     00404D38
00690449   EBDB                   jmp     00690426

****** END
|
0069044B   5B                     pop     ebx
0069044C   8BE5                   mov     esp, ebp
0069044E   5D                     pop     ebp
0069044F   C3                     ret

*)
end;

procedure TfrmAbre.sbCadClieClick(Sender : TObject);
begin
(*
006907BC   55                     push    ebp
006907BD   8BEC                   mov     ebp, esp
006907BF   A160AC7D00             mov     eax, dword ptr [$007DAC60]

* Possible String Reference to: 'cliente'
|
006907C4   BA0C086900             mov     edx, $0069080C

* Reference to: System.@LStrAsg(void;void;void;void);
|
006907C9   E8224DD7FF             call    004054F0
006907CE   33C9                   xor     ecx, ecx
006907D0   B201                   mov     dl, $01

* Reference to class TFrmCadRapido
|
006907D2   A174556300             mov     eax, dword ptr [$00635574]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
006907D7   E834D7E1FF             call    004ADF10
006907DC   8B1528A77D00           mov     edx, [$007DA728]
006907E2   8902                   mov     [edx], eax
006907E4   A128A77D00             mov     eax, dword ptr [$007DA728]
006907E9   8B00                   mov     eax, [eax]
006907EB   8B10                   mov     edx, [eax]
006907ED   FF92EC000000           call    dword ptr [edx+$00EC]
006907F3   A128A77D00             mov     eax, dword ptr [$007DA728]
006907F8   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
006907FA   E89D3DD7FF             call    0040459C
006907FF   5D                     pop     ebp
00690800   C3                     ret

*)
end;

procedure TfrmAbre._PROC_0068F9D0(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
0068F9D0   E96353D7FF             jmp     00404D38

|
0068F9D5   EBDE                   jmp     0068F9B5
0068F9D7   8A45F3                 mov     al, byte ptr [ebp-$0D]
0068F9DA   5F                     pop     edi
0068F9DB   5E                     pop     esi
0068F9DC   5B                     pop     ebx
0068F9DD   8BE5                   mov     esp, ebp
0068F9DF   5D                     pop     ebp
0068F9E0   C3                     ret

*)
end;

procedure TfrmAbre._PROC_0068FA21(Sender : TObject);
begin
(*
0068FA21   8BEC                   mov     ebp, esp
0068FA23   33C9                   xor     ecx, ecx
0068FA25   51                     push    ecx
0068FA26   51                     push    ecx
0068FA27   51                     push    ecx
0068FA28   51                     push    ecx
0068FA29   51                     push    ecx
0068FA2A   53                     push    ebx
0068FA2B   56                     push    esi
0068FA2C   57                     push    edi
0068FA2D   8BF0                   mov     esi, eax
0068FA2F   8B3D8CA97D00           mov     edi, [$007DA98C]
0068FA35   33C0                   xor     eax, eax
0068FA37   55                     push    ebp

* Possible String Reference to: 'éCQ×ÿëëŠEÿ_^[‹å]Ã'
|
0068FA38   68F0FB6800             push    $0068FBF0

***** TRY
|
0068FA3D   64FF30                 push    dword ptr fs:[eax]
0068FA40   648920                 mov     fs:[eax], esp
0068FA43   C645FF00               mov     byte ptr [ebp-$01], $00
0068FA47   33C0                   xor     eax, eax
0068FA49   55                     push    ebp
0068FA4A   68CEFB6800             push    $0068FBCE

***** TRY
|
0068FA4F   64FF30                 push    dword ptr fs:[eax]
0068FA52   648920                 mov     fs:[eax], esp
0068FA55   33C0                   xor     eax, eax
0068FA57   55                     push    ebp
0068FA58   6885FB6800             push    $0068FB85

***** TRY
|
0068FA5D   64FF30                 push    dword ptr fs:[eax]
0068FA60   648920                 mov     fs:[eax], esp
0068FA63   8B07                   mov     eax, [edi]

* Reference to field TfrmAbre.Color : TColor
|
0068FA65   8B4070                 mov     eax, [eax+$70]

|
0068FA68   E837721100             call    007A6CA4
0068FA6D   84C0                   test    al, al
0068FA6F   0F8406010000           jz      0068FB7B
0068FA75   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
0068FA78   8B8600030000           mov     eax, [esi+$0300]

* Reference to: ActnMan.TActionListCollection.GetListItem(TActionListCollection;Integer):TActionListItem;
|
0068FA7E   E855E4E6FF             call    004FDED8
0068FA83   8B55F8                 mov     edx, [ebp-$08]
0068FA86   8B07                   mov     eax, [edi]

* Reference to field TJvComboEdit.OFFS_0924
|
0068FA88   8B8024090000           mov     eax, [eax+$0924]
0068FA8E   8B08                   mov     ecx, [eax]
0068FA90   FF91B0000000           call    dword ptr [ecx+$00B0]

|
0068FA96   E8E9211200             call    007B1C84
0068FA9B   8BD0                   mov     edx, eax
0068FA9D   8B07                   mov     eax, [edi]
0068FA9F   8B8028090000           mov     eax, [eax+$0928]
0068FAA5   8B08                   mov     ecx, [eax]
0068FAA7   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to: SysUtils.Now:TDateTime;
|
0068FAAD   E8AAE1D7FF             call    0040DC5C
0068FAB2   83C4F8                 add     esp, -$08
0068FAB5   DD1C24                 fstp    qword ptr [esp]
0068FAB8   9B                     wait
0068FAB9   8B07                   mov     eax, [edi]
0068FABB   8B802C090000           mov     eax, [eax+$092C]
0068FAC1   8B10                   mov     edx, [eax]
0068FAC3   FF92A0000000           call    dword ptr [edx+$00A0]

* Reference to: SysUtils.Now:TDateTime;
|
0068FAC9   E88EE1D7FF             call    0040DC5C
0068FACE   83C4F8                 add     esp, -$08
0068FAD1   DD1C24                 fstp    qword ptr [esp]
0068FAD4   9B                     wait
0068FAD5   8B07                   mov     eax, [edi]
0068FAD7   8B8030090000           mov     eax, [eax+$0930]
0068FADD   8B10                   mov     edx, [eax]
0068FADF   FF92A0000000           call    dword ptr [edx+$00A0]
0068FAE5   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
0068FAE8   8B8604030000           mov     eax, [esi+$0304]

* Reference to: ActnMan.TActionListCollection.GetListItem(TActionListCollection;Integer):TActionListItem;
|
0068FAEE   E8E5E3E6FF             call    004FDED8
0068FAF3   8B55F4                 mov     edx, [ebp-$0C]
0068FAF6   8B07                   mov     eax, [edi]

* Reference to field TJvComboEdit.OFFS_0934
|
0068FAF8   8B8034090000           mov     eax, [eax+$0934]
0068FAFE   8B08                   mov     ecx, [eax]
0068FB00   FF91B0000000           call    dword ptr [ecx+$00B0]
0068FB06   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
0068FB09   8B8608030000           mov     eax, [esi+$0308]

* Reference to: ActnMan.TActionListCollection.GetListItem(TActionListCollection;Integer):TActionListItem;
|
0068FB0F   E8C4E3E6FF             call    004FDED8
0068FB14   8B55F0                 mov     edx, [ebp-$10]
0068FB17   8B07                   mov     eax, [edi]

* Reference to field TJvComboEdit.OFFS_0938
|
0068FB19   8B8038090000           mov     eax, [eax+$0938]
0068FB1F   8B08                   mov     ecx, [eax]
0068FB21   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TfrmAbre.edNumPessoas : TJvSpinEdit
|
0068FB27   8B860C030000           mov     eax, [esi+$030C]

|
0068FB2D   E83A07F5FF             call    005E026C
0068FB32   8BD0                   mov     edx, eax
0068FB34   8B07                   mov     eax, [edi]

* Reference to field TJvSpinEdit.OFFS_093C
|
0068FB36   8B803C090000           mov     eax, [eax+$093C]
0068FB3C   8B08                   mov     ecx, [eax]
0068FB3E   FF91A8000000           call    dword ptr [ecx+$00A8]
0068FB44   6A00                   push    $00
0068FB46   6A00                   push    $00
0068FB48   8B07                   mov     eax, [edi]
0068FB4A   8B8040090000           mov     eax, [eax+$0940]
0068FB50   8B10                   mov     edx, [eax]
0068FB52   FF92A4000000           call    dword ptr [edx+$00A4]
0068FB58   8B07                   mov     eax, [edi]
0068FB5A   8B8044090000           mov     eax, [eax+$0944]
0068FB60   BA0CFC6800             mov     edx, $0068FC0C
0068FB65   8B08                   mov     ecx, [eax]
0068FB67   FF91B0000000           call    dword ptr [ecx+$00B0]
0068FB6D   8B07                   mov     eax, [edi]
0068FB6F   8B4070                 mov     eax, [eax+$70]

|
0068FB72   E8E9731100             call    007A6F60
0068FB77   C645FF01               mov     byte ptr [ebp-$01], $01
0068FB7B   33C0                   xor     eax, eax
0068FB7D   5A                     pop     edx
0068FB7E   59                     pop     ecx
0068FB7F   59                     pop     ecx
0068FB80   648910                 mov     fs:[eax], edx
0068FB83   EB3B                   jmp     0068FBC0

* Reference to: System.@HandleOnException;
|
0068FB85   E92650D7FF             jmp     00404BB0
0068FB8A   0100                   add     [eax], eax
0068FB8C   0000                   add     [eax], al
0068FB8E   40                     inc     eax
0068FB8F   95                     xchg    eax, ebp
0068FB90   40                     inc     eax
0068FB91   0096FB680089           add     [esi+$890068FB], dl
0068FB97   C3                     ret

0068FB98   6A00                   push    $00
0068FB9A   8B4B04                 mov     ecx, [ebx+$04]
0068FB9D   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'Ocorreu um erro na função AdicionaM
|                                esaLcto.'
|
0068FBA0   BA18FC6800             mov     edx, $0068FC18

* Reference to: System.@LStrCat3;
|
0068FBA5   E8FE5BD7FF             call    004057A8
0068FBAA   8B45EC                 mov     eax, [ebp-$14]
0068FBAD   668B0D48FC6800         mov     cx, word ptr [$0068FC48]
0068FBB4   B201                   mov     dl, $01

|
0068FBB6   E8713FDBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0068FBBB   E8F052D7FF             call    00404EB0

****** END
|
0068FBC0   33C0                   xor     eax, eax
0068FBC2   5A                     pop     edx
0068FBC3   59                     pop     ecx
0068FBC4   59                     pop     ecx
0068FBC5   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068FBC8   68D5FB6800             push    $0068FBD5
0068FBCD   C3                     ret


* Reference to: System.@HandleFinally;
|
0068FBCE   E96551D7FF             jmp     00404D38
0068FBD3   EBF8                   jmp     0068FBCD

****** END
|
0068FBD5   33C0                   xor     eax, eax
0068FBD7   5A                     pop     edx
0068FBD8   59                     pop     ecx
0068FBD9   59                     pop     ecx
0068FBDA   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ŠEÿ_^[‹å]Ã'
|
0068FBDD   68F7FB6800             push    $0068FBF7
0068FBE2   8D45EC                 lea     eax, [ebp-$14]
0068FBE5   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068FBEA   E8D158D7FF             call    004054C0
0068FBEF   C3                     ret

*)
end;

procedure TfrmAbre._PROC_0068FBF0(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
0068FBF0   E94351D7FF             jmp     00404D38

|
0068FBF5   EBEB                   jmp     0068FBE2
0068FBF7   8A45FF                 mov     al, byte ptr [ebp-$01]
0068FBFA   5F                     pop     edi
0068FBFB   5E                     pop     esi
0068FBFC   5B                     pop     ebx
0068FBFD   8BE5                   mov     esp, ebp
0068FBFF   5D                     pop     ebp
0068FC00   C3                     ret

*)
end;

procedure TfrmAbre._PROC_00690155(Sender : TObject);
begin
(*
00690155   4E                     dec     esi
00690156   43                     inc     ebx
00690157   00FF                   add     bh, bh
00690159   FFFF                   DB  $FF, $FF  //      
0069015B   FF0400                 inc     dword ptr [eax+eax]
0069015E   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_00690186(Sender : TObject);
begin
(*
00690186   4E                     dec     esi
00690187   43                     inc     ebx
00690188   52                     push    edx
00690189   45                     inc     ebp
0069018A   50                     push    eax
0069018B   52                     push    edx
0069018C   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_0069046D(Sender : TObject);
begin
(*
0069046D   4E                     dec     esi
0069046E   43                     inc     ebx
0069046F   203D200000FF           and     [$FF000020], bh
00690475   FFFF                   DB  $FF, $FF  //      
00690477   FF08                   dec     dword ptr [eax]
00690479   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_0069047E(Sender : TObject);
begin
(*
0069047E   4E                     dec     esi
0069047F   43                     inc     ebx
00690480   52                     push    edx
00690481   45                     inc     ebp
00690482   50                     push    eax
00690483   52                     push    edx
00690484   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_00690489(Sender : TObject);
begin
(*
00690489   8BEC                   mov     ebp, esp
0069048B   33C9                   xor     ecx, ecx
0069048D   51                     push    ecx
0069048E   51                     push    ecx
0069048F   51                     push    ecx
00690490   51                     push    ecx
00690491   51                     push    ecx
00690492   51                     push    ecx
00690493   51                     push    ecx
00690494   51                     push    ecx
00690495   53                     push    ebx
00690496   56                     push    esi
00690497   57                     push    edi
00690498   8BD8                   mov     ebx, eax
0069049A   33C0                   xor     eax, eax
0069049C   55                     push    ebp

* Possible String Reference to: 'é±F×ÿëãŠEÿ_^[‹å]Ã'
|
0069049D   6882066900             push    $00690682

***** TRY
|
006904A2   64FF30                 push    dword ptr fs:[eax]
006904A5   648920                 mov     fs:[eax], esp
006904A8   C645FF01               mov     byte ptr [ebp-$01], $01
006904AC   33C0                   xor     eax, eax
006904AE   55                     push    ebp
006904AF   6858066900             push    $00690658

***** TRY
|
006904B4   64FF30                 push    dword ptr fs:[eax]
006904B7   648920                 mov     fs:[eax], esp
006904BA   33C0                   xor     eax, eax
006904BC   55                     push    ebp
006904BD   680F066900             push    $0069060F

***** TRY
|
006904C2   64FF30                 push    dword ptr fs:[eax]
006904C5   648920                 mov     fs:[eax], esp
006904C8   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmAbre.edCodMesa : TJvComboEdit
|
006904CB   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006904D1   E866DAE6FF             call    004FDF3C
006904D6   837DF800               cmp     dword ptr [ebp-$08], +$00
006904DA   751E                   jnz     006904FA
006904DC   6A00                   push    $00
006904DE   668B0D94066900         mov     cx, word ptr [$00690694]
006904E5   33D2                   xor     edx, edx

* Possible String Reference to: 'Código da mesa em branco não permit
|                                ido!'
|
006904E7   B8A0066900             mov     eax, $006906A0

|
006904EC   E83B36DBFF             call    00443B2C
006904F1   C645FF00               mov     byte ptr [ebp-$01], $00
006904F5   E90B010000             jmp     00690605
006904FA   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
006904FD   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
00690503   E834DAE6FF             call    004FDF3C
00690508   837DF400               cmp     dword ptr [ebp-$0C], +$00
0069050C   751E                   jnz     0069052C
0069050E   6A00                   push    $00
00690510   668B0D94066900         mov     cx, word ptr [$00690694]
00690517   33D2                   xor     edx, edx

* Possible String Reference to: 'Cliente em branco não permitido!'
|
00690519   B8D0066900             mov     eax, $006906D0

|
0069051E   E80936DBFF             call    00443B2C
00690523   C645FF00               mov     byte ptr [ebp-$01], $00
00690527   E9D9000000             jmp     00690605
0069052C   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmAbre.edCgcClie : TJvComboEdit
|
0069052F   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
00690535   E802DAE6FF             call    004FDF3C
0069053A   8B45F0                 mov     eax, [ebp-$10]

|
0069053D   E81E021200             call    007B0760
00690542   84C0                   test    al, al
00690544   751E                   jnz     00690564
00690546   6A00                   push    $00
00690548   668B0D94066900         mov     cx, word ptr [$00690694]
0069054F   33D2                   xor     edx, edx

* Possible String Reference to: 'Cliente não localizado!'
|
00690551   B8FC066900             mov     eax, $006906FC

|
00690556   E8D135DBFF             call    00443B2C
0069055B   C645FF00               mov     byte ptr [ebp-$01], $00
0069055F   E9A1000000             jmp     00690605
00690564   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
00690567   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0069056D   E8CAD9E6FF             call    004FDF3C
00690572   837DEC00               cmp     dword ptr [ebp-$14], +$00
00690576   751B                   jnz     00690593
00690578   6A00                   push    $00
0069057A   668B0D94066900         mov     cx, word ptr [$00690694]
00690581   33D2                   xor     edx, edx

* Possible String Reference to: 'Informe o atendente!'
|
00690583   B81C076900             mov     eax, $0069071C

|
00690588   E89F35DBFF             call    00443B2C
0069058D   C645FF00               mov     byte ptr [ebp-$01], $00
00690591   EB72                   jmp     00690605
00690593   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TfrmAbre.edCodFunc : TJvComboEdit
|
00690596   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0069059C   E89BD9E6FF             call    004FDF3C
006905A1   8B55E8                 mov     edx, [ebp-$18]
006905A4   A1DCAD7D00             mov     eax, dword ptr [$007DADDC]
006905A9   8B00                   mov     eax, [eax]

|
006905AB   E8880C1200             call    007B1238
006905B0   84C0                   test    al, al
006905B2   751B                   jnz     006905CF
006905B4   6A00                   push    $00
006905B6   668B0D94066900         mov     cx, word ptr [$00690694]
006905BD   33D2                   xor     edx, edx

* Possible String Reference to: 'Funcionario não localizado!'
|
006905BF   B83C076900             mov     eax, $0069073C

|
006905C4   E86335DBFF             call    00443B2C
006905C9   C645FF00               mov     byte ptr [ebp-$01], $00
006905CD   EB36                   jmp     00690605
006905CF   8D55E4                 lea     edx, [ebp-$1C]

* Reference to control TfrmAbre.edNumPessoas : TJvSpinEdit
|
006905D2   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
006905D8   E85FD9E6FF             call    004FDF3C
006905DD   8B45E4                 mov     eax, [ebp-$1C]
006905E0   BA60076900             mov     edx, $00690760

* Reference to: System.@LStrCmp;
|
006905E5   E8BE52D7FF             call    004058A8
006905EA   7519                   jnz     00690605
006905EC   6A00                   push    $00
006905EE   668B0D94066900         mov     cx, word ptr [$00690694]
006905F5   33D2                   xor     edx, edx

* Possible String Reference to: 'Número de pessoas não pode ser zera
|                                do!'
|
006905F7   B86C076900             mov     eax, $0069076C

|
006905FC   E82B35DBFF             call    00443B2C
00690601   C645FF00               mov     byte ptr [ebp-$01], $00
00690605   33C0                   xor     eax, eax
00690607   5A                     pop     edx
00690608   59                     pop     ecx
00690609   59                     pop     ecx
0069060A   648910                 mov     fs:[eax], edx
0069060D   EB3B                   jmp     0069064A

* Reference to: System.@HandleOnException;
|
0069060F   E99C45D7FF             jmp     00404BB0
00690614   0100                   add     [eax], eax
00690616   0000                   add     [eax], al
00690618   40                     inc     eax
00690619   95                     xchg    eax, ebp
0069061A   40                     inc     eax
0069061B   0020                   add     [eax], ah
0069061D   06                     push    es
0069061E   690089C36A00           imul    eax, [eax], $006AC389

* Reference to field TfrmAbre.Owner : TComponent
|
00690624   8B4B04                 mov     ecx, [ebx+$04]
00690627   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: 'Erro ao executar a rotina!'
|
0069062A   BA9C076900             mov     edx, $0069079C

* Reference to: System.@LStrCat3;
|
0069062F   E87451D7FF             call    004057A8
00690634   8B45E0                 mov     eax, [ebp-$20]
00690637   668B0D94066900         mov     cx, word ptr [$00690694]
0069063E   B201                   mov     dl, $01

|
00690640   E8E734DBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
00690645   E86648D7FF             call    00404EB0

****** END
|
0069064A   33C0                   xor     eax, eax
0069064C   5A                     pop     edx
0069064D   59                     pop     ecx
0069064E   59                     pop     ecx
0069064F   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690652   685F066900             push    $0069065F
00690657   C3                     ret


* Reference to: System.@HandleFinally;
|
00690658   E9DB46D7FF             jmp     00404D38
0069065D   EBF8                   jmp     00690657

****** END
|
0069065F   33C0                   xor     eax, eax
00690661   5A                     pop     edx
00690662   59                     pop     ecx
00690663   59                     pop     ecx
00690664   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ŠEÿ_^[‹å]Ã'
|
00690667   6889066900             push    $00690689
0069066C   8D45E0                 lea     eax, [ebp-$20]

* Reference to: System.@LStrClr(void;void);
|
0069066F   E8284ED7FF             call    0040549C
00690674   8D45E4                 lea     eax, [ebp-$1C]
00690677   BA06000000             mov     edx, $00000006

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069067C   E83F4ED7FF             call    004054C0
00690681   C3                     ret


* Reference to: System.@HandleFinally;
|
00690682   E9B146D7FF             jmp     00404D38
00690687   EBE3                   jmp     0069066C

****** END
|
00690689   8A45FF                 mov     al, byte ptr [ebp-$01]
0069068C   5F                     pop     edi
0069068D   5E                     pop     esi
0069068E   5B                     pop     ebx
0069068F   8BE5                   mov     esp, ebp
00690691   5D                     pop     ebp
00690692   C3                     ret

*)
end;

procedure TfrmAbre._PROC_00690682(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00690682   E9B146D7FF             jmp     00404D38

|
00690687   EBE3                   jmp     0069066C
00690689   8A45FF                 mov     al, byte ptr [ebp-$01]
0069068C   5F                     pop     edi
0069068D   5E                     pop     esi
0069068E   5B                     pop     ebx
0069068F   8BE5                   mov     esp, ebp
00690691   5D                     pop     ebp
00690692   C3                     ret

*)
end;

procedure TfrmAbre._PROC_00690693(Sender : TObject);
begin
(*
00690693   000400                 add     [eax+eax], al
00690696   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_00690815(Sender : TObject);
begin
(*
00690815   8BEC                   mov     ebp, esp
00690817   33C0                   xor     eax, eax
00690819   55                     push    ebp

* Possible String Reference to: 'éúD×ÿëø]Ã‹Àƒ-Èì}'
|
0069081A   6839086900             push    $00690839

***** TRY
|
0069081F   64FF30                 push    dword ptr fs:[eax]
00690822   648920                 mov     fs:[eax], esp
00690825   FF05C8EC7D00           inc     dword ptr [$007DECC8]
0069082B   33C0                   xor     eax, eax
0069082D   5A                     pop     edx
0069082E   59                     pop     ecx
0069082F   59                     pop     ecx
00690830   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-Èì}'
|
00690833   6840086900             push    $00690840
00690838   C3                     ret


* Reference to: System.@HandleFinally;
|
00690839   E9FA44D7FF             jmp     00404D38
0069083E   EBF8                   jmp     00690838

****** END
|
00690840   5D                     pop     ebp
00690841   C3                     ret

*)
end;

procedure TfrmAbre._PROC_00690844(Sender : TObject);
begin
(*
00690844   832DC8EC7D0001         sub     dword ptr [$007DECC8], +$01
0069084B   C3                     ret

*)
end;

procedure TfrmAbre._PROC_0069084C(Sender : TObject);
begin
(*
0069084C   98                     cwde 
0069084D   086900                 or      [ecx+$00], ch
00690850   0000                   add     [eax], al

*)
end;

procedure TfrmAbre._PROC_00690B2F(Sender : TObject);
begin
(*
00690B2F   6C                     insb
00690B30   7441                   jz      00690B73
00690B32   7465                   jz      00690B99
00690B34   6E                     outsb
00690B35   646803000001           push    $01000003
00690B3B   0009                   add     [ecx], cl
00690B3D   6C                     insb
00690B3E   624E75                 bound   ecx, qword ptr [esi+$75]
00690B41   6D                     insd
00690B42   50                     push    eax
00690B43   657373                 jnb     00690BB9
00690B46   6C                     insb
00690B47   0300                   add     eax, [eax]
00690B49   0003                   add     [ebx], al
00690B4B   000C45644E756D         add     [$6D754E64+eax*2], cl
00690B52   50                     push    eax
00690B53   657373                 jnb     00690BC9
00690B56   6F                     outsd
00690B57   61                     popa
00690B58   7306                   jnb     00690B60
00690B5A   0016                   add     [esi], dl
00690B5C   009C1869000F62         add     [eax+ebx+$620F0069], bl
00690B63   7443                   jz      00690BA8
00690B65   61                     popa
00690B66   6E                     outsb
00690B67   63656C                 arpl    [ebp+$6C], sp
00690B6A   61                     popa
00690B6B   7243                   jb      00690BB0
00690B6D   6C                     insb
00690B6E   69636B1F00EC18         imul    esp, [ebx+$6B], $18EC001F
00690B75   690018646267           imul    eax, [eax], $67626418
00690B7B   4D                     dec     ebp
00690B7C   657361                 jnb     00690BE0
00690B7F   49                     dec     ecx
00690B80   7465                   jz      00690BE7
00690B82   6D                     insd
00690B83   47                     inc     edi
00690B84   657443                 jz      00690BCA
00690B87   656C                   insb
00690B89   6C                     insb
00690B8A   50                     push    eax
00690B8B   61                     popa
00690B8C   7261                   jb      00690BEF
00690B8E   6D                     insd
00690B8F   7317                   jnb     00690BA8
00690B91   00241A                 add     [edx+ebx], ah
00690B94   69001065644E           imul    eax, [eax], $4E646510
00690B9A   756D                   jnz     00690C09
00690B9C   49                     dec     ecx
00690B9D   7465                   jz      00690C04
00690B9F   6D                     insd
00690BA0   4B                     dec     ebx
00690BA1   657944                 jns     00690BE8
00690BA4   6F                     outsd
00690BA5   776E                   jnbe    00690C15
00690BA7   1A00                   sbb     al, byte ptr [eax]
00690BA9   44                     inc     esp
00690BAA   1A6900                 sbb     ch, byte ptr [ecx+$00]
00690BAD   13646267               adc     esp, [edx+$67]
00690BB1   4D                     dec     ebp
00690BB2   657361                 jnb     00690C16
00690BB5   49                     dec     ecx
00690BB6   7465                   jz      00690C1D
00690BB8   6D                     insd
00690BB9   44                     inc     esp
00690BBA   626C436C               bound   ebp, qword ptr [ebx+eax*2+$6C]
00690BBE   69636B14000C21         imul    esp, [ebx+$6B], $210C0014
00690BC5   69000D627444           imul    eax, [eax], $4474620D
00690BCB   657366                 jnb     00690C34
00690BCE   61                     popa
00690BCF   7A43                   jp      00690C14
00690BD1   6C                     insb
00690BD2   69636B1B005C21         imul    esp, [ebx+$6B], $215C001B
00690BD9   690014646267           imul    eax, [eax], $67626414
00690BDF   4D                     dec     ebp
00690BE0   657361                 jnb     00690C44
00690BE3   49                     dec     ecx
00690BE4   7465                   jz      00690C4B
00690BE6   6D                     insd
00690BE7   43                     inc     ebx
00690BE8   656C                   insb
00690BEA   6C                     insb
00690BEB   43                     inc     ebx
00690BEC   6C                     insb
00690BED   69636B12546672         imul    esp, [ebx+$6B], $72665412
00690BF4   6D                     insd
00690BF5   43                     inc     ebx
00690BF6   61                     popa
00690BF7   6E                     outsb
00690BF8   63656C                 arpl    [ebp+$6C], sp
00690BFB   61                     popa
00690BFC   50                     push    eax
00690BFD   726F                   jb      00690C6E
00690BFF   647574                 jnz     00690C76
00690C02   6F                     outsd
00690C03   07                     pop     es
00690C04   00A0DB5C0004           add     [eax+$4005CDB], ah
00690C0A   F4                     hlt
00690C0B   47                     inc     edi
00690C0C   0088564400A0           add     [eax+$A0004456], cl
00690C12   FC                     cld
00690C13   47                     inc     edi
00690C14   0070CF                 add     [eax-$31], dh
00690C17   44                     inc     esp
00690C18   00DC                   add     ah, bl
00690C1A   51                     push    ecx
00690C1B   44                     inc     esp
00690C1C   005C4244               add     [edx+eax*2+$44], bl
00690C20   008D4000280C           add     [ebp+$C280040], cl
00690C26   690007125466           imul    eax, [eax], $66541207
00690C2C   726D                   jb      00690C9B
00690C2E   43                     inc     ebx
00690C2F   61                     popa
00690C30   6E                     outsb
00690C31   63656C                 arpl    [ebp+$6C], sp
00690C34   61                     popa
00690C35   50                     push    eax
00690C36   726F                   jb      00690CA7
00690C38   647574                 jnz     00690CAF
00690C3B   6F                     outsd
00690C3C   98                     cwde 
00690C3D   086900                 or      [ecx+$00], ch
00690C40   38B44A005E0008         cmp     [edx+ecx*2+$8005E00], dh
00690C47   43                     inc     ebx
00690C48   61                     popa
00690C49   6E                     outsb
00690C4A   635072                 arpl    [eax+$72], dx
00690C4D   6F                     outsd
00690C4E   640000                 add     fs:[eax], al
00690C51   8D4000                 lea     eax, [eax+$00]
00690C54   55                     push    ebp
00690C55   8BEC                   mov     ebp, esp
00690C57   B906000000             mov     ecx, $00000006
00690C5C   6A00                   push    $00
00690C5E   6A00                   push    $00
00690C60   49                     dec     ecx
00690C61   75F9                   jnz     00690C5C
00690C63   53                     push    ebx
00690C64   56                     push    esi
00690C65   57                     push    edi
00690C66   8945FC                 mov     [ebp-$04], eax
00690C69   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00690C6C   E8DB4CD7FF             call    0040594C
00690C71   33C0                   xor     eax, eax
00690C73   55                     push    ebp

* Possible String Reference to: 'é]=×ÿëãŠEû_^[‹å]Ã'
|
00690C74   68D60F6900             push    $00690FD6

***** TRY
|
00690C79   64FF30                 push    dword ptr fs:[eax]
00690C7C   648920                 mov     fs:[eax], esp
00690C7F   C645FB00               mov     byte ptr [ebp-$05], $00
00690C83   33C9                   xor     ecx, ecx
00690C85   B201                   mov     dl, $01

* Reference to class TfrmCancelaProduto
|
00690C87   A14C086900             mov     eax, dword ptr [$0069084C]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
00690C8C   E87FD2E1FF             call    004ADF10

* Reference to GlobalVar_007DECCC
|
00690C91   A3CCEC7D00             mov     dword ptr [$007DECCC], eax
00690C96   33D2                   xor     edx, edx
00690C98   55                     push    ebp
00690C99   68AC0F6900             push    $00690FAC

***** TRY
|
00690C9E   64FF32                 push    dword ptr fs:[edx]
00690CA1   648922                 mov     fs:[edx], esp
00690CA4   33D2                   xor     edx, edx
00690CA6   55                     push    ebp
00690CA7   68590F6900             push    $00690F59

***** TRY
|
00690CAC   64FF32                 push    dword ptr fs:[edx]
00690CAF   648922                 mov     fs:[edx], esp
00690CB2   8B45FC                 mov     eax, [ebp-$04]

|
00690CB5   E8665A1200             call    007B6720
00690CBA   83F804                 cmp     eax, +$04
00690CBD   0F878C020000           jnbe    00690F4F
00690CC3   FF2485CA0C6900         jmp     dword ptr [$690CCA+eax*4]
00690CCA   DE0C69                 fimul   word ptr [ecx+ebp*2]
00690CCD   00F5                   add     ch, dh
00690CCF   0E                     push    cs
00690CD0   69000C0F6900           imul    eax, [eax], $00690F0C
00690CD6   230F                   and     ecx, [edi]
00690CD8   69003A0F6900           imul    eax, [eax], $00690F3A
00690CDE   8B55FC                 mov     edx, [ebp-$04]
00690CE1   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]

|
00690CE6   E85D050000             call    00691248
00690CEB   84C0                   test    al, al
00690CED   0F845C020000           jz      00690F4F
00690CF3   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690CF8   8B00                   mov     eax, [eax]
00690CFA   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CODMESA'
|
00690CFD   BAF00F6900             mov     edx, $00690FF0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690D02   E8FD8EE5FF             call    004E9C04
00690D07   8B10                   mov     edx, [eax]
00690D09   FF5258                 call    dword ptr [edx+$58]

* Reference to GlobalVar_007DECD0
|
00690D0C   A3D0EC7D00             mov     dword ptr [$007DECD0], eax
00690D11   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690D16   8B00                   mov     eax, [eax]
00690D18   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'NUMLCTO'
|
00690D1B   BA00106900             mov     edx, $00691000

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690D20   E8DF8EE5FF             call    004E9C04
00690D25   8B10                   mov     edx, [eax]
00690D27   FF5258                 call    dword ptr [edx+$58]

* Reference to GlobalVar_007DECD4
|
00690D2A   A3D4EC7D00             mov     dword ptr [$007DECD4], eax
00690D2F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690D34   8B00                   mov     eax, [eax]
00690D36   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CODMESA'
|
00690D39   BAF00F6900             mov     edx, $00690FF0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690D3E   E8C18EE5FF             call    004E9C04
00690D43   8D55F4                 lea     edx, [ebp-$0C]
00690D46   8B08                   mov     ecx, [eax]
00690D48   FF5160                 call    dword ptr [ecx+$60]
00690D4B   8B55F4                 mov     edx, [ebp-$0C]
00690D4E   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690D53   8B8044030000           mov     eax, [eax+$0344]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690D59   E89E29E0FF             call    004936FC
00690D5E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690D63   8B00                   mov     eax, [eax]
00690D65   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'DATAINI'
|
00690D68   BA10106900             mov     edx, $00691010

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690D6D   E8928EE5FF             call    004E9C04
00690D72   8B10                   mov     edx, [eax]
00690D74   FF5250                 call    dword ptr [edx+$50]
00690D77   83C4F8                 add     esp, -$08
00690D7A   DD1C24                 fstp    qword ptr [esp]
00690D7D   9B                     wait
00690D7E   8D55F0                 lea     edx, [ebp-$10]

* Possible String Reference to: 'hh:mm'
|
00690D81   B820106900             mov     eax, $00691020

|
00690D86   E84DDBD7FF             call    0040E8D8
00690D8B   8B55F0                 mov     edx, [ebp-$10]
00690D8E   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690D93   8B805C030000           mov     eax, [eax+$035C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690D99   E85E29E0FF             call    004936FC
00690D9E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690DA3   8B00                   mov     eax, [eax]
00690DA5   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'DATAFIM'
|
00690DA8   BA30106900             mov     edx, $00691030

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690DAD   E8528EE5FF             call    004E9C04
00690DB2   8B10                   mov     edx, [eax]
00690DB4   FF5250                 call    dword ptr [edx+$50]
00690DB7   83C4F8                 add     esp, -$08
00690DBA   DD1C24                 fstp    qword ptr [esp]
00690DBD   9B                     wait
00690DBE   8D55EC                 lea     edx, [ebp-$14]

* Possible String Reference to: 'hh:mm'
|
00690DC1   B820106900             mov     eax, $00691020

|
00690DC6   E80DDBD7FF             call    0040E8D8
00690DCB   8B55EC                 mov     edx, [ebp-$14]
00690DCE   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690DD3   8B8064030000           mov     eax, [eax+$0364]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690DD9   E81E29E0FF             call    004936FC
00690DDE   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690DE3   8B00                   mov     eax, [eax]
00690DE5   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'RAZAO'
|
00690DE8   BA40106900             mov     edx, $00691040

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690DED   E8128EE5FF             call    004E9C04
00690DF2   8D55E8                 lea     edx, [ebp-$18]
00690DF5   8B08                   mov     ecx, [eax]
00690DF7   FF5160                 call    dword ptr [ecx+$60]
00690DFA   8B55E8                 mov     edx, [ebp-$18]
00690DFD   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690E02   8B804C030000           mov     eax, [eax+$034C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690E08   E8EF28E0FF             call    004936FC

* Possible String Reference to: 'NOME'
|
00690E0D   6850106900             push    $00691050
00690E12   8D45E4                 lea     eax, [ebp-$1C]
00690E15   50                     push    eax
00690E16   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690E1B   8B00                   mov     eax, [eax]
00690E1D   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CODFUNC'
|
00690E20   BA60106900             mov     edx, $00691060

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690E25   E8DA8DE5FF             call    004E9C04
00690E2A   8D55D8                 lea     edx, [ebp-$28]
00690E2D   8B08                   mov     ecx, [eax]
00690E2F   FF5160                 call    dword ptr [ecx+$60]
00690E32   8B45D8                 mov     eax, [ebp-$28]
00690E35   8D55DC                 lea     edx, [ebp-$24]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
00690E38   E8E32C1100             call    007A3B20
00690E3D   8B4DDC                 mov     ecx, [ebp-$24]
00690E40   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: 'CODFUNC = '
|
00690E43   BA70106900             mov     edx, $00691070

* Reference to: System.@LStrCat3;
|
00690E48   E85B49D7FF             call    004057A8
00690E4D   8B4DE0                 mov     ecx, [ebp-$20]

* Possible String Reference to: 'FUNCREPR'
|
00690E50   BA84106900             mov     edx, $00691084
00690E55   33C0                   xor     eax, eax

|
00690E57   E8B4841100             call    007A9310
00690E5C   8B55E4                 mov     edx, [ebp-$1C]
00690E5F   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690E64   8B8054030000           mov     eax, [eax+$0354]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690E6A   E88D28E0FF             call    004936FC
00690E6F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00690E74   8B00                   mov     eax, [eax]
00690E76   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'NUMPESSOAS'
|
00690E79   BA98106900             mov     edx, $00691098

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00690E7E   E8818DE5FF             call    004E9C04
00690E83   8D55D4                 lea     edx, [ebp-$2C]
00690E86   8B08                   mov     ecx, [eax]
00690E88   FF5160                 call    dword ptr [ecx+$60]
00690E8B   8B55D4                 mov     edx, [ebp-$2C]
00690E8E   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690E93   8B806C030000           mov     eax, [eax+$036C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00690E99   E85E28E0FF             call    004936FC
00690E9E   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]

|
00690EA3   E864070000             call    0069160C
00690EA8   BA03000000             mov     edx, $00000003
00690EAD   8B45FC                 mov     eax, [ebp-$04]

|
00690EB0   E8BF561200             call    007B6574
00690EB5   33C0                   xor     eax, eax
00690EB7   55                     push    ebp
00690EB8   68E80E6900             push    $00690EE8

***** TRY
|
00690EBD   64FF30                 push    dword ptr fs:[eax]
00690EC0   648920                 mov     fs:[eax], esp
00690EC3   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]
00690EC8   8B10                   mov     edx, [eax]
00690ECA   FF92EC000000           call    dword ptr [edx+$00EC]
00690ED0   33C0                   xor     eax, eax
00690ED2   5A                     pop     edx
00690ED3   59                     pop     ecx
00690ED4   59                     pop     ecx
00690ED5   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690ED8   68EF0E6900             push    $00690EEF
00690EDD   33D2                   xor     edx, edx
00690EDF   8B45FC                 mov     eax, [ebp-$04]

|
00690EE2   E88D561200             call    007B6574
00690EE7   C3                     ret


* Reference to: System.@HandleFinally;
|
00690EE8   E94B3ED7FF             jmp     00404D38
00690EED   EBEE                   jmp     00690EDD

****** END
|
00690EEF   C645FB01               mov     byte ptr [ebp-$05], $01
00690EF3   EB5A                   jmp     00690F4F
00690EF5   6A00                   push    $00
00690EF7   668B0DA4106900         mov     cx, word ptr [$006910A4]
00690EFE   33D2                   xor     edx, edx

* Possible String Reference to: 'Não é possivel cancelar itens porqu
|                                e outro terminal ja está adicionand
|                                o itens!'
|
00690F00   B8B0106900             mov     eax, $006910B0

|
00690F05   E8222CDBFF             call    00443B2C
00690F0A   EB43                   jmp     00690F4F
00690F0C   6A00                   push    $00
00690F0E   668B0DA4106900         mov     cx, word ptr [$006910A4]
00690F15   33D2                   xor     edx, edx

* Possible String Reference to: 'Não é possivel cancelar itens porqu
|                                e outro terminal está transferindo 
|                                itens dessa mesa!'
|
00690F17   B808116900             mov     eax, $00691108

|
00690F1C   E80B2CDBFF             call    00443B2C
00690F21   EB2C                   jmp     00690F4F
00690F23   6A00                   push    $00
00690F25   668B0DA4106900         mov     cx, word ptr [$006910A4]
00690F2C   33D2                   xor     edx, edx

* Possible String Reference to: 'Não é possivel cancelar itens porqu
|                                e outro terminal está cancelando it
|                                ens!'
|
00690F2E   B868116900             mov     eax, $00691168

|
00690F33   E8F42BDBFF             call    00443B2C
00690F38   EB15                   jmp     00690F4F
00690F3A   6A00                   push    $00
00690F3C   668B0DA4106900         mov     cx, word ptr [$006910A4]
00690F43   33D2                   xor     edx, edx

* Possible String Reference to: 'Não é possivel cancelar itens porqu
|                                e outro terminal está fechando a me
|                                sa!'
|
00690F45   B8BC116900             mov     eax, $006911BC

|
00690F4A   E8DD2BDBFF             call    00443B2C
00690F4F   33C0                   xor     eax, eax
00690F51   5A                     pop     edx
00690F52   59                     pop     ecx
00690F53   59                     pop     ecx
00690F54   648910                 mov     fs:[eax], edx
00690F57   EB3B                   jmp     00690F94

* Reference to: System.@HandleOnException;
|
00690F59   E9523CD7FF             jmp     00404BB0
00690F5E   0100                   add     [eax], eax
00690F60   0000                   add     [eax], al
00690F62   40                     inc     eax
00690F63   95                     xchg    eax, ebp
00690F64   40                     inc     eax
00690F65   006A0F                 add     [edx+$0F], ch
00690F68   690089C36A00           imul    eax, [eax], $006AC389
00690F6E   8B4B04                 mov     ecx, [ebx+$04]
00690F71   8D45D0                 lea     eax, [ebp-$30]

* Possible String Reference to: 'Ocorreu um erro na execução da funç
|                                ão CancProduto.'
|
00690F74   BA10126900             mov     edx, $00691210

* Reference to: System.@LStrCat3;
|
00690F79   E82A48D7FF             call    004057A8
00690F7E   8B45D0                 mov     eax, [ebp-$30]
00690F81   668B0DA4106900         mov     cx, word ptr [$006910A4]
00690F88   B201                   mov     dl, $01

|
00690F8A   E89D2BDBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
00690F8F   E81C3FD7FF             call    00404EB0

****** END
|
00690F94   33C0                   xor     eax, eax
00690F96   5A                     pop     edx
00690F97   59                     pop     ecx
00690F98   59                     pop     ecx
00690F99   648910                 mov     fs:[eax], edx

****** FINALLY
|
00690F9C   68B30F6900             push    $00690FB3
00690FA1   A1CCEC7D00             mov     eax, dword ptr [$007DECCC]

* Reference to: System.TObject.Free(TObject);
|
00690FA6   E8F135D7FF             call    0040459C
00690FAB   C3                     ret


* Reference to: System.@HandleFinally;
|
00690FAC   E9873DD7FF             jmp     00404D38
00690FB1   EBEE                   jmp     00690FA1

****** END
|
00690FB3   33C0                   xor     eax, eax
00690FB5   5A                     pop     edx
00690FB6   59                     pop     ecx
00690FB7   59                     pop     ecx
00690FB8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ŠEû_^[‹å]Ã'
|
00690FBB   68DD0F6900             push    $00690FDD
00690FC0   8D45D0                 lea     eax, [ebp-$30]
00690FC3   BA0A000000             mov     edx, $0000000A

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00690FC8   E8F344D7FF             call    004054C0
00690FCD   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00690FD0   E8C744D7FF             call    0040549C
00690FD5   C3                     ret


* Reference to: System.@HandleFinally;
|
00690FD6   E95D3DD7FF             jmp     00404D38
00690FDB   EBE3                   jmp     00690FC0

****** END
|
00690FDD   8A45FB                 mov     al, byte ptr [ebp-$05]
00690FE0   5F                     pop     edi
00690FE1   5E                     pop     esi
00690FE2   5B                     pop     ebx
00690FE3   8BE5                   mov     esp, ebp
00690FE5   5D                     pop     ebp
00690FE6   C3                     ret

*)
end;

end.