unit acrescim;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ToolEdit, CurrEdit, ExtCtrls,
  Buttons;
  
type
  TFrmAcrescimo=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    nbAcrescimo: TNotebook;
    Panel2: TPanel;
    Panel3: TPanel;
    Label5: TLabel;
    EdVlrCupom: TCurrencyEdit;
    Panel4: TPanel;
    Panel5: TPanel;
    Label6: TLabel;
    EdVlrItem: TCurrencyEdit;
    pnCupomPorc: TPanel;
    Label10: TLabel;
    EdPorcAC: TCurrencyEdit;
    pnCupomVlr: TPanel;
    Label9: TLabel;
    EdValorAC: TCurrencyEdit;
    Label3: TLabel;
    EdNovoValor: TCurrencyEdit;
    EdValorAtual: TCurrencyEdit;
    Label4: TLabel;
    sbCupomPorc: TSpeedButton;
    sbCupomValor: TSpeedButton;
    sbItemPorc: TSpeedButton;
    sbItemValor: TSpeedButton;
    pnItemVlr: TPanel;
    Label1: TLabel;
    EdValorAI: TCurrencyEdit;
    pnItemPorc: TPanel;
    Label2: TLabel;
    EdPorcAI: TCurrencyEdit;
    Bevel1: TBevel;
    EdValorAcrescimo: TCurrencyEdit;
    Label7: TLabel;
    procedure sbCupomPorcClick(Sender : TObject);
    procedure sbCupomValorClick(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sbItemPorcClick(Sender : TObject);
    procedure sbItemValorClick(Sender : TObject);
    procedure EdValorACChange(Sender : TObject);
    procedure EdPorcAIChange(Sender : TObject);
    procedure EdValorAIChange(Sender : TObject);
    procedure EdPorcACChange(Sender : TObject);
    procedure EdPorcACKeyPress(Sender : TObject);
    procedure EdValorAIKeyPress(Sender : TObject);
    procedure _PROC_006B7C99(Sender : TObject);
    procedure _PROC_006B7EA5(Sender : TObject);
    procedure _PROC_006B8041(Sender : TObject);
    procedure _PROC_006B8451(Sender : TObject);
    procedure _PROC_006B8815(Sender : TObject);
    procedure _PROC_006B8930(Sender : TObject);
    procedure _PROC_006B8974(Sender : TObject);
    procedure _PROC_006B897C(Sender : TObject);
    procedure _PROC_006B89F1(Sender : TObject);
    procedure _PROC_006B8D25(Sender : TObject);
    procedure _PROC_006B8D54(Sender : TObject);
    procedure _PROC_006B8D5C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAcrescimo: TFrmAcrescimo;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAcrescimo.sbCupomPorcClick(Sender : TObject);
begin
(*
006B8090   55                     push    ebp
006B8091   8BEC                   mov     ebp, esp
006B8093   53                     push    ebx
006B8094   8BD8                   mov     ebx, eax
006B8096   33C0                   xor     eax, eax
006B8098   890598ED7D00           mov     [$007DED98], eax
006B809E   89059CED7D00           mov     [$007DED9C], eax
006B80A4   668905A0ED7D00         mov     [$007DEDA0], ax
006B80AB   33C0                   xor     eax, eax
006B80AD   8905A4ED7D00           mov     [$007DEDA4], eax
006B80B3   8905A8ED7D00           mov     [$007DEDA8], eax
006B80B9   668905ACED7D00         mov     [$007DEDAC], ax
006B80C0   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'porc'
|
006B80C5   BA74816B00             mov     edx, $006B8174

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B80CA   E821D4D4FF             call    004054F0
006B80CF   33D2                   xor     edx, edx

* Reference to control TFrmAcrescimo.pnCupomVlr : TPanel
|
006B80D1   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B80D7   E810B5DDFF             call    004935EC
006B80DC   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomVlr : TPanel
|
006B80E1   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B80E7   E84CADDDFF             call    00492E38
006B80EC   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.pnCupomPorc : TPanel
|
006B80EE   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B80F4   E8F3B4DDFF             call    004935EC
006B80F9   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomPorc : TPanel
|
006B80FE   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B8104   E82FADDDFF             call    00492E38

* Reference to control TFrmAcrescimo.EdPorcAC : TCurrencyEdit
|
006B8109   8B832C030000           mov     eax, [ebx+$032C]
006B810F   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
006B8111   FF92C4000000           call    dword ptr [edx+$00C4]
006B8117   A108AF7D00             mov     eax, dword ptr [$007DAF08]
006B811C   803800                 cmp     byte ptr [eax], $00
006B811F   7417                   jz      006B8138
006B8121   6805400000             push    $00004005
006B8126   68000000C8             push    $C8000000
006B812B   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdPorcAC : TCurrencyEdit
|
006B812D   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B8133   E82811F7FF             call    00629260
006B8138   6A00                   push    $00
006B813A   6A00                   push    $00
006B813C   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdValorAcrescimo : TCurrencyEdit
|
006B813E   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8144   E87710F7FF             call    006291C0

* Reference to control TFrmAcrescimo.EdValorAtual : TCurrencyEdit
|
006B8149   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B814F   E8D40FF7FF             call    00629128
006B8154   83C4F4                 add     esp, -$0C
006B8157   DB3C24                 fstp    tbyte ptr [esp]
006B815A   9B                     wait

* Reference to control TFrmAcrescimo.EdNovoValor : TCurrencyEdit
|
006B815B   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8161   E85A10F7FF             call    006291C0
006B8166   5B                     pop     ebx
006B8167   5D                     pop     ebp
006B8168   C3                     ret

*)
end;

procedure TFrmAcrescimo.sbCupomValorClick(Sender : TObject);
begin
(*
006B817C   55                     push    ebp
006B817D   8BEC                   mov     ebp, esp
006B817F   53                     push    ebx
006B8180   8BD8                   mov     ebx, eax
006B8182   33C0                   xor     eax, eax
006B8184   890598ED7D00           mov     [$007DED98], eax
006B818A   89059CED7D00           mov     [$007DED9C], eax
006B8190   668905A0ED7D00         mov     [$007DEDA0], ax
006B8197   33C0                   xor     eax, eax
006B8199   8905A4ED7D00           mov     [$007DEDA4], eax
006B819F   8905A8ED7D00           mov     [$007DEDA8], eax
006B81A5   668905ACED7D00         mov     [$007DEDAC], ax
006B81AC   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'valor'
|
006B81B1   BA60826B00             mov     edx, $006B8260

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B81B6   E835D3D4FF             call    004054F0
006B81BB   33D2                   xor     edx, edx

* Reference to control TFrmAcrescimo.pnCupomPorc : TPanel
|
006B81BD   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B81C3   E824B4DDFF             call    004935EC
006B81C8   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomPorc : TPanel
|
006B81CD   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B81D3   E860ACDDFF             call    00492E38
006B81D8   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.pnCupomVlr : TPanel
|
006B81DA   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B81E0   E807B4DDFF             call    004935EC
006B81E5   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomVlr : TPanel
|
006B81EA   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B81F0   E843ACDDFF             call    00492E38

* Reference to control TFrmAcrescimo.EdValorAC : TCurrencyEdit
|
006B81F5   8B8338030000           mov     eax, [ebx+$0338]
006B81FB   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
006B81FD   FF92C4000000           call    dword ptr [edx+$00C4]
006B8203   A108AF7D00             mov     eax, dword ptr [$007DAF08]
006B8208   803800                 cmp     byte ptr [eax], $00
006B820B   741A                   jz      006B8227
006B820D   A150B67D00             mov     eax, dword ptr [$007DB650]
006B8212   668B5008               mov     dx, word ptr [eax+$08]
006B8216   52                     push    edx
006B8217   FF7004                 push    dword ptr [eax+$04]
006B821A   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAC : TCurrencyEdit
|
006B821C   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B8222   E83910F7FF             call    00629260
006B8227   6A00                   push    $00
006B8229   6A00                   push    $00
006B822B   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdValorAcrescimo : TCurrencyEdit
|
006B822D   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8233   E8880FF7FF             call    006291C0

* Reference to control TFrmAcrescimo.EdValorAtual : TCurrencyEdit
|
006B8238   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B823E   E8E50EF7FF             call    00629128
006B8243   83C4F4                 add     esp, -$0C
006B8246   DB3C24                 fstp    tbyte ptr [esp]
006B8249   9B                     wait

* Reference to control TFrmAcrescimo.EdNovoValor : TCurrencyEdit
|
006B824A   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8250   E86B0FF7FF             call    006291C0
006B8255   5B                     pop     ebx
006B8256   5D                     pop     ebp
006B8257   C3                     ret

*)
end;

procedure TFrmAcrescimo.FormCreate(Sender : TObject);
begin
(*
006B8268   55                     push    ebp
006B8269   8BEC                   mov     ebp, esp
006B826B   53                     push    ebx
006B826C   8BD8                   mov     ebx, eax
006B826E   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomPorc : TPanel
|
006B8273   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B8279   E8BAABDDFF             call    00492E38
006B827E   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnCupomVlr : TPanel
|
006B8283   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B8289   E8AAABDDFF             call    00492E38
006B828E   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B8293   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B8299   E89AABDDFF             call    00492E38
006B829E   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B82A3   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B82A9   E88AABDDFF             call    00492E38
006B82AE   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmAcrescimo.sbCupomPorc : TSpeedButton
|
006B82B3   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B82B9   E87AABDDFF             call    00492E38
006B82BE   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmAcrescimo.sbCupomValor : TSpeedButton
|
006B82C3   8B8350030000           mov     eax, [ebx+$0350]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B82C9   E86AABDDFF             call    00492E38
006B82CE   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmAcrescimo.sbItemPorc : TSpeedButton
|
006B82D3   8B8354030000           mov     eax, [ebx+$0354]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B82D9   E85AABDDFF             call    00492E38
006B82DE   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmAcrescimo.sbItemValor : TSpeedButton
|
006B82E3   8B8358030000           mov     eax, [ebx+$0358]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B82E9   E84AABDDFF             call    00492E38
006B82EE   A108AF7D00             mov     eax, dword ptr [$007DAF08]
006B82F3   803800                 cmp     byte ptr [eax], $00
006B82F6   7462                   jz      006B835A
006B82F8   6805400000             push    $00004005
006B82FD   68000000C8             push    $C8000000
006B8302   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdPorcAI : TCurrencyEdit
|
006B8304   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B830A   E8510FF7FF             call    00629260
006B830F   6805400000             push    $00004005
006B8314   68000000C8             push    $C8000000
006B8319   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdPorcAC : TCurrencyEdit
|
006B831B   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B8321   E83A0FF7FF             call    00629260
006B8326   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B832B   668B5008               mov     dx, word ptr [eax+$08]
006B832F   52                     push    edx
006B8330   FF7004                 push    dword ptr [eax+$04]
006B8333   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAI : TCurrencyEdit
|
006B8335   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B833B   E8200FF7FF             call    00629260
006B8340   A150B67D00             mov     eax, dword ptr [$007DB650]
006B8345   668B5008               mov     dx, word ptr [eax+$08]
006B8349   52                     push    edx
006B834A   FF7004                 push    dword ptr [eax+$04]
006B834D   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAC : TCurrencyEdit
|
006B834F   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B8355   E8060FF7FF             call    00629260
006B835A   5B                     pop     ebx
006B835B   5D                     pop     ebp
006B835C   C3                     ret

*)
end;

procedure TFrmAcrescimo.FormShow(Sender : TObject);
begin
(*
006B8360   55                     push    ebp
006B8361   8BEC                   mov     ebp, esp
006B8363   53                     push    ebx
006B8364   8BD8                   mov     ebx, eax
006B8366   A168897D00             mov     eax, dword ptr [$007D8968]

* Possible String Reference to: 'item'
|
006B836B   BA60856B00             mov     edx, $006B8560

* Reference to: System.@LStrCmp;
|
006B8370   E833D5D4FF             call    004058A8
006B8375   0F85D6000000           jnz     006B8451
006B837B   B868897D00             mov     eax, $007D8968

* Possible String Reference to: 'item'
|
006B8380   BA60856B00             mov     edx, $006B8560

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B8385   E866D1D4FF             call    004054F0
006B838A   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'porc'
|
006B838F   BA70856B00             mov     edx, $006B8570

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B8394   E857D1D4FF             call    004054F0
006B8399   33C0                   xor     eax, eax
006B839B   890598ED7D00           mov     [$007DED98], eax
006B83A1   89059CED7D00           mov     [$007DED9C], eax
006B83A7   668905A0ED7D00         mov     [$007DEDA0], ax
006B83AE   33C0                   xor     eax, eax
006B83B0   8905A4ED7D00           mov     [$007DEDA4], eax
006B83B6   8905A8ED7D00           mov     [$007DEDA8], eax
006B83BC   668905ACED7D00         mov     [$007DEDAC], ax
006B83C3   BA01000000             mov     edx, $00000001

* Reference to control TFrmAcrescimo.nbAcrescimo : TNotebook
|
006B83C8   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: ExtCtrls.TNotebook.SetPageIndex(TNotebook;Integer);
|
006B83CE   E87112D9FF             call    00449644
006B83D3   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B83D5   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B83DB   E80CB2DDFF             call    004935EC

* Reference to control TFrmAcrescimo.EdPorcAI : TCurrencyEdit
|
006B83E0   8B8370030000           mov     eax, [ebx+$0370]
006B83E6   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
006B83E8   FF92C4000000           call    dword ptr [edx+$00C4]
006B83EE   33D2                   xor     edx, edx

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B83F0   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B83F6   E8F1B1DDFF             call    004935EC
006B83FB   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B8400   668B5008               mov     dx, word ptr [eax+$08]
006B8404   52                     push    edx
006B8405   FF7004                 push    dword ptr [eax+$04]
006B8408   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdVlrItem : TCurrencyEdit
|
006B840A   8B8320030000           mov     eax, [ebx+$0320]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8410   E8AB0DF7FF             call    006291C0
006B8415   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B841A   668B5008               mov     dx, word ptr [eax+$08]
006B841E   52                     push    edx
006B841F   FF7004                 push    dword ptr [eax+$04]
006B8422   FF30                   push    dword ptr [eax]
006B8424   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B8429   668B5008               mov     dx, word ptr [eax+$08]
006B842D   52                     push    edx
006B842E   FF7004                 push    dword ptr [eax+$04]
006B8431   FF30                   push    dword ptr [eax]
006B8433   668B05ACED7D00         mov     ax, word ptr [$007DEDAC]
006B843A   50                     push    eax
006B843B   FF35A8ED7D00           push    dword ptr [$007DEDA8]
006B8441   FF35A4ED7D00           push    dword ptr [$007DEDA4]
006B8447   8BC3                   mov     eax, ebx

|
006B8449   E8F2FBFFFF             call    006B8040
006B844E   5B                     pop     ebx
006B844F   5D                     pop     ebp
006B8450   C3                     ret

*)
end;

procedure TFrmAcrescimo.sbItemPorcClick(Sender : TObject);
begin
(*
006B8588   55                     push    ebp
006B8589   8BEC                   mov     ebp, esp
006B858B   53                     push    ebx
006B858C   8BD8                   mov     ebx, eax
006B858E   33C0                   xor     eax, eax
006B8590   890598ED7D00           mov     [$007DED98], eax
006B8596   89059CED7D00           mov     [$007DED9C], eax
006B859C   668905A0ED7D00         mov     [$007DEDA0], ax
006B85A3   33C0                   xor     eax, eax
006B85A5   8905A4ED7D00           mov     [$007DEDA4], eax
006B85AB   8905A8ED7D00           mov     [$007DEDA8], eax
006B85B1   668905ACED7D00         mov     [$007DEDAC], ax
006B85B8   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'porc'
|
006B85BD   BA48866B00             mov     edx, $006B8648

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B85C2   E829CFD4FF             call    004054F0
006B85C7   33D2                   xor     edx, edx

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B85C9   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B85CF   E818B0DDFF             call    004935EC
006B85D4   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B85D9   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B85DF   E854A8DDFF             call    00492E38
006B85E4   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B85E6   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B85EC   E8FBAFDDFF             call    004935EC
006B85F1   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B85F6   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B85FC   E837A8DDFF             call    00492E38

* Reference to control TFrmAcrescimo.EdPorcAI : TCurrencyEdit
|
006B8601   8B8370030000           mov     eax, [ebx+$0370]
006B8607   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
006B8609   FF92C4000000           call    dword ptr [edx+$00C4]
006B860F   6A00                   push    $00
006B8611   6A00                   push    $00
006B8613   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdValorAcrescimo : TCurrencyEdit
|
006B8615   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B861B   E8A00BF7FF             call    006291C0

* Reference to control TFrmAcrescimo.EdValorAtual : TCurrencyEdit
|
006B8620   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B8626   E8FD0AF7FF             call    00629128
006B862B   83C4F4                 add     esp, -$0C
006B862E   DB3C24                 fstp    tbyte ptr [esp]
006B8631   9B                     wait

* Reference to control TFrmAcrescimo.EdNovoValor : TCurrencyEdit
|
006B8632   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8638   E8830BF7FF             call    006291C0
006B863D   5B                     pop     ebx
006B863E   5D                     pop     ebp
006B863F   C3                     ret

*)
end;

procedure TFrmAcrescimo.sbItemValorClick(Sender : TObject);
begin
(*
006B8650   55                     push    ebp
006B8651   8BEC                   mov     ebp, esp
006B8653   53                     push    ebx
006B8654   8BD8                   mov     ebx, eax
006B8656   33C0                   xor     eax, eax
006B8658   890598ED7D00           mov     [$007DED98], eax
006B865E   89059CED7D00           mov     [$007DED9C], eax
006B8664   668905A0ED7D00         mov     [$007DEDA0], ax
006B866B   33C0                   xor     eax, eax
006B866D   8905A4ED7D00           mov     [$007DEDA4], eax
006B8673   8905A8ED7D00           mov     [$007DEDA8], eax
006B8679   668905ACED7D00         mov     [$007DEDAC], ax
006B8680   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'valor'
|
006B8685   BA34876B00             mov     edx, $006B8734

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B868A   E861CED4FF             call    004054F0
006B868F   33D2                   xor     edx, edx

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B8691   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B8697   E850AFDDFF             call    004935EC
006B869C   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemPorc : TPanel
|
006B86A1   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B86A7   E88CA7DDFF             call    00492E38
006B86AC   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B86AE   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B86B4   E833AFDDFF             call    004935EC
006B86B9   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmAcrescimo.pnItemVlr : TPanel
|
006B86BE   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006B86C4   E86FA7DDFF             call    00492E38

* Reference to control TFrmAcrescimo.EdValorAI : TCurrencyEdit
|
006B86C9   8B8364030000           mov     eax, [ebx+$0364]
006B86CF   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
006B86D1   FF92C4000000           call    dword ptr [edx+$00C4]
006B86D7   A108AF7D00             mov     eax, dword ptr [$007DAF08]
006B86DC   803800                 cmp     byte ptr [eax], $00
006B86DF   741A                   jz      006B86FB
006B86E1   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B86E6   668B5008               mov     dx, word ptr [eax+$08]
006B86EA   52                     push    edx
006B86EB   FF7004                 push    dword ptr [eax+$04]
006B86EE   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAI : TCurrencyEdit
|
006B86F0   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629260()
|
006B86F6   E8650BF7FF             call    00629260
006B86FB   6A00                   push    $00
006B86FD   6A00                   push    $00
006B86FF   6A00                   push    $00

* Reference to control TFrmAcrescimo.EdValorAcrescimo : TCurrencyEdit
|
006B8701   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8707   E8B40AF7FF             call    006291C0

* Reference to control TFrmAcrescimo.EdValorAtual : TCurrencyEdit
|
006B870C   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B8712   E8110AF7FF             call    00629128
006B8717   83C4F4                 add     esp, -$0C
006B871A   DB3C24                 fstp    tbyte ptr [esp]
006B871D   9B                     wait

* Reference to control TFrmAcrescimo.EdNovoValor : TCurrencyEdit
|
006B871E   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8724   E8970AF7FF             call    006291C0
006B8729   5B                     pop     ebx
006B872A   5D                     pop     ebp
006B872B   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdValorACChange(Sender : TObject);
begin
(*
006B8814   55                     push    ebp
006B8815   8BEC                   mov     ebp, esp
006B8817   53                     push    ebx
006B8818   8BD8                   mov     ebx, eax
006B881A   A150B67D00             mov     eax, dword ptr [$007DB650]
006B881F   668B5008               mov     dx, word ptr [eax+$08]
006B8823   52                     push    edx
006B8824   FF7004                 push    dword ptr [eax+$04]
006B8827   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAC : TCurrencyEdit
|
006B8829   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B882F   E8F408F7FF             call    00629128
006B8834   83C4F4                 add     esp, -$0C
006B8837   DB3C24                 fstp    tbyte ptr [esp]
006B883A   9B                     wait

* Possible String Reference to: 'valor'
|
006B883B   BA54886B00             mov     edx, $006B8854
006B8840   8BC3                   mov     eax, ebx

|
006B8842   E851F4FFFF             call    006B7C98
006B8847   5B                     pop     ebx
006B8848   5D                     pop     ebp
006B8849   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdPorcAIChange(Sender : TObject);
begin
(*
006B873C   55                     push    ebp
006B873D   8BEC                   mov     ebp, esp
006B873F   53                     push    ebx
006B8740   8BD8                   mov     ebx, eax
006B8742   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B8747   668B5008               mov     dx, word ptr [eax+$08]
006B874B   52                     push    edx
006B874C   FF7004                 push    dword ptr [eax+$04]
006B874F   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdPorcAI : TCurrencyEdit
|
006B8751   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B8757   E8CC09F7FF             call    00629128
006B875C   83C4F4                 add     esp, -$0C
006B875F   DB3C24                 fstp    tbyte ptr [esp]
006B8762   9B                     wait

* Possible String Reference to: 'porc'
|
006B8763   BA7C876B00             mov     edx, $006B877C
006B8768   8BC3                   mov     eax, ebx

|
006B876A   E835F7FFFF             call    006B7EA4
006B876F   5B                     pop     ebx
006B8770   5D                     pop     ebp
006B8771   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdValorAIChange(Sender : TObject);
begin
(*
006B8784   55                     push    ebp
006B8785   8BEC                   mov     ebp, esp
006B8787   53                     push    ebx
006B8788   8BD8                   mov     ebx, eax
006B878A   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006B878F   668B5008               mov     dx, word ptr [eax+$08]
006B8793   52                     push    edx
006B8794   FF7004                 push    dword ptr [eax+$04]
006B8797   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAI : TCurrencyEdit
|
006B8799   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B879F   E88409F7FF             call    00629128
006B87A4   83C4F4                 add     esp, -$0C
006B87A7   DB3C24                 fstp    tbyte ptr [esp]
006B87AA   9B                     wait

* Possible String Reference to: 'valor'
|
006B87AB   BAC4876B00             mov     edx, $006B87C4
006B87B0   8BC3                   mov     eax, ebx

|
006B87B2   E8EDF6FFFF             call    006B7EA4
006B87B7   5B                     pop     ebx
006B87B8   5D                     pop     ebp
006B87B9   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdPorcACChange(Sender : TObject);
begin
(*
006B87CC   55                     push    ebp
006B87CD   8BEC                   mov     ebp, esp
006B87CF   53                     push    ebx
006B87D0   8BD8                   mov     ebx, eax
006B87D2   A150B67D00             mov     eax, dword ptr [$007DB650]
006B87D7   668B5008               mov     dx, word ptr [eax+$08]
006B87DB   52                     push    edx
006B87DC   FF7004                 push    dword ptr [eax+$04]
006B87DF   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdPorcAC : TCurrencyEdit
|
006B87E1   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B87E7   E83C09F7FF             call    00629128
006B87EC   83C4F4                 add     esp, -$0C
006B87EF   DB3C24                 fstp    tbyte ptr [esp]
006B87F2   9B                     wait

* Possible String Reference to: 'porc'
|
006B87F3   BA0C886B00             mov     edx, $006B880C
006B87F8   8BC3                   mov     eax, ebx

|
006B87FA   E899F4FFFF             call    006B7C98
006B87FF   5B                     pop     ebx
006B8800   5D                     pop     ebp
006B8801   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdPorcACKeyPress(Sender : TObject);
begin
(*
006B885C   55                     push    ebp
006B885D   8BEC                   mov     ebp, esp
006B885F   53                     push    ebx
006B8860   56                     push    esi
006B8861   8BD8                   mov     ebx, eax
006B8863   803950                 cmp     byte ptr [ecx], $50
006B8866   7405                   jz      006B886D
006B8868   803970                 cmp     byte ptr [ecx], $70
006B886B   7523                   jnz     006B8890

* Reference to control TFrmAcrescimo.sbCupomPorc : TSpeedButton
|
006B886D   8BB34C030000           mov     esi, [ebx+$034C]
006B8873   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
006B8875   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
006B887B   FF9620010000           call    dword ptr [esi+$0120]
006B8881   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.sbCupomPorc : TSpeedButton
|
006B8883   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006B8889   E83E67D9FF             call    0044EFCC
006B888E   EB35                   jmp     006B88C5
006B8890   803956                 cmp     byte ptr [ecx], $56
006B8893   7405                   jz      006B889A
006B8895   803976                 cmp     byte ptr [ecx], $76
006B8898   7523                   jnz     006B88BD

* Reference to control TFrmAcrescimo.sbCupomValor : TSpeedButton
|
006B889A   8BB350030000           mov     esi, [ebx+$0350]
006B88A0   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
006B88A2   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
006B88A8   FF9620010000           call    dword ptr [esi+$0120]
006B88AE   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.sbCupomValor : TSpeedButton
|
006B88B0   8B8350030000           mov     eax, [ebx+$0350]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006B88B6   E81167D9FF             call    0044EFCC
006B88BB   EB08                   jmp     006B88C5
006B88BD   80392E                 cmp     byte ptr [ecx], $2E
006B88C0   7503                   jnz     006B88C5
006B88C2   C6012C                 mov     byte ptr [ecx], $2C
006B88C5   5E                     pop     esi
006B88C6   5B                     pop     ebx
006B88C7   5D                     pop     ebp
006B88C8   C3                     ret

*)
end;

procedure TFrmAcrescimo.EdValorAIKeyPress(Sender : TObject);
begin
(*
006B88CC   55                     push    ebp
006B88CD   8BEC                   mov     ebp, esp
006B88CF   53                     push    ebx
006B88D0   56                     push    esi
006B88D1   8BD8                   mov     ebx, eax
006B88D3   803950                 cmp     byte ptr [ecx], $50
006B88D6   7405                   jz      006B88DD
006B88D8   803970                 cmp     byte ptr [ecx], $70
006B88DB   7523                   jnz     006B8900

* Reference to control TFrmAcrescimo.sbItemPorc : TSpeedButton
|
006B88DD   8BB354030000           mov     esi, [ebx+$0354]
006B88E3   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
006B88E5   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
006B88EB   FF9620010000           call    dword ptr [esi+$0120]
006B88F1   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.sbItemPorc : TSpeedButton
|
006B88F3   8B8354030000           mov     eax, [ebx+$0354]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006B88F9   E8CE66D9FF             call    0044EFCC
006B88FE   EB2B                   jmp     006B892B
006B8900   803956                 cmp     byte ptr [ecx], $56
006B8903   7405                   jz      006B890A
006B8905   803976                 cmp     byte ptr [ecx], $76
006B8908   7521                   jnz     006B892B

* Reference to control TFrmAcrescimo.sbItemValor : TSpeedButton
|
006B890A   8BB358030000           mov     esi, [ebx+$0358]
006B8910   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
006B8912   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
006B8918   FF9620010000           call    dword ptr [esi+$0120]
006B891E   B201                   mov     dl, $01

* Reference to control TFrmAcrescimo.sbItemValor : TSpeedButton
|
006B8920   8B8358030000           mov     eax, [ebx+$0358]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006B8926   E8A166D9FF             call    0044EFCC
006B892B   5E                     pop     esi
006B892C   5B                     pop     ebx
006B892D   5D                     pop     ebp
006B892E   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B7C99(Sender : TObject);
begin
(*
006B7C99   8BEC                   mov     ebp, esp
006B7C9B   83C4E0                 add     esp, -$20
006B7C9E   53                     push    ebx
006B7C9F   33C9                   xor     ecx, ecx
006B7CA1   894DE4                 mov     [ebp-$1C], ecx
006B7CA4   894DE0                 mov     [ebp-$20], ecx
006B7CA7   894DEC                 mov     [ebp-$14], ecx
006B7CAA   894DE8                 mov     [ebp-$18], ecx
006B7CAD   8955FC                 mov     [ebp-$04], edx
006B7CB0   8BD8                   mov     ebx, eax
006B7CB2   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
006B7CB5   E892DCD4FF             call    0040594C
006B7CBA   33C0                   xor     eax, eax
006B7CBC   55                     push    ebp
006B7CBD   68547E6B00             push    $006B7E54

***** TRY
|
006B7CC2   64FF30                 push    dword ptr fs:[eax]
006B7CC5   648920                 mov     fs:[eax], esp
006B7CC8   8B4514                 mov     eax, [ebp+$14]
006B7CCB   8945F0                 mov     [ebp-$10], eax
006B7CCE   8B4518                 mov     eax, [ebp+$18]
006B7CD1   8945F4                 mov     [ebp-$0C], eax
006B7CD4   668B451C               mov     ax, word ptr [ebp+$1C]
006B7CD8   668945F8               mov     [ebp-$08], ax
006B7CDC   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'valor'
|
006B7CDF   BA6C7E6B00             mov     edx, $006B7E6C

* Reference to: System.@LStrCmp;
|
006B7CE4   E8BFDBD4FF             call    004058A8
006B7CE9   7531                   jnz     006B7D1C
006B7CEB   8B4508                 mov     eax, [ebp+$08]
006B7CEE   8905A4ED7D00           mov     [$007DEDA4], eax
006B7CF4   8B450C                 mov     eax, [ebp+$0C]
006B7CF7   8905A8ED7D00           mov     [$007DEDA8], eax
006B7CFD   668B4510               mov     ax, word ptr [ebp+$10]
006B7D01   668905ACED7D00         mov     [$007DEDAC], ax
006B7D08   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7D0B   DB2DA4ED7D00           fld     tbyte ptr [$007DEDA4]
006B7D11   DEC1                   faddp   st(1), st(0)
006B7D13   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006B7D16   9B                     wait
006B7D17   E9E4000000             jmp     006B7E00
006B7D1C   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'porc'
|
006B7D1F   BA7C7E6B00             mov     edx, $006B7E7C

* Reference to: System.@LStrCmp;
|
006B7D24   E87FDBD4FF             call    004058A8
006B7D29   0F85D1000000           jnz     006B7E00
006B7D2F   8B4508                 mov     eax, [ebp+$08]
006B7D32   890598ED7D00           mov     [$007DED98], eax
006B7D38   8B450C                 mov     eax, [ebp+$0C]
006B7D3B   89059CED7D00           mov     [$007DED9C], eax
006B7D41   668B4510               mov     ax, word ptr [ebp+$10]
006B7D45   668905A0ED7D00         mov     [$007DEDA0], ax
006B7D4C   A1D4AB7D00             mov     eax, dword ptr [$007DABD4]
006B7D51   803800                 cmp     byte ptr [eax], $00
006B7D54   7446                   jz      006B7D9C
006B7D56   DB2D98ED7D00           fld     tbyte ptr [$007DED98]
006B7D5C   D905847E6B00           fld     dword ptr [$006B7E84]

* Reference to: System.@FSafeDivide;
|
006B7D62   E899B7D4FF             call    00403500
006B7D67   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7D6A   DEC9                   fmulp   st(1), st(0)
006B7D6C   83C4F4                 add     esp, -$0C
006B7D6F   DB3C24                 fstp    tbyte ptr [esp]
006B7D72   9B                     wait
006B7D73   8D55E8                 lea     edx, [ebp-$18]

* Possible String Reference to: '###,###,###,##0.00'
|
006B7D76   B8907E6B00             mov     eax, $006B7E90

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
006B7D7B   E8BC57D5FF             call    0040D53C
006B7D80   8B45E8                 mov     eax, [ebp-$18]
006B7D83   8D55EC                 lea     edx, [ebp-$14]

|
006B7D86   E875C10F00             call    007B3F00
006B7D8B   8B45EC                 mov     eax, [ebp-$14]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
006B7D8E   E85958D5FF             call    0040D5EC
006B7D93   DB3DA4ED7D00           fstp    tbyte ptr [$007DEDA4]
006B7D99   9B                     wait
006B7D9A   EB55                   jmp     006B7DF1
006B7D9C   DB2D98ED7D00           fld     tbyte ptr [$007DED98]
006B7DA2   D905847E6B00           fld     dword ptr [$006B7E84]

* Reference to: System.@FSafeDivide;
|
006B7DA8   E853B7D4FF             call    00403500
006B7DAD   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7DB0   DEC9                   fmulp   st(1), st(0)
006B7DB2   83C4F8                 add     esp, -$08
006B7DB5   DD1C24                 fstp    qword ptr [esp]
006B7DB8   9B                     wait
006B7DB9   B802000000             mov     eax, $00000002

* Reference to : TFrmInfoAtu._PROC_007A11C8()
|
006B7DBE   E805940E00             call    007A11C8
006B7DC3   83C4F4                 add     esp, -$0C
006B7DC6   DB3C24                 fstp    tbyte ptr [esp]
006B7DC9   9B                     wait
006B7DCA   8D55E0                 lea     edx, [ebp-$20]

* Possible String Reference to: '###,###,###,##0.00'
|
006B7DCD   B8907E6B00             mov     eax, $006B7E90

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
006B7DD2   E86557D5FF             call    0040D53C
006B7DD7   8B45E0                 mov     eax, [ebp-$20]
006B7DDA   8D55E4                 lea     edx, [ebp-$1C]

|
006B7DDD   E81EC10F00             call    007B3F00
006B7DE2   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
006B7DE5   E80258D5FF             call    0040D5EC
006B7DEA   DB3DA4ED7D00           fstp    tbyte ptr [$007DEDA4]
006B7DF0   9B                     wait
006B7DF1   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7DF4   DB2DA4ED7D00           fld     tbyte ptr [$007DEDA4]
006B7DFA   DEC1                   faddp   st(1), st(0)
006B7DFC   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006B7DFF   9B                     wait
006B7E00   668B451C               mov     ax, word ptr [ebp+$1C]
006B7E04   50                     push    eax
006B7E05   FF7518                 push    dword ptr [ebp+$18]
006B7E08   FF7514                 push    dword ptr [ebp+$14]
006B7E0B   668B45F8               mov     ax, word ptr [ebp-$08]
006B7E0F   50                     push    eax
006B7E10   FF75F4                 push    dword ptr [ebp-$0C]
006B7E13   FF75F0                 push    dword ptr [ebp-$10]
006B7E16   668B05ACED7D00         mov     ax, word ptr [$007DEDAC]
006B7E1D   50                     push    eax
006B7E1E   FF35A8ED7D00           push    dword ptr [$007DEDA8]
006B7E24   FF35A4ED7D00           push    dword ptr [$007DEDA4]
006B7E2A   8BC3                   mov     eax, ebx

|
006B7E2C   E80F020000             call    006B8040
006B7E31   33C0                   xor     eax, eax
006B7E33   5A                     pop     edx
006B7E34   59                     pop     ecx
006B7E35   59                     pop     ecx
006B7E36   648910                 mov     fs:[eax], edx

****** FINALLY
|
006B7E39   685B7E6B00             push    $006B7E5B
006B7E3E   8D45E0                 lea     eax, [ebp-$20]
006B7E41   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
006B7E46   E875D6D4FF             call    004054C0
006B7E4B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
006B7E4E   E849D6D4FF             call    0040549C
006B7E53   C3                     ret


* Reference to: System.@HandleFinally;
|
006B7E54   E9DFCED4FF             jmp     00404D38
006B7E59   EBE3                   jmp     006B7E3E

****** END
|
006B7E5B   5B                     pop     ebx
006B7E5C   8BE5                   mov     esp, ebp
006B7E5E   5D                     pop     ebp
006B7E5F   C21800                 ret     $0018

*)
end;

procedure TFrmAcrescimo._PROC_006B7EA5(Sender : TObject);
begin
(*
006B7EA5   8BEC                   mov     ebp, esp
006B7EA7   83C4E8                 add     esp, -$18
006B7EAA   53                     push    ebx
006B7EAB   33C9                   xor     ecx, ecx
006B7EAD   894DEC                 mov     [ebp-$14], ecx
006B7EB0   894DE8                 mov     [ebp-$18], ecx
006B7EB3   8955FC                 mov     [ebp-$04], edx
006B7EB6   8BD8                   mov     ebx, eax
006B7EB8   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
006B7EBB   E88CDAD4FF             call    0040594C
006B7EC0   33C0                   xor     eax, eax
006B7EC2   55                     push    ebp
006B7EC3   68F27F6B00             push    $006B7FF2

***** TRY
|
006B7EC8   64FF30                 push    dword ptr fs:[eax]
006B7ECB   648920                 mov     fs:[eax], esp
006B7ECE   8B4514                 mov     eax, [ebp+$14]
006B7ED1   8945F0                 mov     [ebp-$10], eax
006B7ED4   8B4518                 mov     eax, [ebp+$18]
006B7ED7   8945F4                 mov     [ebp-$0C], eax
006B7EDA   668B451C               mov     ax, word ptr [ebp+$1C]
006B7EDE   668945F8               mov     [ebp-$08], ax
006B7EE2   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'valor'
|
006B7EE5   BA08806B00             mov     edx, $006B8008

* Reference to: System.@LStrCmp;
|
006B7EEA   E8B9D9D4FF             call    004058A8
006B7EEF   752E                   jnz     006B7F1F
006B7EF1   8B4508                 mov     eax, [ebp+$08]
006B7EF4   8905A4ED7D00           mov     [$007DEDA4], eax
006B7EFA   8B450C                 mov     eax, [ebp+$0C]
006B7EFD   8905A8ED7D00           mov     [$007DEDA8], eax
006B7F03   668B4510               mov     ax, word ptr [ebp+$10]
006B7F07   668905ACED7D00         mov     [$007DEDAC], ax
006B7F0E   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7F11   DB2DA4ED7D00           fld     tbyte ptr [$007DEDA4]
006B7F17   DEC1                   faddp   st(1), st(0)
006B7F19   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006B7F1C   9B                     wait
006B7F1D   EB7F                   jmp     006B7F9E
006B7F1F   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'porc'
|
006B7F22   BA18806B00             mov     edx, $006B8018

* Reference to: System.@LStrCmp;
|
006B7F27   E87CD9D4FF             call    004058A8
006B7F2C   7570                   jnz     006B7F9E
006B7F2E   8B4508                 mov     eax, [ebp+$08]
006B7F31   890598ED7D00           mov     [$007DED98], eax
006B7F37   8B450C                 mov     eax, [ebp+$0C]
006B7F3A   89059CED7D00           mov     [$007DED9C], eax
006B7F40   668B4510               mov     ax, word ptr [ebp+$10]
006B7F44   668905A0ED7D00         mov     [$007DEDA0], ax
006B7F4B   DB2D98ED7D00           fld     tbyte ptr [$007DED98]
006B7F51   D90520806B00           fld     dword ptr [$006B8020]

* Reference to: System.@FSafeDivide;
|
006B7F57   E8A4B5D4FF             call    00403500
006B7F5C   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7F5F   DEC9                   fmulp   st(1), st(0)
006B7F61   83C4F4                 add     esp, -$0C
006B7F64   DB3C24                 fstp    tbyte ptr [esp]
006B7F67   9B                     wait
006B7F68   8D55E8                 lea     edx, [ebp-$18]

* Possible String Reference to: '###,###,###,##0.00'
|
006B7F6B   B82C806B00             mov     eax, $006B802C

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
006B7F70   E8C755D5FF             call    0040D53C
006B7F75   8B45E8                 mov     eax, [ebp-$18]
006B7F78   8D55EC                 lea     edx, [ebp-$14]

|
006B7F7B   E880BF0F00             call    007B3F00
006B7F80   8B45EC                 mov     eax, [ebp-$14]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
006B7F83   E86456D5FF             call    0040D5EC
006B7F88   DB3DA4ED7D00           fstp    tbyte ptr [$007DEDA4]
006B7F8E   9B                     wait
006B7F8F   DB6D14                 fld     tbyte ptr [ebp+$14]
006B7F92   DB2DA4ED7D00           fld     tbyte ptr [$007DEDA4]
006B7F98   DEC1                   faddp   st(1), st(0)
006B7F9A   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006B7F9D   9B                     wait
006B7F9E   668B451C               mov     ax, word ptr [ebp+$1C]
006B7FA2   50                     push    eax
006B7FA3   FF7518                 push    dword ptr [ebp+$18]
006B7FA6   FF7514                 push    dword ptr [ebp+$14]
006B7FA9   668B45F8               mov     ax, word ptr [ebp-$08]
006B7FAD   50                     push    eax
006B7FAE   FF75F4                 push    dword ptr [ebp-$0C]
006B7FB1   FF75F0                 push    dword ptr [ebp-$10]
006B7FB4   668B05ACED7D00         mov     ax, word ptr [$007DEDAC]
006B7FBB   50                     push    eax
006B7FBC   FF35A8ED7D00           push    dword ptr [$007DEDA8]
006B7FC2   FF35A4ED7D00           push    dword ptr [$007DEDA4]
006B7FC8   8BC3                   mov     eax, ebx

|
006B7FCA   E871000000             call    006B8040
006B7FCF   33C0                   xor     eax, eax
006B7FD1   5A                     pop     edx
006B7FD2   59                     pop     ecx
006B7FD3   59                     pop     ecx
006B7FD4   648910                 mov     fs:[eax], edx

****** FINALLY
|
006B7FD7   68F97F6B00             push    $006B7FF9
006B7FDC   8D45E8                 lea     eax, [ebp-$18]
006B7FDF   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
006B7FE4   E8D7D4D4FF             call    004054C0
006B7FE9   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
006B7FEC   E8ABD4D4FF             call    0040549C
006B7FF1   C3                     ret


* Reference to: System.@HandleFinally;
|
006B7FF2   E941CDD4FF             jmp     00404D38
006B7FF7   EBE3                   jmp     006B7FDC

****** END
|
006B7FF9   5B                     pop     ebx
006B7FFA   8BE5                   mov     esp, ebp
006B7FFC   5D                     pop     ebp
006B7FFD   C21800                 ret     $0018

*)
end;

procedure TFrmAcrescimo._PROC_006B8041(Sender : TObject);
begin
(*
006B8041   8BEC                   mov     ebp, esp
006B8043   53                     push    ebx
006B8044   8BD8                   mov     ebx, eax
006B8046   668B4528               mov     ax, word ptr [ebp+$28]
006B804A   50                     push    eax
006B804B   FF7524                 push    dword ptr [ebp+$24]
006B804E   FF7520                 push    dword ptr [ebp+$20]

* Reference to control TFrmAcrescimo.EdValorAtual : TCurrencyEdit
|
006B8051   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8057   E86411F7FF             call    006291C0
006B805C   668B451C               mov     ax, word ptr [ebp+$1C]
006B8060   50                     push    eax
006B8061   FF7518                 push    dword ptr [ebp+$18]
006B8064   FF7514                 push    dword ptr [ebp+$14]

* Reference to control TFrmAcrescimo.EdNovoValor : TCurrencyEdit
|
006B8067   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B806D   E84E11F7FF             call    006291C0
006B8072   668B4510               mov     ax, word ptr [ebp+$10]
006B8076   50                     push    eax
006B8077   FF750C                 push    dword ptr [ebp+$0C]
006B807A   FF7508                 push    dword ptr [ebp+$08]

* Reference to control TFrmAcrescimo.EdValorAcrescimo : TCurrencyEdit
|
006B807D   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8083   E83811F7FF             call    006291C0
006B8088   5B                     pop     ebx
006B8089   5D                     pop     ebp
006B808A   C22400                 ret     $0024

*)
end;

procedure TFrmAcrescimo._PROC_006B8451(Sender : TObject);
begin
(*
006B8451   A168897D00             mov     eax, dword ptr [$007D8968]

* Possible String Reference to: 'cupom'
|
006B8456   BA80856B00             mov     edx, $006B8580

* Reference to: System.@LStrCmp;
|
006B845B   E848D4D4FF             call    004058A8
006B8460   0F85EE000000           jnz     006B8554
006B8466   B868897D00             mov     eax, $007D8968

* Possible String Reference to: 'cupom'
|
006B846B   BA80856B00             mov     edx, $006B8580

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B8470   E87BD0D4FF             call    004054F0
006B8475   B86C897D00             mov     eax, $007D896C

* Possible String Reference to: 'porc'
|
006B847A   BA70856B00             mov     edx, $006B8570

* Reference to: System.@LStrAsg(void;void;void;void);
|
006B847F   E86CD0D4FF             call    004054F0
006B8484   33C0                   xor     eax, eax
006B8486   890598ED7D00           mov     [$007DED98], eax
006B848C   89059CED7D00           mov     [$007DED9C], eax
006B8492   668905A0ED7D00         mov     [$007DEDA0], ax
006B8499   33C0                   xor     eax, eax
006B849B   8905A4ED7D00           mov     [$007DEDA4], eax
006B84A1   8905A8ED7D00           mov     [$007DEDA8], eax
006B84A7   668905ACED7D00         mov     [$007DEDAC], ax
006B84AE   33D2                   xor     edx, edx

* Reference to control btFechar : N.A.
|
006B84B0   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: ExtCtrls.TNotebook.SetPageIndex(TNotebook;Integer);
|
006B84B6   E88911D9FF             call    00449644
006B84BB   B201                   mov     dl, $01
006B84BD   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B84C3   E824B1DDFF             call    004935EC
006B84C8   6A00                   push    $00
006B84CA   6A00                   push    $00
006B84CC   6A00                   push    $00
006B84CE   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B84D4   E8E70CF7FF             call    006291C0
006B84D9   8B832C030000           mov     eax, [ebx+$032C]
006B84DF   8B10                   mov     edx, [eax]
006B84E1   FF92C4000000           call    dword ptr [edx+$00C4]
006B84E7   33D2                   xor     edx, edx
006B84E9   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006B84EF   E8F8B0DDFF             call    004935EC
006B84F4   B201                   mov     dl, $01
006B84F6   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006B84FC   E8CB6AD9FF             call    0044EFCC
006B8501   A150B67D00             mov     eax, dword ptr [$007DB650]
006B8506   668B5008               mov     dx, word ptr [eax+$08]
006B850A   52                     push    edx
006B850B   FF7004                 push    dword ptr [eax+$04]
006B850E   FF30                   push    dword ptr [eax]
006B8510   8B8310030000           mov     eax, [ebx+$0310]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006B8516   E8A50CF7FF             call    006291C0
006B851B   A150B67D00             mov     eax, dword ptr [$007DB650]
006B8520   668B5008               mov     dx, word ptr [eax+$08]
006B8524   52                     push    edx
006B8525   FF7004                 push    dword ptr [eax+$04]
006B8528   FF30                   push    dword ptr [eax]
006B852A   A150B67D00             mov     eax, dword ptr [$007DB650]
006B852F   668B5008               mov     dx, word ptr [eax+$08]
006B8533   52                     push    edx
006B8534   FF7004                 push    dword ptr [eax+$04]
006B8537   FF30                   push    dword ptr [eax]
006B8539   668B05ACED7D00         mov     ax, word ptr [$007DEDAC]
006B8540   50                     push    eax
006B8541   FF35A8ED7D00           push    dword ptr [$007DEDA8]
006B8547   FF35A4ED7D00           push    dword ptr [$007DEDA4]
006B854D   8BC3                   mov     eax, ebx

|
006B854F   E8ECFAFFFF             call    006B8040
006B8554   5B                     pop     ebx
006B8555   5D                     pop     ebp
006B8556   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B8815(Sender : TObject);
begin
(*
006B8815   8BEC                   mov     ebp, esp
006B8817   53                     push    ebx
006B8818   8BD8                   mov     ebx, eax
006B881A   A150B67D00             mov     eax, dword ptr [$007DB650]
006B881F   668B5008               mov     dx, word ptr [eax+$08]
006B8823   52                     push    edx
006B8824   FF7004                 push    dword ptr [eax+$04]
006B8827   FF30                   push    dword ptr [eax]

* Reference to control TFrmAcrescimo.EdValorAC : TCurrencyEdit
|
006B8829   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006B882F   E8F408F7FF             call    00629128
006B8834   83C4F4                 add     esp, -$0C
006B8837   DB3C24                 fstp    tbyte ptr [esp]
006B883A   9B                     wait

* Possible String Reference to: 'valor'
|
006B883B   BA54886B00             mov     edx, $006B8854
006B8840   8BC3                   mov     eax, ebx

|
006B8842   E851F4FFFF             call    006B7C98
006B8847   5B                     pop     ebx
006B8848   5D                     pop     ebp
006B8849   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B8930(Sender : TObject);
begin
(*
006B8930   55                     push    ebp
006B8931   8BEC                   mov     ebp, esp
006B8933   33C0                   xor     eax, eax
006B8935   55                     push    ebp

* Possible String Reference to: 'éÈÃÔÿëø]Ãƒ-°í}'
|
006B8936   686B896B00             push    $006B896B

***** TRY
|
006B893B   64FF30                 push    dword ptr fs:[eax]
006B893E   648920                 mov     fs:[eax], esp
006B8941   FF05B0ED7D00           inc     dword ptr [$007DEDB0]
006B8947   7514                   jnz     006B895D
006B8949   B86C897D00             mov     eax, $007D896C

* Reference to: System.@LStrClr(void;void);
|
006B894E   E849CBD4FF             call    0040549C
006B8953   B868897D00             mov     eax, $007D8968

* Reference to: System.@LStrClr(void;void);
|
006B8958   E83FCBD4FF             call    0040549C
006B895D   33C0                   xor     eax, eax
006B895F   5A                     pop     edx
006B8960   59                     pop     ecx
006B8961   59                     pop     ecx
006B8962   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ãƒ-°í}'
|
006B8965   6872896B00             push    $006B8972
006B896A   C3                     ret


* Reference to: System.@HandleFinally;
|
006B896B   E9C8C3D4FF             jmp     00404D38
006B8970   EBF8                   jmp     006B896A

****** END
|
006B8972   5D                     pop     ebp
006B8973   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B8974(Sender : TObject);
begin
(*
006B8974   832DB0ED7D0001         sub     dword ptr [$007DEDB0], +$01
006B897B   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B897C(Sender : TObject);
begin
(*
006B897C   68C67D0067             push    $67007DC6
006B8981   FC                     cld
006B8982   0000                   add     [eax], al

*)
end;

procedure TFrmAcrescimo._PROC_006B89F1(Sender : TObject);
begin
(*
006B89F1   FC                     cld
006B89F2   0000                   add     [eax], al

*)
end;

procedure TFrmAcrescimo._PROC_006B8D25(Sender : TObject);
begin
(*
006B8D25   8BEC                   mov     ebp, esp
006B8D27   33C0                   xor     eax, eax
006B8D29   55                     push    ebp

* Possible String Reference to: 'éê¿Ôÿëø]Ã‹Àƒ-´í}'
|
006B8D2A   68498D6B00             push    $006B8D49

***** TRY
|
006B8D2F   64FF30                 push    dword ptr fs:[eax]
006B8D32   648920                 mov     fs:[eax], esp
006B8D35   FF05B4ED7D00           inc     dword ptr [$007DEDB4]
006B8D3B   33C0                   xor     eax, eax
006B8D3D   5A                     pop     edx
006B8D3E   59                     pop     ecx
006B8D3F   59                     pop     ecx
006B8D40   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-´í}'
|
006B8D43   68508D6B00             push    $006B8D50
006B8D48   C3                     ret


* Reference to: System.@HandleFinally;
|
006B8D49   E9EABFD4FF             jmp     00404D38
006B8D4E   EBF8                   jmp     006B8D48

****** END
|
006B8D50   5D                     pop     ebp
006B8D51   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B8D54(Sender : TObject);
begin
(*
006B8D54   832DB4ED7D0001         sub     dword ptr [$007DEDB4], +$01
006B8D5B   C3                     ret

*)
end;

procedure TFrmAcrescimo._PROC_006B8D5C(Sender : TObject);
begin
(*
006B8D5C   A88D                   test    al, $8D
006B8D5E   6B0000                 imul    eax, [eax], $00
006B8D61   0000                   add     [eax], al

*)
end;

end.