unit autoriza;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons;
  
type
  TFrmAutoriza=class(TForm)
    EdAutoriza: TEdit;
    btCancela: TBitBtn;
    btOk: TBitBtn;
    Label1: TLabel;
    procedure EdAutorizaKeyDown(Sender : TObject);
    procedure _PROC_006711D4(Sender : TObject);
    procedure _PROC_00671204(Sender : TObject);
    procedure _PROC_0067120C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAutoriza: TFrmAutoriza;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmAutoriza.EdAutorizaKeyDown(Sender : TObject);
begin
(*
0067119C   55                     push    ebp
0067119D   8BEC                   mov     ebp, esp
0067119F   56                     push    esi
006711A0   6683390D               cmp     word ptr [ecx], +$0D
006711A4   7511                   jnz     006711B7

* Reference to control TFrmAutoriza.btOk : TBitBtn
|
006711A6   8B8000030000           mov     eax, [eax+$0300]
006711AC   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
006711B0   E8EB35D9FF             call    004047A0
006711B5   EB15                   jmp     006711CC
006711B7   6683391B               cmp     word ptr [ecx], +$1B
006711BB   750F                   jnz     006711CC

* Reference to control meTexto : N.A.
|
006711BD   8B80FC020000           mov     eax, [eax+$02FC]
006711C3   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
006711C7   E8D435D9FF             call    004047A0
006711CC   5E                     pop     esi
006711CD   5D                     pop     ebp
006711CE   C20400                 ret     $0004

*)
end;

procedure TFrmAutoriza._PROC_006711D4(Sender : TObject);
begin
(*
006711D4   55                     push    ebp
006711D5   8BEC                   mov     ebp, esp
006711D7   33C0                   xor     eax, eax
006711D9   55                     push    ebp

* Possible String Reference to: 'é:;Ùÿëø]Ã‹Àƒ-Xé}'
|
006711DA   68F9116700             push    $006711F9

***** TRY
|
006711DF   64FF30                 push    dword ptr fs:[eax]
006711E2   648920                 mov     fs:[eax], esp
006711E5   FF0558E97D00           inc     dword ptr [$007DE958]
006711EB   33C0                   xor     eax, eax
006711ED   5A                     pop     edx
006711EE   59                     pop     ecx
006711EF   59                     pop     ecx
006711F0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-Xé}'
|
006711F3   6800126700             push    $00671200
006711F8   C3                     ret


* Reference to: System.@HandleFinally;
|
006711F9   E93A3BD9FF             jmp     00404D38
006711FE   EBF8                   jmp     006711F8

****** END
|
00671200   5D                     pop     ebp
00671201   C3                     ret

*)
end;

procedure TFrmAutoriza._PROC_00671204(Sender : TObject);
begin
(*
00671204   832D58E97D0001         sub     dword ptr [$007DE958], +$01
0067120B   C3                     ret

*)
end;

procedure TFrmAutoriza._PROC_0067120C(Sender : TObject);
begin
(*
0067120C   58                     pop     eax
0067120D   126700                 adc     ah, byte ptr [edi+$00]
00671210   0000                   add     [eax], al

*)
end;

end.