unit CadMes;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Spin, Mask, JvExMask, JvToolEdit,
  JvExStdCtrls, JvEdit, JvValidateEdit, Buttons, ExtCtrls;
  
type
  TFrmCadMesas=class(TForm)
    Label1: TLabel;
    btProcessar: TBitBtn;
    btFechar: TBitBtn;
    Bevel1: TBevel;
    ckLimparCadastro: TCheckBox;
    Label2: TLabel;
    Label3: TLabel;
    EdNumMesas: TJvValidateEdit;
    EdCodFunc: TJvComboEdit;
    EdNomeFunc: TEdit;
    sbNumeroMesas: TSpinButton;
    Label4: TLabel;
    EdAltura: TJvValidateEdit;
    sbAltura: TSpinButton;
    Label5: TLabel;
    EdLargura: TJvValidateEdit;
    sbLargura: TSpinButton;
    procedure EdCodFuncButtonClick(Sender : TObject);
    procedure sbNumeroMesasDownClick(Sender : TObject);
    procedure sbNumeroMesasUpClick(Sender : TObject);
    procedure btProcessarClick(Sender : TObject);
    procedure sbAlturaUpClick(Sender : TObject);
    procedure sbAlturaDownClick(Sender : TObject);
    procedure sbLarguraUpClick(Sender : TObject);
    procedure sbLarguraDownClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_0069F36C(Sender : TObject);
    procedure _PROC_0069F575(Sender : TObject);
    procedure _PROC_0069F5A6(Sender : TObject);
    procedure _PROC_0069F5C1(Sender : TObject);
    procedure _PROC_0069F6F7(Sender : TObject);
    procedure _PROC_0069F786(Sender : TObject);
    procedure _PROC_0069F924(Sender : TObject);
    procedure _PROC_0069FA79(Sender : TObject);
    procedure _PROC_0069FC00(Sender : TObject);
    procedure _PROC_0069FCF0(Sender : TObject);
    procedure _PROC_0069FDDC(Sender : TObject);
    procedure _PROC_0069FECC(Sender : TObject);
    procedure _PROC_006A003D(Sender : TObject);
    procedure _PROC_006A006C(Sender : TObject);
    procedure _PROC_006A0074(Sender : TObject);
    procedure _PROC_006A030B(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmCadMesas: TFrmCadMesas;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmCadMesas.EdCodFuncButtonClick(Sender : TObject);
begin
(*
0069F44C   55                     push    ebp
0069F44D   8BEC                   mov     ebp, esp
0069F44F   83C4E0                 add     esp, -$20
0069F452   53                     push    ebx
0069F453   33C9                   xor     ecx, ecx
0069F455   894DE0                 mov     [ebp-$20], ecx
0069F458   894DE4                 mov     [ebp-$1C], ecx
0069F45B   8BD8                   mov     ebx, eax
0069F45D   33C0                   xor     eax, eax
0069F45F   55                     push    ebp
0069F460   6828F56900             push    $0069F528

***** TRY
|
0069F465   64FF30                 push    dword ptr fs:[eax]
0069F468   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'CÛdigo'
|
0069F46B   B83CF56900             mov     eax, $0069F53C
0069F470   8945F4                 mov     [ebp-$0C], eax

* Possible String Reference to: 'Nome'
|
0069F473   B84CF56900             mov     eax, $0069F54C
0069F478   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Fantasia'
|
0069F47B   B85CF56900             mov     eax, $0069F55C
0069F480   8945FC                 mov     [ebp-$04], eax
0069F483   8D45F4                 lea     eax, [ebp-$0C]
0069F486   50                     push    eax
0069F487   6A02                   push    $02
0069F489   6A00                   push    $00

* Possible String Reference to: 'CODFUNC'
|
0069F48B   B870F56900             mov     eax, $0069F570
0069F490   8945E8                 mov     [ebp-$18], eax

* Possible String Reference to: 'NOME'
|
0069F493   B880F56900             mov     eax, $0069F580
0069F498   8945EC                 mov     [ebp-$14], eax

* Possible String Reference to: 'FANTASIA'
|
0069F49B   B890F56900             mov     eax, $0069F590
0069F4A0   8945F0                 mov     [ebp-$10], eax
0069F4A3   8D55E8                 lea     edx, [ebp-$18]
0069F4A6   B902000000             mov     ecx, $00000002

* Possible String Reference to: 'FUNCREPR'
|
0069F4AB   B8A4F56900             mov     eax, $0069F5A4

|
0069F4B0   E89F9DF9FF             call    00639254
0069F4B5   84C0                   test    al, al
0069F4B7   7454                   jz      0069F50D
0069F4B9   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0069F4BE   8B00                   mov     eax, [eax]
0069F4C0   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CodFunc'
|
0069F4C3   BAB8F56900             mov     edx, $0069F5B8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069F4C8   E837A7E4FF             call    004E9C04
0069F4CD   8D55E4                 lea     edx, [ebp-$1C]
0069F4D0   8B08                   mov     ecx, [eax]
0069F4D2   FF5160                 call    dword ptr [ecx+$60]
0069F4D5   8B55E4                 mov     edx, [ebp-$1C]

* Reference to control TFrmCadMesas.EdCodFunc : TJvComboEdit
|
0069F4D8   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0069F4DE   E8EDEAE5FF             call    004FDFD0
0069F4E3   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0069F4E8   8B00                   mov     eax, [eax]
0069F4EA   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Nome'
|
0069F4ED   BA4CF56900             mov     edx, $0069F54C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069F4F2   E80DA7E4FF             call    004E9C04
0069F4F7   8D55E0                 lea     edx, [ebp-$20]
0069F4FA   8B08                   mov     ecx, [eax]
0069F4FC   FF5160                 call    dword ptr [ecx+$60]
0069F4FF   8B55E0                 mov     edx, [ebp-$20]

* Reference to control TFrmCadMesas.EdNomeFunc : TEdit
|
0069F502   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0069F508   E8EF41DFFF             call    004936FC
0069F50D   33C0                   xor     eax, eax
0069F50F   5A                     pop     edx
0069F510   59                     pop     ecx
0069F511   59                     pop     ecx
0069F512   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069F515   682FF56900             push    $0069F52F
0069F51A   8D45E0                 lea     eax, [ebp-$20]
0069F51D   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069F522   E8995FD6FF             call    004054C0
0069F527   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F528   E90B58D6FF             jmp     00404D38
0069F52D   EBEB                   jmp     0069F51A

****** END
|
0069F52F   5B                     pop     ebx
0069F530   8BE5                   mov     esp, ebp
0069F532   5D                     pop     ebp
0069F533   C3                     ret

*)
end;

procedure TFrmCadMesas.sbNumeroMesasDownClick(Sender : TObject);
begin
(*
0069F7C0   55                     push    ebp
0069F7C1   8BEC                   mov     ebp, esp
0069F7C3   B908000000             mov     ecx, $00000008
0069F7C8   6A00                   push    $00
0069F7CA   6A00                   push    $00
0069F7CC   49                     dec     ecx
0069F7CD   75F9                   jnz     0069F7C8
0069F7CF   53                     push    ebx
0069F7D0   56                     push    esi
0069F7D1   8BD8                   mov     ebx, eax
0069F7D3   33C0                   xor     eax, eax
0069F7D5   55                     push    ebp
0069F7D6   6861F86900             push    $0069F861

***** TRY
|
0069F7DB   64FF30                 push    dword ptr fs:[eax]
0069F7DE   648920                 mov     fs:[eax], esp
0069F7E1   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F7E4   8B8314030000           mov     eax, [ebx+$0314]

|
0069F7EA   E8C939FBFF             call    006531B8
0069F7EF   8D45F0                 lea     eax, [ebp-$10]
0069F7F2   50                     push    eax
0069F7F3   8D45E0                 lea     eax, [ebp-$20]
0069F7F6   33D2                   xor     edx, edx
0069F7F8   B101                   mov     cl, $01

|
0069F7FA   E87192D7FF             call    00418A70
0069F7FF   8D55E0                 lea     edx, [ebp-$20]
0069F802   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069F803   E83CD9D7FF             call    0041D144
0069F808   7E36                   jle     0069F840
0069F80A   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F80D   8BB314030000           mov     esi, [ebx+$0314]
0069F813   8BC6                   mov     eax, esi

|
0069F815   E89E39FBFF             call    006531B8
0069F81A   8D45D0                 lea     eax, [ebp-$30]
0069F81D   50                     push    eax
0069F81E   8D45C0                 lea     eax, [ebp-$40]
0069F821   BA01000000             mov     edx, $00000001
0069F826   B101                   mov     cl, $01

|
0069F828   E84392D7FF             call    00418A70
0069F82D   8D55C0                 lea     edx, [ebp-$40]
0069F830   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069F831   E87AD8D7FF             call    0041D0B0
0069F836   8D55D0                 lea     edx, [ebp-$30]
0069F839   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069F83B   E8503AFBFF             call    00653290
0069F840   33C0                   xor     eax, eax
0069F842   5A                     pop     edx
0069F843   59                     pop     ecx
0069F844   59                     pop     ecx
0069F845   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069F848   6868F86900             push    $0069F868
0069F84D   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069F850   8B1524114000           mov     edx, [$00401124]
0069F856   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069F85B   E83C68D6FF             call    0040609C
0069F860   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F861   E9D254D6FF             jmp     00404D38
0069F866   EBE5                   jmp     0069F84D

****** END
|
0069F868   5E                     pop     esi
0069F869   5B                     pop     ebx
0069F86A   8BE5                   mov     esp, ebp
0069F86C   5D                     pop     ebp
0069F86D   C3                     ret

*)
end;

procedure TFrmCadMesas.sbNumeroMesasUpClick(Sender : TObject);
begin
(*
0069F870   55                     push    ebp
0069F871   8BEC                   mov     ebp, esp
0069F873   B908000000             mov     ecx, $00000008
0069F878   6A00                   push    $00
0069F87A   6A00                   push    $00
0069F87C   49                     dec     ecx
0069F87D   75F9                   jnz     0069F878
0069F87F   53                     push    ebx
0069F880   56                     push    esi
0069F881   8BD8                   mov     ebx, eax
0069F883   33C0                   xor     eax, eax
0069F885   55                     push    ebp
0069F886   6814F96900             push    $0069F914

***** TRY
|
0069F88B   64FF30                 push    dword ptr fs:[eax]
0069F88E   648920                 mov     fs:[eax], esp
0069F891   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F894   8B8314030000           mov     eax, [ebx+$0314]

|
0069F89A   E81939FBFF             call    006531B8
0069F89F   8D45F0                 lea     eax, [ebp-$10]
0069F8A2   50                     push    eax
0069F8A3   8D45E0                 lea     eax, [ebp-$20]
0069F8A6   BA64000000             mov     edx, $00000064
0069F8AB   B101                   mov     cl, $01

|
0069F8AD   E8BE91D7FF             call    00418A70
0069F8B2   8D55E0                 lea     edx, [ebp-$20]
0069F8B5   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069F8B6   E869D8D7FF             call    0041D124
0069F8BB   7D36                   jnl     0069F8F3
0069F8BD   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F8C0   8BB314030000           mov     esi, [ebx+$0314]
0069F8C6   8BC6                   mov     eax, esi

|
0069F8C8   E8EB38FBFF             call    006531B8
0069F8CD   8D45D0                 lea     eax, [ebp-$30]
0069F8D0   50                     push    eax
0069F8D1   8D45C0                 lea     eax, [ebp-$40]
0069F8D4   BA01000000             mov     edx, $00000001
0069F8D9   B101                   mov     cl, $01

|
0069F8DB   E89091D7FF             call    00418A70
0069F8E0   8D55C0                 lea     edx, [ebp-$40]
0069F8E3   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069F8E4   E8BBD7D7FF             call    0041D0A4
0069F8E9   8D55D0                 lea     edx, [ebp-$30]
0069F8EC   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069F8EE   E89D39FBFF             call    00653290
0069F8F3   33C0                   xor     eax, eax
0069F8F5   5A                     pop     edx
0069F8F6   59                     pop     ecx
0069F8F7   59                     pop     ecx
0069F8F8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√ç@'
|
0069F8FB   681BF96900             push    $0069F91B
0069F900   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069F903   8B1524114000           mov     edx, [$00401124]
0069F909   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069F90E   E88967D6FF             call    0040609C
0069F913   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F914   E91F54D6FF             jmp     00404D38
0069F919   EBE5                   jmp     0069F900

****** END
|
0069F91B   5E                     pop     esi
0069F91C   5B                     pop     ebx
0069F91D   8BE5                   mov     esp, ebp
0069F91F   5D                     pop     ebp
0069F920   C3                     ret

*)
end;

procedure TFrmCadMesas.btProcessarClick(Sender : TObject);
begin
(*
0069FB2C   55                     push    ebp
0069FB2D   8BEC                   mov     ebp, esp

|
0069FB2F   E830F5FFFF             call    0069F064
0069FB34   5D                     pop     ebp
0069FB35   C3                     ret

*)
end;

procedure TFrmCadMesas.sbAlturaUpClick(Sender : TObject);
begin
(*
0069FB38   55                     push    ebp
0069FB39   8BEC                   mov     ebp, esp
0069FB3B   B908000000             mov     ecx, $00000008
0069FB40   6A00                   push    $00
0069FB42   6A00                   push    $00
0069FB44   49                     dec     ecx
0069FB45   75F9                   jnz     0069FB40
0069FB47   53                     push    ebx
0069FB48   56                     push    esi
0069FB49   8BD8                   mov     ebx, eax
0069FB4B   33C0                   xor     eax, eax
0069FB4D   55                     push    ebp
0069FB4E   68F3FB6900             push    $0069FBF3

***** TRY
|
0069FB53   64FF30                 push    dword ptr fs:[eax]
0069FB56   648920                 mov     fs:[eax], esp
0069FB59   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdAltura : TJvValidateEdit
|
0069FB5C   8B8328030000           mov     eax, [ebx+$0328]

|
0069FB62   E85136FBFF             call    006531B8
0069FB67   8D45F0                 lea     eax, [ebp-$10]
0069FB6A   50                     push    eax
0069FB6B   8D45E0                 lea     eax, [ebp-$20]
0069FB6E   BA64000000             mov     edx, $00000064
0069FB73   B101                   mov     cl, $01

|
0069FB75   E8F68ED7FF             call    00418A70
0069FB7A   8D55E0                 lea     edx, [ebp-$20]
0069FB7D   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069FB7E   E8A1D5D7FF             call    0041D124
0069FB83   7D38                   jnl     0069FBBD
0069FB85   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdAltura : TJvValidateEdit
|
0069FB88   8BB328030000           mov     esi, [ebx+$0328]
0069FB8E   8BC6                   mov     eax, esi

|
0069FB90   E82336FBFF             call    006531B8
0069FB95   8D45D0                 lea     eax, [ebp-$30]
0069FB98   50                     push    eax
0069FB99   8D45C0                 lea     eax, [ebp-$40]
0069FB9C   BA05000000             mov     edx, $00000005
0069FBA1   B101                   mov     cl, $01

|
0069FBA3   E8C88ED7FF             call    00418A70
0069FBA8   8D55C0                 lea     edx, [ebp-$40]
0069FBAB   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069FBAC   E8F3D4D7FF             call    0041D0A4
0069FBB1   8D55D0                 lea     edx, [ebp-$30]
0069FBB4   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FBB6   E8D536FBFF             call    00653290
0069FBBB   EB15                   jmp     0069FBD2
0069FBBD   6A00                   push    $00
0069FBBF   668B0D00FC6900         mov     cx, word ptr [$0069FC00]
0069FBC6   33D2                   xor     edx, edx

* Possible String Reference to: 'A altura m·xima È de 100!'
|
0069FBC8   B80CFC6900             mov     eax, $0069FC0C

|
0069FBCD   E85A3FDAFF             call    00443B2C
0069FBD2   33C0                   xor     eax, eax
0069FBD4   5A                     pop     edx
0069FBD5   59                     pop     ecx
0069FBD6   59                     pop     ecx
0069FBD7   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069FBDA   68FAFB6900             push    $0069FBFA
0069FBDF   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069FBE2   8B1524114000           mov     edx, [$00401124]
0069FBE8   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069FBED   E8AA64D6FF             call    0040609C
0069FBF2   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FBF3   E94051D6FF             jmp     00404D38
0069FBF8   EBE5                   jmp     0069FBDF

****** END
|
0069FBFA   5E                     pop     esi
0069FBFB   5B                     pop     ebx
0069FBFC   8BE5                   mov     esp, ebp
0069FBFE   5D                     pop     ebp
0069FBFF   C3                     ret

*)
end;

procedure TFrmCadMesas.sbAlturaDownClick(Sender : TObject);
begin
(*
0069FC28   55                     push    ebp
0069FC29   8BEC                   mov     ebp, esp
0069FC2B   B908000000             mov     ecx, $00000008
0069FC30   6A00                   push    $00
0069FC32   6A00                   push    $00
0069FC34   49                     dec     ecx
0069FC35   75F9                   jnz     0069FC30
0069FC37   53                     push    ebx
0069FC38   56                     push    esi
0069FC39   8BD8                   mov     ebx, eax
0069FC3B   33C0                   xor     eax, eax
0069FC3D   55                     push    ebp
0069FC3E   68E3FC6900             push    $0069FCE3

***** TRY
|
0069FC43   64FF30                 push    dword ptr fs:[eax]
0069FC46   648920                 mov     fs:[eax], esp
0069FC49   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdAltura : TJvValidateEdit
|
0069FC4C   8B8328030000           mov     eax, [ebx+$0328]

|
0069FC52   E86135FBFF             call    006531B8
0069FC57   8D45F0                 lea     eax, [ebp-$10]
0069FC5A   50                     push    eax
0069FC5B   8D45E0                 lea     eax, [ebp-$20]
0069FC5E   BA05000000             mov     edx, $00000005
0069FC63   B101                   mov     cl, $01

|
0069FC65   E8068ED7FF             call    00418A70
0069FC6A   8D55E0                 lea     edx, [ebp-$20]
0069FC6D   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069FC6E   E8D1D4D7FF             call    0041D144
0069FC73   7E38                   jle     0069FCAD
0069FC75   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdAltura : TJvValidateEdit
|
0069FC78   8BB328030000           mov     esi, [ebx+$0328]
0069FC7E   8BC6                   mov     eax, esi

|
0069FC80   E83335FBFF             call    006531B8
0069FC85   8D45D0                 lea     eax, [ebp-$30]
0069FC88   50                     push    eax
0069FC89   8D45C0                 lea     eax, [ebp-$40]
0069FC8C   BA05000000             mov     edx, $00000005
0069FC91   B101                   mov     cl, $01

|
0069FC93   E8D88DD7FF             call    00418A70
0069FC98   8D55C0                 lea     edx, [ebp-$40]
0069FC9B   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069FC9C   E80FD4D7FF             call    0041D0B0
0069FCA1   8D55D0                 lea     edx, [ebp-$30]
0069FCA4   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FCA6   E8E535FBFF             call    00653290
0069FCAB   EB15                   jmp     0069FCC2
0069FCAD   6A00                   push    $00
0069FCAF   668B0DF0FC6900         mov     cx, word ptr [$0069FCF0]
0069FCB6   33D2                   xor     edx, edx

* Possible String Reference to: 'A altura mÌnima È de 5!'
|
0069FCB8   B8FCFC6900             mov     eax, $0069FCFC

|
0069FCBD   E86A3EDAFF             call    00443B2C
0069FCC2   33C0                   xor     eax, eax
0069FCC4   5A                     pop     edx
0069FCC5   59                     pop     ecx
0069FCC6   59                     pop     ecx
0069FCC7   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069FCCA   68EAFC6900             push    $0069FCEA
0069FCCF   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069FCD2   8B1524114000           mov     edx, [$00401124]
0069FCD8   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069FCDD   E8BA63D6FF             call    0040609C
0069FCE2   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FCE3   E95050D6FF             jmp     00404D38
0069FCE8   EBE5                   jmp     0069FCCF

****** END
|
0069FCEA   5E                     pop     esi
0069FCEB   5B                     pop     ebx
0069FCEC   8BE5                   mov     esp, ebp
0069FCEE   5D                     pop     ebp
0069FCEF   C3                     ret

*)
end;

procedure TFrmCadMesas.sbLarguraUpClick(Sender : TObject);
begin
(*
0069FD14   55                     push    ebp
0069FD15   8BEC                   mov     ebp, esp
0069FD17   B908000000             mov     ecx, $00000008
0069FD1C   6A00                   push    $00
0069FD1E   6A00                   push    $00
0069FD20   49                     dec     ecx
0069FD21   75F9                   jnz     0069FD1C
0069FD23   53                     push    ebx
0069FD24   56                     push    esi
0069FD25   8BD8                   mov     ebx, eax
0069FD27   33C0                   xor     eax, eax
0069FD29   55                     push    ebp
0069FD2A   68CFFD6900             push    $0069FDCF

***** TRY
|
0069FD2F   64FF30                 push    dword ptr fs:[eax]
0069FD32   648920                 mov     fs:[eax], esp
0069FD35   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdLargura : TJvValidateEdit
|
0069FD38   8B8334030000           mov     eax, [ebx+$0334]

|
0069FD3E   E87534FBFF             call    006531B8
0069FD43   8D45F0                 lea     eax, [ebp-$10]
0069FD46   50                     push    eax
0069FD47   8D45E0                 lea     eax, [ebp-$20]
0069FD4A   BA64000000             mov     edx, $00000064
0069FD4F   B101                   mov     cl, $01

|
0069FD51   E81A8DD7FF             call    00418A70
0069FD56   8D55E0                 lea     edx, [ebp-$20]
0069FD59   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069FD5A   E8C5D3D7FF             call    0041D124
0069FD5F   7D38                   jnl     0069FD99
0069FD61   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdLargura : TJvValidateEdit
|
0069FD64   8BB334030000           mov     esi, [ebx+$0334]
0069FD6A   8BC6                   mov     eax, esi

|
0069FD6C   E84734FBFF             call    006531B8
0069FD71   8D45D0                 lea     eax, [ebp-$30]
0069FD74   50                     push    eax
0069FD75   8D45C0                 lea     eax, [ebp-$40]
0069FD78   BA05000000             mov     edx, $00000005
0069FD7D   B101                   mov     cl, $01

|
0069FD7F   E8EC8CD7FF             call    00418A70
0069FD84   8D55C0                 lea     edx, [ebp-$40]
0069FD87   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069FD88   E817D3D7FF             call    0041D0A4
0069FD8D   8D55D0                 lea     edx, [ebp-$30]
0069FD90   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FD92   E8F934FBFF             call    00653290
0069FD97   EB15                   jmp     0069FDAE
0069FD99   6A00                   push    $00
0069FD9B   668B0DDCFD6900         mov     cx, word ptr [$0069FDDC]
0069FDA2   33D2                   xor     edx, edx

* Possible String Reference to: 'A largura m·xima È de 100!'
|
0069FDA4   B8E8FD6900             mov     eax, $0069FDE8

|
0069FDA9   E87E3DDAFF             call    00443B2C
0069FDAE   33C0                   xor     eax, eax
0069FDB0   5A                     pop     edx
0069FDB1   59                     pop     ecx
0069FDB2   59                     pop     ecx
0069FDB3   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069FDB6   68D6FD6900             push    $0069FDD6
0069FDBB   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069FDBE   8B1524114000           mov     edx, [$00401124]
0069FDC4   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069FDC9   E8CE62D6FF             call    0040609C
0069FDCE   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FDCF   E9644FD6FF             jmp     00404D38
0069FDD4   EBE5                   jmp     0069FDBB

****** END
|
0069FDD6   5E                     pop     esi
0069FDD7   5B                     pop     ebx
0069FDD8   8BE5                   mov     esp, ebp
0069FDDA   5D                     pop     ebp
0069FDDB   C3                     ret

*)
end;

procedure TFrmCadMesas.sbLarguraDownClick(Sender : TObject);
begin
(*
0069FE04   55                     push    ebp
0069FE05   8BEC                   mov     ebp, esp
0069FE07   B908000000             mov     ecx, $00000008
0069FE0C   6A00                   push    $00
0069FE0E   6A00                   push    $00
0069FE10   49                     dec     ecx
0069FE11   75F9                   jnz     0069FE0C
0069FE13   53                     push    ebx
0069FE14   56                     push    esi
0069FE15   8BD8                   mov     ebx, eax
0069FE17   33C0                   xor     eax, eax
0069FE19   55                     push    ebp
0069FE1A   68BFFE6900             push    $0069FEBF

***** TRY
|
0069FE1F   64FF30                 push    dword ptr fs:[eax]
0069FE22   648920                 mov     fs:[eax], esp
0069FE25   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdLargura : TJvValidateEdit
|
0069FE28   8B8334030000           mov     eax, [ebx+$0334]

|
0069FE2E   E88533FBFF             call    006531B8
0069FE33   8D45F0                 lea     eax, [ebp-$10]
0069FE36   50                     push    eax
0069FE37   8D45E0                 lea     eax, [ebp-$20]
0069FE3A   BA05000000             mov     edx, $00000005
0069FE3F   B101                   mov     cl, $01

|
0069FE41   E82A8CD7FF             call    00418A70
0069FE46   8D55E0                 lea     edx, [ebp-$20]
0069FE49   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069FE4A   E8F5D2D7FF             call    0041D144
0069FE4F   7E38                   jle     0069FE89
0069FE51   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmCadMesas.EdLargura : TJvValidateEdit
|
0069FE54   8BB334030000           mov     esi, [ebx+$0334]
0069FE5A   8BC6                   mov     eax, esi

|
0069FE5C   E85733FBFF             call    006531B8
0069FE61   8D45D0                 lea     eax, [ebp-$30]
0069FE64   50                     push    eax
0069FE65   8D45C0                 lea     eax, [ebp-$40]
0069FE68   BA05000000             mov     edx, $00000005
0069FE6D   B101                   mov     cl, $01

|
0069FE6F   E8FC8BD7FF             call    00418A70
0069FE74   8D55C0                 lea     edx, [ebp-$40]
0069FE77   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0069FE78   E833D2D7FF             call    0041D0B0
0069FE7D   8D55D0                 lea     edx, [ebp-$30]
0069FE80   8BC6                   mov     eax, esi

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FE82   E80934FBFF             call    00653290
0069FE87   EB15                   jmp     0069FE9E
0069FE89   6A00                   push    $00
0069FE8B   668B0DCCFE6900         mov     cx, word ptr [$0069FECC]
0069FE92   33D2                   xor     edx, edx

* Possible String Reference to: 'A largura mÌnima È de 5!'
|
0069FE94   B8D8FE6900             mov     eax, $0069FED8

|
0069FE99   E88E3CDAFF             call    00443B2C
0069FE9E   33C0                   xor     eax, eax
0069FEA0   5A                     pop     edx
0069FEA1   59                     pop     ecx
0069FEA2   59                     pop     ecx
0069FEA3   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069FEA6   68C6FE6900             push    $0069FEC6
0069FEAB   8D45C0                 lea     eax, [ebp-$40]

* Reference to object Variant
|
0069FEAE   8B1524114000           mov     edx, [$00401124]
0069FEB4   B904000000             mov     ecx, $00000004

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069FEB9   E8DE61D6FF             call    0040609C
0069FEBE   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FEBF   E9744ED6FF             jmp     00404D38
0069FEC4   EBE5                   jmp     0069FEAB

****** END
|
0069FEC6   5E                     pop     esi
0069FEC7   5B                     pop     ebx
0069FEC8   8BE5                   mov     esp, ebp
0069FECA   5D                     pop     ebp
0069FECB   C3                     ret

*)
end;

procedure TFrmCadMesas.FormShow(Sender : TObject);
begin
(*
0069FEF4   55                     push    ebp
0069FEF5   8BEC                   mov     ebp, esp
0069FEF7   B90A000000             mov     ecx, $0000000A
0069FEFC   6A00                   push    $00
0069FEFE   6A00                   push    $00
0069FF00   49                     dec     ecx
0069FF01   75F9                   jnz     0069FEFC
0069FF03   53                     push    ebx
0069FF04   8BD8                   mov     ebx, eax
0069FF06   33C0                   xor     eax, eax
0069FF08   55                     push    ebp
0069FF09   681D006A00             push    $006A001D

***** TRY
|
0069FF0E   64FF30                 push    dword ptr fs:[eax]
0069FF11   648920                 mov     fs:[eax], esp
0069FF14   33C9                   xor     ecx, ecx

* Possible String Reference to: 'MESAS'
|
0069FF16   BA34006A00             mov     edx, $006A0034
0069FF1B   33C0                   xor     eax, eax

|
0069FF1D   E8CE9E1000             call    007A9DF0
0069FF22   8BD0                   mov     edx, eax
0069FF24   8D45F0                 lea     eax, [ebp-$10]
0069FF27   B1FC                   mov     cl, $FC

|
0069FF29   E8428BD7FF             call    00418A70
0069FF2E   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069FF31   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FF37   E85433FBFF             call    00653290
0069FF3C   8D55E0                 lea     edx, [ebp-$20]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069FF3F   8B8314030000           mov     eax, [ebx+$0314]

|
0069FF45   E86E32FBFF             call    006531B8
0069FF4A   8D45E0                 lea     eax, [ebp-$20]
0069FF4D   50                     push    eax
0069FF4E   8D45D0                 lea     eax, [ebp-$30]
0069FF51   33D2                   xor     edx, edx
0069FF53   B101                   mov     cl, $01

|
0069FF55   E8168BD7FF             call    00418A70
0069FF5A   8D55D0                 lea     edx, [ebp-$30]
0069FF5D   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069FF5E   E8E1D1D7FF             call    0041D144
0069FF63   0F8E93000000           jle     0069FFFC
0069FF69   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069FF6E   8B00                   mov     eax, [eax]
0069FF70   8B4068                 mov     eax, [eax+$68]

* Reference to : TFrmInfoAtu._PROC_007A66A4()
|
0069FF73   E82C671000             call    007A66A4
0069FF78   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069FF7D   8B00                   mov     eax, [eax]
0069FF7F   8B8088050000           mov     eax, [eax+$0588]
0069FF85   8B10                   mov     edx, [eax]
0069FF87   FF5258                 call    dword ptr [edx+$58]
0069FF8A   85C0                   test    eax, eax
0069FF8C   7E6E                   jle     0069FFFC
0069FF8E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069FF93   8B00                   mov     eax, [eax]
0069FF95   8B808C050000           mov     eax, [eax+$058C]
0069FF9B   8B10                   mov     edx, [eax]
0069FF9D   FF5258                 call    dword ptr [edx+$58]
0069FFA0   85C0                   test    eax, eax
0069FFA2   7E58                   jle     0069FFFC
0069FFA4   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069FFA9   8B00                   mov     eax, [eax]
0069FFAB   8B8088050000           mov     eax, [eax+$0588]
0069FFB1   8B10                   mov     edx, [eax]
0069FFB3   FF5258                 call    dword ptr [edx+$58]
0069FFB6   8BD0                   mov     edx, eax
0069FFB8   8D45C0                 lea     eax, [ebp-$40]
0069FFBB   B1FC                   mov     cl, $FC

|
0069FFBD   E8AE8AD7FF             call    00418A70
0069FFC2   8D55C0                 lea     edx, [ebp-$40]

* Reference to control TFrmCadMesas.EdAltura : TJvValidateEdit
|
0069FFC5   8B8328030000           mov     eax, [ebx+$0328]

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FFCB   E8C032FBFF             call    00653290
0069FFD0   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069FFD5   8B00                   mov     eax, [eax]
0069FFD7   8B808C050000           mov     eax, [eax+$058C]
0069FFDD   8B10                   mov     edx, [eax]
0069FFDF   FF5258                 call    dword ptr [edx+$58]
0069FFE2   8BD0                   mov     edx, eax
0069FFE4   8D45B0                 lea     eax, [ebp-$50]
0069FFE7   B1FC                   mov     cl, $FC

|
0069FFE9   E8828AD7FF             call    00418A70
0069FFEE   8D55B0                 lea     edx, [ebp-$50]

* Reference to control TFrmCadMesas.EdLargura : TJvValidateEdit
|
0069FFF1   8B8334030000           mov     eax, [ebx+$0334]

* Reference to : TJvValidateEdit._PROC_00653290()
|
0069FFF7   E89432FBFF             call    00653290
0069FFFC   33C0                   xor     eax, eax
0069FFFE   5A                     pop     edx
0069FFFF   59                     pop     ecx
006A0000   59                     pop     ecx
006A0001   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√'
|
006A0004   6824006A00             push    $006A0024
006A0009   8D45B0                 lea     eax, [ebp-$50]

* Reference to object Variant
|
006A000C   8B1524114000           mov     edx, [$00401124]
006A0012   B905000000             mov     ecx, $00000005

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
006A0017   E88060D6FF             call    0040609C
006A001C   C3                     ret


* Reference to: System.@HandleFinally;
|
006A001D   E9164DD6FF             jmp     00404D38
006A0022   EBE5                   jmp     006A0009

****** END
|
006A0024   5B                     pop     ebx
006A0025   8BE5                   mov     esp, ebp
006A0027   5D                     pop     ebp
006A0028   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069F36C(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
0069F36C   E9C759D6FF             jmp     00404D38

|
0069F371   EBEB                   jmp     0069F35E
0069F373   5F                     pop     edi
0069F374   5E                     pop     esi
0069F375   5B                     pop     ebx
0069F376   8BE5                   mov     esp, ebp
0069F378   5D                     pop     ebp
0069F379   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069F575(Sender : TObject);
begin
(*
0069F575   4E                     dec     esi
0069F576   43                     inc     ebx
0069F577   00FF                   add     bh, bh
0069F579   FFFF                   DB  $FF, $FF  //      
0069F57B   FF0400                 inc     dword ptr [eax+eax]
0069F57E   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069F5A6(Sender : TObject);
begin
(*
0069F5A6   4E                     dec     esi
0069F5A7   43                     inc     ebx
0069F5A8   52                     push    edx
0069F5A9   45                     inc     ebp
0069F5AA   50                     push    eax
0069F5AB   52                     push    edx
0069F5AC   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069F5C1(Sender : TObject);
begin
(*
0069F5C1   8BEC                   mov     ebp, esp
0069F5C3   83C4F4                 add     esp, -$0C
0069F5C6   53                     push    ebx
0069F5C7   56                     push    esi
0069F5C8   57                     push    edi
0069F5C9   33D2                   xor     edx, edx
0069F5CB   8955F4                 mov     [ebp-$0C], edx
0069F5CE   33C0                   xor     eax, eax
0069F5D0   55                     push    ebp
0069F5D1   68F7F66900             push    $0069F6F7

***** TRY
|
0069F5D6   64FF30                 push    dword ptr fs:[eax]
0069F5D9   648920                 mov     fs:[eax], esp
0069F5DC   C645FF00               mov     byte ptr [ebp-$01], $00
0069F5E0   33C0                   xor     eax, eax
0069F5E2   55                     push    ebp
0069F5E3   68DAF66900             push    $0069F6DA

***** TRY
|
0069F5E8   64FF30                 push    dword ptr fs:[eax]
0069F5EB   648920                 mov     fs:[eax], esp
0069F5EE   33C0                   xor     eax, eax
0069F5F0   55                     push    ebp
0069F5F1   6891F66900             push    $0069F691

***** TRY
|
0069F5F6   64FF30                 push    dword ptr fs:[eax]
0069F5F9   648920                 mov     fs:[eax], esp
0069F5FC   33C9                   xor     ecx, ecx

* Possible String Reference to: 'MESAS'
|
0069F5FE   BA10F76900             mov     edx, $0069F710
0069F603   33C0                   xor     eax, eax

|
0069F605   E8E6A71000             call    007A9DF0
0069F60A   85C0                   test    eax, eax
0069F60C   7E79                   jle     0069F687
0069F60E   6A00                   push    $00
0069F610   668B0D18F76900         mov     cx, word ptr [$0069F718]
0069F617   B203                   mov     dl, $03

* Possible String Reference to: 'Tem certeza que deseja limpar o cad
|                                astro?'
|
0069F619   B824F76900             mov     eax, $0069F724

|
0069F61E   E80945DAFF             call    00443B2C
0069F623   83F806                 cmp     eax, +$06
0069F626   755F                   jnz     0069F687
0069F628   6A00                   push    $00

* Possible String Reference to: 'MESAITEM'
|
0069F62A   B858F76900             mov     eax, $0069F758
0069F62F   8945F8                 mov     [ebp-$08], eax
0069F632   8D55F8                 lea     edx, [ebp-$08]
0069F635   33C9                   xor     ecx, ecx
0069F637   33C0                   xor     eax, eax

|
0069F639   E8EEB11000             call    007AA82C
0069F63E   6A00                   push    $00

* Possible String Reference to: 'MESALCTO'
|
0069F640   B86CF76900             mov     eax, $0069F76C
0069F645   8945F8                 mov     [ebp-$08], eax
0069F648   8D55F8                 lea     edx, [ebp-$08]
0069F64B   33C9                   xor     ecx, ecx
0069F64D   33C0                   xor     eax, eax

|
0069F64F   E8D8B11000             call    007AA82C
0069F654   6A00                   push    $00

* Possible String Reference to: 'MESAFUNC'
|
0069F656   B880F76900             mov     eax, $0069F780
0069F65B   8945F8                 mov     [ebp-$08], eax
0069F65E   8D55F8                 lea     edx, [ebp-$08]
0069F661   33C9                   xor     ecx, ecx
0069F663   33C0                   xor     eax, eax

|
0069F665   E8C2B11000             call    007AA82C
0069F66A   6A00                   push    $00

* Possible String Reference to: 'MESAS'
|
0069F66C   B810F76900             mov     eax, $0069F710
0069F671   8945F8                 mov     [ebp-$08], eax
0069F674   8D55F8                 lea     edx, [ebp-$08]
0069F677   33C9                   xor     ecx, ecx
0069F679   33C0                   xor     eax, eax

|
0069F67B   E8ACB11000             call    007AA82C
0069F680   33C0                   xor     eax, eax

|
0069F682   E875B31000             call    007AA9FC
0069F687   33C0                   xor     eax, eax
0069F689   5A                     pop     edx
0069F68A   59                     pop     ecx
0069F68B   59                     pop     ecx
0069F68C   648910                 mov     fs:[eax], edx
0069F68F   EB3B                   jmp     0069F6CC

* Reference to: System.@HandleOnException;
|
0069F691   E91A55D6FF             jmp     00404BB0
0069F696   0100                   add     [eax], eax
0069F698   0000                   add     [eax], al
0069F69A   40                     inc     eax
0069F69B   95                     xchg    eax, ebp
0069F69C   40                     inc     eax
0069F69D   00A2F6690089           add     [edx+$890069F6], ah
0069F6A3   C3                     ret

0069F6A4   6A00                   push    $00
0069F6A6   8B4B04                 mov     ecx, [ebx+$04]
0069F6A9   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'Erro ao limpar o cadastro anterior!'
|
0069F6AC   BA94F76900             mov     edx, $0069F794

* Reference to: System.@LStrCat3;
|
0069F6B1   E8F260D6FF             call    004057A8
0069F6B6   8B45F4                 mov     eax, [ebp-$0C]
0069F6B9   668B0DBCF76900         mov     cx, word ptr [$0069F7BC]
0069F6C0   B201                   mov     dl, $01

|
0069F6C2   E86544DAFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0069F6C7   E8E457D6FF             call    00404EB0

****** END
|
0069F6CC   33C0                   xor     eax, eax
0069F6CE   5A                     pop     edx
0069F6CF   59                     pop     ecx
0069F6D0   59                     pop     ecx
0069F6D1   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069F6D4   68E1F66900             push    $0069F6E1
0069F6D9   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F6DA   E95956D6FF             jmp     00404D38
0069F6DF   EBF8                   jmp     0069F6D9

****** END
|
0069F6E1   33C0                   xor     eax, eax
0069F6E3   5A                     pop     edx
0069F6E4   59                     pop     ecx
0069F6E5   59                     pop     ecx
0069F6E6   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069F6E9   68FEF66900             push    $0069F6FE
0069F6EE   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0069F6F1   E8A65DD6FF             call    0040549C
0069F6F6   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069F6F7(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
0069F6F7   E93C56D6FF             jmp     00404D38

|
0069F6FC   EBF0                   jmp     0069F6EE
0069F6FE   8A45FF                 mov     al, byte ptr [ebp-$01]
0069F701   5F                     pop     edi
0069F702   5E                     pop     esi
0069F703   5B                     pop     ebx
0069F704   8BE5                   mov     esp, ebp
0069F706   5D                     pop     ebp
0069F707   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069F786(Sender : TObject);
begin
(*
0069F786   4E                     dec     esi
0069F787   43                     inc     ebx
0069F788   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069F924(Sender : TObject);
begin
(*
0069F924   55                     push    ebp
0069F925   8BEC                   mov     ebp, esp
0069F927   B905000000             mov     ecx, $00000005
0069F92C   6A00                   push    $00
0069F92E   6A00                   push    $00
0069F930   49                     dec     ecx
0069F931   75F9                   jnz     0069F92C
0069F933   51                     push    ecx
0069F934   53                     push    ebx
0069F935   56                     push    esi
0069F936   57                     push    edi
0069F937   8BD8                   mov     ebx, eax
0069F939   33C0                   xor     eax, eax
0069F93B   55                     push    ebp

* Possible String Reference to: 'È∫R÷ˇÎ’äEˇ_^[ãÂ]√'
|
0069F93C   6879FA6900             push    $0069FA79

***** TRY
|
0069F941   64FF30                 push    dword ptr fs:[eax]
0069F944   648920                 mov     fs:[eax], esp
0069F947   C645FF01               mov     byte ptr [ebp-$01], $01
0069F94B   33C0                   xor     eax, eax
0069F94D   55                     push    ebp
0069F94E   6841FA6900             push    $0069FA41

***** TRY
|
0069F953   64FF30                 push    dword ptr fs:[eax]
0069F956   648920                 mov     fs:[eax], esp
0069F959   33C0                   xor     eax, eax
0069F95B   55                     push    ebp
0069F95C   68F8F96900             push    $0069F9F8

***** TRY
|
0069F961   64FF30                 push    dword ptr fs:[eax]
0069F964   648920                 mov     fs:[eax], esp
0069F967   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F96A   8B8314030000           mov     eax, [ebx+$0314]

|
0069F970   E84338FBFF             call    006531B8
0069F975   8D45EC                 lea     eax, [ebp-$14]
0069F978   50                     push    eax
0069F979   8D45DC                 lea     eax, [ebp-$24]
0069F97C   33D2                   xor     edx, edx
0069F97E   B101                   mov     cl, $01

|
0069F980   E8EB90D7FF             call    00418A70
0069F985   8D55DC                 lea     edx, [ebp-$24]
0069F988   58                     pop     eax

* Reference to: Variants.@VarCmpEQ(TVarData;TVarData;TVarData;TVarData);
|
0069F989   E8A6D7D7FF             call    0041D134
0069F98E   7F26                   jnle    0069F9B6
0069F990   6A00                   push    $00
0069F992   668B0D8CFA6900         mov     cx, word ptr [$0069FA8C]
0069F999   33D2                   xor     edx, edx

* Possible String Reference to: '… necess·rio informar o n˙mero de m
|                                esas!'
|
0069F99B   B898FA6900             mov     eax, $0069FA98

|
0069F9A0   E88741DAFF             call    00443B2C

* Reference to control TFrmCadMesas.EdNumMesas : TJvValidateEdit
|
0069F9A5   8B8314030000           mov     eax, [ebx+$0314]

|
0069F9AB   E830671000             call    007A60E0
0069F9B0   C645FF00               mov     byte ptr [ebp-$01], $00
0069F9B4   EB38                   jmp     0069F9EE
0069F9B6   8D55D8                 lea     edx, [ebp-$28]

* Reference to control TFrmCadMesas.EdCodFunc : TJvComboEdit
|
0069F9B9   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0069F9BF   E878E5E5FF             call    004FDF3C
0069F9C4   837DD800               cmp     dword ptr [ebp-$28], +$00
0069F9C8   7524                   jnz     0069F9EE
0069F9CA   6A00                   push    $00
0069F9CC   668B0D8CFA6900         mov     cx, word ptr [$0069FA8C]
0069F9D3   33D2                   xor     edx, edx

* Possible String Reference to: 'Informe o funcion·rio respons·vel p
|                                elas mesas!'
|
0069F9D5   B8CCFA6900             mov     eax, $0069FACC

|
0069F9DA   E84D41DAFF             call    00443B2C

* Reference to control TFrmCadMesas.EdCodFunc : TJvComboEdit
|
0069F9DF   8B8318030000           mov     eax, [ebx+$0318]

|
0069F9E5   E8F6661000             call    007A60E0
0069F9EA   C645FF00               mov     byte ptr [ebp-$01], $00
0069F9EE   33C0                   xor     eax, eax
0069F9F0   5A                     pop     edx
0069F9F1   59                     pop     ecx
0069F9F2   59                     pop     ecx
0069F9F3   648910                 mov     fs:[eax], edx
0069F9F6   EB3B                   jmp     0069FA33

* Reference to: System.@HandleOnException;
|
0069F9F8   E9B351D6FF             jmp     00404BB0
0069F9FD   0100                   add     [eax], eax
0069F9FF   0000                   add     [eax], al
0069FA01   40                     inc     eax
0069FA02   95                     xchg    eax, ebp
0069FA03   40                     inc     eax
0069FA04   0009                   add     [ecx], cl
0069FA06   FA                     cli
0069FA07   690089C36A00           imul    eax, [eax], $006AC389

* Reference to field TFrmCadMesas.Owner : TComponent
|
0069FA0D   8B4B04                 mov     ecx, [ebx+$04]
0069FA10   8D45D4                 lea     eax, [ebp-$2C]

* Possible String Reference to: 'Erro ao validar o cadastro de mesas
|                                !'
|
0069FA13   BA04FB6900             mov     edx, $0069FB04

* Reference to: System.@LStrCat3;
|
0069FA18   E88B5DD6FF             call    004057A8
0069FA1D   8B45D4                 mov     eax, [ebp-$2C]
0069FA20   668B0D8CFA6900         mov     cx, word ptr [$0069FA8C]
0069FA27   B201                   mov     dl, $01

|
0069FA29   E8FE40DAFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0069FA2E   E87D54D6FF             call    00404EB0

****** END
|
0069FA33   33C0                   xor     eax, eax
0069FA35   5A                     pop     edx
0069FA36   59                     pop     ecx
0069FA37   59                     pop     ecx
0069FA38   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069FA3B   6848FA6900             push    $0069FA48
0069FA40   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FA41   E9F252D6FF             jmp     00404D38
0069FA46   EBF8                   jmp     0069FA40

****** END
|
0069FA48   33C0                   xor     eax, eax
0069FA4A   5A                     pop     edx
0069FA4B   59                     pop     ecx
0069FA4C   59                     pop     ecx
0069FA4D   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äEˇ_^[ãÂ]√'
|
0069FA50   6880FA6900             push    $0069FA80
0069FA55   8D45D4                 lea     eax, [ebp-$2C]

* Reference to: System.@LStrClr(void;void);
|
0069FA58   E83F5AD6FF             call    0040549C
0069FA5D   8D45D8                 lea     eax, [ebp-$28]

* Reference to: System.@LStrClr(void;void);
|
0069FA60   E8375AD6FF             call    0040549C
0069FA65   8D45DC                 lea     eax, [ebp-$24]

* Reference to object Variant
|
0069FA68   8B1524114000           mov     edx, [$00401124]
0069FA6E   B902000000             mov     ecx, $00000002

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0069FA73   E82466D6FF             call    0040609C
0069FA78   C3                     ret


* Reference to: System.@HandleFinally;
|
0069FA79   E9BA52D6FF             jmp     00404D38
0069FA7E   EBD5                   jmp     0069FA55

****** END
|
0069FA80   8A45FF                 mov     al, byte ptr [ebp-$01]
0069FA83   5F                     pop     edi
0069FA84   5E                     pop     esi
0069FA85   5B                     pop     ebx
0069FA86   8BE5                   mov     esp, ebp
0069FA88   5D                     pop     ebp
0069FA89   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069FA79(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
0069FA79   E9BA52D6FF             jmp     00404D38

|
0069FA7E   EBD5                   jmp     0069FA55
0069FA80   8A45FF                 mov     al, byte ptr [ebp-$01]
0069FA83   5F                     pop     edi
0069FA84   5E                     pop     esi
0069FA85   5B                     pop     ebx
0069FA86   8BE5                   mov     esp, ebp
0069FA88   5D                     pop     ebp
0069FA89   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_0069FC00(Sender : TObject);
begin
(*
0069FC00   0400                   add     al, +$00
0069FC02   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069FCF0(Sender : TObject);
begin
(*
0069FCF0   0400                   add     al, +$00
0069FCF2   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069FDDC(Sender : TObject);
begin
(*
0069FDDC   0400                   add     al, +$00
0069FDDE   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_0069FECC(Sender : TObject);
begin
(*
0069FECC   0400                   add     al, +$00
0069FECE   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_006A003D(Sender : TObject);
begin
(*
006A003D   8BEC                   mov     ebp, esp
006A003F   33C0                   xor     eax, eax
006A0041   55                     push    ebp
006A0042   6861006A00             push    $006A0061

***** TRY
|
006A0047   64FF30                 push    dword ptr fs:[eax]
006A004A   648920                 mov     fs:[eax], esp
006A004D   FF0518ED7D00           inc     dword ptr [$007DED18]
006A0053   33C0                   xor     eax, eax
006A0055   5A                     pop     edx
006A0056   59                     pop     ecx
006A0057   59                     pop     ecx
006A0058   648910                 mov     fs:[eax], edx

****** FINALLY
|
006A005B   6868006A00             push    $006A0068
006A0060   C3                     ret


* Reference to: System.@HandleFinally;
|
006A0061   E9D24CD6FF             jmp     00404D38
006A0066   EBF8                   jmp     006A0060

****** END
|
006A0068   5D                     pop     ebp
006A0069   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_006A006C(Sender : TObject);
begin
(*
006A006C   832D18ED7D0001         sub     dword ptr [$007DED18], +$01
006A0073   C3                     ret

*)
end;

procedure TFrmCadMesas._PROC_006A0074(Sender : TObject);
begin
(*
006A0074   C0006A                 rol     byte ptr [eax], $6A
006A0077   0000                   add     [eax], al

*)
end;

procedure TFrmCadMesas._PROC_006A030B(Sender : TObject);
begin
(*
006A030B   4E                     dec     esi
006A030C   49                     dec     ecx
006A030D   54                     push    esp
006A030E   44                     inc     esp
006A030F   0300                   add     eax, [eax]
006A0311   000B                   add     [ebx], cl
006A0313   000F                   add     [edi], cl
006A0315   7462                   jz      006A0379
006A0317   49                     dec     ecx
006A0318   7465                   jz      006A037F
006A031A   6E                     outsb
006A031B   7356                   jnb     006A0373
006A031D   4C                     dec     esp
006A031E   52                     push    edx
006A031F   54                     push    esp
006A0320   4F                     dec     edi
006A0321   54                     push    esp
006A0322   41                     inc     ecx
006A0323   4C                     dec     esp
006A0324   48                     dec     eax
006A0325   0300                   add     eax, [eax]
006A0327   000A                   add     [edx], cl
006A0329   000E                   add     [esi], cl
006A032B   7462                   jz      006A038F
006A032D   49                     dec     ecx
006A032E   7465                   jz      006A0395
006A0330   6E                     outsb
006A0331   7343                   jnb     006A0376
006A0333   4F                     dec     edi
006A0334   44                     inc     esp
006A0335   46                     inc     esi
006A0336   55                     push    ebp
006A0337   4E                     dec     esi
006A0338   43                     inc     ebx
006A0339   4C                     dec     esp
006A033A   0300                   add     eax, [eax]
006A033C   000A                   add     [edx], cl
006A033E   000D74624974           add     [$74496274], cl
006A0344   656E                   outsb
006A0346   7353                   jnb     006A039B
006A0348   54                     push    esp
006A0349   41                     inc     ecx
006A034A   54                     push    esp
006A034B   55                     push    ebp
006A034C   53                     push    ebx
006A034D   50                     push    eax
006A034E   0300                   add     eax, [eax]
006A0350   000400                 add     [eax+eax], al
006A0353   087076                 or      [eax+$76], dh
006A0356   52                     push    edx
006A0357   6F                     outsd
006A0358   6461                   popa
006A035A   7065                   jo      006A03C1
006A035C   54                     push    esp
006A035D   0300                   add     eax, [eax]
006A035F   000500096274           add     [$74620900], al
006A0365   41                     inc     ecx
006A0366   7465                   jz      006A03CD
006A0368   6E                     outsb
006A0369   64657258               jb      006A03C5
006A036D   0300                   add     eax, [eax]
006A036F   000500086274           add     [$74620800], al
006A0375   46                     inc     esi
006A0376   65636861               arpl    gs:[eax+$61], bp
006A037A   725C                   jb      006A03D8
006A037C   0300                   add     eax, [eax]
006A037E   0005000A6274           add     [$74620A00], al
006A0384   43                     inc     ebx
006A0385   61                     popa
006A0386   6E                     outsb
006A0387   63656C                 arpl    [ebp+$6C], sp
006A038A   61                     popa
006A038B   7260                   jb      006A03ED
006A038D   0300                   add     eax, [eax]
006A038F   000C00                 add     [eax+eax], cl
006A0392   0B746D72               or      esi, [ebp+ebp*2+$72]
006A0396   47                     inc     edi
006A0397   657265                 jb      006A03FF
006A039A   49                     dec     ecx
006A039B   7465                   jz      006A0402
006A039D   6D                     insd
006A039E   640300                 add     eax, fs:[eax]
006A03A1   0009                   add     [ecx], cl
006A03A3   000E                   add     [esi], cl
006A03A5   7462                   jz      006A0409
006A03A7   49                     dec     ecx
006A03A8   7465                   jz      006A040F
006A03AA   6E                     outsb
006A03AB   734E                   jnb     006A03FB
006A03AD   55                     push    ebp
006A03AE   4D                     dec     ebp
006A03AF   4C                     dec     esp
006A03B0   43                     inc     ebx
006A03B1   54                     push    esp
006A03B2   4F                     dec     edi
006A03B3   680300000A             push    $0A000003
006A03B8   000E                   add     [esi], cl
006A03BA   7462                   jz      006A041E
006A03BC   49                     dec     ecx
006A03BD   7465                   jz      006A0424
006A03BF   6E                     outsb
006A03C0   7355                   jnb     006A0417
006A03C2   4E                     dec     esi
006A03C3   49                     dec     ecx
006A03C4   44                     inc     esp
006A03C5   4D                     dec     ebp
006A03C6   45                     inc     ebp
006A03C7   44                     inc     esp
006A03C8   6C                     insb
006A03C9   0300                   add     eax, [eax]
006A03CB   000B                   add     [ebx], cl
006A03CD   0012                   add     [edx], dl
006A03CF   7462                   jz      006A0433
006A03D1   49                     dec     ecx
006A03D2   7465                   jz      006A0439
006A03D4   6E                     outsb
006A03D5   7351                   jnb     006A0428
006A03D7   54                     push    esp
006A03D8   44                     inc     esp
006A03D9   45                     inc     ebp
006A03DA   55                     push    ebp
006A03DB   4E                     dec     esi
006A03DC   49                     dec     ecx
006A03DD   44                     inc     esp
006A03DE   4D                     dec     ebp
006A03DF   45                     inc     ebp
006A03E0   44                     inc     esp
006A03E1   7003                   jo      006A03E6
006A03E3   0000                   add     [eax], al

006A03E5   0500076274             add     eax, +$74620700
006A03EA   54                     push    esp
006A03EB   6F                     outsd
006A03EC   646F                   outsd
006A03EE   7374                   jnb     006A0464
006A03F0   0300                   add     eax, [eax]
006A03F2   0000                   add     [eax], al

006A03F4   0006                   add     [esi], al
006A03F6   4C                     dec     esp
006A03F7   61                     popa
006A03F8   62656C                 bound   esp, qword ptr [ebp+$6C]
006A03FB   317803                 xor     [eax+$03], edi
006A03FE   0000                   add     [eax], al

006A0400   07                     pop     es
006A0401   000C6564436F64         add     [$646F4364], cl
006A0408   44                     inc     esp
006A0409   657374                 jnb     006A0480
006A040C   696E6F7C030000         imul    ebp, [esi+$6F], $0000037C
006A0413   06                     push    es
006A0414   0009                   add     [ecx], cl
006A0416   45                     inc     ebp
006A0417   6444                   inc     esp
006A0419   657374                 jnb     006A0490
006A041C   696E6F80030000         imul    ebp, [esi+$6F], $00000380
006A0423   0500074269             add     eax, +$69420700
006A0428   7442                   jz      006A046C
006A042A   746E                   jz      006A049A
006A042C   31840300000D00         xor     [ebx+eax+$D0000], eax
006A0433   0E                     push    cs
006A0434   7462                   jz      006A0498
006A0436   49                     dec     ecx
006A0437   7465                   jz      006A049E
006A0439   6E                     outsb
006A043A   7344                   jnb     006A0480
006A043C   41                     inc     ecx
006A043D   54                     push    esp
006A043E   41                     inc     ecx
006A043F   52                     push    edx
006A0440   45                     inc     ebp
006A0441   51                     push    ecx
006A0442   8803                   mov     [ebx], al
006A0444   0000                   add     [eax], al

006A0446   0A00                   or      al, byte ptr [eax]
006A0448   0E                     push    cs
006A0449   7462                   jz      006A04AD
006A044B   49                     dec     ecx
006A044C   7465                   jz      006A04B3
006A044E   6E                     outsb
006A044F   7346                   jnb     006A0497
006A0451   45                     inc     ebp
006A0452   43                     inc     ebx
006A0453   48                     dec     eax
006A0454   41                     inc     ecx
006A0455   44                     inc     esp
006A0456   4F                     dec     edi
006A0457   8C03                   mov     word ptr [ebx], es
006A0459   0000                   add     [eax], al

006A045B   0900                   or      [eax], eax
006A045D   0E                     push    cs
006A045E   7462                   jz      006A04C2
006A0460   49                     dec     ecx
006A0461   7465                   jz      006A04C8
006A0463   6E                     outsb
006A0464   7343                   jnb     006A04A9
006A0466   4F                     dec     edi
006A0467   44                     inc     esp
006A0468   49                     dec     ecx
006A0469   4D                     dec     ebp
006A046A   50                     push    eax
006A046B   52                     push    edx
006A046C   90                     nop
006A046D   0300                   add     eax, [eax]
006A046F   000A                   add     [edx], cl
006A0471   000F                   add     [edi], cl
006A0473   7462                   jz      006A04D7
006A0475   49                     dec     ecx
006A0476   7465                   jz      006A04DD
006A0478   6E                     outsb
006A0479   7349                   jnb     006A04C4
006A047B   4D                     dec     ebp
006A047C   50                     push    eax
006A047D   52                     push    edx
006A047E   45                     inc     ebp
006A047F   53                     push    ebx
006A0480   53                     push    ebx
006A0481   4F                     dec     edi
006A0482   94                     xchg    eax, esp
006A0483   0300                   add     eax, [eax]
006A0485   000A                   add     [edx], cl
006A0487   000D74624974           add     [$74496274], cl
006A048D   656E                   outsb
006A048F   7356                   jnb     006A04E7
006A0491   49                     dec     ecx
006A0492   41                     inc     ecx
006A0493   47                     inc     edi
006A0494   45                     inc     ebp
006A0495   4D                     dec     ebp
006A0496   98                     cwde 
006A0497   0300                   add     eax, [eax]
006A0499   000A                   add     [edx], cl
006A049B   000F                   add     [edi], cl
006A049D   7462                   jz      006A0501
006A049F   49                     dec     ecx
006A04A0   7465                   jz      006A0507
006A04A2   6E                     outsb
006A04A3   7348                   jnb     006A04ED
006A04A5   52                     push    edx
006A04A6   52                     push    edx
006A04A7   45                     inc     ebp
006A04A8   51                     push    ecx
006A04A9   55                     push    ebp
006A04AA   49                     dec     ecx
006A04AB   53                     push    ebx
006A04AC   9C                     pushf   
006A04AD   0300                   add     eax, [eax]
006A04AF   000A                   add     [edx], cl
006A04B1   0010                   add     [eax], dl
006A04B3   7462                   jz      006A0517
006A04B5   49                     dec     ecx
006A04B6   7465                   jz      006A051D
006A04B8   6E                     outsb
006A04B9   7348                   jnb     006A0503
006A04BB   49                     dec     ecx
006A04BC   53                     push    ebx
006A04BD   54                     push    esp
006A04BE   4F                     dec     edi
006A04BF   52                     push    edx
006A04C0   49                     dec     ecx
006A04C1   43                     inc     ebx
006A04C2   4F                     dec     edi
006A04C3   A00300000A             mov     al, byte ptr [$0A000003]
006A04C8   000E                   add     [esi], cl
006A04CA   7462                   jz      006A052E
006A04CC   49                     dec     ecx
006A04CD   7465                   jz      006A0534
006A04CF   6E                     outsb
006A04D0   7348                   jnb     006A051A
006A04D2   52                     push    edx
006A04D3   41                     inc     ecx
006A04D4   54                     push    esp
006A04D5   45                     inc     ebp
006A04D6   4E                     dec     esi
006A04D7   44                     inc     esp
006A04D8   A4                     movsb
006A04D9   0300                   add     eax, [eax]
006A04DB   000500074269           add     [$69420700], al
006A04E1   7442                   jz      006A0525
006A04E3   746E                   jz      006A0553
006A04E5   32A80300000E           xor     ch, byte ptr [eax+$E000003]
006A04EB   0008                   add     [eax], cl
006A04ED   49                     dec     ecx
006A04EE   42                     inc     edx
006A04EF   54                     push    esp
006A04F0   61                     popa
006A04F1   626C6531               bound   ebp, qword ptr [ebp+$31]
006A04F5   AC                     lodsb
006A04F6   0300                   add     eax, [eax]
006A04F8   000A                   add     [edx], cl
006A04FA   0012                   add     [edx], dl
006A04FC   49                     dec     ecx
006A04FD   42                     inc     edx
006A04FE   54                     push    esp
006A04FF   61                     popa
006A0500   626C6531               bound   ebp, qword ptr [ebp+$31]
006A0504   43                     inc     ebx
006A0505   4F                     dec     edi
006A0506   44                     inc     esp
006A0507   43                     inc     ebx
006A0508   4F                     dec     edi
006A0509   4D                     dec     ebp
006A050A   41                     inc     ecx
006A050B   4E                     dec     esi
006A050C   44                     inc     esp
006A050D   41                     inc     ecx
006A050E   B003                   mov     al, $03
006A0510   0000                   add     [eax], al

006A0512   0900                   or      [eax], eax
006A0514   0F494254               cmovns  eax, [edx+$54]
006A0518   61                     popa
006A0519   626C6531               bound   ebp, qword ptr [ebp+$31]
006A051D   43                     inc     ebx
006A051E   4F                     dec     edi
006A051F   44                     inc     esp
006A0520   4D                     dec     ebp
006A0521   45                     inc     ebp
006A0522   53                     push    ebx
006A0523   41                     inc     ecx
006A0524   B403                   mov     ah, $03
006A0526   0000                   add     [eax], al

006A0528   0F0011                 lldt    word ptr [ecx]
006A052B   7462                   jz      006A058F
006A052D   49                     dec     ecx
006A052E   7465                   jz      006A0595
006A0530   6E                     outsb
006A0531   7343                   jnb     006A0576
006A0533   4F                     dec     edi
006A0534   44                     inc     esp
006A0535   43                     inc     ebx
006A0536   4F                     dec     edi
006A0537   4D                     dec     ebp
006A0538   41                     inc     ecx
006A0539   4E                     dec     esi
006A053A   44                     inc     esp
006A053B   41                     inc     ecx
006A053C   1300                   adc     eax, [eax]
006A053E   1100                   adc     [eax], eax
006A0540   140D                   adc     al, $0D
006A0542   6A00                   push    $00
006A0544   0A466F                 or      al, byte ptr [esi+$6F]
006A0547   726D                   jb      006A05B6
006A0549   43                     inc     ebx
006A054A   7265                   jb      006A05B1
006A054C   61                     popa
006A054D   7465                   jz      006A05B4
006A054F   0F0018                 ltr     word ptr [eax]
006A0552   0D6A000846             or      eax, $4608006A
006A0557   6F                     outsd
006A0558   726D                   jb      006A05C7
006A055A   53                     push    ebx
006A055B   686F771000             push    $0010776F
006A0560   50                     push    eax
006A0561   0D6A000946             or      eax, $4609006A
006A0566   6F                     outsd
006A0567   726D                   jb      006A05D6
006A0569   43                     inc     ebx
006A056A   6C                     insb
006A056B   6F                     outsd
006A056C   7365                   jnb     006A05D3
006A056E   15005C0D6A             adc     eax, $6A0D5C00
006A0573   000E                   add     [esi], cl
006A0575   62744669               bound   esi, qword ptr [esi+eax*2+$69]
006A0579   6C                     insb
006A057A   7472                   jz      006A05EE
006A057C   61                     popa
006A057D   7243                   jb      006A05C2
006A057F   6C                     insb
006A0580   69636B1B00680D         imul    esp, [ebx+$6B], $0D68001B
006A0587   6A00                   push    $00
006A0589   1465                   adc     al, $65
006A058B   6443                   inc     ebx
006A058D   6F                     outsd
006A058E   6446                   inc     esi
006A0590   756E                   jnz     006A0600
006A0592   634275                 arpl    [edx+$75], ax
006A0595   7474                   jz      006A060B
006A0597   6F                     outsd
006A0598   6E                     outsb
006A0599   43                     inc     ebx
006A059A   6C                     insb
006A059B   69636B1B00CC0E         imul    esp, [ebx+$6B], $0ECC001B
006A05A2   6A00                   push    $00
006A05A4   1465                   adc     al, $65
006A05A6   6443                   inc     ebx
006A05A8   6F                     outsd
006A05A9   644D                   dec     ebp
006A05AB   657361                 jnb     006A060F
006A05AE   42                     inc     edx
006A05AF   7574                   jnz     006A0625
006A05B1   746F                   jz      006A0622
006A05B3   6E                     outsb
006A05B4   43                     inc     ebx
006A05B5   6C                     insb
006A05B6   69636B15002010         imul    esp, [ebx+$6B], $10200015
006A05BD   6A00                   push    $00
006A05BF   0E                     push    cs
006A05C0   62744174               bound   esi, qword ptr [ecx+eax*2+$74]
006A05C4   656E                   outsb
006A05C6   64657243               jb      006A060D
006A05CA   6C                     insb
006A05CB   69636B1600D410         imul    esp, [ebx+$6B], $10D40016
006A05D2   6A00                   push    $00
006A05D4   0F62744361             punpckldq MM6, [ebx+eax*2+$61]
006A05D9   6E                     outsb
006A05DA   63656C                 arpl    [ebp+$6C], sp
006A05DD   61                     popa
006A05DE   7243                   jb      006A0623
006A05E0   6C                     insb
006A05E1   69636B20003C12         imul    esp, [ebx+$6B], $123C0020
006A05E8   6A00                   push    $00
006A05EA   19646267               sbb     [edx+$67], esp
006A05EE   4D                     dec     ebp
006A05EF   657361                 jnb     006A0653
006A05F2   49                     dec     ecx
006A05F3   7465                   jz      006A065A
006A05F5   6D                     insd
006A05F6   44                     inc     esp
006A05F7   7261                   jb      006A065A
006A05F9   7743                   jnbe    006A063E
006A05FB   6F                     outsd
006A05FC   6C                     insb
006A05FD   756D                   jnz     006A066C
006A05FF   6E                     outsb
006A0600   43                     inc     ebx
006A0601   656C                   insb
006A0603   6C                     insb
006A0604   17                     pop     ss
006A0605   0064156A               add     [ebp+edx+$6A], ah
006A0609   0010                   add     [eax], dl
006A060B   746D                   jz      006A067A
006A060D   7247                   jb      006A0656
006A060F   657265                 jb      006A0677
006A0612   49                     dec     ecx
006A0613   7465                   jz      006A067A
006A0615   6D                     insd
006A0616   54                     push    esp
006A0617   696D65721F0070         imul    ebp, [ebp+$65], $70001F72
006A061E   156A001864             adc     eax, $6418006A
006A0623   62674D                 bound   esp, qword ptr [edi+$4D]
006A0626   657361                 jnb     006A068A
006A0629   49                     dec     ecx
006A062A   7465                   jz      006A0691
006A062C   6D                     insd
006A062D   54                     push    esp
006A062E   69746C6542746E43       imul    esi, [esp+ebp*2+$65], $436E7442
006A0636   6C                     insb
006A0637   69636B13008C16         imul    esp, [ebx+$6B], $168C0013
006A063E   6A00                   push    $00
006A0640   0C62                   or      al, $62
006A0642   7454                   jz      006A0698
006A0644   6F                     outsd
006A0645   646F                   outsd
006A0647   7343                   jnb     006A068C
006A0649   6C                     insb
006A064A   69636B13006017         imul    esp, [ebx+$6B], $17600013
006A0651   6A00                   push    $00
006A0653   0C65                   or      al, $65
006A0655   644D                   dec     ebp
006A0657   657361                 jnb     006A06BB
006A065A   43                     inc     ebx
006A065B   68616E6765             push    $65676E61
006A0660   16                     push    ss
006A0661   00B8176A000F           add     [eax+$F006A17], bh
006A0667   656443                 inc     ebx
006A066A   6F                     outsd
006A066B   644D                   dec     ebp
006A066D   657361                 jnb     006A06D1
006A0670   43                     inc     ebx
006A0671   68616E6765             push    $65676E61
006A0676   1E                     push    ds
006A0677   00B4186A001765         add     [eax+ebx+$6517006A], dh
006A067E   6443                   inc     ebx
006A0680   6F                     outsd
006A0681   6444                   inc     esp
006A0683   657374                 jnb     006A06FA
006A0686   696E6F42757474         imul    ebp, [esi+$6F], $74747542
006A068D   6F                     outsd
006A068E   6E                     outsb
006A068F   43                     inc     ebx
006A0690   6C                     insb
006A0691   69636B1900B819         imul    esp, [ebx+$6B], $19B80019
006A0698   6A00                   push    $00
006A069A   126564                 adc     ah, byte ptr [ebp+$64]
006A069D   43                     inc     ebx
006A069E   6F                     outsd
006A069F   6444                   inc     esp
006A06A1   657374                 jnb     006A0718
006A06A4   696E6F4368616E         imul    ebp, [esi+$6F], $6E616843
006A06AB   67651300               adc     eax, gs:[bx+si]
006A06AF   B81A6A000C             mov     eax, $0C006A1A
006A06B4   42                     inc     edx
006A06B5   697442746E31436C       imul    esi, [edx+eax*2+$74], $6C43316E
006A06BD   69636B1300AC1B         imul    esp, [ebx+$6B], $1BAC0013
006A06C4   6A00                   push    $00
006A06C6   0C42                   or      al, $42
006A06C8   697442746E32436C       imul    esi, [edx+eax*2+$74], $6C43326E
006A06D0   69636B1900B81B         imul    esp, [ebx+$6B], $1BB80019
006A06D7   6A00                   push    $00
006A06D9   12646267               adc     ah, byte ptr [edx+$67]
006A06DD   4D                     dec     ebp
006A06DE   657361                 jnb     006A0742
006A06E1   49                     dec     ecx
006A06E2   7465                   jz      006A0749
006A06E4   6D                     insd
006A06E5   4B                     dec     ebx
006A06E6   657944                 jns     006A072D
006A06E9   6F                     outsd
006A06EA   776E                   jnbe    006A075A
006A06EC   0C54                   or      al, $54
006A06EE   66726D                 jb      006A075E
006A06F1   47                     inc     edi
006A06F2   657265                 jb      006A075A
006A06F5   49                     dec     ecx
006A06F6   7465                   jz      006A075D
006A06F8   6D                     insd
006A06F9   1000                   adc     [eax], al
006A06FB   04F4                   add     al, -$0C
006A06FD   47                     inc     edi
006A06FE   00A0DB5C00B4           add     [eax+$B4005CDB], ah
006A0704   A5                     movsd
006A0705   55                     push    ebp
006A0706   0064A84D               add     [eax+ebp*4+$4D], ah
006A070A   008856440070           add     [eax+$70004456], cl
006A0710   CF                     iret
006A0711   44                     inc     esp
006A0712   00A0FC47002C           add     [eax+$2C0047FC], ah
006A0718   FD                     std
006A0719   58                     pop     eax
006A071A   00DC                   add     ah, bl
006A071C   6D                     insd
006A071D   44                     inc     esp
006A071E   0044754D               add     [ebp+esi*2+$4D], al
006A0722   0018                   add     [eax], bl
006A0724   97                     xchg    eax, edi
006A0725   55                     push    ebp
006A0726   00A87C4D00F8           add     [eax+$F8004D7C], ch
006A072C   53                     push    ebx
006A072D   44                     inc     esp
006A072E   00CC                   add     ah, cl
006A0730   814D00E4C05900         or      dword ptr [ebp+$00], $0059C0E4
006A0737   08704D                 or      [eax+$4D], dh
006A073A   009040076A00           add     [eax+$6A0740], dl
006A0740   07                     pop     es
006A0741   0C54                   or      al, $54
006A0743   66726D                 jb      006A07B3
006A0746   47                     inc     edi
006A0747   657265                 jb      006A07AF
006A074A   49                     dec     ecx
006A074B   7465                   jz      006A07B2
006A074D   6D                     insd
006A074E   C0006A                 rol     byte ptr [eax], $6A
006A0751   0038                   add     [eax], bh
006A0753   B44A                   mov     ah, $4A
006A0755   005E00                 add     [esi+$00], bl
006A0758   084765                 or      [edi+$65], al
006A075B   7265                   jb      006A07C2
006A075D   49                     dec     ecx
006A075E   7465                   jz      006A07C5
006A0760   6D                     insd
006A0761   0000                   add     [eax], al

006A0763   90                     nop
006A0764   55                     push    ebp
006A0765   8BEC                   mov     ebp, esp
006A0767   51                     push    ecx

* Possible String Reference to: 'grill.ini'
|
006A0768   B9B4076A00             mov     ecx, $006A07B4
006A076D   B201                   mov     dl, $01

* Reference to class TIniFile
|
006A076F   A1540F4500             mov     eax, dword ptr [$00450F54]

* Reference to: IniFiles.TCustomIniFile.Create(TCustomIniFile;boolean;AnsiString);
|
006A0774   E88B08DBFF             call    00451004
006A0779   8945FC                 mov     [ebp-$04], eax
006A077C   33C0                   xor     eax, eax
006A077E   55                     push    ebp

* Possible String Reference to: 'ÈìE÷ˇÎY]√'
|
006A077F   68A0076A00             push    $006A07A0

***** TRY
|
006A0784   64FF30                 push    dword ptr fs:[eax]
006A0787   648920                 mov     fs:[eax], esp
006A078A   33C0                   xor     eax, eax
006A078C   5A                     pop     edx
006A078D   59                     pop     ecx
006A078E   59                     pop     ecx
006A078F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'Y]√'
|
006A0792   68A7076A00             push    $006A07A7
006A0797   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
006A079A   E8FD3DD6FF             call    0040459C
006A079F   C3                     ret


* Reference to: System.@HandleFinally;
|
006A07A0   E99345D6FF             jmp     00404D38
006A07A5   EBF0                   jmp     006A0797

****** END
|
006A07A7   59                     pop     ecx
006A07A8   5D                     pop     ebp
006A07A9   C3                     ret

006A07AA   0000                   add     [eax], al

006A07AC   FFFF                   DB  $FF, $FF  //      
006A07AE   FFFF                   DB  $FF, $FF  //      
006A07B0   0900                   or      [eax], eax
006A07B2   0000                   add     [eax], al

006A07B4   677269                 jb      006A0820
006A07B7   6C                     insb
006A07B8   6C                     insb
006A07B9   2E696E6900000055       imul    ebp, cs:[esi+$69], $55000000
006A07C1   8BEC                   mov     ebp, esp
006A07C3   51                     push    ecx

* Possible String Reference to: 'grill.ini'
|
006A07C4   B910086A00             mov     ecx, $006A0810
006A07C9   B201                   mov     dl, $01

* Reference to class TIniFile
|
006A07CB   A1540F4500             mov     eax, dword ptr [$00450F54]

* Reference to: IniFiles.TCustomIniFile.Create(TCustomIniFile;boolean;AnsiString);
|
006A07D0   E82F08DBFF             call    00451004
006A07D5   8945FC                 mov     [ebp-$04], eax
006A07D8   33C0                   xor     eax, eax
006A07DA   55                     push    ebp

* Possible String Reference to: 'È7E÷ˇÎY]√'
|
006A07DB   68FC076A00             push    $006A07FC

***** TRY
|
006A07E0   64FF30                 push    dword ptr fs:[eax]
006A07E3   648920                 mov     fs:[eax], esp
006A07E6   33C0                   xor     eax, eax
006A07E8   5A                     pop     edx
006A07E9   59                     pop     ecx
006A07EA   59                     pop     ecx
006A07EB   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'Y]√'
|
006A07EE   6803086A00             push    $006A0803
006A07F3   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
006A07F6   E8A13DD6FF             call    0040459C
006A07FB   C3                     ret

*)
end;

end.