unit CancProd;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, ExtCtrls, Grids, DBGrids,
  JvExDBGrids, JvDBGrid;
  
type
  TfrmCancelaProduto=class(TForm)
    dbgMesaItem: TJvDBGrid;
    lbTitulo: TLabel;
    pnTopo: TPanel;
    edNumItem: TEdit;
    Label1: TLabel;
    btCancelar: TBitBtn;
    lbVlrTotal: TLabel;
    Bevel1: TBevel;
    Bevel2: TBevel;
    btFechar: TBitBtn;
    Shape1: TShape;
    Label9: TLabel;
    Shape2: TShape;
    Label10: TLabel;
    Shape3: TShape;
    Label11: TLabel;
    Label2: TLabel;
    btDesfaz: TBitBtn;
    lbMesa: TLabel;
    edMesa: TEdit;
    lbCliente: TLabel;
    EdCliente: TEdit;
    lbFuncionario: TLabel;
    EdFuncionario: TEdit;
    lbDataIni: TLabel;
    EdInicio: TEdit;
    lbDataFim: TLabel;
    EdUltAtend: TEdit;
    lbNumPess: TLabel;
    EdNumPessoas: TEdit;
    procedure btCancelarClick(Sender : TObject);
    procedure dbgMesaItemGetCellParams(Sender : TObject);
    procedure edNumItemKeyDown(Sender : TObject);
    procedure dbgMesaItemDblClick(Sender : TObject);
    procedure btDesfazClick(Sender : TObject);
    procedure dbgMesaItemCellClick(Sender : TObject);
    procedure _PROC_00690FAC(Sender : TObject);
    procedure _PROC_00691002(Sender : TObject);
    procedure _PROC_00691065(Sender : TObject);
    procedure _PROC_00691075(Sender : TObject);
    procedure _PROC_00691086(Sender : TObject);
    procedure _PROC_0069109A(Sender : TObject);
    procedure _PROC_00691249(Sender : TObject);
    procedure _PROC_006913F8(Sender : TObject);
    procedure _PROC_0069160D(Sender : TObject);
    procedure _PROC_006917C4(Sender : TObject);
    procedure _PROC_006917F2(Sender : TObject);
    procedure _PROC_00691805(Sender : TObject);
    procedure _PROC_006919FD(Sender : TObject);
    procedure _PROC_00691A9C(Sender : TObject);
    procedure _PROC_00691CD7(Sender : TObject);
    procedure _PROC_00691CE8(Sender : TObject);
    procedure _PROC_00691D59(Sender : TObject);
    procedure _PROC_00691DE9(Sender : TObject);
    procedure _PROC_00691FE6(Sender : TObject);
    procedure _PROC_00691FF7(Sender : TObject);
    procedure _PROC_00692069(Sender : TObject);
    procedure _PROC_006921B8(Sender : TObject);
    procedure _PROC_006921E8(Sender : TObject);
    procedure _PROC_006921F0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmCancelaProduto: TfrmCancelaProduto;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmCancelaProduto.btCancelarClick(Sender : TObject);
begin
(*
0069189C   55                     push    ebp
0069189D   8BEC                   mov     ebp, esp
0069189F   6A00                   push    $00
006918A1   53                     push    ebx
006918A2   8BD8                   mov     ebx, eax
006918A4   33C0                   xor     eax, eax
006918A6   55                     push    ebp

* Possible String Reference to: 'ÈS4◊ˇÎ[Y]√êUãÏj'
|
006918A7   68E0186900             push    $006918E0

***** TRY
|
006918AC   64FF30                 push    dword ptr fs:[eax]
006918AF   648920                 mov     fs:[eax], esp
006918B2   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
006918B5   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
006918BB   E80C1EE0FF             call    004936CC
006918C0   8B55FC                 mov     edx, [ebp-$04]
006918C3   8BC3                   mov     eax, ebx

* Reference to : TfrmCancelaProduto._PROC_00691A9C()
|
006918C5   E8D2010000             call    00691A9C
006918CA   33C0                   xor     eax, eax
006918CC   5A                     pop     edx
006918CD   59                     pop     ecx
006918CE   59                     pop     ecx
006918CF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏj'
|
006918D2   68E7186900             push    $006918E7
006918D7   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
006918DA   E8BD3BD7FF             call    0040549C
006918DF   C3                     ret


* Reference to: System.@HandleFinally;
|
006918E0   E95334D7FF             jmp     00404D38
006918E5   EBF0                   jmp     006918D7

****** END
|
006918E7   5B                     pop     ebx
006918E8   59                     pop     ecx
006918E9   5D                     pop     ebp
006918EA   C3                     ret

*)
end;

procedure TfrmCancelaProduto.dbgMesaItemGetCellParams(Sender : TObject);
begin
(*
006918EC   55                     push    ebp
006918ED   8BEC                   mov     ebp, esp
006918EF   6A00                   push    $00
006918F1   6A00                   push    $00
006918F3   6A00                   push    $00
006918F5   53                     push    ebx
006918F6   33C0                   xor     eax, eax
006918F8   55                     push    ebp
006918F9   68E0196900             push    $006919E0

***** TRY
|
006918FE   64FF30                 push    dword ptr fs:[eax]
00691901   648920                 mov     fs:[eax], esp
00691904   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691909   8B00                   mov     eax, [eax]
0069190B   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'STATUS'
|
0069190E   BAF8196900             mov     edx, $006919F8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691913   E8EC82E5FF             call    004E9C04
00691918   8D55FC                 lea     edx, [ebp-$04]
0069191B   8B08                   mov     ecx, [eax]
0069191D   FF5160                 call    dword ptr [ecx+$60]
00691920   8B45FC                 mov     eax, [ebp-$04]
00691923   BA081A6900             mov     edx, $00691A08

* Reference to: System.@LStrCmp;
|
00691928   E87B3FD7FF             call    004058A8
0069192D   7518                   jnz     00691947
0069192F   8B450C                 mov     eax, [ebp+$0C]
00691932   C700FF000000           mov     dword ptr [eax], $000000FF
00691938   BAFFFFFF00             mov     edx, $00FFFFFF
0069193D   8B4510                 mov     eax, [ebp+$10]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
00691940   E80B01DAFF             call    00431A50
00691945   EB7E                   jmp     006919C5
00691947   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069194C   8B00                   mov     eax, [eax]
0069194E   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'STATUS'
|
00691951   BAF8196900             mov     edx, $006919F8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691956   E8A982E5FF             call    004E9C04
0069195B   8D55F8                 lea     edx, [ebp-$08]
0069195E   8B08                   mov     ecx, [eax]
00691960   FF5160                 call    dword ptr [ecx+$60]
00691963   8B45F8                 mov     eax, [ebp-$08]
00691966   BA141A6900             mov     edx, $00691A14

* Reference to: System.@LStrCmp;
|
0069196B   E8383FD7FF             call    004058A8
00691970   7515                   jnz     00691987
00691972   8B450C                 mov     eax, [ebp+$0C]
00691975   C700180000FF           mov     dword ptr [eax], $FF000018
0069197B   33D2                   xor     edx, edx
0069197D   8B4510                 mov     eax, [ebp+$10]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
00691980   E8CB00DAFF             call    00431A50
00691985   EB3E                   jmp     006919C5
00691987   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069198C   8B00                   mov     eax, [eax]
0069198E   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'STATUS'
|
00691991   BAF8196900             mov     edx, $006919F8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691996   E86982E5FF             call    004E9C04
0069199B   8D55F4                 lea     edx, [ebp-$0C]
0069199E   8B08                   mov     ecx, [eax]
006919A0   FF5160                 call    dword ptr [ecx+$60]
006919A3   8B45F4                 mov     eax, [ebp-$0C]
006919A6   BA201A6900             mov     edx, $00691A20

* Reference to: System.@LStrCmp;
|
006919AB   E8F83ED7FF             call    004058A8
006919B0   7513                   jnz     006919C5
006919B2   8B450C                 mov     eax, [ebp+$0C]
006919B5   C700C0DCC000           mov     dword ptr [eax], $00C0DCC0
006919BB   33D2                   xor     edx, edx
006919BD   8B4510                 mov     eax, [ebp+$10]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
006919C0   E88B00DAFF             call    00431A50
006919C5   33C0                   xor     eax, eax
006919C7   5A                     pop     edx
006919C8   59                     pop     ecx
006919C9   59                     pop     ecx
006919CA   648910                 mov     fs:[eax], edx

****** FINALLY
|
006919CD   68E7196900             push    $006919E7
006919D2   8D45F4                 lea     eax, [ebp-$0C]
006919D5   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
006919DA   E8E13AD7FF             call    004054C0
006919DF   C3                     ret


* Reference to: System.@HandleFinally;
|
006919E0   E95333D7FF             jmp     00404D38
006919E5   EBEB                   jmp     006919D2

****** END
|
006919E7   5B                     pop     ebx
006919E8   8BE5                   mov     esp, ebp
006919EA   5D                     pop     ebp
006919EB   C20C00                 ret     $000C

*)
end;

procedure TfrmCancelaProduto.edNumItemKeyDown(Sender : TObject);
begin
(*
00691A24   55                     push    ebp
00691A25   8BEC                   mov     ebp, esp
00691A27   56                     push    esi
00691A28   6683390D               cmp     word ptr [ecx], +$0D
00691A2C   750F                   jnz     00691A3D

* Reference to control TfrmCancelaProduto.btCancelar : TBitBtn
|
00691A2E   8B800C030000           mov     eax, [eax+$030C]
00691A34   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
00691A38   E8632DD7FF             call    004047A0
00691A3D   5E                     pop     esi
00691A3E   5D                     pop     ebp
00691A3F   C20400                 ret     $0004

*)
end;

procedure TfrmCancelaProduto.dbgMesaItemDblClick(Sender : TObject);
begin
(*
00691A44   55                     push    ebp
00691A45   8BEC                   mov     ebp, esp
00691A47   6A00                   push    $00
00691A49   53                     push    ebx
00691A4A   8BD8                   mov     ebx, eax
00691A4C   33C0                   xor     eax, eax
00691A4E   55                     push    ebp
00691A4F   688F1A6900             push    $00691A8F

***** TRY
|
00691A54   64FF30                 push    dword ptr fs:[eax]
00691A57   648920                 mov     fs:[eax], esp
00691A5A   8D55FC                 lea     edx, [ebp-$04]
00691A5D   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691A62   8B00                   mov     eax, [eax]
00691A64   8B80BC050000           mov     eax, [eax+$05BC]
00691A6A   8B08                   mov     ecx, [eax]
00691A6C   FF5160                 call    dword ptr [ecx+$60]
00691A6F   8B55FC                 mov     edx, [ebp-$04]
00691A72   8BC3                   mov     eax, ebx

* Reference to : TfrmCancelaProduto._PROC_00691A9C()
|
00691A74   E823000000             call    00691A9C
00691A79   33C0                   xor     eax, eax
00691A7B   5A                     pop     edx
00691A7C   59                     pop     ecx
00691A7D   59                     pop     ecx
00691A7E   648910                 mov     fs:[eax], edx

****** FINALLY
|
00691A81   68961A6900             push    $00691A96
00691A86   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00691A89   E80E3AD7FF             call    0040549C
00691A8E   C3                     ret


* Reference to: System.@HandleFinally;
|
00691A8F   E9A432D7FF             jmp     00404D38
00691A94   EBF0                   jmp     00691A86

****** END
|
00691A96   5B                     pop     ebx
00691A97   59                     pop     ecx
00691A98   5D                     pop     ebp
00691A99   C3                     ret

*)
end;

procedure TfrmCancelaProduto.btDesfazClick(Sender : TObject);
begin
(*
0069210C   55                     push    ebp
0069210D   8BEC                   mov     ebp, esp
0069210F   6A00                   push    $00
00692111   53                     push    ebx
00692112   8BD8                   mov     ebx, eax
00692114   33C0                   xor     eax, eax
00692116   55                     push    ebp

* Possible String Reference to: 'È„+◊ˇÎ[Y]√êUãÏj'
|
00692117   6850216900             push    $00692150

***** TRY
|
0069211C   64FF30                 push    dword ptr fs:[eax]
0069211F   648920                 mov     fs:[eax], esp
00692122   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
00692125   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0069212B   E89C15E0FF             call    004936CC
00692130   8B55FC                 mov     edx, [ebp-$04]
00692133   8BC3                   mov     eax, ebx

|
00692135   E8AEFCFFFF             call    00691DE8
0069213A   33C0                   xor     eax, eax
0069213C   5A                     pop     edx
0069213D   59                     pop     ecx
0069213E   59                     pop     ecx
0069213F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏj'
|
00692142   6857216900             push    $00692157
00692147   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0069214A   E84D33D7FF             call    0040549C
0069214F   C3                     ret


* Reference to: System.@HandleFinally;
|
00692150   E9E32BD7FF             jmp     00404D38
00692155   EBF0                   jmp     00692147

****** END
|
00692157   5B                     pop     ebx
00692158   59                     pop     ecx
00692159   5D                     pop     ebp
0069215A   C3                     ret

*)
end;

procedure TfrmCancelaProduto.dbgMesaItemCellClick(Sender : TObject);
begin
(*
0069215C   55                     push    ebp
0069215D   8BEC                   mov     ebp, esp
0069215F   6A00                   push    $00
00692161   53                     push    ebx
00692162   8BD8                   mov     ebx, eax
00692164   33C0                   xor     eax, eax
00692166   55                     push    ebp

* Possible String Reference to: 'Èà+◊ˇÎ[Y]√ã¿UãÏ3¿Uh›!i'
|
00692167   68AB216900             push    $006921AB

***** TRY
|
0069216C   64FF30                 push    dword ptr fs:[eax]
0069216F   648920                 mov     fs:[eax], esp
00692172   8D55FC                 lea     edx, [ebp-$04]
00692175   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069217A   8B00                   mov     eax, [eax]
0069217C   8B80BC050000           mov     eax, [eax+$05BC]
00692182   8B08                   mov     ecx, [eax]
00692184   FF5160                 call    dword ptr [ecx+$60]
00692187   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
0069218A   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00692190   E86715E0FF             call    004936FC
00692195   33C0                   xor     eax, eax
00692197   5A                     pop     edx
00692198   59                     pop     ecx
00692199   59                     pop     ecx
0069219A   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ã¿UãÏ3¿Uh›!i'
|
0069219D   68B2216900             push    $006921B2
006921A2   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
006921A5   E8F232D7FF             call    0040549C
006921AA   C3                     ret


* Reference to: System.@HandleFinally;
|
006921AB   E9882BD7FF             jmp     00404D38
006921B0   EBF0                   jmp     006921A2

****** END
|
006921B2   5B                     pop     ebx
006921B3   59                     pop     ecx
006921B4   5D                     pop     ebp
006921B5   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00690FAC(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00690FAC   E9873DD7FF             jmp     00404D38

* Reference to: iwmain.TFormIWMain.OnCreateSession(TFormIWMain;TObject);
|
00690FB1   EBEE                   jmp     00690FA1
00690FB3   33C0                   xor     eax, eax
00690FB5   5A                     pop     edx
00690FB6   59                     pop     ecx
00690FB7   59                     pop     ecx
00690FB8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äE˚_^[ãÂ]√'
|
00690FBB   68DD0F6900             push    $00690FDD
00690FC0   8D45D0                 lea     eax, [ebp-$30]
00690FC3   BA0A000000             mov     edx, $0000000A

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00690FC8   E8F344D7FF             call    004054C0
00690FCD   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00690FD0   E8C744D7FF             call    0040549C
00690FD5   C3                     ret


* Reference to: System.@HandleFinally;
|
00690FD6   E95D3DD7FF             jmp     00404D38
00690FDB   EBE3                   jmp     00690FC0

****** END
|
00690FDD   8A45FB                 mov     al, byte ptr [ebp-$05]
00690FE0   5F                     pop     edi
00690FE1   5E                     pop     esi
00690FE2   5B                     pop     ebx
00690FE3   8BE5                   mov     esp, ebp
00690FE5   5D                     pop     ebp
00690FE6   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00691002(Sender : TObject);
begin
(*
00691002   4D                     dec     ebp
00691003   4C                     dec     esp
00691004   43                     inc     ebx
00691005   54                     push    esp
00691006   4F                     dec     edi
00691007   00FF                   add     bh, bh
00691009   FFFF                   DB  $FF, $FF  //      
0069100B   FF07                   inc     dword ptr [edi]
0069100D   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691065(Sender : TObject);
begin
(*
00691065   4E                     dec     esi
00691066   43                     inc     ebx
00691067   00FF                   add     bh, bh
00691069   FFFF                   DB  $FF, $FF  //      
0069106B   FF0A                   dec     dword ptr [edx]
0069106D   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691075(Sender : TObject);
begin
(*
00691075   4E                     dec     esi
00691076   43                     inc     ebx
00691077   203D200000FF           and     [$FF000020], bh
0069107D   FFFF                   DB  $FF, $FF  //      
0069107F   FF08                   dec     dword ptr [eax]
00691081   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691086(Sender : TObject);
begin
(*
00691086   4E                     dec     esi
00691087   43                     inc     ebx
00691088   52                     push    edx
00691089   45                     inc     ebp
0069108A   50                     push    eax
0069108B   52                     push    edx
0069108C   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_0069109A(Sender : TObject);
begin
(*
0069109A   4D                     dec     ebp
0069109B   50                     push    eax
0069109C   45                     inc     ebp
0069109D   53                     push    ebx
0069109E   53                     push    ebx
0069109F   4F                     dec     edi
006910A0   41                     inc     ecx
006910A1   53                     push    ebx
006910A2   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691249(Sender : TObject);
begin
(*
00691249   8BEC                   mov     ebp, esp
0069124B   33C9                   xor     ecx, ecx
0069124D   51                     push    ecx
0069124E   51                     push    ecx
0069124F   51                     push    ecx
00691250   51                     push    ecx
00691251   51                     push    ecx
00691252   51                     push    ecx
00691253   53                     push    ebx
00691254   56                     push    esi
00691255   57                     push    edi
00691256   8955FC                 mov     [ebp-$04], edx
00691259   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
0069125C   E8EB46D7FF             call    0040594C
00691261   8B358CA97D00           mov     esi, [$007DA98C]
00691267   33C0                   xor     eax, eax
00691269   55                     push    ebp
0069126A   6822146900             push    $00691422

***** TRY
|
0069126F   64FF30                 push    dword ptr fs:[eax]
00691272   648920                 mov     fs:[eax], esp
00691275   C645FB00               mov     byte ptr [ebp-$05], $00
00691279   33D2                   xor     edx, edx
0069127B   55                     push    ebp
0069127C   68F8136900             push    $006913F8

***** TRY
|
00691281   64FF32                 push    dword ptr fs:[edx]
00691284   648922                 mov     fs:[edx], esp
00691287   33D2                   xor     edx, edx
00691289   55                     push    ebp
0069128A   68AF136900             push    $006913AF

***** TRY
|
0069128F   64FF32                 push    dword ptr fs:[edx]
00691292   648922                 mov     fs:[edx], esp
00691295   8B06                   mov     eax, [esi]
00691297   8B4058                 mov     eax, [eax+$58]
0069129A   8B9850020000           mov     ebx, [eax+$0250]
006912A0   8BC3                   mov     eax, ebx
006912A2   8B10                   mov     edx, [eax]
006912A4   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select'
|
006912A7   BA3C146900             mov     edx, $0069143C
006912AC   8BC3                   mov     eax, ebx
006912AE   8B08                   mov     ecx, [eax]
006912B0   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'ml.codmesa, ml.numlcto, ml.dataini,
|                                 ml.datafim, ml.cgcclie, ml.codfunc
|                                ,'
|
006912B3   BA4C146900             mov     edx, $0069144C
006912B8   8BC3                   mov     eax, ebx
006912BA   8B08                   mov     ecx, [eax]
006912BC   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'ml.numpessoas, ml.vlrtotal, ml.stat
|                                us, c.razao, f.nome'
|
006912BF   BA9C146900             mov     edx, $0069149C
006912C4   8BC3                   mov     eax, ebx
006912C6   8B08                   mov     ecx, [eax]
006912C8   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'from mesalcto ml'
|
006912CB   BADC146900             mov     edx, $006914DC
006912D0   8BC3                   mov     eax, ebx
006912D2   8B08                   mov     ecx, [eax]
006912D4   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'left join clientes c'
|
006912D7   BAF8146900             mov     edx, $006914F8
006912DC   8BC3                   mov     eax, ebx
006912DE   8B08                   mov     ecx, [eax]
006912E0   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'on (ml.cgcclie = c.cgcclie)'
|
006912E3   BA18156900             mov     edx, $00691518
006912E8   8BC3                   mov     eax, ebx
006912EA   8B08                   mov     ecx, [eax]
006912EC   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'left join funcrepr f'
|
006912EF   BA3C156900             mov     edx, $0069153C
006912F4   8BC3                   mov     eax, ebx
006912F6   8B08                   mov     ecx, [eax]
006912F8   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'on (ml.codfunc = f.codfunc)'
|
006912FB   BA5C156900             mov     edx, $0069155C
00691300   8BC3                   mov     eax, ebx
00691302   8B08                   mov     ecx, [eax]
00691304   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: 'where'
|
00691307   BA80156900             mov     edx, $00691580
0069130C   8BC3                   mov     eax, ebx
0069130E   8B08                   mov     ecx, [eax]
00691310   FF5138                 call    dword ptr [ecx+$38]

* Possible String Reference to: '(ml.codmesa = '
|
00691313   6890156900             push    $00691590
00691318   8D55F0                 lea     edx, [ebp-$10]
0069131B   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0069131E   E8FD271100             call    007A3B20
00691323   FF75F0                 push    dword ptr [ebp-$10]

* Possible String Reference to: ') and (ml.status = '
|
00691326   68A8156900             push    $006915A8
0069132B   8D55EC                 lea     edx, [ebp-$14]
0069132E   B8C4156900             mov     eax, $006915C4

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
00691333   E8E8271100             call    007A3B20
00691338   FF75EC                 push    dword ptr [ebp-$14]
0069133B   68D0156900             push    $006915D0
00691340   8D45F4                 lea     eax, [ebp-$0C]
00691343   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrCatN;
|
00691348   E8CF44D7FF             call    0040581C
0069134D   8B55F4                 mov     edx, [ebp-$0C]
00691350   8BC3                   mov     eax, ebx
00691352   8B08                   mov     ecx, [eax]
00691354   FF5138                 call    dword ptr [ecx+$38]
00691357   8B06                   mov     eax, [esi]
00691359   8B4058                 mov     eax, [eax+$58]
0069135C   80B85402000000         cmp     byte ptr [eax+$0254], $00
00691363   7505                   jnz     0069136A

* Reference to: ActnMenus.TInternalMDIAction.UpdateTarget(TInternalMDIAction;TObject);
|
00691365   E8669DF0FF             call    0059B0D0
0069136A   8B06                   mov     eax, [esi]
0069136C   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Open(TDataSet);
|
0069136F   E8E075E5FF             call    004E8954
00691374   8B06                   mov     eax, [esi]
00691376   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Last(TDataSet);
|
00691379   E8869DE5FF             call    004EB104
0069137E   8B06                   mov     eax, [esi]
00691380   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
00691383   E81877E5FF             call    004E8AA0
00691388   84C0                   test    al, al
0069138A   7410                   jz      0069139C
0069138C   8B06                   mov     eax, [esi]
0069138E   8B4058                 mov     eax, [eax+$58]
00691391   8B10                   mov     edx, [eax]
00691393   FF924C010000           call    dword ptr [edx+$014C]
00691399   48                     dec     eax
0069139A   7D04                   jnl     006913A0
0069139C   33C0                   xor     eax, eax
0069139E   EB02                   jmp     006913A2
006913A0   B001                   mov     al, $01
006913A2   8845FB                 mov     [ebp-$05], al
006913A5   33C0                   xor     eax, eax
006913A7   5A                     pop     edx
006913A8   59                     pop     ecx
006913A9   59                     pop     ecx
006913AA   648910                 mov     fs:[eax], edx
006913AD   EB3B                   jmp     006913EA

* Reference to: System.@HandleOnException;
|
006913AF   E9FC37D7FF             jmp     00404BB0
006913B4   0100                   add     [eax], eax
006913B6   0000                   add     [eax], al
006913B8   40                     inc     eax
006913B9   95                     xchg    eax, ebp
006913BA   40                     inc     eax
006913BB   00C0                   add     al, al
006913BD   136900                 adc     ebp, [ecx+$00]
006913C0   89C3                   mov     ebx, eax
006913C2   6A00                   push    $00
006913C4   8B4B04                 mov     ecx, [ebx+$04]
006913C7   8D45E8                 lea     eax, [ebp-$18]

* Possible String Reference to: 'Ocorreu um erro na funÁ„o VerificaM
|                                esa.'
|
006913CA   BADC156900             mov     edx, $006915DC

* Reference to: System.@LStrCat3;
|
006913CF   E8D443D7FF             call    004057A8
006913D4   8B45E8                 mov     eax, [ebp-$18]
006913D7   668B0D08166900         mov     cx, word ptr [$00691608]
006913DE   B201                   mov     dl, $01

|
006913E0   E84727DBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
006913E5   E8C63AD7FF             call    00404EB0

****** END
|
006913EA   33C0                   xor     eax, eax
006913EC   5A                     pop     edx
006913ED   59                     pop     ecx
006913EE   59                     pop     ecx
006913EF   648910                 mov     fs:[eax], edx

****** FINALLY
|
006913F2   68FF136900             push    $006913FF
006913F7   C3                     ret


* Reference to: System.@HandleFinally;
|
006913F8   E93B39D7FF             jmp     00404D38
006913FD   EBF8                   jmp     006913F7

****** END
|
006913FF   33C0                   xor     eax, eax
00691401   5A                     pop     edx
00691402   59                     pop     ecx
00691403   59                     pop     ecx
00691404   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äE˚_^[ãÂ]√'
|
00691407   6829146900             push    $00691429
0069140C   8D45E8                 lea     eax, [ebp-$18]
0069140F   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00691414   E8A740D7FF             call    004054C0
00691419   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0069141C   E87B40D7FF             call    0040549C
00691421   C3                     ret


* Reference to: System.@HandleFinally;
|
00691422   E91139D7FF             jmp     00404D38
00691427   EBE3                   jmp     0069140C

****** END
|
00691429   8A45FB                 mov     al, byte ptr [ebp-$05]
0069142C   5F                     pop     edi
0069142D   5E                     pop     esi
0069142E   5B                     pop     ebx
0069142F   8BE5                   mov     esp, ebp
00691431   5D                     pop     ebp
00691432   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_006913F8(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
006913F8   E93B39D7FF             jmp     00404D38

|
006913FD   EBF8                   jmp     006913F7
006913FF   33C0                   xor     eax, eax
00691401   5A                     pop     edx
00691402   59                     pop     ecx
00691403   59                     pop     ecx
00691404   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äE˚_^[ãÂ]√'
|
00691407   6829146900             push    $00691429
0069140C   8D45E8                 lea     eax, [ebp-$18]
0069140F   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00691414   E8A740D7FF             call    004054C0
00691419   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0069141C   E87B40D7FF             call    0040549C
00691421   C3                     ret


* Reference to: System.@HandleFinally;
|
00691422   E91139D7FF             jmp     00404D38
00691427   EBE3                   jmp     0069140C

****** END
|
00691429   8A45FB                 mov     al, byte ptr [ebp-$05]
0069142C   5F                     pop     edi
0069142D   5E                     pop     esi
0069142E   5B                     pop     ebx
0069142F   8BE5                   mov     esp, ebp
00691431   5D                     pop     ebp
00691432   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_0069160D(Sender : TObject);
begin
(*
0069160D   8BEC                   mov     ebp, esp
0069160F   33C9                   xor     ecx, ecx
00691611   51                     push    ecx
00691612   51                     push    ecx
00691613   51                     push    ecx
00691614   51                     push    ecx
00691615   51                     push    ecx
00691616   53                     push    ebx
00691617   56                     push    esi
00691618   57                     push    edi
00691619   8BF8                   mov     edi, eax
0069161B   8B358CA97D00           mov     esi, [$007DA98C]
00691621   33C0                   xor     eax, eax
00691623   55                     push    ebp

* Possible String Reference to: 'Èo5◊ˇÎÎäEˇ_^[ãÂ]√'
|
00691624   68C4176900             push    $006917C4

***** TRY
|
00691629   64FF30                 push    dword ptr fs:[eax]
0069162C   648920                 mov     fs:[eax], esp
0069162F   C645FF00               mov     byte ptr [ebp-$01], $00
00691633   33C0                   xor     eax, eax
00691635   8905D8EC7D00           mov     [$007DECD8], eax
0069163B   8905DCEC7D00           mov     [$007DECDC], eax
00691641   668905E0EC7D00         mov     [$007DECE0], ax
00691648   33C0                   xor     eax, eax
0069164A   55                     push    ebp
0069164B   68A2176900             push    $006917A2

***** TRY
|
00691650   64FF30                 push    dword ptr fs:[eax]
00691653   648920                 mov     fs:[eax], esp
00691656   33C0                   xor     eax, eax
00691658   55                     push    ebp
00691659   6859176900             push    $00691759

***** TRY
|
0069165E   64FF30                 push    dword ptr fs:[eax]
00691661   648920                 mov     fs:[eax], esp
00691664   8B06                   mov     eax, [esi]
00691666   8B4074                 mov     eax, [eax+$74]

|
00691669   E82A501100             call    007A6698
0069166E   8B06                   mov     eax, [esi]
00691670   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'CODMESA'
|
00691673   BAE0176900             mov     edx, $006917E0

* Reference to: IBCustomDataSet.TIBDataSet.ParamByName(TIBDataSet;AnsiString):TIBXSQLVAR;
|
00691678   E88FFAECFF             call    0056110C
0069167D   8B15D0EC7D00           mov     edx, [$007DECD0]

* Reference to: IBSQL.TIBXSQLVAR.SetAsLong(TIBXSQLVAR;Long);
|
00691683   E80427EDFF             call    00563D8C
00691688   8B06                   mov     eax, [esi]
0069168A   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'NUMLCTO'
|
0069168D   BAF0176900             mov     edx, $006917F0

* Reference to: IBCustomDataSet.TIBDataSet.ParamByName(TIBDataSet;AnsiString):TIBXSQLVAR;
|
00691692   E875FAECFF             call    0056110C
00691697   8B15D4EC7D00           mov     edx, [$007DECD4]

* Reference to: IBSQL.TIBXSQLVAR.SetAsLong(TIBXSQLVAR;Long);
|
0069169D   E8EA26EDFF             call    00563D8C
006916A2   8B06                   mov     eax, [esi]
006916A4   8B4074                 mov     eax, [eax+$74]

|
006916A7   E85C4E1100             call    007A6508
006916AC   EB50                   jmp     006916FE
006916AE   8BC3                   mov     eax, ebx

* Possible String Reference to: 'STATUS'
|
006916B0   BA00186900             mov     edx, $00691800

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006916B5   E84A85E5FF             call    004E9C04
006916BA   8D55F8                 lea     edx, [ebp-$08]
006916BD   8B08                   mov     ecx, [eax]
006916BF   FF5160                 call    dword ptr [ecx+$60]
006916C2   8B45F8                 mov     eax, [ebp-$08]
006916C5   BA10186900             mov     edx, $00691810

* Reference to: System.@LStrCmp;
|
006916CA   E8D941D7FF             call    004058A8
006916CF   7423                   jz      006916F4
006916D1   8B06                   mov     eax, [esi]
006916D3   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'VLRTOTAL'
|
006916D6   BA1C186900             mov     edx, $0069181C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006916DB   E82485E5FF             call    004E9C04
006916E0   8B10                   mov     edx, [eax]
006916E2   FF5254                 call    dword ptr [edx+$54]
006916E5   DB2DD8EC7D00           fld     tbyte ptr [$007DECD8]
006916EB   DEC1                   faddp   st(1), st(0)
006916ED   DB3DD8EC7D00           fstp    tbyte ptr [$007DECD8]
006916F3   9B                     wait
006916F4   8B06                   mov     eax, [esi]
006916F6   8B4074                 mov     eax, [eax+$74]

* Reference to: DB.TDataSet.Next(TDataSet);
|
006916F9   E8469CE5FF             call    004EB344
006916FE   8B06                   mov     eax, [esi]
00691700   8B5874                 mov     ebx, [eax+$74]
00691703   80BBA100000000         cmp     byte ptr [ebx+$00A1], $00
0069170A   74A2                   jz      006916AE
0069170C   668B05E0EC7D00         mov     ax, word ptr [$007DECE0]
00691713   50                     push    eax
00691714   FF35DCEC7D00           push    dword ptr [$007DECDC]
0069171A   FF35D8EC7D00           push    dword ptr [$007DECD8]
00691720   8D55F0                 lea     edx, [ebp-$10]

* Possible String Reference to: '###,###,##0.00'
|
00691723   B830186900             mov     eax, $00691830

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
00691728   E80FBED7FF             call    0040D53C
0069172D   8B4DF0                 mov     ecx, [ebp-$10]
00691730   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'Valor total: $ '
|
00691733   BA48186900             mov     edx, $00691848

* Reference to: System.@LStrCat3;
|
00691738   E86B40D7FF             call    004057A8
0069173D   8B55F4                 mov     edx, [ebp-$0C]
00691740   8B8710030000           mov     eax, [edi+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00691746   E8B11FE0FF             call    004936FC
0069174B   C645FF01               mov     byte ptr [ebp-$01], $01
0069174F   33C0                   xor     eax, eax
00691751   5A                     pop     edx
00691752   59                     pop     ecx
00691753   59                     pop     ecx
00691754   648910                 mov     fs:[eax], edx
00691757   EB3B                   jmp     00691794

* Reference to: System.@HandleOnException;
|
00691759   E95234D7FF             jmp     00404BB0
0069175E   0100                   add     [eax], eax
00691760   0000                   add     [eax], al
00691762   40                     inc     eax
00691763   95                     xchg    eax, ebp
00691764   40                     inc     eax
00691765   006A17                 add     [edx+$17], ch
00691768   690089C36A00           imul    eax, [eax], $006AC389
0069176E   8B4B04                 mov     ecx, [ebx+$04]
00691771   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'Ocorreu um erro ao executar a funÁ„
|                                o AbreMesaItem.'
|
00691774   BA60186900             mov     edx, $00691860

* Reference to: System.@LStrCat3;
|
00691779   E82A40D7FF             call    004057A8
0069177E   8B45EC                 mov     eax, [ebp-$14]
00691781   668B0D98186900         mov     cx, word ptr [$00691898]
00691788   B201                   mov     dl, $01

|
0069178A   E89D23DBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0069178F   E81C37D7FF             call    00404EB0

****** END
|
00691794   33C0                   xor     eax, eax
00691796   5A                     pop     edx
00691797   59                     pop     ecx
00691798   59                     pop     ecx
00691799   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069179C   68A9176900             push    $006917A9
006917A1   C3                     ret


* Reference to: System.@HandleFinally;
|
006917A2   E99135D7FF             jmp     00404D38
006917A7   EBF8                   jmp     006917A1

****** END
|
006917A9   33C0                   xor     eax, eax
006917AB   5A                     pop     edx
006917AC   59                     pop     ecx
006917AD   59                     pop     ecx
006917AE   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äEˇ_^[ãÂ]√'
|
006917B1   68CB176900             push    $006917CB
006917B6   8D45EC                 lea     eax, [ebp-$14]
006917B9   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
006917BE   E8FD3CD7FF             call    004054C0
006917C3   C3                     ret


* Reference to: System.@HandleFinally;
|
006917C4   E96F35D7FF             jmp     00404D38
006917C9   EBEB                   jmp     006917B6

****** END
|
006917CB   8A45FF                 mov     al, byte ptr [ebp-$01]
006917CE   5F                     pop     edi
006917CF   5E                     pop     esi
006917D0   5B                     pop     ebx
006917D1   8BE5                   mov     esp, ebp
006917D3   5D                     pop     ebp
006917D4   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_006917C4(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
006917C4   E96F35D7FF             jmp     00404D38

|
006917C9   EBEB                   jmp     006917B6
006917CB   8A45FF                 mov     al, byte ptr [ebp-$01]
006917CE   5F                     pop     edi
006917CF   5E                     pop     esi
006917D0   5B                     pop     ebx
006917D1   8BE5                   mov     esp, ebp
006917D3   5D                     pop     ebp
006917D4   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_006917F2(Sender : TObject);
begin
(*
006917F2   4D                     dec     ebp
006917F3   4C                     dec     esp
006917F4   43                     inc     ebx
006917F5   54                     push    esp
006917F6   4F                     dec     edi
006917F7   00FF                   add     bh, bh
006917F9   FFFF                   DB  $FF, $FF  //      
006917FB   FF06                   inc     dword ptr [esi]
006917FD   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691805(Sender : TObject);
begin
(*
00691805   53                     push    ebx
00691806   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_006919FD(Sender : TObject);
begin
(*
006919FD   53                     push    ebx
006919FE   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691A9C(Sender : TObject);
begin
(*
00691A9C   55                     push    ebp
00691A9D   8BEC                   mov     ebp, esp
00691A9F   B906000000             mov     ecx, $00000006
00691AA4   6A00                   push    $00
00691AA6   6A00                   push    $00
00691AA8   49                     dec     ecx
00691AA9   75F9                   jnz     00691AA4
00691AAB   53                     push    ebx
00691AAC   56                     push    esi
00691AAD   57                     push    edi
00691AAE   8955FC                 mov     [ebp-$04], edx
00691AB1   8BD8                   mov     ebx, eax
00691AB3   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00691AB6   E8913ED7FF             call    0040594C
00691ABB   33C0                   xor     eax, eax
00691ABD   55                     push    ebp
00691ABE   68D71C6900             push    $00691CD7

***** TRY
|
00691AC3   64FF30                 push    dword ptr fs:[eax]
00691AC6   648920                 mov     fs:[eax], esp
00691AC9   C645FB00               mov     byte ptr [ebp-$05], $00
00691ACD   8D55F0                 lea     edx, [ebp-$10]
00691AD0   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00691AD5   8B00                   mov     eax, [eax]
00691AD7   8B80D8010000           mov     eax, [eax+$01D8]
00691ADD   8B08                   mov     ecx, [eax]
00691ADF   FF5160                 call    dword ptr [ecx+$60]
00691AE2   8B45F0                 mov     eax, [ebp-$10]
00691AE5   8D55F4                 lea     edx, [ebp-$0C]

* Reference to : TFrmInfoAtu._PROC_007A3638()
|
00691AE8   E84B1B1100             call    007A3638
00691AED   33C0                   xor     eax, eax
00691AEF   55                     push    ebp
00691AF0   68641C6900             push    $00691C64

***** TRY
|
00691AF5   64FF30                 push    dword ptr fs:[eax]
00691AF8   648920                 mov     fs:[eax], esp
00691AFB   837DFC00               cmp     dword ptr [ebp-$04], +$00
00691AFF   0F8455010000           jz      00691C5A
00691B05   8B45F4                 mov     eax, [ebp-$0C]

* Reference to : TFrmInfoAtu._PROC_007AFBA0()
|
00691B08   E893E01100             call    007AFBA0
00691B0D   84C0                   test    al, al
00691B0F   0F8445010000           jz      00691C5A
00691B15   A0E81C6900             mov     al, byte ptr [$00691CE8]
00691B1A   50                     push    eax
00691B1B   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.StrToInt(AnsiString):Integer;
|
00691B1E   E8AD93D7FF             call    0040AED0
00691B23   8BD0                   mov     edx, eax
00691B25   8D45E0                 lea     eax, [ebp-$20]
00691B28   B1FC                   mov     cl, $FC

|
00691B2A   E8416FD8FF             call    00418A70
00691B2F   8D4DE0                 lea     ecx, [ebp-$20]
00691B32   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691B37   8B00                   mov     eax, [eax]
00691B39   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'ITEM'
|
00691B3C   BAF41C6900             mov     edx, $00691CF4

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
00691B41   E8B2681100             call    007A83F8
00691B46   84C0                   test    al, al
00691B48   0F840C010000           jz      00691C5A
00691B4E   8D55DC                 lea     edx, [ebp-$24]
00691B51   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691B56   8B00                   mov     eax, [eax]
00691B58   8B80E0050000           mov     eax, [eax+$05E0]
00691B5E   8B08                   mov     ecx, [eax]
00691B60   FF5160                 call    dword ptr [ecx+$60]
00691B63   8B45DC                 mov     eax, [ebp-$24]
00691B66   BA041D6900             mov     edx, $00691D04

* Reference to: System.@LStrCmp;
|
00691B6B   E8383DD7FF             call    004058A8
00691B70   0F84CF000000           jz      00691C45
00691B76   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691B7B   8B00                   mov     eax, [eax]
00691B7D   8B4074                 mov     eax, [eax+$74]

|
00691B80   E89B521100             call    007A6E20
00691B85   84C0                   test    al, al
00691B87   0F84CD000000           jz      00691C5A
00691B8D   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691B92   8B00                   mov     eax, [eax]
00691B94   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'VLRTOTAL'
|
00691B97   BA101D6900             mov     edx, $00691D10

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691B9C   E86380E5FF             call    004E9C04
00691BA1   8B10                   mov     edx, [eax]
00691BA3   FF5254                 call    dword ptr [edx+$54]
00691BA6   DB2DD8EC7D00           fld     tbyte ptr [$007DECD8]
00691BAC   DEE1                   fsubrp  st(1), st(0)
00691BAE   DB3DD8EC7D00           fstp    tbyte ptr [$007DECD8]
00691BB4   9B                     wait
00691BB5   668B05E0EC7D00         mov     ax, word ptr [$007DECE0]
00691BBC   50                     push    eax
00691BBD   FF35DCEC7D00           push    dword ptr [$007DECDC]
00691BC3   FF35D8EC7D00           push    dword ptr [$007DECD8]
00691BC9   8D55D4                 lea     edx, [ebp-$2C]

* Possible String Reference to: '###,###,##0.00'
|
00691BCC   B8241D6900             mov     eax, $00691D24

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
00691BD1   E866B9D7FF             call    0040D53C
00691BD6   8B4DD4                 mov     ecx, [ebp-$2C]
00691BD9   8D45D8                 lea     eax, [ebp-$28]

* Possible String Reference to: 'Valor total: $ '
|
00691BDC   BA3C1D6900             mov     edx, $00691D3C

* Reference to: System.@LStrCat3;
|
00691BE1   E8C23BD7FF             call    004057A8
00691BE6   8B55D8                 mov     edx, [ebp-$28]

* Reference to control TfrmCancelaProduto.lbVlrTotal : TLabel
|
00691BE9   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00691BEF   E8081BE0FF             call    004936FC
00691BF4   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691BF9   8B00                   mov     eax, [eax]
00691BFB   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'STATUS'
|
00691BFE   BA541D6900             mov     edx, $00691D54

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691C03   E8FC7FE5FF             call    004E9C04
00691C08   BA041D6900             mov     edx, $00691D04
00691C0D   8B08                   mov     ecx, [eax]
00691C0F   FF91B0000000           call    dword ptr [ecx+$00B0]
00691C15   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691C1A   8B00                   mov     eax, [eax]
00691C1C   8B4074                 mov     eax, [eax+$74]

|
00691C1F   E83C531100             call    007A6F60

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
00691C24   8B8304030000           mov     eax, [ebx+$0304]
00691C2A   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00691C2C   E8CB1AE0FF             call    004936FC

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
00691C31   8B8304030000           mov     eax, [ebx+$0304]
00691C37   8B10                   mov     edx, [eax]

* Reference to method TEdit.SetFocus()
|
00691C39   FF92C4000000           call    dword ptr [edx+$00C4]
00691C3F   C645FB01               mov     byte ptr [ebp-$05], $01
00691C43   EB15                   jmp     00691C5A
00691C45   6A00                   push    $00
00691C47   668B0D5C1D6900         mov     cx, word ptr [$00691D5C]
00691C4E   33D2                   xor     edx, edx

* Possible String Reference to: 'O item que vocÍ est· tentando cance
|                                lar j· foi cancelado anteriormente!'
|
00691C50   B8681D6900             mov     eax, $00691D68

|
00691C55   E8D21EDBFF             call    00443B2C
00691C5A   33C0                   xor     eax, eax
00691C5C   5A                     pop     edx
00691C5D   59                     pop     ecx
00691C5E   59                     pop     ecx
00691C5F   648910                 mov     fs:[eax], edx
00691C62   EB3B                   jmp     00691C9F

* Reference to: System.@HandleOnException;
|
00691C64   E9472FD7FF             jmp     00404BB0
00691C69   0100                   add     [eax], eax
00691C6B   0000                   add     [eax], al
00691C6D   40                     inc     eax
00691C6E   95                     xchg    eax, ebp
00691C6F   40                     inc     eax
00691C70   00751C                 add     [ebp+$1C], dh
00691C73   690089C36A00           imul    eax, [eax], $006AC389

* Reference to field TfrmCancelaProduto.Owner : TComponent
|
00691C79   8B4B04                 mov     ecx, [ebx+$04]
00691C7C   8D45D0                 lea     eax, [ebp-$30]

* Possible String Reference to: 'Ocorreu um erro ao tentar cancelar 
|                                o item.'
|
00691C7F   BAB81D6900             mov     edx, $00691DB8

* Reference to: System.@LStrCat3;
|
00691C84   E81F3BD7FF             call    004057A8
00691C89   8B45D0                 mov     eax, [ebp-$30]
00691C8C   668B0D5C1D6900         mov     cx, word ptr [$00691D5C]
00691C93   B201                   mov     dl, $01

|
00691C95   E8921EDBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
00691C9A   E81132D7FF             call    00404EB0

****** END
|
00691C9F   33C0                   xor     eax, eax
00691CA1   5A                     pop     edx
00691CA2   59                     pop     ecx
00691CA3   59                     pop     ecx
00691CA4   648910                 mov     fs:[eax], edx

****** FINALLY
|
00691CA7   68DE1C6900             push    $00691CDE
00691CAC   8D45D0                 lea     eax, [ebp-$30]
00691CAF   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00691CB4   E80738D7FF             call    004054C0
00691CB9   8D45E0                 lea     eax, [ebp-$20]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
00691CBC   E8B728D8FF             call    00414578
00691CC1   8D45F0                 lea     eax, [ebp-$10]
00691CC4   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00691CC9   E8F237D7FF             call    004054C0
00691CCE   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00691CD1   E8C637D7FF             call    0040549C
00691CD6   C3                     ret


* Reference to: System.@HandleFinally;
|
00691CD7   E95C30D7FF             jmp     00404D38
00691CDC   EBCE                   jmp     00691CAC

****** END
|
00691CDE   8A45FB                 mov     al, byte ptr [ebp-$05]
00691CE1   5F                     pop     edi
00691CE2   5E                     pop     esi
00691CE3   5B                     pop     ebx
00691CE4   8BE5                   mov     esp, ebp
00691CE6   5D                     pop     ebp
00691CE7   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00691CD7(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00691CD7   E95C30D7FF             jmp     00404D38

|
00691CDC   EBCE                   jmp     00691CAC
00691CDE   8A45FB                 mov     al, byte ptr [ebp-$05]
00691CE1   5F                     pop     edi
00691CE2   5E                     pop     esi
00691CE3   5B                     pop     ebx
00691CE4   8BE5                   mov     esp, ebp
00691CE6   5D                     pop     ebp
00691CE7   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00691CE8(Sender : TObject);
begin
(*
00691CE8   0100                   add     [eax], eax
00691CEA   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691D59(Sender : TObject);
begin
(*
00691D59   53                     push    ebx
00691D5A   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00691DE9(Sender : TObject);
begin
(*
00691DE9   8BEC                   mov     ebp, esp
00691DEB   B905000000             mov     ecx, $00000005
00691DF0   6A00                   push    $00
00691DF2   6A00                   push    $00
00691DF4   49                     dec     ecx
00691DF5   75F9                   jnz     00691DF0
00691DF7   53                     push    ebx
00691DF8   56                     push    esi
00691DF9   57                     push    edi
00691DFA   8955FC                 mov     [ebp-$04], edx
00691DFD   8BD8                   mov     ebx, eax
00691DFF   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00691E02   E8453BD7FF             call    0040594C
00691E07   33C0                   xor     eax, eax
00691E09   55                     push    ebp

* Possible String Reference to: 'ÈM-◊ˇÎ€äE˚_^[ãÂ]√'
|
00691E0A   68E61F6900             push    $00691FE6

***** TRY
|
00691E0F   64FF30                 push    dword ptr fs:[eax]
00691E12   648920                 mov     fs:[eax], esp
00691E15   C645FB00               mov     byte ptr [ebp-$05], $00
00691E19   33C0                   xor     eax, eax
00691E1B   55                     push    ebp
00691E1C   68801F6900             push    $00691F80

***** TRY
|
00691E21   64FF30                 push    dword ptr fs:[eax]
00691E24   648920                 mov     fs:[eax], esp
00691E27   837DFC00               cmp     dword ptr [ebp-$04], +$00
00691E2B   0F8445010000           jz      00691F76
00691E31   A0F81F6900             mov     al, byte ptr [$00691FF8]
00691E36   50                     push    eax
00691E37   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.StrToInt(AnsiString):Integer;
|
00691E3A   E89190D7FF             call    0040AED0
00691E3F   8BD0                   mov     edx, eax
00691E41   8D45E8                 lea     eax, [ebp-$18]
00691E44   B1FC                   mov     cl, $FC

|
00691E46   E8256CD8FF             call    00418A70
00691E4B   8D4DE8                 lea     ecx, [ebp-$18]
00691E4E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691E53   8B00                   mov     eax, [eax]
00691E55   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'ITEM'
|
00691E58   BA04206900             mov     edx, $00692004

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
00691E5D   E896651100             call    007A83F8
00691E62   84C0                   test    al, al
00691E64   0F840C010000           jz      00691F76
00691E6A   8D55E4                 lea     edx, [ebp-$1C]
00691E6D   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691E72   8B00                   mov     eax, [eax]
00691E74   8B80E0050000           mov     eax, [eax+$05E0]
00691E7A   8B08                   mov     ecx, [eax]
00691E7C   FF5160                 call    dword ptr [ecx+$60]
00691E7F   8B45E4                 mov     eax, [ebp-$1C]
00691E82   BA14206900             mov     edx, $00692014

* Reference to: System.@LStrCmp;
|
00691E87   E81C3AD7FF             call    004058A8
00691E8C   0F85CF000000           jnz     00691F61
00691E92   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691E97   8B00                   mov     eax, [eax]
00691E99   8B4074                 mov     eax, [eax+$74]

|
00691E9C   E87F4F1100             call    007A6E20
00691EA1   84C0                   test    al, al
00691EA3   0F84CD000000           jz      00691F76
00691EA9   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691EAE   8B00                   mov     eax, [eax]
00691EB0   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'VLRTOTAL'
|
00691EB3   BA20206900             mov     edx, $00692020

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691EB8   E8477DE5FF             call    004E9C04
00691EBD   8B10                   mov     edx, [eax]
00691EBF   FF5254                 call    dword ptr [edx+$54]
00691EC2   DB2DD8EC7D00           fld     tbyte ptr [$007DECD8]
00691EC8   DEC1                   faddp   st(1), st(0)
00691ECA   DB3DD8EC7D00           fstp    tbyte ptr [$007DECD8]
00691ED0   9B                     wait
00691ED1   668B05E0EC7D00         mov     ax, word ptr [$007DECE0]
00691ED8   50                     push    eax
00691ED9   FF35DCEC7D00           push    dword ptr [$007DECDC]
00691EDF   FF35D8EC7D00           push    dword ptr [$007DECD8]
00691EE5   8D55DC                 lea     edx, [ebp-$24]

* Possible String Reference to: '###,###,##0.00'
|
00691EE8   B834206900             mov     eax, $00692034

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
00691EED   E84AB6D7FF             call    0040D53C
00691EF2   8B4DDC                 mov     ecx, [ebp-$24]
00691EF5   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: 'Valor total: $ '
|
00691EF8   BA4C206900             mov     edx, $0069204C

* Reference to: System.@LStrCat3;
|
00691EFD   E8A638D7FF             call    004057A8
00691F02   8B55E0                 mov     edx, [ebp-$20]

* Reference to control TfrmCancelaProduto.lbVlrTotal : TLabel
|
00691F05   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00691F0B   E8EC17E0FF             call    004936FC
00691F10   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691F15   8B00                   mov     eax, [eax]
00691F17   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'STATUS'
|
00691F1A   BA64206900             mov     edx, $00692064

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00691F1F   E8E07CE5FF             call    004E9C04
00691F24   BA74206900             mov     edx, $00692074
00691F29   8B08                   mov     ecx, [eax]
00691F2B   FF91B0000000           call    dword ptr [ecx+$00B0]
00691F31   A18CA97D00             mov     eax, dword ptr [$007DA98C]
00691F36   8B00                   mov     eax, [eax]
00691F38   8B4074                 mov     eax, [eax+$74]

|
00691F3B   E820501100             call    007A6F60

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
00691F40   8B8304030000           mov     eax, [ebx+$0304]
00691F46   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00691F48   E8AF17E0FF             call    004936FC

* Reference to control TfrmCancelaProduto.edNumItem : TEdit
|
00691F4D   8B8304030000           mov     eax, [ebx+$0304]
00691F53   8B10                   mov     edx, [eax]

* Reference to method TEdit.SetFocus()
|
00691F55   FF92C4000000           call    dword ptr [edx+$00C4]
00691F5B   C645FB01               mov     byte ptr [ebp-$05], $01
00691F5F   EB15                   jmp     00691F76
00691F61   6A00                   push    $00
00691F63   668B0D78206900         mov     cx, word ptr [$00692078]
00691F6A   33D2                   xor     edx, edx

* Possible String Reference to: 'N„o h· como desfazer um cancelament
|                                o de um item n„o cancelado!'
|
00691F6C   B884206900             mov     eax, $00692084

|
00691F71   E8B61BDBFF             call    00443B2C
00691F76   33C0                   xor     eax, eax
00691F78   5A                     pop     edx
00691F79   59                     pop     ecx
00691F7A   59                     pop     ecx
00691F7B   648910                 mov     fs:[eax], edx
00691F7E   EB3B                   jmp     00691FBB

* Reference to: System.@HandleOnException;
|
00691F80   E92B2CD7FF             jmp     00404BB0
00691F85   0100                   add     [eax], eax
00691F87   0000                   add     [eax], al
00691F89   40                     inc     eax
00691F8A   95                     xchg    eax, ebp
00691F8B   40                     inc     eax
00691F8C   00911F690089           add     [ecx+$8900691F], dl
00691F92   C3                     ret

00691F93   6A00                   push    $00

* Reference to field TfrmCancelaProduto.Owner : TComponent
|
00691F95   8B4B04                 mov     ecx, [ebx+$04]
00691F98   8D45D8                 lea     eax, [ebp-$28]

* Possible String Reference to: 'Ocorreu um erro ao tentar desfazer 
|                                o cancelamento do item.'
|
00691F9B   BACC206900             mov     edx, $006920CC

* Reference to: System.@LStrCat3;
|
00691FA0   E80338D7FF             call    004057A8
00691FA5   8B45D8                 mov     eax, [ebp-$28]
00691FA8   668B0D78206900         mov     cx, word ptr [$00692078]
00691FAF   B201                   mov     dl, $01

|
00691FB1   E8761BDBFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
00691FB6   E8F52ED7FF             call    00404EB0

****** END
|
00691FBB   33C0                   xor     eax, eax
00691FBD   5A                     pop     edx
00691FBE   59                     pop     ecx
00691FBF   59                     pop     ecx
00691FC0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'äE˚_^[ãÂ]√'
|
00691FC3   68ED1F6900             push    $00691FED
00691FC8   8D45D8                 lea     eax, [ebp-$28]
00691FCB   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00691FD0   E8EB34D7FF             call    004054C0
00691FD5   8D45E8                 lea     eax, [ebp-$18]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
00691FD8   E89B25D8FF             call    00414578
00691FDD   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00691FE0   E8B734D7FF             call    0040549C
00691FE5   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00691FE6(Sender : TObject);
begin
(*

* Reference to: System.@HandleFinally;
|
00691FE6   E94D2DD7FF             jmp     00404D38

|
00691FEB   EBDB                   jmp     00691FC8
00691FED   8A45FB                 mov     al, byte ptr [ebp-$05]
00691FF0   5F                     pop     edi
00691FF1   5E                     pop     esi
00691FF2   5B                     pop     ebx
00691FF3   8BE5                   mov     esp, ebp
00691FF5   5D                     pop     ebp
00691FF6   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_00691FF7(Sender : TObject);
begin
(*
00691FF7   0001                   add     [ecx], al
00691FF9   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_00692069(Sender : TObject);
begin
(*
00692069   53                     push    ebx
0069206A   0000                   add     [eax], al

*)
end;

procedure TfrmCancelaProduto._PROC_006921B8(Sender : TObject);
begin
(*
006921B8   55                     push    ebp
006921B9   8BEC                   mov     ebp, esp
006921BB   33C0                   xor     eax, eax
006921BD   55                     push    ebp

* Possible String Reference to: 'ÈV+◊ˇÎ¯]√ã¿É-‰Ï}'
|
006921BE   68DD216900             push    $006921DD

***** TRY
|
006921C3   64FF30                 push    dword ptr fs:[eax]
006921C6   648920                 mov     fs:[eax], esp
006921C9   FF05E4EC7D00           inc     dword ptr [$007DECE4]
006921CF   33C0                   xor     eax, eax
006921D1   5A                     pop     edx
006921D2   59                     pop     ecx
006921D3   59                     pop     ecx
006921D4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-‰Ï}'
|
006921D7   68E4216900             push    $006921E4
006921DC   C3                     ret


* Reference to: System.@HandleFinally;
|
006921DD   E9562BD7FF             jmp     00404D38
006921E2   EBF8                   jmp     006921DC

****** END
|
006921E4   5D                     pop     ebp
006921E5   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_006921E8(Sender : TObject);
begin
(*
006921E8   832DE4EC7D0001         sub     dword ptr [$007DECE4], +$01
006921EF   C3                     ret

*)
end;

procedure TfrmCancelaProduto._PROC_006921F0(Sender : TObject);
begin
(*
006921F0   3C22                   cmp     al, $22
006921F2   690000000000           imul    eax, [eax], $00000000
006921F8   0000                   add     [eax], al

*)
end;

end.