unit cancela;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ToolEdit, CurrEdit, Buttons,
  ExtCtrls;
  
type
  TFrmCancelaCupom=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    EdNumCupom: TCurrencyEdit;
    Label1: TLabel;
    Memo1: TMemo;
    Bevel1: TBevel;
    procedure _PROC_00671428(Sender : TObject);
    procedure _PROC_00671430(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmCancelaCupom: TFrmCancelaCupom;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmCancelaCupom._PROC_00671428(Sender : TObject);
begin
(*
00671428   832D60E97D0001         sub     dword ptr [$007DE960], +$01
0067142F   C3                     ret

*)
end;

procedure TFrmCancelaCupom._PROC_00671430(Sender : TObject);
begin
(*
00671430   7C14                   jl      00671446
00671432   670000                 add     [bx+si], al
00671435   0000                   add     [eax], al

00671437   0000                   add     [eax], al

00671439   0000                   add     [eax], al

0067143B   0000                   add     [eax], al

0067143D   0000                   add     [eax], al

0067143F   00E0                   add     al, ah
00671441   1567007015             adc     eax, $15700067
00671446   670000                 add     [bx+si], al
00671449   0000                   add     [eax], al

*)
end;

end.