unit Conecta;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, ExtCtrls, Mask, JvExMask,
  JvToolEdit;
  
type
  TfrmConecta=class(TForm)
    lbTitulo: TLabel;
    edServidor: TEdit;
    lbServidor: TLabel;
    edCaminho: TJvFilenameEdit;
    Label3: TLabel;
    rgTipo: TRadioGroup;
    Bevel1: TBevel;
    btOK: TBitBtn;
    btTestar: TBitBtn;
    btCancelar: TBitBtn;
    procedure FormCreate(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure rgTipoClick(Sender : TObject);
    procedure btTestarClick(Sender : TObject);
    procedure _PROC_0064ECC5(Sender : TObject);
    procedure _PROC_0064ECF4(Sender : TObject);
    procedure _PROC_0064ECFC(Sender : TObject);
    procedure _PROC_0064ED2C(Sender : TObject);
    procedure _PROC_0064ED34(Sender : TObject);
    procedure _PROC_0064ED64(Sender : TObject);
    procedure _PROC_0064ED6C(Sender : TObject);
    procedure _PROC_0064ED9C(Sender : TObject);
    procedure _PROC_0064EDA4(Sender : TObject);
    procedure _PROC_0064EDD4(Sender : TObject);
    procedure _PROC_0064EDE8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmConecta: TfrmConecta;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmConecta.FormCreate(Sender : TObject);
begin
(*
0064E710   55                     push    ebp
0064E711   8BEC                   mov     ebp, esp
0064E713   33C9                   xor     ecx, ecx
0064E715   51                     push    ecx
0064E716   51                     push    ecx
0064E717   51                     push    ecx
0064E718   51                     push    ecx
0064E719   51                     push    ecx
0064E71A   53                     push    ebx
0064E71B   56                     push    esi
0064E71C   8BD8                   mov     ebx, eax
0064E71E   33C0                   xor     eax, eax
0064E720   55                     push    ebp

* Possible String Reference to: 'é"eÛÿëë^[‹å]Ã'
|
0064E721   6811E86400             push    $0064E811

***** TRY
|
0064E726   64FF30                 push    dword ptr fs:[eax]
0064E729   648920                 mov     fs:[eax], esp
0064E72C   8D55F4                 lea     edx, [ebp-$0C]
0064E72F   33C0                   xor     eax, eax

* Reference to: System.ParamStr(Integer):String;
|
0064E731   E8B645DBFF             call    00402CEC
0064E736   8B45F4                 mov     eax, [ebp-$0C]
0064E739   8D55F8                 lea     edx, [ebp-$08]

* Reference to: SysUtils.ExtractFilePath(AnsiString):AnsiString;
|
0064E73C   E8FBD0DBFF             call    0040B83C
0064E741   8D45F8                 lea     eax, [ebp-$08]

* Possible String Reference to: 'Servidor.ini'
|
0064E744   BA28E86400             mov     edx, $0064E828

* Reference to: System.@LStrCat;
|
0064E749   E81670DBFF             call    00405764
0064E74E   8B4DF8                 mov     ecx, [ebp-$08]
0064E751   B201                   mov     dl, $01

* Reference to class TIniFile
|
0064E753   A1540F4500             mov     eax, dword ptr [$00450F54]

* Reference to: IniFiles.TCustomIniFile.Create(TCustomIniFile;boolean;AnsiString);
|
0064E758   E8A728E0FF             call    00451004
0064E75D   8945FC                 mov     [ebp-$04], eax
0064E760   33C0                   xor     eax, eax
0064E762   55                     push    ebp
0064E763   68EFE76400             push    $0064E7EF

***** TRY
|
0064E768   64FF30                 push    dword ptr fs:[eax]
0064E76B   648920                 mov     fs:[eax], esp
0064E76E   6A01                   push    $01

* Possible String Reference to: 'Tipo'
|
0064E770   B940E86400             mov     ecx, $0064E840

* Possible String Reference to: 'Servidor'
|
0064E775   BA50E86400             mov     edx, $0064E850
0064E77A   8B45FC                 mov     eax, [ebp-$04]
0064E77D   8B30                   mov     esi, [eax]

* Reference to method TIniFile.ReadInteger(string,string,Longint)
|
0064E77F   FF5608                 call    dword ptr [esi+$08]
0064E782   8BD0                   mov     edx, eax

* Reference to control TfrmConecta.rgTipo : TRadioGroup
|
0064E784   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: ExtCtrls.TCustomRadioGroup.SetItemIndex(TCustomRadioGroup;Integer);
|
0064E78A   E8EDC5DFFF             call    0044AD7C
0064E78F   6A00                   push    $00
0064E791   8D45F0                 lea     eax, [ebp-$10]
0064E794   50                     push    eax

* Possible String Reference to: 'Nome'
|
0064E795   B964E86400             mov     ecx, $0064E864

* Possible String Reference to: 'Servidor'
|
0064E79A   BA50E86400             mov     edx, $0064E850
0064E79F   8B45FC                 mov     eax, [ebp-$04]
0064E7A2   8B30                   mov     esi, [eax]
0064E7A4   FF16                   call    dword ptr [esi]
0064E7A6   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TfrmConecta.edServidor : TEdit
|
0064E7A9   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0064E7AF   E8484FE4FF             call    004936FC
0064E7B4   6A00                   push    $00
0064E7B6   8D45EC                 lea     eax, [ebp-$14]
0064E7B9   50                     push    eax

* Possible String Reference to: 'Caminho'
|
0064E7BA   B974E86400             mov     ecx, $0064E874

* Possible String Reference to: 'Servidor'
|
0064E7BF   BA50E86400             mov     edx, $0064E850
0064E7C4   8B45FC                 mov     eax, [ebp-$04]
0064E7C7   8B30                   mov     esi, [eax]
0064E7C9   FF16                   call    dword ptr [esi]
0064E7CB   8B55EC                 mov     edx, [ebp-$14]

* Reference to control TfrmConecta.edCaminho : TJvFilenameEdit
|
0064E7CE   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0064E7D4   E8F7F7EAFF             call    004FDFD0
0064E7D9   33C0                   xor     eax, eax
0064E7DB   5A                     pop     edx
0064E7DC   59                     pop     ecx
0064E7DD   59                     pop     ecx
0064E7DE   648910                 mov     fs:[eax], edx

****** FINALLY
|
0064E7E1   68F6E76400             push    $0064E7F6
0064E7E6   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
0064E7E9   E8AE5DDBFF             call    0040459C
0064E7EE   C3                     ret


* Reference to: System.@HandleFinally;
|
0064E7EF   E94465DBFF             jmp     00404D38
0064E7F4   EBF0                   jmp     0064E7E6

****** END
|
0064E7F6   33C0                   xor     eax, eax
0064E7F8   5A                     pop     edx
0064E7F9   59                     pop     ecx
0064E7FA   59                     pop     ecx
0064E7FB   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0064E7FE   6818E86400             push    $0064E818
0064E803   8D45EC                 lea     eax, [ebp-$14]
0064E806   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0064E80B   E8B06CDBFF             call    004054C0
0064E810   C3                     ret


* Reference to: System.@HandleFinally;
|
0064E811   E92265DBFF             jmp     00404D38
0064E816   EBEB                   jmp     0064E803

****** END
|
0064E818   5E                     pop     esi
0064E819   5B                     pop     ebx
0064E81A   8BE5                   mov     esp, ebp
0064E81C   5D                     pop     ebp
0064E81D   C3                     ret

*)
end;

procedure TfrmConecta.FormShow(Sender : TObject);
begin
(*
0064E87C   C3                     ret

*)
end;

procedure TfrmConecta.FormCloseQuery(Sender : TObject);
begin
(*
0064E880   55                     push    ebp
0064E881   8BEC                   mov     ebp, esp
0064E883   6A00                   push    $00
0064E885   6A00                   push    $00
0064E887   6A00                   push    $00
0064E889   53                     push    ebx
0064E88A   56                     push    esi
0064E88B   8BF1                   mov     esi, ecx
0064E88D   8BD8                   mov     ebx, eax
0064E88F   33C0                   xor     eax, eax
0064E891   55                     push    ebp

* Possible String Reference to: 'éúcÛÿëã^[‹å]Ã'
|
0064E892   6839E96400             push    $0064E939

***** TRY
|
0064E897   64FF30                 push    dword ptr fs:[eax]
0064E89A   648920                 mov     fs:[eax], esp
0064E89D   A178B47D00             mov     eax, dword ptr [$007DB478]
0064E8A2   8B00                   mov     eax, [eax]
0064E8A4   8B4058                 mov     eax, [eax+$58]
0064E8A7   33D2                   xor     edx, edx
0064E8A9   8B08                   mov     ecx, [eax]
0064E8AB   FF5148                 call    dword ptr [ecx+$48]
0064E8AE   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmConecta.edServidor : TEdit
|
0064E8B1   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0064E8B7   E8104EE4FF             call    004936CC
0064E8BC   FF75F8                 push    dword ptr [ebp-$08]
0064E8BF   6850E96400             push    $0064E950
0064E8C4   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmConecta.edCaminho : TJvFilenameEdit
|
0064E8C7   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0064E8CD   E86AF6EAFF             call    004FDF3C
0064E8D2   FF75F4                 push    dword ptr [ebp-$0C]
0064E8D5   8D45FC                 lea     eax, [ebp-$04]
0064E8D8   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0064E8DD   E83A6FDBFF             call    0040581C
0064E8E2   8B55FC                 mov     edx, [ebp-$04]
0064E8E5   A178B47D00             mov     eax, dword ptr [$007DB478]
0064E8EA   8B00                   mov     eax, [eax]
0064E8EC   8B4058                 mov     eax, [eax+$58]

* Reference to: IBDatabase.TIBDatabase.SetDatabaseName(TIBDatabase;TIBFileName);
|
0064E8EF   E81CC3F1FF             call    0056AC10

* Reference to field TfrmConecta.ModalResult : TModalResult
|
0064E8F4   8B834C020000           mov     eax, [ebx+$024C]
0064E8FA   83F801                 cmp     eax, +$01
0064E8FD   7505                   jnz     0064E904
0064E8FF   C60601                 mov     byte ptr [esi], $01
0064E902   EB12                   jmp     0064E916
0064E904   83F806                 cmp     eax, +$06
0064E907   7505                   jnz     0064E90E
0064E909   C60600                 mov     byte ptr [esi], $00
0064E90C   EB08                   jmp     0064E916
0064E90E   83F802                 cmp     eax, +$02
0064E911   7503                   jnz     0064E916
0064E913   C60601                 mov     byte ptr [esi], $01
0064E916   33C0                   xor     eax, eax
0064E918   5A                     pop     edx
0064E919   59                     pop     ecx
0064E91A   59                     pop     ecx
0064E91B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0064E91E   6840E96400             push    $0064E940
0064E923   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0064E926   E8716BDBFF             call    0040549C
0064E92B   8D45F8                 lea     eax, [ebp-$08]
0064E92E   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0064E933   E8886BDBFF             call    004054C0
0064E938   C3                     ret


* Reference to: System.@HandleFinally;
|
0064E939   E9FA63DBFF             jmp     00404D38
0064E93E   EBE3                   jmp     0064E923

****** END
|
0064E940   5E                     pop     esi
0064E941   5B                     pop     ebx
0064E942   8BE5                   mov     esp, ebp
0064E944   5D                     pop     ebp
0064E945   C3                     ret

*)
end;

procedure TfrmConecta.FormClose(Sender : TObject);
begin
(*
0064E954   55                     push    ebp
0064E955   8BEC                   mov     ebp, esp
0064E957   6A00                   push    $00
0064E959   6A00                   push    $00
0064E95B   6A00                   push    $00
0064E95D   6A00                   push    $00
0064E95F   6A00                   push    $00
0064E961   53                     push    ebx
0064E962   56                     push    esi
0064E963   8BD8                   mov     ebx, eax
0064E965   33C0                   xor     eax, eax
0064E967   55                     push    ebp

* Possible String Reference to: 'éÏbÛÿëÛ^[‹å]Ã'
|
0064E968   6864EA6400             push    $0064EA64

***** TRY
|
0064E96D   64FF30                 push    dword ptr fs:[eax]
0064E970   648920                 mov     fs:[eax], esp
0064E973   8D55F4                 lea     edx, [ebp-$0C]
0064E976   33C0                   xor     eax, eax

* Reference to: System.ParamStr(Integer):String;
|
0064E978   E86F43DBFF             call    00402CEC
0064E97D   8B45F4                 mov     eax, [ebp-$0C]
0064E980   8D55F8                 lea     edx, [ebp-$08]

* Reference to: SysUtils.ExtractFilePath(AnsiString):AnsiString;
|
0064E983   E8B4CEDBFF             call    0040B83C
0064E988   8D45F8                 lea     eax, [ebp-$08]

* Possible String Reference to: 'Servidor.ini'
|
0064E98B   BA7CEA6400             mov     edx, $0064EA7C

* Reference to: System.@LStrCat;
|
0064E990   E8CF6DDBFF             call    00405764
0064E995   8B4DF8                 mov     ecx, [ebp-$08]
0064E998   B201                   mov     dl, $01

* Reference to class TIniFile
|
0064E99A   A1540F4500             mov     eax, dword ptr [$00450F54]

* Reference to: IniFiles.TCustomIniFile.Create(TCustomIniFile;boolean;AnsiString);
|
0064E99F   E86026E0FF             call    00451004
0064E9A4   8945FC                 mov     [ebp-$04], eax
0064E9A7   33C0                   xor     eax, eax
0064E9A9   55                     push    ebp
0064E9AA   6832EA6400             push    $0064EA32

***** TRY
|
0064E9AF   64FF30                 push    dword ptr fs:[eax]
0064E9B2   648920                 mov     fs:[eax], esp

* Reference to control TfrmConecta.rgTipo : TRadioGroup
|
0064E9B5   8B830C030000           mov     eax, [ebx+$030C]

* Reference to field TRadioGroup.ItemIndex : Integer
|
0064E9BB   8B8018020000           mov     eax, [eax+$0218]
0064E9C1   50                     push    eax

* Possible String Reference to: 'Tipo'
|
0064E9C2   B994EA6400             mov     ecx, $0064EA94

* Possible String Reference to: 'Servidor'
|
0064E9C7   BAA4EA6400             mov     edx, $0064EAA4
0064E9CC   8B45FC                 mov     eax, [ebp-$04]
0064E9CF   8B30                   mov     esi, [eax]

* Reference to method TIniFile.WriteInteger(string,string,Longint)
|
0064E9D1   FF560C                 call    dword ptr [esi+$0C]
0064E9D4   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TfrmConecta.edServidor : TEdit
|
0064E9D7   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0064E9DD   E8EA4CE4FF             call    004936CC
0064E9E2   8B45F0                 mov     eax, [ebp-$10]
0064E9E5   50                     push    eax

* Possible String Reference to: 'Nome'
|
0064E9E6   B9B8EA6400             mov     ecx, $0064EAB8

* Possible String Reference to: 'Servidor'
|
0064E9EB   BAA4EA6400             mov     edx, $0064EAA4
0064E9F0   8B45FC                 mov     eax, [ebp-$04]
0064E9F3   8B30                   mov     esi, [eax]

* Reference to method TIniFile.WriteString(string,string,string)
|
0064E9F5   FF5604                 call    dword ptr [esi+$04]
0064E9F8   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TfrmConecta.edCaminho : TJvFilenameEdit
|
0064E9FB   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0064EA01   E836F5EAFF             call    004FDF3C
0064EA06   8B45EC                 mov     eax, [ebp-$14]
0064EA09   50                     push    eax

* Possible String Reference to: 'Caminho'
|
0064EA0A   B9C8EA6400             mov     ecx, $0064EAC8

* Possible String Reference to: 'Servidor'
|
0064EA0F   BAA4EA6400             mov     edx, $0064EAA4
0064EA14   8B45FC                 mov     eax, [ebp-$04]
0064EA17   8B18                   mov     ebx, [eax]

* Reference to method TIniFile.WriteString(string,string,string)
|
0064EA19   FF5304                 call    dword ptr [ebx+$04]
0064EA1C   33C0                   xor     eax, eax
0064EA1E   5A                     pop     edx
0064EA1F   59                     pop     ecx
0064EA20   59                     pop     ecx
0064EA21   648910                 mov     fs:[eax], edx

****** FINALLY
|
0064EA24   6839EA6400             push    $0064EA39
0064EA29   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.TObject.Free(TObject);
|
0064EA2C   E86B5BDBFF             call    0040459C
0064EA31   C3                     ret


* Reference to: System.@HandleFinally;
|
0064EA32   E90163DBFF             jmp     00404D38
0064EA37   EBF0                   jmp     0064EA29

****** END
|
0064EA39   33C0                   xor     eax, eax
0064EA3B   5A                     pop     edx
0064EA3C   59                     pop     ecx
0064EA3D   59                     pop     ecx
0064EA3E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0064EA41   686BEA6400             push    $0064EA6B
0064EA46   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0064EA49   E84E6ADBFF             call    0040549C
0064EA4E   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.@LStrClr(void;void);
|
0064EA51   E8466ADBFF             call    0040549C
0064EA56   8D45F4                 lea     eax, [ebp-$0C]
0064EA59   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0064EA5E   E85D6ADBFF             call    004054C0
0064EA63   C3                     ret


* Reference to: System.@HandleFinally;
|
0064EA64   E9CF62DBFF             jmp     00404D38
0064EA69   EBDB                   jmp     0064EA46

****** END
|
0064EA6B   5E                     pop     esi
0064EA6C   5B                     pop     ebx
0064EA6D   8BE5                   mov     esp, ebp
0064EA6F   5D                     pop     ebp
0064EA70   C3                     ret

*)
end;

procedure TfrmConecta.rgTipoClick(Sender : TObject);
begin
(*
0064EAD0   55                     push    ebp
0064EAD1   8BEC                   mov     ebp, esp
0064EAD3   53                     push    ebx
0064EAD4   8BD8                   mov     ebx, eax

* Reference to control TfrmConecta.rgTipo : TRadioGroup
|
0064EAD6   8B830C030000           mov     eax, [ebx+$030C]

* Reference to field TRadioGroup.ItemIndex : Integer
|
0064EADC   83B81802000000         cmp     dword ptr [eax+$0218], +$00
0064EAE3   752D                   jnz     0064EB12
0064EAE5   B201                   mov     dl, $01

* Reference to control TfrmConecta.lbServidor : TLabel
|
0064EAE7   8B8300030000           mov     eax, [ebx+$0300]
0064EAED   8B08                   mov     ecx, [eax]

* Reference to method TLabel.SetEnabled(Boolean)
|
0064EAEF   FF5164                 call    dword ptr [ecx+$64]
0064EAF2   B201                   mov     dl, $01

* Reference to control TfrmConecta.edServidor : TEdit
|
0064EAF4   8B83FC020000           mov     eax, [ebx+$02FC]
0064EAFA   8B08                   mov     ecx, [eax]

* Reference to method TEdit.SetEnabled(Boolean)
|
0064EAFC   FF5164                 call    dword ptr [ecx+$64]
0064EAFF   BAFFFFFF00             mov     edx, $00FFFFFF

* Reference to control TfrmConecta.edServidor : TEdit
|
0064EB04   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
0064EB0A   E8754DE4FF             call    00493884
0064EB0F   5B                     pop     ebx
0064EB10   5D                     pop     ebp
0064EB11   C3                     ret

0064EB12   33D2                   xor     edx, edx

* Reference to control btFechar : N.A.
|
0064EB14   8B8300030000           mov     eax, [ebx+$0300]
0064EB1A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TN.A..OFFS_64
|
0064EB1C   FF5164                 call    dword ptr [ecx+$64]
0064EB1F   33D2                   xor     edx, edx

* Reference to control meTexto : N.A.
|
0064EB21   8B83FC020000           mov     eax, [ebx+$02FC]
0064EB27   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TN.A..OFFS_64
|
0064EB29   FF5164                 call    dword ptr [ecx+$64]
0064EB2C   BAC0C0C000             mov     edx, $00C0C0C0

* Reference to control meTexto : N.A.
|
0064EB31   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
0064EB37   E8484DE4FF             call    00493884
0064EB3C   33D2                   xor     edx, edx

* Reference to control meTexto : N.A.
|
0064EB3E   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0064EB44   E8B34BE4FF             call    004936FC
0064EB49   5B                     pop     ebx
0064EB4A   5D                     pop     ebp
0064EB4B   C3                     ret

*)
end;

procedure TfrmConecta.btTestarClick(Sender : TObject);
begin
(*
0064EB4C   55                     push    ebp
0064EB4D   8BEC                   mov     ebp, esp
0064EB4F   6A00                   push    $00
0064EB51   6A00                   push    $00
0064EB53   6A00                   push    $00
0064EB55   53                     push    ebx
0064EB56   56                     push    esi
0064EB57   57                     push    edi
0064EB58   8BD8                   mov     ebx, eax
0064EB5A   33C0                   xor     eax, eax
0064EB5C   55                     push    ebp

* Possible String Reference to: 'éô`Ûÿëã_^[‹å]Ã'
|
0064EB5D   683FEC6400             push    $0064EC3F

***** TRY
|
0064EB62   64FF30                 push    dword ptr fs:[eax]
0064EB65   648920                 mov     fs:[eax], esp
0064EB68   33C0                   xor     eax, eax
0064EB6A   55                     push    ebp

* Possible String Reference to: 'é‚^Ûÿj'
|
0064EB6B   68FDEB6400             push    $0064EBFD

***** TRY
|
0064EB70   64FF30                 push    dword ptr fs:[eax]
0064EB73   648920                 mov     fs:[eax], esp
0064EB76   A178B47D00             mov     eax, dword ptr [$007DB478]
0064EB7B   8B00                   mov     eax, [eax]
0064EB7D   8B4058                 mov     eax, [eax+$58]
0064EB80   33D2                   xor     edx, edx
0064EB82   8B08                   mov     ecx, [eax]
0064EB84   FF5148                 call    dword ptr [ecx+$48]
0064EB87   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TfrmConecta.edServidor : TEdit
|
0064EB8A   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0064EB90   E8374BE4FF             call    004936CC
0064EB95   FF75F8                 push    dword ptr [ebp-$08]
0064EB98   6858EC6400             push    $0064EC58
0064EB9D   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TfrmConecta.edCaminho : TJvFilenameEdit
|
0064EBA0   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0064EBA6   E891F3EAFF             call    004FDF3C
0064EBAB   FF75F4                 push    dword ptr [ebp-$0C]
0064EBAE   8D45FC                 lea     eax, [ebp-$04]
0064EBB1   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0064EBB6   E8616CDBFF             call    0040581C
0064EBBB   8B55FC                 mov     edx, [ebp-$04]
0064EBBE   A178B47D00             mov     eax, dword ptr [$007DB478]
0064EBC3   8B00                   mov     eax, [eax]
0064EBC5   8B4058                 mov     eax, [eax+$58]

* Reference to: IBDatabase.TIBDatabase.SetDatabaseName(TIBDatabase;TIBFileName);
|
0064EBC8   E843C0F1FF             call    0056AC10
0064EBCD   A178B47D00             mov     eax, dword ptr [$007DB478]
0064EBD2   8B00                   mov     eax, [eax]
0064EBD4   8B4058                 mov     eax, [eax+$58]
0064EBD7   B201                   mov     dl, $01
0064EBD9   8B08                   mov     ecx, [eax]
0064EBDB   FF5148                 call    dword ptr [ecx+$48]
0064EBDE   6A00                   push    $00
0064EBE0   668B0D5CEC6400         mov     cx, word ptr [$0064EC5C]
0064EBE7   B202                   mov     dl, $02

* Possible String Reference to: 'Conectado com sucesso ao Banco de D
|                                ados!'
|
0064EBE9   B868EC6400             mov     eax, $0064EC68

|
0064EBEE   E8394FDFFF             call    00443B2C
0064EBF3   33C0                   xor     eax, eax
0064EBF5   5A                     pop     edx
0064EBF6   59                     pop     ecx
0064EBF7   59                     pop     ecx
0064EBF8   648910                 mov     fs:[eax], edx
0064EBFB   EB1F                   jmp     0064EC1C

* Reference to: System.@HandleAnyException;
|
0064EBFD   E9825EDBFF             jmp     00404A84
0064EC02   6A00                   push    $00
0064EC04   668B0D5CEC6400         mov     cx, word ptr [$0064EC5C]
0064EC0B   B202                   mov     dl, $02

* Possible String Reference to: 'Falha na conexão com o Banco de Dad
|                                os!'
|
0064EC0D   B89CEC6400             mov     eax, $0064EC9C

|
0064EC12   E8154FDFFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0064EC17   E89462DBFF             call    00404EB0

****** END
|
0064EC1C   33C0                   xor     eax, eax
0064EC1E   5A                     pop     edx
0064EC1F   59                     pop     ecx
0064EC20   59                     pop     ecx
0064EC21   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
0064EC24   6846EC6400             push    $0064EC46
0064EC29   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0064EC2C   E86B68DBFF             call    0040549C
0064EC31   8D45F8                 lea     eax, [ebp-$08]
0064EC34   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0064EC39   E88268DBFF             call    004054C0
0064EC3E   C3                     ret


* Reference to: System.@HandleFinally;
|
0064EC3F   E9F460DBFF             jmp     00404D38
0064EC44   EBE3                   jmp     0064EC29

****** END
|
0064EC46   5F                     pop     edi
0064EC47   5E                     pop     esi
0064EC48   5B                     pop     ebx
0064EC49   8BE5                   mov     esp, ebp
0064EC4B   5D                     pop     ebp
0064EC4C   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ECC5(Sender : TObject);
begin
(*
0064ECC5   8BEC                   mov     ebp, esp
0064ECC7   33C0                   xor     eax, eax
0064ECC9   55                     push    ebp

* Possible String Reference to: 'éJ`Ûÿëø]Ã‹Àƒ-ÄÝ}'
|
0064ECCA   68E9EC6400             push    $0064ECE9

***** TRY
|
0064ECCF   64FF30                 push    dword ptr fs:[eax]
0064ECD2   648920                 mov     fs:[eax], esp
0064ECD5   FF05C4DD7D00           inc     dword ptr [$007DDDC4]
0064ECDB   33C0                   xor     eax, eax
0064ECDD   5A                     pop     edx
0064ECDE   59                     pop     ecx
0064ECDF   59                     pop     ecx
0064ECE0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÄÝ}'
|
0064ECE3   68F0EC6400             push    $0064ECF0
0064ECE8   C3                     ret


* Reference to: System.@HandleFinally;
|
0064ECE9   E94A60DBFF             jmp     00404D38
0064ECEE   EBF8                   jmp     0064ECE8

****** END
|
0064ECF0   5D                     pop     ebp
0064ECF1   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ECF4(Sender : TObject);
begin
(*
0064ECF4   832DC4DD7D0001         sub     dword ptr [$007DDDC4], +$01
0064ECFB   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ECFC(Sender : TObject);
begin
(*
0064ECFC   55                     push    ebp
0064ECFD   8BEC                   mov     ebp, esp
0064ECFF   33C0                   xor     eax, eax
0064ED01   55                     push    ebp
0064ED02   6821ED6400             push    $0064ED21

***** TRY
|
0064ED07   64FF30                 push    dword ptr fs:[eax]
0064ED0A   648920                 mov     fs:[eax], esp
0064ED0D   FF05C8DD7D00           inc     dword ptr [$007DDDC8]
0064ED13   33C0                   xor     eax, eax
0064ED15   5A                     pop     edx
0064ED16   59                     pop     ecx
0064ED17   59                     pop     ecx
0064ED18   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÈÝ}'
|
0064ED1B   6828ED6400             push    $0064ED28
0064ED20   C3                     ret


* Reference to: System.@HandleFinally;
|
0064ED21   E91260DBFF             jmp     00404D38
0064ED26   EBF8                   jmp     0064ED20

****** END
|
0064ED28   5D                     pop     ebp
0064ED29   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ED2C(Sender : TObject);
begin
(*
0064ED2C   832DC8DD7D0001         sub     dword ptr [$007DDDC8], +$01
0064ED33   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ED34(Sender : TObject);
begin
(*
0064ED34   55                     push    ebp
0064ED35   8BEC                   mov     ebp, esp
0064ED37   33C0                   xor     eax, eax
0064ED39   55                     push    ebp

* Possible String Reference to: 'éÚ_Ûÿëø]Ã‹Àƒ-ÌÝ}'
|
0064ED3A   6859ED6400             push    $0064ED59

***** TRY
|
0064ED3F   64FF30                 push    dword ptr fs:[eax]
0064ED42   648920                 mov     fs:[eax], esp
0064ED45   FF05CCDD7D00           inc     dword ptr [$007DDDCC]
0064ED4B   33C0                   xor     eax, eax
0064ED4D   5A                     pop     edx
0064ED4E   59                     pop     ecx
0064ED4F   59                     pop     ecx
0064ED50   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÌÝ}'
|
0064ED53   6860ED6400             push    $0064ED60
0064ED58   C3                     ret


* Reference to: System.@HandleFinally;
|
0064ED59   E9DA5FDBFF             jmp     00404D38
0064ED5E   EBF8                   jmp     0064ED58

****** END
|
0064ED60   5D                     pop     ebp
0064ED61   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ED64(Sender : TObject);
begin
(*
0064ED64   832DCCDD7D0001         sub     dword ptr [$007DDDCC], +$01
0064ED6B   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ED6C(Sender : TObject);
begin
(*
0064ED6C   55                     push    ebp
0064ED6D   8BEC                   mov     ebp, esp
0064ED6F   33C0                   xor     eax, eax
0064ED71   55                     push    ebp

* Possible String Reference to: 'é¢_Ûÿëø]Ã‹Àƒ-ÐÝ}'
|
0064ED72   6891ED6400             push    $0064ED91

***** TRY
|
0064ED77   64FF30                 push    dword ptr fs:[eax]
0064ED7A   648920                 mov     fs:[eax], esp
0064ED7D   FF05D0DD7D00           inc     dword ptr [$007DDDD0]
0064ED83   33C0                   xor     eax, eax
0064ED85   5A                     pop     edx
0064ED86   59                     pop     ecx
0064ED87   59                     pop     ecx
0064ED88   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÐÝ}'
|
0064ED8B   6898ED6400             push    $0064ED98
0064ED90   C3                     ret


* Reference to: System.@HandleFinally;
|
0064ED91   E9A25FDBFF             jmp     00404D38
0064ED96   EBF8                   jmp     0064ED90

****** END
|
0064ED98   5D                     pop     ebp
0064ED99   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064ED9C(Sender : TObject);
begin
(*
0064ED9C   832DD0DD7D0001         sub     dword ptr [$007DDDD0], +$01
0064EDA3   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064EDA4(Sender : TObject);
begin
(*
0064EDA4   55                     push    ebp
0064EDA5   8BEC                   mov     ebp, esp
0064EDA7   33C0                   xor     eax, eax
0064EDA9   55                     push    ebp

* Possible String Reference to: 'éj_Ûÿëø]Ã‹Àƒ-ÔÝ}'
|
0064EDAA   68C9ED6400             push    $0064EDC9

***** TRY
|
0064EDAF   64FF30                 push    dword ptr fs:[eax]
0064EDB2   648920                 mov     fs:[eax], esp
0064EDB5   FF05D4DD7D00           inc     dword ptr [$007DDDD4]
0064EDBB   33C0                   xor     eax, eax
0064EDBD   5A                     pop     edx
0064EDBE   59                     pop     ecx
0064EDBF   59                     pop     ecx
0064EDC0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ÔÝ}'
|
0064EDC3   68D0ED6400             push    $0064EDD0
0064EDC8   C3                     ret


* Reference to: System.@HandleFinally;
|
0064EDC9   E96A5FDBFF             jmp     00404D38
0064EDCE   EBF8                   jmp     0064EDC8

****** END
|
0064EDD0   5D                     pop     ebp
0064EDD1   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064EDD4(Sender : TObject);
begin
(*
0064EDD4   832DD4DD7D0001         sub     dword ptr [$007DDDD4], +$01
0064EDDB   7307                   jnb     0064EDE4
0064EDDD   C605D8DD7D0000         mov     byte ptr [$007DDDD8], $00
0064EDE4   C3                     ret

*)
end;

procedure TfrmConecta._PROC_0064EDE8(Sender : TObject);
begin
(*
0064EDE8   34EE                   xor     al, $EE
0064EDEA   640000                 add     fs:[eax], al
0064EDED   0000                   add     [eax], al

*)
end;

end.