unit ConfNum;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, JvExStdCtrls, JvEdit,
  JvValidateEdit, ExtCtrls;
  
type
  TFrmConfirmaNumLcto=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    EdNumLcto: TJvValidateEdit;
    Bevel1: TBevel;
    BitBtn2: TBitBtn;
    BitBtn1: TBitBtn;
    procedure FormShow(Sender : TObject);
    procedure _PROC_00658670(Sender : TObject);
    procedure _PROC_006586A0(Sender : TObject);
    procedure _PROC_006586A8(Sender : TObject);
    procedure _PROC_0065878D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmConfirmaNumLcto: TFrmConfirmaNumLcto;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmConfirmaNumLcto.FormShow(Sender : TObject);
begin
(*
0065865C   55                     push    ebp
0065865D   8BEC                   mov     ebp, esp

* Reference to control TFrmConfirmaNumLcto.EdNumLcto : TJvValidateEdit
|
0065865F   8B8000030000           mov     eax, [eax+$0300]
00658665   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvValidateEdit.OFFS_00C4
|
00658667   FF92C4000000           call    dword ptr [edx+$00C4]
0065866D   5D                     pop     ebp
0065866E   C3                     ret

*)
end;

procedure TFrmConfirmaNumLcto._PROC_00658670(Sender : TObject);
begin
(*
00658670   55                     push    ebp
00658671   8BEC                   mov     ebp, esp
00658673   33C0                   xor     eax, eax
00658675   55                     push    ebp

* Possible String Reference to: 'éžÆÚÿëø]Ã‹Àƒ-HÞ}'
|
00658676   6895866500             push    $00658695

***** TRY
|
0065867B   64FF30                 push    dword ptr fs:[eax]
0065867E   648920                 mov     fs:[eax], esp
00658681   FF0548DE7D00           inc     dword ptr [$007DDE48]
00658687   33C0                   xor     eax, eax
00658689   5A                     pop     edx
0065868A   59                     pop     ecx
0065868B   59                     pop     ecx
0065868C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-HÞ}'
|
0065868F   689C866500             push    $0065869C
00658694   C3                     ret


* Reference to: System.@HandleFinally;
|
00658695   E99EC6DAFF             jmp     00404D38
0065869A   EBF8                   jmp     00658694

****** END
|
0065869C   5D                     pop     ebp
0065869D   C3                     ret

*)
end;

procedure TFrmConfirmaNumLcto._PROC_006586A0(Sender : TObject);
begin
(*
006586A0   832D48DE7D0001         sub     dword ptr [$007DDE48], +$01
006586A7   C3                     ret

*)
end;

procedure TFrmConfirmaNumLcto._PROC_006586A8(Sender : TObject);
begin
(*
006586A8   F4                     hlt
006586A9   866500                 xchg    [ebp+$00], ah
006586AC   0000                   add     [eax], al

*)
end;

procedure TFrmConfirmaNumLcto._PROC_0065878D(Sender : TObject);
begin
(*
0065878D   53                     push    ebx
0065878E   55                     push    ebp
0065878F   41                     inc     ecx
00658790   52                     push    edx
00658791   49                     dec     ecx
00658792   4F                     dec     edi
00658793   6800000002             push    $02000000
00658798   000B                   add     [ebx], cl
0065879A   44                     inc     esp
0065879B   7341                   jnb     006587DE
0065879D   6E                     outsb
0065879E   6461                   popa
006587A0   6D                     insd
006587A1   656E                   outsb
006587A3   746F                   jz      00658814
006587A5   0100                   add     [eax], eax
006587A7   17                     pop     ss
006587A8   00F0                   add     al, dh
006587AA   876500                 xchg    [ebp+$00], esp
006587AD   10446174               adc     [ecx+$74], al
006587B1   61                     popa
006587B2   4D                     dec     ebp
006587B3   6F                     outsd
006587B4   64756C                 jnz     00658823
006587B7   6543                   inc     ebx
006587B9   7265                   jb      00658820
006587BB   61                     popa
006587BC   7465                   jz      00658823
006587BE   0454                   add     al, +$54
006587C0   44                     inc     esp
006587C1   6D                     insd
006587C2   3403                   xor     al, $03
006587C4   00B4A555001897         add     [ebp+$97180055], dh
006587CB   55                     push    ebp
006587CC   0064A84D               add     [eax+ebp*4+$4D], ah
006587D0   008D4000D887           add     [ebp+$87D80040], cl
006587D6   650007                 add     gs:[edi], al
006587D9   0454                   add     al, +$54
006587DB   44                     inc     esp
006587DC   6D                     insd
006587DD   34F4                   xor     al, $F4
006587DF   866500                 xchg    [ebp+$00], ah
006587E2   E412                   in      al, $12
006587E4   42                     inc     edx
006587E5   000500045564           add     [$64550400], al
006587EB   6D                     insd
006587EC   3400                   xor     al, $00
006587EE   0090558BECE8           add     [eax+$E8EC8B55], dl
006587F4   0400                   add     al, +$00
006587F6   0000                   add     [eax], al

006587F8   5D                     pop     ebp
006587F9   C3                     ret

006587FA   8BC0                   mov     eax, eax
006587FC   55                     push    ebp
006587FD   8BEC                   mov     ebp, esp
006587FF   53                     push    ebx
00658800   56                     push    esi
00658801   57                     push    edi
00658802   BE4CDE7D00             mov     esi, $007DDE4C
00658807   8B3D78B47D00           mov     edi, [$007DB478]
0065880D   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponentCount(TComponent):Integer;
|
0065880F   E8EC5ADDFF             call    0042E300
00658814   8BD8                   mov     ebx, eax
00658816   4B                     dec     ebx
00658817   83FB00                 cmp     ebx, +$00
0065881A   0F8CDB000000           jl      006588FB
00658820   8BD3                   mov     edx, ebx
00658822   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
00658824   E8AB5ADDFF             call    0042E2D4

* Reference to class TIBDataSet
|
00658829   8B15B4A55500           mov     edx, [$0055A5B4]

* Reference to: System.@IsClass(TObject;TClass):Boolean;
|
0065882F   E8FCBEDAFF             call    00404730
00658834   84C0                   test    al, al
00658836   0F84B5000000           jz      006588F1
0065883C   8BD3                   mov     edx, ebx
0065883E   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
00658840   E88F5ADDFF             call    0042E2D4
00658845   8B17                   mov     edx, [edi]
00658847   8990BC000000           mov     [eax+$00BC], edx

* Possible String Reference to: 'U‹ì‹Âèæ²þÿ]ÃU‹ìj'
|
0065884D   C780B8000000E8CF7B00   mov     dword ptr [eax+$00B8], $007BCFE8
00658857   8BD3                   mov     edx, ebx
00658859   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
0065885B   E8745ADDFF             call    0042E2D4
00658860   83780C00               cmp     dword ptr [eax+$0C], +$00
00658864   0F8E87000000           jle     006588F1
0065886A   8BD3                   mov     edx, ebx
0065886C   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
0065886E   E8615ADDFF             call    0042E2D4
00658873   8B17                   mov     edx, [edi]
00658875   8990D4000000           mov     [eax+$00D4], edx

* Possible String Reference to: 'U‹ìj'
|
0065887B   C780D000000044D27B00   mov     dword ptr [eax+$00D0], $007BD244
00658885   8BD3                   mov     edx, ebx
00658887   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
00658889   E8465ADDFF             call    0042E2D4
0065888E   8B17                   mov     edx, [edi]
00658890   8990E4000000           mov     [eax+$00E4], edx

* Possible String Reference to: 'U‹ì3ÉQQQQSV‹ò3ÀUh”Ñ{'
|
00658896   C780E0000000C8D07B00   mov     dword ptr [eax+$00E0], $007BD0C8
006588A0   8BD3                   mov     edx, ebx
006588A2   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
006588A4   E82B5ADDFF             call    0042E2D4
006588A9   8B17                   mov     edx, [edi]
006588AB   8990F4000000           mov     [eax+$00F4], edx

* Possible String Reference to: 'U‹ì3ÉQQQQSVW‹ò‹ø3ÀUhßÔ{'
|
006588B1   C780F0000000C0D37B00   mov     dword ptr [eax+$00F0], $007BD3C0
006588BB   8BD3                   mov     edx, ebx
006588BD   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
006588BF   E8105ADDFF             call    0042E2D4
006588C4   8B17                   mov     edx, [edi]
006588C6   8990FC000000           mov     [eax+$00FC], edx

* Possible String Reference to: 'U‹ìj'
|
006588CC   C780F8000000F4CF7B00   mov     dword ptr [eax+$00F8], $007BCFF4
006588D6   8BD3                   mov     edx, ebx
006588D8   8B06                   mov     eax, [esi]

* Reference to: Classes.TComponent.GetComponent(TComponent;Integer):TComponent;
|
006588DA   E8F559DDFF             call    0042E2D4
006588DF   8B17                   mov     edx, [edi]
006588E1   89901C010000           mov     [eax+$011C], edx

* Possible String Reference to: 'U‹ìj'
|
006588E7   C7801801000008CF7B00   mov     dword ptr [eax+$0118], $007BCF08
006588F1   4B                     dec     ebx
006588F2   83FBFF                 cmp     ebx, -$01
006588F5   0F8525FFFFFF           jnz     00658820
006588FB   5F                     pop     edi
006588FC   5E                     pop     esi
006588FD   5B                     pop     ebx
006588FE   5D                     pop     ebp
006588FF   C3                     ret

*)
end;

end.