unit DBLogDlg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls;
  
type
  TLoginDialog=class(TForm)
    Panel: TPanel;
    Bevel: TBevel;
    DatabaseName: TLabel;
    OKButton: TButton;
    CancelButton: TButton;
    Panel1: TPanel;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    Password: TEdit;
    UserName: TEdit;
    procedure FormShow(Sender : TObject);
    procedure _PROC_0050A9F4(Sender : TObject);
    procedure _PROC_0050AB24(Sender : TObject);
    procedure _PROC_0050AD2C(Sender : TObject);
    procedure _PROC_0050AD3C(Sender : TObject);
    procedure _PROC_0050AD6C(Sender : TObject);
    procedure _PROC_0050ADC0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  LoginDialog: TLoginDialog;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TLoginDialog.FormShow(Sender : TObject);
begin
(*
0050ACE4   53                     push    ebx
0050ACE5   56                     push    esi
0050ACE6   8BD8                   mov     ebx, eax

* Reference to control TLoginDialog.Panel : TPanel
|
0050ACE8   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: Controls.TControl.GetClientWidth(TControl):Integer;
|
0050ACEE   E8DD83F8FF             call    004930D0

* Reference to control TLoginDialog.DatabaseName : TLabel
|
0050ACF3   8BB300030000           mov     esi, [ebx+$0300]

* Reference to field TLabel.Width : Integer
|
0050ACF9   8B5648                 mov     edx, [esi+$48]
0050ACFC   035640                 add     edx, [esi+$40]
0050ACFF   3BC2                   cmp     eax, edx
0050AD01   7F24                   jnle    0050AD27

* Reference to control TLoginDialog.Panel : TPanel
|
0050AD03   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: Controls.TControl.GetClientWidth(TControl):Integer;
|
0050AD09   E8C283F8FF             call    004930D0
0050AD0E   8BD0                   mov     edx, eax

* Reference to control TLoginDialog.DatabaseName : TLabel
|
0050AD10   8B8300030000           mov     eax, [ebx+$0300]
0050AD16   2B5040                 sub     edx, dword ptr [eax+$40]
0050AD19   83EA05                 sub     edx, +$05

* Reference to control TLoginDialog.DatabaseName : TLabel
|
0050AD1C   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Controls.TControl.SetWidth(TControl;Integer);
|
0050AD22   E83981F8FF             call    00492E60
0050AD27   5E                     pop     esi
0050AD28   5B                     pop     ebx
0050AD29   C3                     ret

*)
end;

procedure TLoginDialog._PROC_0050A9F4(Sender : TObject);
begin
(*
0050A9F4   55                     push    ebp
0050A9F5   8BEC                   mov     ebp, esp
0050A9F7   83C4F0                 add     esp, -$10
0050A9FA   53                     push    ebx
0050A9FB   56                     push    esi
0050A9FC   57                     push    edi
0050A9FD   33DB                   xor     ebx, ebx
0050A9FF   895DF0                 mov     [ebp-$10], ebx
0050AA02   895DF4                 mov     [ebp-$0C], ebx
0050AA05   8BF9                   mov     edi, ecx
0050AA07   8BDA                   mov     ebx, edx
0050AA09   8BF0                   mov     esi, eax
0050AA0B   33C0                   xor     eax, eax
0050AA0D   55                     push    ebp
0050AA0E   6810AB5000             push    $0050AB10

***** TRY
|
0050AA13   64FF30                 push    dword ptr fs:[eax]
0050AA16   648920                 mov     fs:[eax], esp
0050AA19   8B0D54AE7D00           mov     ecx, [$007DAE54]
0050AA1F   8B09                   mov     ecx, [ecx]
0050AA21   B201                   mov     dl, $01

* Reference to class TLoginDialog
|
0050AA23   A198A65000             mov     eax, dword ptr [$0050A698]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0050AA28   E8E334FAFF             call    004ADF10
0050AA2D   8945F8                 mov     [ebp-$08], eax
0050AA30   33C0                   xor     eax, eax
0050AA32   55                     push    ebp
0050AA33   68EEAA5000             push    $0050AAEE

***** TRY
|
0050AA38   64FF30                 push    dword ptr fs:[eax]
0050AA3B   648920                 mov     fs:[eax], esp
0050AA3E   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.DatabaseName : TLabel
|
0050AA41   8B8000030000           mov     eax, [eax+$0300]
0050AA47   8BD6                   mov     edx, esi

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0050AA49   E8AE8CF8FF             call    004936FC
0050AA4E   8B13                   mov     edx, [ebx]
0050AA50   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AA53   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0050AA59   E89E8CF8FF             call    004936FC
0050AA5E   C645FF00               mov     byte ptr [ebp-$01], $00
0050AA62   807D0800               cmp     byte ptr [ebp+$08], $00
0050AA66   7412                   jz      0050AA7A
0050AA68   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AA6B   8B8020030000           mov     eax, [eax+$0320]
0050AA71   33D2                   xor     edx, edx
0050AA73   8B08                   mov     ecx, [eax]

* Reference to method TEdit.SetEnabled(Boolean)
|
0050AA75   FF5164                 call    dword ptr [ecx+$64]
0050AA78   EB16                   jmp     0050AA90
0050AA7A   833B00                 cmp     dword ptr [ebx], +$00
0050AA7D   7511                   jnz     0050AA90
0050AA7F   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AA82   8B9020030000           mov     edx, [eax+$0320]
0050AA88   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);
|
0050AA8B   E8905CFAFF             call    004B0720
0050AA90   8B45F8                 mov     eax, [ebp-$08]
0050AA93   8B10                   mov     edx, [eax]

* Reference to method TLoginDialog.ShowModal()
|
0050AA95   FF92EC000000           call    dword ptr [edx+$00EC]
0050AA9B   48                     dec     eax
0050AA9C   753A                   jnz     0050AAD8
0050AA9E   8D55F4                 lea     edx, [ebp-$0C]
0050AAA1   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AAA4   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0050AAAA   E81D8CF8FF             call    004936CC
0050AAAF   8B55F4                 mov     edx, [ebp-$0C]
0050AAB2   8BC3                   mov     eax, ebx

* Reference to: System.@LStrAsg(void;void;void;void);
|
0050AAB4   E837AAEFFF             call    004054F0
0050AAB9   8D55F0                 lea     edx, [ebp-$10]
0050AABC   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Password : TEdit
|
0050AABF   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0050AAC5   E8028CF8FF             call    004936CC
0050AACA   8B55F0                 mov     edx, [ebp-$10]
0050AACD   8BC7                   mov     eax, edi

* Reference to: System.@LStrAsg(void;void;void;void);
|
0050AACF   E81CAAEFFF             call    004054F0
0050AAD4   C645FF01               mov     byte ptr [ebp-$01], $01
0050AAD8   33C0                   xor     eax, eax
0050AADA   5A                     pop     edx
0050AADB   59                     pop     ecx
0050AADC   59                     pop     ecx
0050AADD   648910                 mov     fs:[eax], edx

****** FINALLY
|
0050AAE0   68F5AA5000             push    $0050AAF5
0050AAE5   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.TObject.Free(TObject);
|
0050AAE8   E8AF9AEFFF             call    0040459C
0050AAED   C3                     ret


* Reference to: System.@HandleFinally;
|
0050AAEE   E945A2EFFF             jmp     00404D38
0050AAF3   EBF0                   jmp     0050AAE5

****** END
|
0050AAF5   33C0                   xor     eax, eax
0050AAF7   5A                     pop     edx
0050AAF8   59                     pop     ecx
0050AAF9   59                     pop     ecx
0050AAFA   648910                 mov     fs:[eax], edx

****** FINALLY
|
0050AAFD   6817AB5000             push    $0050AB17
0050AB02   8D45F0                 lea     eax, [ebp-$10]
0050AB05   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0050AB0A   E8B1A9EFFF             call    004054C0
0050AB0F   C3                     ret


* Reference to: System.@HandleFinally;
|
0050AB10   E923A2EFFF             jmp     00404D38
0050AB15   EBEB                   jmp     0050AB02

****** END
|
0050AB17   8A45FF                 mov     al, byte ptr [ebp-$01]
0050AB1A   5F                     pop     edi
0050AB1B   5E                     pop     esi
0050AB1C   5B                     pop     ebx
0050AB1D   8BE5                   mov     esp, ebp
0050AB1F   5D                     pop     ebp
0050AB20   C20400                 ret     $0004

*)
end;

procedure TLoginDialog._PROC_0050AB24(Sender : TObject);
begin
(*
0050AB24   55                     push    ebp
0050AB25   8BEC                   mov     ebp, esp
0050AB27   33C9                   xor     ecx, ecx
0050AB29   51                     push    ecx
0050AB2A   51                     push    ecx
0050AB2B   51                     push    ecx
0050AB2C   51                     push    ecx
0050AB2D   51                     push    ecx
0050AB2E   53                     push    ebx
0050AB2F   56                     push    esi
0050AB30   8BF2                   mov     esi, edx
0050AB32   8BD8                   mov     ebx, eax
0050AB34   33C0                   xor     eax, eax
0050AB36   55                     push    ebp
0050AB37   68D2AC5000             push    $0050ACD2

***** TRY
|
0050AB3C   64FF30                 push    dword ptr fs:[eax]
0050AB3F   648920                 mov     fs:[eax], esp
0050AB42   8B0D54AE7D00           mov     ecx, [$007DAE54]
0050AB48   8B09                   mov     ecx, [ecx]
0050AB4A   B201                   mov     dl, $01

* Reference to class TLoginDialog
|
0050AB4C   A198A65000             mov     eax, dword ptr [$0050A698]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0050AB51   E8BA33FAFF             call    004ADF10
0050AB56   8945F8                 mov     [ebp-$08], eax
0050AB59   33D2                   xor     edx, edx
0050AB5B   55                     push    ebp
0050AB5C   68A8AC5000             push    $0050ACA8

***** TRY
|
0050AB61   64FF32                 push    dword ptr fs:[edx]
0050AB64   648922                 mov     fs:[edx], esp
0050AB67   8D55F4                 lea     edx, [ebp-$0C]
0050AB6A   A184A57D00             mov     eax, dword ptr [$007DA584]

* Reference to: System.LoadResString(PResStringRec):String;
|
0050AB6F   E828CDEFFF             call    0040789C
0050AB74   8B55F4                 mov     edx, [ebp-$0C]
0050AB77   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0050AB7A   E87D8BF8FF             call    004936FC
0050AB7F   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Bevel : TBevel
|
0050AB82   8B80FC020000           mov     eax, [eax+$02FC]
0050AB88   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0050AB8A   E85D8AF8FF             call    004935EC
0050AB8F   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.DatabaseName : TLabel
|
0050AB92   8B8000030000           mov     eax, [eax+$0300]
0050AB98   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0050AB9A   E84D8AF8FF             call    004935EC
0050AB9F   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Label3 : TLabel
|
0050ABA2   8B8018030000           mov     eax, [eax+$0318]
0050ABA8   33D2                   xor     edx, edx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0050ABAA   E83D8AF8FF             call    004935EC
0050ABAF   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Panel : TPanel
|
0050ABB2   8B80F8020000           mov     eax, [eax+$02F8]

* Reference to field TPanel.Height : Integer
|
0050ABB8   8B504C                 mov     edx, [eax+$4C]
0050ABBB   8B4DF8                 mov     ecx, [ebp-$08]
0050ABBE   8B89FC020000           mov     ecx, [ecx+$02FC]
0050ABC4   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
0050ABC7   E8B882F8FF             call    00492E84
0050ABCC   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.OKButton : TButton
|
0050ABCF   8B8004030000           mov     eax, [eax+$0304]

* Reference to field TButton.Top : Integer
|
0050ABD5   8B5044                 mov     edx, [eax+$44]
0050ABD8   8B4DF8                 mov     ecx, [ebp-$08]
0050ABDB   8B89FC020000           mov     ecx, [ecx+$02FC]
0050ABE1   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
0050ABE4   E84F82F8FF             call    00492E38
0050ABE9   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.CancelButton : TButton
|
0050ABEC   8B8008030000           mov     eax, [eax+$0308]

* Reference to field TButton.Top : Integer
|
0050ABF2   8B5044                 mov     edx, [eax+$44]
0050ABF5   8B4DF8                 mov     ecx, [ebp-$08]
0050ABF8   8B89FC020000           mov     ecx, [ecx+$02FC]
0050ABFE   2B5144                 sub     edx, dword ptr [ecx+$44]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
0050AC01   E83282F8FF             call    00492E38
0050AC06   8B45F8                 mov     eax, [ebp-$08]

* Reference to field TLoginDialog.Height : Integer
|
0050AC09   8B504C                 mov     edx, [eax+$4C]
0050AC0C   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Bevel : TBevel
|
0050AC0F   8B80FC020000           mov     eax, [eax+$02FC]
0050AC15   2B5044                 sub     edx, dword ptr [eax+$44]
0050AC18   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Controls.TControl.SetHeight(TControl;Integer);
|
0050AC1B   E86482F8FF             call    00492E84
0050AC20   8B13                   mov     edx, [ebx]
0050AC22   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AC25   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0050AC2B   E8CC8AF8FF             call    004936FC
0050AC30   C645FF00               mov     byte ptr [ebp-$01], $00
0050AC34   833B00                 cmp     dword ptr [ebx], +$00
0050AC37   7511                   jnz     0050AC4A
0050AC39   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AC3C   8B9020030000           mov     edx, [eax+$0320]
0050AC42   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Forms.TCustomForm.SetActiveControl(TCustomForm;TWinControl);
|
0050AC45   E8D65AFAFF             call    004B0720
0050AC4A   8B45F8                 mov     eax, [ebp-$08]
0050AC4D   8B10                   mov     edx, [eax]

* Reference to method TLoginDialog.ShowModal()
|
0050AC4F   FF92EC000000           call    dword ptr [edx+$00EC]
0050AC55   48                     dec     eax
0050AC56   753A                   jnz     0050AC92
0050AC58   8D55F0                 lea     edx, [ebp-$10]
0050AC5B   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.UserName : TEdit
|
0050AC5E   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0050AC64   E8638AF8FF             call    004936CC
0050AC69   8B55F0                 mov     edx, [ebp-$10]
0050AC6C   8BC3                   mov     eax, ebx

* Reference to: System.@LStrAsg(void;void;void;void);
|
0050AC6E   E87DA8EFFF             call    004054F0
0050AC73   8D55EC                 lea     edx, [ebp-$14]
0050AC76   8B45F8                 mov     eax, [ebp-$08]

* Reference to control TLoginDialog.Password : TEdit
|
0050AC79   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0050AC7F   E8488AF8FF             call    004936CC
0050AC84   8B55EC                 mov     edx, [ebp-$14]
0050AC87   8BC6                   mov     eax, esi

* Reference to: System.@LStrAsg(void;void;void;void);
|
0050AC89   E862A8EFFF             call    004054F0
0050AC8E   C645FF01               mov     byte ptr [ebp-$01], $01
0050AC92   33C0                   xor     eax, eax
0050AC94   5A                     pop     edx
0050AC95   59                     pop     ecx
0050AC96   59                     pop     ecx
0050AC97   648910                 mov     fs:[eax], edx

****** FINALLY
|
0050AC9A   68AFAC5000             push    $0050ACAF
0050AC9F   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.TObject.Free(TObject);
|
0050ACA2   E8F598EFFF             call    0040459C
0050ACA7   C3                     ret


* Reference to: System.@HandleFinally;
|
0050ACA8   E98BA0EFFF             jmp     00404D38
0050ACAD   EBF0                   jmp     0050AC9F

****** END
|
0050ACAF   33C0                   xor     eax, eax
0050ACB1   5A                     pop     edx
0050ACB2   59                     pop     ecx
0050ACB3   59                     pop     ecx
0050ACB4   648910                 mov     fs:[eax], edx

****** FINALLY
|
0050ACB7   68D9AC5000             push    $0050ACD9
0050ACBC   8D45EC                 lea     eax, [ebp-$14]
0050ACBF   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0050ACC4   E8F7A7EFFF             call    004054C0
0050ACC9   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0050ACCC   E8CBA7EFFF             call    0040549C
0050ACD1   C3                     ret


* Reference to: System.@HandleFinally;
|
0050ACD2   E961A0EFFF             jmp     00404D38
0050ACD7   EBE3                   jmp     0050ACBC

****** END
|
0050ACD9   8A45FF                 mov     al, byte ptr [ebp-$01]
0050ACDC   5E                     pop     esi
0050ACDD   5B                     pop     ebx
0050ACDE   8BE5                   mov     esp, ebp
0050ACE0   5D                     pop     ebp
0050ACE1   C3                     ret

*)
end;

procedure TLoginDialog._PROC_0050AD2C(Sender : TObject);
begin
(*
0050AD2C   8B1568B67D00           mov     edx, [$007DB668]
0050AD32   8B12                   mov     edx, [edx]
0050AD34   92                     xchg    eax, edx

* Reference to: Forms.TScreen.SetCursor(TScreen;TCursor);
|
0050AD35   E8F28FFAFF             call    004B3D2C
0050AD3A   C3                     ret

*)
end;

procedure TLoginDialog._PROC_0050AD3C(Sender : TObject);
begin
(*
0050AD3C   55                     push    ebp
0050AD3D   8BEC                   mov     ebp, esp
0050AD3F   33C0                   xor     eax, eax
0050AD41   55                     push    ebp
0050AD42   6861AD5000             push    $0050AD61

***** TRY
|
0050AD47   64FF30                 push    dword ptr fs:[eax]
0050AD4A   648920                 mov     fs:[eax], esp
0050AD4D   FF0518CD7D00           inc     dword ptr [$007DCD18]
0050AD53   33C0                   xor     eax, eax
0050AD55   5A                     pop     edx
0050AD56   59                     pop     ecx
0050AD57   59                     pop     ecx
0050AD58   648910                 mov     fs:[eax], edx

****** FINALLY
|
0050AD5B   6868AD5000             push    $0050AD68
0050AD60   C3                     ret


* Reference to: System.@HandleFinally;
|
0050AD61   E9D29FEFFF             jmp     00404D38
0050AD66   EBF8                   jmp     0050AD60

****** END
|
0050AD68   5D                     pop     ebp
0050AD69   C3                     ret

*)
end;

procedure TLoginDialog._PROC_0050AD6C(Sender : TObject);
begin
(*
0050AD6C   832D18CD7D0001         sub     dword ptr [$007DCD18], +$01
0050AD73   734A                   jnb     0050ADBF
0050AD75   A148A07D00             mov     eax, dword ptr [$007DA048]
0050AD7A   833800                 cmp     dword ptr [eax], +$00
0050AD7D   750B                   jnz     0050AD8A
0050AD7F   A148A07D00             mov     eax, dword ptr [$007DA048]

* Possible String Reference to: 'U‹ìƒÄðSVW3Û‰]ð‰]ô‹ù‹Ú‹ð3ÀUhà©P'
|
0050AD84   C700DCA85000           mov     dword ptr [eax], $0050A8DC
0050AD8A   A1D8A57D00             mov     eax, dword ptr [$007DA5D8]
0050AD8F   833800                 cmp     dword ptr [eax], +$00
0050AD92   750B                   jnz     0050AD9F
0050AD94   A1D8A57D00             mov     eax, dword ptr [$007DA5D8]
0050AD99   C700F4A95000           mov     dword ptr [eax], $0050A9F4
0050AD9F   A118A17D00             mov     eax, dword ptr [$007DA118]
0050ADA4   833800                 cmp     dword ptr [eax], +$00
0050ADA7   750B                   jnz     0050ADB4
0050ADA9   A118A17D00             mov     eax, dword ptr [$007DA118]

* Possible String Reference to: 'U‹ì3ÉQQQQQSV‹ò‹Ø3ÀUhÒ¬P'
|
0050ADAE   C70024AB5000           mov     dword ptr [eax], $0050AB24
0050ADB4   A110A57D00             mov     eax, dword ptr [$007DA510]
0050ADB9   C7002CAD5000           mov     dword ptr [eax], $0050AD2C
0050ADBF   C3                     ret

*)
end;

procedure TLoginDialog._PROC_0050ADC0(Sender : TObject);
begin
(*
0050ADC0   0CAE                   or      al, $AE
0050ADC2   50                     push    eax
0050ADC3   0000                   add     [eax], al

*)
end;

end.