unit deffunc;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, JvExControls, JvComponent,
  JvEditorCommon, JvEditor, JvHLEditor, DBCtrls, Mask, JvExMask,
  JvToolEdit, JvDBControls, ExtCtrls, Buttons, JvLabel;
  
type
  TFrmDefFuncoes=class(TForm)
    DBStatusLabel1: TJvDBStatusLabel;
    DBText1: TDBText;
    Label1: TLabel;
    Panel1: TPanel;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbFecha: TSpeedButton;
    DBNavigator1: TDBNavigator;
    Label2: TLabel;
    SpeedButton1: TSpeedButton;
    pnlResult: TPanel;
    pnlTime: TPanel;
    Label3: TLabel;
    meDescricao: TDBMemo;
    Label5: TLabel;
    EdTela: TJvDBComboEdit;
    sbReplica: TSpeedButton;
    EdCodFuncao: TJvDBComboEdit;
    EdNomeFuncao: TDBEdit;
    SpeedButton7: TSpeedButton;
    meFuncao: TJvHLEditor;
    procedure sbFechaClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure DBNavigator1Click(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure EdNomeFuncaoButtonClick(Sender : TObject);
    procedure EdTelaButtonClick(Sender : TObject);
    procedure meFuncaoKeyPress(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure sbReplicaClick(Sender : TObject);
    procedure EdCodFuncaoButtonClick(Sender : TObject);
    procedure SpeedButton7Click(Sender : TObject);
    procedure _PROC_0068C735(Sender : TObject);
    procedure _PROC_0068C7C9(Sender : TObject);
    procedure _PROC_0068C7DA(Sender : TObject);
    procedure _PROC_0068C883(Sender : TObject);
    procedure _PROC_0068C9D2(Sender : TObject);
    procedure _PROC_0068C9ED(Sender : TObject);
    procedure _PROC_0068CA1C(Sender : TObject);
    procedure _PROC_0068CA24(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmDefFuncoes: TFrmDefFuncoes;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmDefFuncoes.sbFechaClick(Sender : TObject);
begin
(*
0068C288   55                     push    ebp
0068C289   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
0068C28B   E8305EE2FF             call    004B20C0
0068C290   5D                     pop     ebp
0068C291   C3                     ret

*)
end;

procedure TFrmDefFuncoes.sbAdicionaClick(Sender : TObject);
begin
(*
0068C294   55                     push    ebp
0068C295   8BEC                   mov     ebp, esp
0068C297   53                     push    ebx
0068C298   56                     push    esi
0068C299   8BF0                   mov     esi, eax
0068C29B   8BC6                   mov     eax, esi

|
0068C29D   E892040000             call    0068C734
0068C2A2   8BD8                   mov     ebx, eax
0068C2A4   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C2A9   8B00                   mov     eax, [eax]
0068C2AB   8B4058                 mov     eax, [eax+$58]

|
0068C2AE   E8F1A91100             call    007A6CA4
0068C2B3   84C0                   test    al, al
0068C2B5   7460                   jz      0068C317

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C2B7   8B864C030000           mov     eax, [esi+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C2BD   E842E9EAFF             call    0053AC04
0068C2C2   8B10                   mov     edx, [eax]

* Reference to method TDBEdit.GetClientRect()
|
0068C2C4   FF5244                 call    dword ptr [edx+$44]
0068C2C7   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C2CC   8B00                   mov     eax, [eax]
0068C2CE   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CodFuncao'
|
0068C2D1   BA24C36800             mov     edx, $0068C324

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C2D6   E829D9E5FF             call    004E9C04
0068C2DB   8BD3                   mov     edx, ebx
0068C2DD   8B08                   mov     ecx, [eax]
0068C2DF   FF91A8000000           call    dword ptr [ecx+$00A8]
0068C2E5   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C2EA   8B00                   mov     eax, [eax]
0068C2EC   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Tela'
|
0068C2EF   BA38C36800             mov     edx, $0068C338

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C2F4   E80BD9E5FF             call    004E9C04
0068C2F9   8B15D8A97D00           mov     edx, [$007DA9D8]
0068C2FF   8B12                   mov     edx, [edx]
0068C301   8B08                   mov     ecx, [eax]
0068C303   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TFrmDefFuncoes.EdNomeFuncao : TDBEdit
|
0068C309   8B8644030000           mov     eax, [esi+$0344]
0068C30F   8B10                   mov     edx, [eax]

* Reference to method TDBEdit.SetFocus()
|
0068C311   FF92C4000000           call    dword ptr [edx+$00C4]
0068C317   5E                     pop     esi
0068C318   5B                     pop     ebx
0068C319   5D                     pop     ebp
0068C31A   C3                     ret

*)
end;

procedure TFrmDefFuncoes.sbGravaClick(Sender : TObject);
begin
(*
0068C340   55                     push    ebp
0068C341   8BEC                   mov     ebp, esp
0068C343   6A00                   push    $00
0068C345   6A00                   push    $00
0068C347   6A00                   push    $00
0068C349   53                     push    ebx
0068C34A   8BD8                   mov     ebx, eax
0068C34C   33C0                   xor     eax, eax
0068C34E   55                     push    ebp
0068C34F   680CC46800             push    $0068C40C

***** TRY
|
0068C354   64FF30                 push    dword ptr fs:[eax]
0068C357   648920                 mov     fs:[eax], esp
0068C35A   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C35F   8B00                   mov     eax, [eax]
0068C361   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0068C364   E8CFF0E5FF             call    004EB438
0068C369   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TFrmDefFuncoes.meDescricao : TDBMemo
|
0068C36C   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068C372   E85573E0FF             call    004936CC
0068C377   8B45F8                 mov     eax, [ebp-$08]
0068C37A   8D55FC                 lea     edx, [ebp-$04]

* Reference to: SysUtils.AnsiUpperCase(AnsiString):AnsiString;
|
0068C37D   E8E6E2D7FF             call    0040A668
0068C382   8B45FC                 mov     eax, [ebp-$04]
0068C385   50                     push    eax
0068C386   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C38B   8B00                   mov     eax, [eax]
0068C38D   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Descricao'
|
0068C390   BA20C46800             mov     edx, $0068C420

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C395   E86AD8E5FF             call    004E9C04
0068C39A   5A                     pop     edx
0068C39B   8B08                   mov     ecx, [eax]
0068C39D   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C3A3   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C3A9   E856E8EAFF             call    0053AC04
0068C3AE   8D55F4                 lea     edx, [ebp-$0C]
0068C3B1   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.UpdateRegistry(Boolean,string,string)
|
0068C3B3   FF511C                 call    dword ptr [ecx+$1C]
0068C3B6   8B45F4                 mov     eax, [ebp-$0C]
0068C3B9   50                     push    eax
0068C3BA   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C3BF   8B00                   mov     eax, [eax]
0068C3C1   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C3C4   BA34C46800             mov     edx, $0068C434

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C3C9   E836D8E5FF             call    004E9C04
0068C3CE   5A                     pop     edx
0068C3CF   8B08                   mov     ecx, [eax]
0068C3D1   FF91B0000000           call    dword ptr [ecx+$00B0]
0068C3D7   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C3DC   8B00                   mov     eax, [eax]
0068C3DE   8B4058                 mov     eax, [eax+$58]

|
0068C3E1   E87AAB1100             call    007A6F60
0068C3E6   33C0                   xor     eax, eax
0068C3E8   5A                     pop     edx
0068C3E9   59                     pop     ecx
0068C3EA   59                     pop     ecx
0068C3EB   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068C3EE   6813C46800             push    $0068C413
0068C3F3   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.@LStrClr(void;void);
|
0068C3F6   E8A190D7FF             call    0040549C
0068C3FB   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0068C3FE   E89990D7FF             call    0040549C
0068C403   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068C406   E89190D7FF             call    0040549C
0068C40B   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C40C   E92789D7FF             jmp     00404D38
0068C411   EBE0                   jmp     0068C3F3

****** END
|
0068C413   5B                     pop     ebx
0068C414   8BE5                   mov     esp, ebp
0068C416   5D                     pop     ebp
0068C417   C3                     ret

*)
end;

procedure TFrmDefFuncoes.sbApagaClick(Sender : TObject);
begin
(*
0068C43C   55                     push    ebp
0068C43D   8BEC                   mov     ebp, esp
0068C43F   6A00                   push    $00
0068C441   53                     push    ebx
0068C442   8BD8                   mov     ebx, eax
0068C444   33C0                   xor     eax, eax
0068C446   55                     push    ebp

* Possible String Reference to: 'é‰ˆ×ÿëð[Y]Ã'
|
0068C447   68AAC46800             push    $0068C4AA

***** TRY
|
0068C44C   64FF30                 push    dword ptr fs:[eax]
0068C44F   648920                 mov     fs:[eax], esp
0068C452   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C457   8B00                   mov     eax, [eax]
0068C459   8B4058                 mov     eax, [eax+$58]
0068C45C   B201                   mov     dl, $01

|
0068C45E   E8F5AD1100             call    007A7258
0068C463   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C468   8B00                   mov     eax, [eax]
0068C46A   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C46D   BAC0C46800             mov     edx, $0068C4C0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C472   E88DD7E5FF             call    004E9C04
0068C477   8D55FC                 lea     edx, [ebp-$04]
0068C47A   8B08                   mov     ecx, [eax]
0068C47C   FF5160                 call    dword ptr [ecx+$60]
0068C47F   8B45FC                 mov     eax, [ebp-$04]
0068C482   50                     push    eax

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C483   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C489   E876E7EAFF             call    0053AC04
0068C48E   5A                     pop     edx
0068C48F   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.Create(TComponent)
|
0068C491   FF512C                 call    dword ptr [ecx+$2C]
0068C494   33C0                   xor     eax, eax
0068C496   5A                     pop     edx
0068C497   59                     pop     ecx
0068C498   59                     pop     ecx
0068C499   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]Ã'
|
0068C49C   68B1C46800             push    $0068C4B1
0068C4A1   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068C4A4   E8F38FD7FF             call    0040549C
0068C4A9   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C4AA   E98988D7FF             jmp     00404D38
0068C4AF   EBF0                   jmp     0068C4A1

****** END
|
0068C4B1   5B                     pop     ebx
0068C4B2   59                     pop     ecx
0068C4B3   5D                     pop     ebp
0068C4B4   C3                     ret

*)
end;

procedure TFrmDefFuncoes.FormShow(Sender : TObject);
begin
(*
0068C4C8   55                     push    ebp
0068C4C9   8BEC                   mov     ebp, esp
0068C4CB   6A00                   push    $00
0068C4CD   53                     push    ebx
0068C4CE   8BD8                   mov     ebx, eax
0068C4D0   33C0                   xor     eax, eax
0068C4D2   55                     push    ebp
0068C4D3   6825C56800             push    $0068C525

***** TRY
|
0068C4D8   64FF30                 push    dword ptr fs:[eax]
0068C4DB   648920                 mov     fs:[eax], esp
0068C4DE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C4E3   8B00                   mov     eax, [eax]
0068C4E5   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C4E8   BA38C56800             mov     edx, $0068C538

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C4ED   E812D7E5FF             call    004E9C04
0068C4F2   8D55FC                 lea     edx, [ebp-$04]
0068C4F5   8B08                   mov     ecx, [eax]
0068C4F7   FF5160                 call    dword ptr [ecx+$60]
0068C4FA   8B45FC                 mov     eax, [ebp-$04]
0068C4FD   50                     push    eax

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C4FE   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C504   E8FBE6EAFF             call    0053AC04
0068C509   5A                     pop     edx
0068C50A   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.Create(TComponent)
|
0068C50C   FF512C                 call    dword ptr [ecx+$2C]
0068C50F   33C0                   xor     eax, eax
0068C511   5A                     pop     edx
0068C512   59                     pop     ecx
0068C513   59                     pop     ecx
0068C514   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068C517   682CC56800             push    $0068C52C
0068C51C   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068C51F   E8788FD7FF             call    0040549C
0068C524   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C525   E90E88D7FF             jmp     00404D38
0068C52A   EBF0                   jmp     0068C51C

****** END
|
0068C52C   5B                     pop     ebx
0068C52D   59                     pop     ecx
0068C52E   5D                     pop     ebp
0068C52F   C3                     ret

*)
end;

procedure TFrmDefFuncoes.DBNavigator1Click(Sender : TObject);
begin
(*
0068C540   55                     push    ebp
0068C541   8BEC                   mov     ebp, esp
0068C543   6A00                   push    $00
0068C545   53                     push    ebx
0068C546   8BD8                   mov     ebx, eax
0068C548   33C0                   xor     eax, eax
0068C54A   55                     push    ebp
0068C54B   689DC56800             push    $0068C59D

***** TRY
|
0068C550   64FF30                 push    dword ptr fs:[eax]
0068C553   648920                 mov     fs:[eax], esp
0068C556   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C55B   8B00                   mov     eax, [eax]
0068C55D   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C560   BAB0C56800             mov     edx, $0068C5B0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C565   E89AD6E5FF             call    004E9C04
0068C56A   8D55FC                 lea     edx, [ebp-$04]
0068C56D   8B08                   mov     ecx, [eax]
0068C56F   FF5160                 call    dword ptr [ecx+$60]
0068C572   8B45FC                 mov     eax, [ebp-$04]
0068C575   50                     push    eax

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C576   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C57C   E883E6EAFF             call    0053AC04
0068C581   5A                     pop     edx
0068C582   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.Create(TComponent)
|
0068C584   FF512C                 call    dword ptr [ecx+$2C]
0068C587   33C0                   xor     eax, eax
0068C589   5A                     pop     edx
0068C58A   59                     pop     ecx
0068C58B   59                     pop     ecx
0068C58C   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068C58F   68A4C56800             push    $0068C5A4
0068C594   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068C597   E8008FD7FF             call    0040549C
0068C59C   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C59D   E99687D7FF             jmp     00404D38
0068C5A2   EBF0                   jmp     0068C594

****** END
|
0068C5A4   5B                     pop     ebx
0068C5A5   59                     pop     ecx
0068C5A6   5D                     pop     ebp
0068C5A7   C3                     ret

*)
end;

procedure TFrmDefFuncoes.SpeedButton1Click(Sender : TObject);
begin
(*
0068C5B8   55                     push    ebp
0068C5B9   8BEC                   mov     ebp, esp

* Reference to control TFrmDefFuncoes.pnlTime : TPanel
|
0068C5BB   8D9028030000           lea     edx, [eax+$0328]
0068C5C1   52                     push    edx

* Reference to control TFrmDefFuncoes.pnlResult : TPanel
|
0068C5C2   8D8824030000           lea     ecx, [eax+$0324]

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C5C8   8D904C030000           lea     edx, [eax+$034C]
0068C5CE   A178B47D00             mov     eax, dword ptr [$007DB478]
0068C5D3   8B00                   mov     eax, [eax]

|
0068C5D5   E8621F1300             call    007BE53C
0068C5DA   5D                     pop     ebp
0068C5DB   C3                     ret

*)
end;

procedure TFrmDefFuncoes.EdNomeFuncaoButtonClick(Sender : TObject);
begin
(*
0068C5DC   55                     push    ebp
0068C5DD   8BEC                   mov     ebp, esp
0068C5DF   33C9                   xor     ecx, ecx
0068C5E1   51                     push    ecx
0068C5E2   51                     push    ecx
0068C5E3   51                     push    ecx
0068C5E4   51                     push    ecx
0068C5E5   51                     push    ecx
0068C5E6   51                     push    ecx
0068C5E7   53                     push    ebx
0068C5E8   56                     push    esi
0068C5E9   8BD8                   mov     ebx, eax
0068C5EB   33C0                   xor     eax, eax
0068C5ED   55                     push    ebp

* Possible String Reference to: 'é5†×ÿëã^[‹å]Ã'
|
0068C5EE   68FEC66800             push    $0068C6FE

***** TRY
|
0068C5F3   64FF30                 push    dword ptr fs:[eax]
0068C5F6   648920                 mov     fs:[eax], esp
0068C5F9   A108A97D00             mov     eax, dword ptr [$007DA908]
0068C5FE   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A2474()
|
0068C600   E86F5E1100             call    007A2474
0068C605   84C0                   test    al, al
0068C607   0F85CE000000           jnz     0068C6DB
0068C60D   A14CB27D00             mov     eax, dword ptr [$007DB24C]
0068C612   C60000                 mov     byte ptr [eax], $00
0068C615   8BCB                   mov     ecx, ebx
0068C617   B201                   mov     dl, $01

* Reference to class TFrmF2Funcoes
|
0068C619   A1D0E36800             mov     eax, dword ptr [$0068E3D0]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0068C61E   E8ED18E2FF             call    004ADF10
0068C623   8B1508A97D00           mov     edx, [$007DA908]
0068C629   8902                   mov     [edx], eax
0068C62B   A108A97D00             mov     eax, dword ptr [$007DA908]
0068C630   8B00                   mov     eax, [eax]
0068C632   8B10                   mov     edx, [eax]
0068C634   FF92EC000000           call    dword ptr [edx+$00EC]
0068C63A   48                     dec     eax
0068C63B   0F8586000000           jnz     0068C6C7
0068C641   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C646   8B00                   mov     eax, [eax]
0068C648   8B4058                 mov     eax, [eax+$58]

* Reference to : TFrmInfoAtu._PROC_007A66A4()
|
0068C64B   E854A01100             call    007A66A4
0068C650   A00CC76800             mov     al, byte ptr [$0068C70C]
0068C655   50                     push    eax
0068C656   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C65B   8B00                   mov     eax, [eax]
0068C65D   8B7058                 mov     esi, [eax+$58]
0068C660   8BC6                   mov     eax, esi

* Possible String Reference to: 'CodFuncao'
|
0068C662   BA18C76800             mov     edx, $0068C718

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C667   E898D5E5FF             call    004E9C04
0068C66C   8D55EC                 lea     edx, [ebp-$14]
0068C66F   8B08                   mov     ecx, [eax]
0068C671   FF5160                 call    dword ptr [ecx+$60]
0068C674   8B55EC                 mov     edx, [ebp-$14]
0068C677   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068C67A   E845C6D8FF             call    00418CC4
0068C67F   8D4DF0                 lea     ecx, [ebp-$10]
0068C682   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C687   8BC6                   mov     eax, esi

* Possible String Reference to: 'CodFuncao'
|
0068C689   BA18C76800             mov     edx, $0068C718
0068C68E   8B30                   mov     esi, [eax]
0068C690   FF9644020000           call    dword ptr [esi+$0244]
0068C696   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C69B   8B00                   mov     eax, [eax]
0068C69D   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C6A0   BA2CC76800             mov     edx, $0068C72C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C6A5   E85AD5E5FF             call    004E9C04
0068C6AA   8D55E8                 lea     edx, [ebp-$18]
0068C6AD   8B08                   mov     ecx, [eax]
0068C6AF   FF5160                 call    dword ptr [ecx+$60]
0068C6B2   8B45E8                 mov     eax, [ebp-$18]
0068C6B5   50                     push    eax

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C6B6   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C6BC   E843E5EAFF             call    0053AC04
0068C6C1   5A                     pop     edx
0068C6C2   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.Create(TComponent)
|
0068C6C4   FF512C                 call    dword ptr [ecx+$2C]
0068C6C7   A108A97D00             mov     eax, dword ptr [$007DA908]
0068C6CC   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0068C6CE   E8C97ED7FF             call    0040459C
0068C6D3   A14CB27D00             mov     eax, dword ptr [$007DB24C]
0068C6D8   C60001                 mov     byte ptr [eax], $01
0068C6DB   33C0                   xor     eax, eax
0068C6DD   5A                     pop     edx
0068C6DE   59                     pop     ecx
0068C6DF   59                     pop     ecx
0068C6E0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0068C6E3   6805C76800             push    $0068C705
0068C6E8   8D45E8                 lea     eax, [ebp-$18]
0068C6EB   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068C6F0   E8CB8DD7FF             call    004054C0
0068C6F5   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068C6F8   E87B7ED8FF             call    00414578
0068C6FD   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C6FE   E93586D7FF             jmp     00404D38
0068C703   EBE3                   jmp     0068C6E8

****** END
|
0068C705   5E                     pop     esi
0068C706   5B                     pop     ebx
0068C707   8BE5                   mov     esp, ebp
0068C709   5D                     pop     ebp
0068C70A   C3                     ret

*)
end;

procedure TFrmDefFuncoes.EdTelaButtonClick(Sender : TObject);
begin
(*
0068C7E0   55                     push    ebp
0068C7E1   8BEC                   mov     ebp, esp
0068C7E3   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C7E8   8B00                   mov     eax, [eax]
0068C7EA   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0068C7ED   E846ECE5FF             call    004EB438
0068C7F2   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C7F7   8B00                   mov     eax, [eax]
0068C7F9   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Tela'
|
0068C7FC   BA20C86800             mov     edx, $0068C820

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C801   E8FED3E5FF             call    004E9C04
0068C806   8B15D8A97D00           mov     edx, [$007DA9D8]
0068C80C   8B12                   mov     edx, [edx]
0068C80E   8B08                   mov     ecx, [eax]
0068C810   FF91B0000000           call    dword ptr [ecx+$00B0]
0068C816   5D                     pop     ebp
0068C817   C3                     ret

*)
end;

procedure TFrmDefFuncoes.meFuncaoKeyPress(Sender : TObject);
begin
(*
0068C828   55                     push    ebp
0068C829   8BEC                   mov     ebp, esp
0068C82B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C830   8B00                   mov     eax, [eax]
0068C832   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0068C835   E8FEEBE5FF             call    004EB438
0068C83A   5D                     pop     ebp
0068C83B   C3                     ret

*)
end;

procedure TFrmDefFuncoes.FormCloseQuery(Sender : TObject);
begin
(*
0068C83C   55                     push    ebp
0068C83D   8BEC                   mov     ebp, esp
0068C83F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C844   8B00                   mov     eax, [eax]
0068C846   8B4058                 mov     eax, [eax+$58]
0068C849   8A809D000000           mov     al, byte ptr [eax+$009D]
0068C84F   04FE                   add     al, -$02
0068C851   2C02                   sub     al, $02
0068C853   732C                   jnb     0068C881
0068C855   6A00                   push    $00
0068C857   668B0D84C86800         mov     cx, word ptr [$0068C884]
0068C85E   B203                   mov     dl, $03

* Possible String Reference to: 'Deseja salvar alterações?'
|
0068C860   B890C86800             mov     eax, $0068C890

|
0068C865   E8C272DBFF             call    00443B2C
0068C86A   83F806                 cmp     eax, +$06
0068C86D   7512                   jnz     0068C881
0068C86F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C874   8B00                   mov     eax, [eax]
0068C876   8B4058                 mov     eax, [eax+$58]
0068C879   8B10                   mov     edx, [eax]
0068C87B   FF924C020000           call    dword ptr [edx+$024C]
0068C881   5D                     pop     ebp
0068C882   C3                     ret

*)
end;

procedure TFrmDefFuncoes.sbReplicaClick(Sender : TObject);
begin
(*
0068C8AC   C3                     ret

*)
end;

procedure TFrmDefFuncoes.EdCodFuncaoButtonClick(Sender : TObject);
begin
(*
0068C8B0   55                     push    ebp
0068C8B1   8BEC                   mov     ebp, esp
0068C8B3   83C4E4                 add     esp, -$1C
0068C8B6   53                     push    ebx
0068C8B7   33C9                   xor     ecx, ecx
0068C8B9   894DE4                 mov     [ebp-$1C], ecx
0068C8BC   8BD8                   mov     ebx, eax
0068C8BE   33C0                   xor     eax, eax
0068C8C0   55                     push    ebp

* Possible String Reference to: 'éÒƒ×ÿëð[‹å]Ã'
|
0068C8C1   6861C96800             push    $0068C961

***** TRY
|
0068C8C6   64FF30                 push    dword ptr fs:[eax]
0068C8C9   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'Código'
|
0068C8CC   B878C96800             mov     eax, $0068C978
0068C8D1   8945F4                 mov     [ebp-$0C], eax

* Possible String Reference to: 'Macro'
|
0068C8D4   B888C96800             mov     eax, $0068C988
0068C8D9   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Descricao'
|
0068C8DC   B898C96800             mov     eax, $0068C998
0068C8E1   8945FC                 mov     [ebp-$04], eax
0068C8E4   8D45F4                 lea     eax, [ebp-$0C]
0068C8E7   50                     push    eax
0068C8E8   6A02                   push    $02
0068C8EA   6A00                   push    $00

* Possible String Reference to: 'CodFuncao'
|
0068C8EC   B8ACC96800             mov     eax, $0068C9AC
0068C8F1   8945E8                 mov     [ebp-$18], eax

* Possible String Reference to: 'Nome'
|
0068C8F4   B8C0C96800             mov     eax, $0068C9C0
0068C8F9   8945EC                 mov     [ebp-$14], eax

* Possible String Reference to: 'Descricao'
|
0068C8FC   B898C96800             mov     eax, $0068C998
0068C901   8945F0                 mov     [ebp-$10], eax
0068C904   8D55E8                 lea     edx, [ebp-$18]
0068C907   B902000000             mov     ecx, $00000002

* Possible String Reference to: 'FUNCOES'
|
0068C90C   B8D0C96800             mov     eax, $0068C9D0

|
0068C911   E83EC9FAFF             call    00639254
0068C916   84C0                   test    al, al
0068C918   7431                   jz      0068C94B
0068C91A   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C91F   8B00                   mov     eax, [eax]
0068C921   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Funcao'
|
0068C924   BAE0C96800             mov     edx, $0068C9E0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C929   E8D6D2E5FF             call    004E9C04
0068C92E   8D55E4                 lea     edx, [ebp-$1C]
0068C931   8B08                   mov     ecx, [eax]
0068C933   FF5160                 call    dword ptr [ecx+$60]
0068C936   8B45E4                 mov     eax, [ebp-$1C]
0068C939   50                     push    eax

* Reference to control TFrmDefFuncoes.meFuncao : TDBEdit
|
0068C93A   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Mask.TCustomMaskEdit.GetMaxLength(TCustomMaskEdit):Integer;
|
0068C940   E8BFE2EAFF             call    0053AC04
0068C945   5A                     pop     edx
0068C946   8B08                   mov     ecx, [eax]

* Reference to method TDBEdit.Create(TComponent)
|
0068C948   FF512C                 call    dword ptr [ecx+$2C]
0068C94B   33C0                   xor     eax, eax
0068C94D   5A                     pop     edx
0068C94E   59                     pop     ecx
0068C94F   59                     pop     ecx
0068C950   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0068C953   6868C96800             push    $0068C968
0068C958   8D45E4                 lea     eax, [ebp-$1C]

* Reference to: System.@LStrClr(void;void);
|
0068C95B   E83C8BD7FF             call    0040549C
0068C960   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C961   E9D283D7FF             jmp     00404D38
0068C966   EBF0                   jmp     0068C958

****** END
|
0068C968   5B                     pop     ebx
0068C969   8BE5                   mov     esp, ebp
0068C96B   5D                     pop     ebp
0068C96C   C3                     ret

*)
end;

procedure TFrmDefFuncoes.SpeedButton7Click(Sender : TObject);
begin
(*
0068C9E8   C3                     ret

*)
end;

procedure TFrmDefFuncoes._PROC_0068C735(Sender : TObject);
begin
(*
0068C735   8BEC                   mov     ebp, esp
0068C737   33C9                   xor     ecx, ecx
0068C739   51                     push    ecx
0068C73A   51                     push    ecx
0068C73B   51                     push    ecx
0068C73C   51                     push    ecx
0068C73D   51                     push    ecx
0068C73E   51                     push    ecx
0068C73F   51                     push    ecx
0068C740   51                     push    ecx
0068C741   53                     push    ebx
0068C742   33C0                   xor     eax, eax
0068C744   55                     push    ebp
0068C745   68AEC76800             push    $0068C7AE

***** TRY
|
0068C74A   64FF30                 push    dword ptr fs:[eax]
0068C74D   648920                 mov     fs:[eax], esp
0068C750   6A00                   push    $00
0068C752   8D45F0                 lea     eax, [ebp-$10]
0068C755   50                     push    eax

* Possible String Reference to: 'CODFUNCAO'
|
0068C756   B9C4C76800             mov     ecx, $0068C7C4

* Possible String Reference to: 'FUNCOES'
|
0068C75B   BAD8C76800             mov     edx, $0068C7D8
0068C760   33C0                   xor     eax, eax

|
0068C762   E88DDE1100             call    007AA5F4
0068C767   8D45F0                 lea     eax, [ebp-$10]
0068C76A   50                     push    eax
0068C76B   8D45E0                 lea     eax, [ebp-$20]
0068C76E   BA01000000             mov     edx, $00000001
0068C773   B101                   mov     cl, $01

|
0068C775   E8F6C2D8FF             call    00418A70
0068C77A   8D55E0                 lea     edx, [ebp-$20]
0068C77D   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
0068C77E   E82109D9FF             call    0041D0A4
0068C783   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Variants.@VarToInteger(TVarData;TVarData):Integer;
|
0068C786   E80D8BD8FF             call    00415298
0068C78B   8BD8                   mov     ebx, eax
0068C78D   33C0                   xor     eax, eax
0068C78F   5A                     pop     edx
0068C790   59                     pop     ecx
0068C791   59                     pop     ecx
0068C792   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068C795   68B5C76800             push    $0068C7B5
0068C79A   8D45E0                 lea     eax, [ebp-$20]

* Reference to object Variant
|
0068C79D   8B1524114000           mov     edx, [$00401124]
0068C7A3   B902000000             mov     ecx, $00000002

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0068C7A8   E8EF98D7FF             call    0040609C
0068C7AD   C3                     ret


* Reference to: System.@HandleFinally;
|
0068C7AE   E98585D7FF             jmp     00404D38
0068C7B3   EBE5                   jmp     0068C79A

****** END
|
0068C7B5   8BC3                   mov     eax, ebx
0068C7B7   5B                     pop     ebx
0068C7B8   8BE5                   mov     esp, ebp
0068C7BA   5D                     pop     ebp
0068C7BB   C3                     ret

*)
end;

procedure TFrmDefFuncoes._PROC_0068C7C9(Sender : TObject);
begin
(*
0068C7C9   4E                     dec     esi
0068C7CA   43                     inc     ebx
0068C7CB   41                     inc     ecx
0068C7CC   4F                     dec     edi
0068C7CD   0000                   add     [eax], al

*)
end;

procedure TFrmDefFuncoes._PROC_0068C7DA(Sender : TObject);
begin
(*
0068C7DA   4E                     dec     esi
0068C7DB   43                     inc     ebx
0068C7DC   4F                     dec     edi
0068C7DD   45                     inc     ebp
0068C7DE   53                     push    ebx
0068C7DF   00558B                 add     [ebp-$75], dl
0068C7E2   EC                     in      al, dx
0068C7E3   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C7E8   8B00                   mov     eax, [eax]
0068C7EA   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0068C7ED   E846ECE5FF             call    004EB438
0068C7F2   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068C7F7   8B00                   mov     eax, [eax]
0068C7F9   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Tela'
|
0068C7FC   BA20C86800             mov     edx, $0068C820

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0068C801   E8FED3E5FF             call    004E9C04
0068C806   8B15D8A97D00           mov     edx, [$007DA9D8]
0068C80C   8B12                   mov     edx, [edx]
0068C80E   8B08                   mov     ecx, [eax]
0068C810   FF91B0000000           call    dword ptr [ecx+$00B0]
0068C816   5D                     pop     ebp
0068C817   C3                     ret

*)
end;

procedure TFrmDefFuncoes._PROC_0068C883(Sender : TObject);
begin
(*
0068C883   0003                   add     [ebx], al
0068C885   0000                   add     [eax], al

*)
end;

procedure TFrmDefFuncoes._PROC_0068C9D2(Sender : TObject);
begin
(*
0068C9D2   4E                     dec     esi
0068C9D3   43                     inc     ebx
0068C9D4   4F                     dec     edi
0068C9D5   45                     inc     ebp
0068C9D6   53                     push    ebx
0068C9D7   00FF                   add     bh, bh
0068C9D9   FFFF                   DB  $FF, $FF  //      
0068C9DB   FF06                   inc     dword ptr [esi]
0068C9DD   0000                   add     [eax], al

*)
end;

procedure TFrmDefFuncoes._PROC_0068C9ED(Sender : TObject);
begin
(*
0068C9ED   8BEC                   mov     ebp, esp
0068C9EF   33C0                   xor     eax, eax
0068C9F1   55                     push    ebp

* Possible String Reference to: 'é"ƒ×ÿëø]Ã‹Àƒ-°ì}'
|
0068C9F2   6811CA6800             push    $0068CA11

***** TRY
|
0068C9F7   64FF30                 push    dword ptr fs:[eax]
0068C9FA   648920                 mov     fs:[eax], esp
0068C9FD   FF05B0EC7D00           inc     dword ptr [$007DECB0]
0068CA03   33C0                   xor     eax, eax
0068CA05   5A                     pop     edx
0068CA06   59                     pop     ecx
0068CA07   59                     pop     ecx
0068CA08   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-°ì}'
|
0068CA0B   6818CA6800             push    $0068CA18
0068CA10   C3                     ret


* Reference to: System.@HandleFinally;
|
0068CA11   E92283D7FF             jmp     00404D38
0068CA16   EBF8                   jmp     0068CA10

****** END
|
0068CA18   5D                     pop     ebp
0068CA19   C3                     ret

*)
end;

procedure TFrmDefFuncoes._PROC_0068CA1C(Sender : TObject);
begin
(*
0068CA1C   832DB0EC7D0001         sub     dword ptr [$007DECB0], +$01
0068CA23   C3                     ret

*)
end;

procedure TFrmDefFuncoes._PROC_0068CA24(Sender : TObject);
begin
(*
0068CA24   28CA                   sub     dl, cl
0068CA26   68000E0874             push    $74080E00
0068CA2B   46                     inc     esi
0068CA2C   756E                   jnz     0068CA9C
0068CA2E   636F65                 arpl    [edi+$65], bp
0068CA31   7310                   jnb     0068CA43
0068CA33   0000                   add     [eax], al

0068CA35   0002                   add     [edx], al
0068CA37   0000                   add     [eax], al

0068CA39   0008                   add     [eax], cl
0068CA3B   114000                 adc     [eax+$00], eax
0068CA3E   0400                   add     al, +$00
0068CA40   0000                   add     [eax], al

0068CA42   0811                   or      [ecx], dl
0068CA44   40                     inc     eax
0068CA45   0008                   add     [eax], cl
0068CA47   0000                   add     [eax], al

0068CA49   008BC050CA68           add     [ebx+$68CA50C0], cl
0068CA4F   0011                   add     [ecx], dl
0068CA51   022E                   add     ch, byte ptr [esi]
0068CA53   3210                   xor     dl, byte ptr [eax]
0068CA55   0000                   add     [eax], al

0068CA57   0024CA                 add     [edx+ecx*8], ah
0068CA5A   6800FFFFFF             push    $FFFFFF00
0068CA5F   FF24CA                 jmp     dword ptr [edx+ecx*8]
0068CA62   6800074675             push    $75460700
0068CA67   6E                     outsb
0068CA68   634578                 arpl    [ebp+$78], ax
0068CA6B   7070                   jo      0068CADD
0068CA6D   CA                     ret     

0068CA6E   680011022E             push    $2E021100
0068CA73   3310                   xor     edx, [eax]
0068CA75   0000                   add     [eax], al

0068CA77   0024CA                 add     [edx+ecx*8], ah
0068CA7A   6800FFFFFF             push    $FFFFFF00
0068CA7F   FF24CA                 jmp     dword ptr [edx+ecx*8]
0068CA82   6800074675             push    $75460700
0068CA87   6E                     outsb
0068CA88   634578                 arpl    [ebp+$78], ax
0068CA8B   7090                   jo      0068CA1D
0068CA8D   CA                     ret     

0068CA8E   680011022E             push    $2E021100
0068CA93   3410                   xor     al, $10
0068CA95   0000                   add     [eax], al

0068CA97   0024CA                 add     [edx+ecx*8], ah
0068CA9A   6800FFFFFF             push    $FFFFFF00
0068CA9F   FF24CA                 jmp     dword ptr [edx+ecx*8]
0068CAA2   6800074675             push    $75460700
0068CAA7   6E                     outsb
0068CAA8   634578                 arpl    [ebp+$78], ax
0068CAAB   70F8                   jo      0068CAA5
0068CAAD   CA                     ret     

0068CAAE   6800000000             push    $00000000
0068CAB3   0000                   add     [eax], al

0068CAB5   0000                   add     [eax], al

0068CAB7   00EC                   add     ah, ch
0068CAB9   CB                     ret

0068CABA   680024CE68             push    $68CE2400
0068CABF   000E                   add     [esi], cl
0068CAC1   CC                     int     3
0068CAC2   68001CCD68             push    $68CD1C00
0068CAC7   0000                   add     [eax], al

0068CAC9   0000                   add     [eax], al

0068CACB   00E5                   add     ch, ah
0068CACD   CD68                   int     $68
0068CACF   004C0300               add     [ebx+eax+$00], cl
0068CAD3   00F0                   add     al, dh
0068CAD5   B24A                   mov     dl, $4A
0068CAD7   00E8                   add     al, ch
0068CAD9   E442                   in      al, $42
0068CADB   009CE04A0050E2         add     [eax+$E250004A], bl
0068CAE2   4A                     dec     edx
0068CAE3   0000                   add     [eax], al

*)
end;

end.