unit DefRel;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, PBPrinterSetupDialog, ExtDlgs,
  DBCtrls, ExtCtrls, JvExStdCtrls, JvDBCombobox, JvExMask, JvToolEdit,
  JvDBControls, JvExControls, JvComponent, JvEditorCommon, JvEditor,
  JvHLEditor, ComCtrls, Buttons, Mask;
  
type
  TFrmDefRelatorio=class(TForm)
    Panel1: TPanel;
    Label1: TLabel;
    Panel2: TPanel;
    sbFecha: TSpeedButton;
    EdDescrRelatorio: TDBEdit;
    nbBotoes: TNotebook;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    SpeedButton3: TSpeedButton;
    EdCodigo: TDBEdit;
    Label2: TLabel;
    Label3: TLabel;
    EdTela: TDBEdit;
    SpeedButton5: TSpeedButton;
    SpeedButton6: TSpeedButton;
    sdDefRelatorio: TSaveDialog;
    odDefRelatorio: TOpenDialog;
    SpeedButton4: TSpeedButton;
    sbGrava: TSpeedButton;
    pgDefinicao: TPageControl;
    tbDefinicao: TTabSheet;
    meDefForm: TJvHLEditor;
    tbOpcoes: TTabSheet;
    Label4: TLabel;
    Label5: TLabel;
    EdDesenho: TJvDBComboEdit;
    opDesenho: TOpenPictureDialog;
    Label6: TLabel;
    cbTipoRelatorio: TJvDBComboBox;
    Label7: TLabel;
    EdNumLinhas: TDBEdit;
    PrintSetup: TPBPrinterSetupDialog;
    EdImpressora: TJvDBComboEdit;
    rgSaidaPadrao: TDBRadioGroup;
    Label8: TLabel;
    cbTipoPapel: TJvDBComboBox;
    GrDirecao: TDBRadioGroup;
    Label9: TLabel;
    Label10: TLabel;
    EdAltura: TDBEdit;
    EdLargura: TDBEdit;
    Bevel1: TBevel;
    Bevel2: TBevel;
    Label11: TLabel;
    EdCodImpressora: TJvDBComboEdit;
    EdMatricial: TEdit;
    rgQuebra: TDBRadioGroup;
    EdTamPagDOS: TDBEdit;
    Label12: TLabel;
    sbGravar: TSpeedButton;
    nbEtiquetas: TNotebook;
    Label13: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    Label16: TLabel;
    Label17: TLabel;
    Label18: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    Label21: TLabel;
    EdMargemSuperior: TDBEdit;
    EdMargemLateral: TDBEdit;
    EdDistaciaVertical: TDBEdit;
    EdDistaciaHorizontal: TDBEdit;
    EdAlturaEtiqueta: TDBEdit;
    EdLarguraEtiqueta: TDBEdit;
    EdEtiquetasPorLinha: TDBEdit;
    EdLinhasPorPagina: TDBEdit;
    SpeedButton7: TSpeedButton;
    ckVias: TDBCheckBox;
    procedure sbFechaClick(Sender : TObject);
    procedure SpeedButton4Click(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure DBNavigator1Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure SpeedButton2Click(Sender : TObject);
    procedure SpeedButton3Click(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure SpeedButton5Click(Sender : TObject);
    procedure SpeedButton6Click(Sender : TObject);
    procedure EdDesenhoButtonClick(Sender : TObject);
    procedure EdImpressoraButtonClick(Sender : TObject);
    procedure EdCodImpressoraChange(Sender : TObject);
    procedure EdCodImpressoraButtonClick(Sender : TObject);
    procedure sbGravarClick(Sender : TObject);
    procedure cbTipoRelatorioChange(Sender : TObject);
    procedure SpeedButton7Click(Sender : TObject);
    procedure GrDirecaoExit(Sender : TObject);
    procedure EdCodImpressoraExit(Sender : TObject);
    procedure _PROC_0072B3B6(Sender : TObject);
    procedure _PROC_0072B60C(Sender : TObject);
    procedure _PROC_0072B918(Sender : TObject);
    procedure _PROC_0072B930(Sender : TObject);
    procedure _PROC_0072BC98(Sender : TObject);
    procedure _PROC_0072BCC8(Sender : TObject);
    procedure _PROC_0072BCD0(Sender : TObject);
    procedure _PROC_0072BE13(Sender : TObject);
    procedure _PROC_0072BF7D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmDefRelatorio: TFrmDefRelatorio;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmDefRelatorio.sbFechaClick(Sender : TObject);
begin
(*
0072AF80   55                     push    ebp
0072AF81   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
0072AF83   E83871D8FF             call    004B20C0
0072AF88   5D                     pop     ebp
0072AF89   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton4Click(Sender : TObject);
begin
(*
0072AF8C   55                     push    ebp
0072AF8D   8BEC                   mov     ebp, esp
0072AF8F   53                     push    ebx
0072AF90   8BD8                   mov     ebx, eax
0072AF92   6A00                   push    $00
0072AF94   668B0D00B07200         mov     cx, word ptr [$0072B000]
0072AF9B   B203                   mov     dl, $03

* Possible String Reference to: 'Tem certeza que deseja limpar as de
|                                finiÁıes de formul·rio?'
|
0072AF9D   B80CB07200             mov     eax, $0072B00C

|
0072AFA2   E8858BD1FF             call    00443B2C
0072AFA7   83F806                 cmp     eax, +$06
0072AFAA   754F                   jnz     0072AFFB

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072AFAC   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072AFB2   E84DFCE0FF             call    0053AC04
0072AFB7   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_44
|
0072AFB9   FF5244                 call    dword ptr [edx+$44]
0072AFBC   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072AFC1   8B00                   mov     eax, [eax]
0072AFC3   8B4074                 mov     eax, [eax+$74]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0072AFC6   E86D04DCFF             call    004EB438
0072AFCB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072AFD0   8B00                   mov     eax, [eax]
0072AFD2   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Definicao'
|
0072AFD5   BA50B07200             mov     edx, $0072B050

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072AFDA   E825ECDBFF             call    004E9C04
0072AFDF   33D2                   xor     edx, edx
0072AFE1   8B08                   mov     ecx, [eax]
0072AFE3   FF91B0000000           call    dword ptr [ecx+$00B0]
0072AFE9   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072AFEE   8B00                   mov     eax, [eax]
0072AFF0   8B4074                 mov     eax, [eax+$74]
0072AFF3   8B10                   mov     edx, [eax]
0072AFF5   FF924C020000           call    dword ptr [edx+$024C]
0072AFFB   5B                     pop     ebx
0072AFFC   5D                     pop     ebp
0072AFFD   C3                     ret

*)
end;

procedure TFrmDefRelatorio.sbGravaClick(Sender : TObject);
begin
(*
0072B05C   55                     push    ebp
0072B05D   8BEC                   mov     ebp, esp
0072B05F   6A00                   push    $00
0072B061   6A00                   push    $00
0072B063   56                     push    esi
0072B064   8BF0                   mov     esi, eax
0072B066   33C0                   xor     eax, eax
0072B068   55                     push    ebp
0072B069   6824B17200             push    $0072B124

***** TRY
|
0072B06E   64FF30                 push    dword ptr fs:[eax]
0072B071   648920                 mov     fs:[eax], esp
0072B074   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.EdDescrRelatorio : TDBEdit
|
0072B077   8B8608030000           mov     eax, [esi+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072B07D   E8BA2EDDFF             call    004FDF3C
0072B082   837DFC00               cmp     dword ptr [ebp-$04], +$00
0072B086   7466                   jz      0072B0EE
0072B088   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B08D   8B00                   mov     eax, [eax]
0072B08F   8B4074                 mov     eax, [eax+$74]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0072B092   E8A103DCFF             call    004EB438

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B097   8B864C030000           mov     eax, [esi+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B09D   E862FBE0FF             call    0053AC04
0072B0A2   8D55F8                 lea     edx, [ebp-$08]
0072B0A5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_1C
|
0072B0A7   FF511C                 call    dword ptr [ecx+$1C]
0072B0AA   8B45F8                 mov     eax, [ebp-$08]
0072B0AD   50                     push    eax
0072B0AE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B0B3   8B00                   mov     eax, [eax]
0072B0B5   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Definicao'
|
0072B0B8   BA38B17200             mov     edx, $0072B138

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B0BD   E842EBDBFF             call    004E9C04
0072B0C2   5A                     pop     edx
0072B0C3   8B08                   mov     ecx, [eax]
0072B0C5   FF91B0000000           call    dword ptr [ecx+$00B0]
0072B0CB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B0D0   8B00                   mov     eax, [eax]
0072B0D2   8B80C8000000           mov     eax, [eax+$00C8]

|
0072B0D8   E883BE0700             call    007A6F60
0072B0DD   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B0E2   8B00                   mov     eax, [eax]
0072B0E4   8B4074                 mov     eax, [eax+$74]

|
0072B0E7   E874BE0700             call    007A6F60
0072B0EC   EB18                   jmp     0072B106

* Possible String Reference to: 'Informe a DescriÁ„o!'
|
0072B0EE   B84CB17200             mov     eax, $0072B14C

* Reference to: Dialogs.ShowMessage(AnsiString);
|
0072B0F3   E82C8BD1FF             call    00443C24

* Reference to control TFrmDefRelatorio.EdDescrRelatorio : TDBEdit
|
0072B0F8   8B8608030000           mov     eax, [esi+$0308]
0072B0FE   8B10                   mov     edx, [eax]

* Reference to method TDBEdit.SetFocus()
|
0072B100   FF92C4000000           call    dword ptr [edx+$00C4]
0072B106   33C0                   xor     eax, eax
0072B108   5A                     pop     edx
0072B109   59                     pop     ecx
0072B10A   59                     pop     ecx
0072B10B   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B10E   682BB17200             push    $0072B12B
0072B113   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0072B116   E881A3CDFF             call    0040549C
0072B11B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B11E   E879A3CDFF             call    0040549C
0072B123   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B124   E90F9CCDFF             jmp     00404D38
0072B129   EBE8                   jmp     0072B113

****** END
|
0072B12B   5E                     pop     esi
0072B12C   59                     pop     ecx
0072B12D   59                     pop     ecx
0072B12E   5D                     pop     ebp
0072B12F   C3                     ret

*)
end;

procedure TFrmDefRelatorio.sbAdicionaClick(Sender : TObject);
begin
(*
0072B164   C3                     ret

*)
end;

procedure TFrmDefRelatorio.DBNavigator1Click(Sender : TObject);
begin
(*
0072B168   55                     push    ebp
0072B169   8BEC                   mov     ebp, esp
0072B16B   6A00                   push    $00
0072B16D   53                     push    ebx
0072B16E   8BD8                   mov     ebx, eax
0072B170   33C0                   xor     eax, eax
0072B172   55                     push    ebp
0072B173   68C5B17200             push    $0072B1C5

***** TRY
|
0072B178   64FF30                 push    dword ptr fs:[eax]
0072B17B   648920                 mov     fs:[eax], esp
0072B17E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B183   8B00                   mov     eax, [eax]
0072B185   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Definicao'
|
0072B188   BAD8B17200             mov     edx, $0072B1D8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B18D   E872EADBFF             call    004E9C04
0072B192   8D55FC                 lea     edx, [ebp-$04]
0072B195   8B08                   mov     ecx, [eax]
0072B197   FF5160                 call    dword ptr [ecx+$60]
0072B19A   8B45FC                 mov     eax, [ebp-$04]
0072B19D   50                     push    eax

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B19E   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B1A4   E85BFAE0FF             call    0053AC04
0072B1A9   5A                     pop     edx
0072B1AA   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_2C
|
0072B1AC   FF512C                 call    dword ptr [ecx+$2C]
0072B1AF   33C0                   xor     eax, eax
0072B1B1   5A                     pop     edx
0072B1B2   59                     pop     ecx
0072B1B3   59                     pop     ecx
0072B1B4   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B1B7   68CCB17200             push    $0072B1CC
0072B1BC   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B1BF   E8D8A2CDFF             call    0040549C
0072B1C4   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B1C5   E96E9BCDFF             jmp     00404D38
0072B1CA   EBF0                   jmp     0072B1BC

****** END
|
0072B1CC   5B                     pop     ebx
0072B1CD   59                     pop     ecx
0072B1CE   5D                     pop     ebp
0072B1CF   C3                     ret

*)
end;

procedure TFrmDefRelatorio.FormShow(Sender : TObject);
begin
(*
0072B1E4   55                     push    ebp
0072B1E5   8BEC                   mov     ebp, esp
0072B1E7   6A00                   push    $00
0072B1E9   53                     push    ebx
0072B1EA   56                     push    esi
0072B1EB   8BD8                   mov     ebx, eax
0072B1ED   33C0                   xor     eax, eax
0072B1EF   55                     push    ebp
0072B1F0   6858B27200             push    $0072B258

***** TRY
|
0072B1F5   64FF30                 push    dword ptr fs:[eax]
0072B1F8   648920                 mov     fs:[eax], esp
0072B1FB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B200   8B00                   mov     eax, [eax]
0072B202   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Definicao'
|
0072B205   BA6CB27200             mov     edx, $0072B26C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B20A   E8F5E9DBFF             call    004E9C04
0072B20F   8D55FC                 lea     edx, [ebp-$04]
0072B212   8B08                   mov     ecx, [eax]
0072B214   FF5160                 call    dword ptr [ecx+$60]
0072B217   8B45FC                 mov     eax, [ebp-$04]
0072B21A   50                     push    eax

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B21B   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B221   E8DEF9E0FF             call    0053AC04
0072B226   5A                     pop     edx
0072B227   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_2C
|
0072B229   FF512C                 call    dword ptr [ecx+$2C]

* Reference to control TFrmDefRelatorio.cbTipoRelatorio : TJvDBComboBox
|
0072B22C   8B8368030000           mov     eax, [ebx+$0368]
0072B232   8BF0                   mov     esi, eax
0072B234   8BD0                   mov     edx, eax

* Reference to field TJvDBComboBox.OFFS_021C
|
0072B236   8B861C020000           mov     eax, [esi+$021C]

* Possible reference to virtual method TJvDBComboBox.OFFS_0218
|
0072B23C   FF9618020000           call    dword ptr [esi+$0218]
0072B242   33C0                   xor     eax, eax
0072B244   5A                     pop     edx
0072B245   59                     pop     ecx
0072B246   59                     pop     ecx
0072B247   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B24A   685FB27200             push    $0072B25F
0072B24F   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B252   E845A2CDFF             call    0040549C
0072B257   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B258   E9DB9ACDFF             jmp     00404D38
0072B25D   EBF0                   jmp     0072B24F

****** END
|
0072B25F   5E                     pop     esi
0072B260   5B                     pop     ebx
0072B261   59                     pop     ecx
0072B262   5D                     pop     ebp
0072B263   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton1Click(Sender : TObject);
begin
(*
0072B278   55                     push    ebp
0072B279   8BEC                   mov     ebp, esp
0072B27B   6A00                   push    $00
0072B27D   6A00                   push    $00
0072B27F   53                     push    ebx
0072B280   8BD8                   mov     ebx, eax
0072B282   33C0                   xor     eax, eax
0072B284   55                     push    ebp

* Possible String Reference to: 'È»ôÕˇÎÎ[YY]√'
|
0072B285   686BB37200             push    $0072B36B

***** TRY
|
0072B28A   64FF30                 push    dword ptr fs:[eax]
0072B28D   648920                 mov     fs:[eax], esp
0072B290   8B0D54AE7D00           mov     ecx, [$007DAE54]
0072B296   8B09                   mov     ecx, [ecx]
0072B298   B201                   mov     dl, $01

* Reference to class TFrmF2Funcoes
|
0072B29A   A1D0E36800             mov     eax, dword ptr [$0068E3D0]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0072B29F   E86C2CD8FF             call    004ADF10
0072B2A4   8B1508A97D00           mov     edx, [$007DA908]
0072B2AA   8902                   mov     [edx], eax
0072B2AC   33C0                   xor     eax, eax
0072B2AE   55                     push    ebp
0072B2AF   6849B37200             push    $0072B349

***** TRY
|
0072B2B4   64FF30                 push    dword ptr fs:[eax]
0072B2B7   648920                 mov     fs:[eax], esp
0072B2BA   A108A97D00             mov     eax, dword ptr [$007DA908]
0072B2BF   8B00                   mov     eax, [eax]
0072B2C1   8B10                   mov     edx, [eax]
0072B2C3   FF92EC000000           call    dword ptr [edx+$00EC]
0072B2C9   48                     dec     eax
0072B2CA   7544                   jnz     0072B310
0072B2CC   6880B37200             push    $0072B380
0072B2D1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B2D6   8B00                   mov     eax, [eax]
0072B2D8   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Nome'
|
0072B2DB   BA8CB37200             mov     edx, $0072B38C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B2E0   E81FE9DBFF             call    004E9C04
0072B2E5   8D55F8                 lea     edx, [ebp-$08]
0072B2E8   8B08                   mov     ecx, [eax]
0072B2EA   FF5160                 call    dword ptr [ecx+$60]
0072B2ED   FF75F8                 push    dword ptr [ebp-$08]
0072B2F0   689CB37200             push    $0072B39C
0072B2F5   8D45FC                 lea     eax, [ebp-$04]
0072B2F8   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0072B2FD   E81AA5CDFF             call    0040581C
0072B302   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B305   8B834C030000           mov     eax, [ebx+$034C]

|
0072B30B   E878EBE0FF             call    00539E88
0072B310   33C0                   xor     eax, eax
0072B312   5A                     pop     edx
0072B313   59                     pop     ecx
0072B314   59                     pop     ecx
0072B315   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B318   6850B37200             push    $0072B350
0072B31D   A108A97D00             mov     eax, dword ptr [$007DA908]
0072B322   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0072B324   E87392CDFF             call    0040459C
0072B329   6A00                   push    $00
0072B32B   6A00                   push    $00
0072B32D   6A01                   push    $01
0072B32F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B334   8B00                   mov     eax, [eax]
0072B336   8B4058                 mov     eax, [eax+$58]
0072B339   B9A8B37200             mov     ecx, $0072B3A8

* Possible String Reference to: 'FUNCOES'
|
0072B33E   BAB4B37200             mov     edx, $0072B3B4

|
0072B343   E820C70700             call    007A7A68
0072B348   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B349   E9EA99CDFF             jmp     00404D38
0072B34E   EBCD                   jmp     0072B31D

****** END
|
0072B350   33C0                   xor     eax, eax
0072B352   5A                     pop     edx
0072B353   59                     pop     ecx
0072B354   59                     pop     ecx
0072B355   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]√'
|
0072B358   6872B37200             push    $0072B372
0072B35D   8D45F8                 lea     eax, [ebp-$08]
0072B360   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072B365   E856A1CDFF             call    004054C0
0072B36A   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B36B   E9C899CDFF             jmp     00404D38
0072B370   EBEB                   jmp     0072B35D

****** END
|
0072B372   5B                     pop     ebx
0072B373   59                     pop     ecx
0072B374   59                     pop     ecx
0072B375   5D                     pop     ebp
0072B376   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton2Click(Sender : TObject);
begin
(*
0072B3BC   55                     push    ebp
0072B3BD   8BEC                   mov     ebp, esp
0072B3BF   6A00                   push    $00
0072B3C1   6A00                   push    $00
0072B3C3   53                     push    ebx
0072B3C4   8BD8                   mov     ebx, eax
0072B3C6   33C0                   xor     eax, eax
0072B3C8   55                     push    ebp
0072B3C9   6870B47200             push    $0072B470

***** TRY
|
0072B3CE   64FF30                 push    dword ptr fs:[eax]
0072B3D1   648920                 mov     fs:[eax], esp
0072B3D4   8B0D54AE7D00           mov     ecx, [$007DAE54]
0072B3DA   8B09                   mov     ecx, [ecx]
0072B3DC   B201                   mov     dl, $01

* Reference to class TFrmF2Fontes
|
0072B3DE   A1B8917200             mov     eax, dword ptr [$007291B8]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0072B3E3   E8282BD8FF             call    004ADF10
0072B3E8   8B15749F7D00           mov     edx, [$007D9F74]
0072B3EE   8902                   mov     [edx], eax
0072B3F0   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072B3F5   8B00                   mov     eax, [eax]
0072B3F7   8B10                   mov     edx, [eax]
0072B3F9   FF92EC000000           call    dword ptr [edx+$00EC]
0072B3FF   48                     dec     eax
0072B400   7547                   jnz     0072B449
0072B402   6884B47200             push    $0072B484
0072B407   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B40C   8B00                   mov     eax, [eax]
0072B40E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'CodFonte'
|
0072B414   BA90B47200             mov     edx, $0072B490

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B419   E8E6E7DBFF             call    004E9C04
0072B41E   8D55F8                 lea     edx, [ebp-$08]
0072B421   8B08                   mov     ecx, [eax]
0072B423   FF5160                 call    dword ptr [ecx+$60]
0072B426   FF75F8                 push    dword ptr [ebp-$08]
0072B429   6884B47200             push    $0072B484
0072B42E   8D45FC                 lea     eax, [ebp-$04]
0072B431   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0072B436   E8E1A3CDFF             call    0040581C
0072B43B   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B43E   8B834C030000           mov     eax, [ebx+$034C]

|
0072B444   E83FEAE0FF             call    00539E88
0072B449   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072B44E   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0072B450   E84791CDFF             call    0040459C
0072B455   33C0                   xor     eax, eax
0072B457   5A                     pop     edx
0072B458   59                     pop     ecx
0072B459   59                     pop     ecx
0072B45A   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B45D   6877B47200             push    $0072B477
0072B462   8D45F8                 lea     eax, [ebp-$08]
0072B465   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072B46A   E851A0CDFF             call    004054C0
0072B46F   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B470   E9C398CDFF             jmp     00404D38
0072B475   EBEB                   jmp     0072B462

****** END
|
0072B477   5B                     pop     ebx
0072B478   59                     pop     ecx
0072B479   59                     pop     ecx
0072B47A   5D                     pop     ebp
0072B47B   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton3Click(Sender : TObject);
begin
(*
0072B49C   55                     push    ebp
0072B49D   8BEC                   mov     ebp, esp
0072B49F   33C0                   xor     eax, eax
0072B4A1   55                     push    ebp

* Possible String Reference to: 'ÈZòÕˇÎ¯]√'
|
0072B4A2   68D9B47200             push    $0072B4D9

***** TRY
|
0072B4A7   64FF30                 push    dword ptr fs:[eax]
0072B4AA   648920                 mov     fs:[eax], esp
0072B4AD   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B4B2   8B00                   mov     eax, [eax]
0072B4B4   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'CODIGO'
|
0072B4B7   BAECB47200             mov     edx, $0072B4EC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B4BC   E843E7DBFF             call    004E9C04
0072B4C1   8B10                   mov     edx, [eax]
0072B4C3   FF5258                 call    dword ptr [edx+$58]

* Reference to : TFrmPreview._PROC_0072E820()
|
0072B4C6   E855330000             call    0072E820
0072B4CB   33C0                   xor     eax, eax
0072B4CD   5A                     pop     edx
0072B4CE   59                     pop     ecx
0072B4CF   59                     pop     ecx
0072B4D0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√'
|
0072B4D3   68E0B47200             push    $0072B4E0
0072B4D8   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B4D9   E95A98CDFF             jmp     00404D38
0072B4DE   EBF8                   jmp     0072B4D8

****** END
|
0072B4E0   5D                     pop     ebp
0072B4E1   C3                     ret

*)
end;

procedure TFrmDefRelatorio.FormCloseQuery(Sender : TObject);
begin
(*
0072B4F4   55                     push    ebp
0072B4F5   8BEC                   mov     ebp, esp
0072B4F7   6A00                   push    $00
0072B4F9   6A00                   push    $00
0072B4FB   53                     push    ebx
0072B4FC   56                     push    esi
0072B4FD   8BD9                   mov     ebx, ecx
0072B4FF   8BF0                   mov     esi, eax
0072B501   33C0                   xor     eax, eax
0072B503   55                     push    ebp
0072B504   68FFB57200             push    $0072B5FF

***** TRY
|
0072B509   64FF30                 push    dword ptr fs:[eax]
0072B50C   648920                 mov     fs:[eax], esp
0072B50F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B514   8B00                   mov     eax, [eax]
0072B516   8B4074                 mov     eax, [eax+$74]
0072B519   8A809D000000           mov     al, byte ptr [eax+$009D]
0072B51F   04FE                   add     al, -$02
0072B521   2C02                   sub     al, $02
0072B523   0F83B8000000           jnb     0072B5E1
0072B529   6A00                   push    $00
0072B52B   668B0D0CB67200         mov     cx, word ptr [$0072B60C]
0072B532   B203                   mov     dl, $03

* Possible String Reference to: 'Deseja salvar as alteraÁıes antes d
|                                e sair?'
|
0072B534   B818B67200             mov     eax, $0072B618

|
0072B539   E8EE85D1FF             call    00443B2C
0072B53E   83F806                 cmp     eax, +$06
0072B541   0F8588000000           jnz     0072B5CF
0072B547   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.EdDescrRelatorio : TDBEdit
|
0072B54A   8B8608030000           mov     eax, [esi+$0308]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072B550   E8E729DDFF             call    004FDF3C
0072B555   837DFC00               cmp     dword ptr [ebp-$04], +$00
0072B559   7457                   jz      0072B5B2
0072B55B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B560   8B00                   mov     eax, [eax]
0072B562   8B4074                 mov     eax, [eax+$74]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0072B565   E8CEFEDBFF             call    004EB438

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B56A   8B864C030000           mov     eax, [esi+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B570   E88FF6E0FF             call    0053AC04
0072B575   8D55F8                 lea     edx, [ebp-$08]
0072B578   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_1C
|
0072B57A   FF511C                 call    dword ptr [ecx+$1C]
0072B57D   8B45F8                 mov     eax, [ebp-$08]
0072B580   50                     push    eax
0072B581   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B586   8B00                   mov     eax, [eax]
0072B588   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Definicao'
|
0072B58B   BA4CB67200             mov     edx, $0072B64C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B590   E86FE6DBFF             call    004E9C04
0072B595   5A                     pop     edx
0072B596   8B08                   mov     ecx, [eax]
0072B598   FF91B0000000           call    dword ptr [ecx+$00B0]
0072B59E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B5A3   8B00                   mov     eax, [eax]
0072B5A5   8B4074                 mov     eax, [eax+$74]
0072B5A8   8B10                   mov     edx, [eax]
0072B5AA   FF924C020000           call    dword ptr [edx+$024C]
0072B5B0   EB2F                   jmp     0072B5E1

* Possible String Reference to: 'Informe a DescriÁ„o!'
|
0072B5B2   B860B67200             mov     eax, $0072B660

* Reference to: Dialogs.ShowMessage(AnsiString);
|
0072B5B7   E86886D1FF             call    00443C24

* Reference to control TFrmDefRelatorio.EdDescrRelatorio : TDBEdit
|
0072B5BC   8B8608030000           mov     eax, [esi+$0308]
0072B5C2   8B10                   mov     edx, [eax]

* Reference to method TDBEdit.SetFocus()
|
0072B5C4   FF92C4000000           call    dword ptr [edx+$00C4]
0072B5CA   C60300                 mov     byte ptr [ebx], $00
0072B5CD   EB12                   jmp     0072B5E1
0072B5CF   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B5D4   8B00                   mov     eax, [eax]
0072B5D6   8B4074                 mov     eax, [eax+$74]
0072B5D9   8B10                   mov     edx, [eax]
0072B5DB   FF920C020000           call    dword ptr [edx+$020C]
0072B5E1   33C0                   xor     eax, eax
0072B5E3   5A                     pop     edx
0072B5E4   59                     pop     ecx
0072B5E5   59                     pop     ecx
0072B5E6   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B5E9   6806B67200             push    $0072B606
0072B5EE   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
0072B5F1   E8A69ECDFF             call    0040549C
0072B5F6   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B5F9   E89E9ECDFF             call    0040549C
0072B5FE   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B5FF   E93497CDFF             jmp     00404D38
0072B604   EBE8                   jmp     0072B5EE

****** END
|
0072B606   5E                     pop     esi
0072B607   5B                     pop     ebx
0072B608   59                     pop     ecx
0072B609   59                     pop     ecx
0072B60A   5D                     pop     ebp
0072B60B   C3                     ret

*)
end;

procedure TFrmDefRelatorio.FormCreate(Sender : TObject);
begin
(*
0072B678   55                     push    ebp
0072B679   8BEC                   mov     ebp, esp

|
0072B67B   E8C0A80700             call    007A5F40
0072B680   5D                     pop     ebp
0072B681   C3                     ret

*)
end;

procedure TFrmDefRelatorio.FormClose(Sender : TObject);
begin
(*
0072B684   55                     push    ebp
0072B685   8BEC                   mov     ebp, esp

|
0072B687   E8CCA80700             call    007A5F58
0072B68C   5D                     pop     ebp
0072B68D   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton5Click(Sender : TObject);
begin
(*
0072B690   55                     push    ebp
0072B691   8BEC                   mov     ebp, esp
0072B693   6A00                   push    $00
0072B695   56                     push    esi
0072B696   8BF0                   mov     esi, eax
0072B698   33C0                   xor     eax, eax
0072B69A   55                     push    ebp

* Possible String Reference to: 'ÈEñÕˇÎ^Y]√ç@'
|
0072B69B   68EEB67200             push    $0072B6EE

***** TRY
|
0072B6A0   64FF30                 push    dword ptr fs:[eax]
0072B6A3   648920                 mov     fs:[eax], esp

* Reference to control TFrmDefRelatorio.sdDefRelatorio : TSaveDialog
|
0072B6A6   8B8634030000           mov     eax, [esi+$0334]
0072B6AC   8B10                   mov     edx, [eax]

* Reference to method TSaveDialog.Execute()
|
0072B6AE   FF523C                 call    dword ptr [edx+$3C]
0072B6B1   84C0                   test    al, al
0072B6B3   7423                   jz      0072B6D8
0072B6B5   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.sdDefRelatorio : TSaveDialog
|
0072B6B8   8B8634030000           mov     eax, [esi+$0334]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0072B6BE   E86D63D1FF             call    00441A30
0072B6C3   8B45FC                 mov     eax, [ebp-$04]
0072B6C6   50                     push    eax

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B6C7   8B864C030000           mov     eax, [esi+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B6CD   E832F5E0FF             call    0053AC04
0072B6D2   5A                     pop     edx
0072B6D3   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_74
|
0072B6D5   FF5174                 call    dword ptr [ecx+$74]
0072B6D8   33C0                   xor     eax, eax
0072B6DA   5A                     pop     edx
0072B6DB   59                     pop     ecx
0072B6DC   59                     pop     ecx
0072B6DD   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^Y]√ç@'
|
0072B6E0   68F5B67200             push    $0072B6F5
0072B6E5   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B6E8   E8AF9DCDFF             call    0040549C
0072B6ED   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B6EE   E94596CDFF             jmp     00404D38
0072B6F3   EBF0                   jmp     0072B6E5

****** END
|
0072B6F5   5E                     pop     esi
0072B6F6   59                     pop     ecx
0072B6F7   5D                     pop     ebp
0072B6F8   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton6Click(Sender : TObject);
begin
(*
0072B6FC   55                     push    ebp
0072B6FD   8BEC                   mov     ebp, esp
0072B6FF   6A00                   push    $00
0072B701   56                     push    esi
0072B702   8BF0                   mov     esi, eax
0072B704   33C0                   xor     eax, eax
0072B706   55                     push    ebp

* Possible String Reference to: 'È…ïÕˇÎ^Y]√ç@'
|
0072B707   686AB77200             push    $0072B76A

***** TRY
|
0072B70C   64FF30                 push    dword ptr fs:[eax]
0072B70F   648920                 mov     fs:[eax], esp

* Reference to control TFrmDefRelatorio.odDefRelatorio : TOpenDialog
|
0072B712   8B8638030000           mov     eax, [esi+$0338]
0072B718   8B10                   mov     edx, [eax]

* Reference to method TOpenDialog.Execute()
|
0072B71A   FF523C                 call    dword ptr [edx+$3C]
0072B71D   84C0                   test    al, al
0072B71F   7433                   jz      0072B754

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B721   8B864C030000           mov     eax, [esi+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B727   E8D8F4E0FF             call    0053AC04
0072B72C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_44
|
0072B72E   FF5244                 call    dword ptr [edx+$44]
0072B731   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.odDefRelatorio : TOpenDialog
|
0072B734   8B8638030000           mov     eax, [esi+$0338]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0072B73A   E8F162D1FF             call    00441A30
0072B73F   8B45FC                 mov     eax, [ebp-$04]
0072B742   50                     push    eax

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B743   8B864C030000           mov     eax, [esi+$034C]

* Reference to: ADODB.TADOQuery.GetSQL(TADOQuery):TStrings;
|
0072B749   E8B6F4E0FF             call    0053AC04
0072B74E   5A                     pop     edx
0072B74F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TJvHLEditor.OFFS_68
|
0072B751   FF5168                 call    dword ptr [ecx+$68]
0072B754   33C0                   xor     eax, eax
0072B756   5A                     pop     edx
0072B757   59                     pop     ecx
0072B758   59                     pop     ecx
0072B759   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^Y]√ç@'
|
0072B75C   6871B77200             push    $0072B771
0072B761   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B764   E8339DCDFF             call    0040549C
0072B769   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B76A   E9C995CDFF             jmp     00404D38
0072B76F   EBF0                   jmp     0072B761

****** END
|
0072B771   5E                     pop     esi
0072B772   59                     pop     ecx
0072B773   5D                     pop     ebp
0072B774   C3                     ret

*)
end;

procedure TFrmDefRelatorio.EdDesenhoButtonClick(Sender : TObject);
begin
(*
0072B778   55                     push    ebp
0072B779   8BEC                   mov     ebp, esp
0072B77B   6A00                   push    $00
0072B77D   53                     push    ebx
0072B77E   8BD8                   mov     ebx, eax
0072B780   33C0                   xor     eax, eax
0072B782   55                     push    ebp

* Possible String Reference to: 'È0ïÕˇÎ[Y]√'
|
0072B783   6803B87200             push    $0072B803

***** TRY
|
0072B788   64FF30                 push    dword ptr fs:[eax]
0072B78B   648920                 mov     fs:[eax], esp

* Reference to control TFrmDefRelatorio.opDesenho : TOpenPictureDialog
|
0072B78E   8B8360030000           mov     eax, [ebx+$0360]
0072B794   8B10                   mov     edx, [eax]

* Reference to method TOpenPictureDialog.Execute()
|
0072B796   FF523C                 call    dword ptr [edx+$3C]
0072B799   84C0                   test    al, al
0072B79B   7450                   jz      0072B7ED
0072B79D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B7A2   8B00                   mov     eax, [eax]
0072B7A4   8B4074                 mov     eax, [eax+$74]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0072B7A7   E88CFCDBFF             call    004EB438
0072B7AC   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.opDesenho : TOpenPictureDialog
|
0072B7AF   8B8360030000           mov     eax, [ebx+$0360]

* Reference to: Dialogs.TOpenDialog.GetFileName(TOpenDialog):TFileName;
|
0072B7B5   E87662D1FF             call    00441A30
0072B7BA   8B45FC                 mov     eax, [ebp-$04]
0072B7BD   50                     push    eax
0072B7BE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B7C3   8B00                   mov     eax, [eax]
0072B7C5   8B4074                 mov     eax, [eax+$74]

* Possible String Reference to: 'Desenho'
|
0072B7C8   BA18B87200             mov     edx, $0072B818

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B7CD   E832E4DBFF             call    004E9C04
0072B7D2   5A                     pop     edx
0072B7D3   8B08                   mov     ecx, [eax]
0072B7D5   FF91B0000000           call    dword ptr [ecx+$00B0]
0072B7DB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B7E0   8B00                   mov     eax, [eax]
0072B7E2   8B4074                 mov     eax, [eax+$74]
0072B7E5   8B10                   mov     edx, [eax]
0072B7E7   FF924C020000           call    dword ptr [edx+$024C]
0072B7ED   33C0                   xor     eax, eax
0072B7EF   5A                     pop     edx
0072B7F0   59                     pop     ecx
0072B7F1   59                     pop     ecx
0072B7F2   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√'
|
0072B7F5   680AB87200             push    $0072B80A
0072B7FA   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072B7FD   E89A9CCDFF             call    0040549C
0072B802   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B803   E93095CDFF             jmp     00404D38
0072B808   EBF0                   jmp     0072B7FA

****** END
|
0072B80A   5B                     pop     ebx
0072B80B   59                     pop     ecx
0072B80C   5D                     pop     ebp
0072B80D   C3                     ret

*)
end;

procedure TFrmDefRelatorio.EdImpressoraButtonClick(Sender : TObject);
begin
(*
0072B820   55                     push    ebp
0072B821   8BEC                   mov     ebp, esp
0072B823   53                     push    ebx
0072B824   8BD8                   mov     ebx, eax

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B826   8B8374030000           mov     eax, [ebx+$0374]
0072B82C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPBPrinterSetupDialog.OFFS_3C
|
0072B82E   FF523C                 call    dword ptr [edx+$3C]
0072B831   84C0                   test    al, al
0072B833   0F84DF000000           jz      0072B918
0072B839   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B83E   8B00                   mov     eax, [eax]
0072B840   8B80C8000000           mov     eax, [eax+$00C8]

|
0072B846   E8D5B50700             call    007A6E20

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B84B   8B8374030000           mov     eax, [ebx+$0374]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
0072B851   8B8010030000           mov     eax, [eax+$0310]
0072B857   8B5034                 mov     edx, [eax+$34]
0072B85A   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B85F   8B00                   mov     eax, [eax]
0072B861   8B80D8000000           mov     eax, [eax+$00D8]
0072B867   8B08                   mov     ecx, [eax]
0072B869   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B86F   8B8374030000           mov     eax, [ebx+$0374]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
0072B875   8B8010030000           mov     eax, [eax+$0310]
0072B87B   0FBF502A               movsx   edx, word ptr [eax+$2A]
0072B87F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B884   8B00                   mov     eax, [eax]
0072B886   8B80E0000000           mov     eax, [eax+$00E0]
0072B88C   8B08                   mov     ecx, [eax]
0072B88E   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B894   8B8374030000           mov     eax, [ebx+$0374]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
0072B89A   8B8010030000           mov     eax, [eax+$0310]
0072B8A0   0FBF5028               movsx   edx, word ptr [eax+$28]
0072B8A4   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B8A9   8B00                   mov     eax, [eax]
0072B8AB   8B80E4000000           mov     eax, [eax+$00E4]
0072B8B1   8B08                   mov     ecx, [eax]
0072B8B3   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B8B9   8B8374030000           mov     eax, [ebx+$0374]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
0072B8BF   8B8010030000           mov     eax, [eax+$0310]
0072B8C5   0FBF502C               movsx   edx, word ptr [eax+$2C]
0072B8C9   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B8CE   8B00                   mov     eax, [eax]
0072B8D0   8B80E8000000           mov     eax, [eax+$00E8]
0072B8D6   8B08                   mov     ecx, [eax]
0072B8D8   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TFrmDefRelatorio.PrintSetup : TPBPrinterSetupDialog
|
0072B8DE   8B8374030000           mov     eax, [ebx+$0374]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
0072B8E4   8B8010030000           mov     eax, [eax+$0310]
0072B8EA   0FBF502E               movsx   edx, word ptr [eax+$2E]
0072B8EE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B8F3   8B00                   mov     eax, [eax]
0072B8F5   8B80EC000000           mov     eax, [eax+$00EC]
0072B8FB   8B08                   mov     ecx, [eax]
0072B8FD   FF91A8000000           call    dword ptr [ecx+$00A8]
0072B903   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B908   8B00                   mov     eax, [eax]
0072B90A   8B80C8000000           mov     eax, [eax+$00C8]

|
0072B910   E84BB60700             call    007A6F60
0072B915   5B                     pop     ebx
0072B916   5D                     pop     ebp
0072B917   C3                     ret

*)
end;

procedure TFrmDefRelatorio.EdCodImpressoraChange(Sender : TObject);
begin
(*
0072B984   55                     push    ebp
0072B985   8BEC                   mov     ebp, esp
0072B987   33C9                   xor     ecx, ecx
0072B989   51                     push    ecx
0072B98A   51                     push    ecx
0072B98B   51                     push    ecx
0072B98C   51                     push    ecx
0072B98D   51                     push    ecx
0072B98E   53                     push    ebx
0072B98F   8BD8                   mov     ebx, eax
0072B991   33C0                   xor     eax, eax
0072B993   55                     push    ebp

* Possible String Reference to: 'È˘íÕˇÎ€[ãÂ]√'
|
0072B994   683ABA7200             push    $0072BA3A

***** TRY
|
0072B999   64FF30                 push    dword ptr fs:[eax]
0072B99C   648920                 mov     fs:[eax], esp
0072B99F   33D2                   xor     edx, edx

* Reference to control TFrmDefRelatorio.EdMatricial : TEdit
|
0072B9A1   8B83AC030000           mov     eax, [ebx+$03AC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0072B9A7   E8507DD6FF             call    004936FC
0072B9AC   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.EdCodImpressora : TJvDBComboEdit
|
0072B9AF   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072B9B5   E88225DDFF             call    004FDF3C
0072B9BA   837DFC00               cmp     dword ptr [ebp-$04], +$00
0072B9BE   744F                   jz      0072BA0F

* Possible String Reference to: 'Impressora'
|
0072B9C0   6850BA7200             push    $0072BA50
0072B9C5   8D45F8                 lea     eax, [ebp-$08]
0072B9C8   50                     push    eax
0072B9C9   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmDefRelatorio.EdCodImpressora : TJvDBComboEdit
|
0072B9CC   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072B9D2   E86525DDFF             call    004FDF3C
0072B9D7   8B45EC                 mov     eax, [ebp-$14]
0072B9DA   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0072B9DD   E83E810700             call    007A3B20
0072B9E2   8B4DF0                 mov     ecx, [ebp-$10]
0072B9E5   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'CodImpressora = '
|
0072B9E8   BA64BA7200             mov     edx, $0072BA64

* Reference to: System.@LStrCat3;
|
0072B9ED   E8B69DCDFF             call    004057A8
0072B9F2   8B4DF4                 mov     ecx, [ebp-$0C]

* Possible String Reference to: 'Impress'
|
0072B9F5   BA80BA7200             mov     edx, $0072BA80
0072B9FA   33C0                   xor     eax, eax

|
0072B9FC   E80FD90700             call    007A9310
0072BA01   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TFrmDefRelatorio.EdMatricial : TEdit
|
0072BA04   8B83AC030000           mov     eax, [ebx+$03AC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0072BA0A   E8ED7CD6FF             call    004936FC
0072BA0F   33C0                   xor     eax, eax
0072BA11   5A                     pop     edx
0072BA12   59                     pop     ecx
0072BA13   59                     pop     ecx
0072BA14   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√'
|
0072BA17   6841BA7200             push    $0072BA41
0072BA1C   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0072BA1F   E8789ACDFF             call    0040549C
0072BA24   8D45F0                 lea     eax, [ebp-$10]
0072BA27   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072BA2C   E88F9ACDFF             call    004054C0
0072BA31   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072BA34   E8639ACDFF             call    0040549C
0072BA39   C3                     ret


* Reference to: System.@HandleFinally;
|
0072BA3A   E9F992CDFF             jmp     00404D38
0072BA3F   EBDB                   jmp     0072BA1C

****** END
|
0072BA41   5B                     pop     ebx
0072BA42   8BE5                   mov     esp, ebp
0072BA44   5D                     pop     ebp
0072BA45   C3                     ret

*)
end;

procedure TFrmDefRelatorio.EdCodImpressoraButtonClick(Sender : TObject);
begin
(*
0072BA88   55                     push    ebp
0072BA89   8BEC                   mov     ebp, esp
0072BA8B   83C4EC                 add     esp, -$14
0072BA8E   33C9                   xor     ecx, ecx
0072BA90   894DEC                 mov     [ebp-$14], ecx
0072BA93   33C0                   xor     eax, eax
0072BA95   55                     push    ebp

* Possible String Reference to: 'È‘ëÕˇÎãÂ]√'
|
0072BA96   685FBB7200             push    $0072BB5F

***** TRY
|
0072BA9B   64FF30                 push    dword ptr fs:[eax]
0072BA9E   648920                 mov     fs:[eax], esp
0072BAA1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BAA6   8B00                   mov     eax, [eax]
0072BAA8   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BAAE   E855AA0700             call    007A6508

* Possible String Reference to: 'CÛdigo'
|
0072BAB3   B874BB7200             mov     eax, $0072BB74
0072BAB8   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Impressora'
|
0072BABB   B884BB7200             mov     eax, $0072BB84
0072BAC0   8945FC                 mov     [ebp-$04], eax
0072BAC3   8D45F8                 lea     eax, [ebp-$08]
0072BAC6   50                     push    eax
0072BAC7   6A01                   push    $01
0072BAC9   6A00                   push    $00

* Possible String Reference to: 'CodImpressora'
|
0072BACB   B898BB7200             mov     eax, $0072BB98
0072BAD0   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Impressora'
|
0072BAD3   B884BB7200             mov     eax, $0072BB84
0072BAD8   8945F4                 mov     [ebp-$0C], eax
0072BADB   8D55F0                 lea     edx, [ebp-$10]
0072BADE   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRESS'
|
0072BAE3   B8B0BB7200             mov     eax, $0072BBB0

|
0072BAE8   E867D7F0FF             call    00639254
0072BAED   84C0                   test    al, al
0072BAEF   7458                   jz      0072BB49
0072BAF1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BAF6   8B00                   mov     eax, [eax]
0072BAF8   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BAFE   E81DB30700             call    007A6E20
0072BB03   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0072BB08   8B00                   mov     eax, [eax]
0072BB0A   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CodImpressora'
|
0072BB0D   BA98BB7200             mov     edx, $0072BB98

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072BB12   E8EDE0DBFF             call    004E9C04
0072BB17   8D55EC                 lea     edx, [ebp-$14]
0072BB1A   8B08                   mov     ecx, [eax]
0072BB1C   FF5160                 call    dword ptr [ecx+$60]
0072BB1F   8B55EC                 mov     edx, [ebp-$14]
0072BB22   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BB27   8B00                   mov     eax, [eax]
0072BB29   8B80DC000000           mov     eax, [eax+$00DC]
0072BB2F   8B08                   mov     ecx, [eax]
0072BB31   FF91B0000000           call    dword ptr [ecx+$00B0]
0072BB37   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BB3C   8B00                   mov     eax, [eax]
0072BB3E   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BB44   E817B40700             call    007A6F60
0072BB49   33C0                   xor     eax, eax
0072BB4B   5A                     pop     edx
0072BB4C   59                     pop     ecx
0072BB4D   59                     pop     ecx
0072BB4E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0072BB51   6866BB7200             push    $0072BB66
0072BB56   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0072BB59   E83E99CDFF             call    0040549C
0072BB5E   C3                     ret


* Reference to: System.@HandleFinally;
|
0072BB5F   E9D491CDFF             jmp     00404D38
0072BB64   EBF0                   jmp     0072BB56

****** END
|
0072BB66   8BE5                   mov     esp, ebp
0072BB68   5D                     pop     ebp
0072BB69   C3                     ret

*)
end;

procedure TFrmDefRelatorio.sbGravarClick(Sender : TObject);
begin
(*
0072BBB8   55                     push    ebp
0072BBB9   8BEC                   mov     ebp, esp
0072BBBB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BBC0   8B00                   mov     eax, [eax]
0072BBC2   8B4074                 mov     eax, [eax+$74]

|
0072BBC5   E896B30700             call    007A6F60
0072BBCA   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BBCF   8B00                   mov     eax, [eax]
0072BBD1   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BBD7   E884B30700             call    007A6F60
0072BBDC   5D                     pop     ebp
0072BBDD   C3                     ret

*)
end;

procedure TFrmDefRelatorio.cbTipoRelatorioChange(Sender : TObject);
begin
(*
0072BBE0   55                     push    ebp
0072BBE1   8BEC                   mov     ebp, esp
0072BBE3   6A00                   push    $00
0072BBE5   53                     push    ebx
0072BBE6   8BD8                   mov     ebx, eax
0072BBE8   33C0                   xor     eax, eax
0072BBEA   55                     push    ebp
0072BBEB   6845BC7200             push    $0072BC45

***** TRY
|
0072BBF0   64FF30                 push    dword ptr fs:[eax]
0072BBF3   648920                 mov     fs:[eax], esp
0072BBF6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.cbTipoRelatorio : TJvDBComboBox
|
0072BBF9   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0072BBFF   E8C87AD6FF             call    004936CC
0072BC04   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'etiqueta'
|
0072BC07   BA58BC7200             mov     edx, $0072BC58

* Reference to: System.@LStrCmp;
|
0072BC0C   E8979CCDFF             call    004058A8
0072BC11   750F                   jnz     0072BC22
0072BC13   B201                   mov     dl, $01

* Reference to control TFrmDefRelatorio.nbEtiquetas : TNotebook
|
0072BC15   8B83C0030000           mov     eax, [ebx+$03C0]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0072BC1B   E8CC79D6FF             call    004935EC
0072BC20   EB0D                   jmp     0072BC2F
0072BC22   33D2                   xor     edx, edx

* Reference to control TFrmDefRelatorio.nbEtiquetas : TNotebook
|
0072BC24   8B83C0030000           mov     eax, [ebx+$03C0]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0072BC2A   E8BD79D6FF             call    004935EC
0072BC2F   33C0                   xor     eax, eax
0072BC31   5A                     pop     edx
0072BC32   59                     pop     ecx
0072BC33   59                     pop     ecx
0072BC34   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072BC37   684CBC7200             push    $0072BC4C
0072BC3C   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0072BC3F   E85898CDFF             call    0040549C
0072BC44   C3                     ret


* Reference to: System.@HandleFinally;
|
0072BC45   E9EE90CDFF             jmp     00404D38
0072BC4A   EBF0                   jmp     0072BC3C

****** END
|
0072BC4C   5B                     pop     ebx
0072BC4D   59                     pop     ecx
0072BC4E   5D                     pop     ebp
0072BC4F   C3                     ret

*)
end;

procedure TFrmDefRelatorio.SpeedButton7Click(Sender : TObject);
begin
(*
0072BC64   C3                     ret

*)
end;

procedure TFrmDefRelatorio.GrDirecaoExit(Sender : TObject);
begin
(*
0072BC68   55                     push    ebp
0072BC69   8BEC                   mov     ebp, esp
0072BC6B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BC70   8B00                   mov     eax, [eax]
0072BC72   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BC78   E8E3B20700             call    007A6F60
0072BC7D   5D                     pop     ebp
0072BC7E   C3                     ret

*)
end;

procedure TFrmDefRelatorio.EdCodImpressoraExit(Sender : TObject);
begin
(*
0072BC80   55                     push    ebp
0072BC81   8BEC                   mov     ebp, esp
0072BC83   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072BC88   8B00                   mov     eax, [eax]
0072BC8A   8B80C8000000           mov     eax, [eax+$00C8]

|
0072BC90   E8CBB20700             call    007A6F60
0072BC95   5D                     pop     ebp
0072BC96   C3                     ret

*)
end;

procedure TFrmDefRelatorio._PROC_0072B3B6(Sender : TObject);
begin
(*
0072B3B6   4E                     dec     esi
0072B3B7   43                     inc     ebx
0072B3B8   4F                     dec     edi
0072B3B9   45                     inc     ebp
0072B3BA   53                     push    ebx
0072B3BB   00558B                 add     [ebp-$75], dl
0072B3BE   EC                     in      al, dx
0072B3BF   6A00                   push    $00
0072B3C1   6A00                   push    $00
0072B3C3   53                     push    ebx
0072B3C4   8BD8                   mov     ebx, eax
0072B3C6   33C0                   xor     eax, eax
0072B3C8   55                     push    ebp
0072B3C9   6870B47200             push    $0072B470

***** TRY
|
0072B3CE   64FF30                 push    dword ptr fs:[eax]
0072B3D1   648920                 mov     fs:[eax], esp
0072B3D4   8B0D54AE7D00           mov     ecx, [$007DAE54]
0072B3DA   8B09                   mov     ecx, [ecx]
0072B3DC   B201                   mov     dl, $01

* Reference to class TFrmF2Fontes
|
0072B3DE   A1B8917200             mov     eax, dword ptr [$007291B8]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0072B3E3   E8282BD8FF             call    004ADF10
0072B3E8   8B15749F7D00           mov     edx, [$007D9F74]
0072B3EE   8902                   mov     [edx], eax
0072B3F0   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072B3F5   8B00                   mov     eax, [eax]
0072B3F7   8B10                   mov     edx, [eax]
0072B3F9   FF92EC000000           call    dword ptr [edx+$00EC]
0072B3FF   48                     dec     eax
0072B400   7547                   jnz     0072B449
0072B402   6884B47200             push    $0072B484
0072B407   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072B40C   8B00                   mov     eax, [eax]
0072B40E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'CodFonte'
|
0072B414   BA90B47200             mov     edx, $0072B490

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072B419   E8E6E7DBFF             call    004E9C04
0072B41E   8D55F8                 lea     edx, [ebp-$08]
0072B421   8B08                   mov     ecx, [eax]
0072B423   FF5160                 call    dword ptr [ecx+$60]
0072B426   FF75F8                 push    dword ptr [ebp-$08]
0072B429   6884B47200             push    $0072B484
0072B42E   8D45FC                 lea     eax, [ebp-$04]
0072B431   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0072B436   E8E1A3CDFF             call    0040581C
0072B43B   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TFrmDefRelatorio.meDefForm : TJvHLEditor
|
0072B43E   8B834C030000           mov     eax, [ebx+$034C]

|
0072B444   E83FEAE0FF             call    00539E88
0072B449   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072B44E   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0072B450   E84791CDFF             call    0040459C
0072B455   33C0                   xor     eax, eax
0072B457   5A                     pop     edx
0072B458   59                     pop     ecx
0072B459   59                     pop     ecx
0072B45A   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072B45D   6877B47200             push    $0072B477
0072B462   8D45F8                 lea     eax, [ebp-$08]
0072B465   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072B46A   E851A0CDFF             call    004054C0
0072B46F   C3                     ret


* Reference to: System.@HandleFinally;
|
0072B470   E9C398CDFF             jmp     00404D38
0072B475   EBEB                   jmp     0072B462

****** END
|
0072B477   5B                     pop     ebx
0072B478   59                     pop     ecx
0072B479   59                     pop     ecx
0072B47A   5D                     pop     ebp
0072B47B   C3                     ret

*)
end;

procedure TFrmDefRelatorio._PROC_0072B60C(Sender : TObject);
begin
(*
0072B60C   0300                   add     eax, [eax]
0072B60E   0000                   add     [eax], al

*)
end;

procedure TFrmDefRelatorio._PROC_0072B918(Sender : TObject);
begin
(*
0072B918   6A00                   push    $00
0072B91A   668B0D30B97200         mov     cx, word ptr [$0072B930]
0072B921   33D2                   xor     edx, edx

* Possible String Reference to: 'O WinSati n„o conseguiu executar o 
|                                di·logo de escolha de impressora!'
|
0072B923   B83CB97200             mov     eax, $0072B93C

|
0072B928   E8FF81D1FF             call    00443B2C
0072B92D   5B                     pop     ebx
0072B92E   5D                     pop     ebp
0072B92F   C3                     ret

*)
end;

procedure TFrmDefRelatorio._PROC_0072B930(Sender : TObject);
begin
(*
0072B930   0400                   add     al, +$00
0072B932   0000                   add     [eax], al

*)
end;

procedure TFrmDefRelatorio._PROC_0072BC98(Sender : TObject);
begin
(*
0072BC98   55                     push    ebp
0072BC99   8BEC                   mov     ebp, esp
0072BC9B   33C0                   xor     eax, eax
0072BC9D   55                     push    ebp

* Possible String Reference to: 'ÈvêÕˇÎ¯]√ã¿É-,Û}'
|
0072BC9E   68BDBC7200             push    $0072BCBD

***** TRY
|
0072BCA3   64FF30                 push    dword ptr fs:[eax]
0072BCA6   648920                 mov     fs:[eax], esp
0072BCA9   FF052CF37D00           inc     dword ptr [$007DF32C]
0072BCAF   33C0                   xor     eax, eax
0072BCB1   5A                     pop     edx
0072BCB2   59                     pop     ecx
0072BCB3   59                     pop     ecx
0072BCB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-,Û}'
|
0072BCB7   68C4BC7200             push    $0072BCC4
0072BCBC   C3                     ret


* Reference to: System.@HandleFinally;
|
0072BCBD   E97690CDFF             jmp     00404D38
0072BCC2   EBF8                   jmp     0072BCBC

****** END
|
0072BCC4   5D                     pop     ebp
0072BCC5   C3                     ret

*)
end;

procedure TFrmDefRelatorio._PROC_0072BCC8(Sender : TObject);
begin
(*
0072BCC8   832D2CF37D0001         sub     dword ptr [$007DF32C], +$01
0072BCCF   C3                     ret

*)
end;

procedure TFrmDefRelatorio._PROC_0072BCD0(Sender : TObject);
begin
(*
0072BCD0   1CBD                   sbb     al, $BD
0072BCD2   7200                   jb      0072BCD4
0072BCD4   0000                   add     [eax], al

*)
end;

procedure TFrmDefRelatorio._PROC_0072BE13(Sender : TObject);
begin
(*
0072BE13   BF7200F802             mov     edi, $02F80072
0072BE18   0000                   add     [eax], al

*)
end;

procedure TFrmDefRelatorio._PROC_0072BF7D(Sender : TObject);
begin
(*
0072BF7D   7375                   jnb     0072BFF4
0072BF7F   61                     popa
0072BF80   7269                   jb      0072BFEB
0072BF82   6F                     outsd
0072BF83   050004F447             add     eax, +$47F40400
0072BF88   0090614400A8           add     [eax+$A8004461], dl
0072BF8E   C9                     leave
0072BF8F   44                     inc     esp
0072BF90   00A0DB5C0070           add     [eax+$70005CDB], ah
0072BF96   CF                     iret
0072BF97   44                     inc     esp
0072BF98   008D4000A0BF           add     [ebp+$BFA00040], cl
0072BF9E   7200                   jb      0072BFA0
0072BFA0   07                     pop     es
0072BFA1   155446726D             adc     eax, $6D724654
0072BFA6   52                     push    edx
0072BFA7   656C                   insb
0072BFA9   61                     popa
0072BFAA   746F                   jz      0072C01B
0072BFAC   7269                   jb      0072C017
0072BFAE   6F                     outsd
0072BFAF   7355                   jnb     0072C006
0072BFB1   7375                   jnb     0072C028
0072BFB3   61                     popa
0072BFB4   7269                   jb      0072C01F
0072BFB6   6F                     outsd
0072BFB7   1CBD                   sbb     al, $BD
0072BFB9   7200                   jb      0072BFBB
0072BFBB   38B44A005E0007         cmp     [edx+ecx*2+$7005E00], dh
0072BFC2   7265                   jb      0072C029
0072BFC4   6C                     insb
0072BFC5   61                     popa
0072BFC6   746F                   jz      0072C037
0072BFC8   7200                   jb      0072BFCA
0072BFCA   0090558BECA1           add     [eax+$A1EC8B55], dl
0072BFD0   689F7D008B             push    $8B007D9F
0072BFD5   008B406C8B10           add     [ebx+$108B6C40], cl
0072BFDB   FF5258                 call    dword ptr [edx+$58]

* Reference to : TFrmPreview._PROC_0072E820()
|
0072BFDE   E83D280000             call    0072E820
0072BFE3   5D                     pop     ebp
0072BFE4   C3                     ret

0072BFE5   8D4000                 lea     eax, [eax+$00]
0072BFE8   55                     push    ebp
0072BFE9   8BEC                   mov     ebp, esp
0072BFEB   B907000000             mov     ecx, $00000007
0072BFF0   6A00                   push    $00
0072BFF2   6A00                   push    $00
0072BFF4   49                     dec     ecx
0072BFF5   75F9                   jnz     0072BFF0
0072BFF7   51                     push    ecx
0072BFF8   53                     push    ebx
0072BFF9   8945FC                 mov     [ebp-$04], eax
0072BFFC   33C0                   xor     eax, eax
0072BFFE   55                     push    ebp
0072BFFF   6858C17200             push    $0072C158

***** TRY
|
0072C004   64FF30                 push    dword ptr fs:[eax]
0072C007   648920                 mov     fs:[eax], esp
0072C00A   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072C00F   8B00                   mov     eax, [eax]
0072C011   8B4074                 mov     eax, [eax+$74]
0072C014   8B55FC                 mov     edx, [ebp-$04]
0072C017   89903C010000           mov     [eax+$013C], edx

* Possible String Reference to: 'UãÏ3…QQQQSãÿ3¿UhB…r'
|
0072C01D   C78038010000A4C87200   mov     dword ptr [eax+$0138], $0072C8A4
0072C027   8D45EC                 lea     eax, [ebp-$14]
0072C02A   50                     push    eax
0072C02B   8D45E8                 lea     eax, [ebp-$18]
0072C02E   50                     push    eax
0072C02F   6A00                   push    $00
0072C031   8D45E4                 lea     eax, [ebp-$1C]
0072C034   50                     push    eax
0072C035   A1A4AF7D00             mov     eax, dword ptr [$007DAFA4]
0072C03A   8B00                   mov     eax, [eax]
0072C03C   33C9                   xor     ecx, ecx
0072C03E   BAF7270000             mov     edx, $000027F7

|
0072C043   E848370800             call    007AF790
0072C048   8B45E4                 mov     eax, [ebp-$1C]
0072C04B   B901000000             mov     ecx, $00000001
0072C050   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrCopy;
|
0072C055   E86299CDFF             call    004059BC
0072C05A   8B45E8                 mov     eax, [ebp-$18]
0072C05D   BA6CC17200             mov     edx, $0072C16C

* Reference to: System.@LStrCmp;
|
0072C062   E84198CDFF             call    004058A8
0072C067   0F94C0                 setz    al
0072C06A   50                     push    eax
0072C06B   8D45D4                 lea     eax, [ebp-$2C]
0072C06E   33D2                   xor     edx, edx

* Reference to: Variants.@VarFromBool(TVarData;TVarData;Boolean);
|
0072C070   E8EBCBCEFF             call    00418C60
0072C075   8D45D4                 lea     eax, [ebp-$2C]
0072C078   50                     push    eax
0072C079   8D45C4                 lea     eax, [ebp-$3C]
0072C07C   B201                   mov     dl, $01

* Reference to: Variants.@VarFromBool(TVarData;TVarData;Boolean);
|
0072C07E   E8DDCBCEFF             call    00418C60
0072C083   8D55C4                 lea     edx, [ebp-$3C]
0072C086   59                     pop     ecx
0072C087   58                     pop     eax

|
0072C088   E8DF420700             call    007A036C
0072C08D   8D45EC                 lea     eax, [ebp-$14]

* Reference to: Variants.@VarToBool(TVarData;TVarData):LongBool;
|
0072C090   E80BA6CEFF             call    004166A0
0072C095   8BD8                   mov     ebx, eax
0072C097   8B45FC                 mov     eax, [ebp-$04]
0072C09A   8B8008030000           mov     eax, [eax+$0308]
0072C0A0   8BD3                   mov     edx, ebx
0072C0A2   8B08                   mov     ecx, [eax]
0072C0A4   FF5164                 call    dword ptr [ecx+$64]
0072C0A7   8B45FC                 mov     eax, [ebp-$04]
0072C0AA   8B8004030000           mov     eax, [eax+$0304]
0072C0B0   8BD3                   mov     edx, ebx
0072C0B2   8B08                   mov     ecx, [eax]
0072C0B4   FF5164                 call    dword ptr [ecx+$64]
0072C0B7   8B45FC                 mov     eax, [ebp-$04]

* Reference to control btFechar : N.A.
|
0072C0BA   8B8000030000           mov     eax, [eax+$0300]
0072C0C0   8BD3                   mov     edx, ebx
0072C0C2   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TN.A..OFFS_64
|
0072C0C4   FF5164                 call    dword ptr [ecx+$64]
0072C0C7   8B45FC                 mov     eax, [ebp-$04]

* Reference to control meTexto : N.A.
|
0072C0CA   8B80FC020000           mov     eax, [eax+$02FC]
0072C0D0   8BD3                   mov     edx, ebx

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0072C0D2   E81575D6FF             call    004935EC
0072C0D7   8B1578AF7D00           mov     edx, [$007DAF78]
0072C0DD   8A12                   mov     dl, byte ptr [edx]
0072C0DF   8B45FC                 mov     eax, [ebp-$04]
0072C0E2   8B801C030000           mov     eax, [eax+$031C]
0072C0E8   8B08                   mov     ecx, [eax]
0072C0EA   FF5164                 call    dword ptr [ecx+$64]
0072C0ED   33C0                   xor     eax, eax
0072C0EF   55                     push    ebp
0072C0F0   681BC17200             push    $0072C11B

***** TRY
|
0072C0F5   64FF30                 push    dword ptr fs:[eax]
0072C0F8   648920                 mov     fs:[eax], esp
0072C0FB   33C0                   xor     eax, eax
0072C0FD   5A                     pop     edx
0072C0FE   59                     pop     ecx
0072C0FF   59                     pop     ecx
0072C100   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072C103   6822C17200             push    $0072C122
0072C108   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072C10D   8B00                   mov     eax, [eax]
0072C10F   8B5074                 mov     edx, [eax+$74]
0072C112   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TFrmRelatoriosUsuario.TbRelatAfterScroll()
|
0072C115   E88A070000             call    0072C8A4
0072C11A   C3                     ret


* Reference to: System.@HandleFinally;
|
0072C11B   E9188CCDFF             jmp     00404D38
0072C120   EBE6                   jmp     0072C108

****** END
|
0072C122   33C0                   xor     eax, eax
0072C124   5A                     pop     edx
0072C125   59                     pop     ecx
0072C126   59                     pop     ecx
0072C127   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072C12A   685FC17200             push    $0072C15F
0072C12F   8D45C4                 lea     eax, [ebp-$3C]

* Reference to object Variant
|
0072C132   8B1524114000           mov     edx, [$00401124]
0072C138   B902000000             mov     ecx, $00000002

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
0072C13D   E85A9FCDFF             call    0040609C
0072C142   8D45E4                 lea     eax, [ebp-$1C]
0072C145   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072C14A   E87193CDFF             call    004054C0
0072C14F   8D45EC                 lea     eax, [ebp-$14]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0072C152   E82184CEFF             call    00414578
0072C157   C3                     ret

*)
end;

end.