unit desconto;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ToolEdit, CurrEdit, ExtCtrls,
  Buttons;
  
type
  TFrmDesconto=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    nbDesconto: TNotebook;
    Panel2: TPanel;
    Panel3: TPanel;
    Label5: TLabel;
    EdVlrCupom: TCurrencyEdit;
    Panel4: TPanel;
    Panel5: TPanel;
    Label6: TLabel;
    EdVlrItem: TCurrencyEdit;
    pnCupomPorc: TPanel;
    Label10: TLabel;
    EdPorcDC: TCurrencyEdit;
    pnCupomVlr: TPanel;
    Label9: TLabel;
    EdValorDC: TCurrencyEdit;
    Label3: TLabel;
    EdNovoValor: TCurrencyEdit;
    EdValorAtual: TCurrencyEdit;
    Label4: TLabel;
    sbCupomPorc: TSpeedButton;
    sbCupomValor: TSpeedButton;
    sbItemPorc: TSpeedButton;
    sbItemValor: TSpeedButton;
    pnItemVlr: TPanel;
    Label1: TLabel;
    EdValorDI: TCurrencyEdit;
    pnItemPorc: TPanel;
    Label2: TLabel;
    EdPorcDI: TCurrencyEdit;
    Bevel1: TBevel;
    EdValorDesconto: TCurrencyEdit;
    Label7: TLabel;
    procedure sbCupomPorcClick(Sender : TObject);
    procedure sbCupomValorClick(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sbItemPorcClick(Sender : TObject);
    procedure sbItemValorClick(Sender : TObject);
    procedure EdValorDCChange(Sender : TObject);
    procedure EdPorcDIChange(Sender : TObject);
    procedure EdValorDIChange(Sender : TObject);
    procedure EdPorcDCChange(Sender : TObject);
    procedure EdPorcDCKeyPress(Sender : TObject);
    procedure EdValorDIKeyPress(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure _PROC_00665F69(Sender : TObject);
    procedure _PROC_00666191(Sender : TObject);
    procedure _PROC_0066639D(Sender : TObject);
    procedure _PROC_00666C7D(Sender : TObject);
    procedure _PROC_00666E35(Sender : TObject);
    procedure _PROC_00666E78(Sender : TObject);
    procedure _PROC_00666E80(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmDesconto: TFrmDesconto;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmDesconto.sbCupomPorcClick(Sender : TObject);
begin
(*
006663EC   55                     push    ebp
006663ED   8BEC                   mov     ebp, esp
006663EF   53                     push    ebx
006663F0   8BD8                   mov     ebx, eax
006663F2   33C0                   xor     eax, eax
006663F4   8905ACE27D00           mov     [$007DE2AC], eax
006663FA   8905B0E27D00           mov     [$007DE2B0], eax
00666400   668905B4E27D00         mov     [$007DE2B4], ax
00666407   33C0                   xor     eax, eax
00666409   8905B8E27D00           mov     [$007DE2B8], eax
0066640F   8905BCE27D00           mov     [$007DE2BC], eax
00666415   668905C0E27D00         mov     [$007DE2C0], ax
0066641C   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'porc'
|
00666421   BAC4646600             mov     edx, $006664C4

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666426   E8C5F0D9FF             call    004054F0
0066642B   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
0066642D   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666433   E8B4D1E2FF             call    004935EC
00666438   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
0066643D   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666443   E8F0C9E2FF             call    00492E38
00666448   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066644A   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666450   E897D1E2FF             call    004935EC
00666455   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066645A   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666460   E8D3C9E2FF             call    00492E38

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
00666465   8B832C030000           mov     eax, [ebx+$032C]
0066646B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
0066646D   FF92C4000000           call    dword ptr [edx+$00C4]
00666473   6805400000             push    $00004005
00666478   68000000C8             push    $C8000000
0066647D   6A00                   push    $00

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
0066647F   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666485   E8D62DFCFF             call    00629260
0066648A   6A00                   push    $00
0066648C   6A00                   push    $00
0066648E   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDesconto : TCurrencyEdit
|
00666490   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666496   E8252DFCFF             call    006291C0

* Reference to control TFrmDesconto.EdValorAtual : TCurrencyEdit
|
0066649B   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
006664A1   E8822CFCFF             call    00629128
006664A6   83C4F4                 add     esp, -$0C
006664A9   DB3C24                 fstp    tbyte ptr [esp]
006664AC   9B                     wait

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
006664AD   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006664B3   E8082DFCFF             call    006291C0
006664B8   5B                     pop     ebx
006664B9   5D                     pop     ebp
006664BA   C3                     ret

*)
end;

procedure TFrmDesconto.sbCupomValorClick(Sender : TObject);
begin
(*
006664CC   55                     push    ebp
006664CD   8BEC                   mov     ebp, esp
006664CF   53                     push    ebx
006664D0   8BD8                   mov     ebx, eax
006664D2   33C0                   xor     eax, eax
006664D4   8905ACE27D00           mov     [$007DE2AC], eax
006664DA   8905B0E27D00           mov     [$007DE2B0], eax
006664E0   668905B4E27D00         mov     [$007DE2B4], ax
006664E7   33C0                   xor     eax, eax
006664E9   8905B8E27D00           mov     [$007DE2B8], eax
006664EF   8905BCE27D00           mov     [$007DE2BC], eax
006664F5   668905C0E27D00         mov     [$007DE2C0], ax
006664FC   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'valor'
|
00666501   BAA8656600             mov     edx, $006665A8

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666506   E8E5EFD9FF             call    004054F0
0066650B   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066650D   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666513   E8D4D0E2FF             call    004935EC
00666518   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066651D   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666523   E810C9E2FF             call    00492E38
00666528   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
0066652A   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666530   E8B7D0E2FF             call    004935EC
00666535   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
0066653A   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666540   E8F3C8E2FF             call    00492E38

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666545   8B8338030000           mov     eax, [ebx+$0338]
0066654B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
0066654D   FF92C4000000           call    dword ptr [edx+$00C4]
00666553   A150B67D00             mov     eax, dword ptr [$007DB650]
00666558   668B5008               mov     dx, word ptr [eax+$08]
0066655C   52                     push    edx
0066655D   FF7004                 push    dword ptr [eax+$04]
00666560   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666562   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666568   E8F32CFCFF             call    00629260
0066656D   6A00                   push    $00
0066656F   6A00                   push    $00
00666571   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDesconto : TCurrencyEdit
|
00666573   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666579   E8422CFCFF             call    006291C0

* Reference to control TFrmDesconto.EdValorAtual : TCurrencyEdit
|
0066657E   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666584   E89F2BFCFF             call    00629128
00666589   83C4F4                 add     esp, -$0C
0066658C   DB3C24                 fstp    tbyte ptr [esp]
0066658F   9B                     wait

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
00666590   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666596   E8252CFCFF             call    006291C0
0066659B   5B                     pop     ebx
0066659C   5D                     pop     ebp
0066659D   C3                     ret

*)
end;

procedure TFrmDesconto.FormCreate(Sender : TObject);
begin
(*
006665B0   55                     push    ebp
006665B1   8BEC                   mov     ebp, esp
006665B3   53                     push    ebx
006665B4   8BD8                   mov     ebx, eax
006665B6   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
006665BB   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006665C1   E872C8E2FF             call    00492E38
006665C6   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
006665CB   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006665D1   E862C8E2FF             call    00492E38
006665D6   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
006665DB   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006665E1   E852C8E2FF             call    00492E38
006665E6   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
006665EB   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
006665F1   E842C8E2FF             call    00492E38
006665F6   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmDesconto.sbCupomPorc : TSpeedButton
|
006665FB   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666601   E832C8E2FF             call    00492E38
00666606   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmDesconto.sbCupomValor : TSpeedButton
|
0066660B   8B8350030000           mov     eax, [ebx+$0350]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666611   E822C8E2FF             call    00492E38
00666616   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmDesconto.sbItemPorc : TSpeedButton
|
0066661B   8B8354030000           mov     eax, [ebx+$0354]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666621   E812C8E2FF             call    00492E38
00666626   BA4A000000             mov     edx, $0000004A

* Reference to control TFrmDesconto.sbItemValor : TSpeedButton
|
0066662B   8B8358030000           mov     eax, [ebx+$0358]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666631   E802C8E2FF             call    00492E38
00666636   6805400000             push    $00004005
0066663B   68000000C8             push    $C8000000
00666640   6A00                   push    $00

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
00666642   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666648   E8132CFCFF             call    00629260
0066664D   6805400000             push    $00004005
00666652   68000000C8             push    $C8000000
00666657   6A00                   push    $00

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
00666659   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629260()
|
0066665F   E8FC2BFCFF             call    00629260
00666664   A124AC7D00             mov     eax, dword ptr [$007DAC24]
00666669   668B5008               mov     dx, word ptr [eax+$08]
0066666D   52                     push    edx
0066666E   FF7004                 push    dword ptr [eax+$04]
00666671   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
00666673   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666679   E8E22BFCFF             call    00629260
0066667E   A150B67D00             mov     eax, dword ptr [$007DB650]
00666683   668B5008               mov     dx, word ptr [eax+$08]
00666687   52                     push    edx
00666688   FF7004                 push    dword ptr [eax+$04]
0066668B   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
0066668D   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666693   E8C82BFCFF             call    00629260
00666698   5B                     pop     ebx
00666699   5D                     pop     ebp
0066669A   C3                     ret

*)
end;

procedure TFrmDesconto.FormShow(Sender : TObject);
begin
(*
0066669C   55                     push    ebp
0066669D   8BEC                   mov     ebp, esp
0066669F   53                     push    ebx
006666A0   56                     push    esi
006666A1   8BD8                   mov     ebx, eax
006666A3   6A00                   push    $00
006666A5   6A00                   push    $00
006666A7   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
006666A9   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006666AF   E80C2BFCFF             call    006291C0
006666B4   6A00                   push    $00
006666B6   6A00                   push    $00
006666B8   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
006666BA   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006666C0   E8FB2AFCFF             call    006291C0
006666C5   6A00                   push    $00
006666C7   6A00                   push    $00
006666C9   6A00                   push    $00

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
006666CB   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006666D1   E8EA2AFCFF             call    006291C0
006666D6   6A00                   push    $00
006666D8   6A00                   push    $00
006666DA   6A00                   push    $00

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
006666DC   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006666E2   E8D92AFCFF             call    006291C0
006666E7   A1C4887D00             mov     eax, dword ptr [$007D88C4]

* Possible String Reference to: 'item'
|
006666EC   BA78696600             mov     edx, $00666978

* Reference to: System.@LStrCmp;
|
006666F1   E8B2F1D9FF             call    004058A8
006666F6   0F85F9000000           jnz     006667F5
006666FC   B8C4887D00             mov     eax, $007D88C4

* Possible String Reference to: 'item'
|
00666701   BA78696600             mov     edx, $00666978

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666706   E8E5EDD9FF             call    004054F0
0066670B   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'porc'
|
00666710   BA88696600             mov     edx, $00666988

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666715   E8D6EDD9FF             call    004054F0
0066671A   33C0                   xor     eax, eax
0066671C   8905ACE27D00           mov     [$007DE2AC], eax
00666722   8905B0E27D00           mov     [$007DE2B0], eax
00666728   668905B4E27D00         mov     [$007DE2B4], ax
0066672F   33C0                   xor     eax, eax
00666731   8905B8E27D00           mov     [$007DE2B8], eax
00666737   8905BCE27D00           mov     [$007DE2BC], eax
0066673D   668905C0E27D00         mov     [$007DE2C0], ax
00666744   BA01000000             mov     edx, $00000001

* Reference to control TFrmDesconto.nbDesconto : TNotebook
|
00666749   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: ExtCtrls.TNotebook.SetPageIndex(TNotebook;Integer);
|
0066674F   E8F02EDEFF             call    00449644
00666754   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbItemPorc : TSpeedButton
|
00666756   8B8354030000           mov     eax, [ebx+$0354]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
0066675C   E86B88DEFF             call    0044EFCC

* Reference to control TFrmDesconto.sbItemPorc : TSpeedButton
|
00666761   8BB354030000           mov     esi, [ebx+$0354]
00666767   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
00666769   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
0066676F   FF9620010000           call    dword ptr [esi+$0120]
00666775   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
00666777   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0066677D   E86ACEE2FF             call    004935EC

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
00666782   8B8370030000           mov     eax, [ebx+$0370]
00666788   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
0066678A   FF92C4000000           call    dword ptr [edx+$00C4]
00666790   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
00666792   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666798   E84FCEE2FF             call    004935EC
0066679D   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006667A2   668B5008               mov     dx, word ptr [eax+$08]
006667A6   52                     push    edx
006667A7   FF7004                 push    dword ptr [eax+$04]
006667AA   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdVlrItem : TCurrencyEdit
|
006667AC   8B8320030000           mov     eax, [ebx+$0320]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006667B2   E8092AFCFF             call    006291C0
006667B7   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006667BC   668B5008               mov     dx, word ptr [eax+$08]
006667C0   52                     push    edx
006667C1   FF7004                 push    dword ptr [eax+$04]
006667C4   FF30                   push    dword ptr [eax]
006667C6   A124AC7D00             mov     eax, dword ptr [$007DAC24]
006667CB   668B5008               mov     dx, word ptr [eax+$08]
006667CF   52                     push    edx
006667D0   FF7004                 push    dword ptr [eax+$04]
006667D3   FF30                   push    dword ptr [eax]
006667D5   668B05C0E27D00         mov     ax, word ptr [$007DE2C0]
006667DC   50                     push    eax
006667DD   FF35BCE27D00           push    dword ptr [$007DE2BC]
006667E3   FF35B8E27D00           push    dword ptr [$007DE2B8]
006667E9   8BC3                   mov     eax, ebx

|
006667EB   E8ACFBFFFF             call    0066639C
006667F0   E974010000             jmp     00666969
006667F5   A1C4887D00             mov     eax, dword ptr [$007D88C4]

* Possible String Reference to: 'cupom'
|
006667FA   BA98696600             mov     edx, $00666998

* Reference to: System.@LStrCmp;
|
006667FF   E8A4F0D9FF             call    004058A8
00666804   0F855F010000           jnz     00666969
0066680A   B8C4887D00             mov     eax, $007D88C4

* Possible String Reference to: 'cupom'
|
0066680F   BA98696600             mov     edx, $00666998

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666814   E8D7ECD9FF             call    004054F0
00666819   33C0                   xor     eax, eax
0066681B   8905ACE27D00           mov     [$007DE2AC], eax
00666821   8905B0E27D00           mov     [$007DE2B0], eax
00666827   668905B4E27D00         mov     [$007DE2B4], ax
0066682E   33C0                   xor     eax, eax
00666830   8905B8E27D00           mov     [$007DE2B8], eax
00666836   8905BCE27D00           mov     [$007DE2BC], eax
0066683C   668905C0E27D00         mov     [$007DE2C0], ax
00666843   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.nbDesconto : TNotebook
|
00666845   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: ExtCtrls.TNotebook.SetPageIndex(TNotebook;Integer);
|
0066684B   E8F42DDEFF             call    00449644
00666850   A154B17D00             mov     eax, dword ptr [$007DB154]
00666855   833800                 cmp     dword ptr [eax], +$00
00666858   755A                   jnz     006668B4
0066685A   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'porc'
|
0066685F   BA88696600             mov     edx, $00666988

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666864   E887ECD9FF             call    004054F0
00666869   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbCupomPorc : TSpeedButton
|
0066686B   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
00666871   E85687DEFF             call    0044EFCC

* Reference to control TFrmDesconto.sbCupomPorc : TSpeedButton
|
00666876   8BB34C030000           mov     esi, [ebx+$034C]
0066687C   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
0066687E   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
00666884   FF9620010000           call    dword ptr [esi+$0120]
0066688A   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066688C   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666892   E855CDE2FF             call    004935EC

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
00666897   8B832C030000           mov     eax, [ebx+$032C]
0066689D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
0066689F   FF92C4000000           call    dword ptr [edx+$00C4]
006668A5   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
006668A7   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006668AD   E83ACDE2FF             call    004935EC
006668B2   EB62                   jmp     00666916
006668B4   A154B17D00             mov     eax, dword ptr [$007DB154]
006668B9   833801                 cmp     dword ptr [eax], +$01
006668BC   7558                   jnz     00666916
006668BE   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'valor'
|
006668C3   BAA8696600             mov     edx, $006669A8

* Reference to: System.@LStrAsg(void;void;void;void);
|
006668C8   E823ECD9FF             call    004054F0
006668CD   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbCupomValor : TSpeedButton
|
006668CF   8B8350030000           mov     eax, [ebx+$0350]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
006668D5   E8F286DEFF             call    0044EFCC

* Reference to control TFrmDesconto.sbCupomValor : TSpeedButton
|
006668DA   8BB350030000           mov     esi, [ebx+$0350]
006668E0   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
006668E2   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
006668E8   FF9620010000           call    dword ptr [esi+$0120]
006668EE   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnCupomVlr : TPanel
|
006668F0   8B8330030000           mov     eax, [ebx+$0330]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006668F6   E8F1CCE2FF             call    004935EC

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
006668FB   8B8338030000           mov     eax, [ebx+$0338]
00666901   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00666903   FF92C4000000           call    dword ptr [edx+$00C4]
00666909   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnCupomPorc : TPanel
|
0066690B   8B8324030000           mov     eax, [ebx+$0324]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666911   E8D6CCE2FF             call    004935EC
00666916   A150B67D00             mov     eax, dword ptr [$007DB650]
0066691B   668B5008               mov     dx, word ptr [eax+$08]
0066691F   52                     push    edx
00666920   FF7004                 push    dword ptr [eax+$04]
00666923   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdVlrCupom : TCurrencyEdit
|
00666925   8B8310030000           mov     eax, [ebx+$0310]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
0066692B   E89028FCFF             call    006291C0
00666930   A150B67D00             mov     eax, dword ptr [$007DB650]
00666935   668B5008               mov     dx, word ptr [eax+$08]
00666939   52                     push    edx
0066693A   FF7004                 push    dword ptr [eax+$04]
0066693D   FF30                   push    dword ptr [eax]
0066693F   A150B67D00             mov     eax, dword ptr [$007DB650]
00666944   668B5008               mov     dx, word ptr [eax+$08]
00666948   52                     push    edx
00666949   FF7004                 push    dword ptr [eax+$04]
0066694C   FF30                   push    dword ptr [eax]
0066694E   668B05C0E27D00         mov     ax, word ptr [$007DE2C0]
00666955   50                     push    eax
00666956   FF35BCE27D00           push    dword ptr [$007DE2BC]
0066695C   FF35B8E27D00           push    dword ptr [$007DE2B8]
00666962   8BC3                   mov     eax, ebx

|
00666964   E833FAFFFF             call    0066639C
00666969   5E                     pop     esi
0066696A   5B                     pop     ebx
0066696B   5D                     pop     ebp
0066696C   C3                     ret

*)
end;

procedure TFrmDesconto.sbItemPorcClick(Sender : TObject);
begin
(*
006669B0   55                     push    ebp
006669B1   8BEC                   mov     ebp, esp
006669B3   53                     push    ebx
006669B4   8BD8                   mov     ebx, eax
006669B6   33C0                   xor     eax, eax
006669B8   8905ACE27D00           mov     [$007DE2AC], eax
006669BE   8905B0E27D00           mov     [$007DE2B0], eax
006669C4   668905B4E27D00         mov     [$007DE2B4], ax
006669CB   33C0                   xor     eax, eax
006669CD   8905B8E27D00           mov     [$007DE2B8], eax
006669D3   8905BCE27D00           mov     [$007DE2BC], eax
006669D9   668905C0E27D00         mov     [$007DE2C0], ax
006669E0   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'porc'
|
006669E5   BA706A6600             mov     edx, $00666A70

* Reference to: System.@LStrAsg(void;void;void;void);
|
006669EA   E801EBD9FF             call    004054F0
006669EF   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
006669F1   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
006669F7   E8F0CBE2FF             call    004935EC
006669FC   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
00666A01   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666A07   E82CC4E2FF             call    00492E38
00666A0C   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
00666A0E   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666A14   E8D3CBE2FF             call    004935EC
00666A19   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
00666A1E   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666A24   E80FC4E2FF             call    00492E38

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
00666A29   8B8370030000           mov     eax, [ebx+$0370]
00666A2F   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00666A31   FF92C4000000           call    dword ptr [edx+$00C4]
00666A37   6A00                   push    $00
00666A39   6A00                   push    $00
00666A3B   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDesconto : TCurrencyEdit
|
00666A3D   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666A43   E87827FCFF             call    006291C0

* Reference to control TFrmDesconto.EdValorAtual : TCurrencyEdit
|
00666A48   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666A4E   E8D526FCFF             call    00629128
00666A53   83C4F4                 add     esp, -$0C
00666A56   DB3C24                 fstp    tbyte ptr [esp]
00666A59   9B                     wait

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
00666A5A   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666A60   E85B27FCFF             call    006291C0
00666A65   5B                     pop     ebx
00666A66   5D                     pop     ebp
00666A67   C3                     ret

*)
end;

procedure TFrmDesconto.sbItemValorClick(Sender : TObject);
begin
(*
00666A78   55                     push    ebp
00666A79   8BEC                   mov     ebp, esp
00666A7B   53                     push    ebx
00666A7C   8BD8                   mov     ebx, eax
00666A7E   33C0                   xor     eax, eax
00666A80   8905ACE27D00           mov     [$007DE2AC], eax
00666A86   8905B0E27D00           mov     [$007DE2B0], eax
00666A8C   668905B4E27D00         mov     [$007DE2B4], ax
00666A93   33C0                   xor     eax, eax
00666A95   8905B8E27D00           mov     [$007DE2B8], eax
00666A9B   8905BCE27D00           mov     [$007DE2BC], eax
00666AA1   668905C0E27D00         mov     [$007DE2C0], ax
00666AA8   B8C8887D00             mov     eax, $007D88C8

* Possible String Reference to: 'valor'
|
00666AAD   BA546B6600             mov     edx, $00666B54

* Reference to: System.@LStrAsg(void;void;void;void);
|
00666AB2   E839EAD9FF             call    004054F0
00666AB7   33D2                   xor     edx, edx

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
00666AB9   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666ABF   E828CBE2FF             call    004935EC
00666AC4   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemPorc : TPanel
|
00666AC9   8B8368030000           mov     eax, [ebx+$0368]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666ACF   E864C3E2FF             call    00492E38
00666AD4   B201                   mov     dl, $01

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
00666AD6   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00666ADC   E80BCBE2FF             call    004935EC
00666AE1   BA6F000000             mov     edx, $0000006F

* Reference to control TFrmDesconto.pnItemVlr : TPanel
|
00666AE6   8B835C030000           mov     eax, [ebx+$035C]

* Reference to: Controls.TControl.SetTop(TControl;Integer);
|
00666AEC   E847C3E2FF             call    00492E38

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
00666AF1   8B8364030000           mov     eax, [ebx+$0364]
00666AF7   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00666AF9   FF92C4000000           call    dword ptr [edx+$00C4]
00666AFF   A124AC7D00             mov     eax, dword ptr [$007DAC24]
00666B04   668B5008               mov     dx, word ptr [eax+$08]
00666B08   52                     push    edx
00666B09   FF7004                 push    dword ptr [eax+$04]
00666B0C   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
00666B0E   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629260()
|
00666B14   E84727FCFF             call    00629260
00666B19   6A00                   push    $00
00666B1B   6A00                   push    $00
00666B1D   6A00                   push    $00

* Reference to control TFrmDesconto.EdValorDesconto : TCurrencyEdit
|
00666B1F   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666B25   E89626FCFF             call    006291C0

* Reference to control TFrmDesconto.EdValorAtual : TCurrencyEdit
|
00666B2A   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666B30   E8F325FCFF             call    00629128
00666B35   83C4F4                 add     esp, -$0C
00666B38   DB3C24                 fstp    tbyte ptr [esp]
00666B3B   9B                     wait

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
00666B3C   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00666B42   E87926FCFF             call    006291C0
00666B47   5B                     pop     ebx
00666B48   5D                     pop     ebp
00666B49   C3                     ret

*)
end;

procedure TFrmDesconto.EdValorDCChange(Sender : TObject);
begin
(*
00666C7C   55                     push    ebp
00666C7D   8BEC                   mov     ebp, esp
00666C7F   53                     push    ebx
00666C80   8BD8                   mov     ebx, eax

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666C82   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666C88   E89B24FCFF             call    00629128
00666C8D   A150B67D00             mov     eax, dword ptr [$007DB650]
00666C92   DB28                   fld     tbyte ptr [eax]
00666C94   DED9                   fcompp
00666C96   DFE0                   fstsw   ax
00666C98   9E                     sahf
00666C99   722D                   jb      00666CC8
00666C9B   A150B67D00             mov     eax, dword ptr [$007DB650]
00666CA0   668B5008               mov     dx, word ptr [eax+$08]
00666CA4   52                     push    edx
00666CA5   FF7004                 push    dword ptr [eax+$04]
00666CA8   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666CAA   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666CB0   E87324FCFF             call    00629128
00666CB5   83C4F4                 add     esp, -$0C
00666CB8   DB3C24                 fstp    tbyte ptr [esp]
00666CBB   9B                     wait

* Possible String Reference to: 'valor'
|
00666CBC   BAD46C6600             mov     edx, $00666CD4
00666CC1   8BC3                   mov     eax, ebx

|
00666CC3   E8A0F2FFFF             call    00665F68
00666CC8   5B                     pop     ebx
00666CC9   5D                     pop     ebp
00666CCA   C3                     ret

*)
end;

procedure TFrmDesconto.EdPorcDIChange(Sender : TObject);
begin
(*
00666B5C   55                     push    ebp
00666B5D   8BEC                   mov     ebp, esp
00666B5F   53                     push    ebx
00666B60   8BD8                   mov     ebx, eax

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
00666B62   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666B68   E8BB25FCFF             call    00629128
00666B6D   D81DA86B6600           fcomp   dword ptr [$00666BA8]
00666B73   DFE0                   fstsw   ax
00666B75   9E                     sahf
00666B76   772D                   jnbe    00666BA5
00666B78   A124AC7D00             mov     eax, dword ptr [$007DAC24]
00666B7D   668B5008               mov     dx, word ptr [eax+$08]
00666B81   52                     push    edx
00666B82   FF7004                 push    dword ptr [eax+$04]
00666B85   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdPorcDI : TCurrencyEdit
|
00666B87   8B8370030000           mov     eax, [ebx+$0370]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666B8D   E89625FCFF             call    00629128
00666B92   83C4F4                 add     esp, -$0C
00666B95   DB3C24                 fstp    tbyte ptr [esp]
00666B98   9B                     wait

* Possible String Reference to: 'porc'
|
00666B99   BAB46B6600             mov     edx, $00666BB4
00666B9E   8BC3                   mov     eax, ebx

|
00666BA0   E8EBF5FFFF             call    00666190
00666BA5   5B                     pop     ebx
00666BA6   5D                     pop     ebp
00666BA7   C3                     ret

*)
end;

procedure TFrmDesconto.EdValorDIChange(Sender : TObject);
begin
(*
00666BBC   55                     push    ebp
00666BBD   8BEC                   mov     ebp, esp
00666BBF   53                     push    ebx
00666BC0   8BD8                   mov     ebx, eax

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
00666BC2   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666BC8   E85B25FCFF             call    00629128
00666BCD   A124AC7D00             mov     eax, dword ptr [$007DAC24]
00666BD2   DB28                   fld     tbyte ptr [eax]
00666BD4   DED9                   fcompp
00666BD6   DFE0                   fstsw   ax
00666BD8   9E                     sahf
00666BD9   722D                   jb      00666C08
00666BDB   A124AC7D00             mov     eax, dword ptr [$007DAC24]
00666BE0   668B5008               mov     dx, word ptr [eax+$08]
00666BE4   52                     push    edx
00666BE5   FF7004                 push    dword ptr [eax+$04]
00666BE8   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDI : TCurrencyEdit
|
00666BEA   8B8364030000           mov     eax, [ebx+$0364]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666BF0   E83325FCFF             call    00629128
00666BF5   83C4F4                 add     esp, -$0C
00666BF8   DB3C24                 fstp    tbyte ptr [esp]
00666BFB   9B                     wait

* Possible String Reference to: 'valor'
|
00666BFC   BA146C6600             mov     edx, $00666C14
00666C01   8BC3                   mov     eax, ebx

|
00666C03   E888F5FFFF             call    00666190
00666C08   5B                     pop     ebx
00666C09   5D                     pop     ebp
00666C0A   C3                     ret

*)
end;

procedure TFrmDesconto.EdPorcDCChange(Sender : TObject);
begin
(*
00666C1C   55                     push    ebp
00666C1D   8BEC                   mov     ebp, esp
00666C1F   53                     push    ebx
00666C20   8BD8                   mov     ebx, eax

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
00666C22   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666C28   E8FB24FCFF             call    00629128
00666C2D   D81D686C6600           fcomp   dword ptr [$00666C68]
00666C33   DFE0                   fstsw   ax
00666C35   9E                     sahf
00666C36   772D                   jnbe    00666C65
00666C38   A150B67D00             mov     eax, dword ptr [$007DB650]
00666C3D   668B5008               mov     dx, word ptr [eax+$08]
00666C41   52                     push    edx
00666C42   FF7004                 push    dword ptr [eax+$04]
00666C45   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdPorcDC : TCurrencyEdit
|
00666C47   8B832C030000           mov     eax, [ebx+$032C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666C4D   E8D624FCFF             call    00629128
00666C52   83C4F4                 add     esp, -$0C
00666C55   DB3C24                 fstp    tbyte ptr [esp]
00666C58   9B                     wait

* Possible String Reference to: 'porc'
|
00666C59   BA746C6600             mov     edx, $00666C74
00666C5E   8BC3                   mov     eax, ebx

|
00666C60   E803F3FFFF             call    00665F68
00666C65   5B                     pop     ebx
00666C66   5D                     pop     ebp
00666C67   C3                     ret

*)
end;

procedure TFrmDesconto.EdPorcDCKeyPress(Sender : TObject);
begin
(*
00666CDC   55                     push    ebp
00666CDD   8BEC                   mov     ebp, esp
00666CDF   53                     push    ebx
00666CE0   56                     push    esi
00666CE1   8BD8                   mov     ebx, eax
00666CE3   803950                 cmp     byte ptr [ecx], $50
00666CE6   7405                   jz      00666CED
00666CE8   803970                 cmp     byte ptr [ecx], $70
00666CEB   7523                   jnz     00666D10

* Reference to control TFrmDesconto.sbCupomPorc : TSpeedButton
|
00666CED   8BB34C030000           mov     esi, [ebx+$034C]
00666CF3   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
00666CF5   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
00666CFB   FF9620010000           call    dword ptr [esi+$0120]
00666D01   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbCupomPorc : TSpeedButton
|
00666D03   8B834C030000           mov     eax, [ebx+$034C]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
00666D09   E8BE82DEFF             call    0044EFCC
00666D0E   EB35                   jmp     00666D45
00666D10   803956                 cmp     byte ptr [ecx], $56
00666D13   7405                   jz      00666D1A
00666D15   803976                 cmp     byte ptr [ecx], $76
00666D18   7523                   jnz     00666D3D

* Reference to control TFrmDesconto.sbCupomValor : TSpeedButton
|
00666D1A   8BB350030000           mov     esi, [ebx+$0350]
00666D20   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
00666D22   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
00666D28   FF9620010000           call    dword ptr [esi+$0120]
00666D2E   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbCupomValor : TSpeedButton
|
00666D30   8B8350030000           mov     eax, [ebx+$0350]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
00666D36   E89182DEFF             call    0044EFCC
00666D3B   EB08                   jmp     00666D45
00666D3D   80392E                 cmp     byte ptr [ecx], $2E
00666D40   7503                   jnz     00666D45
00666D42   C6012C                 mov     byte ptr [ecx], $2C
00666D45   5E                     pop     esi
00666D46   5B                     pop     ebx
00666D47   5D                     pop     ebp
00666D48   C3                     ret

*)
end;

procedure TFrmDesconto.EdValorDIKeyPress(Sender : TObject);
begin
(*
00666D4C   55                     push    ebp
00666D4D   8BEC                   mov     ebp, esp
00666D4F   53                     push    ebx
00666D50   56                     push    esi
00666D51   8BD8                   mov     ebx, eax
00666D53   803950                 cmp     byte ptr [ecx], $50
00666D56   7405                   jz      00666D5D
00666D58   803970                 cmp     byte ptr [ecx], $70
00666D5B   7523                   jnz     00666D80

* Reference to control TFrmDesconto.sbItemPorc : TSpeedButton
|
00666D5D   8BB354030000           mov     esi, [ebx+$0354]
00666D63   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
00666D65   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
00666D6B   FF9620010000           call    dword ptr [esi+$0120]
00666D71   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbItemPorc : TSpeedButton
|
00666D73   8B8354030000           mov     eax, [ebx+$0354]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
00666D79   E84E82DEFF             call    0044EFCC
00666D7E   EB35                   jmp     00666DB5
00666D80   803956                 cmp     byte ptr [ecx], $56
00666D83   7405                   jz      00666D8A
00666D85   803976                 cmp     byte ptr [ecx], $76
00666D88   7523                   jnz     00666DAD

* Reference to control TFrmDesconto.sbItemValor : TSpeedButton
|
00666D8A   8BB358030000           mov     esi, [ebx+$0358]
00666D90   8BD3                   mov     edx, ebx

* Reference to field TSpeedButton.OFFS_0124
|
00666D92   8B8624010000           mov     eax, [esi+$0124]

* Possible reference to virtual method TSpeedButton.OFFS_0120
|
00666D98   FF9620010000           call    dword ptr [esi+$0120]
00666D9E   B201                   mov     dl, $01

* Reference to control TFrmDesconto.sbItemValor : TSpeedButton
|
00666DA0   8B8358030000           mov     eax, [ebx+$0358]

* Reference to: Buttons.TSpeedButton.SetDown(TSpeedButton;Boolean);
|
00666DA6   E82182DEFF             call    0044EFCC
00666DAB   EB08                   jmp     00666DB5
00666DAD   80392E                 cmp     byte ptr [ecx], $2E
00666DB0   7503                   jnz     00666DB5
00666DB2   C6012C                 mov     byte ptr [ecx], $2C
00666DB5   5E                     pop     esi
00666DB6   5B                     pop     ebx
00666DB7   5D                     pop     ebp
00666DB8   C3                     ret

*)
end;

procedure TFrmDesconto.FormCloseQuery(Sender : TObject);
begin
(*
00666DBC   55                     push    ebp
00666DBD   8BEC                   mov     ebp, esp
00666DBF   53                     push    ebx
00666DC0   56                     push    esi
00666DC1   8BF1                   mov     esi, ecx
00666DC3   8BD8                   mov     ebx, eax

* Reference to field TFrmDesconto.ModalResult : TModalResult
|
00666DC5   83BB4C02000001         cmp     dword ptr [ebx+$024C], +$01
00666DCC   752D                   jnz     00666DFB
00666DCE   A108AF7D00             mov     eax, dword ptr [$007DAF08]
00666DD3   803800                 cmp     byte ptr [eax], $00
00666DD6   7423                   jz      00666DFB

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
00666DD8   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666DDE   E84523FCFF             call    00629128
00666DE3   D81D006E6600           fcomp   dword ptr [$00666E00]
00666DE9   DFE0                   fstsw   ax
00666DEB   9E                     sahf
00666DEC   770D                   jnbe    00666DFB

* Possible String Reference to: 'desconto de 100 % não é permitido!!
|                                !!'
|
00666DEE   B80C6E6600             mov     eax, $00666E0C

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00666DF3   E82CCEDDFF             call    00443C24
00666DF8   C60600                 mov     byte ptr [esi], $00
00666DFB   5E                     pop     esi
00666DFC   5B                     pop     ebx
00666DFD   5D                     pop     ebp
00666DFE   C3                     ret

*)
end;

procedure TFrmDesconto._PROC_00665F69(Sender : TObject);
begin
(*
00665F69   8BEC                   mov     ebp, esp
00665F6B   83C4E0                 add     esp, -$20
00665F6E   53                     push    ebx
00665F6F   33C9                   xor     ecx, ecx
00665F71   894DE4                 mov     [ebp-$1C], ecx
00665F74   894DE0                 mov     [ebp-$20], ecx
00665F77   894DEC                 mov     [ebp-$14], ecx
00665F7A   894DE8                 mov     [ebp-$18], ecx
00665F7D   8955FC                 mov     [ebp-$04], edx
00665F80   8BD8                   mov     ebx, eax
00665F82   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
00665F85   E8C2F9D9FF             call    0040594C
00665F8A   33C0                   xor     eax, eax
00665F8C   55                     push    ebp
00665F8D   683F616600             push    $0066613F

***** TRY
|
00665F92   64FF30                 push    dword ptr fs:[eax]
00665F95   648920                 mov     fs:[eax], esp
00665F98   8B4514                 mov     eax, [ebp+$14]
00665F9B   8945F0                 mov     [ebp-$10], eax
00665F9E   8B4518                 mov     eax, [ebp+$18]
00665FA1   8945F4                 mov     [ebp-$0C], eax
00665FA4   668B451C               mov     ax, word ptr [ebp+$1C]
00665FA8   668945F8               mov     [ebp-$08], ax
00665FAC   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'valor'
|
00665FAF   BA58616600             mov     edx, $00666158

* Reference to: System.@LStrCmp;
|
00665FB4   E8EFF8D9FF             call    004058A8
00665FB9   754C                   jnz     00666007
00665FBB   8B4508                 mov     eax, [ebp+$08]
00665FBE   8905B8E27D00           mov     [$007DE2B8], eax
00665FC4   8B450C                 mov     eax, [ebp+$0C]
00665FC7   8905BCE27D00           mov     [$007DE2BC], eax
00665FCD   668B4510               mov     ax, word ptr [ebp+$10]
00665FD1   668905C0E27D00         mov     [$007DE2C0], ax
00665FD8   DB2DB8E27D00           fld     tbyte ptr [$007DE2B8]
00665FDE   D80D60616600           fmul    dword ptr [$00666160]
00665FE4   DB6D14                 fld     tbyte ptr [ebp+$14]

* Reference to: System.@FSafeDivide;
|
00665FE7   E814D5D9FF             call    00403500
00665FEC   DB3DACE27D00           fstp    tbyte ptr [$007DE2AC]
00665FF2   9B                     wait
00665FF3   DB6D14                 fld     tbyte ptr [ebp+$14]
00665FF6   DB2DB8E27D00           fld     tbyte ptr [$007DE2B8]
00665FFC   DEE9                   fsubp   st(1), st(0)
00665FFE   DB7DF0                 fstp    tbyte ptr [ebp-$10]
00666001   9B                     wait
00666002   E9E4000000             jmp     006660EB
00666007   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'porc'
|
0066600A   BA6C616600             mov     edx, $0066616C

* Reference to: System.@LStrCmp;
|
0066600F   E894F8D9FF             call    004058A8
00666014   0F85D1000000           jnz     006660EB
0066601A   8B4508                 mov     eax, [ebp+$08]
0066601D   8905ACE27D00           mov     [$007DE2AC], eax
00666023   8B450C                 mov     eax, [ebp+$0C]
00666026   8905B0E27D00           mov     [$007DE2B0], eax
0066602C   668B4510               mov     ax, word ptr [ebp+$10]
00666030   668905B4E27D00         mov     [$007DE2B4], ax
00666037   A1D4AB7D00             mov     eax, dword ptr [$007DABD4]
0066603C   803800                 cmp     byte ptr [eax], $00
0066603F   7446                   jz      00666087
00666041   DB2DACE27D00           fld     tbyte ptr [$007DE2AC]
00666047   D90560616600           fld     dword ptr [$00666160]

* Reference to: System.@FSafeDivide;
|
0066604D   E8AED4D9FF             call    00403500
00666052   DB6D14                 fld     tbyte ptr [ebp+$14]
00666055   DEC9                   fmulp   st(1), st(0)
00666057   83C4F4                 add     esp, -$0C
0066605A   DB3C24                 fstp    tbyte ptr [esp]
0066605D   9B                     wait
0066605E   8D55E8                 lea     edx, [ebp-$18]

* Possible String Reference to: '###,###,###,##0.00'
|
00666061   B87C616600             mov     eax, $0066617C

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
00666066   E8D174DAFF             call    0040D53C
0066606B   8B45E8                 mov     eax, [ebp-$18]
0066606E   8D55EC                 lea     edx, [ebp-$14]

* Reference to : TFrmInfoAtu._PROC_007A3884()
|
00666071   E80ED81300             call    007A3884
00666076   8B45EC                 mov     eax, [ebp-$14]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
00666079   E86E75DAFF             call    0040D5EC
0066607E   DB3DB8E27D00           fstp    tbyte ptr [$007DE2B8]
00666084   9B                     wait
00666085   EB55                   jmp     006660DC
00666087   DB2DACE27D00           fld     tbyte ptr [$007DE2AC]
0066608D   D90560616600           fld     dword ptr [$00666160]

* Reference to: System.@FSafeDivide;
|
00666093   E868D4D9FF             call    00403500
00666098   DB6D14                 fld     tbyte ptr [ebp+$14]
0066609B   DEC9                   fmulp   st(1), st(0)
0066609D   83C4F8                 add     esp, -$08
006660A0   DD1C24                 fstp    qword ptr [esp]
006660A3   9B                     wait
006660A4   B802000000             mov     eax, $00000002

* Reference to : TFrmInfoAtu._PROC_007A11C8()
|
006660A9   E81AB11300             call    007A11C8
006660AE   83C4F4                 add     esp, -$0C
006660B1   DB3C24                 fstp    tbyte ptr [esp]
006660B4   9B                     wait
006660B5   8D55E0                 lea     edx, [ebp-$20]

* Possible String Reference to: '###,###,###,##0.00'
|
006660B8   B87C616600             mov     eax, $0066617C

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
006660BD   E87A74DAFF             call    0040D53C
006660C2   8B45E0                 mov     eax, [ebp-$20]
006660C5   8D55E4                 lea     edx, [ebp-$1C]

* Reference to : TFrmInfoAtu._PROC_007A3884()
|
006660C8   E8B7D71300             call    007A3884
006660CD   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
006660D0   E81775DAFF             call    0040D5EC
006660D5   DB3DB8E27D00           fstp    tbyte ptr [$007DE2B8]
006660DB   9B                     wait
006660DC   DB6D14                 fld     tbyte ptr [ebp+$14]
006660DF   DB2DB8E27D00           fld     tbyte ptr [$007DE2B8]
006660E5   DEE9                   fsubp   st(1), st(0)
006660E7   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006660EA   9B                     wait
006660EB   668B451C               mov     ax, word ptr [ebp+$1C]
006660EF   50                     push    eax
006660F0   FF7518                 push    dword ptr [ebp+$18]
006660F3   FF7514                 push    dword ptr [ebp+$14]
006660F6   668B45F8               mov     ax, word ptr [ebp-$08]
006660FA   50                     push    eax
006660FB   FF75F4                 push    dword ptr [ebp-$0C]
006660FE   FF75F0                 push    dword ptr [ebp-$10]
00666101   668B05C0E27D00         mov     ax, word ptr [$007DE2C0]
00666108   50                     push    eax
00666109   FF35BCE27D00           push    dword ptr [$007DE2BC]
0066610F   FF35B8E27D00           push    dword ptr [$007DE2B8]
00666115   8BC3                   mov     eax, ebx

|
00666117   E880020000             call    0066639C
0066611C   33C0                   xor     eax, eax
0066611E   5A                     pop     edx
0066611F   59                     pop     ecx
00666120   59                     pop     ecx
00666121   648910                 mov     fs:[eax], edx

****** FINALLY
|
00666124   6846616600             push    $00666146
00666129   8D45E0                 lea     eax, [ebp-$20]
0066612C   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00666131   E88AF3D9FF             call    004054C0
00666136   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00666139   E85EF3D9FF             call    0040549C
0066613E   C3                     ret


* Reference to: System.@HandleFinally;
|
0066613F   E9F4EBD9FF             jmp     00404D38
00666144   EBE3                   jmp     00666129

****** END
|
00666146   5B                     pop     ebx
00666147   8BE5                   mov     esp, ebp
00666149   5D                     pop     ebp
0066614A   C21800                 ret     $0018

*)
end;

procedure TFrmDesconto._PROC_00666191(Sender : TObject);
begin
(*
00666191   8BEC                   mov     ebp, esp
00666193   83C4E0                 add     esp, -$20
00666196   53                     push    ebx
00666197   33C9                   xor     ecx, ecx
00666199   894DE4                 mov     [ebp-$1C], ecx
0066619C   894DE0                 mov     [ebp-$20], ecx
0066619F   894DEC                 mov     [ebp-$14], ecx
006661A2   894DE8                 mov     [ebp-$18], ecx
006661A5   8955FC                 mov     [ebp-$04], edx
006661A8   8BD8                   mov     ebx, eax
006661AA   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrAddRef(void;void):Pointer;
|
006661AD   E89AF7D9FF             call    0040594C
006661B2   33C0                   xor     eax, eax
006661B4   55                     push    ebp
006661B5   684C636600             push    $0066634C

***** TRY
|
006661BA   64FF30                 push    dword ptr fs:[eax]
006661BD   648920                 mov     fs:[eax], esp
006661C0   8B4514                 mov     eax, [ebp+$14]
006661C3   8945F0                 mov     [ebp-$10], eax
006661C6   8B4518                 mov     eax, [ebp+$18]
006661C9   8945F4                 mov     [ebp-$0C], eax
006661CC   668B451C               mov     ax, word ptr [ebp+$1C]
006661D0   668945F8               mov     [ebp-$08], ax
006661D4   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'valor'
|
006661D7   BA64636600             mov     edx, $00666364

* Reference to: System.@LStrCmp;
|
006661DC   E8C7F6D9FF             call    004058A8
006661E1   7531                   jnz     00666214
006661E3   8B4508                 mov     eax, [ebp+$08]
006661E6   8905B8E27D00           mov     [$007DE2B8], eax
006661EC   8B450C                 mov     eax, [ebp+$0C]
006661EF   8905BCE27D00           mov     [$007DE2BC], eax
006661F5   668B4510               mov     ax, word ptr [ebp+$10]
006661F9   668905C0E27D00         mov     [$007DE2C0], ax
00666200   DB6D14                 fld     tbyte ptr [ebp+$14]
00666203   DB2DB8E27D00           fld     tbyte ptr [$007DE2B8]
00666209   DEE9                   fsubp   st(1), st(0)
0066620B   DB7DF0                 fstp    tbyte ptr [ebp-$10]
0066620E   9B                     wait
0066620F   E9E4000000             jmp     006662F8
00666214   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'porc'
|
00666217   BA74636600             mov     edx, $00666374

* Reference to: System.@LStrCmp;
|
0066621C   E887F6D9FF             call    004058A8
00666221   0F85D1000000           jnz     006662F8
00666227   8B4508                 mov     eax, [ebp+$08]
0066622A   8905ACE27D00           mov     [$007DE2AC], eax
00666230   8B450C                 mov     eax, [ebp+$0C]
00666233   8905B0E27D00           mov     [$007DE2B0], eax
00666239   668B4510               mov     ax, word ptr [ebp+$10]
0066623D   668905B4E27D00         mov     [$007DE2B4], ax
00666244   A1D4AB7D00             mov     eax, dword ptr [$007DABD4]
00666249   803800                 cmp     byte ptr [eax], $00
0066624C   7446                   jz      00666294
0066624E   DB2DACE27D00           fld     tbyte ptr [$007DE2AC]
00666254   D9057C636600           fld     dword ptr [$0066637C]

* Reference to: System.@FSafeDivide;
|
0066625A   E8A1D2D9FF             call    00403500
0066625F   DB6D14                 fld     tbyte ptr [ebp+$14]
00666262   DEC9                   fmulp   st(1), st(0)
00666264   83C4F4                 add     esp, -$0C
00666267   DB3C24                 fstp    tbyte ptr [esp]
0066626A   9B                     wait
0066626B   8D55E8                 lea     edx, [ebp-$18]

* Possible String Reference to: '###,###,###,##0.00'
|
0066626E   B888636600             mov     eax, $00666388

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
00666273   E8C472DAFF             call    0040D53C
00666278   8B45E8                 mov     eax, [ebp-$18]
0066627B   8D55EC                 lea     edx, [ebp-$14]

* Reference to : TFrmInfoAtu._PROC_007A3884()
|
0066627E   E801D61300             call    007A3884
00666283   8B45EC                 mov     eax, [ebp-$14]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
00666286   E86173DAFF             call    0040D5EC
0066628B   DB3DB8E27D00           fstp    tbyte ptr [$007DE2B8]
00666291   9B                     wait
00666292   EB55                   jmp     006662E9
00666294   DB2DACE27D00           fld     tbyte ptr [$007DE2AC]
0066629A   D9057C636600           fld     dword ptr [$0066637C]

* Reference to: System.@FSafeDivide;
|
006662A0   E85BD2D9FF             call    00403500
006662A5   DB6D14                 fld     tbyte ptr [ebp+$14]
006662A8   DEC9                   fmulp   st(1), st(0)
006662AA   83C4F8                 add     esp, -$08
006662AD   DD1C24                 fstp    qword ptr [esp]
006662B0   9B                     wait
006662B1   B802000000             mov     eax, $00000002

* Reference to : TFrmInfoAtu._PROC_007A11C8()
|
006662B6   E80DAF1300             call    007A11C8
006662BB   83C4F4                 add     esp, -$0C
006662BE   DB3C24                 fstp    tbyte ptr [esp]
006662C1   9B                     wait
006662C2   8D55E0                 lea     edx, [ebp-$20]

* Possible String Reference to: '###,###,###,##0.00'
|
006662C5   B888636600             mov     eax, $00666388

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
006662CA   E86D72DAFF             call    0040D53C
006662CF   8B45E0                 mov     eax, [ebp-$20]
006662D2   8D55E4                 lea     edx, [ebp-$1C]

* Reference to : TFrmInfoAtu._PROC_007A3884()
|
006662D5   E8AAD51300             call    007A3884
006662DA   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: SysUtils.StrToFloat(AnsiString):Extended;overload;
|
006662DD   E80A73DAFF             call    0040D5EC
006662E2   DB3DB8E27D00           fstp    tbyte ptr [$007DE2B8]
006662E8   9B                     wait
006662E9   DB6D14                 fld     tbyte ptr [ebp+$14]
006662EC   DB2DB8E27D00           fld     tbyte ptr [$007DE2B8]
006662F2   DEE9                   fsubp   st(1), st(0)
006662F4   DB7DF0                 fstp    tbyte ptr [ebp-$10]
006662F7   9B                     wait
006662F8   668B451C               mov     ax, word ptr [ebp+$1C]
006662FC   50                     push    eax
006662FD   FF7518                 push    dword ptr [ebp+$18]
00666300   FF7514                 push    dword ptr [ebp+$14]
00666303   668B45F8               mov     ax, word ptr [ebp-$08]
00666307   50                     push    eax
00666308   FF75F4                 push    dword ptr [ebp-$0C]
0066630B   FF75F0                 push    dword ptr [ebp-$10]
0066630E   668B05C0E27D00         mov     ax, word ptr [$007DE2C0]
00666315   50                     push    eax
00666316   FF35BCE27D00           push    dword ptr [$007DE2BC]
0066631C   FF35B8E27D00           push    dword ptr [$007DE2B8]
00666322   8BC3                   mov     eax, ebx

|
00666324   E873000000             call    0066639C
00666329   33C0                   xor     eax, eax
0066632B   5A                     pop     edx
0066632C   59                     pop     ecx
0066632D   59                     pop     ecx
0066632E   648910                 mov     fs:[eax], edx

****** FINALLY
|
00666331   6853636600             push    $00666353
00666336   8D45E0                 lea     eax, [ebp-$20]
00666339   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0066633E   E87DF1D9FF             call    004054C0
00666343   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00666346   E851F1D9FF             call    0040549C
0066634B   C3                     ret


* Reference to: System.@HandleFinally;
|
0066634C   E9E7E9D9FF             jmp     00404D38
00666351   EBE3                   jmp     00666336

****** END
|
00666353   5B                     pop     ebx
00666354   8BE5                   mov     esp, ebp
00666356   5D                     pop     ebp
00666357   C21800                 ret     $0018

*)
end;

procedure TFrmDesconto._PROC_0066639D(Sender : TObject);
begin
(*
0066639D   8BEC                   mov     ebp, esp
0066639F   53                     push    ebx
006663A0   8BD8                   mov     ebx, eax
006663A2   668B4528               mov     ax, word ptr [ebp+$28]
006663A6   50                     push    eax
006663A7   FF7524                 push    dword ptr [ebp+$24]
006663AA   FF7520                 push    dword ptr [ebp+$20]

* Reference to control TFrmDesconto.EdValorAtual : TCurrencyEdit
|
006663AD   8B8344030000           mov     eax, [ebx+$0344]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006663B3   E8082EFCFF             call    006291C0
006663B8   668B451C               mov     ax, word ptr [ebp+$1C]
006663BC   50                     push    eax
006663BD   FF7518                 push    dword ptr [ebp+$18]
006663C0   FF7514                 push    dword ptr [ebp+$14]

* Reference to control TFrmDesconto.EdNovoValor : TCurrencyEdit
|
006663C3   8B8340030000           mov     eax, [ebx+$0340]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006663C9   E8F22DFCFF             call    006291C0
006663CE   668B4510               mov     ax, word ptr [ebp+$10]
006663D2   50                     push    eax
006663D3   FF750C                 push    dword ptr [ebp+$0C]
006663D6   FF7508                 push    dword ptr [ebp+$08]

* Reference to control TFrmDesconto.EdValorDesconto : TCurrencyEdit
|
006663D9   8B8378030000           mov     eax, [ebx+$0378]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
006663DF   E8DC2DFCFF             call    006291C0
006663E4   5B                     pop     ebx
006663E5   5D                     pop     ebp
006663E6   C22400                 ret     $0024

*)
end;

procedure TFrmDesconto._PROC_00666C7D(Sender : TObject);
begin
(*
00666C7D   8BEC                   mov     ebp, esp
00666C7F   53                     push    ebx
00666C80   8BD8                   mov     ebx, eax

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666C82   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666C88   E89B24FCFF             call    00629128
00666C8D   A150B67D00             mov     eax, dword ptr [$007DB650]
00666C92   DB28                   fld     tbyte ptr [eax]
00666C94   DED9                   fcompp
00666C96   DFE0                   fstsw   ax
00666C98   9E                     sahf
00666C99   722D                   jb      00666CC8
00666C9B   A150B67D00             mov     eax, dword ptr [$007DB650]
00666CA0   668B5008               mov     dx, word ptr [eax+$08]
00666CA4   52                     push    edx
00666CA5   FF7004                 push    dword ptr [eax+$04]
00666CA8   FF30                   push    dword ptr [eax]

* Reference to control TFrmDesconto.EdValorDC : TCurrencyEdit
|
00666CAA   8B8338030000           mov     eax, [ebx+$0338]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00666CB0   E87324FCFF             call    00629128
00666CB5   83C4F4                 add     esp, -$0C
00666CB8   DB3C24                 fstp    tbyte ptr [esp]
00666CBB   9B                     wait

* Possible String Reference to: 'valor'
|
00666CBC   BAD46C6600             mov     edx, $00666CD4
00666CC1   8BC3                   mov     eax, ebx

|
00666CC3   E8A0F2FFFF             call    00665F68
00666CC8   5B                     pop     ebx
00666CC9   5D                     pop     ebp
00666CCA   C3                     ret

*)
end;

procedure TFrmDesconto._PROC_00666E35(Sender : TObject);
begin
(*
00666E35   8BEC                   mov     ebp, esp
00666E37   33C0                   xor     eax, eax
00666E39   55                     push    ebp

* Possible String Reference to: 'éÄÞÙÿëø]Ãƒ-Äâ}'
|
00666E3A   686F6E6600             push    $00666E6F

***** TRY
|
00666E3F   64FF30                 push    dword ptr fs:[eax]
00666E42   648920                 mov     fs:[eax], esp
00666E45   FF05C4E27D00           inc     dword ptr [$007DE2C4]
00666E4B   7514                   jnz     00666E61
00666E4D   B8C8887D00             mov     eax, $007D88C8

* Reference to: System.@LStrClr(void;void);
|
00666E52   E845E6D9FF             call    0040549C
00666E57   B8C4887D00             mov     eax, $007D88C4

* Reference to: System.@LStrClr(void;void);
|
00666E5C   E83BE6D9FF             call    0040549C
00666E61   33C0                   xor     eax, eax
00666E63   5A                     pop     edx
00666E64   59                     pop     ecx
00666E65   59                     pop     ecx
00666E66   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ãƒ-Äâ}'
|
00666E69   68766E6600             push    $00666E76
00666E6E   C3                     ret


* Reference to: System.@HandleFinally;
|
00666E6F   E9C4DED9FF             jmp     00404D38
00666E74   EBF8                   jmp     00666E6E

****** END
|
00666E76   5D                     pop     ebp
00666E77   C3                     ret

*)
end;

procedure TFrmDesconto._PROC_00666E78(Sender : TObject);
begin
(*
00666E78   832DC4E27D0001         sub     dword ptr [$007DE2C4], +$01
00666E7F   C3                     ret

*)
end;

procedure TFrmDesconto._PROC_00666E80(Sender : TObject);
begin
(*
00666E80   846E66                 test    [esi+$66], ch
00666E83   000E                   add     [esi], cl
00666E85   0B745265               or      esi, [edx+edx*2+$65]
00666E89   746F                   jz      00666EFA
00666E8B   726E                   jb      00666EFB
00666E8D   6F                     outsd
00666E8E   53                     push    ebx
00666E8F   54                     push    esp
00666E90   53                     push    ebx
00666E91   0C00                   or      al, $00
00666E93   0000                   add     [eax], al

00666E95   0100                   add     [eax], eax
00666E97   0000                   add     [eax], al

00666E99   0811                   or      [ecx], dl
00666E9B   40                     inc     eax
00666E9C   0000                   add     [eax], al

00666E9E   0000                   add     [eax], al

00666EA0   008D4000A86E           add     [ebp+$6EA80040], cl
00666EA6   66000E                 add     [esi], cl
00666EA9   08745265               or      [edx+edx*2+$65], dh
00666EAD   746F                   jz      00666F1E
00666EAF   726E                   jb      00666F1F
00666EB1   6F                     outsd
00666EB2   C800                   enter   , $00
00666EB4   0000                   add     [eax], al

00666EB6   1400                   adc     al, $00
00666EB8   0000                   add     [eax], al

00666EBA   0811                   or      [ecx], dl
00666EBC   40                     inc     eax
00666EBD   0000                   add     [eax], al

00666EBF   0000                   add     [eax], al

00666EC1   0008                   add     [eax], cl
00666EC3   114000                 adc     [eax+$00], eax
00666EC6   1C00                   sbb     al, $00
00666EC8   0000                   add     [eax], al

00666ECA   0811                   or      [ecx], dl
00666ECC   40                     inc     eax
00666ECD   0020                   add     [eax], ah
00666ECF   0000                   add     [eax], al

00666ED1   0008                   add     [eax], cl
00666ED3   114000                 adc     [eax+$00], eax
00666ED6   2400                   and     al, $00
00666ED8   0000                   add     [eax], al

00666EDA   0811                   or      [ecx], dl
00666EDC   40                     inc     eax
00666EDD   003400                 add     [eax+eax], dh
00666EE0   0000                   add     [eax], al

00666EE2   0811                   or      [ecx], dl
00666EE4   40                     inc     eax
00666EE5   0038                   add     [eax], bh
00666EE7   0000                   add     [eax], al

00666EE9   0008                   add     [eax], cl
00666EEB   114000                 adc     [eax+$00], eax
00666EEE   3C00                   cmp     al, $00
00666EF0   0000                   add     [eax], al

00666EF2   0811                   or      [ecx], dl
00666EF4   40                     inc     eax
00666EF5   004000                 add     [eax+$00], al
00666EF8   0000                   add     [eax], al

00666EFA   0811                   or      [ecx], dl
00666EFC   40                     inc     eax
00666EFD   009000000008           add     [eax+$8000000], dl
00666F03   114000                 adc     [eax+$00], eax
00666F06   98                     cwde 
00666F07   0000                   add     [eax], al

00666F09   0008                   add     [eax], cl
00666F0B   114000                 adc     [eax+$00], eax
00666F0E   9C                     pushf   
00666F0F   0000                   add     [eax], al

00666F11   0008                   add     [eax], cl
00666F13   114000                 adc     [eax+$00], eax
00666F16   A000000008             mov     al, byte ptr [$08000000]
00666F1B   114000                 adc     [eax+$00], eax
00666F1E   A4                     movsb
00666F1F   0000                   add     [eax], al

*)
end;

end.