unit dinheiro;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, Mask, ToolEdit, CurrEdit,
  LMDControl, LMDCustomControl, LMDCustomPanel, LMDCustomBevelPanel,
  LMDSimplePanel, ExtCtrls, LMDBaseControl, LMDBaseGraphicControl,
  LMDGraphicControl, LMDFill;
  
type
  TFrmFinalizaDinheiro=class(TForm)
    txFundo: TLMDFill;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    pnTotal: TLMDSimplePanel;
    EdVlrTotal: TCurrencyEdit;
    pnRecebido: TLMDSimplePanel;
    EdVlrRecebido: TCurrencyEdit;
    pnTroco: TLMDSimplePanel;
    EdVlrTroco: TCurrencyEdit;
    btDesiste: TBitBtn;
    btConfirma: TBitBtn;
    stTitulo: TStaticText;
    Bevel1: TBevel;
    procedure EdVlrRecebidoChange(Sender : TObject);
    procedure EdVlrTotalEnter(Sender : TObject);
    procedure EdVlrTrocoEnter(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure EdVlrRecebidoEnter(Sender : TObject);
    procedure EdVlrRecebidoExit(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure EdVlrRecebidoKeyPress(Sender : TObject);
    procedure _PROC_00670EA0(Sender : TObject);
    procedure _PROC_00670F80(Sender : TObject);
    procedure _PROC_00670F88(Sender : TObject);
    procedure _PROC_00670FB8(Sender : TObject);
    procedure _PROC_00670FC0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmFinalizaDinheiro: TFrmFinalizaDinheiro;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmFinalizaDinheiro.EdVlrRecebidoChange(Sender : TObject);
begin
(*
00670BF0   55                     push    ebp
00670BF1   8BEC                   mov     ebp, esp
00670BF3   83C4F4                 add     esp, -$0C
00670BF6   53                     push    ebx
00670BF7   56                     push    esi
00670BF8   8BD8                   mov     ebx, eax

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670BFA   8B8314030000           mov     eax, [ebx+$0314]
00670C00   66BEB5FF               mov     si, $FFB5

* Reference to: System.@CallDynaInst;
|
00670C04   E8973BD9FF             call    004047A0
00670C09   84C0                   test    al, al
00670C0B   7468                   jz      00670C75

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670C0D   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670C13   E81085FBFF             call    00629128
00670C18   DB7DF4                 fstp    tbyte ptr [ebp-$0C]
00670C1B   9B                     wait

* Reference to control TFrmFinalizaDinheiro.EdVlrTotal : TCurrencyEdit
|
00670C1C   8B830C030000           mov     eax, [ebx+$030C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670C22   E80185FBFF             call    00629128
00670C27   DB6DF4                 fld     tbyte ptr [ebp-$0C]
00670C2A   DED9                   fcompp
00670C2C   DFE0                   fstsw   ax
00670C2E   9E                     sahf
00670C2F   7233                   jb      00670C64

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670C31   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670C37   E8EC84FBFF             call    00629128
00670C3C   DB7DF4                 fstp    tbyte ptr [ebp-$0C]
00670C3F   9B                     wait

* Reference to control TFrmFinalizaDinheiro.EdVlrTotal : TCurrencyEdit
|
00670C40   8B830C030000           mov     eax, [ebx+$030C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670C46   E8DD84FBFF             call    00629128
00670C4B   DB6DF4                 fld     tbyte ptr [ebp-$0C]
00670C4E   DEE1                   fsubrp  st(1), st(0)
00670C50   83C4F4                 add     esp, -$0C
00670C53   DB3C24                 fstp    tbyte ptr [esp]
00670C56   9B                     wait

* Reference to control TFrmFinalizaDinheiro.EdVlrTroco : TCurrencyEdit
|
00670C57   8B831C030000           mov     eax, [ebx+$031C]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00670C5D   E85E85FBFF             call    006291C0
00670C62   EB11                   jmp     00670C75
00670C64   6A00                   push    $00
00670C66   6A00                   push    $00
00670C68   6A00                   push    $00

* Reference to control TFrmFinalizaDinheiro.EdVlrTroco : TCurrencyEdit
|
00670C6A   8B831C030000           mov     eax, [ebx+$031C]

* Reference to : TCurrencyEdit._PROC_006291C0()
|
00670C70   E84B85FBFF             call    006291C0
00670C75   5E                     pop     esi
00670C76   5B                     pop     ebx
00670C77   8BE5                   mov     esp, ebp
00670C79   5D                     pop     ebp
00670C7A   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.EdVlrTotalEnter(Sender : TObject);
begin
(*
00670C7C   55                     push    ebp
00670C7D   8BEC                   mov     ebp, esp

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670C7F   8B8014030000           mov     eax, [eax+$0314]
00670C85   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00670C87   FF92C4000000           call    dword ptr [edx+$00C4]
00670C8D   5D                     pop     ebp
00670C8E   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.EdVlrTrocoEnter(Sender : TObject);
begin
(*
00670C90   55                     push    ebp
00670C91   8BEC                   mov     ebp, esp

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670C93   8B8014030000           mov     eax, [eax+$0314]
00670C99   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00670C9B   FF92C4000000           call    dword ptr [edx+$00C4]
00670CA1   5D                     pop     ebp
00670CA2   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.FormCloseQuery(Sender : TObject);
begin
(*
00670CA4   55                     push    ebp
00670CA5   8BEC                   mov     ebp, esp
00670CA7   83C4F4                 add     esp, -$0C
00670CAA   53                     push    ebx
00670CAB   56                     push    esi
00670CAC   8BF1                   mov     esi, ecx
00670CAE   8BD8                   mov     ebx, eax

* Reference to field TFrmFinalizaDinheiro.ModalResult : TModalResult
|
00670CB0   83BB4C02000001         cmp     dword ptr [ebx+$024C], +$01
00670CB7   0F85E2000000           jnz     00670D9F
00670CBD   8BC3                   mov     eax, ebx

* Reference to : TFrmFinalizaDinheiro._PROC_00670F80()
|
00670CBF   E8BC020000             call    00670F80

* Reference to control TFrmFinalizaDinheiro.EdVlrTotal : TCurrencyEdit
|
00670CC4   8B830C030000           mov     eax, [ebx+$030C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670CCA   E85984FBFF             call    00629128
00670CCF   D81DA80D6700           fcomp   dword ptr [$00670DA8]
00670CD5   DFE0                   fstsw   ax
00670CD7   9E                     sahf
00670CD8   7708                   jnbe    00670CE2
00670CDA   C60601                 mov     byte ptr [esi], $01
00670CDD   E9BD000000             jmp     00670D9F

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670CE2   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670CE8   E83B84FBFF             call    00629128
00670CED   D81DA80D6700           fcomp   dword ptr [$00670DA8]
00670CF3   DFE0                   fstsw   ax
00670CF5   9E                     sahf
00670CF6   0F86A3000000           jbe     00670D9F

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670CFC   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670D02   E82184FBFF             call    00629128
00670D07   DB7DF4                 fstp    tbyte ptr [ebp-$0C]
00670D0A   9B                     wait

* Reference to control TFrmFinalizaDinheiro.EdVlrTotal : TCurrencyEdit
|
00670D0B   8B830C030000           mov     eax, [ebx+$030C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670D11   E81284FBFF             call    00629128
00670D16   DB6DF4                 fld     tbyte ptr [ebp-$0C]
00670D19   DED9                   fcompp
00670D1B   DFE0                   fstsw   ax
00670D1D   9E                     sahf
00670D1E   7328                   jnb     00670D48
00670D20   6A00                   push    $00
00670D22   668B0DAC0D6700         mov     cx, word ptr [$00670DAC]
00670D29   33D2                   xor     edx, edx

* Possible String Reference to: 'Valor Recebido não pode ser menor q
|                                ue o valor total!'
|
00670D2B   B8B80D6700             mov     eax, $00670DB8

|
00670D30   E8F72DDDFF             call    00443B2C

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670D35   8B8314030000           mov     eax, [ebx+$0314]
00670D3B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00670D3D   FF92C4000000           call    dword ptr [edx+$00C4]
00670D43   C60600                 mov     byte ptr [esi], $00
00670D46   EB57                   jmp     00670D9F

* Reference to control TFrmFinalizaDinheiro.EdVlrTotal : TCurrencyEdit
|
00670D48   8B830C030000           mov     eax, [ebx+$030C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670D4E   E8D583FBFF             call    00629128
00670D53   D81DF00D6700           fcomp   dword ptr [$00670DF0]
00670D59   DFE0                   fstsw   ax
00670D5B   9E                     sahf
00670D5C   7628                   jbe     00670D86
00670D5E   6A00                   push    $00
00670D60   668B0DAC0D6700         mov     cx, word ptr [$00670DAC]
00670D67   33D2                   xor     edx, edx

* Possible String Reference to: 'O valor total está muito alto! Veri
|                                fique se não ocorreu nenhum erro no
|                                 cupom e seu possível cancelamento 
|                                (ou de algum item).'
|
00670D69   B8FC0D6700             mov     eax, $00670DFC

|
00670D6E   E8B92DDDFF             call    00443B2C

* Reference to control TFrmFinalizaDinheiro.EdVlrRecebido : TCurrencyEdit
|
00670D73   8B8314030000           mov     eax, [ebx+$0314]
00670D79   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCurrencyEdit.OFFS_00C4
|
00670D7B   FF92C4000000           call    dword ptr [edx+$00C4]
00670D81   C60600                 mov     byte ptr [esi], $00
00670D84   EB19                   jmp     00670D9F

* Reference to control TFrmFinalizaDinheiro.EdVlrTroco : TCurrencyEdit
|
00670D86   8B831C030000           mov     eax, [ebx+$031C]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00670D8C   E89783FBFF             call    00629128
00670D91   D81DA80D6700           fcomp   dword ptr [$00670DA8]
00670D97   DFE0                   fstsw   ax
00670D99   9E                     sahf
00670D9A   7603                   jbe     00670D9F
00670D9C   C60601                 mov     byte ptr [esi], $01
00670D9F   5E                     pop     esi
00670DA0   5B                     pop     ebx
00670DA1   8BE5                   mov     esp, ebp
00670DA3   5D                     pop     ebp
00670DA4   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.EdVlrRecebidoEnter(Sender : TObject);
begin
(*
00670E7C   55                     push    ebp
00670E7D   8BEC                   mov     ebp, esp

|
00670E7F   E8BC501300             call    007A5F40
00670E84   5D                     pop     ebp
00670E85   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.EdVlrRecebidoExit(Sender : TObject);
begin
(*
00670E88   55                     push    ebp
00670E89   8BEC                   mov     ebp, esp

|
00670E8B   E8C8501300             call    007A5F58
00670E90   5D                     pop     ebp
00670E91   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.FormClose(Sender : TObject);
begin
(*
00670E94   55                     push    ebp
00670E95   8BEC                   mov     ebp, esp

|
00670E97   E8BC501300             call    007A5F58
00670E9C   5D                     pop     ebp
00670E9D   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.FormCreate(Sender : TObject);
begin
(*
00670F24   55                     push    ebp
00670F25   8BEC                   mov     ebp, esp

* Reference to : TFrmFinalizaDinheiro._PROC_00670EA0()
|
00670F27   E874FFFFFF             call    00670EA0
00670F2C   5D                     pop     ebp
00670F2D   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.FormKeyDown(Sender : TObject);
begin
(*
00670F30   55                     push    ebp
00670F31   8BEC                   mov     ebp, esp
00670F33   56                     push    esi
00670F34   6683390D               cmp     word ptr [ecx], +$0D
00670F38   7511                   jnz     00670F4B

* Reference to control TFrmFinalizaDinheiro.btConfirma : TBitBtn
|
00670F3A   8B8024030000           mov     eax, [eax+$0324]
00670F40   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
00670F44   E85738D9FF             call    004047A0
00670F49   EB15                   jmp     00670F60
00670F4B   6683391B               cmp     word ptr [ecx], +$1B
00670F4F   750F                   jnz     00670F60

* Reference to field TBitBtn.OFFS_0320
|
00670F51   8B8020030000           mov     eax, [eax+$0320]
00670F57   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
00670F5B   E84038D9FF             call    004047A0
00670F60   5E                     pop     esi
00670F61   5D                     pop     ebp
00670F62   C20400                 ret     $0004

*)
end;

procedure TFrmFinalizaDinheiro.FormShow(Sender : TObject);
begin
(*
00670F68   55                     push    ebp
00670F69   8BEC                   mov     ebp, esp

|
00670F6B   E8D04F1300             call    007A5F40
00670F70   5D                     pop     ebp
00670F71   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro.EdVlrRecebidoKeyPress(Sender : TObject);
begin
(*
00670F74   80392E                 cmp     byte ptr [ecx], $2E
00670F77   7503                   jnz     00670F7C
00670F79   C6012C                 mov     byte ptr [ecx], $2C
00670F7C   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro._PROC_00670EA0(Sender : TObject);
begin
(*
00670EA0   55                     push    ebp
00670EA1   8BEC                   mov     ebp, esp
00670EA3   53                     push    ebx
00670EA4   8BD8                   mov     ebx, eax

* Reference to control TFrmFinalizaDinheiro.txFundo : TLMDFill
|
00670EA6   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TLMDFill.OFFS_01BC
|
00670EAC   8B80BC010000           mov     eax, [eax+$01BC]
00670EB2   33D2                   xor     edx, edx

|
00670EB4   E8636DF8FF             call    005F7C1C
00670EB9   33D2                   xor     edx, edx

* Reference to control TFrmFinalizaDinheiro.stTitulo : TStaticText
|
00670EBB   8B8328030000           mov     eax, [ebx+$0328]

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
00670EC1   E8BE29E2FF             call    00493884

* Reference to control TFrmFinalizaDinheiro.stTitulo : TStaticText
|
00670EC6   8B8328030000           mov     eax, [ebx+$0328]

* Reference to field TStaticText.Font : TFont
|
00670ECC   8B4068                 mov     eax, [eax+$68]
00670ECF   BAFFFFFF00             mov     edx, $00FFFFFF

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
00670ED4   E8770BDCFF             call    00431A50

* Reference to control TFrmFinalizaDinheiro.pnTotal : TLMDSimplePanel
|
00670ED9   8B8308030000           mov     eax, [ebx+$0308]

* Reference to field TLMDSimplePanel.OFFS_0260
|
00670EDF   8B8060020000           mov     eax, [eax+$0260]
00670EE5   B900808000             mov     ecx, $00808000
00670EEA   33D2                   xor     edx, edx

|
00670EEC   E8830EF9FF             call    00601D74

* Reference to control TFrmFinalizaDinheiro.pnRecebido : TLMDSimplePanel
|
00670EF1   8B8310030000           mov     eax, [ebx+$0310]

* Reference to field TLMDSimplePanel.OFFS_0260
|
00670EF7   8B8060020000           mov     eax, [eax+$0260]
00670EFD   B900808000             mov     ecx, $00808000
00670F02   33D2                   xor     edx, edx

|
00670F04   E86B0EF9FF             call    00601D74

* Reference to control TFrmFinalizaDinheiro.pnTroco : TLMDSimplePanel
|
00670F09   8B8318030000           mov     eax, [ebx+$0318]

* Reference to field TLMDSimplePanel.OFFS_0260
|
00670F0F   8B8060020000           mov     eax, [eax+$0260]
00670F15   B900808000             mov     ecx, $00808000
00670F1A   33D2                   xor     edx, edx

|
00670F1C   E8530EF9FF             call    00601D74
00670F21   5B                     pop     ebx
00670F22   5D                     pop     ebp
00670F23   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro._PROC_00670F80(Sender : TObject);
begin
(*

* Reference to field TFrmFinalizaDinheiro.Tag : Longint
|
00670F80   83780C00               cmp     dword ptr [eax+$0C], +$00
00670F84   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro._PROC_00670F88(Sender : TObject);
begin
(*
00670F88   55                     push    ebp
00670F89   8BEC                   mov     ebp, esp
00670F8B   33C0                   xor     eax, eax
00670F8D   55                     push    ebp

* Possible String Reference to: 'é†=Ùÿëø]Ã‹Àƒ-Pé}'
|
00670F8E   68AD0F6700             push    $00670FAD

***** TRY
|
00670F93   64FF30                 push    dword ptr fs:[eax]
00670F96   648920                 mov     fs:[eax], esp
00670F99   FF0550E97D00           inc     dword ptr [$007DE950]
00670F9F   33C0                   xor     eax, eax
00670FA1   5A                     pop     edx
00670FA2   59                     pop     ecx
00670FA3   59                     pop     ecx
00670FA4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-Pé}'
|
00670FA7   68B40F6700             push    $00670FB4
00670FAC   C3                     ret


* Reference to: System.@HandleFinally;
|
00670FAD   E9863DD9FF             jmp     00404D38
00670FB2   EBF8                   jmp     00670FAC

****** END
|
00670FB4   5D                     pop     ebp
00670FB5   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro._PROC_00670FB8(Sender : TObject);
begin
(*
00670FB8   832D50E97D0001         sub     dword ptr [$007DE950], +$01
00670FBF   C3                     ret

*)
end;

procedure TFrmFinalizaDinheiro._PROC_00670FC0(Sender : TObject);
begin
(*
00670FC0   0C10                   or      al, $10
00670FC2   670000                 add     [bx+si], al
00670FC5   0000                   add     [eax], al

*)
end;

end.