unit F2Fontes;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, Grids, DBGrids, JvExDBGrids,
  JvDBGrid, DBCtrls;
  
type
  TFrmF2Fontes=class(TForm)
    grFontes: TJvDBGrid;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    BitBtn3: TBitBtn;
    DBText1: TDBText;
    procedure grFontesGetCellParams(Sender : TObject);
    procedure grFontesDrawColumnCell(Sender : TObject);
    procedure BitBtn3Click(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure _PROC_00729769(Sender : TObject);
    procedure _PROC_00729798(Sender : TObject);
    procedure _PROC_007297A0(Sender : TObject);
    procedure _PROC_00729A1F(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmF2Fontes: TFrmF2Fontes;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmF2Fontes.grFontesGetCellParams(Sender : TObject);
begin
(*
007293E8   55                     push    ebp
007293E9   8BEC                   mov     ebp, esp
007293EB   6A00                   push    $00
007293ED   6A00                   push    $00
007293EF   6A00                   push    $00
007293F1   6A00                   push    $00
007293F3   53                     push    ebx
007293F4   8B5D10                 mov     ebx, [ebp+$10]
007293F7   33C0                   xor     eax, eax
007293F9   55                     push    ebp
007293FA   688E957200             push    $0072958E

***** TRY
|
007293FF   64FF30                 push    dword ptr fs:[eax]
00729402   648920                 mov     fs:[eax], esp
00729405   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072940A   8B00                   mov     eax, [eax]
0072940C   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
00729412   BAA4957200             mov     edx, $007295A4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729417   E8E807DCFF             call    004E9C04
0072941C   8D55FC                 lea     edx, [ebp-$04]
0072941F   8B08                   mov     ecx, [eax]
00729421   FF5160                 call    dword ptr [ecx+$60]
00729424   837DFC00               cmp     dword ptr [ebp-$04], +$00
00729428   0F8445010000           jz      00729573
0072942E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
00729433   8B00                   mov     eax, [eax]
00729435   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
0072943B   BAA4957200             mov     edx, $007295A4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729440   E8BF07DCFF             call    004E9C04
00729445   8D55F8                 lea     edx, [ebp-$08]
00729448   8B08                   mov     ecx, [eax]
0072944A   FF5160                 call    dword ptr [ecx+$60]
0072944D   8B55F8                 mov     edx, [ebp-$08]
00729450   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetName(TFont;TFontName);
|
00729452   E82188D0FF             call    00431C78
00729457   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072945C   8B00                   mov     eax, [eax]
0072945E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Tamanho'
|
00729464   BAB4957200             mov     edx, $007295B4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729469   E89607DCFF             call    004E9C04
0072946E   8B10                   mov     edx, [eax]
00729470   FF5258                 call    dword ptr [edx+$58]
00729473   8BD0                   mov     edx, eax
00729475   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetSize(TFont;Integer);
|
00729477   E87488D0FF             call    00431CF0
0072947C   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
00729481   8B00                   mov     eax, [eax]
00729483   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
00729489   BAC4957200             mov     edx, $007295C4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072948E   E87107DCFF             call    004E9C04
00729493   8D55F4                 lea     edx, [ebp-$0C]
00729496   8B08                   mov     ecx, [eax]
00729498   FF5160                 call    dword ptr [ecx+$60]
0072949B   837DF400               cmp     dword ptr [ebp-$0C], +$00
0072949F   7430                   jz      007294D1
007294A1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007294A6   8B00                   mov     eax, [eax]
007294A8   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
007294AE   BAC4957200             mov     edx, $007295C4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007294B3   E84C07DCFF             call    004E9C04
007294B8   8D55F0                 lea     edx, [ebp-$10]
007294BB   8B08                   mov     ecx, [eax]
007294BD   FF5160                 call    dword ptr [ecx+$60]
007294C0   8B45F0                 mov     eax, [ebp-$10]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
007294C3   E8B480D0FF             call    0043157C
007294C8   8BD0                   mov     edx, eax
007294CA   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
007294CC   E87F85D0FF             call    00431A50
007294D1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007294D6   8B00                   mov     eax, [eax]
007294D8   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'sublinhado'
|
007294DE   BAD0957200             mov     edx, $007295D0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007294E3   E81C07DCFF             call    004E9C04
007294E8   8B10                   mov     edx, [eax]
007294EA   FF5244                 call    dword ptr [edx+$44]
007294ED   84C0                   test    al, al
007294EF   7416                   jz      00729507
007294F1   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
007294F3   E81888D0FF             call    00431D10
007294F8   8BD0                   mov     edx, eax
007294FA   0A15DC957200           or      dl, byte ptr [$007295DC]
00729500   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
00729502   E81588D0FF             call    00431D1C
00729507   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072950C   8B00                   mov     eax, [eax]
0072950E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'bold'
|
00729514   BAE8957200             mov     edx, $007295E8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729519   E8E606DCFF             call    004E9C04
0072951E   8B10                   mov     edx, [eax]
00729520   FF5244                 call    dword ptr [edx+$44]
00729523   84C0                   test    al, al
00729525   7416                   jz      0072953D
00729527   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729529   E8E287D0FF             call    00431D10
0072952E   8BD0                   mov     edx, eax
00729530   0A15F0957200           or      dl, byte ptr [$007295F0]
00729536   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
00729538   E8DF87D0FF             call    00431D1C
0072953D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
00729542   8B00                   mov     eax, [eax]
00729544   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'italico'
|
0072954A   BAFC957200             mov     edx, $007295FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072954F   E8B006DCFF             call    004E9C04
00729554   8B10                   mov     edx, [eax]
00729556   FF5244                 call    dword ptr [edx+$44]
00729559   84C0                   test    al, al
0072955B   7416                   jz      00729573
0072955D   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072955F   E8AC87D0FF             call    00431D10
00729564   8BD0                   mov     edx, eax
00729566   0A1504967200           or      dl, byte ptr [$00729604]
0072956C   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072956E   E8A987D0FF             call    00431D1C
00729573   33C0                   xor     eax, eax
00729575   5A                     pop     edx
00729576   59                     pop     ecx
00729577   59                     pop     ecx
00729578   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072957B   6895957200             push    $00729595
00729580   8D45F0                 lea     eax, [ebp-$10]
00729583   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00729588   E833BFCDFF             call    004054C0
0072958D   C3                     ret


* Reference to: System.@HandleFinally;
|
0072958E   E9A5B7CDFF             jmp     00404D38
00729593   EBEB                   jmp     00729580

****** END
|
00729595   5B                     pop     ebx
00729596   8BE5                   mov     esp, ebp
00729598   5D                     pop     ebp
00729599   C20C00                 ret     $000C

*)
end;

procedure TFrmF2Fontes.grFontesDrawColumnCell(Sender : TObject);
begin
(*
00729608   55                     push    ebp
00729609   8BEC                   mov     ebp, esp
0072960B   6A00                   push    $00
0072960D   53                     push    ebx
0072960E   56                     push    esi
0072960F   8BF1                   mov     esi, ecx
00729611   8BD8                   mov     ebx, eax
00729613   33C0                   xor     eax, eax
00729615   55                     push    ebp
00729616   68BD967200             push    $007296BD

***** TRY
|
0072961B   64FF30                 push    dword ptr fs:[eax]
0072961E   648920                 mov     fs:[eax], esp

* Reference to control TFrmF2Fontes.grFontes : TJvDBGrid
|
00729621   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TJvDBGrid.OFFS_0208
|
00729627   8B8008020000           mov     eax, [eax+$0208]
0072962D   8B4014                 mov     eax, [eax+$14]
00729630   BAFFFFFF00             mov     edx, $00FFFFFF

* Reference to: Graphics.TBrush.SetColor(TBrush;TColor);
|
00729635   E80A8CD0FF             call    00432244

* Reference to control TFrmF2Fontes.grFontes : TJvDBGrid
|
0072963A   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TJvDBGrid.OFFS_0208
|
00729640   8B8008020000           mov     eax, [eax+$0208]
00729646   8B4010                 mov     eax, [eax+$10]
00729649   33D2                   xor     edx, edx

* Reference to: Graphics.TPen.SetColor(TPen;TColor);
|
0072964B   E8EC88D0FF             call    00431F3C
00729650   8BD6                   mov     edx, esi

* Reference to control TFrmF2Fontes.grFontes : TJvDBGrid
|
00729652   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TJvDBGrid.OFFS_0208
|
00729658   8B8008020000           mov     eax, [eax+$0208]

* Reference to: Graphics.TCanvas.FillRect(TCanvas;Windows.TRect;Windows.TRect);
|
0072965E   E89193D0FF             call    004329F4
00729663   8BD6                   mov     edx, esi

* Reference to control TFrmF2Fontes.grFontes : TJvDBGrid
|
00729665   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TJvDBGrid.OFFS_0208
|
0072966B   8B8008020000           mov     eax, [eax+$0208]

* Reference to: Graphics.TCanvas.Ellipse(TCanvas;Windows.TRect;Windows.TRect);overload;
|
00729671   E8E295D0FF             call    00432C58
00729676   8B4604                 mov     eax, [esi+$04]
00729679   83C003                 add     eax, +$03
0072967C   50                     push    eax
0072967D   8B450C                 mov     eax, [ebp+$0C]

* Reference to: DBGrids.TColumn.GetField(TColumn):TField;
|
00729680   E8CB47DFFF             call    0051DE50
00729685   8D55FC                 lea     edx, [ebp-$04]
00729688   8B08                   mov     ecx, [eax]
0072968A   FF5160                 call    dword ptr [ecx+$60]
0072968D   8B45FC                 mov     eax, [ebp-$04]
00729690   50                     push    eax
00729691   8B0E                   mov     ecx, [esi]
00729693   41                     inc     ecx
00729694   8BD6                   mov     edx, esi

* Reference to control TFrmF2Fontes.grFontes : TJvDBGrid
|
00729696   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TJvDBGrid.OFFS_0208
|
0072969C   8B8008020000           mov     eax, [eax+$0208]

* Reference to: Graphics.TCanvas.TextRect(TCanvas;Windows.TRect;Integer;Integer;AnsiString);
|
007296A2   E81197D0FF             call    00432DB8
007296A7   33C0                   xor     eax, eax
007296A9   5A                     pop     edx
007296AA   59                     pop     ecx
007296AB   59                     pop     ecx
007296AC   648910                 mov     fs:[eax], edx

****** FINALLY
|
007296AF   68C4967200             push    $007296C4
007296B4   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
007296B7   E8E0BDCDFF             call    0040549C
007296BC   C3                     ret


* Reference to: System.@HandleFinally;
|
007296BD   E976B6CDFF             jmp     00404D38
007296C2   EBF0                   jmp     007296B4

****** END
|
007296C4   5E                     pop     esi
007296C5   5B                     pop     ebx
007296C6   59                     pop     ecx
007296C7   5D                     pop     ebp
007296C8   C20C00                 ret     $000C

*)
end;

procedure TFrmF2Fontes.BitBtn3Click(Sender : TObject);
begin
(*
007296CC   55                     push    ebp
007296CD   8BEC                   mov     ebp, esp
007296CF   53                     push    ebx
007296D0   8BD8                   mov     ebx, eax
007296D2   8BCB                   mov     ecx, ebx
007296D4   B201                   mov     dl, $01

* Reference to class TFrmFontes
|
007296D6   A1A0977200             mov     eax, dword ptr [$007297A0]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
007296DB   E83048D8FF             call    004ADF10
007296E0   8B1598A27D00           mov     edx, [$007DA298]
007296E6   8902                   mov     [edx], eax
007296E8   A198A27D00             mov     eax, dword ptr [$007DA298]
007296ED   8B00                   mov     eax, [eax]
007296EF   8B10                   mov     edx, [eax]
007296F1   FF92EC000000           call    dword ptr [edx+$00EC]
007296F7   A198A27D00             mov     eax, dword ptr [$007DA298]
007296FC   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
007296FE   E899AECDFF             call    0040459C
00729703   5B                     pop     ebx
00729704   5D                     pop     ebp
00729705   C3                     ret

*)
end;

procedure TFrmF2Fontes.FormShow(Sender : TObject);
begin
(*
00729708   55                     push    ebp
00729709   8BEC                   mov     ebp, esp
0072970B   6A00                   push    $00

* Possible String Reference to: 'CODFONTE'
|
0072970D   683C977200             push    $0072973C
00729712   6A01                   push    $01
00729714   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
00729719   8B00                   mov     eax, [eax]
0072971B   8B80F4000000           mov     eax, [eax+$00F4]
00729721   B950977200             mov     ecx, $00729750

* Possible String Reference to: 'RELFONTE'
|
00729726   BA5C977200             mov     edx, $0072975C

|
0072972B   E838E30700             call    007A7A68
00729730   5D                     pop     ebp
00729731   C3                     ret

*)
end;

procedure TFrmF2Fontes._PROC_00729769(Sender : TObject);
begin
(*
00729769   8BEC                   mov     ebp, esp
0072976B   33C0                   xor     eax, eax
0072976D   55                     push    ebp
0072976E   688D977200             push    $0072978D

***** TRY
|
00729773   64FF30                 push    dword ptr fs:[eax]
00729776   648920                 mov     fs:[eax], esp
00729779   FF051CF37D00           inc     dword ptr [$007DF31C]
0072977F   33C0                   xor     eax, eax
00729781   5A                     pop     edx
00729782   59                     pop     ecx
00729783   59                     pop     ecx
00729784   648910                 mov     fs:[eax], edx

****** FINALLY
|
00729787   6894977200             push    $00729794
0072978C   C3                     ret


* Reference to: System.@HandleFinally;
|
0072978D   E9A6B5CDFF             jmp     00404D38
00729792   EBF8                   jmp     0072978C

****** END
|
00729794   5D                     pop     ebp
00729795   C3                     ret

*)
end;

procedure TFrmF2Fontes._PROC_00729798(Sender : TObject);
begin
(*
00729798   832D1CF37D0001         sub     dword ptr [$007DF31C], +$01
0072979F   C3                     ret

*)
end;

procedure TFrmF2Fontes._PROC_007297A0(Sender : TObject);
begin
(*
007297A0   EC                     in      al, dx
007297A1   97                     xchg    eax, edi
007297A2   7200                   jb      007297A4
007297A4   0000                   add     [eax], al

*)
end;

procedure TFrmF2Fontes._PROC_00729A1F(Sender : TObject);
begin
(*
00729A1F   736F                   jnb     00729A90
00729A21   44                     inc     esp
00729A22   61                     popa
00729A23   46                     inc     esi
00729A24   6F                     outsd
00729A25   6E                     outsb
00729A26   7465                   jz      00729A8D
00729A28   4C                     dec     esp
00729A29   0300                   add     eax, [eax]
00729A2B   0002                   add     [edx], al
00729A2D   0007                   add     [edi], al
00729A2F   706E                   jo      00729A9F
00729A31   46                     inc     esi
00729A32   6F                     outsd
00729A33   6E                     outsb
00729A34   7465                   jz      00729A9B
00729A36   50                     push    eax
00729A37   0300                   add     eax, [eax]
00729A39   0006                   add     [esi], al
00729A3B   0006                   add     [esi], al
00729A3D   4C                     dec     esp
00729A3E   61                     popa
00729A3F   62656C                 bound   esp, qword ptr [ebp+$6C]
00729A42   37                     aaa
00729A43   54                     push    esp
00729A44   0300                   add     eax, [eax]
00729A46   000B                   add     [ebx], cl
00729A48   0006                   add     [esi], al
00729A4A   42                     inc     edx
00729A4B   657665                 jbe     00729AB3
00729A4E   6C                     insb
00729A4F   315803                 xor     [eax+$03], ebx
00729A52   0000                   add     [eax], al

00729A54   06                     push    es
00729A55   0006                   add     [esi], al
00729A57   4C                     dec     esp
00729A58   61                     popa
00729A59   62656C                 bound   esp, qword ptr [ebp+$6C]
00729A5C   365C                   pop     esp
00729A5E   0300                   add     eax, [eax]
00729A60   0006                   add     [esi], al
00729A62   0006                   add     [esi], al
00729A64   4C                     dec     esp
00729A65   61                     popa
00729A66   62656C                 bound   esp, qword ptr [ebp+$6C]
00729A69   386003                 cmp     [eax+$03], ah
00729A6C   0000                   add     [eax], al

00729A6E   0B00                   or      eax, [eax]
00729A70   06                     push    es
00729A71   42                     inc     edx
00729A72   657665                 jbe     00729ADA
00729A75   6C                     insb
00729A76   32640300               xor     ah, byte ptr [ebx+eax+$00]
00729A7A   000C00                 add     [eax+eax], cl
00729A7D   0D44425261             or      eax, $61524244
00729A82   64696F47726F7570       imul    ebp, fs:[edi+$47], $70756F72
00729A8A   316803                 xor     [eax+$03], ebp
00729A8D   0000                   add     [eax], al

00729A8F   0C00                   or      al, $00
00729A91   0D44425261             or      eax, $61524244
00729A96   64696F47726F7570       imul    ebp, fs:[edi+$47], $70756F72
00729A9E   326C0300               xor     ch, byte ptr [ebx+eax+$00]
00729AA2   000C00                 add     [eax+eax], cl
00729AA5   0D44425261             or      eax, $61524244
00729AAA   64696F47726F7570       imul    ebp, fs:[edi+$47], $70756F72
00729AB2   337003                 xor     esi, [eax+$03]
00729AB5   0000                   add     [eax], al

*)
end;

end.