unit F2Func;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Buttons, DBCtrls, Grids, DBGrids,
  JvExDBGrids, JvDBGrid, ExtCtrls;
  
type
  TFrmF2Funcoes=class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    Panel3: TPanel;
    GrFuncoes: TJvDBGrid;
    Label2: TLabel;
    EdDescricao: TEdit;
    meFuncao: TDBMemo;
    Label3: TLabel;
    BitBtn2: TBitBtn;
    BitBtn3: TBitBtn;
    ckPartes: TCheckBox;
    BitBtn4: TBitBtn;
    Label1: TLabel;
    EdNome: TEdit;
    BitBtn1: TBitBtn;
    Label4: TLabel;
    EdCodigo: TEdit;
    procedure EdDescricaoChange(Sender : TObject);
    procedure EdCodigoChange(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure BitBtn3Click(Sender : TObject);
    procedure GrFuncoesTitleBtnClick(Sender : TObject);
    procedure EdDescricaoKeyDown(Sender : TObject);
    procedure EdNomeChange(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure _PROC_0068EA66(Sender : TObject);
    procedure _PROC_0068EBFD(Sender : TObject);
    procedure _PROC_0068EC1A(Sender : TObject);
    procedure _PROC_0068ED02(Sender : TObject);
    procedure _PROC_0068F005(Sender : TObject);
    procedure _PROC_0068F022(Sender : TObject);
    procedure _PROC_0068F40E(Sender : TObject);
    procedure _PROC_0068F49D(Sender : TObject);
    procedure _PROC_0068F4CC(Sender : TObject);
    procedure _PROC_0068F4D4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmF2Funcoes: TFrmF2Funcoes;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmF2Funcoes.EdDescricaoChange(Sender : TObject);
begin
(*
0068E708   55                     push    ebp
0068E709   8BEC                   mov     ebp, esp
0068E70B   B90B000000             mov     ecx, $0000000B
0068E710   6A00                   push    $00
0068E712   6A00                   push    $00
0068E714   49                     dec     ecx
0068E715   75F9                   jnz     0068E710
0068E717   51                     push    ecx
0068E718   53                     push    ebx
0068E719   8BD8                   mov     ebx, eax
0068E71B   33C0                   xor     eax, eax
0068E71D   55                     push    ebp

* Possible String Reference to: 'éXc×ÿë‘[‹å]Ã'
|
0068E71E   68DBE96800             push    $0068E9DB

***** TRY
|
0068E723   64FF30                 push    dword ptr fs:[eax]
0068E726   648920                 mov     fs:[eax], esp
0068E729   803D58897D0000         cmp     byte ptr [$007D8958], $00
0068E730   0F8443010000           jz      0068E879
0068E736   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E739   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E73F   E8884FE0FF             call    004936CC
0068E744   837DFC00               cmp     dword ptr [ebp-$04], +$00
0068E748   0F84D9000000           jz      0068E827

* Reference to control TFrmF2Funcoes.ckPartes : TCheckBox
|
0068E74E   8B8320030000           mov     eax, [ebx+$0320]
0068E754   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0068E756   FF92C8000000           call    dword ptr [edx+$00C8]
0068E75C   84C0                   test    al, al
0068E75E   0F8488000000           jz      0068E7EC

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068E764   68F0E96800             push    $0068E9F0
0068E769   8D55F4                 lea     edx, [ebp-$0C]
0068E76C   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068E771   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068E773   E8A8531100             call    007A3B20
0068E778   FF75F4                 push    dword ptr [ebp-$0C]

* Possible String Reference to: ')) AND DESCRICAO LIKE '
|
0068E77B   6818EA6800             push    $0068EA18
0068E780   6838EA6800             push    $0068EA38
0068E785   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E788   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E78E   E8394FE0FF             call    004936CC
0068E793   FF75E8                 push    dword ptr [ebp-$18]
0068E796   6838EA6800             push    $0068EA38
0068E79B   8D45EC                 lea     eax, [ebp-$14]
0068E79E   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068E7A3   E87470D7FF             call    0040581C
0068E7A8   8B45EC                 mov     eax, [ebp-$14]
0068E7AB   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068E7AE   E86D531100             call    007A3B20
0068E7B3   FF75F0                 push    dword ptr [ebp-$10]
0068E7B6   8D45F8                 lea     eax, [ebp-$08]
0068E7B9   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0068E7BE   E85970D7FF             call    0040581C
0068E7C3   8B45F8                 mov     eax, [ebp-$08]
0068E7C6   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068E7C7   6844EA6800             push    $0068EA44
0068E7CC   6A01                   push    $01
0068E7CE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E7D3   8B00                   mov     eax, [eax]
0068E7D5   8B4058                 mov     eax, [eax+$58]
0068E7D8   B958EA6800             mov     ecx, $0068EA58

* Possible String Reference to: 'FUNCOES'
|
0068E7DD   BA64EA6800             mov     edx, $0068EA64

|
0068E7E2   E881921100             call    007A7A68
0068E7E7   E97A010000             jmp     0068E966
0068E7EC   A06CEA6800             mov     al, byte ptr [$0068EA6C]
0068E7F1   50                     push    eax
0068E7F2   8D55D4                 lea     edx, [ebp-$2C]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E7F5   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E7FB   E8CC4EE0FF             call    004936CC
0068E800   8B55D4                 mov     edx, [ebp-$2C]
0068E803   8D45D8                 lea     eax, [ebp-$28]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068E806   E8B9A4D8FF             call    00418CC4
0068E80B   8D4DD8                 lea     ecx, [ebp-$28]
0068E80E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E813   8B00                   mov     eax, [eax]
0068E815   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Descricao'
|
0068E818   BA78EA6800             mov     edx, $0068EA78

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068E81D   E8D69B1100             call    007A83F8
0068E822   E93F010000             jmp     0068E966

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068E827   68F0E96800             push    $0068E9F0
0068E82C   8D55CC                 lea     edx, [ebp-$34]
0068E82F   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068E834   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068E836   E8E5521100             call    007A3B20
0068E83B   FF75CC                 push    dword ptr [ebp-$34]
0068E83E   688CEA6800             push    $0068EA8C
0068E843   8D45D0                 lea     eax, [ebp-$30]
0068E846   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068E84B   E8CC6FD7FF             call    0040581C
0068E850   8B45D0                 mov     eax, [ebp-$30]
0068E853   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068E854   6844EA6800             push    $0068EA44
0068E859   6A01                   push    $01
0068E85B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E860   8B00                   mov     eax, [eax]
0068E862   8B4058                 mov     eax, [eax+$58]
0068E865   B958EA6800             mov     ecx, $0068EA58

* Possible String Reference to: 'FUNCOES'
|
0068E86A   BA64EA6800             mov     edx, $0068EA64

|
0068E86F   E8F4911100             call    007A7A68
0068E874   E9ED000000             jmp     0068E966
0068E879   8D55C8                 lea     edx, [ebp-$38]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E87C   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E882   E8454EE0FF             call    004936CC
0068E887   837DC800               cmp     dword ptr [ebp-$38], +$00
0068E88B   0F84B3000000           jz      0068E944

* Reference to control TFrmF2Funcoes.ckPartes : TCheckBox
|
0068E891   8B8320030000           mov     eax, [ebx+$0320]
0068E897   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0068E899   FF92C8000000           call    dword ptr [edx+$00C8]
0068E89F   84C0                   test    al, al
0068E8A1   7469                   jz      0068E90C
0068E8A3   6838EA6800             push    $0068EA38
0068E8A8   8D55B8                 lea     edx, [ebp-$48]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E8AB   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E8B1   E8164EE0FF             call    004936CC
0068E8B6   FF75B8                 push    dword ptr [ebp-$48]
0068E8B9   6838EA6800             push    $0068EA38
0068E8BE   8D45BC                 lea     eax, [ebp-$44]
0068E8C1   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068E8C6   E8516FD7FF             call    0040581C
0068E8CB   8B45BC                 mov     eax, [ebp-$44]
0068E8CE   8D55C0                 lea     edx, [ebp-$40]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068E8D1   E84A521100             call    007A3B20
0068E8D6   8B4DC0                 mov     ecx, [ebp-$40]
0068E8D9   8D45C4                 lea     eax, [ebp-$3C]

* Possible String Reference to: 'DESCRICAO LIKE '
|
0068E8DC   BA98EA6800             mov     edx, $0068EA98

* Reference to: System.@LStrCat3;
|
0068E8E1   E8C26ED7FF             call    004057A8
0068E8E6   8B45C4                 mov     eax, [ebp-$3C]
0068E8E9   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068E8EA   6844EA6800             push    $0068EA44
0068E8EF   6A01                   push    $01
0068E8F1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E8F6   8B00                   mov     eax, [eax]
0068E8F8   8B4058                 mov     eax, [eax+$58]
0068E8FB   B958EA6800             mov     ecx, $0068EA58

* Possible String Reference to: 'FUNCOES'
|
0068E900   BA64EA6800             mov     edx, $0068EA64

|
0068E905   E85E911100             call    007A7A68
0068E90A   EB5A                   jmp     0068E966
0068E90C   A06CEA6800             mov     al, byte ptr [$0068EA6C]
0068E911   50                     push    eax
0068E912   8D55A4                 lea     edx, [ebp-$5C]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068E915   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068E91B   E8AC4DE0FF             call    004936CC
0068E920   8B55A4                 mov     edx, [ebp-$5C]
0068E923   8D45A8                 lea     eax, [ebp-$58]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068E926   E899A3D8FF             call    00418CC4
0068E92B   8D4DA8                 lea     ecx, [ebp-$58]
0068E92E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E933   8B00                   mov     eax, [eax]
0068E935   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Descricao'
|
0068E938   BA78EA6800             mov     edx, $0068EA78

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068E93D   E8B69A1100             call    007A83F8
0068E942   EB22                   jmp     0068E966
0068E944   6A00                   push    $00

* Possible String Reference to: 'DESCRICAO'
|
0068E946   6844EA6800             push    $0068EA44
0068E94B   6A01                   push    $01
0068E94D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068E952   8B00                   mov     eax, [eax]
0068E954   8B4058                 mov     eax, [eax+$58]
0068E957   B958EA6800             mov     ecx, $0068EA58

* Possible String Reference to: 'FUNCOES'
|
0068E95C   BA64EA6800             mov     edx, $0068EA64

|
0068E961   E802911100             call    007A7A68
0068E966   33C0                   xor     eax, eax
0068E968   5A                     pop     edx
0068E969   59                     pop     ecx
0068E96A   59                     pop     ecx
0068E96B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0068E96E   68E2E96800             push    $0068E9E2
0068E973   8D45A4                 lea     eax, [ebp-$5C]

* Reference to: System.@LStrClr(void;void);
|
0068E976   E8216BD7FF             call    0040549C
0068E97B   8D45A8                 lea     eax, [ebp-$58]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068E97E   E8F55BD8FF             call    00414578
0068E983   8D45B8                 lea     eax, [ebp-$48]

* Reference to: System.@LStrClr(void;void);
|
0068E986   E8116BD7FF             call    0040549C
0068E98B   8D45BC                 lea     eax, [ebp-$44]
0068E98E   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068E993   E8286BD7FF             call    004054C0
0068E998   8D45C8                 lea     eax, [ebp-$38]

* Reference to: System.@LStrClr(void;void);
|
0068E99B   E8FC6AD7FF             call    0040549C
0068E9A0   8D45CC                 lea     eax, [ebp-$34]
0068E9A3   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068E9A8   E8136BD7FF             call    004054C0
0068E9AD   8D45D4                 lea     eax, [ebp-$2C]

* Reference to: System.@LStrClr(void;void);
|
0068E9B0   E8E76AD7FF             call    0040549C
0068E9B5   8D45D8                 lea     eax, [ebp-$28]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068E9B8   E8BB5BD8FF             call    00414578
0068E9BD   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.@LStrClr(void;void);
|
0068E9C0   E8D76AD7FF             call    0040549C
0068E9C5   8D45EC                 lea     eax, [ebp-$14]
0068E9C8   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068E9CD   E8EE6AD7FF             call    004054C0
0068E9D2   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068E9D5   E8C26AD7FF             call    0040549C
0068E9DA   C3                     ret


* Reference to: System.@HandleFinally;
|
0068E9DB   E95863D7FF             jmp     00404D38
0068E9E0   EB91                   jmp     0068E973

****** END
|
0068E9E2   5B                     pop     ebx
0068E9E3   8BE5                   mov     esp, ebp
0068E9E5   5D                     pop     ebp
0068E9E6   C3                     ret

*)
end;

procedure TFrmF2Funcoes.EdCodigoChange(Sender : TObject);
begin
(*
0068EAA8   55                     push    ebp
0068EAA9   8BEC                   mov     ebp, esp
0068EAAB   B906000000             mov     ecx, $00000006
0068EAB0   6A00                   push    $00
0068EAB2   6A00                   push    $00
0068EAB4   49                     dec     ecx
0068EAB5   75F9                   jnz     0068EAB0
0068EAB7   53                     push    ebx
0068EAB8   8BD8                   mov     ebx, eax
0068EABA   33C0                   xor     eax, eax
0068EABC   55                     push    ebp

* Possible String Reference to: 'éia×ÿëË[‹å]Ã'
|
0068EABD   68CAEB6800             push    $0068EBCA

***** TRY
|
0068EAC2   64FF30                 push    dword ptr fs:[eax]
0068EAC5   648920                 mov     fs:[eax], esp
0068EAC8   803D58897D0000         cmp     byte ptr [$007D8958], $00
0068EACF   7450                   jz      0068EB21
0068EAD1   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmF2Funcoes.EdCodigo : TEdit
|
0068EAD4   8B8338030000           mov     eax, [ebx+$0338]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EADA   E8ED4BE0FF             call    004936CC
0068EADF   837DFC00               cmp     dword ptr [ebp-$04], +$00
0068EAE3   0F84A6000000           jz      0068EB8F
0068EAE9   A0D8EB6800             mov     al, byte ptr [$0068EBD8]
0068EAEE   50                     push    eax
0068EAEF   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TFrmF2Funcoes.EdCodigo : TEdit
|
0068EAF2   8B8338030000           mov     eax, [ebx+$0338]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EAF8   E8CF4BE0FF             call    004936CC
0068EAFD   8B55E8                 mov     edx, [ebp-$18]
0068EB00   8D45EC                 lea     eax, [ebp-$14]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068EB03   E8BCA1D8FF             call    00418CC4
0068EB08   8D4DEC                 lea     ecx, [ebp-$14]
0068EB0B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EB10   8B00                   mov     eax, [eax]
0068EB12   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CodFuncao'
|
0068EB15   BAE4EB6800             mov     edx, $0068EBE4

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068EB1A   E8D9981100             call    007A83F8
0068EB1F   EB6E                   jmp     0068EB8F
0068EB21   8D55E4                 lea     edx, [ebp-$1C]

* Reference to control TFrmF2Funcoes.EdCodigo : TEdit
|
0068EB24   8B8338030000           mov     eax, [ebx+$0338]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EB2A   E89D4BE0FF             call    004936CC
0068EB2F   837DE400               cmp     dword ptr [ebp-$1C], +$00
0068EB33   7438                   jz      0068EB6D
0068EB35   A0D8EB6800             mov     al, byte ptr [$0068EBD8]
0068EB3A   50                     push    eax
0068EB3B   8D55D0                 lea     edx, [ebp-$30]

* Reference to control TFrmF2Funcoes.EdCodigo : TEdit
|
0068EB3E   8B8338030000           mov     eax, [ebx+$0338]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EB44   E8834BE0FF             call    004936CC
0068EB49   8B55D0                 mov     edx, [ebp-$30]
0068EB4C   8D45D4                 lea     eax, [ebp-$2C]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068EB4F   E870A1D8FF             call    00418CC4
0068EB54   8D4DD4                 lea     ecx, [ebp-$2C]
0068EB57   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EB5C   8B00                   mov     eax, [eax]
0068EB5E   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'CODFUNCAO'
|
0068EB61   BAF8EB6800             mov     edx, $0068EBF8

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068EB66   E88D981100             call    007A83F8
0068EB6B   EB22                   jmp     0068EB8F
0068EB6D   6A00                   push    $00

* Possible String Reference to: 'CODFUNCAO'
|
0068EB6F   68F8EB6800             push    $0068EBF8
0068EB74   6A01                   push    $01
0068EB76   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EB7B   8B00                   mov     eax, [eax]
0068EB7D   8B4058                 mov     eax, [eax+$58]
0068EB80   B90CEC6800             mov     ecx, $0068EC0C

* Possible String Reference to: 'FUNCOES'
|
0068EB85   BA18EC6800             mov     edx, $0068EC18

|
0068EB8A   E8D98E1100             call    007A7A68
0068EB8F   33C0                   xor     eax, eax
0068EB91   5A                     pop     edx
0068EB92   59                     pop     ecx
0068EB93   59                     pop     ecx
0068EB94   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0068EB97   68D1EB6800             push    $0068EBD1
0068EB9C   8D45D0                 lea     eax, [ebp-$30]

* Reference to: System.@LStrClr(void;void);
|
0068EB9F   E8F868D7FF             call    0040549C
0068EBA4   8D45D4                 lea     eax, [ebp-$2C]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068EBA7   E8CC59D8FF             call    00414578
0068EBAC   8D45E4                 lea     eax, [ebp-$1C]
0068EBAF   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068EBB4   E80769D7FF             call    004054C0
0068EBB9   8D45EC                 lea     eax, [ebp-$14]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068EBBC   E8B759D8FF             call    00414578
0068EBC1   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068EBC4   E8D368D7FF             call    0040549C
0068EBC9   C3                     ret


* Reference to: System.@HandleFinally;
|
0068EBCA   E96961D7FF             jmp     00404D38
0068EBCF   EBCB                   jmp     0068EB9C

****** END
|
0068EBD1   5B                     pop     ebx
0068EBD2   8BE5                   mov     esp, ebp
0068EBD4   5D                     pop     ebp
0068EBD5   C3                     ret

*)
end;

procedure TFrmF2Funcoes.FormShow(Sender : TObject);
begin
(*
0068EC20   55                     push    ebp
0068EC21   8BEC                   mov     ebp, esp
0068EC23   6A00                   push    $00
0068EC25   6A00                   push    $00
0068EC27   33C0                   xor     eax, eax
0068EC29   55                     push    ebp

* Possible String Reference to: 'éi`×ÿëëYY]Ã'
|
0068EC2A   68CAEC6800             push    $0068ECCA

***** TRY
|
0068EC2F   64FF30                 push    dword ptr fs:[eax]
0068EC32   648920                 mov     fs:[eax], esp
0068EC35   803D58897D0000         cmp     byte ptr [$007D8958], $00
0068EC3C   7524                   jnz     0068EC62
0068EC3E   6A00                   push    $00

* Possible String Reference to: 'DESCRICAO'
|
0068EC40   68E0EC6800             push    $0068ECE0
0068EC45   6A01                   push    $01
0068EC47   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EC4C   8B00                   mov     eax, [eax]
0068EC4E   8B4058                 mov     eax, [eax+$58]
0068EC51   B9F4EC6800             mov     ecx, $0068ECF4

* Possible String Reference to: 'FUNCOES'
|
0068EC56   BA00ED6800             mov     edx, $0068ED00

|
0068EC5B   E8088E1100             call    007A7A68
0068EC60   EB4D                   jmp     0068ECAF

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068EC62   6810ED6800             push    $0068ED10
0068EC67   8D55F8                 lea     edx, [ebp-$08]
0068EC6A   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068EC6F   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EC71   E8AA4E1100             call    007A3B20
0068EC76   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: '))'
|
0068EC79   6838ED6800             push    $0068ED38
0068EC7E   8D45FC                 lea     eax, [ebp-$04]
0068EC81   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068EC86   E8916BD7FF             call    0040581C
0068EC8B   8B45FC                 mov     eax, [ebp-$04]
0068EC8E   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068EC8F   68E0EC6800             push    $0068ECE0
0068EC94   6A01                   push    $01
0068EC96   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EC9B   8B00                   mov     eax, [eax]
0068EC9D   8B4058                 mov     eax, [eax+$58]
0068ECA0   B9F4EC6800             mov     ecx, $0068ECF4

* Possible String Reference to: 'FUNCOES'
|
0068ECA5   BA00ED6800             mov     edx, $0068ED00

|
0068ECAA   E8B98D1100             call    007A7A68
0068ECAF   33C0                   xor     eax, eax
0068ECB1   5A                     pop     edx
0068ECB2   59                     pop     ecx
0068ECB3   59                     pop     ecx
0068ECB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'YY]Ã'
|
0068ECB7   68D1EC6800             push    $0068ECD1
0068ECBC   8D45F8                 lea     eax, [ebp-$08]
0068ECBF   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068ECC4   E8F767D7FF             call    004054C0
0068ECC9   C3                     ret


* Reference to: System.@HandleFinally;
|
0068ECCA   E96960D7FF             jmp     00404D38
0068ECCF   EBEB                   jmp     0068ECBC

****** END
|
0068ECD1   59                     pop     ecx
0068ECD2   59                     pop     ecx
0068ECD3   5D                     pop     ebp
0068ECD4   C3                     ret

*)
end;

procedure TFrmF2Funcoes.BitBtn3Click(Sender : TObject);
begin
(*
0068ED3C   55                     push    ebp
0068ED3D   8BEC                   mov     ebp, esp
0068ED3F   53                     push    ebx
0068ED40   8BD8                   mov     ebx, eax
0068ED42   8BCB                   mov     ecx, ebx
0068ED44   B201                   mov     dl, $01

* Reference to class TFrmDefFuncoes
|
0068ED46   A14CBE6800             mov     eax, dword ptr [$0068BE4C]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0068ED4B   E8C0F1E1FF             call    004ADF10
0068ED50   8B1548B67D00           mov     edx, [$007DB648]
0068ED56   8902                   mov     [edx], eax
0068ED58   A148B67D00             mov     eax, dword ptr [$007DB648]
0068ED5D   8B00                   mov     eax, [eax]
0068ED5F   8B10                   mov     edx, [eax]
0068ED61   FF92EC000000           call    dword ptr [edx+$00EC]
0068ED67   A148B67D00             mov     eax, dword ptr [$007DB648]
0068ED6C   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0068ED6E   E82958D7FF             call    0040459C
0068ED73   5B                     pop     ebx
0068ED74   5D                     pop     ebp
0068ED75   C3                     ret

*)
end;

procedure TFrmF2Funcoes.GrFuncoesTitleBtnClick(Sender : TObject);
begin
(*
0068ED78   55                     push    ebp
0068ED79   8BEC                   mov     ebp, esp
0068ED7B   51                     push    ecx
0068ED7C   B907000000             mov     ecx, $00000007
0068ED81   6A00                   push    $00
0068ED83   6A00                   push    $00
0068ED85   49                     dec     ecx
0068ED86   75F9                   jnz     0068ED81
0068ED88   874DFC                 xchg    [ebp-$04], ecx
0068ED8B   53                     push    ebx
0068ED8C   8BD8                   mov     ebx, eax
0068ED8E   33C0                   xor     eax, eax
0068ED90   55                     push    ebp
0068ED91   6893EF6800             push    $0068EF93

***** TRY
|
0068ED96   64FF30                 push    dword ptr fs:[eax]
0068ED99   648920                 mov     fs:[eax], esp
0068ED9C   83E901                 sub     ecx, +$01
0068ED9F   7212                   jb      0068EDB3
0068EDA1   0F8494000000           jz      0068EE3B
0068EDA7   49                     dec     ecx
0068EDA8   0F8415010000           jz      0068EEC3
0068EDAE   E993010000             jmp     0068EF46

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068EDB3   68ACEF6800             push    $0068EFAC
0068EDB8   8D55F8                 lea     edx, [ebp-$08]
0068EDBB   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068EDC0   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EDC2   E8594D1100             call    007A3B20
0068EDC7   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ')) AND DESCRICAO LIKE '
|
0068EDCA   68D4EF6800             push    $0068EFD4
0068EDCF   68F4EF6800             push    $0068EFF4
0068EDD4   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068EDD7   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EDDD   E8EA48E0FF             call    004936CC
0068EDE2   FF75EC                 push    dword ptr [ebp-$14]
0068EDE5   68F4EF6800             push    $0068EFF4
0068EDEA   8D45F0                 lea     eax, [ebp-$10]
0068EDED   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068EDF2   E8256AD7FF             call    0040581C
0068EDF7   8B45F0                 mov     eax, [ebp-$10]
0068EDFA   8D55F4                 lea     edx, [ebp-$0C]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EDFD   E81E4D1100             call    007A3B20
0068EE02   FF75F4                 push    dword ptr [ebp-$0C]
0068EE05   8D45FC                 lea     eax, [ebp-$04]
0068EE08   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0068EE0D   E80A6AD7FF             call    0040581C
0068EE12   8B45FC                 mov     eax, [ebp-$04]
0068EE15   50                     push    eax

* Possible String Reference to: 'CODFUNCAO'
|
0068EE16   6800F06800             push    $0068F000
0068EE1B   6A01                   push    $01
0068EE1D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EE22   8B00                   mov     eax, [eax]
0068EE24   8B4058                 mov     eax, [eax+$58]
0068EE27   B914F06800             mov     ecx, $0068F014

* Possible String Reference to: 'FUNCOES'
|
0068EE2C   BA20F06800             mov     edx, $0068F020

|
0068EE31   E8328C1100             call    007A7A68
0068EE36   E90B010000             jmp     0068EF46

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068EE3B   68ACEF6800             push    $0068EFAC
0068EE40   8D55E4                 lea     edx, [ebp-$1C]
0068EE43   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068EE48   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EE4A   E8D14C1100             call    007A3B20
0068EE4F   FF75E4                 push    dword ptr [ebp-$1C]

* Possible String Reference to: ')) AND DESCRICAO LIKE '
|
0068EE52   68D4EF6800             push    $0068EFD4
0068EE57   68F4EF6800             push    $0068EFF4
0068EE5C   8D55D8                 lea     edx, [ebp-$28]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068EE5F   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EE65   E86248E0FF             call    004936CC
0068EE6A   FF75D8                 push    dword ptr [ebp-$28]
0068EE6D   68F4EF6800             push    $0068EFF4
0068EE72   8D45DC                 lea     eax, [ebp-$24]
0068EE75   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068EE7A   E89D69D7FF             call    0040581C
0068EE7F   8B45DC                 mov     eax, [ebp-$24]
0068EE82   8D55E0                 lea     edx, [ebp-$20]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EE85   E8964C1100             call    007A3B20
0068EE8A   FF75E0                 push    dword ptr [ebp-$20]
0068EE8D   8D45E8                 lea     eax, [ebp-$18]
0068EE90   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0068EE95   E88269D7FF             call    0040581C
0068EE9A   8B45E8                 mov     eax, [ebp-$18]
0068EE9D   50                     push    eax

* Possible String Reference to: 'NOME'
|
0068EE9E   6830F06800             push    $0068F030
0068EEA3   6A01                   push    $01
0068EEA5   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EEAA   8B00                   mov     eax, [eax]
0068EEAC   8B4058                 mov     eax, [eax+$58]
0068EEAF   B914F06800             mov     ecx, $0068F014

* Possible String Reference to: 'FUNCOES'
|
0068EEB4   BA20F06800             mov     edx, $0068F020

|
0068EEB9   E8AA8B1100             call    007A7A68
0068EEBE   E983000000             jmp     0068EF46

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068EEC3   68ACEF6800             push    $0068EFAC
0068EEC8   8D55D0                 lea     edx, [ebp-$30]
0068EECB   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068EED0   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EED2   E8494C1100             call    007A3B20
0068EED7   FF75D0                 push    dword ptr [ebp-$30]

* Possible String Reference to: ')) AND DESCRICAO LIKE '
|
0068EEDA   68D4EF6800             push    $0068EFD4
0068EEDF   68F4EF6800             push    $0068EFF4
0068EEE4   8D55C4                 lea     edx, [ebp-$3C]

* Reference to control TFrmF2Funcoes.EdDescricao : TEdit
|
0068EEE7   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068EEED   E8DA47E0FF             call    004936CC
0068EEF2   FF75C4                 push    dword ptr [ebp-$3C]
0068EEF5   68F4EF6800             push    $0068EFF4
0068EEFA   8D45C8                 lea     eax, [ebp-$38]
0068EEFD   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068EF02   E81569D7FF             call    0040581C
0068EF07   8B45C8                 mov     eax, [ebp-$38]
0068EF0A   8D55CC                 lea     edx, [ebp-$34]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EF0D   E80E4C1100             call    007A3B20
0068EF12   FF75CC                 push    dword ptr [ebp-$34]
0068EF15   8D45D4                 lea     eax, [ebp-$2C]
0068EF18   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0068EF1D   E8FA68D7FF             call    0040581C
0068EF22   8B45D4                 mov     eax, [ebp-$2C]
0068EF25   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068EF26   6840F06800             push    $0068F040
0068EF2B   6A01                   push    $01
0068EF2D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EF32   8B00                   mov     eax, [eax]
0068EF34   8B4058                 mov     eax, [eax+$58]
0068EF37   B914F06800             mov     ecx, $0068F014

* Possible String Reference to: 'FUNCOES'
|
0068EF3C   BA20F06800             mov     edx, $0068F020

|
0068EF41   E8228B1100             call    007A7A68
0068EF46   33C0                   xor     eax, eax
0068EF48   5A                     pop     edx
0068EF49   59                     pop     ecx
0068EF4A   59                     pop     ecx
0068EF4B   648910                 mov     fs:[eax], edx

****** FINALLY
|
0068EF4E   689AEF6800             push    $0068EF9A
0068EF53   8D45C4                 lea     eax, [ebp-$3C]

* Reference to: System.@LStrClr(void;void);
|
0068EF56   E84165D7FF             call    0040549C
0068EF5B   8D45C8                 lea     eax, [ebp-$38]
0068EF5E   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068EF63   E85865D7FF             call    004054C0
0068EF68   8D45D8                 lea     eax, [ebp-$28]

* Reference to: System.@LStrClr(void;void);
|
0068EF6B   E82C65D7FF             call    0040549C
0068EF70   8D45DC                 lea     eax, [ebp-$24]
0068EF73   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068EF78   E84365D7FF             call    004054C0
0068EF7D   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0068EF80   E81765D7FF             call    0040549C
0068EF85   8D45F0                 lea     eax, [ebp-$10]
0068EF88   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068EF8D   E82E65D7FF             call    004054C0
0068EF92   C3                     ret


* Reference to: System.@HandleFinally;
|
0068EF93   E9A05DD7FF             jmp     00404D38
0068EF98   EBB9                   jmp     0068EF53

****** END
|
0068EF9A   5B                     pop     ebx
0068EF9B   8BE5                   mov     esp, ebp
0068EF9D   5D                     pop     ebp
0068EF9E   C20400                 ret     $0004

*)
end;

procedure TFrmF2Funcoes.EdDescricaoKeyDown(Sender : TObject);
begin
(*
0068F04C   55                     push    ebp
0068F04D   8BEC                   mov     ebp, esp
0068F04F   66833926               cmp     word ptr [ecx], +$26
0068F053   7511                   jnz     0068F066
0068F055   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F05A   8B00                   mov     eax, [eax]
0068F05C   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Prior(TDataSet);
|
0068F05F   E808C3E5FF             call    004EB36C
0068F064   EB4D                   jmp     0068F0B3
0068F066   66833928               cmp     word ptr [ecx], +$28
0068F06A   7511                   jnz     0068F07D
0068F06C   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F071   8B00                   mov     eax, [eax]
0068F073   8B4058                 mov     eax, [eax+$58]

* Reference to: DB.TDataSet.Next(TDataSet);
|
0068F076   E8C9C2E5FF             call    004EB344
0068F07B   EB36                   jmp     0068F0B3
0068F07D   66833922               cmp     word ptr [ecx], +$22
0068F081   7516                   jnz     0068F099
0068F083   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F088   8B00                   mov     eax, [eax]
0068F08A   8B4058                 mov     eax, [eax+$58]
0068F08D   BA0A000000             mov     edx, $0000000A

* Reference to: DB.TDataSet.MoveBy(TDataSet;Integer):Integer;
|
0068F092   E809C1E5FF             call    004EB1A0
0068F097   EB1A                   jmp     0068F0B3
0068F099   66833921               cmp     word ptr [ecx], +$21
0068F09D   7514                   jnz     0068F0B3
0068F09F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F0A4   8B00                   mov     eax, [eax]
0068F0A6   8B4058                 mov     eax, [eax+$58]
0068F0A9   BAF6FFFFFF             mov     edx, $FFFFFFF6

* Reference to: DB.TDataSet.MoveBy(TDataSet;Integer):Integer;
|
0068F0AE   E8EDC0E5FF             call    004EB1A0
0068F0B3   5D                     pop     ebp
0068F0B4   C20400                 ret     $0004

*)
end;

procedure TFrmF2Funcoes.EdNomeChange(Sender : TObject);
begin
(*
0068F0B8   55                     push    ebp
0068F0B9   8BEC                   mov     ebp, esp
0068F0BB   B90B000000             mov     ecx, $0000000B
0068F0C0   6A00                   push    $00
0068F0C2   6A00                   push    $00
0068F0C4   49                     dec     ecx
0068F0C5   75F9                   jnz     0068F0C0
0068F0C7   51                     push    ecx
0068F0C8   53                     push    ebx
0068F0C9   8BD8                   mov     ebx, eax
0068F0CB   33C0                   xor     eax, eax
0068F0CD   55                     push    ebp

* Possible String Reference to: 'é¨Y×ÿë‘[‹å]Ã'
|
0068F0CE   688BF36800             push    $0068F38B

***** TRY
|
0068F0D3   64FF30                 push    dword ptr fs:[eax]
0068F0D6   648920                 mov     fs:[eax], esp
0068F0D9   803D58897D0000         cmp     byte ptr [$007D8958], $00
0068F0E0   0F8443010000           jz      0068F229
0068F0E6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F0E9   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F0EF   E8D845E0FF             call    004936CC
0068F0F4   837DFC00               cmp     dword ptr [ebp-$04], +$00
0068F0F8   0F84D9000000           jz      0068F1D7

* Reference to control TFrmF2Funcoes.ckPartes : TCheckBox
|
0068F0FE   8B8320030000           mov     eax, [ebx+$0320]
0068F104   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0068F106   FF92C8000000           call    dword ptr [edx+$00C8]
0068F10C   84C0                   test    al, al
0068F10E   0F8488000000           jz      0068F19C

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068F114   68A0F36800             push    $0068F3A0
0068F119   8D55F4                 lea     edx, [ebp-$0C]
0068F11C   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068F121   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068F123   E8F8491100             call    007A3B20
0068F128   FF75F4                 push    dword ptr [ebp-$0C]

* Possible String Reference to: ')) AND NOME LIKE '
|
0068F12B   68C8F36800             push    $0068F3C8
0068F130   68E4F36800             push    $0068F3E4
0068F135   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F138   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F13E   E88945E0FF             call    004936CC
0068F143   FF75E8                 push    dword ptr [ebp-$18]
0068F146   68E4F36800             push    $0068F3E4
0068F14B   8D45EC                 lea     eax, [ebp-$14]
0068F14E   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068F153   E8C466D7FF             call    0040581C
0068F158   8B45EC                 mov     eax, [ebp-$14]
0068F15B   8D55F0                 lea     edx, [ebp-$10]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068F15E   E8BD491100             call    007A3B20
0068F163   FF75F0                 push    dword ptr [ebp-$10]
0068F166   8D45F8                 lea     eax, [ebp-$08]
0068F169   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0068F16E   E8A966D7FF             call    0040581C
0068F173   8B45F8                 mov     eax, [ebp-$08]
0068F176   50                     push    eax

* Possible String Reference to: 'NOME'
|
0068F177   68F0F36800             push    $0068F3F0
0068F17C   6A01                   push    $01
0068F17E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F183   8B00                   mov     eax, [eax]
0068F185   8B4058                 mov     eax, [eax+$58]
0068F188   B900F46800             mov     ecx, $0068F400

* Possible String Reference to: 'FUNCOES'
|
0068F18D   BA0CF46800             mov     edx, $0068F40C

|
0068F192   E8D1881100             call    007A7A68
0068F197   E97A010000             jmp     0068F316
0068F19C   A014F46800             mov     al, byte ptr [$0068F414]
0068F1A1   50                     push    eax
0068F1A2   8D55D4                 lea     edx, [ebp-$2C]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F1A5   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F1AB   E81C45E0FF             call    004936CC
0068F1B0   8B55D4                 mov     edx, [ebp-$2C]
0068F1B3   8D45D8                 lea     eax, [ebp-$28]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068F1B6   E8099BD8FF             call    00418CC4
0068F1BB   8D4DD8                 lea     ecx, [ebp-$28]
0068F1BE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F1C3   8B00                   mov     eax, [eax]
0068F1C5   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'Nome'
|
0068F1C8   BA20F46800             mov     edx, $0068F420

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068F1CD   E826921100             call    007A83F8
0068F1D2   E93F010000             jmp     0068F316

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068F1D7   68A0F36800             push    $0068F3A0
0068F1DC   8D55CC                 lea     edx, [ebp-$34]
0068F1DF   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068F1E4   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068F1E6   E835491100             call    007A3B20
0068F1EB   FF75CC                 push    dword ptr [ebp-$34]

* Possible String Reference to: '))'
|
0068F1EE   6830F46800             push    $0068F430
0068F1F3   8D45D0                 lea     eax, [ebp-$30]
0068F1F6   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068F1FB   E81C66D7FF             call    0040581C
0068F200   8B45D0                 mov     eax, [ebp-$30]
0068F203   50                     push    eax

* Possible String Reference to: 'NOME'
|
0068F204   68F0F36800             push    $0068F3F0
0068F209   6A01                   push    $01
0068F20B   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F210   8B00                   mov     eax, [eax]
0068F212   8B4058                 mov     eax, [eax+$58]
0068F215   B900F46800             mov     ecx, $0068F400

* Possible String Reference to: 'FUNCOES'
|
0068F21A   BA0CF46800             mov     edx, $0068F40C

|
0068F21F   E844881100             call    007A7A68
0068F224   E9ED000000             jmp     0068F316
0068F229   8D55C8                 lea     edx, [ebp-$38]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F22C   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F232   E89544E0FF             call    004936CC
0068F237   837DC800               cmp     dword ptr [ebp-$38], +$00
0068F23B   0F84B3000000           jz      0068F2F4

* Reference to control TFrmF2Funcoes.ckPartes : TCheckBox
|
0068F241   8B8320030000           mov     eax, [ebx+$0320]
0068F247   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0068F249   FF92C8000000           call    dword ptr [edx+$00C8]
0068F24F   84C0                   test    al, al
0068F251   7469                   jz      0068F2BC
0068F253   68E4F36800             push    $0068F3E4
0068F258   8D55B8                 lea     edx, [ebp-$48]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F25B   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F261   E86644E0FF             call    004936CC
0068F266   FF75B8                 push    dword ptr [ebp-$48]
0068F269   68E4F36800             push    $0068F3E4
0068F26E   8D45BC                 lea     eax, [ebp-$44]
0068F271   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068F276   E8A165D7FF             call    0040581C
0068F27B   8B45BC                 mov     eax, [ebp-$44]
0068F27E   8D55C0                 lea     edx, [ebp-$40]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068F281   E89A481100             call    007A3B20
0068F286   8B4DC0                 mov     ecx, [ebp-$40]
0068F289   8D45C4                 lea     eax, [ebp-$3C]

* Possible String Reference to: 'NOME LIKE '
|
0068F28C   BA3CF46800             mov     edx, $0068F43C

* Reference to: System.@LStrCat3;
|
0068F291   E81265D7FF             call    004057A8
0068F296   8B45C4                 mov     eax, [ebp-$3C]
0068F299   50                     push    eax

* Possible String Reference to: 'NOME'
|
0068F29A   68F0F36800             push    $0068F3F0
0068F29F   6A01                   push    $01
0068F2A1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F2A6   8B00                   mov     eax, [eax]
0068F2A8   8B4058                 mov     eax, [eax+$58]
0068F2AB   B900F46800             mov     ecx, $0068F400

* Possible String Reference to: 'FUNCOES'
|
0068F2B0   BA0CF46800             mov     edx, $0068F40C

|
0068F2B5   E8AE871100             call    007A7A68
0068F2BA   EB5A                   jmp     0068F316
0068F2BC   A014F46800             mov     al, byte ptr [$0068F414]
0068F2C1   50                     push    eax
0068F2C2   8D55A4                 lea     edx, [ebp-$5C]

* Reference to control TFrmF2Funcoes.EdNome : TEdit
|
0068F2C5   8B832C030000           mov     eax, [ebx+$032C]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0068F2CB   E8FC43E0FF             call    004936CC
0068F2D0   8B55A4                 mov     edx, [ebp-$5C]
0068F2D3   8D45A8                 lea     eax, [ebp-$58]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0068F2D6   E8E999D8FF             call    00418CC4
0068F2DB   8D4DA8                 lea     ecx, [ebp-$58]
0068F2DE   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F2E3   8B00                   mov     eax, [eax]
0068F2E5   8B4058                 mov     eax, [eax+$58]

* Possible String Reference to: 'NOME'
|
0068F2E8   BAF0F36800             mov     edx, $0068F3F0

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0068F2ED   E806911100             call    007A83F8
0068F2F2   EB22                   jmp     0068F316
0068F2F4   6A00                   push    $00

* Possible String Reference to: 'NOME'
|
0068F2F6   68F0F36800             push    $0068F3F0
0068F2FB   6A01                   push    $01
0068F2FD   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068F302   8B00                   mov     eax, [eax]
0068F304   8B4058                 mov     eax, [eax+$58]
0068F307   B900F46800             mov     ecx, $0068F400

* Possible String Reference to: 'FUNCOES'
|
0068F30C   BA0CF46800             mov     edx, $0068F40C

|
0068F311   E852871100             call    007A7A68
0068F316   33C0                   xor     eax, eax
0068F318   5A                     pop     edx
0068F319   59                     pop     ecx
0068F31A   59                     pop     ecx
0068F31B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0068F31E   6892F36800             push    $0068F392
0068F323   8D45A4                 lea     eax, [ebp-$5C]

* Reference to: System.@LStrClr(void;void);
|
0068F326   E87161D7FF             call    0040549C
0068F32B   8D45A8                 lea     eax, [ebp-$58]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068F32E   E84552D8FF             call    00414578
0068F333   8D45B8                 lea     eax, [ebp-$48]

* Reference to: System.@LStrClr(void;void);
|
0068F336   E86161D7FF             call    0040549C
0068F33B   8D45BC                 lea     eax, [ebp-$44]
0068F33E   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068F343   E87861D7FF             call    004054C0
0068F348   8D45C8                 lea     eax, [ebp-$38]

* Reference to: System.@LStrClr(void;void);
|
0068F34B   E84C61D7FF             call    0040549C
0068F350   8D45CC                 lea     eax, [ebp-$34]
0068F353   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068F358   E86361D7FF             call    004054C0
0068F35D   8D45D4                 lea     eax, [ebp-$2C]

* Reference to: System.@LStrClr(void;void);
|
0068F360   E83761D7FF             call    0040549C
0068F365   8D45D8                 lea     eax, [ebp-$28]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0068F368   E80B52D8FF             call    00414578
0068F36D   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.@LStrClr(void;void);
|
0068F370   E82761D7FF             call    0040549C
0068F375   8D45EC                 lea     eax, [ebp-$14]
0068F378   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068F37D   E83E61D7FF             call    004054C0
0068F382   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0068F385   E81261D7FF             call    0040549C
0068F38A   C3                     ret


* Reference to: System.@HandleFinally;
|
0068F38B   E9A859D7FF             jmp     00404D38
0068F390   EB91                   jmp     0068F323

****** END
|
0068F392   5B                     pop     ebx
0068F393   8BE5                   mov     esp, ebp
0068F395   5D                     pop     ebp
0068F396   C3                     ret

*)
end;

procedure TFrmF2Funcoes.BitBtn1Click(Sender : TObject);
begin
(*
0068F448   55                     push    ebp
0068F449   8BEC                   mov     ebp, esp

* Possible String Reference to: 'teste'
|
0068F44B   B894F46800             mov     eax, $0068F494

* Reference to : TFrmInfoAtu._PROC_007AFBA0()
|
0068F450   E84B071200             call    007AFBA0
0068F455   84C0                   test    al, al
0068F457   7431                   jz      0068F48A
0068F459   33C9                   xor     ecx, ecx
0068F45B   B201                   mov     dl, $01

* Reference to class TFrmImpExpFuncoes
|
0068F45D   A1ACCA6800             mov     eax, dword ptr [$0068CAAC]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0068F462   E8A9EAE1FF             call    004ADF10
0068F467   8B15F89F7D00           mov     edx, [$007D9FF8]
0068F46D   8902                   mov     [edx], eax
0068F46F   A1F89F7D00             mov     eax, dword ptr [$007D9FF8]
0068F474   8B00                   mov     eax, [eax]
0068F476   8B10                   mov     edx, [eax]
0068F478   FF92EC000000           call    dword ptr [edx+$00EC]
0068F47E   A1F89F7D00             mov     eax, dword ptr [$007D9FF8]
0068F483   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0068F485   E81251D7FF             call    0040459C
0068F48A   5D                     pop     ebp
0068F48B   C3                     ret

*)
end;

procedure TFrmF2Funcoes._PROC_0068EA66(Sender : TObject);
begin
(*
0068EA66   4E                     dec     esi
0068EA67   43                     inc     ebx
0068EA68   4F                     dec     edi
0068EA69   45                     inc     ebp
0068EA6A   53                     push    ebx
0068EA6B   0003                   add     [ebx], al
0068EA6D   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068EBFD(Sender : TObject);
begin
(*
0068EBFD   4E                     dec     esi
0068EBFE   43                     inc     ebx
0068EBFF   41                     inc     ecx
0068EC00   4F                     dec     edi
0068EC01   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068EC1A(Sender : TObject);
begin
(*
0068EC1A   4E                     dec     esi
0068EC1B   43                     inc     ebx
0068EC1C   4F                     dec     edi
0068EC1D   45                     inc     ebp
0068EC1E   53                     push    ebx
0068EC1F   00558B                 add     [ebp-$75], dl
0068EC22   EC                     in      al, dx
0068EC23   6A00                   push    $00
0068EC25   6A00                   push    $00
0068EC27   33C0                   xor     eax, eax
0068EC29   55                     push    ebp

* Possible String Reference to: 'éi`×ÿëëYY]Ã'
|
0068EC2A   68CAEC6800             push    $0068ECCA

***** TRY
|
0068EC2F   64FF30                 push    dword ptr fs:[eax]
0068EC32   648920                 mov     fs:[eax], esp
0068EC35   803D58897D0000         cmp     byte ptr [$007D8958], $00
0068EC3C   7524                   jnz     0068EC62
0068EC3E   6A00                   push    $00

* Possible String Reference to: 'DESCRICAO'
|
0068EC40   68E0EC6800             push    $0068ECE0
0068EC45   6A01                   push    $01
0068EC47   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EC4C   8B00                   mov     eax, [eax]
0068EC4E   8B4058                 mov     eax, [eax+$58]
0068EC51   B9F4EC6800             mov     ecx, $0068ECF4

* Possible String Reference to: 'FUNCOES'
|
0068EC56   BA00ED6800             mov     edx, $0068ED00

|
0068EC5B   E8088E1100             call    007A7A68
0068EC60   EB4D                   jmp     0068ECAF

* Possible String Reference to: '((TELA = 'sistema') OR (TELA = '
|
0068EC62   6810ED6800             push    $0068ED10
0068EC67   8D55F8                 lea     edx, [ebp-$08]
0068EC6A   A1D8A97D00             mov     eax, dword ptr [$007DA9D8]
0068EC6F   8B00                   mov     eax, [eax]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
0068EC71   E8AA4E1100             call    007A3B20
0068EC76   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: '))'
|
0068EC79   6838ED6800             push    $0068ED38
0068EC7E   8D45FC                 lea     eax, [ebp-$04]
0068EC81   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrCatN;
|
0068EC86   E8916BD7FF             call    0040581C
0068EC8B   8B45FC                 mov     eax, [ebp-$04]
0068EC8E   50                     push    eax

* Possible String Reference to: 'DESCRICAO'
|
0068EC8F   68E0EC6800             push    $0068ECE0
0068EC94   6A01                   push    $01
0068EC96   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0068EC9B   8B00                   mov     eax, [eax]
0068EC9D   8B4058                 mov     eax, [eax+$58]
0068ECA0   B9F4EC6800             mov     ecx, $0068ECF4

* Possible String Reference to: 'FUNCOES'
|
0068ECA5   BA00ED6800             mov     edx, $0068ED00

|
0068ECAA   E8B98D1100             call    007A7A68
0068ECAF   33C0                   xor     eax, eax
0068ECB1   5A                     pop     edx
0068ECB2   59                     pop     ecx
0068ECB3   59                     pop     ecx
0068ECB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'YY]Ã'
|
0068ECB7   68D1EC6800             push    $0068ECD1
0068ECBC   8D45F8                 lea     eax, [ebp-$08]
0068ECBF   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0068ECC4   E8F767D7FF             call    004054C0
0068ECC9   C3                     ret


* Reference to: System.@HandleFinally;
|
0068ECCA   E96960D7FF             jmp     00404D38
0068ECCF   EBEB                   jmp     0068ECBC

****** END
|
0068ECD1   59                     pop     ecx
0068ECD2   59                     pop     ecx
0068ECD3   5D                     pop     ebp
0068ECD4   C3                     ret

*)
end;

procedure TFrmF2Funcoes._PROC_0068ED02(Sender : TObject);
begin
(*
0068ED02   4E                     dec     esi
0068ED03   43                     inc     ebx
0068ED04   4F                     dec     edi
0068ED05   45                     inc     ebp
0068ED06   53                     push    ebx
0068ED07   00FF                   add     bh, bh
0068ED09   FFFF                   DB  $FF, $FF  //      
0068ED0B   FF1F                   call    [edi]
0068ED0D   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068F005(Sender : TObject);
begin
(*
0068F005   4E                     dec     esi
0068F006   43                     inc     ebx
0068F007   41                     inc     ecx
0068F008   4F                     dec     edi
0068F009   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068F022(Sender : TObject);
begin
(*
0068F022   4E                     dec     esi
0068F023   43                     inc     ebx
0068F024   4F                     dec     edi
0068F025   45                     inc     ebp
0068F026   53                     push    ebx
0068F027   00FF                   add     bh, bh
0068F029   FFFF                   DB  $FF, $FF  //      
0068F02B   FF0400                 inc     dword ptr [eax+eax]
0068F02E   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068F40E(Sender : TObject);
begin
(*
0068F40E   4E                     dec     esi
0068F40F   43                     inc     ebx
0068F410   4F                     dec     edi
0068F411   45                     inc     ebp
0068F412   53                     push    ebx
0068F413   0003                   add     [ebx], al
0068F415   0000                   add     [eax], al

*)
end;

procedure TFrmF2Funcoes._PROC_0068F49D(Sender : TObject);
begin
(*
0068F49D   8BEC                   mov     ebp, esp
0068F49F   33C0                   xor     eax, eax
0068F4A1   55                     push    ebp

* Possible String Reference to: 'érX×ÿëø]Ã‹Àƒ-Àì}'
|
0068F4A2   68C1F46800             push    $0068F4C1

***** TRY
|
0068F4A7   64FF30                 push    dword ptr fs:[eax]
0068F4AA   648920                 mov     fs:[eax], esp
0068F4AD   FF05C0EC7D00           inc     dword ptr [$007DECC0]
0068F4B3   33C0                   xor     eax, eax
0068F4B5   5A                     pop     edx
0068F4B6   59                     pop     ecx
0068F4B7   59                     pop     ecx
0068F4B8   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-Àì}'
|
0068F4BB   68C8F46800             push    $0068F4C8
0068F4C0   C3                     ret


* Reference to: System.@HandleFinally;
|
0068F4C1   E97258D7FF             jmp     00404D38
0068F4C6   EBF8                   jmp     0068F4C0

****** END
|
0068F4C8   5D                     pop     ebp
0068F4C9   C3                     ret

*)
end;

procedure TFrmF2Funcoes._PROC_0068F4CC(Sender : TObject);
begin
(*
0068F4CC   832DC0EC7D0001         sub     dword ptr [$007DECC0], +$01
0068F4D3   C3                     ret

*)
end;

procedure TFrmF2Funcoes._PROC_0068F4D4(Sender : TObject);
begin
(*
0068F4D4   20F5                   and     ch, dh
0068F4D6   6800000000             push    $00000000
0068F4DB   0000                   add     [eax], al

*)
end;

end.