unit F2Geral;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Grids, DBGrids,
  JvExDBGrids, JvDBGrid, Mask, JvExMask, JvSpin, DBCtrls, Buttons;
  
type
  TFrmF2=class(TForm)
    Panel2: TPanel;
    GrF2: TJvDBGrid;
    BitBtn1: TBitBtn;
    btOK: TBitBtn;
    nbF2: TNotebook;
    lb1Campo1: TLabel;
    Ed1Campo1: TEdit;
    Ed2Campo1: TEdit;
    lb2Campo1: TLabel;
    Ed2Campo2: TEdit;
    lb2Campo2: TLabel;
    Ed3Campo2: TEdit;
    lb3Campo2: TLabel;
    Ed3Campo1: TEdit;
    lb3Campo1: TLabel;
    lb3Campo3: TLabel;
    Ed3Campo3: TEdit;
    lb4Campo1: TLabel;
    Ed4Campo1: TEdit;
    lb4Campo2: TLabel;
    Ed4Campo2: TEdit;
    lb4Campo3: TLabel;
    Ed4Campo3: TEdit;
    lb4Campo4: TLabel;
    Ed4Campo4: TEdit;
    lb5Campo4: TLabel;
    Ed5Campo4: TEdit;
    Ed5Campo3: TEdit;
    lb5Campo3: TLabel;
    lb5Campo2: TLabel;
    Ed5Campo2: TEdit;
    Ed5Campo1: TEdit;
    lb5Campo1: TLabel;
    lb5Campo5: TLabel;
    Ed5Campo5: TEdit;
    CkGenerico: TCheckBox;
    cbOrdem: TComboBox;
    lbOrdem: TLabel;
    btInfoAtu: TSpeedButton;
    nvF2: TDBNavigator;
    edGuia: TEdit;
    lbFSetor: TLabel;
    lbFGuia: TLabel;
    btVoltar: TButton;
    cbSetor: TComboBox;
    btLimpar: TButton;
    Bevel1: TBevel;
    Bevel2: TBevel;
    Bevel3: TBevel;
    Bevel4: TBevel;
    Bevel5: TBevel;
    ckMaiMin: TCheckBox;
    edNumRegs: TJvSpinEdit;
    Label1: TLabel;
    Bevel6: TBevel;
    sbCadastro: TSpeedButton;
    procedure sbFechaClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure ChecaTeclado(Sender : TObject);
    procedure TiraLetraCGC(Sender : TObject);
    procedure PesquisaCampo(Sender : TObject);
    procedure cbOrdemChange(Sender : TObject);
    procedure btInfoAtuClick(Sender : TObject);
    procedure GrF2DblClick(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormDestroy(Sender : TObject);
    procedure MudaIndice(Sender : TObject);
    procedure btVoltarClick(Sender : TObject);
    procedure btLimparClick(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure GrF2GetCellProps(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure btCadastrarClick(Sender : TObject);
    procedure sbCadastroClick(Sender : TObject);
    procedure _PROC_00639234(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmF2: TFrmF2;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmF2.sbFechaClick(Sender : TObject);
begin
(*
006391DC   55                     push    ebp
006391DD   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
006391DF   E8DC8EE7FF             call    004B20C0
006391E4   5D                     pop     ebp
006391E5   C3                     ret

*)
end;

procedure TFrmF2.FormShow(Sender : TObject);
begin
(*
006391E8   55                     push    ebp
006391E9   8BEC                   mov     ebp, esp
006391EB   53                     push    ebx
006391EC   8BD8                   mov     ebx, eax
006391EE   A188AE7D00             mov     eax, dword ptr [$007DAE88]
006391F3   C60000                 mov     byte ptr [eax], $00
006391F6   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
006391F8   E83F4A1700             call    007ADC3C
006391FD   8BC3                   mov     eax, ebx

|
006391FF   E84C1C0000             call    0063AE50
00639204   8BC3                   mov     eax, ebx

|
00639206   E815200000             call    0063B220
0063920B   8BC3                   mov     eax, ebx

|
0063920D   E87E2A0000             call    0063BC90
00639212   A1FCDC7D00             mov     eax, dword ptr [$007DDCFC]

* Reference to: DBAdapt.TBaseDataSetAdapterField.ImplCheckOrigValue(TBaseDataSetAdapterField;WebAdapt.IActionRequest;System.Integer);
|
00639217   E8682D0000             call    0063BF84
0063921C   833D1CDD7D0000         cmp     dword ptr [$007DDD1C], +$00
00639223   0F95C2                 setnz   dl

* Reference to control TFrmF2.sbCadastro : TSpeedButton
|
00639226   8B83D4030000           mov     eax, [ebx+$03D4]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
0063922C   E8BBA3E5FF             call    004935EC
00639231   5B                     pop     ebx
00639232   5D                     pop     ebp
00639233   C3                     ret

*)
end;

procedure TFrmF2.ChecaTeclado(Sender : TObject);
begin
(*
0063A668   55                     push    ebp
0063A669   8BEC                   mov     ebp, esp
0063A66B   53                     push    ebx
0063A66C   8BD9                   mov     ebx, ecx
0063A66E   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A673   8B00                   mov     eax, [eax]
0063A675   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
0063A678   E823E4EAFF             call    004E8AA0
0063A67D   84C0                   test    al, al
0063A67F   7464                   jz      0063A6E5
0063A681   66833B22               cmp     word ptr [ebx], +$22
0063A685   7516                   jnz     0063A69D
0063A687   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A68C   8B00                   mov     eax, [eax]
0063A68E   8B4060                 mov     eax, [eax+$60]
0063A691   BA0A000000             mov     edx, $0000000A

* Reference to: DB.TDataSet.MoveBy(TDataSet;Integer):Integer;
|
0063A696   E8050BEBFF             call    004EB1A0
0063A69B   EB48                   jmp     0063A6E5
0063A69D   66833B21               cmp     word ptr [ebx], +$21
0063A6A1   7516                   jnz     0063A6B9
0063A6A3   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A6A8   8B00                   mov     eax, [eax]
0063A6AA   8B4060                 mov     eax, [eax+$60]
0063A6AD   BAF6FFFFFF             mov     edx, $FFFFFFF6

* Reference to: DB.TDataSet.MoveBy(TDataSet;Integer):Integer;
|
0063A6B2   E8E90AEBFF             call    004EB1A0
0063A6B7   EB2C                   jmp     0063A6E5
0063A6B9   66833B28               cmp     word ptr [ebx], +$28
0063A6BD   7511                   jnz     0063A6D0
0063A6BF   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A6C4   8B00                   mov     eax, [eax]
0063A6C6   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.Next(TDataSet);
|
0063A6C9   E8760CEBFF             call    004EB344
0063A6CE   EB15                   jmp     0063A6E5
0063A6D0   66833B26               cmp     word ptr [ebx], +$26
0063A6D4   750F                   jnz     0063A6E5
0063A6D6   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A6DB   8B00                   mov     eax, [eax]
0063A6DD   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.Prior(TDataSet);
|
0063A6E0   E8870CEBFF             call    004EB36C
0063A6E5   5B                     pop     ebx
0063A6E6   5D                     pop     ebp
0063A6E7   C20400                 ret     $0004

*)
end;

procedure TFrmF2.TiraLetraCGC(Sender : TObject);
begin
(*
0063A6EC   55                     push    ebp
0063A6ED   8BEC                   mov     ebp, esp
0063A6EF   6A00                   push    $00
0063A6F1   53                     push    ebx
0063A6F2   56                     push    esi
0063A6F3   8BD9                   mov     ebx, ecx
0063A6F5   8BF2                   mov     esi, edx
0063A6F7   33C0                   xor     eax, eax
0063A6F9   55                     push    ebp

* Possible String Reference to: 'ÈÕ•‹ˇÎ^[Y]√'
|
0063A6FA   6866A76300             push    $0063A766

***** TRY
|
0063A6FF   64FF30                 push    dword ptr fs:[eax]
0063A702   648920                 mov     fs:[eax], esp
0063A705   8BC6                   mov     eax, esi

* Reference to class TEdit
|
0063A707   8B15A0FC4700           mov     edx, [$0047FCA0]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
0063A70D   E842A0DCFF             call    00404754
0063A712   8BF0                   mov     esi, eax
0063A714   803B41                 cmp     byte ptr [ebx], $41
0063A717   7205                   jb      0063A71E
0063A719   803B5A                 cmp     byte ptr [ebx], $5A
0063A71C   760A                   jbe     0063A728
0063A71E   803B61                 cmp     byte ptr [ebx], $61
0063A721   722D                   jb      0063A750
0063A723   803B7A                 cmp     byte ptr [ebx], $7A
0063A726   7728                   jnbe    0063A750
0063A728   A1F0DC7D00             mov     eax, dword ptr [$007DDCF0]
0063A72D   8B560C                 mov     edx, [esi+$0C]
0063A730   8B4490FC               mov     eax, [eax+edx*4-$04]
0063A734   8D55FC                 lea     edx, [ebp-$04]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
0063A737   E8ECFDDCFF             call    0040A528
0063A73C   8B55FC                 mov     edx, [ebp-$04]

* Possible String Reference to: 'CGC'
|
0063A73F   B87CA76300             mov     eax, $0063A77C

* Reference to: System.@LStrPos;
|
0063A744   E857B3DCFF             call    00405AA0
0063A749   85C0                   test    eax, eax
0063A74B   7403                   jz      0063A750
0063A74D   C60300                 mov     byte ptr [ebx], $00
0063A750   33C0                   xor     eax, eax
0063A752   5A                     pop     edx
0063A753   59                     pop     ecx
0063A754   59                     pop     ecx
0063A755   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]√'
|
0063A758   686DA76300             push    $0063A76D
0063A75D   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0063A760   E837ADDCFF             call    0040549C
0063A765   C3                     ret


* Reference to: System.@HandleFinally;
|
0063A766   E9CDA5DCFF             jmp     00404D38
0063A76B   EBF0                   jmp     0063A75D

****** END
|
0063A76D   5E                     pop     esi
0063A76E   5B                     pop     ebx
0063A76F   59                     pop     ecx
0063A770   5D                     pop     ebp
0063A771   C3                     ret

*)
end;

procedure TFrmF2.PesquisaCampo(Sender : TObject);
begin
(*
0063A780   55                     push    ebp
0063A781   8BEC                   mov     ebp, esp
0063A783   B90A000000             mov     ecx, $0000000A
0063A788   6A00                   push    $00
0063A78A   6A00                   push    $00
0063A78C   49                     dec     ecx
0063A78D   75F9                   jnz     0063A788
0063A78F   53                     push    ebx
0063A790   56                     push    esi
0063A791   57                     push    edi
0063A792   8BF2                   mov     esi, edx
0063A794   8945FC                 mov     [ebp-$04], eax
0063A797   33C0                   xor     eax, eax
0063A799   55                     push    ebp

* Possible String Reference to: 'ÈY¢‹ˇÈwˇˇˇ_^[ãÂ]√'
|
0063A79A   68DAAA6300             push    $0063AADA

***** TRY
|
0063A79F   64FF30                 push    dword ptr fs:[eax]
0063A7A2   648920                 mov     fs:[eax], esp
0063A7A5   8BC6                   mov     eax, esi

* Reference to class TEdit
|
0063A7A7   8B15A0FC4700           mov     edx, [$0047FCA0]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
0063A7AD   E8A29FDCFF             call    00404754
0063A7B2   8BD8                   mov     ebx, eax
0063A7B4   8D45F8                 lea     eax, [ebp-$08]
0063A7B7   8B15F0DC7D00           mov     edx, [$007DDCF0]
0063A7BD   8B4B0C                 mov     ecx, [ebx+$0C]
0063A7C0   8B548AFC               mov     edx, [edx+ecx*4-$04]

* Reference to: System.@LStrLAsg(void;void;void;void);
|
0063A7C4   E86BADDCFF             call    00405534
0063A7C9   8D55F4                 lea     edx, [ebp-$0C]
0063A7CC   8B45F8                 mov     eax, [ebp-$08]

* Reference to: SysUtils.LowerCase(AnsiString):AnsiString;
|
0063A7CF   E890FDDCFF             call    0040A564
0063A7D4   8B45F4                 mov     eax, [ebp-$0C]

* Possible String Reference to: 'numlcto'
|
0063A7D7   BAF4AA6300             mov     edx, $0063AAF4

* Reference to: System.@LStrCmp;
|
0063A7DC   E8C7B0DCFF             call    004058A8
0063A7E1   7542                   jnz     0063A825
0063A7E3   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A7E8   8B00                   mov     eax, [eax]
0063A7EA   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'NumLcto'
|
0063A7ED   BA04AB6300             mov     edx, $0063AB04

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063A7F2   E80DF4EAFF             call    004E9C04
0063A7F7   8D55F0                 lea     edx, [ebp-$10]
0063A7FA   8B08                   mov     ecx, [eax]
0063A7FC   FF5160                 call    dword ptr [ecx+$60]
0063A7FF   8B45F0                 mov     eax, [ebp-$10]

* Reference to: System.@LStrLen(String):Integer;
|
0063A802   E855AFDCFF             call    0040575C
0063A807   8BF8                   mov     edi, eax
0063A809   83EF02                 sub     edi, +$02
0063A80C   8D55EC                 lea     edx, [ebp-$14]
0063A80F   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A811   E8B68EE5FF             call    004936CC
0063A816   8B45EC                 mov     eax, [ebp-$14]

* Reference to: System.@LStrLen(String):Integer;
|
0063A819   E83EAFDCFF             call    0040575C
0063A81E   3BF8                   cmp     edi, eax
0063A820   0F9CC0                 setl    al
0063A823   EB5E                   jmp     0063A883
0063A825   8D55E8                 lea     edx, [ebp-$18]
0063A828   8B45F8                 mov     eax, [ebp-$08]

* Reference to: SysUtils.LowerCase(AnsiString):AnsiString;
|
0063A82B   E834FDDCFF             call    0040A564
0063A830   8B45E8                 mov     eax, [ebp-$18]

* Possible String Reference to: 'numpedido'
|
0063A833   BA14AB6300             mov     edx, $0063AB14

* Reference to: System.@LStrCmp;
|
0063A838   E86BB0DCFF             call    004058A8
0063A83D   7542                   jnz     0063A881
0063A83F   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063A844   8B00                   mov     eax, [eax]
0063A846   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'NumPedido'
|
0063A849   BA28AB6300             mov     edx, $0063AB28

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063A84E   E8B1F3EAFF             call    004E9C04
0063A853   8D55E4                 lea     edx, [ebp-$1C]
0063A856   8B08                   mov     ecx, [eax]
0063A858   FF5160                 call    dword ptr [ecx+$60]
0063A85B   8B45E4                 mov     eax, [ebp-$1C]

* Reference to: System.@LStrLen(String):Integer;
|
0063A85E   E8F9AEDCFF             call    0040575C
0063A863   8BF8                   mov     edi, eax
0063A865   83EF02                 sub     edi, +$02
0063A868   8D55E0                 lea     edx, [ebp-$20]
0063A86B   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A86D   E85A8EE5FF             call    004936CC
0063A872   8B45E0                 mov     eax, [ebp-$20]

* Reference to: System.@LStrLen(String):Integer;
|
0063A875   E8E2AEDCFF             call    0040575C
0063A87A   3BF8                   cmp     edi, eax
0063A87C   0F9CC0                 setl    al
0063A87F   EB02                   jmp     0063A883
0063A881   B001                   mov     al, $01
0063A883   84C0                   test    al, al
0063A885   0F84C3010000           jz      0063AA4E
0063A88B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmF2.CkGenerico : TCheckBox
|
0063A88E   8B8084030000           mov     eax, [eax+$0384]
0063A894   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0063A896   FF92C8000000           call    dword ptr [edx+$00C8]
0063A89C   84C0                   test    al, al
0063A89E   0F84D9000000           jz      0063A97D
0063A8A4   8D55DC                 lea     edx, [ebp-$24]
0063A8A7   8BC3                   mov     eax, ebx

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A8A9   E81E8EE5FF             call    004936CC
0063A8AE   837DDC00               cmp     dword ptr [ebp-$24], +$00
0063A8B2   0F8496010000           jz      0063AA4E
0063A8B8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmF2.ckMaiMin : TCheckBox
|
0063A8BB   8B80C4030000           mov     eax, [eax+$03C4]
0063A8C1   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0063A8C3   FF92C8000000           call    dword ptr [edx+$00C8]
0063A8C9   84C0                   test    al, al
0063A8CB   7460                   jz      0063A92D

* Possible String Reference to: 'UPPER('
|
0063A8CD   683CAB6300             push    $0063AB3C
0063A8D2   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ') LIKE '
|
0063A8D5   684CAB6300             push    $0063AB4C
0063A8DA   685CAB6300             push    $0063AB5C
0063A8DF   6868AB6300             push    $0063AB68
0063A8E4   8D55D0                 lea     edx, [ebp-$30]
0063A8E7   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A8E9   E8DE8DE5FF             call    004936CC
0063A8EE   8B45D0                 mov     eax, [ebp-$30]
0063A8F1   8D55D4                 lea     edx, [ebp-$2C]

* Reference to: SysUtils.AnsiUpperCase(AnsiString):AnsiString;
|
0063A8F4   E86FFDDCFF             call    0040A668
0063A8F9   FF75D4                 push    dword ptr [ebp-$2C]
0063A8FC   6868AB6300             push    $0063AB68
0063A901   685CAB6300             push    $0063AB5C
0063A906   8D45D8                 lea     eax, [ebp-$28]
0063A909   BA08000000             mov     edx, $00000008

* Reference to: System.@LStrCatN;
|
0063A90E   E809AFDCFF             call    0040581C
0063A913   8B45D8                 mov     eax, [ebp-$28]
0063A916   50                     push    eax
0063A917   8B4DF8                 mov     ecx, [ebp-$08]
0063A91A   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063A920   8B45FC                 mov     eax, [ebp-$04]

|
0063A923   E800F6FFFF             call    00639F28
0063A928   E921010000             jmp     0063AA4E
0063A92D   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ' LIKE '
|
0063A930   6874AB6300             push    $0063AB74
0063A935   685CAB6300             push    $0063AB5C
0063A93A   6868AB6300             push    $0063AB68
0063A93F   8D55C8                 lea     edx, [ebp-$38]
0063A942   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A944   E8838DE5FF             call    004936CC
0063A949   FF75C8                 push    dword ptr [ebp-$38]
0063A94C   6868AB6300             push    $0063AB68
0063A951   685CAB6300             push    $0063AB5C
0063A956   8D45CC                 lea     eax, [ebp-$34]
0063A959   BA07000000             mov     edx, $00000007

* Reference to: System.@LStrCatN;
|
0063A95E   E8B9AEDCFF             call    0040581C
0063A963   8B45CC                 mov     eax, [ebp-$34]
0063A966   50                     push    eax
0063A967   8B4DF8                 mov     ecx, [ebp-$08]
0063A96A   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063A970   8B45FC                 mov     eax, [ebp-$04]

|
0063A973   E8B0F5FFFF             call    00639F28
0063A978   E9D1000000             jmp     0063AA4E
0063A97D   837DF800               cmp     dword ptr [ebp-$08], +$00
0063A981   0F84C7000000           jz      0063AA4E
0063A987   8D55C4                 lea     edx, [ebp-$3C]
0063A98A   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A98C   E83B8DE5FF             call    004936CC
0063A991   837DC400               cmp     dword ptr [ebp-$3C], +$00
0063A995   0F84B3000000           jz      0063AA4E
0063A99B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TFrmF2.ckMaiMin : TCheckBox
|
0063A99E   8B80C4030000           mov     eax, [eax+$03C4]
0063A9A4   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
0063A9A6   FF92C8000000           call    dword ptr [edx+$00C8]
0063A9AC   84C0                   test    al, al
0063A9AE   7458                   jz      0063AA08

* Possible String Reference to: 'UPPER('
|
0063A9B0   683CAB6300             push    $0063AB3C
0063A9B5   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ') LIKE '
|
0063A9B8   684CAB6300             push    $0063AB4C
0063A9BD   685CAB6300             push    $0063AB5C
0063A9C2   8D55B8                 lea     edx, [ebp-$48]
0063A9C5   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063A9C7   E8008DE5FF             call    004936CC
0063A9CC   8B45B8                 mov     eax, [ebp-$48]
0063A9CF   8D55BC                 lea     edx, [ebp-$44]

* Reference to: SysUtils.AnsiUpperCase(AnsiString):AnsiString;
|
0063A9D2   E891FCDCFF             call    0040A668
0063A9D7   FF75BC                 push    dword ptr [ebp-$44]
0063A9DA   6868AB6300             push    $0063AB68
0063A9DF   685CAB6300             push    $0063AB5C
0063A9E4   8D45C0                 lea     eax, [ebp-$40]
0063A9E7   BA07000000             mov     edx, $00000007

* Reference to: System.@LStrCatN;
|
0063A9EC   E82BAEDCFF             call    0040581C
0063A9F1   8B45C0                 mov     eax, [ebp-$40]
0063A9F4   50                     push    eax
0063A9F5   8B4DF8                 mov     ecx, [ebp-$08]
0063A9F8   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063A9FE   8B45FC                 mov     eax, [ebp-$04]

|
0063AA01   E822F5FFFF             call    00639F28
0063AA06   EB46                   jmp     0063AA4E
0063AA08   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: ' LIKE '
|
0063AA0B   6874AB6300             push    $0063AB74
0063AA10   685CAB6300             push    $0063AB5C
0063AA15   8D55B0                 lea     edx, [ebp-$50]
0063AA18   8BC6                   mov     eax, esi

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063AA1A   E8AD8CE5FF             call    004936CC
0063AA1F   FF75B0                 push    dword ptr [ebp-$50]
0063AA22   6868AB6300             push    $0063AB68
0063AA27   685CAB6300             push    $0063AB5C
0063AA2C   8D45B4                 lea     eax, [ebp-$4C]
0063AA2F   BA06000000             mov     edx, $00000006

* Reference to: System.@LStrCatN;
|
0063AA34   E8E3ADDCFF             call    0040581C
0063AA39   8B45B4                 mov     eax, [ebp-$4C]
0063AA3C   50                     push    eax
0063AA3D   8B4DF8                 mov     ecx, [ebp-$08]
0063AA40   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063AA46   8B45FC                 mov     eax, [ebp-$04]

|
0063AA49   E8DAF4FFFF             call    00639F28
0063AA4E   33C0                   xor     eax, eax
0063AA50   5A                     pop     edx
0063AA51   59                     pop     ecx
0063AA52   59                     pop     ecx
0063AA53   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[ãÂ]√'
|
0063AA56   68E4AA6300             push    $0063AAE4
0063AA5B   8D45B0                 lea     eax, [ebp-$50]

* Reference to: System.@LStrClr(void;void);
|
0063AA5E   E839AADCFF             call    0040549C
0063AA63   8D45B4                 lea     eax, [ebp-$4C]

* Reference to: System.@LStrClr(void;void);
|
0063AA66   E831AADCFF             call    0040549C
0063AA6B   8D45B8                 lea     eax, [ebp-$48]

* Reference to: System.@LStrClr(void;void);
|
0063AA6E   E829AADCFF             call    0040549C
0063AA73   8D45BC                 lea     eax, [ebp-$44]
0063AA76   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AA7B   E840AADCFF             call    004054C0
0063AA80   8D45C4                 lea     eax, [ebp-$3C]
0063AA83   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AA88   E833AADCFF             call    004054C0
0063AA8D   8D45CC                 lea     eax, [ebp-$34]

* Reference to: System.@LStrClr(void;void);
|
0063AA90   E807AADCFF             call    0040549C
0063AA95   8D45D0                 lea     eax, [ebp-$30]

* Reference to: System.@LStrClr(void;void);
|
0063AA98   E8FFA9DCFF             call    0040549C
0063AA9D   8D45D4                 lea     eax, [ebp-$2C]
0063AAA0   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AAA5   E816AADCFF             call    004054C0
0063AAAA   8D45DC                 lea     eax, [ebp-$24]
0063AAAD   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AAB2   E809AADCFF             call    004054C0
0063AAB7   8D45E4                 lea     eax, [ebp-$1C]
0063AABA   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AABF   E8FCA9DCFF             call    004054C0
0063AAC4   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0063AAC7   E8D0A9DCFF             call    0040549C
0063AACC   8D45F0                 lea     eax, [ebp-$10]
0063AACF   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063AAD4   E8E7A9DCFF             call    004054C0
0063AAD9   C3                     ret


* Reference to: System.@HandleFinally;
|
0063AADA   E959A2DCFF             jmp     00404D38
0063AADF   E977FFFFFF             jmp     0063AA5B

****** END
|
0063AAE4   5F                     pop     edi
0063AAE5   5E                     pop     esi
0063AAE6   5B                     pop     ebx
0063AAE7   8BE5                   mov     esp, ebp
0063AAE9   5D                     pop     ebp
0063AAEA   C3                     ret

*)
end;

procedure TFrmF2.cbOrdemChange(Sender : TObject);
begin
(*
0063AB7C   55                     push    ebp
0063AB7D   8BEC                   mov     ebp, esp
0063AB7F   6A00                   push    $00
0063AB81   53                     push    ebx
0063AB82   8BD8                   mov     ebx, eax
0063AB84   33C0                   xor     eax, eax
0063AB86   55                     push    ebp

* Possible String Reference to: 'Èk°‹ˇÎ[Y]√êUãÏj'
|
0063AB87   68C8AB6300             push    $0063ABC8

***** TRY
|
0063AB8C   64FF30                 push    dword ptr fs:[eax]
0063AB8F   648920                 mov     fs:[eax], esp
0063AB92   6A00                   push    $00
0063AB94   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmF2.cbOrdem : TComboBox
|
0063AB97   8B8388030000           mov     eax, [ebx+$0388]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063AB9D   E82A8BE5FF             call    004936CC
0063ABA2   8B4DFC                 mov     ecx, [ebp-$04]
0063ABA5   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063ABAB   8BC3                   mov     eax, ebx

|
0063ABAD   E876F3FFFF             call    00639F28
0063ABB2   33C0                   xor     eax, eax
0063ABB4   5A                     pop     edx
0063ABB5   59                     pop     ecx
0063ABB6   59                     pop     ecx
0063ABB7   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏj'
|
0063ABBA   68CFAB6300             push    $0063ABCF
0063ABBF   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0063ABC2   E8D5A8DCFF             call    0040549C
0063ABC7   C3                     ret


* Reference to: System.@HandleFinally;
|
0063ABC8   E96BA1DCFF             jmp     00404D38
0063ABCD   EBF0                   jmp     0063ABBF

****** END
|
0063ABCF   5B                     pop     ebx
0063ABD0   59                     pop     ecx
0063ABD1   5D                     pop     ebp
0063ABD2   C3                     ret

*)
end;

procedure TFrmF2.btInfoAtuClick(Sender : TObject);
begin
(*
0063ABD4   55                     push    ebp
0063ABD5   8BEC                   mov     ebp, esp
0063ABD7   6A00                   push    $00
0063ABD9   33C0                   xor     eax, eax
0063ABDB   55                     push    ebp
0063ABDC   6814AC6300             push    $0063AC14

***** TRY
|
0063ABE1   64FF30                 push    dword ptr fs:[eax]
0063ABE4   648920                 mov     fs:[eax], esp
0063ABE7   8D45FC                 lea     eax, [ebp-$04]
0063ABEA   50                     push    eax
0063ABEB   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063ABF0   8B00                   mov     eax, [eax]
0063ABF2   8B4060                 mov     eax, [eax+$60]
0063ABF5   B101                   mov     cl, $01
0063ABF7   33D2                   xor     edx, edx

|
0063ABF9   E8BA841600             call    007A30B8
0063ABFE   33C0                   xor     eax, eax
0063AC00   5A                     pop     edx
0063AC01   59                     pop     ecx
0063AC02   59                     pop     ecx
0063AC03   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'Y]√ã¿UãÏSãÿj'
|
0063AC06   681BAC6300             push    $0063AC1B
0063AC0B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0063AC0E   E889A8DCFF             call    0040549C
0063AC13   C3                     ret


* Reference to: System.@HandleFinally;
|
0063AC14   E91FA1DCFF             jmp     00404D38
0063AC19   EBF0                   jmp     0063AC0B

****** END
|
0063AC1B   59                     pop     ecx
0063AC1C   5D                     pop     ebp
0063AC1D   C3                     ret

*)
end;

procedure TFrmF2.GrF2DblClick(Sender : TObject);
begin
(*
0063AC20   55                     push    ebp
0063AC21   8BEC                   mov     ebp, esp
0063AC23   53                     push    ebx
0063AC24   8BD8                   mov     ebx, eax
0063AC26   6A00                   push    $00
0063AC28   6A00                   push    $00
0063AC2A   6801020000             push    $00000201

* Reference to control TFrmF2.btOK : TBitBtn
|
0063AC2F   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: QStdCtrls.TButtonControl.GetHandle(TButtonControl):QButtonH;
|
0063AC35   E8F2F5E5FF             call    0049A22C
0063AC3A   50                     push    eax

* Reference to: user32.SendMessageA()
|
0063AC3B   E844E0DCFF             call    00408C84
0063AC40   5B                     pop     ebx
0063AC41   5D                     pop     ebp
0063AC42   C3                     ret

*)
end;

procedure TFrmF2.FormCreate(Sender : TObject);
begin
(*
0063AC44   55                     push    ebp
0063AC45   8BEC                   mov     ebp, esp

|
0063AC47   E8F4B21600             call    007A5F40
0063AC4C   5D                     pop     ebp
0063AC4D   C3                     ret

*)
end;

procedure TFrmF2.FormDestroy(Sender : TObject);
begin
(*
0063AC50   55                     push    ebp
0063AC51   8BEC                   mov     ebp, esp

|
0063AC53   E800B31600             call    007A5F58
0063AC58   5D                     pop     ebp
0063AC59   C3                     ret

*)
end;

procedure TFrmF2.MudaIndice(Sender : TObject);
begin
(*
0063AC5C   55                     push    ebp
0063AC5D   8BEC                   mov     ebp, esp
0063AC5F   53                     push    ebx
0063AC60   56                     push    esi
0063AC61   8BF2                   mov     esi, edx
0063AC63   8BD8                   mov     ebx, eax
0063AC65   8BC6                   mov     eax, esi

* Reference to class TEdit
|
0063AC67   8B15A0FC4700           mov     edx, [$0047FCA0]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
0063AC6D   E8E29ADCFF             call    00404754
0063AC72   8BF0                   mov     esi, eax
0063AC74   6A00                   push    $00
0063AC76   A1F0DC7D00             mov     eax, dword ptr [$007DDCF0]
0063AC7B   8B560C                 mov     edx, [esi+$0C]
0063AC7E   8B4C90FC               mov     ecx, [eax+edx*4-$04]
0063AC82   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063AC88   8BC3                   mov     eax, ebx

|
0063AC8A   E899F2FFFF             call    00639F28
0063AC8F   8B560C                 mov     edx, [esi+$0C]
0063AC92   4A                     dec     edx

* Reference to control TFrmF2.cbOrdem : TComboBox
|
0063AC93   8B8388030000           mov     eax, [ebx+$0388]
0063AC99   8B08                   mov     ecx, [eax]

* Reference to method TComboBox.ItemIndex()
|
0063AC9B   FF91D0000000           call    dword ptr [ecx+$00D0]
0063ACA1   5E                     pop     esi
0063ACA2   5B                     pop     ebx
0063ACA3   5D                     pop     ebp
0063ACA4   C3                     ret

*)
end;

procedure TFrmF2.btVoltarClick(Sender : TObject);
begin
(*
0063B094   55                     push    ebp
0063B095   8BEC                   mov     ebp, esp
0063B097   33C9                   xor     ecx, ecx
0063B099   51                     push    ecx
0063B09A   51                     push    ecx
0063B09B   51                     push    ecx
0063B09C   51                     push    ecx
0063B09D   51                     push    ecx
0063B09E   53                     push    ebx
0063B09F   8BD8                   mov     ebx, eax
0063B0A1   33C0                   xor     eax, eax
0063B0A3   55                     push    ebp

* Possible String Reference to: 'Èlõ‹ˇÎÎ[ãÂ]√'
|
0063B0A4   68C7B16300             push    $0063B1C7

***** TRY
|
0063B0A9   64FF30                 push    dword ptr fs:[eax]
0063B0AC   648920                 mov     fs:[eax], esp
0063B0AF   B84C887D00             mov     eax, $007D884C

* Reference to: System.@LStrClr(void;void);
|
0063B0B4   E8E3A3DCFF             call    0040549C
0063B0B9   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmF2.cbSetor : TComboBox
|
0063B0BC   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063B0C2   E80586E5FF             call    004936CC
0063B0C7   837DFC00               cmp     dword ptr [ebp-$04], +$00
0063B0CB   745E                   jz      0063B12B
0063B0CD   833D4C887D0000         cmp     dword ptr [$007D884C], +$00
0063B0D4   740F                   jz      0063B0E5
0063B0D6   B84C887D00             mov     eax, $007D884C

* Possible String Reference to: ' AND '
|
0063B0DB   BADCB16300             mov     edx, $0063B1DC

* Reference to: System.@LStrCat;
|
0063B0E0   E87FA6DCFF             call    00405764
0063B0E5   FF354C887D00           push    dword ptr [$007D884C]

* Possible String Reference to: '(CodSetor = "'
|
0063B0EB   68ECB16300             push    $0063B1EC
0063B0F0   8D45F8                 lea     eax, [ebp-$08]
0063B0F3   50                     push    eax
0063B0F4   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TFrmF2.cbSetor : TComboBox
|
0063B0F7   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063B0FD   E8CA85E5FF             call    004936CC
0063B102   8B45F4                 mov     eax, [ebp-$0C]
0063B105   B903000000             mov     ecx, $00000003
0063B10A   BA01000000             mov     edx, $00000001

* Reference to: System.@LStrCopy;
|
0063B10F   E8A8A8DCFF             call    004059BC
0063B114   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: '")'
|
0063B117   6804B26300             push    $0063B204
0063B11C   B84C887D00             mov     eax, $007D884C
0063B121   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0063B126   E8F1A6DCFF             call    0040581C
0063B12B   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmF2.edGuia : TEdit
|
0063B12E   8B8398030000           mov     eax, [ebx+$0398]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063B134   E89385E5FF             call    004936CC
0063B139   837DF000               cmp     dword ptr [ebp-$10], +$00
0063B13D   7448                   jz      0063B187
0063B13F   833D4C887D0000         cmp     dword ptr [$007D884C], +$00
0063B146   740F                   jz      0063B157
0063B148   B84C887D00             mov     eax, $007D884C

* Possible String Reference to: ' AND '
|
0063B14D   BADCB16300             mov     edx, $0063B1DC

* Reference to: System.@LStrCat;
|
0063B152   E80DA6DCFF             call    00405764
0063B157   FF354C887D00           push    dword ptr [$007D884C]

* Possible String Reference to: '(CoordGuia = "'
|
0063B15D   6810B26300             push    $0063B210
0063B162   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmF2.edGuia : TEdit
|
0063B165   8B8398030000           mov     eax, [ebx+$0398]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
0063B16B   E85C85E5FF             call    004936CC
0063B170   FF75EC                 push    dword ptr [ebp-$14]

* Possible String Reference to: '")'
|
0063B173   6804B26300             push    $0063B204
0063B178   B84C887D00             mov     eax, $007D884C
0063B17D   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrCatN;
|
0063B182   E895A6DCFF             call    0040581C
0063B187   6A00                   push    $00
0063B189   33C9                   xor     ecx, ecx
0063B18B   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063B191   A1ECDC7D00             mov     eax, dword ptr [$007DDCEC]

|
0063B196   E88DEDFFFF             call    00639F28
0063B19B   8B1510DD7D00           mov     edx, [$007DDD10]

* Reference to control TFrmF2.nbF2 : TNotebook
|
0063B1A1   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: ExtCtrls.TNotebook.SetPageIndex(TNotebook;Integer);
|
0063B1A7   E898E4E0FF             call    00449644
0063B1AC   33C0                   xor     eax, eax
0063B1AE   5A                     pop     edx
0063B1AF   59                     pop     ecx
0063B1B0   59                     pop     ecx
0063B1B1   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√'
|
0063B1B4   68CEB16300             push    $0063B1CE
0063B1B9   8D45EC                 lea     eax, [ebp-$14]
0063B1BC   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063B1C1   E8FAA2DCFF             call    004054C0
0063B1C6   C3                     ret


* Reference to: System.@HandleFinally;
|
0063B1C7   E96C9BDCFF             jmp     00404D38
0063B1CC   EBEB                   jmp     0063B1B9

****** END
|
0063B1CE   5B                     pop     ebx
0063B1CF   8BE5                   mov     esp, ebp
0063B1D1   5D                     pop     ebp
0063B1D2   C3                     ret

*)
end;

procedure TFrmF2.btLimparClick(Sender : TObject);
begin
(*
0063B238   55                     push    ebp
0063B239   8BEC                   mov     ebp, esp
0063B23B   53                     push    ebx
0063B23C   8BD8                   mov     ebx, eax
0063B23E   33D2                   xor     edx, edx

* Reference to control TFrmF2.cbSetor : TComboBox
|
0063B240   8B83A8030000           mov     eax, [ebx+$03A8]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0063B246   E8B184E5FF             call    004936FC
0063B24B   33D2                   xor     edx, edx

* Reference to control TFrmF2.edGuia : TEdit
|
0063B24D   8B8398030000           mov     eax, [ebx+$0398]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0063B253   E8A484E5FF             call    004936FC
0063B258   B84C887D00             mov     eax, $007D884C

* Reference to: System.@LStrClr(void;void);
|
0063B25D   E83AA2DCFF             call    0040549C
0063B262   6A00                   push    $00
0063B264   33C9                   xor     ecx, ecx
0063B266   8B15FCDC7D00           mov     edx, [$007DDCFC]
0063B26C   A1ECDC7D00             mov     eax, dword ptr [$007DDCEC]

|
0063B271   E8B2ECFFFF             call    00639F28
0063B276   5B                     pop     ebx
0063B277   5D                     pop     ebp
0063B278   C3                     ret

*)
end;

procedure TFrmF2.FormKeyDown(Sender : TObject);
begin
(*
0063B27C   55                     push    ebp
0063B27D   8BEC                   mov     ebp, esp
0063B27F   53                     push    ebx
0063B280   56                     push    esi
0063B281   8BF1                   mov     esi, ecx
0063B283   8B5D08                 mov     ebx, [ebp+$08]
0063B286   66833E7B               cmp     word ptr [esi], +$7B
0063B28A   7529                   jnz     0063B2B5
0063B28C   A010B36300             mov     al, byte ptr [$0063B310]
0063B291   3AC3                   cmp     al, bl
0063B293   7520                   jnz     0063B2B5
0063B295   B854887D00             mov     eax, $007D8854
0063B29A   BA1CB36300             mov     edx, $0063B31C

* Reference to: System.@LStrAsg(void;void;void;void);
|
0063B29F   E84CA2DCFF             call    004054F0

* Possible String Reference to: 'Pesquisa no cadastro-'
|
0063B2A4   BA28B36300             mov     edx, $0063B328
0063B2A9   A1ECDC7D00             mov     eax, dword ptr [$007DDCEC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0063B2AE   E84984E5FF             call    004936FC
0063B2B3   EB53                   jmp     0063B308
0063B2B5   66833E7B               cmp     word ptr [esi], +$7B
0063B2B9   7529                   jnz     0063B2E4
0063B2BB   A040B36300             mov     al, byte ptr [$0063B340]
0063B2C0   3AC3                   cmp     al, bl
0063B2C2   7520                   jnz     0063B2E4
0063B2C4   B854887D00             mov     eax, $007D8854
0063B2C9   BA4CB36300             mov     edx, $0063B34C

* Reference to: System.@LStrAsg(void;void;void;void);
|
0063B2CE   E81DA2DCFF             call    004054F0

* Possible String Reference to: 'Pesquisa no cadastro'
|
0063B2D3   BA58B36300             mov     edx, $0063B358
0063B2D8   A1ECDC7D00             mov     eax, dword ptr [$007DDCEC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0063B2DD   E81A84E5FF             call    004936FC
0063B2E2   EB24                   jmp     0063B308
0063B2E4   66833E7B               cmp     word ptr [esi], +$7B
0063B2E8   751E                   jnz     0063B308
0063B2EA   B854887D00             mov     eax, $007D8854
0063B2EF   BA78B36300             mov     edx, $0063B378

* Reference to: System.@LStrAsg(void;void;void;void);
|
0063B2F4   E8F7A1DCFF             call    004054F0

* Possible String Reference to: 'Pesquisa no cadastro:'
|
0063B2F9   BA84B36300             mov     edx, $0063B384
0063B2FE   A1ECDC7D00             mov     eax, dword ptr [$007DDCEC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
0063B303   E8F483E5FF             call    004936FC
0063B308   5E                     pop     esi
0063B309   5B                     pop     ebx
0063B30A   5D                     pop     ebp
0063B30B   C20400                 ret     $0004

*)
end;

procedure TFrmF2.GrF2GetCellProps(Sender : TObject);
begin
(*
0063B39C   55                     push    ebp
0063B39D   8BEC                   mov     ebp, esp
0063B39F   51                     push    ecx
0063B3A0   B905000000             mov     ecx, $00000005
0063B3A5   6A00                   push    $00
0063B3A7   6A00                   push    $00
0063B3A9   49                     dec     ecx
0063B3AA   75F9                   jnz     0063B3A5
0063B3AC   51                     push    ecx
0063B3AD   874DFC                 xchg    [ebp-$04], ecx
0063B3B0   53                     push    ebx
0063B3B1   8B5D08                 mov     ebx, [ebp+$08]
0063B3B4   33C0                   xor     eax, eax
0063B3B6   55                     push    ebp
0063B3B7   688EB66300             push    $0063B68E

***** TRY
|
0063B3BC   64FF30                 push    dword ptr fs:[eax]
0063B3BF   648920                 mov     fs:[eax], esp
0063B3C2   8D55FC                 lea     edx, [ebp-$04]
0063B3C5   A1FCDC7D00             mov     eax, dword ptr [$007DDCFC]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
0063B3CA   E859F1DCFF             call    0040A528
0063B3CF   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'SAIDAS'
|
0063B3D2   BAA4B66300             mov     edx, $0063B6A4

* Reference to: System.@LStrCmp;
|
0063B3D7   E8CCA4DCFF             call    004058A8
0063B3DC   0F8550010000           jnz     0063B532
0063B3E2   803D48887D0000         cmp     byte ptr [$007D8848], $00
0063B3E9   0F8443010000           jz      0063B532
0063B3EF   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B3F4   8B00                   mov     eax, [eax]
0063B3F6   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
0063B3F9   E8A2D6EAFF             call    004E8AA0
0063B3FE   84C0                   test    al, al
0063B400   0F842C010000           jz      0063B532
0063B406   C703FFFFFF00           mov     dword ptr [ebx], $00FFFFFF
0063B40C   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B411   8B00                   mov     eax, [eax]
0063B413   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Status'
|
0063B416   BAB4B66300             mov     edx, $0063B6B4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B41B   E8E4E7EAFF             call    004E9C04
0063B420   8D55F8                 lea     edx, [ebp-$08]
0063B423   8B08                   mov     ecx, [eax]
0063B425   FF5160                 call    dword ptr [ecx+$60]
0063B428   8B45F8                 mov     eax, [ebp-$08]
0063B42B   BAC4B66300             mov     edx, $0063B6C4

* Reference to: System.@LStrCmp;
|
0063B430   E873A4DCFF             call    004058A8
0063B435   750B                   jnz     0063B442
0063B437   C703C0C0C000           mov     dword ptr [ebx], $00C0C0C0
0063B43D   E931020000             jmp     0063B673
0063B442   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B447   8B00                   mov     eax, [eax]
0063B449   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Status'
|
0063B44C   BAB4B66300             mov     edx, $0063B6B4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B451   E8AEE7EAFF             call    004E9C04
0063B456   8D55F4                 lea     edx, [ebp-$0C]
0063B459   8B08                   mov     ecx, [eax]
0063B45B   FF5160                 call    dword ptr [ecx+$60]
0063B45E   8B45F4                 mov     eax, [ebp-$0C]
0063B461   BAD0B66300             mov     edx, $0063B6D0

* Reference to: System.@LStrCmp;
|
0063B466   E83DA4DCFF             call    004058A8
0063B46B   7536                   jnz     0063B4A3
0063B46D   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B472   8B00                   mov     eax, [eax]
0063B474   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'TipoLcto'
|
0063B477   BADCB66300             mov     edx, $0063B6DC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B47C   E883E7EAFF             call    004E9C04
0063B481   8D55F0                 lea     edx, [ebp-$10]
0063B484   8B08                   mov     ecx, [eax]
0063B486   FF5160                 call    dword ptr [ecx+$60]
0063B489   8B45F0                 mov     eax, [ebp-$10]

* Possible String Reference to: 'VA'
|
0063B48C   BAF0B66300             mov     edx, $0063B6F0

* Reference to: System.@LStrCmp;
|
0063B491   E812A4DCFF             call    004058A8
0063B496   750B                   jnz     0063B4A3
0063B498   C7030080C000           mov     dword ptr [ebx], $00C08000
0063B49E   E9D0010000             jmp     0063B673
0063B4A3   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B4A8   8B00                   mov     eax, [eax]
0063B4AA   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'NumNotas'
|
0063B4AD   BAFCB66300             mov     edx, $0063B6FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B4B2   E84DE7EAFF             call    004E9C04
0063B4B7   8B10                   mov     edx, [eax]
0063B4B9   FF5258                 call    dword ptr [edx+$58]
0063B4BC   85C0                   test    eax, eax
0063B4BE   7E0B                   jle     0063B4CB
0063B4C0   C703180000FF           mov     dword ptr [ebx], $FF000018
0063B4C6   E9A8010000             jmp     0063B673
0063B4CB   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B4D0   8B00                   mov     eax, [eax]
0063B4D2   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'RespAuto'
|
0063B4D5   BA10B76300             mov     edx, $0063B710

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B4DA   E825E7EAFF             call    004E9C04
0063B4DF   8D55EC                 lea     edx, [ebp-$14]
0063B4E2   8B08                   mov     ecx, [eax]
0063B4E4   FF5160                 call    dword ptr [ecx+$60]
0063B4E7   8B45EC                 mov     eax, [ebp-$14]

* Possible String Reference to: 'zzzzz'
|
0063B4EA   BA24B76300             mov     edx, $0063B724

* Reference to: System.@LStrCmp;
|
0063B4EF   E8B4A3DCFF             call    004058A8
0063B4F4   750B                   jnz     0063B501
0063B4F6   C703FF808000           mov     dword ptr [ebx], $008080FF
0063B4FC   E972010000             jmp     0063B673
0063B501   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B506   8B00                   mov     eax, [eax]
0063B508   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'RespAuto'
|
0063B50B   BA10B76300             mov     edx, $0063B710

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B510   E8EFE6EAFF             call    004E9C04
0063B515   8D55E8                 lea     edx, [ebp-$18]
0063B518   8B08                   mov     ecx, [eax]
0063B51A   FF5160                 call    dword ptr [ecx+$60]
0063B51D   837DE800               cmp     dword ptr [ebp-$18], +$00
0063B521   0F844C010000           jz      0063B673
0063B527   C703B0FFB000           mov     dword ptr [ebx], $00B0FFB0
0063B52D   E941010000             jmp     0063B673
0063B532   8D55E4                 lea     edx, [ebp-$1C]
0063B535   A1FCDC7D00             mov     eax, dword ptr [$007DDCFC]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
0063B53A   E8E9EFDCFF             call    0040A528
0063B53F   8B45E4                 mov     eax, [ebp-$1C]

* Possible String Reference to: 'CLIENTES'
|
0063B542   BA34B76300             mov     edx, $0063B734

* Reference to: System.@LStrCmp;
|
0063B547   E85CA3DCFF             call    004058A8
0063B54C   0F8581000000           jnz     0063B5D3
0063B552   803D48887D0000         cmp     byte ptr [$007D8848], $00
0063B559   7478                   jz      0063B5D3
0063B55B   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B560   8B00                   mov     eax, [eax]
0063B562   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
0063B565   E836D5EAFF             call    004E8AA0
0063B56A   84C0                   test    al, al
0063B56C   7465                   jz      0063B5D3
0063B56E   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B573   8B00                   mov     eax, [eax]
0063B575   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Ativo'
|
0063B578   BA48B76300             mov     edx, $0063B748

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B57D   E882E6EAFF             call    004E9C04
0063B582   8D55E0                 lea     edx, [ebp-$20]
0063B585   8B08                   mov     ecx, [eax]
0063B587   FF5160                 call    dword ptr [ecx+$60]
0063B58A   8B45E0                 mov     eax, [ebp-$20]
0063B58D   BA58B76300             mov     edx, $0063B758

* Reference to: System.@LStrCmp;
|
0063B592   E811A3DCFF             call    004058A8
0063B597   742F                   jz      0063B5C8
0063B599   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B59E   8B00                   mov     eax, [eax]
0063B5A0   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Ativo'
|
0063B5A3   BA48B76300             mov     edx, $0063B748

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B5A8   E857E6EAFF             call    004E9C04
0063B5AD   8D55DC                 lea     edx, [ebp-$24]
0063B5B0   8B08                   mov     ecx, [eax]
0063B5B2   FF5160                 call    dword ptr [ecx+$60]
0063B5B5   8B45DC                 mov     eax, [ebp-$24]
0063B5B8   BA64B76300             mov     edx, $0063B764

* Reference to: System.@LStrCmp;
|
0063B5BD   E8E6A2DCFF             call    004058A8
0063B5C2   0F85AB000000           jnz     0063B673
0063B5C8   C703C0C0C000           mov     dword ptr [ebx], $00C0C0C0
0063B5CE   E9A0000000             jmp     0063B673
0063B5D3   8D55D8                 lea     edx, [ebp-$28]
0063B5D6   A1FCDC7D00             mov     eax, dword ptr [$007DDCFC]

* Reference to: SysUtils.UpperCase(AnsiString):AnsiString;
|
0063B5DB   E848EFDCFF             call    0040A528
0063B5E0   8B45D8                 mov     eax, [ebp-$28]

* Possible String Reference to: 'NATOPER'
|
0063B5E3   BA70B76300             mov     edx, $0063B770

* Reference to: System.@LStrCmp;
|
0063B5E8   E8BBA2DCFF             call    004058A8
0063B5ED   0F8580000000           jnz     0063B673
0063B5F3   803D48887D0000         cmp     byte ptr [$007D8848], $00
0063B5FA   7477                   jz      0063B673
0063B5FC   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B601   8B00                   mov     eax, [eax]
0063B603   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
0063B606   E895D4EAFF             call    004E8AA0
0063B60B   84C0                   test    al, al
0063B60D   7464                   jz      0063B673
0063B60F   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B614   8B00                   mov     eax, [eax]
0063B616   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Desativado'
|
0063B619   BA80B76300             mov     edx, $0063B780

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B61E   E8E1E5EAFF             call    004E9C04
0063B623   8D55D4                 lea     edx, [ebp-$2C]
0063B626   8B08                   mov     ecx, [eax]
0063B628   FF5160                 call    dword ptr [ecx+$60]
0063B62B   8B45D4                 mov     eax, [ebp-$2C]
0063B62E   BAD0B66300             mov     edx, $0063B6D0

* Reference to: System.@LStrCmp;
|
0063B633   E870A2DCFF             call    004058A8
0063B638   7508                   jnz     0063B642
0063B63A   C703C0C0C000           mov     dword ptr [ebx], $00C0C0C0
0063B640   EB31                   jmp     0063B673
0063B642   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063B647   8B00                   mov     eax, [eax]
0063B649   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'Mercantil'
|
0063B64C   BA94B76300             mov     edx, $0063B794

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0063B651   E8AEE5EAFF             call    004E9C04
0063B656   8D55D0                 lea     edx, [ebp-$30]
0063B659   8B08                   mov     ecx, [eax]
0063B65B   FF5160                 call    dword ptr [ecx+$60]
0063B65E   8B45D0                 mov     eax, [ebp-$30]
0063B661   BAD0B66300             mov     edx, $0063B6D0

* Reference to: System.@LStrCmp;
|
0063B666   E83DA2DCFF             call    004058A8
0063B66B   7406                   jz      0063B673
0063B66D   C70300FFFF00           mov     dword ptr [ebx], $00FFFF00
0063B673   33C0                   xor     eax, eax
0063B675   5A                     pop     edx
0063B676   59                     pop     ecx
0063B677   59                     pop     ecx
0063B678   648910                 mov     fs:[eax], edx

****** FINALLY
|
0063B67B   6895B66300             push    $0063B695
0063B680   8D45D0                 lea     eax, [ebp-$30]
0063B683   BA0C000000             mov     edx, $0000000C

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0063B688   E8339EDCFF             call    004054C0
0063B68D   C3                     ret


* Reference to: System.@HandleFinally;
|
0063B68E   E9A596DCFF             jmp     00404D38
0063B693   EBEB                   jmp     0063B680

****** END
|
0063B695   5B                     pop     ebx
0063B696   8BE5                   mov     esp, ebp
0063B698   5D                     pop     ebp
0063B699   C20800                 ret     $0008

*)
end;

procedure TFrmF2.FormClose(Sender : TObject);
begin
(*
0063BF30   55                     push    ebp
0063BF31   8BEC                   mov     ebp, esp

|
0063BF33   E8ACFEFFFF             call    0063BDE4
0063BF38   5D                     pop     ebp
0063BF39   C3                     ret

*)
end;

procedure TFrmF2.btCadastrarClick(Sender : TObject);
begin
(*
0063BF3C   55                     push    ebp
0063BF3D   8BEC                   mov     ebp, esp
0063BF3F   A1FCDC7D00             mov     eax, dword ptr [$007DDCFC]

* Reference to: DBAdapt.TBaseDataSetAdapterField.ImplCheckOrigValue(TBaseDataSetAdapterField;WebAdapt.IActionRequest;System.Integer);
|
0063BF44   E813000000             call    0063BF5C
0063BF49   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0063BF4E   8B00                   mov     eax, [eax]
0063BF50   8B4060                 mov     eax, [eax+$60]

* Reference to : TFrmInfoAtu._PROC_007A66A4()
|
0063BF53   E84CA71600             call    007A66A4
0063BF58   5D                     pop     ebp
0063BF59   C3                     ret

*)
end;

procedure TFrmF2.sbCadastroClick(Sender : TObject);
begin
(*
0063BFAC   55                     push    ebp
0063BFAD   8BEC                   mov     ebp, esp
0063BFAF   A11CDD7D00             mov     eax, dword ptr [$007DDD1C]

* Possible String Reference to: 'clientes'
|
0063BFB4   BA0CC06300             mov     edx, $0063C00C

* Reference to: System.@LStrCmp;
|
0063BFB9   E8EA98DCFF             call    004058A8
0063BFBE   7540                   jnz     0063C000
0063BFC0   A160AC7D00             mov     eax, dword ptr [$007DAC60]

* Possible String Reference to: 'cliente'
|
0063BFC5   BA20C06300             mov     edx, $0063C020

* Reference to: System.@LStrAsg(void;void;void;void);
|
0063BFCA   E82195DCFF             call    004054F0
0063BFCF   33C9                   xor     ecx, ecx
0063BFD1   B201                   mov     dl, $01

* Reference to class TFrmCadRapido
|
0063BFD3   A174556300             mov     eax, dword ptr [$00635574]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0063BFD8   E8331FE7FF             call    004ADF10
0063BFDD   8B1528A77D00           mov     edx, [$007DA728]
0063BFE3   8902                   mov     [edx], eax
0063BFE5   A128A77D00             mov     eax, dword ptr [$007DA728]
0063BFEA   8B00                   mov     eax, [eax]
0063BFEC   8B10                   mov     edx, [eax]
0063BFEE   FF92EC000000           call    dword ptr [edx+$00EC]
0063BFF4   A128A77D00             mov     eax, dword ptr [$007DA728]
0063BFF9   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0063BFFB   E89C85DCFF             call    0040459C
0063C000   5D                     pop     ebp
0063C001   C3                     ret

*)
end;

procedure TFrmF2._PROC_00639234(Sender : TObject);
begin
(*
00639234   389263001102           cmp     [edx+$2110063], dl
0063923A   2E380400               cmp     cs:[eax+eax], al
0063923E   0000                   add     [eax], al

*)
end;

end.