unit F2Preco;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ToolEdit, CurrEdit, Buttons,
  ExtCtrls;
  
type
  TFrmF2Preco=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Label1: TLabel;
    EdVlrUnit: TCurrencyEdit;
    Bevel1: TBevel;
    procedure FormCloseQuery(Sender : TObject);
    procedure _PROC_00658BF5(Sender : TObject);
    procedure _PROC_00658C24(Sender : TObject);
    procedure _PROC_00658C2C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmF2Preco: TFrmF2Preco;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmF2Preco.FormCloseQuery(Sender : TObject);
begin
(*
00658B24   55                     push    ebp
00658B25   8BEC                   mov     ebp, esp
00658B27   53                     push    ebx
00658B28   56                     push    esi
00658B29   8BF1                   mov     esi, ecx
00658B2B   8BD8                   mov     ebx, eax

* Reference to field TFrmF2Preco.ModalResult : TModalResult
|
00658B2D   83BB4C02000001         cmp     dword ptr [ebx+$024C], +$01
00658B34   7548                   jnz     00658B7E

* Reference to control TFrmF2Preco.EdVlrUnit : TCurrencyEdit
|
00658B36   8B8304030000           mov     eax, [ebx+$0304]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00658B3C   E8E705FDFF             call    00629128
00658B41   D81D848B6500           fcomp   dword ptr [$00658B84]
00658B47   DFE0                   fstsw   ax
00658B49   9E                     sahf
00658B4A   770F                   jnbe    00658B5B

* Possible String Reference to: 'Informe o valor unitário!'
|
00658B4C   B8908B6500             mov     eax, $00658B90

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00658B51   E8CEB0DEFF             call    00443C24
00658B56   C60600                 mov     byte ptr [esi], $00
00658B59   EB23                   jmp     00658B7E

* Reference to control TFrmF2Preco.EdVlrUnit : TCurrencyEdit
|
00658B5B   8B8304030000           mov     eax, [ebx+$0304]

* Reference to : TCurrencyEdit._PROC_00629128()
|
00658B61   E8C205FDFF             call    00629128
00658B66   D81DAC8B6500           fcomp   dword ptr [$00658BAC]
00658B6C   DFE0                   fstsw   ax
00658B6E   9E                     sahf
00658B6F   760D                   jbe     00658B7E

* Possible String Reference to: 'Atenção: o valor unitário é muito g
|                                rande !... Confira !!'
|
00658B71   B8B88B6500             mov     eax, $00658BB8

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00658B76   E8A9B0DEFF             call    00443C24
00658B7B   C60600                 mov     byte ptr [esi], $00
00658B7E   5E                     pop     esi
00658B7F   5B                     pop     ebx
00658B80   5D                     pop     ebp
00658B81   C3                     ret

*)
end;

procedure TFrmF2Preco._PROC_00658BF5(Sender : TObject);
begin
(*
00658BF5   8BEC                   mov     ebp, esp
00658BF7   33C0                   xor     eax, eax
00658BF9   55                     push    ebp
00658BFA   68198C6500             push    $00658C19

***** TRY
|
00658BFF   64FF30                 push    dword ptr fs:[eax]
00658C02   648920                 mov     fs:[eax], esp
00658C05   FF0558DE7D00           inc     dword ptr [$007DDE58]
00658C0B   33C0                   xor     eax, eax
00658C0D   5A                     pop     edx
00658C0E   59                     pop     ecx
00658C0F   59                     pop     ecx
00658C10   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-XÞ}'
|
00658C13   68208C6500             push    $00658C20
00658C18   C3                     ret


* Reference to: System.@HandleFinally;
|
00658C19   E91AC1DAFF             jmp     00404D38
00658C1E   EBF8                   jmp     00658C18

****** END
|
00658C20   5D                     pop     ebp
00658C21   C3                     ret

*)
end;

procedure TFrmF2Preco._PROC_00658C24(Sender : TObject);
begin
(*
00658C24   832D58DE7D0001         sub     dword ptr [$007DDE58], +$01
00658C2B   C3                     ret

*)
end;

procedure TFrmF2Preco._PROC_00658C2C(Sender : TObject);
begin
(*
00658C2C   788C                   js      00658BBA
00658C2E   650000                 add     gs:[eax], al
00658C31   0000                   add     [eax], al

*)
end;

end.