unit finaliza;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, LMDCustomButton, LMDButton, ExtCtrls;
  
type
  TFrmFinaliza=class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    btFinaliza: TLMDButton;
    btVoltar: TLMDButton;
    btDesconto: TLMDButton;
    btAcrescimo: TLMDButton;
    LMDButton1: TLMDButton;
    procedure FormShow(Sender : TObject);
    procedure btFinalizaMouseExit(Sender : TObject);
    procedure btFinalizaEnter(Sender : TObject);
    procedure btFinalizaExit(Sender : TObject);
    procedure btVoltarKeyDown(Sender : TObject);
    procedure FormKeyDown(Sender : TObject);
    procedure _PROC_00665A54(Sender : TObject);
    procedure _PROC_00665A84(Sender : TObject);
    procedure _PROC_00665A8C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmFinaliza: TFrmFinaliza;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmFinaliza.FormShow(Sender : TObject);
begin
(*
00665874   55                     push    ebp
00665875   8BEC                   mov     ebp, esp
00665877   53                     push    ebx
00665878   56                     push    esi
00665879   8BD8                   mov     ebx, eax
0066587B   8B35E4A07D00           mov     esi, [$007DA0E4]
00665881   8B06                   mov     eax, [esi]

* Possible String Reference to: 'bematech'
|
00665883   BA34596600             mov     edx, $00665934

* Reference to: System.@LStrCmp;
|
00665888   E81B00DAFF             call    004058A8
0066588D   7462                   jz      006658F1
0066588F   8B06                   mov     eax, [esi]

* Possible String Reference to: 'daruma'
|
00665891   BA48596600             mov     edx, $00665948

* Reference to: System.@LStrCmp;
|
00665896   E80D00DAFF             call    004058A8
0066589B   7454                   jz      006658F1
0066589D   8B06                   mov     eax, [esi]

* Possible String Reference to: 'windows'
|
0066589F   BA58596600             mov     edx, $00665958

* Reference to: System.@LStrCmp;
|
006658A4   E8FFFFD9FF             call    004058A8
006658A9   7446                   jz      006658F1
006658AB   8B06                   mov     eax, [esi]

* Possible String Reference to: 'tm-uc300c'
|
006658AD   BA68596600             mov     edx, $00665968

* Reference to: System.@LStrCmp;
|
006658B2   E8F1FFD9FF             call    004058A8
006658B7   7438                   jz      006658F1
006658B9   8B06                   mov     eax, [esi]

* Possible String Reference to: 'nenhuma'
|
006658BB   BA7C596600             mov     edx, $0066597C

* Reference to: System.@LStrCmp;
|
006658C0   E8E3FFD9FF             call    004058A8
006658C5   742A                   jz      006658F1
006658C7   8B06                   mov     eax, [esi]

* Possible String Reference to: 'mecaf'
|
006658C9   BA8C596600             mov     edx, $0066598C

* Reference to: System.@LStrCmp;
|
006658CE   E8D5FFD9FF             call    004058A8
006658D3   741C                   jz      006658F1
006658D5   8B06                   mov     eax, [esi]

* Possible String Reference to: 'trends'
|
006658D7   BA9C596600             mov     edx, $0066599C

* Reference to: System.@LStrCmp;
|
006658DC   E8C7FFD9FF             call    004058A8
006658E1   740E                   jz      006658F1
006658E3   8B06                   mov     eax, [esi]

* Possible String Reference to: 'mp-20ci'
|
006658E5   BAAC596600             mov     edx, $006659AC

* Reference to: System.@LStrCmp;
|
006658EA   E8B9FFD9FF             call    004058A8
006658EF   751C                   jnz     0066590D
006658F1   B201                   mov     dl, $01

* Reference to control TFrmFinaliza.btDesconto : TLMDButton
|
006658F3   8B8308030000           mov     eax, [ebx+$0308]
006658F9   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLMDButton.OFFS_64
|
006658FB   FF5164                 call    dword ptr [ecx+$64]
006658FE   B201                   mov     dl, $01

* Reference to control TFrmFinaliza.btAcrescimo : TLMDButton
|
00665900   8B830C030000           mov     eax, [ebx+$030C]
00665906   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLMDButton.OFFS_64
|
00665908   FF5164                 call    dword ptr [ecx+$64]
0066590B   EB1A                   jmp     00665927
0066590D   33D2                   xor     edx, edx

* Reference to control TFrmFinaliza.btDesconto : TLMDButton
|
0066590F   8B8308030000           mov     eax, [ebx+$0308]
00665915   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLMDButton.OFFS_64
|
00665917   FF5164                 call    dword ptr [ecx+$64]
0066591A   33D2                   xor     edx, edx

* Reference to control TFrmFinaliza.btAcrescimo : TLMDButton
|
0066591C   8B830C030000           mov     eax, [ebx+$030C]
00665922   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TLMDButton.OFFS_64
|
00665924   FF5164                 call    dword ptr [ecx+$64]
00665927   5E                     pop     esi
00665928   5B                     pop     ebx
00665929   5D                     pop     ebp
0066592A   C3                     ret

*)
end;

procedure TFrmFinaliza.btFinalizaMouseExit(Sender : TObject);
begin
(*
006659B4   55                     push    ebp
006659B5   8BEC                   mov     ebp, esp
006659B7   53                     push    ebx
006659B8   8BDA                   mov     ebx, edx
006659BA   8BC3                   mov     eax, ebx

* Reference to class TLMDSpeedButton
|
006659BC   8B1544506000           mov     edx, [$00605044]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
006659C2   E88DEDD9FF             call    00404754
006659C7   BAC0C0C000             mov     edx, $00C0C0C0

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
006659CC   E8B3DEE2FF             call    00493884
006659D1   5B                     pop     ebx
006659D2   5D                     pop     ebp
006659D3   C3                     ret

*)
end;

procedure TFrmFinaliza.btFinalizaEnter(Sender : TObject);
begin
(*
006659D4   55                     push    ebp
006659D5   8BEC                   mov     ebp, esp
006659D7   53                     push    ebx
006659D8   8BDA                   mov     ebx, edx
006659DA   8BC3                   mov     eax, ebx

* Reference to class TLMDButton
|
006659DC   8B15C8536600           mov     edx, [$006653C8]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
006659E2   E86DEDD9FF             call    00404754
006659E7   BA80808000             mov     edx, $00808080

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
006659EC   E893DEE2FF             call    00493884
006659F1   5B                     pop     ebx
006659F2   5D                     pop     ebp
006659F3   C3                     ret

*)
end;

procedure TFrmFinaliza.btFinalizaExit(Sender : TObject);
begin
(*
006659F4   55                     push    ebp
006659F5   8BEC                   mov     ebp, esp
006659F7   53                     push    ebx
006659F8   8BDA                   mov     ebx, edx
006659FA   8BC3                   mov     eax, ebx

* Reference to class TLMDButton
|
006659FC   8B15C8536600           mov     edx, [$006653C8]

* Reference to: System.@AsClass(TObject;TClass):TObject;
|
00665A02   E84DEDD9FF             call    00404754
00665A07   BA0F0000FF             mov     edx, $FF00000F

* Reference to: Controls.TControl.SetColor(TControl;TColor);
|
00665A0C   E873DEE2FF             call    00493884
00665A11   5B                     pop     ebx
00665A12   5D                     pop     ebp
00665A13   C3                     ret

*)
end;

procedure TFrmFinaliza.btVoltarKeyDown(Sender : TObject);
begin
(*
00665A14   55                     push    ebp
00665A15   8BEC                   mov     ebp, esp
00665A17   56                     push    esi
00665A18   8BF0                   mov     esi, eax
00665A1A   6683391B               cmp     word ptr [ecx], +$1B
00665A1E   750F                   jnz     00665A2F

* Reference to control TFrmFinaliza.btVoltar : TLMDButton
|
00665A20   8B8604030000           mov     eax, [esi+$0304]
00665A26   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
00665A2A   E871EDD9FF             call    004047A0
00665A2F   5E                     pop     esi
00665A30   5D                     pop     ebp
00665A31   C20400                 ret     $0004

*)
end;

procedure TFrmFinaliza.FormKeyDown(Sender : TObject);
begin
(*
00665A34   55                     push    ebp
00665A35   8BEC                   mov     ebp, esp
00665A37   56                     push    esi
00665A38   8BF0                   mov     esi, eax
00665A3A   6683391B               cmp     word ptr [ecx], +$1B
00665A3E   750F                   jnz     00665A4F

* Reference to control TFrmFinaliza.btVoltar : TLMDButton
|
00665A40   8B8604030000           mov     eax, [esi+$0304]
00665A46   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
00665A4A   E851EDD9FF             call    004047A0
00665A4F   5E                     pop     esi
00665A50   5D                     pop     ebp
00665A51   C20400                 ret     $0004

*)
end;

procedure TFrmFinaliza._PROC_00665A54(Sender : TObject);
begin
(*
00665A54   55                     push    ebp
00665A55   8BEC                   mov     ebp, esp
00665A57   33C0                   xor     eax, eax
00665A59   55                     push    ebp

* Possible String Reference to: 'éºòÙÿëø]Ã‹Àƒ-¤â}'
|
00665A5A   68795A6600             push    $00665A79

***** TRY
|
00665A5F   64FF30                 push    dword ptr fs:[eax]
00665A62   648920                 mov     fs:[eax], esp
00665A65   FF05A4E27D00           inc     dword ptr [$007DE2A4]
00665A6B   33C0                   xor     eax, eax
00665A6D   5A                     pop     edx
00665A6E   59                     pop     ecx
00665A6F   59                     pop     ecx
00665A70   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-¤â}'
|
00665A73   68805A6600             push    $00665A80
00665A78   C3                     ret


* Reference to: System.@HandleFinally;
|
00665A79   E9BAF2D9FF             jmp     00404D38
00665A7E   EBF8                   jmp     00665A78

****** END
|
00665A80   5D                     pop     ebp
00665A81   C3                     ret

*)
end;

procedure TFrmFinaliza._PROC_00665A84(Sender : TObject);
begin
(*
00665A84   832DA4E27D0001         sub     dword ptr [$007DE2A4], +$01
00665A8B   C3                     ret

*)
end;

procedure TFrmFinaliza._PROC_00665A8C(Sender : TObject);
begin
(*
00665A8C   D85A66                 fcomp   dword ptr [edx+$66]
00665A8F   0000                   add     [eax], al

*)
end;

end.