unit fontes;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DBNumEdt, ExtCtrls, DBCtrls, Mask,
  JvExMask, JvToolEdit, JvDBControls, Buttons, JvExControls, JvComponent,
  JvLabel;
  
type
  TFrmFontes=class(TForm)
    DBStatusLabel1: TJvDBStatusLabel;
    DBText1: TDBText;
    Panel1: TPanel;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbFecha: TSpeedButton;
    DBNavigator1: TDBNavigator;
    EdFonte: TJvDBComboEdit;
    Label1: TLabel;
    Label2: TLabel;
    fdFonte: TFontDialog;
    Label3: TLabel;
    ckSublinhado: TDBCheckBox;
    ckNegrito: TDBCheckBox;
    ckItalico: TDBCheckBox;
    Label5: TLabel;
    EdCorFonte: TJvDBComboEdit;
    cdCor: TColorDialog;
    EdCodFonte: TJvDBComboEdit;
    EdUsoDaFonte: TDBEdit;
    pnFonte: TPanel;
    Label7: TLabel;
    Bevel1: TBevel;
    Label6: TLabel;
    Label8: TLabel;
    Bevel2: TBevel;
    DBRadioGroup1: TDBRadioGroup;
    DBRadioGroup2: TDBRadioGroup;
    DBRadioGroup3: TDBRadioGroup;
    DBRadioGroup4: TDBRadioGroup;
    DBRadioGroup5: TDBRadioGroup;
    EdTamanho: TDBNumEdit;
    procedure sbFechaClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure EdFonteButtonClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure grFontesGetCellParams(Sender : TObject);
    procedure EdCorFonteButtonClick(Sender : TObject);
    procedure EdCodFonteButtonClick(Sender : TObject);
    procedure EdFonteChange(Sender : TObject);
    procedure EdCodFonteEnter(Sender : TObject);
    procedure DBNavigator1BeforeAction(Sender : TObject);
    procedure _PROC_0072A6C8(Sender : TObject);
    procedure _PROC_0072A6F8(Sender : TObject);
    procedure _PROC_0072A700(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmFontes: TFrmFontes;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmFontes.sbFechaClick(Sender : TObject);
begin
(*
00729C6C   55                     push    ebp
00729C6D   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
00729C6F   E84C84D8FF             call    004B20C0
00729C74   5D                     pop     ebp
00729C75   C3                     ret

*)
end;

procedure TFrmFontes.FormShow(Sender : TObject);
begin
(*
00729C78   55                     push    ebp
00729C79   8BEC                   mov     ebp, esp
00729C7B   53                     push    ebx
00729C7C   8BD8                   mov     ebx, eax
00729C7E   6A00                   push    $00

* Possible String Reference to: 'CODFONTE'
|
00729C80   68B89C7200             push    $00729CB8
00729C85   6A01                   push    $01
00729C87   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
00729C8C   8B00                   mov     eax, [eax]
00729C8E   8B80F4000000           mov     eax, [eax+$00F4]
00729C94   B9CC9C7200             mov     ecx, $00729CCC

* Possible String Reference to: 'RELFONTE'
|
00729C99   BAD89C7200             mov     edx, $00729CD8

|
00729C9E   E8C5DD0700             call    007A7A68
00729CA3   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
00729CA5   E8923F0800             call    007ADC3C
00729CAA   5B                     pop     ebx
00729CAB   5D                     pop     ebp
00729CAC   C3                     ret

*)
end;

procedure TFrmFontes.EdFonteButtonClick(Sender : TObject);
begin
(*
00729CE4   55                     push    ebp
00729CE5   8BEC                   mov     ebp, esp
00729CE7   33C9                   xor     ecx, ecx
00729CE9   51                     push    ecx
00729CEA   51                     push    ecx
00729CEB   51                     push    ecx
00729CEC   51                     push    ecx
00729CED   51                     push    ecx
00729CEE   53                     push    ebx
00729CEF   56                     push    esi
00729CF0   57                     push    edi
00729CF1   8BD8                   mov     ebx, eax
00729CF3   8B35B0AA7D00           mov     esi, [$007DAAB0]
00729CF9   33C0                   xor     eax, eax
00729CFB   55                     push    ebp

* Possible String Reference to: 'éo­ÍÿëÛ_^[‹å]Ã'
|
00729CFC   68C49F7200             push    $00729FC4

***** TRY
|
00729D01   64FF30                 push    dword ptr fs:[eax]
00729D04   648920                 mov     fs:[eax], esp
00729D07   8B06                   mov     eax, [esi]
00729D09   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
00729D0F   BADC9F7200             mov     edx, $00729FDC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729D14   E8EBFEDBFF             call    004E9C04
00729D19   8D55FC                 lea     edx, [ebp-$04]
00729D1C   8B08                   mov     ecx, [eax]
00729D1E   FF5160                 call    dword ptr [ecx+$60]
00729D21   837DFC00               cmp     dword ptr [ebp-$04], +$00
00729D25   0F8432010000           jz      00729E5D
00729D2B   8B06                   mov     eax, [esi]
00729D2D   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
00729D33   BADC9F7200             mov     edx, $00729FDC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729D38   E8C7FEDBFF             call    004E9C04
00729D3D   8D55F8                 lea     edx, [ebp-$08]
00729D40   8B08                   mov     ecx, [eax]
00729D42   FF5160                 call    dword ptr [ecx+$60]
00729D45   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729D48   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729D4E   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.SetName(TFont;TFontName);
|
00729D51   E8227FD0FF             call    00431C78
00729D56   8B06                   mov     eax, [esi]
00729D58   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Tamanho'
|
00729D5E   BAEC9F7200             mov     edx, $00729FEC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729D63   E89CFEDBFF             call    004E9C04
00729D68   8B10                   mov     edx, [eax]
00729D6A   FF5258                 call    dword ptr [edx+$58]
00729D6D   8BD0                   mov     edx, eax

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729D6F   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729D75   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.SetSize(TFont;Integer);
|
00729D78   E8737FD0FF             call    00431CF0
00729D7D   8B06                   mov     eax, [esi]
00729D7F   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
00729D85   BAFC9F7200             mov     edx, $00729FFC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729D8A   E875FEDBFF             call    004E9C04
00729D8F   8D55F4                 lea     edx, [ebp-$0C]
00729D92   8B08                   mov     ecx, [eax]
00729D94   FF5160                 call    dword ptr [ecx+$60]
00729D97   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
00729D9A   E8DD77D0FF             call    0043157C
00729D9F   8BD0                   mov     edx, eax

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729DA1   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729DA7   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
00729DAA   E8A17CD0FF             call    00431A50
00729DAF   8B06                   mov     eax, [esi]
00729DB1   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'sublinhado'
|
00729DB7   BA08A07200             mov     edx, $0072A008

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729DBC   E843FEDBFF             call    004E9C04
00729DC1   8B10                   mov     edx, [eax]
00729DC3   FF5244                 call    dword ptr [edx+$44]
00729DC6   84C0                   test    al, al
00729DC8   741F                   jz      00729DE9

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729DCA   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729DD0   8B7858                 mov     edi, [eax+$58]
00729DD3   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729DD5   E8367FD0FF             call    00431D10
00729DDA   8BD0                   mov     edx, eax
00729DDC   0A1514A07200           or      dl, byte ptr [$0072A014]
00729DE2   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
00729DE4   E8337FD0FF             call    00431D1C
00729DE9   8B06                   mov     eax, [esi]
00729DEB   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'bold'
|
00729DF1   BA20A07200             mov     edx, $0072A020

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729DF6   E809FEDBFF             call    004E9C04
00729DFB   8B10                   mov     edx, [eax]
00729DFD   FF5244                 call    dword ptr [edx+$44]
00729E00   84C0                   test    al, al
00729E02   741F                   jz      00729E23

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729E04   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729E0A   8B7858                 mov     edi, [eax+$58]
00729E0D   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729E0F   E8FC7ED0FF             call    00431D10
00729E14   8BD0                   mov     edx, eax
00729E16   0A1528A07200           or      dl, byte ptr [$0072A028]
00729E1C   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
00729E1E   E8F97ED0FF             call    00431D1C
00729E23   8B06                   mov     eax, [esi]
00729E25   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'italico'
|
00729E2B   BA34A07200             mov     edx, $0072A034

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729E30   E8CFFDDBFF             call    004E9C04
00729E35   8B10                   mov     edx, [eax]
00729E37   FF5244                 call    dword ptr [edx+$44]
00729E3A   84C0                   test    al, al
00729E3C   741F                   jz      00729E5D

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729E3E   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729E44   8B7858                 mov     edi, [eax+$58]
00729E47   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729E49   E8C27ED0FF             call    00431D10
00729E4E   8BD0                   mov     edx, eax
00729E50   0A153CA07200           or      dl, byte ptr [$0072A03C]
00729E56   8BC7                   mov     eax, edi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
00729E58   E8BF7ED0FF             call    00431D1C

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729E5D   8B8324030000           mov     eax, [ebx+$0324]
00729E63   8B10                   mov     edx, [eax]

* Reference to method TFontDialog.Execute()
|
00729E65   FF523C                 call    dword ptr [edx+$3C]
00729E68   84C0                   test    al, al
00729E6A   0F8429010000           jz      00729F99
00729E70   8B06                   mov     eax, [esi]
00729E72   8B80F4000000           mov     eax, [eax+$00F4]

|
00729E78   E8A3CF0700             call    007A6E20
00729E7D   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729E80   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729E86   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.GetName(TFont):TFontName;
|
00729E89   E8D27DD0FF             call    00431C60
00729E8E   8B45F0                 mov     eax, [ebp-$10]
00729E91   50                     push    eax
00729E92   8B06                   mov     eax, [esi]
00729E94   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
00729E9A   BADC9F7200             mov     edx, $00729FDC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729E9F   E860FDDBFF             call    004E9C04
00729EA4   5A                     pop     edx
00729EA5   8B08                   mov     ecx, [eax]
00729EA7   FF91B0000000           call    dword ptr [ecx+$00B0]
00729EAD   8B06                   mov     eax, [esi]
00729EAF   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Tamanho'
|
00729EB5   BAEC9F7200             mov     edx, $00729FEC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729EBA   E845FDDBFF             call    004E9C04
00729EBF   50                     push    eax

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729EC0   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729EC6   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.GetSize(TFont):Integer;
|
00729EC9   E8067ED0FF             call    00431CD4
00729ECE   8BD0                   mov     edx, eax
00729ED0   58                     pop     eax
00729ED1   8B08                   mov     ecx, [eax]
00729ED3   FF91A8000000           call    dword ptr [ecx+$00A8]
00729ED9   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729EDC   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729EE2   8B4058                 mov     eax, [eax+$58]

* Reference to field TFont.Color : TColor
|
00729EE5   8B4018                 mov     eax, [eax+$18]

* Reference to: Graphics.ColorToString(TColor):AnsiString;
|
00729EE8   E83776D0FF             call    00431524
00729EED   8B45EC                 mov     eax, [ebp-$14]
00729EF0   50                     push    eax
00729EF1   8B06                   mov     eax, [esi]
00729EF3   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
00729EF9   BAFC9F7200             mov     edx, $00729FFC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729EFE   E801FDDBFF             call    004E9C04
00729F03   5A                     pop     edx
00729F04   8B08                   mov     ecx, [eax]
00729F06   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729F0C   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729F12   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729F15   E8F67DD0FF             call    00431D10
00729F1A   A802                   test    al, $02
00729F1C   0F95C0                 setnz   al
00729F1F   50                     push    eax
00729F20   8B06                   mov     eax, [esi]
00729F22   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Italico'
|
00729F28   BA48A07200             mov     edx, $0072A048

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729F2D   E8D2FCDBFF             call    004E9C04
00729F32   5A                     pop     edx
00729F33   8B08                   mov     ecx, [eax]
00729F35   FF9194000000           call    dword ptr [ecx+$0094]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729F3B   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729F41   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729F44   E8C77DD0FF             call    00431D10
00729F49   A801                   test    al, $01
00729F4B   0F95C0                 setnz   al
00729F4E   50                     push    eax
00729F4F   8B06                   mov     eax, [esi]
00729F51   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Bold'
|
00729F57   BA58A07200             mov     edx, $0072A058

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729F5C   E8A3FCDBFF             call    004E9C04
00729F61   5A                     pop     edx
00729F62   8B08                   mov     ecx, [eax]
00729F64   FF9194000000           call    dword ptr [ecx+$0094]

* Reference to control TFrmFontes.fdFonte : TFontDialog
|
00729F6A   8B8324030000           mov     eax, [ebx+$0324]

* Reference to field TFontDialog.Font : TFont
|
00729F70   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
00729F73   E8987DD0FF             call    00431D10
00729F78   A804                   test    al, $04
00729F7A   0F95C0                 setnz   al
00729F7D   50                     push    eax
00729F7E   8B06                   mov     eax, [esi]
00729F80   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Sublinhado'
|
00729F86   BA68A07200             mov     edx, $0072A068

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00729F8B   E874FCDBFF             call    004E9C04
00729F90   5A                     pop     edx
00729F91   8B08                   mov     ecx, [eax]
00729F93   FF9194000000           call    dword ptr [ecx+$0094]
00729F99   33C0                   xor     eax, eax
00729F9B   5A                     pop     edx
00729F9C   59                     pop     ecx
00729F9D   59                     pop     ecx
00729F9E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
00729FA1   68CB9F7200             push    $00729FCB
00729FA6   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
00729FA9   E8EEB4CDFF             call    0040549C
00729FAE   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.@LStrClr(void;void);
|
00729FB1   E8E6B4CDFF             call    0040549C
00729FB6   8D45F4                 lea     eax, [ebp-$0C]
00729FB9   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00729FBE   E8FDB4CDFF             call    004054C0
00729FC3   C3                     ret


* Reference to: System.@HandleFinally;
|
00729FC4   E96FADCDFF             jmp     00404D38
00729FC9   EBDB                   jmp     00729FA6

****** END
|
00729FCB   5F                     pop     edi
00729FCC   5E                     pop     esi
00729FCD   5B                     pop     ebx
00729FCE   8BE5                   mov     esp, ebp
00729FD0   5D                     pop     ebp
00729FD1   C3                     ret

*)
end;

procedure TFrmFontes.sbAdicionaClick(Sender : TObject);
begin
(*
0072A074   55                     push    ebp
0072A075   8BEC                   mov     ebp, esp
0072A077   53                     push    ebx
0072A078   8BD8                   mov     ebx, eax
0072A07A   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A07F   8B00                   mov     eax, [eax]
0072A081   8B80F4000000           mov     eax, [eax+$00F4]

|
0072A087   E818CC0700             call    007A6CA4
0072A08C   84C0                   test    al, al
0072A08E   740E                   jz      0072A09E

* Reference to control TFrmFontes.EdCodFonte : TJvDBComboEdit
|
0072A090   8B8344030000           mov     eax, [ebx+$0344]
0072A096   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvDBComboEdit.OFFS_00C4
|
0072A098   FF92C4000000           call    dword ptr [edx+$00C4]
0072A09E   5B                     pop     ebx
0072A09F   5D                     pop     ebp
0072A0A0   C3                     ret

*)
end;

procedure TFrmFontes.sbGravaClick(Sender : TObject);
begin
(*
0072A0A4   55                     push    ebp
0072A0A5   8BEC                   mov     ebp, esp
0072A0A7   53                     push    ebx
0072A0A8   8BD8                   mov     ebx, eax
0072A0AA   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A0AF   8B00                   mov     eax, [eax]
0072A0B1   8B80F4000000           mov     eax, [eax+$00F4]

|
0072A0B7   E8A4CE0700             call    007A6F60

* Reference to control TFrmFontes.EdFonte : TJvDBComboEdit
|
0072A0BC   8B9318030000           mov     edx, [ebx+$0318]
0072A0C2   8BC3                   mov     eax, ebx

* Reference to : TFrmFontes.EdFonteChange()
|
0072A0C4   E873030000             call    0072A43C
0072A0C9   5B                     pop     ebx
0072A0CA   5D                     pop     ebp
0072A0CB   C3                     ret

*)
end;

procedure TFrmFontes.sbApagaClick(Sender : TObject);
begin
(*
0072A0CC   55                     push    ebp
0072A0CD   8BEC                   mov     ebp, esp
0072A0CF   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A0D4   8B00                   mov     eax, [eax]
0072A0D6   8B80F4000000           mov     eax, [eax+$00F4]
0072A0DC   B201                   mov     dl, $01

|
0072A0DE   E875D10700             call    007A7258
0072A0E3   5D                     pop     ebp
0072A0E4   C3                     ret

*)
end;

procedure TFrmFontes.grFontesGetCellParams(Sender : TObject);
begin
(*
0072A0E8   55                     push    ebp
0072A0E9   8BEC                   mov     ebp, esp
0072A0EB   6A00                   push    $00
0072A0ED   6A00                   push    $00
0072A0EF   6A00                   push    $00
0072A0F1   6A00                   push    $00
0072A0F3   53                     push    ebx
0072A0F4   8B5D10                 mov     ebx, [ebp+$10]
0072A0F7   33C0                   xor     eax, eax
0072A0F9   55                     push    ebp
0072A0FA   688EA27200             push    $0072A28E

***** TRY
|
0072A0FF   64FF30                 push    dword ptr fs:[eax]
0072A102   648920                 mov     fs:[eax], esp
0072A105   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A10A   8B00                   mov     eax, [eax]
0072A10C   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
0072A112   BAA4A27200             mov     edx, $0072A2A4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A117   E8E8FADBFF             call    004E9C04
0072A11C   8D55FC                 lea     edx, [ebp-$04]
0072A11F   8B08                   mov     ecx, [eax]
0072A121   FF5160                 call    dword ptr [ecx+$60]
0072A124   837DFC00               cmp     dword ptr [ebp-$04], +$00
0072A128   0F8445010000           jz      0072A273
0072A12E   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A133   8B00                   mov     eax, [eax]
0072A135   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Fonte'
|
0072A13B   BAA4A27200             mov     edx, $0072A2A4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A140   E8BFFADBFF             call    004E9C04
0072A145   8D55F8                 lea     edx, [ebp-$08]
0072A148   8B08                   mov     ecx, [eax]
0072A14A   FF5160                 call    dword ptr [ecx+$60]
0072A14D   8B55F8                 mov     edx, [ebp-$08]
0072A150   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetName(TFont;TFontName);
|
0072A152   E8217BD0FF             call    00431C78
0072A157   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A15C   8B00                   mov     eax, [eax]
0072A15E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Tamanho'
|
0072A164   BAB4A27200             mov     edx, $0072A2B4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A169   E896FADBFF             call    004E9C04
0072A16E   8B10                   mov     edx, [eax]
0072A170   FF5258                 call    dword ptr [edx+$58]
0072A173   8BD0                   mov     edx, eax
0072A175   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetSize(TFont;Integer);
|
0072A177   E8747BD0FF             call    00431CF0
0072A17C   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A181   8B00                   mov     eax, [eax]
0072A183   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A189   BAC4A27200             mov     edx, $0072A2C4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A18E   E871FADBFF             call    004E9C04
0072A193   8D55F4                 lea     edx, [ebp-$0C]
0072A196   8B08                   mov     ecx, [eax]
0072A198   FF5160                 call    dword ptr [ecx+$60]
0072A19B   837DF400               cmp     dword ptr [ebp-$0C], +$00
0072A19F   7430                   jz      0072A1D1
0072A1A1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A1A6   8B00                   mov     eax, [eax]
0072A1A8   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A1AE   BAC4A27200             mov     edx, $0072A2C4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A1B3   E84CFADBFF             call    004E9C04
0072A1B8   8D55F0                 lea     edx, [ebp-$10]
0072A1BB   8B08                   mov     ecx, [eax]
0072A1BD   FF5160                 call    dword ptr [ecx+$60]
0072A1C0   8B45F0                 mov     eax, [ebp-$10]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
0072A1C3   E8B473D0FF             call    0043157C
0072A1C8   8BD0                   mov     edx, eax
0072A1CA   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
0072A1CC   E87F78D0FF             call    00431A50
0072A1D1   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A1D6   8B00                   mov     eax, [eax]
0072A1D8   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'sublinhado'
|
0072A1DE   BAD0A27200             mov     edx, $0072A2D0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A1E3   E81CFADBFF             call    004E9C04
0072A1E8   8B10                   mov     edx, [eax]
0072A1EA   FF5244                 call    dword ptr [edx+$44]
0072A1ED   84C0                   test    al, al
0072A1EF   7416                   jz      0072A207
0072A1F1   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A1F3   E8187BD0FF             call    00431D10
0072A1F8   8BD0                   mov     edx, eax
0072A1FA   0A15DCA27200           or      dl, byte ptr [$0072A2DC]
0072A200   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A202   E8157BD0FF             call    00431D1C
0072A207   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A20C   8B00                   mov     eax, [eax]
0072A20E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'bold'
|
0072A214   BAE8A27200             mov     edx, $0072A2E8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A219   E8E6F9DBFF             call    004E9C04
0072A21E   8B10                   mov     edx, [eax]
0072A220   FF5244                 call    dword ptr [edx+$44]
0072A223   84C0                   test    al, al
0072A225   7416                   jz      0072A23D
0072A227   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A229   E8E27AD0FF             call    00431D10
0072A22E   8BD0                   mov     edx, eax
0072A230   0A15F0A27200           or      dl, byte ptr [$0072A2F0]
0072A236   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A238   E8DF7AD0FF             call    00431D1C
0072A23D   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A242   8B00                   mov     eax, [eax]
0072A244   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'italico'
|
0072A24A   BAFCA27200             mov     edx, $0072A2FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A24F   E8B0F9DBFF             call    004E9C04
0072A254   8B10                   mov     edx, [eax]
0072A256   FF5244                 call    dword ptr [edx+$44]
0072A259   84C0                   test    al, al
0072A25B   7416                   jz      0072A273
0072A25D   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A25F   E8AC7AD0FF             call    00431D10
0072A264   8BD0                   mov     edx, eax
0072A266   0A1504A37200           or      dl, byte ptr [$0072A304]
0072A26C   8BC3                   mov     eax, ebx

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A26E   E8A97AD0FF             call    00431D1C
0072A273   33C0                   xor     eax, eax
0072A275   5A                     pop     edx
0072A276   59                     pop     ecx
0072A277   59                     pop     ecx
0072A278   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072A27B   6895A27200             push    $0072A295
0072A280   8D45F0                 lea     eax, [ebp-$10]
0072A283   BA04000000             mov     edx, $00000004

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072A288   E833B2CDFF             call    004054C0
0072A28D   C3                     ret


* Reference to: System.@HandleFinally;
|
0072A28E   E9A5AACDFF             jmp     00404D38
0072A293   EBEB                   jmp     0072A280

****** END
|
0072A295   5B                     pop     ebx
0072A296   8BE5                   mov     esp, ebp
0072A298   5D                     pop     ebp
0072A299   C20C00                 ret     $000C

*)
end;

procedure TFrmFontes.EdCorFonteButtonClick(Sender : TObject);
begin
(*
0072A308   55                     push    ebp
0072A309   8BEC                   mov     ebp, esp
0072A30B   6A00                   push    $00
0072A30D   6A00                   push    $00
0072A30F   6A00                   push    $00
0072A311   53                     push    ebx
0072A312   8BD8                   mov     ebx, eax
0072A314   33C0                   xor     eax, eax
0072A316   55                     push    ebp
0072A317   68E8A37200             push    $0072A3E8

***** TRY
|
0072A31C   64FF30                 push    dword ptr fs:[eax]
0072A31F   648920                 mov     fs:[eax], esp
0072A322   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A327   8B00                   mov     eax, [eax]
0072A329   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A32F   BAFCA37200             mov     edx, $0072A3FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A334   E8CBF8DBFF             call    004E9C04
0072A339   8D55FC                 lea     edx, [ebp-$04]
0072A33C   8B08                   mov     ecx, [eax]
0072A33E   FF5160                 call    dword ptr [ecx+$60]
0072A341   837DFC00               cmp     dword ptr [ebp-$04], +$00
0072A345   7430                   jz      0072A377
0072A347   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A34C   8B00                   mov     eax, [eax]
0072A34E   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A354   BAFCA37200             mov     edx, $0072A3FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A359   E8A6F8DBFF             call    004E9C04
0072A35E   8D55F8                 lea     edx, [ebp-$08]
0072A361   8B08                   mov     ecx, [eax]
0072A363   FF5160                 call    dword ptr [ecx+$60]
0072A366   8B45F8                 mov     eax, [ebp-$08]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
0072A369   E80E72D0FF             call    0043157C

* Reference to control TFrmFontes.cdCor : TColorDialog
|
0072A36E   8B9340030000           mov     edx, [ebx+$0340]

* Reference to field TColorDialog.Color : TColor
|
0072A374   894258                 mov     [edx+$58], eax

* Reference to control TFrmFontes.cdCor : TColorDialog
|
0072A377   8B8340030000           mov     eax, [ebx+$0340]
0072A37D   8B10                   mov     edx, [eax]

* Reference to method TColorDialog.Execute()
|
0072A37F   FF523C                 call    dword ptr [edx+$3C]
0072A382   84C0                   test    al, al
0072A384   7447                   jz      0072A3CD
0072A386   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A38B   8B00                   mov     eax, [eax]
0072A38D   8B80F4000000           mov     eax, [eax+$00F4]

|
0072A393   E888CA0700             call    007A6E20
0072A398   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TFrmFontes.cdCor : TColorDialog
|
0072A39B   8B8340030000           mov     eax, [ebx+$0340]

* Reference to field TColorDialog.Color : TColor
|
0072A3A1   8B4058                 mov     eax, [eax+$58]

* Reference to: Graphics.ColorToString(TColor):AnsiString;
|
0072A3A4   E87B71D0FF             call    00431524
0072A3A9   8B45F4                 mov     eax, [ebp-$0C]
0072A3AC   50                     push    eax
0072A3AD   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A3B2   8B00                   mov     eax, [eax]
0072A3B4   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A3BA   BAFCA37200             mov     edx, $0072A3FC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A3BF   E840F8DBFF             call    004E9C04
0072A3C4   5A                     pop     edx
0072A3C5   8B08                   mov     ecx, [eax]
0072A3C7   FF91B0000000           call    dword ptr [ecx+$00B0]
0072A3CD   33C0                   xor     eax, eax
0072A3CF   5A                     pop     edx
0072A3D0   59                     pop     ecx
0072A3D1   59                     pop     ecx
0072A3D2   648910                 mov     fs:[eax], edx

****** FINALLY
|
0072A3D5   68EFA37200             push    $0072A3EF
0072A3DA   8D45F4                 lea     eax, [ebp-$0C]
0072A3DD   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072A3E2   E8D9B0CDFF             call    004054C0
0072A3E7   C3                     ret


* Reference to: System.@HandleFinally;
|
0072A3E8   E94BA9CDFF             jmp     00404D38
0072A3ED   EBEB                   jmp     0072A3DA

****** END
|
0072A3EF   5B                     pop     ebx
0072A3F0   8BE5                   mov     esp, ebp
0072A3F2   5D                     pop     ebp
0072A3F3   C3                     ret

*)
end;

procedure TFrmFontes.EdCodFonteButtonClick(Sender : TObject);
begin
(*
0072A400   55                     push    ebp
0072A401   8BEC                   mov     ebp, esp
0072A403   53                     push    ebx
0072A404   8BD8                   mov     ebx, eax
0072A406   8BCB                   mov     ecx, ebx
0072A408   B201                   mov     dl, $01

* Reference to class TFrmF2Fontes
|
0072A40A   A1B8917200             mov     eax, dword ptr [$007291B8]

* Reference to: Forms.TCustomForm.Create(TCustomForm;boolean;TComponent);
|
0072A40F   E8FC3AD8FF             call    004ADF10
0072A414   8B15749F7D00           mov     edx, [$007D9F74]
0072A41A   8902                   mov     [edx], eax
0072A41C   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072A421   8B00                   mov     eax, [eax]
0072A423   8B10                   mov     edx, [eax]
0072A425   FF92EC000000           call    dword ptr [edx+$00EC]
0072A42B   A1749F7D00             mov     eax, dword ptr [$007D9F74]
0072A430   8B00                   mov     eax, [eax]

* Reference to: System.TObject.Free(TObject);
|
0072A432   E865A1CDFF             call    0040459C
0072A437   5B                     pop     ebx
0072A438   5D                     pop     ebp
0072A439   C3                     ret

*)
end;

procedure TFrmFontes.EdFonteChange(Sender : TObject);
begin
(*
0072A43C   55                     push    ebp
0072A43D   8BEC                   mov     ebp, esp
0072A43F   33C9                   xor     ecx, ecx
0072A441   51                     push    ecx
0072A442   51                     push    ecx
0072A443   51                     push    ecx
0072A444   51                     push    ecx
0072A445   51                     push    ecx
0072A446   53                     push    ebx
0072A447   56                     push    esi
0072A448   8BD8                   mov     ebx, eax
0072A44A   33C0                   xor     eax, eax
0072A44C   55                     push    ebp

* Possible String Reference to: 'éú¦ÍÿëÛ^[‹å]Ã'
|
0072A44D   6839A67200             push    $0072A639

***** TRY
|
0072A452   64FF30                 push    dword ptr fs:[eax]
0072A455   648920                 mov     fs:[eax], esp
0072A458   A168B67D00             mov     eax, dword ptr [$007DB668]
0072A45D   8B00                   mov     eax, [eax]
0072A45F   8B406C                 mov     eax, [eax+$6C]
0072A462   3B0520F37D00           cmp     eax, [$007DF320]
0072A468   0F85A0010000           jnz     0072A60E
0072A46E   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmFontes.EdFonte : TJvDBComboEdit
|
0072A471   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072A477   E8C03ADDFF             call    004FDF3C
0072A47C   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A47F   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A485   8B4068                 mov     eax, [eax+$68]

* Reference to: Graphics.TFont.SetName(TFont;TFontName);
|
0072A488   E8EB77D0FF             call    00431C78
0072A48D   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TFrmFontes.EdTamanho : TDBNumEdit
|
0072A490   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072A496   E8A13ADDFF             call    004FDF3C
0072A49B   837DF800               cmp     dword ptr [ebp-$08], +$00
0072A49F   7426                   jz      0072A4C7
0072A4A1   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TFrmFontes.EdTamanho : TDBNumEdit
|
0072A4A4   8B8378030000           mov     eax, [ebx+$0378]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072A4AA   E88D3ADDFF             call    004FDF3C
0072A4AF   8B45F4                 mov     eax, [ebp-$0C]

* Reference to: SysUtils.StrToInt(AnsiString):Integer;
|
0072A4B2   E8190ACEFF             call    0040AED0
0072A4B7   8BD0                   mov     edx, eax

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A4B9   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A4BF   8B4068                 mov     eax, [eax+$68]

* Reference to: Graphics.TFont.SetSize(TFont;Integer);
|
0072A4C2   E82978D0FF             call    00431CF0
0072A4C7   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A4CC   8B00                   mov     eax, [eax]
0072A4CE   8B80F4000000           mov     eax, [eax+$00F4]

* Possible String Reference to: 'Cor'
|
0072A4D4   BA50A67200             mov     edx, $0072A650

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0072A4D9   E826F7DBFF             call    004E9C04
0072A4DE   8D55F0                 lea     edx, [ebp-$10]
0072A4E1   8B08                   mov     ecx, [eax]
0072A4E3   FF5160                 call    dword ptr [ecx+$60]
0072A4E6   837DF000               cmp     dword ptr [ebp-$10], +$00
0072A4EA   7426                   jz      0072A512
0072A4EC   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TFrmFontes.EdCorFonte : TJvDBComboEdit
|
0072A4EF   8B833C030000           mov     eax, [ebx+$033C]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
0072A4F5   E8423ADDFF             call    004FDF3C
0072A4FA   8B45EC                 mov     eax, [ebp-$14]

* Reference to: Graphics.StringToColor(AnsiString):TColor;
|
0072A4FD   E87A70D0FF             call    0043157C
0072A502   8BD0                   mov     edx, eax

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A504   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A50A   8B4068                 mov     eax, [eax+$68]

* Reference to: Graphics.TFont.SetColor(TFont;TColor);
|
0072A50D   E83E75D0FF             call    00431A50

* Reference to control TFrmFontes.ckSublinhado : TDBCheckBox
|
0072A512   8B832C030000           mov     eax, [ebx+$032C]
0072A518   8B10                   mov     edx, [eax]

* Reference to method TDBCheckBox.GetChecked()
|
0072A51A   FF92C8000000           call    dword ptr [edx+$00C8]
0072A520   84C0                   test    al, al
0072A522   7421                   jz      0072A545

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A524   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A52A   8B7068                 mov     esi, [eax+$68]
0072A52D   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A52F   E8DC77D0FF             call    00431D10
0072A534   8BD0                   mov     edx, eax
0072A536   0A1554A67200           or      dl, byte ptr [$0072A654]
0072A53C   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A53E   E8D977D0FF             call    00431D1C
0072A543   EB21                   jmp     0072A566

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A545   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A54B   8B7068                 mov     esi, [eax+$68]
0072A54E   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A550   E8BB77D0FF             call    00431D10
0072A555   8A1554A67200           mov     dl, byte ptr [$0072A654]
0072A55B   F7D2                   not     edx 
0072A55D   22D0                   and     dl, al
0072A55F   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A561   E8B677D0FF             call    00431D1C

* Reference to control TFrmFontes.ckNegrito : TDBCheckBox
|
0072A566   8B8330030000           mov     eax, [ebx+$0330]
0072A56C   8B10                   mov     edx, [eax]

* Reference to method TDBCheckBox.GetChecked()
|
0072A56E   FF92C8000000           call    dword ptr [edx+$00C8]
0072A574   84C0                   test    al, al
0072A576   7421                   jz      0072A599

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A578   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A57E   8B7068                 mov     esi, [eax+$68]
0072A581   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A583   E88877D0FF             call    00431D10
0072A588   8BD0                   mov     edx, eax
0072A58A   0A1558A67200           or      dl, byte ptr [$0072A658]
0072A590   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A592   E88577D0FF             call    00431D1C
0072A597   EB21                   jmp     0072A5BA

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A599   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A59F   8B7068                 mov     esi, [eax+$68]
0072A5A2   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A5A4   E86777D0FF             call    00431D10
0072A5A9   8A1558A67200           mov     dl, byte ptr [$0072A658]
0072A5AF   F7D2                   not     edx 
0072A5B1   22D0                   and     dl, al
0072A5B3   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A5B5   E86277D0FF             call    00431D1C

* Reference to control TFrmFontes.ckItalico : TDBCheckBox
|
0072A5BA   8B8334030000           mov     eax, [ebx+$0334]
0072A5C0   8B10                   mov     edx, [eax]

* Reference to method TDBCheckBox.GetChecked()
|
0072A5C2   FF92C8000000           call    dword ptr [edx+$00C8]
0072A5C8   84C0                   test    al, al
0072A5CA   7421                   jz      0072A5ED

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A5CC   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A5D2   8B7068                 mov     esi, [eax+$68]
0072A5D5   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A5D7   E83477D0FF             call    00431D10
0072A5DC   8BD0                   mov     edx, eax
0072A5DE   0A155CA67200           or      dl, byte ptr [$0072A65C]
0072A5E4   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A5E6   E83177D0FF             call    00431D1C
0072A5EB   EB21                   jmp     0072A60E

* Reference to control TFrmFontes.pnFonte : TPanel
|
0072A5ED   8B834C030000           mov     eax, [ebx+$034C]

* Reference to field TPanel.Font : TFont
|
0072A5F3   8B7068                 mov     esi, [eax+$68]
0072A5F6   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.GetStyle(TFont):TFontStyles;
|
0072A5F8   E81377D0FF             call    00431D10
0072A5FD   8A155CA67200           mov     dl, byte ptr [$0072A65C]
0072A603   F7D2                   not     edx 
0072A605   22D0                   and     dl, al
0072A607   8BC6                   mov     eax, esi

* Reference to: Graphics.TFont.SetStyle(TFont;TFontStyles);
|
0072A609   E80E77D0FF             call    00431D1C
0072A60E   33C0                   xor     eax, eax
0072A610   5A                     pop     edx
0072A611   59                     pop     ecx
0072A612   59                     pop     ecx
0072A613   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ã'
|
0072A616   6840A67200             push    $0072A640
0072A61B   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0072A61E   E879AECDFF             call    0040549C
0072A623   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.@LStrClr(void;void);
|
0072A626   E871AECDFF             call    0040549C
0072A62B   8D45F4                 lea     eax, [ebp-$0C]
0072A62E   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0072A633   E888AECDFF             call    004054C0
0072A638   C3                     ret


* Reference to: System.@HandleFinally;
|
0072A639   E9FAA6CDFF             jmp     00404D38
0072A63E   EBDB                   jmp     0072A61B

****** END
|
0072A640   5E                     pop     esi
0072A641   5B                     pop     ebx
0072A642   8BE5                   mov     esp, ebp
0072A644   5D                     pop     ebp
0072A645   C3                     ret

*)
end;

procedure TFrmFontes.EdCodFonteEnter(Sender : TObject);
begin
(*
0072A660   55                     push    ebp
0072A661   8BEC                   mov     ebp, esp

* Reference to control TFrmFontes.EdFonte : TJvDBComboEdit
|
0072A663   8B9018030000           mov     edx, [eax+$0318]

* Reference to : TFrmFontes.EdFonteChange()
|
0072A669   E8CEFDFFFF             call    0072A43C
0072A66E   5D                     pop     ebp
0072A66F   C3                     ret

*)
end;

procedure TFrmFontes.DBNavigator1BeforeAction(Sender : TObject);
begin
(*
0072A670   55                     push    ebp
0072A671   8BEC                   mov     ebp, esp
0072A673   56                     push    esi
0072A674   8BF0                   mov     esi, eax
0072A676   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A67B   8B00                   mov     eax, [eax]
0072A67D   8B80F4000000           mov     eax, [eax+$00F4]
0072A683   8A809D000000           mov     al, byte ptr [eax+$009D]
0072A689   04FE                   add     al, -$02
0072A68B   2C02                   sub     al, $02
0072A68D   7321                   jnb     0072A6B0

* Reference to control TFrmFontes.sbGrava : TSpeedButton
|
0072A68F   8B8608030000           mov     eax, [esi+$0308]
0072A695   8B10                   mov     edx, [eax]

* Reference to method TSpeedButton.GetEnabled()
|
0072A697   FF5250                 call    dword ptr [edx+$50]
0072A69A   84C0                   test    al, al
0072A69C   7412                   jz      0072A6B0

* Reference to control TFrmFontes.sbGrava : TSpeedButton
|
0072A69E   8B8608030000           mov     eax, [esi+$0308]
0072A6A4   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
0072A6A8   E8F3A0CDFF             call    004047A0
0072A6AD   5E                     pop     esi
0072A6AE   5D                     pop     ebp
0072A6AF   C3                     ret

0072A6B0   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
0072A6B5   8B00                   mov     eax, [eax]
0072A6B7   8B80F4000000           mov     eax, [eax+$00F4]

|
0072A6BD   E872CC0700             call    007A7334
0072A6C2   5E                     pop     esi
0072A6C3   5D                     pop     ebp
0072A6C4   C3                     ret

*)
end;

procedure TFrmFontes._PROC_0072A6C8(Sender : TObject);
begin
(*
0072A6C8   55                     push    ebp
0072A6C9   8BEC                   mov     ebp, esp
0072A6CB   33C0                   xor     eax, eax
0072A6CD   55                     push    ebp

* Possible String Reference to: 'éF¦Íÿëø]Ã‹Àƒ-$ó}'
|
0072A6CE   68EDA67200             push    $0072A6ED

***** TRY
|
0072A6D3   64FF30                 push    dword ptr fs:[eax]
0072A6D6   648920                 mov     fs:[eax], esp
0072A6D9   FF0524F37D00           inc     dword ptr [$007DF324]
0072A6DF   33C0                   xor     eax, eax
0072A6E1   5A                     pop     edx
0072A6E2   59                     pop     ecx
0072A6E3   59                     pop     ecx
0072A6E4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-$ó}'
|
0072A6E7   68F4A67200             push    $0072A6F4
0072A6EC   C3                     ret


* Reference to: System.@HandleFinally;
|
0072A6ED   E946A6CDFF             jmp     00404D38
0072A6F2   EBF8                   jmp     0072A6EC

****** END
|
0072A6F4   5D                     pop     ebp
0072A6F5   C3                     ret

*)
end;

procedure TFrmFontes._PROC_0072A6F8(Sender : TObject);
begin
(*
0072A6F8   832D24F37D0001         sub     dword ptr [$007DF324], +$01
0072A6FF   C3                     ret

*)
end;

procedure TFrmFontes._PROC_0072A700(Sender : TObject);
begin
(*
0072A700   4C                     dec     esp
0072A701   A7                     cmpsd
0072A702   7200                   jb      0072A704
0072A704   0000                   add     [eax], al

*)
end;

end.