unit Grupos;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ToolEdit, RXDBCtrl, DBNumEdt,
  JvExMask, JvToolEdit, JvDBControls, Mask, DBCtrls, Buttons, ExtCtrls,
  JvExControls, JvComponent, JvLabel;

type
  TfrmGrupos=class(TForm)
    Panel1: TPanel;
    DBStatusLabel1: TJvDBStatusLabel;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbDesfaz: TSpeedButton;
    sbFecha: TSpeedButton;
    DBText1: TDBText;
    sbImprime: TSpeedButton;
    Label1: TLabel;
    Label2: TLabel;
    EdDescricao: TDBEdit;
    Label4: TLabel;
    Label5: TLabel;
    Label3: TLabel;
    EdUnidMed: TJvDBComboEdit;
    EdSitTrib: TJvDBComboEdit;
    EdClasFisc: TJvDBComboEdit;
    Bevel1: TBevel;
    EdCodGrupo: TJvDBComboEdit;
    LbMargem: TLabel;
    EdMargem: TDBNumEdit;
    edSugDescrProd: TDBEdit;
    Label9: TLabel;
    DBNavigator1: TDBNavigator;
    sbTodos: TSpeedButton;
    EdDescrUnidMed: TDBEdit;
    EdDescrSitTrib: TDBEdit;
    EdDescrClassFisc: TDBEdit;
    Label11: TLabel;
    EdImpressora: TRxDBComboEdit;
    EdDescrImpressora: TDBEdit;
    procedure FormShow(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure sbFechaClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure EdCodGrupoButtonClick(Sender : TObject);
    procedure NvGruposBeforeAction(Sender : TObject);
    procedure sbTodosClick(Sender : TObject);
    procedure EdUnidMedButtonClick(Sender : TObject);
    procedure sbDesfazClick(Sender : TObject);
    procedure EdSitTribButtonClick(Sender : TObject);
    procedure EdClasFiscButtonClick(Sender : TObject);
    procedure EdImpressoraButtonClick(Sender : TObject);
    procedure _PROC_0062F7AF(Sender : TObject);
    procedure _PROC_0062F7C2(Sender : TObject);
    procedure _PROC_0062F7D6(Sender : TObject);
    procedure _PROC_0062F91E(Sender : TObject);
    procedure _PROC_0062F93B(Sender : TObject);
    procedure _PROC_0062FA0D(Sender : TObject);
    procedure _PROC_0062FA31(Sender : TObject);
    procedure _PROC_0062FA55(Sender : TObject);
    procedure _PROC_0062FDE9(Sender : TObject);
    procedure _PROC_0062FE18(Sender : TObject);
    procedure _PROC_0062FE20(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmGrupos: TfrmGrupos;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmGrupos.FormShow(Sender : TObject);
begin
(*
0062F5C4   55                     push    ebp
0062F5C5   8BEC                   mov     ebp, esp
0062F5C7   53                     push    ebx
0062F5C8   8BD8                   mov     ebx, eax
0062F5CA   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
0062F5CC   E86BE61700             call    007ADC3C
0062F5D1   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F5D6   8B00                   mov     eax, [eax]
0062F5D8   8B8084000000           mov     eax, [eax+$0084]
0062F5DE   895844                 mov     [eax+$44], ebx

* Possible String Reference to: '√ç@'
|
0062F5E1   C74040C0F56200         mov     dword ptr [eax+$40], $0062F5C0
0062F5E8   5B                     pop     ebx
0062F5E9   5D                     pop     ebp
0062F5EA   C3                     ret

*)
end;

procedure TfrmGrupos.FormClose(Sender : TObject);
begin
(*
0062F5EC   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F5F1   8B00                   mov     eax, [eax]
0062F5F3   8B8084000000           mov     eax, [eax+$0084]
0062F5F9   33D2                   xor     edx, edx
0062F5FB   895040                 mov     [eax+$40], edx
0062F5FE   895044                 mov     [eax+$44], edx
0062F601   C3                     ret

*)
end;

procedure TfrmGrupos.sbFechaClick(Sender : TObject);
begin
(*
0062F604   55                     push    ebp
0062F605   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
0062F607   E8B42AE8FF             call    004B20C0
0062F60C   5D                     pop     ebp
0062F60D   C3                     ret

*)
end;

procedure TfrmGrupos.sbAdicionaClick(Sender : TObject);
begin
(*
0062F610   55                     push    ebp
0062F611   8BEC                   mov     ebp, esp
0062F613   53                     push    ebx
0062F614   8BD8                   mov     ebx, eax
0062F616   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F61B   8B00                   mov     eax, [eax]
0062F61D   8B8080000000           mov     eax, [eax+$0080]

|
0062F623   E87C761700             call    007A6CA4
0062F628   84C0                   test    al, al
0062F62A   740E                   jz      0062F63A

* Reference to control TfrmGrupos.EdCodGrupo : TJvDBComboEdit
|
0062F62C   8B8344030000           mov     eax, [ebx+$0344]
0062F632   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvDBComboEdit.OFFS_00C4
|
0062F634   FF92C4000000           call    dword ptr [edx+$00C4]
0062F63A   5B                     pop     ebx
0062F63B   5D                     pop     ebp
0062F63C   C3                     ret

*)
end;

procedure TfrmGrupos.sbGravaClick(Sender : TObject);
begin
(*
0062F640   55                     push    ebp
0062F641   8BEC                   mov     ebp, esp
0062F643   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F648   8B00                   mov     eax, [eax]
0062F64A   8B8080000000           mov     eax, [eax+$0080]

|
0062F650   E80B791700             call    007A6F60
0062F655   5D                     pop     ebp
0062F656   C3                     ret

*)
end;

procedure TfrmGrupos.sbApagaClick(Sender : TObject);
begin
(*
0062F658   55                     push    ebp
0062F659   8BEC                   mov     ebp, esp
0062F65B   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F660   8B00                   mov     eax, [eax]
0062F662   8B8080000000           mov     eax, [eax+$0080]
0062F668   B201                   mov     dl, $01

|
0062F66A   E8E97B1700             call    007A7258
0062F66F   5D                     pop     ebp
0062F670   C3                     ret

*)
end;

procedure TfrmGrupos.EdCodGrupoButtonClick(Sender : TObject);
begin
(*
0062F674   55                     push    ebp
0062F675   8BEC                   mov     ebp, esp
0062F677   83C4E4                 add     esp, -$1C
0062F67A   33C9                   xor     ecx, ecx
0062F67C   894DEC                 mov     [ebp-$14], ecx
0062F67F   894DE8                 mov     [ebp-$18], ecx
0062F682   894DE4                 mov     [ebp-$1C], ecx
0062F685   33C0                   xor     eax, eax
0062F687   55                     push    ebp

* Possible String Reference to: 'ÈÈU›ˇÎÎãÂ]√'
|
0062F688   684AF76200             push    $0062F74A

***** TRY
|
0062F68D   64FF30                 push    dword ptr fs:[eax]
0062F690   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'cÛdigo'
|
0062F693   B860F76200             mov     eax, $0062F760
0062F698   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
0062F69B   B870F76200             mov     eax, $0062F770
0062F6A0   8945FC                 mov     [ebp-$04], eax
0062F6A3   8D45F8                 lea     eax, [ebp-$08]
0062F6A6   50                     push    eax
0062F6A7   6A01                   push    $01
0062F6A9   6A00                   push    $00

* Possible String Reference to: 'CodGrupo'
|
0062F6AB   B884F76200             mov     eax, $0062F784
0062F6B0   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Descricao'
|
0062F6B3   B898F76200             mov     eax, $0062F798
0062F6B8   8945F4                 mov     [ebp-$0C], eax
0062F6BB   8D55F0                 lea     edx, [ebp-$10]
0062F6BE   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'GRUPOS'
|
0062F6C3   B8ACF76200             mov     eax, $0062F7AC

|
0062F6C8   E8879B0000             call    00639254
0062F6CD   84C0                   test    al, al
0062F6CF   745E                   jz      0062F72F
0062F6D1   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0062F6D6   8B00                   mov     eax, [eax]
0062F6D8   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODGRUPO'
|
0062F6DB   BABCF76200             mov     edx, $0062F7BC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0062F6E0   E81FA5EBFF             call    004E9C04
0062F6E5   8D55E4                 lea     edx, [ebp-$1C]
0062F6E8   8B08                   mov     ecx, [eax]
0062F6EA   FF5160                 call    dword ptr [ecx+$60]
0062F6ED   8B45E4                 mov     eax, [ebp-$1C]
0062F6F0   8D55E8                 lea     edx, [ebp-$18]

* Reference to: SysUtils.QuotedStr(AnsiString):AnsiString;
|
0062F6F3   E8D0B1DDFF             call    0040A8C8
0062F6F8   8B4DE8                 mov     ecx, [ebp-$18]
0062F6FB   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'CODGRUPO = '
|
0062F6FE   BAD0F76200             mov     edx, $0062F7D0

* Reference to: System.@LStrCat3;
|
0062F703   E8A060DDFF             call    004057A8
0062F708   8B45EC                 mov     eax, [ebp-$14]
0062F70B   50                     push    eax

* Possible String Reference to: 'CODGRUPO'
|
0062F70C   68BCF76200             push    $0062F7BC
0062F711   6A01                   push    $01
0062F713   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F718   8B00                   mov     eax, [eax]
0062F71A   8B8080000000           mov     eax, [eax+$0080]
0062F720   B9E4F76200             mov     ecx, $0062F7E4

* Possible String Reference to: 'GRUPOS'
|
0062F725   BAACF76200             mov     edx, $0062F7AC

|
0062F72A   E839831700             call    007A7A68
0062F72F   33C0                   xor     eax, eax
0062F731   5A                     pop     edx
0062F732   59                     pop     ecx
0062F733   59                     pop     ecx
0062F734   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062F737   6851F76200             push    $0062F751
0062F73C   8D45E4                 lea     eax, [ebp-$1C]
0062F73F   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0062F744   E8775DDDFF             call    004054C0
0062F749   C3                     ret


* Reference to: System.@HandleFinally;
|
0062F74A   E9E955DDFF             jmp     00404D38
0062F74F   EBEB                   jmp     0062F73C

****** END
|
0062F751   8BE5                   mov     esp, ebp
0062F753   5D                     pop     ebp
0062F754   C3                     ret

*)
end;

procedure TfrmGrupos.NvGruposBeforeAction(Sender : TObject);
begin
(*
0062F7E8   55                     push    ebp
0062F7E9   8BEC                   mov     ebp, esp
0062F7EB   56                     push    esi
0062F7EC   8BF0                   mov     esi, eax
0062F7EE   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F7F3   8B00                   mov     eax, [eax]
0062F7F5   8B8080000000           mov     eax, [eax+$0080]
0062F7FB   8A809D000000           mov     al, byte ptr [eax+$009D]
0062F801   04FE                   add     al, -$02
0062F803   2C02                   sub     al, $02
0062F805   7321                   jnb     0062F828

* Reference to control TfrmGrupos.sbGrava : TSpeedButton
|
0062F807   8B8604030000           mov     eax, [esi+$0304]
0062F80D   8B10                   mov     edx, [eax]

* Reference to method TSpeedButton.GetEnabled()
|
0062F80F   FF5250                 call    dword ptr [edx+$50]
0062F812   84C0                   test    al, al
0062F814   7412                   jz      0062F828

* Reference to control TfrmGrupos.sbGrava : TSpeedButton
|
0062F816   8B8604030000           mov     eax, [esi+$0304]
0062F81C   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
0062F820   E87B4FDDFF             call    004047A0
0062F825   5E                     pop     esi
0062F826   5D                     pop     ebp
0062F827   C3                     ret

0062F828   8B860C030000           mov     eax, [esi+$030C]
0062F82E   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
0062F832   E8694FDDFF             call    004047A0
0062F837   5E                     pop     esi
0062F838   5D                     pop     ebp
0062F839   C3                     ret

*)
end;

procedure TfrmGrupos.sbTodosClick(Sender : TObject);
begin
(*
0062F83C   55                     push    ebp
0062F83D   8BEC                   mov     ebp, esp
0062F83F   33C9                   xor     ecx, ecx
0062F841   51                     push    ecx
0062F842   51                     push    ecx
0062F843   51                     push    ecx
0062F844   51                     push    ecx
0062F845   51                     push    ecx
0062F846   51                     push    ecx
0062F847   33C0                   xor     eax, eax
0062F849   55                     push    ebp

* Possible String Reference to: 'È0T›ˇÎ„ãÂ]√'
|
0062F84A   6803F96200             push    $0062F903

***** TRY
|
0062F84F   64FF30                 push    dword ptr fs:[eax]
0062F852   648920                 mov     fs:[eax], esp
0062F855   8D55FC                 lea     edx, [ebp-$04]
0062F858   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F85D   8B00                   mov     eax, [eax]
0062F85F   8B8088000000           mov     eax, [eax+$0088]
0062F865   8B08                   mov     ecx, [eax]
0062F867   FF5160                 call    dword ptr [ecx+$60]
0062F86A   6A00                   push    $00

* Possible String Reference to: 'CODGRUPO'
|
0062F86C   6818F96200             push    $0062F918
0062F871   6A01                   push    $01
0062F873   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F878   8B00                   mov     eax, [eax]
0062F87A   8B8080000000           mov     eax, [eax+$0080]
0062F880   B92CF96200             mov     ecx, $0062F92C

* Possible String Reference to: 'GRUPOS'
|
0062F885   BA38F96200             mov     edx, $0062F938

|
0062F88A   E8D9811700             call    007A7A68
0062F88F   84C0                   test    al, al
0062F891   744D                   jz      0062F8E0
0062F893   8D55F8                 lea     edx, [ebp-$08]
0062F896   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F89B   8B00                   mov     eax, [eax]
0062F89D   8B8088000000           mov     eax, [eax+$0088]
0062F8A3   8B08                   mov     ecx, [eax]
0062F8A5   FF5160                 call    dword ptr [ecx+$60]
0062F8A8   8B45F8                 mov     eax, [ebp-$08]
0062F8AB   8B55FC                 mov     edx, [ebp-$04]

* Reference to: System.@LStrCmp;
|
0062F8AE   E8F55FDDFF             call    004058A8
0062F8B3   742B                   jz      0062F8E0
0062F8B5   A040F96200             mov     al, byte ptr [$0062F940]
0062F8BA   50                     push    eax
0062F8BB   8D45E8                 lea     eax, [ebp-$18]
0062F8BE   8B55FC                 mov     edx, [ebp-$04]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0062F8C1   E8FE93DEFF             call    00418CC4
0062F8C6   8D4DE8                 lea     ecx, [ebp-$18]
0062F8C9   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F8CE   8B00                   mov     eax, [eax]
0062F8D0   8B8080000000           mov     eax, [eax+$0080]

* Possible String Reference to: 'CODGRUPO'
|
0062F8D6   BA18F96200             mov     edx, $0062F918

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0062F8DB   E8188B1700             call    007A83F8
0062F8E0   33C0                   xor     eax, eax
0062F8E2   5A                     pop     edx
0062F8E3   59                     pop     ecx
0062F8E4   59                     pop     ecx
0062F8E5   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062F8E8   680AF96200             push    $0062F90A
0062F8ED   8D45E8                 lea     eax, [ebp-$18]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0062F8F0   E8834CDEFF             call    00414578
0062F8F5   8D45F8                 lea     eax, [ebp-$08]
0062F8F8   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0062F8FD   E8BE5BDDFF             call    004054C0
0062F902   C3                     ret


* Reference to: System.@HandleFinally;
|
0062F903   E93054DDFF             jmp     00404D38
0062F908   EBE3                   jmp     0062F8ED

****** END
|
0062F90A   8BE5                   mov     esp, ebp
0062F90C   5D                     pop     ebp
0062F90D   C3                     ret

*)
end;

procedure TfrmGrupos.EdUnidMedButtonClick(Sender : TObject);
begin
(*
0062F944   55                     push    ebp
0062F945   8BEC                   mov     ebp, esp
0062F947   83C4EC                 add     esp, -$14
0062F94A   33C9                   xor     ecx, ecx
0062F94C   894DEC                 mov     [ebp-$14], ecx
0062F94F   33C0                   xor     eax, eax
0062F951   55                     push    ebp

* Possible String Reference to: 'È<S›ˇÎãÂ]√'
|
0062F952   68F7F96200             push    $0062F9F7

***** TRY
|
0062F957   64FF30                 push    dword ptr fs:[eax]
0062F95A   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'Unidade'
|
0062F95D   B80CFA6200             mov     eax, $0062FA0C
0062F962   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
0062F965   B81CFA6200             mov     eax, $0062FA1C
0062F96A   8945FC                 mov     [ebp-$04], eax
0062F96D   8D45F8                 lea     eax, [ebp-$08]
0062F970   50                     push    eax
0062F971   6A01                   push    $01
0062F973   6A00                   push    $00

* Possible String Reference to: 'UNIDMED'
|
0062F975   B830FA6200             mov     eax, $0062FA30
0062F97A   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'DESCRICAO'
|
0062F97D   B840FA6200             mov     eax, $0062FA40
0062F982   8945F4                 mov     [ebp-$0C], eax
0062F985   8D55F0                 lea     edx, [ebp-$10]
0062F988   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'UNIDMED'
|
0062F98D   B830FA6200             mov     eax, $0062FA30

|
0062F992   E8BD980000             call    00639254
0062F997   84C0                   test    al, al
0062F999   7446                   jz      0062F9E1
0062F99B   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F9A0   8B00                   mov     eax, [eax]
0062F9A2   8B8080000000           mov     eax, [eax+$0080]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0062F9A8   E88BBAEBFF             call    004EB438
0062F9AD   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0062F9B2   8B00                   mov     eax, [eax]
0062F9B4   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'UnidMed'
|
0062F9B7   BA54FA6200             mov     edx, $0062FA54

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0062F9BC   E843A2EBFF             call    004E9C04
0062F9C1   8D55EC                 lea     edx, [ebp-$14]
0062F9C4   8B08                   mov     ecx, [eax]
0062F9C6   FF5160                 call    dword ptr [ecx+$60]
0062F9C9   8B55EC                 mov     edx, [ebp-$14]
0062F9CC   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062F9D1   8B00                   mov     eax, [eax]
0062F9D3   8B8090000000           mov     eax, [eax+$0090]
0062F9D9   8B08                   mov     ecx, [eax]
0062F9DB   FF91B0000000           call    dword ptr [ecx+$00B0]
0062F9E1   33C0                   xor     eax, eax
0062F9E3   5A                     pop     edx
0062F9E4   59                     pop     ecx
0062F9E5   59                     pop     ecx
0062F9E6   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062F9E9   68FEF96200             push    $0062F9FE
0062F9EE   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0062F9F1   E8A65ADDFF             call    0040549C
0062F9F6   C3                     ret


* Reference to: System.@HandleFinally;
|
0062F9F7   E93C53DDFF             jmp     00404D38
0062F9FC   EBF0                   jmp     0062F9EE

****** END
|
0062F9FE   8BE5                   mov     esp, ebp
0062FA00   5D                     pop     ebp
0062FA01   C3                     ret

*)
end;

procedure TfrmGrupos.sbDesfazClick(Sender : TObject);
begin
(*
0062FA5C   55                     push    ebp
0062FA5D   8BEC                   mov     ebp, esp
0062FA5F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FA64   8B00                   mov     eax, [eax]
0062FA66   8B8080000000           mov     eax, [eax+$0080]

|
0062FA6C   E8C3781700             call    007A7334
0062FA71   5D                     pop     ebp
0062FA72   C3                     ret

*)
end;

procedure TfrmGrupos.EdSitTribButtonClick(Sender : TObject);
begin
(*
0062FA74   55                     push    ebp
0062FA75   8BEC                   mov     ebp, esp
0062FA77   83C4EC                 add     esp, -$14
0062FA7A   33C9                   xor     ecx, ecx
0062FA7C   894DEC                 mov     [ebp-$14], ecx
0062FA7F   33C0                   xor     eax, eax
0062FA81   55                     push    ebp
0062FA82   6827FB6200             push    $0062FB27

***** TRY
|
0062FA87   64FF30                 push    dword ptr fs:[eax]
0062FA8A   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'Sit. Trib'
|
0062FA8D   B83CFB6200             mov     eax, $0062FB3C
0062FA92   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
0062FA95   B850FB6200             mov     eax, $0062FB50
0062FA9A   8945FC                 mov     [ebp-$04], eax
0062FA9D   8D45F8                 lea     eax, [ebp-$08]
0062FAA0   50                     push    eax
0062FAA1   6A01                   push    $01
0062FAA3   6A00                   push    $00

* Possible String Reference to: 'SITTRIB'
|
0062FAA5   B864FB6200             mov     eax, $0062FB64
0062FAAA   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'DESCRICAO'
|
0062FAAD   B874FB6200             mov     eax, $0062FB74
0062FAB2   8945F4                 mov     [ebp-$0C], eax
0062FAB5   8D55F0                 lea     edx, [ebp-$10]
0062FAB8   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'SITTRIB'
|
0062FABD   B864FB6200             mov     eax, $0062FB64

|
0062FAC2   E88D970000             call    00639254
0062FAC7   84C0                   test    al, al
0062FAC9   7446                   jz      0062FB11
0062FACB   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FAD0   8B00                   mov     eax, [eax]
0062FAD2   8B8080000000           mov     eax, [eax+$0080]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0062FAD8   E85BB9EBFF             call    004EB438
0062FADD   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0062FAE2   8B00                   mov     eax, [eax]
0062FAE4   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'SitTrib'
|
0062FAE7   BA88FB6200             mov     edx, $0062FB88

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0062FAEC   E813A1EBFF             call    004E9C04
0062FAF1   8D55EC                 lea     edx, [ebp-$14]
0062FAF4   8B08                   mov     ecx, [eax]
0062FAF6   FF5160                 call    dword ptr [ecx+$60]
0062FAF9   8B55EC                 mov     edx, [ebp-$14]
0062FAFC   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FB01   8B00                   mov     eax, [eax]
0062FB03   8B8094000000           mov     eax, [eax+$0094]
0062FB09   8B08                   mov     ecx, [eax]
0062FB0B   FF91B0000000           call    dword ptr [ecx+$00B0]
0062FB11   33C0                   xor     eax, eax
0062FB13   5A                     pop     edx
0062FB14   59                     pop     ecx
0062FB15   59                     pop     ecx
0062FB16   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062FB19   682EFB6200             push    $0062FB2E
0062FB1E   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0062FB21   E87659DDFF             call    0040549C
0062FB26   C3                     ret


* Reference to: System.@HandleFinally;
|
0062FB27   E90C52DDFF             jmp     00404D38
0062FB2C   EBF0                   jmp     0062FB1E

****** END
|
0062FB2E   8BE5                   mov     esp, ebp
0062FB30   5D                     pop     ebp
0062FB31   C3                     ret

*)
end;

procedure TfrmGrupos.EdClasFiscButtonClick(Sender : TObject);
begin
(*
0062FB90   55                     push    ebp
0062FB91   8BEC                   mov     ebp, esp
0062FB93   83C4EC                 add     esp, -$14
0062FB96   33C9                   xor     ecx, ecx
0062FB98   894DEC                 mov     [ebp-$14], ecx
0062FB9B   33C0                   xor     eax, eax
0062FB9D   55                     push    ebp

* Possible String Reference to: 'ÈP›ˇÎãÂ]√'
|
0062FB9E   6843FC6200             push    $0062FC43

***** TRY
|
0062FBA3   64FF30                 push    dword ptr fs:[eax]
0062FBA6   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'Class. Fiscal'
|
0062FBA9   B858FC6200             mov     eax, $0062FC58
0062FBAE   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
0062FBB1   B870FC6200             mov     eax, $0062FC70
0062FBB6   8945FC                 mov     [ebp-$04], eax
0062FBB9   8D45F8                 lea     eax, [ebp-$08]
0062FBBC   50                     push    eax
0062FBBD   6A01                   push    $01
0062FBBF   6A00                   push    $00

* Possible String Reference to: 'CLASSFISC'
|
0062FBC1   B884FC6200             mov     eax, $0062FC84
0062FBC6   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'DESCRICAO'
|
0062FBC9   B898FC6200             mov     eax, $0062FC98
0062FBCE   8945F4                 mov     [ebp-$0C], eax
0062FBD1   8D55F0                 lea     edx, [ebp-$10]
0062FBD4   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'CLASFISC'
|
0062FBD9   B8ACFC6200             mov     eax, $0062FCAC

|
0062FBDE   E871960000             call    00639254
0062FBE3   84C0                   test    al, al
0062FBE5   7446                   jz      0062FC2D
0062FBE7   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FBEC   8B00                   mov     eax, [eax]
0062FBEE   8B8080000000           mov     eax, [eax+$0080]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0062FBF4   E83FB8EBFF             call    004EB438
0062FBF9   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0062FBFE   8B00                   mov     eax, [eax]
0062FC00   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'ClassFisc'
|
0062FC03   BAC0FC6200             mov     edx, $0062FCC0

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0062FC08   E8F79FEBFF             call    004E9C04
0062FC0D   8D55EC                 lea     edx, [ebp-$14]
0062FC10   8B08                   mov     ecx, [eax]
0062FC12   FF5160                 call    dword ptr [ecx+$60]
0062FC15   8B55EC                 mov     edx, [ebp-$14]
0062FC18   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FC1D   8B00                   mov     eax, [eax]
0062FC1F   8B8098000000           mov     eax, [eax+$0098]
0062FC25   8B08                   mov     ecx, [eax]
0062FC27   FF91B0000000           call    dword ptr [ecx+$00B0]
0062FC2D   33C0                   xor     eax, eax
0062FC2F   5A                     pop     edx
0062FC30   59                     pop     ecx
0062FC31   59                     pop     ecx
0062FC32   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062FC35   684AFC6200             push    $0062FC4A
0062FC3A   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0062FC3D   E85A58DDFF             call    0040549C
0062FC42   C3                     ret


* Reference to: System.@HandleFinally;
|
0062FC43   E9F050DDFF             jmp     00404D38
0062FC48   EBF0                   jmp     0062FC3A

****** END
|
0062FC4A   8BE5                   mov     esp, ebp
0062FC4C   5D                     pop     ebp
0062FC4D   C3                     ret

*)
end;

procedure TfrmGrupos.EdImpressoraButtonClick(Sender : TObject);
begin
(*
0062FCCC   55                     push    ebp
0062FCCD   8BEC                   mov     ebp, esp
0062FCCF   83C4EC                 add     esp, -$14
0062FCD2   33C9                   xor     ecx, ecx
0062FCD4   894DEC                 mov     [ebp-$14], ecx
0062FCD7   33C0                   xor     eax, eax
0062FCD9   55                     push    ebp

* Possible String Reference to: 'È¥O›ˇÎãÂ]√'
|
0062FCDA   687FFD6200             push    $0062FD7F

***** TRY
|
0062FCDF   64FF30                 push    dword ptr fs:[eax]
0062FCE2   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'cÛdigo'
|
0062FCE5   B894FD6200             mov     eax, $0062FD94
0062FCEA   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
0062FCED   B8A4FD6200             mov     eax, $0062FDA4
0062FCF2   8945FC                 mov     [ebp-$04], eax
0062FCF5   8D45F8                 lea     eax, [ebp-$08]
0062FCF8   50                     push    eax
0062FCF9   6A01                   push    $01
0062FCFB   6A00                   push    $00

* Possible String Reference to: 'CodImpr'
|
0062FCFD   B8B8FD6200             mov     eax, $0062FDB8
0062FD02   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Descricao'
|
0062FD05   B8C8FD6200             mov     eax, $0062FDC8
0062FD0A   8945F4                 mov     [ebp-$0C], eax
0062FD0D   8D55F0                 lea     edx, [ebp-$10]
0062FD10   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRGRILL'
|
0062FD15   B8DCFD6200             mov     eax, $0062FDDC

|
0062FD1A   E835950000             call    00639254
0062FD1F   84C0                   test    al, al
0062FD21   7446                   jz      0062FD69
0062FD23   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FD28   8B00                   mov     eax, [eax]
0062FD2A   8B8080000000           mov     eax, [eax+$0080]

|
0062FD30   E8EB701700             call    007A6E20
0062FD35   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0062FD3A   8B00                   mov     eax, [eax]
0062FD3C   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CodImpr'
|
0062FD3F   BAB8FD6200             mov     edx, $0062FDB8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0062FD44   E8BB9EEBFF             call    004E9C04
0062FD49   8D55EC                 lea     edx, [ebp-$14]
0062FD4C   8B08                   mov     ecx, [eax]
0062FD4E   FF5160                 call    dword ptr [ecx+$60]
0062FD51   8B55EC                 mov     edx, [ebp-$14]
0062FD54   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FD59   8B00                   mov     eax, [eax]
0062FD5B   8B80000C0000           mov     eax, [eax+$0C00]
0062FD61   8B08                   mov     ecx, [eax]
0062FD63   FF91B0000000           call    dword ptr [ecx+$00B0]
0062FD69   33C0                   xor     eax, eax
0062FD6B   5A                     pop     edx
0062FD6C   59                     pop     ecx
0062FD6D   59                     pop     ecx
0062FD6E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
0062FD71   6886FD6200             push    $0062FD86
0062FD76   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
0062FD79   E81E57DDFF             call    0040549C
0062FD7E   C3                     ret


* Reference to: System.@HandleFinally;
|
0062FD7F   E9B44FDDFF             jmp     00404D38
0062FD84   EBF0                   jmp     0062FD76

****** END
|
0062FD86   8BE5                   mov     esp, ebp
0062FD88   5D                     pop     ebp
0062FD89   C3                     ret

*)
end;

procedure TfrmGrupos._PROC_0062F7AF(Sender : TObject);
begin
(*
0062F7AF   50                     push    eax
0062F7B0   4F                     dec     edi
0062F7B1   53                     push    ebx
0062F7B2   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062F7C2(Sender : TObject);
begin
(*
0062F7C2   50                     push    eax
0062F7C3   4F                     dec     edi
0062F7C4   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062F7D6(Sender : TObject);
begin
(*
0062F7D6   50                     push    eax
0062F7D7   4F                     dec     edi
0062F7D8   203D2000FFFF           and     [$FFFF0020], bh
0062F7DE   FFFF                   DB  $FF, $FF  //      
0062F7E0   0100                   add     [eax], eax
0062F7E2   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062F91E(Sender : TObject);
begin
(*
0062F91E   50                     push    eax
0062F91F   4F                     dec     edi
0062F920   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062F93B(Sender : TObject);
begin
(*
0062F93B   50                     push    eax
0062F93C   4F                     dec     edi
0062F93D   53                     push    ebx
0062F93E   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062FA0D(Sender : TObject);
begin
(*
0062FA0D   6E                     outsb
0062FA0E   696461646500FFFF       imul    esp, [ecx+$64], $FFFF0065
0062FA16   FFFF                   DB  $FF, $FF  //      
0062FA18   0900                   or      [eax], eax
0062FA1A   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062FA31(Sender : TObject);
begin
(*
0062FA31   4E                     dec     esi
0062FA32   49                     dec     ecx
0062FA33   44                     inc     esp
0062FA34   4D                     dec     ebp
0062FA35   45                     inc     ebp
0062FA36   44                     inc     esp
0062FA37   00FF                   add     bh, bh
0062FA39   FFFF                   DB  $FF, $FF  //      
0062FA3B   FF09                   dec     dword ptr [ecx]
0062FA3D   0000                   add     [eax], al

*)
end;

procedure TfrmGrupos._PROC_0062FA55(Sender : TObject);
begin
(*
0062FA55   6E                     outsb
0062FA56   69644D656400558B       imul    esp, [ebp+ecx*2+$65], $8B550064
0062FA5E   EC                     in      al, dx
0062FA5F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0062FA64   8B00                   mov     eax, [eax]
0062FA66   8B8080000000           mov     eax, [eax+$0080]

|
0062FA6C   E8C3781700             call    007A7334
0062FA71   5D                     pop     ebp
0062FA72   C3                     ret

*)
end;

procedure TfrmGrupos._PROC_0062FDE9(Sender : TObject);
begin
(*
0062FDE9   8BEC                   mov     ebp, esp
0062FDEB   33C0                   xor     eax, eax
0062FDED   55                     push    ebp

* Possible String Reference to: 'È&O›ˇÎ¯]√ã¿É-¿‹}'
|
0062FDEE   680DFE6200             push    $0062FE0D

***** TRY
|
0062FDF3   64FF30                 push    dword ptr fs:[eax]
0062FDF6   648920                 mov     fs:[eax], esp
0062FDF9   FF05C0DC7D00           inc     dword ptr [$007DDCC0]
0062FDFF   33C0                   xor     eax, eax
0062FE01   5A                     pop     edx
0062FE02   59                     pop     ecx
0062FE03   59                     pop     ecx
0062FE04   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-¿‹}'
|
0062FE07   6814FE6200             push    $0062FE14
0062FE0C   C3                     ret


* Reference to: System.@HandleFinally;
|
0062FE0D   E9264FDDFF             jmp     00404D38
0062FE12   EBF8                   jmp     0062FE0C

****** END
|
0062FE14   5D                     pop     ebp
0062FE15   C3                     ret

*)
end;

procedure TfrmGrupos._PROC_0062FE18(Sender : TObject);
begin
(*
0062FE18   832DC0DC7D0001         sub     dword ptr [$007DDCC0], +$01
0062FE1F   C3                     ret

*)
end;

procedure TfrmGrupos._PROC_0062FE20(Sender : TObject);
begin
(*
0062FE20   6C                     insb
0062FE21   FE62                   DB  $FE, $62  //      
0062FE23   0000                   add     [eax], al

*)
end;

end.