unit ImpGrill;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, PBPrinterSetupDialog, DBCtrls,
  JvExMask, JvToolEdit, JvDBControls, Mask, Buttons, ExtCtrls,
  JvExControls, JvComponent, JvLabel;
  
type
  TFrmImprGrill=class(TForm)
    Panel1: TPanel;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbDesfaz: TSpeedButton;
    sbFecha: TSpeedButton;
    DBText1: TDBText;
    sbImprime: TSpeedButton;
    Label1: TLabel;
    Label2: TLabel;
    EdDescricao: TDBEdit;
    Bevel1: TBevel;
    EdCodImpr: TJvDBComboEdit;
    DBNavigator1: TDBNavigator;
    sbTodos: TSpeedButton;
    Label3: TLabel;
    EdImprBar: TJvDBComboEdit;
    PrintSetup: TPBPrinterSetupDialog;
    DBStatusLabel1: TJvDBStatusLabel;
    Label4: TLabel;
    EdCodMapa: TJvDBComboEdit;
    EdDescrMapa: TDBEdit;
    DBCheckBox1: TDBCheckBox;
    EdComputador: TDBEdit;
    Label5: TLabel;
    procedure FormShow(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure sbFechaClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure EdCodImprButtonClick(Sender : TObject);
    procedure NvGruposBeforeAction(Sender : TObject);
    procedure sbTodosClick(Sender : TObject);
    procedure sbDesfazClick(Sender : TObject);
    procedure EdImprBarButtonClick(Sender : TObject);
    procedure EdCodMapaButtonClick(Sender : TObject);
    procedure _PROC_007C856D(Sender : TObject);
    procedure _PROC_007C859C(Sender : TObject);
    procedure _PROC_007C85A4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmImprGrill: TFrmImprGrill;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmImprGrill.FormShow(Sender : TObject);
begin
(*
007C7EA0   55                     push    ebp
007C7EA1   8BEC                   mov     ebp, esp
007C7EA3   53                     push    ebx
007C7EA4   8BD8                   mov     ebx, eax
007C7EA6   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
007C7EA8   E88F5DFEFF             call    007ADC3C
007C7EAD   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7EB2   8B00                   mov     eax, [eax]
007C7EB4   8B8084000000           mov     eax, [eax+$0084]
007C7EBA   895844                 mov     [eax+$44], ebx

* Possible String Reference to: '√ç@'
|
007C7EBD   C740409C7E7C00         mov     dword ptr [eax+$40], $007C7E9C
007C7EC4   5B                     pop     ebx
007C7EC5   5D                     pop     ebp
007C7EC6   C3                     ret

*)
end;

procedure TFrmImprGrill.FormClose(Sender : TObject);
begin
(*
007C7EC8   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7ECD   8B00                   mov     eax, [eax]
007C7ECF   8B8084000000           mov     eax, [eax+$0084]
007C7ED5   33D2                   xor     edx, edx
007C7ED7   895040                 mov     [eax+$40], edx
007C7EDA   895044                 mov     [eax+$44], edx
007C7EDD   C3                     ret

*)
end;

procedure TFrmImprGrill.sbFechaClick(Sender : TObject);
begin
(*
007C7EE0   55                     push    ebp
007C7EE1   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
007C7EE3   E8D8A1CEFF             call    004B20C0
007C7EE8   5D                     pop     ebp
007C7EE9   C3                     ret

*)
end;

procedure TFrmImprGrill.sbAdicionaClick(Sender : TObject);
begin
(*
007C7EEC   55                     push    ebp
007C7EED   8BEC                   mov     ebp, esp
007C7EEF   33C9                   xor     ecx, ecx
007C7EF1   51                     push    ecx
007C7EF2   51                     push    ecx
007C7EF3   51                     push    ecx
007C7EF4   51                     push    ecx
007C7EF5   51                     push    ecx
007C7EF6   51                     push    ecx
007C7EF7   51                     push    ecx
007C7EF8   51                     push    ecx
007C7EF9   53                     push    ebx
007C7EFA   56                     push    esi
007C7EFB   8BD8                   mov     ebx, eax
007C7EFD   33C0                   xor     eax, eax
007C7EFF   55                     push    ebp

* Possible String Reference to: 'ÈíÕ√ˇÎÂ^[ãÂ]√'
|
007C7F00   68A17F7C00             push    $007C7FA1

***** TRY
|
007C7F05   64FF30                 push    dword ptr fs:[eax]
007C7F08   648920                 mov     fs:[eax], esp
007C7F0B   6A00                   push    $00
007C7F0D   8D45F0                 lea     eax, [ebp-$10]
007C7F10   50                     push    eax

* Possible String Reference to: 'CODIMPR'
|
007C7F11   B9B87F7C00             mov     ecx, $007C7FB8

* Possible String Reference to: 'IMPRGRILL'
|
007C7F16   BAC87F7C00             mov     edx, $007C7FC8
007C7F1B   33C0                   xor     eax, eax

|
007C7F1D   E8D226FEFF             call    007AA5F4
007C7F22   8D45F0                 lea     eax, [ebp-$10]
007C7F25   50                     push    eax
007C7F26   8D45E0                 lea     eax, [ebp-$20]
007C7F29   BA01000000             mov     edx, $00000001
007C7F2E   B101                   mov     cl, $01

|
007C7F30   E83B0BC5FF             call    00418A70
007C7F35   8D55E0                 lea     edx, [ebp-$20]
007C7F38   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
007C7F39   E86651C5FF             call    0041D0A4
007C7F3E   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Variants.@VarToInteger(TVarData;TVarData):Integer;
|
007C7F41   E852D3C4FF             call    00415298
007C7F46   8BF0                   mov     esi, eax
007C7F48   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7F4D   8B00                   mov     eax, [eax]
007C7F4F   8B80EC0B0000           mov     eax, [eax+$0BEC]

|
007C7F55   E84AEDFDFF             call    007A6CA4
007C7F5A   84C0                   test    al, al
007C7F5C   7422                   jz      007C7F80
007C7F5E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7F63   8B00                   mov     eax, [eax]
007C7F65   8B80F40B0000           mov     eax, [eax+$0BF4]
007C7F6B   8BD6                   mov     edx, esi
007C7F6D   8B08                   mov     ecx, [eax]
007C7F6F   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TFrmImprGrill.EdCodImpr : TJvDBComboEdit
|
007C7F75   8B8328030000           mov     eax, [ebx+$0328]

|
007C7F7B   E860E1FDFF             call    007A60E0
007C7F80   33C0                   xor     eax, eax
007C7F82   5A                     pop     edx
007C7F83   59                     pop     ecx
007C7F84   59                     pop     ecx
007C7F85   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√'
|
007C7F88   68A87F7C00             push    $007C7FA8
007C7F8D   8D45E0                 lea     eax, [ebp-$20]

* Reference to object Variant
|
007C7F90   8B1524114000           mov     edx, [$00401124]
007C7F96   B902000000             mov     ecx, $00000002

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
007C7F9B   E8FCE0C3FF             call    0040609C
007C7FA0   C3                     ret


* Reference to: System.@HandleFinally;
|
007C7FA1   E992CDC3FF             jmp     00404D38
007C7FA6   EBE5                   jmp     007C7F8D

****** END
|
007C7FA8   5E                     pop     esi
007C7FA9   5B                     pop     ebx
007C7FAA   8BE5                   mov     esp, ebp
007C7FAC   5D                     pop     ebp
007C7FAD   C3                     ret

*)
end;

procedure TFrmImprGrill.sbGravaClick(Sender : TObject);
begin
(*
007C7FD4   55                     push    ebp
007C7FD5   8BEC                   mov     ebp, esp
007C7FD7   6A00                   push    $00
007C7FD9   53                     push    ebx
007C7FDA   8BD8                   mov     ebx, eax
007C7FDC   33C0                   xor     eax, eax
007C7FDE   55                     push    ebp

* Possible String Reference to: 'ÈÈÃ√ˇÎ[Y]√ç@'
|
007C7FDF   684A807C00             push    $007C804A

***** TRY
|
007C7FE4   64FF30                 push    dword ptr fs:[eax]
007C7FE7   648920                 mov     fs:[eax], esp
007C7FEA   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7FEF   8B00                   mov     eax, [eax]
007C7FF1   8B80EC0B0000           mov     eax, [eax+$0BEC]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
007C7FF7   E83C34D2FF             call    004EB438
007C7FFC   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmImprGrill.EdImprBar : TJvDBComboEdit
|
007C7FFF   8B8338030000           mov     eax, [ebx+$0338]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
007C8005   E8325FD3FF             call    004FDF3C
007C800A   8B55FC                 mov     edx, [ebp-$04]
007C800D   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8012   8B00                   mov     eax, [eax]
007C8014   8B80FC0B0000           mov     eax, [eax+$0BFC]
007C801A   8B08                   mov     ecx, [eax]
007C801C   FF91B0000000           call    dword ptr [ecx+$00B0]
007C8022   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8027   8B00                   mov     eax, [eax]
007C8029   8B80EC0B0000           mov     eax, [eax+$0BEC]

|
007C802F   E82CEFFDFF             call    007A6F60
007C8034   33C0                   xor     eax, eax
007C8036   5A                     pop     edx
007C8037   59                     pop     ecx
007C8038   59                     pop     ecx
007C8039   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ç@'
|
007C803C   6851807C00             push    $007C8051
007C8041   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
007C8044   E853D4C3FF             call    0040549C
007C8049   C3                     ret


* Reference to: System.@HandleFinally;
|
007C804A   E9E9CCC3FF             jmp     00404D38
007C804F   EBF0                   jmp     007C8041

****** END
|
007C8051   5B                     pop     ebx
007C8052   59                     pop     ecx
007C8053   5D                     pop     ebp
007C8054   C3                     ret

*)
end;

procedure TFrmImprGrill.sbApagaClick(Sender : TObject);
begin
(*
007C8058   55                     push    ebp
007C8059   8BEC                   mov     ebp, esp
007C805B   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8060   8B00                   mov     eax, [eax]
007C8062   8B80EC0B0000           mov     eax, [eax+$0BEC]
007C8068   B201                   mov     dl, $01

|
007C806A   E8E9F1FDFF             call    007A7258
007C806F   5D                     pop     ebp
007C8070   C3                     ret

*)
end;

procedure TFrmImprGrill.EdCodImprButtonClick(Sender : TObject);
begin
(*
007C8074   55                     push    ebp
007C8075   8BEC                   mov     ebp, esp
007C8077   83C4E4                 add     esp, -$1C
007C807A   33C9                   xor     ecx, ecx
007C807C   894DEC                 mov     [ebp-$14], ecx
007C807F   894DE8                 mov     [ebp-$18], ecx
007C8082   894DE4                 mov     [ebp-$1C], ecx
007C8085   33C0                   xor     eax, eax
007C8087   55                     push    ebp

* Possible String Reference to: 'ÈÈÀ√ˇÎÎãÂ]√'
|
007C8088   684A817C00             push    $007C814A

***** TRY
|
007C808D   64FF30                 push    dword ptr fs:[eax]
007C8090   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'cÛdigo'
|
007C8093   B860817C00             mov     eax, $007C8160
007C8098   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'DescriÁ„o'
|
007C809B   B870817C00             mov     eax, $007C8170
007C80A0   8945FC                 mov     [ebp-$04], eax
007C80A3   8D45F8                 lea     eax, [ebp-$08]
007C80A6   50                     push    eax
007C80A7   6A01                   push    $01
007C80A9   6A00                   push    $00

* Possible String Reference to: 'CodImpr'
|
007C80AB   B884817C00             mov     eax, $007C8184
007C80B0   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Descricao'
|
007C80B3   B894817C00             mov     eax, $007C8194
007C80B8   8945F4                 mov     [ebp-$0C], eax
007C80BB   8D55F0                 lea     edx, [ebp-$10]
007C80BE   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRGRILL'
|
007C80C3   B8A8817C00             mov     eax, $007C81A8

|
007C80C8   E88711E7FF             call    00639254
007C80CD   84C0                   test    al, al
007C80CF   745E                   jz      007C812F
007C80D1   A1689F7D00             mov     eax, dword ptr [$007D9F68]
007C80D6   8B00                   mov     eax, [eax]
007C80D8   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODIMPR'
|
007C80DB   BABC817C00             mov     edx, $007C81BC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007C80E0   E81F1BD2FF             call    004E9C04
007C80E5   8D55E4                 lea     edx, [ebp-$1C]
007C80E8   8B08                   mov     ecx, [eax]
007C80EA   FF5160                 call    dword ptr [ecx+$60]
007C80ED   8B45E4                 mov     eax, [ebp-$1C]
007C80F0   8D55E8                 lea     edx, [ebp-$18]

* Reference to: SysUtils.QuotedStr(AnsiString):AnsiString;
|
007C80F3   E8D027C4FF             call    0040A8C8
007C80F8   8B4DE8                 mov     ecx, [ebp-$18]
007C80FB   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'CODIMPR = '
|
007C80FE   BACC817C00             mov     edx, $007C81CC

* Reference to: System.@LStrCat3;
|
007C8103   E8A0D6C3FF             call    004057A8
007C8108   8B45EC                 mov     eax, [ebp-$14]
007C810B   50                     push    eax

* Possible String Reference to: 'CODIMPR'
|
007C810C   68BC817C00             push    $007C81BC
007C8111   6A01                   push    $01
007C8113   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8118   8B00                   mov     eax, [eax]
007C811A   8B80EC0B0000           mov     eax, [eax+$0BEC]
007C8120   B9E0817C00             mov     ecx, $007C81E0

* Possible String Reference to: 'IMPRGRILL'
|
007C8125   BAA8817C00             mov     edx, $007C81A8

|
007C812A   E839F9FDFF             call    007A7A68
007C812F   33C0                   xor     eax, eax
007C8131   5A                     pop     edx
007C8132   59                     pop     ecx
007C8133   59                     pop     ecx
007C8134   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
007C8137   6851817C00             push    $007C8151
007C813C   8D45E4                 lea     eax, [ebp-$1C]
007C813F   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
007C8144   E877D3C3FF             call    004054C0
007C8149   C3                     ret


* Reference to: System.@HandleFinally;
|
007C814A   E9E9CBC3FF             jmp     00404D38
007C814F   EBEB                   jmp     007C813C

****** END
|
007C8151   8BE5                   mov     esp, ebp
007C8153   5D                     pop     ebp
007C8154   C3                     ret

*)
end;

procedure TFrmImprGrill.NvGruposBeforeAction(Sender : TObject);
begin
(*
007C81E4   55                     push    ebp
007C81E5   8BEC                   mov     ebp, esp
007C81E7   56                     push    esi
007C81E8   8BF0                   mov     esi, eax
007C81EA   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C81EF   8B00                   mov     eax, [eax]
007C81F1   8B80EC0B0000           mov     eax, [eax+$0BEC]
007C81F7   8A809D000000           mov     al, byte ptr [eax+$009D]
007C81FD   04FE                   add     al, -$02
007C81FF   2C02                   sub     al, $02
007C8201   7321                   jnb     007C8224

* Reference to control TFrmImprGrill.sbGrava : TSpeedButton
|
007C8203   8B8600030000           mov     eax, [esi+$0300]
007C8209   8B10                   mov     edx, [eax]

* Reference to method TSpeedButton.GetEnabled()
|
007C820B   FF5250                 call    dword ptr [edx+$50]
007C820E   84C0                   test    al, al
007C8210   7412                   jz      007C8224

* Reference to control TFrmImprGrill.sbGrava : TSpeedButton
|
007C8212   8B8600030000           mov     eax, [esi+$0300]
007C8218   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
007C821C   E87FC5C3FF             call    004047A0
007C8221   5E                     pop     esi
007C8222   5D                     pop     ebp
007C8223   C3                     ret

007C8224   8B8608030000           mov     eax, [esi+$0308]
007C822A   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
007C822E   E86DC5C3FF             call    004047A0
007C8233   5E                     pop     esi
007C8234   5D                     pop     ebp
007C8235   C3                     ret

*)
end;

procedure TFrmImprGrill.sbTodosClick(Sender : TObject);
begin
(*
007C8238   55                     push    ebp
007C8239   8BEC                   mov     ebp, esp
007C823B   33C9                   xor     ecx, ecx
007C823D   51                     push    ecx
007C823E   51                     push    ecx
007C823F   51                     push    ecx
007C8240   51                     push    ecx
007C8241   51                     push    ecx
007C8242   51                     push    ecx
007C8243   33C0                   xor     eax, eax
007C8245   55                     push    ebp

* Possible String Reference to: 'È4 √ˇÎ„ãÂ]√'
|
007C8246   68FF827C00             push    $007C82FF

***** TRY
|
007C824B   64FF30                 push    dword ptr fs:[eax]
007C824E   648920                 mov     fs:[eax], esp
007C8251   8D55FC                 lea     edx, [ebp-$04]
007C8254   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8259   8B00                   mov     eax, [eax]
007C825B   8B80F40B0000           mov     eax, [eax+$0BF4]
007C8261   8B08                   mov     ecx, [eax]
007C8263   FF5160                 call    dword ptr [ecx+$60]
007C8266   6A00                   push    $00

* Possible String Reference to: 'CODIMPR'
|
007C8268   6814837C00             push    $007C8314
007C826D   6A01                   push    $01
007C826F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8274   8B00                   mov     eax, [eax]
007C8276   8B80EC0B0000           mov     eax, [eax+$0BEC]
007C827C   B924837C00             mov     ecx, $007C8324

* Possible String Reference to: 'IMPRGRILL'
|
007C8281   BA30837C00             mov     edx, $007C8330

|
007C8286   E8DDF7FDFF             call    007A7A68
007C828B   84C0                   test    al, al
007C828D   744D                   jz      007C82DC
007C828F   8D55F8                 lea     edx, [ebp-$08]
007C8292   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8297   8B00                   mov     eax, [eax]
007C8299   8B80F40B0000           mov     eax, [eax+$0BF4]
007C829F   8B08                   mov     ecx, [eax]
007C82A1   FF5160                 call    dword ptr [ecx+$60]
007C82A4   8B45F8                 mov     eax, [ebp-$08]
007C82A7   8B55FC                 mov     edx, [ebp-$04]

* Reference to: System.@LStrCmp;
|
007C82AA   E8F9D5C3FF             call    004058A8
007C82AF   742B                   jz      007C82DC
007C82B1   A03C837C00             mov     al, byte ptr [$007C833C]
007C82B6   50                     push    eax
007C82B7   8D45E8                 lea     eax, [ebp-$18]
007C82BA   8B55FC                 mov     edx, [ebp-$04]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
007C82BD   E8020AC5FF             call    00418CC4
007C82C2   8D4DE8                 lea     ecx, [ebp-$18]
007C82C5   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C82CA   8B00                   mov     eax, [eax]
007C82CC   8B80EC0B0000           mov     eax, [eax+$0BEC]

* Possible String Reference to: 'CODIMPR'
|
007C82D2   BA14837C00             mov     edx, $007C8314

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
007C82D7   E81C01FEFF             call    007A83F8
007C82DC   33C0                   xor     eax, eax
007C82DE   5A                     pop     edx
007C82DF   59                     pop     ecx
007C82E0   59                     pop     ecx
007C82E1   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
007C82E4   6806837C00             push    $007C8306
007C82E9   8D45E8                 lea     eax, [ebp-$18]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
007C82EC   E887C2C4FF             call    00414578
007C82F1   8D45F8                 lea     eax, [ebp-$08]
007C82F4   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
007C82F9   E8C2D1C3FF             call    004054C0
007C82FE   C3                     ret


* Reference to: System.@HandleFinally;
|
007C82FF   E934CAC3FF             jmp     00404D38
007C8304   EBE3                   jmp     007C82E9

****** END
|
007C8306   8BE5                   mov     esp, ebp
007C8308   5D                     pop     ebp
007C8309   C3                     ret

*)
end;

procedure TFrmImprGrill.sbDesfazClick(Sender : TObject);
begin
(*
007C8340   55                     push    ebp
007C8341   8BEC                   mov     ebp, esp
007C8343   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8348   8B00                   mov     eax, [eax]
007C834A   8B80EC0B0000           mov     eax, [eax+$0BEC]

|
007C8350   E8DFEFFDFF             call    007A7334
007C8355   5D                     pop     ebp
007C8356   C3                     ret

*)
end;

procedure TFrmImprGrill.EdImprBarButtonClick(Sender : TObject);
begin
(*
007C8358   55                     push    ebp
007C8359   8BEC                   mov     ebp, esp
007C835B   6A00                   push    $00
007C835D   53                     push    ebx
007C835E   8BD8                   mov     ebx, eax
007C8360   33C0                   xor     eax, eax
007C8362   55                     push    ebp

* Possible String Reference to: 'Èˆ»√ˇÎ[Y]√UãÏÉƒÏ3…âMÏ3¿Uh˚Ñ|'
|
007C8363   683D847C00             push    $007C843D

***** TRY
|
007C8368   64FF30                 push    dword ptr fs:[eax]
007C836B   648920                 mov     fs:[eax], esp

* Reference to control TFrmImprGrill.PrintSetup : TPBPrinterSetupDialog
|
007C836E   8B833C030000           mov     eax, [ebx+$033C]
007C8374   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPBPrinterSetupDialog.OFFS_3C
|
007C8376   FF523C                 call    dword ptr [edx+$3C]
007C8379   84C0                   test    al, al
007C837B   0F84A6000000           jz      007C8427
007C8381   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8386   8B00                   mov     eax, [eax]
007C8388   8B80200C0000           mov     eax, [eax+$0C20]

* Reference to : TFrmInfoAtu._PROC_007A66A4()
|
007C838E   E811E3FDFF             call    007A66A4
007C8393   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8398   8B00                   mov     eax, [eax]
007C839A   8B80200C0000           mov     eax, [eax+$0C20]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
007C83A0   E89330D2FF             call    004EB438
007C83A5   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C83AA   8B00                   mov     eax, [eax]
007C83AC   8B80F40B0000           mov     eax, [eax+$0BF4]
007C83B2   8B10                   mov     edx, [eax]
007C83B4   FF5258                 call    dword ptr [edx+$58]
007C83B7   8BD0                   mov     edx, eax
007C83B9   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C83BE   8B00                   mov     eax, [eax]
007C83C0   8B80280C0000           mov     eax, [eax+$0C28]
007C83C6   8B08                   mov     ecx, [eax]
007C83C8   FF91A8000000           call    dword ptr [ecx+$00A8]
007C83CE   8D45FC                 lea     eax, [ebp-$04]

* Reference to : TFrmInfoAtu._PROC_007A3864()
|
007C83D1   E88EB4FDFF             call    007A3864
007C83D6   8B55FC                 mov     edx, [ebp-$04]
007C83D9   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C83DE   8B00                   mov     eax, [eax]
007C83E0   8B802C0C0000           mov     eax, [eax+$0C2C]
007C83E6   8B08                   mov     ecx, [eax]
007C83E8   FF91B0000000           call    dword ptr [ecx+$00B0]

* Reference to control TFrmImprGrill.PrintSetup : TPBPrinterSetupDialog
|
007C83EE   8B833C030000           mov     eax, [ebx+$033C]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
007C83F4   8B8010030000           mov     eax, [eax+$0310]
007C83FA   8B5034                 mov     edx, [eax+$34]
007C83FD   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8402   8B00                   mov     eax, [eax]
007C8404   8B80300C0000           mov     eax, [eax+$0C30]
007C840A   8B08                   mov     ecx, [eax]
007C840C   FF91B0000000           call    dword ptr [ecx+$00B0]
007C8412   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C8417   8B00                   mov     eax, [eax]
007C8419   8B80200C0000           mov     eax, [eax+$0C20]
007C841F   8B10                   mov     edx, [eax]
007C8421   FF924C020000           call    dword ptr [edx+$024C]
007C8427   33C0                   xor     eax, eax
007C8429   5A                     pop     edx
007C842A   59                     pop     ecx
007C842B   59                     pop     ecx
007C842C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√UãÏÉƒÏ3…âMÏ3¿Uh˚Ñ|'
|
007C842F   6844847C00             push    $007C8444
007C8434   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
007C8437   E860D0C3FF             call    0040549C
007C843C   C3                     ret


* Reference to: System.@HandleFinally;
|
007C843D   E9F6C8C3FF             jmp     00404D38
007C8442   EBF0                   jmp     007C8434

****** END
|
007C8444   5B                     pop     ebx
007C8445   59                     pop     ecx
007C8446   5D                     pop     ebp
007C8447   C3                     ret

*)
end;

procedure TFrmImprGrill.EdCodMapaButtonClick(Sender : TObject);
begin
(*
007C8448   55                     push    ebp
007C8449   8BEC                   mov     ebp, esp
007C844B   83C4EC                 add     esp, -$14
007C844E   33C9                   xor     ecx, ecx
007C8450   894DEC                 mov     [ebp-$14], ecx
007C8453   33C0                   xor     eax, eax
007C8455   55                     push    ebp

* Possible String Reference to: 'È8»√ˇÎãÂ]√'
|
007C8456   68FB847C00             push    $007C84FB

***** TRY
|
007C845B   64FF30                 push    dword ptr fs:[eax]
007C845E   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'cÛdigo'
|
007C8461   B810857C00             mov     eax, $007C8510
007C8466   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Impressora'
|
007C8469   B820857C00             mov     eax, $007C8520
007C846E   8945FC                 mov     [ebp-$04], eax
007C8471   8D45F8                 lea     eax, [ebp-$08]
007C8474   50                     push    eax
007C8475   6A01                   push    $01
007C8477   6A00                   push    $00

* Possible String Reference to: 'CodImpressora'
|
007C8479   B834857C00             mov     eax, $007C8534
007C847E   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Impressora'
|
007C8481   B820857C00             mov     eax, $007C8520
007C8486   8945F4                 mov     [ebp-$0C], eax
007C8489   8D55F0                 lea     edx, [ebp-$10]
007C848C   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRESS'
|
007C8491   B84C857C00             mov     eax, $007C854C

|
007C8496   E8B90DE7FF             call    00639254
007C849B   84C0                   test    al, al
007C849D   7446                   jz      007C84E5
007C849F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C84A4   8B00                   mov     eax, [eax]
007C84A6   8B80EC0B0000           mov     eax, [eax+$0BEC]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
007C84AC   E8872FD2FF             call    004EB438
007C84B1   A1689F7D00             mov     eax, dword ptr [$007D9F68]
007C84B6   8B00                   mov     eax, [eax]
007C84B8   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODIMPRESSORA'
|
007C84BB   BA5C857C00             mov     edx, $007C855C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007C84C0   E83F17D2FF             call    004E9C04
007C84C5   8D55EC                 lea     edx, [ebp-$14]
007C84C8   8B08                   mov     ecx, [eax]
007C84CA   FF5160                 call    dword ptr [ecx+$60]
007C84CD   8B55EC                 mov     edx, [ebp-$14]
007C84D0   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C84D5   8B00                   mov     eax, [eax]
007C84D7   8B80080C0000           mov     eax, [eax+$0C08]
007C84DD   8B08                   mov     ecx, [eax]
007C84DF   FF91B0000000           call    dword ptr [ecx+$00B0]
007C84E5   33C0                   xor     eax, eax
007C84E7   5A                     pop     edx
007C84E8   59                     pop     ecx
007C84E9   59                     pop     ecx
007C84EA   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
007C84ED   6802857C00             push    $007C8502
007C84F2   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
007C84F5   E8A2CFC3FF             call    0040549C
007C84FA   C3                     ret


* Reference to: System.@HandleFinally;
|
007C84FB   E938C8C3FF             jmp     00404D38
007C8500   EBF0                   jmp     007C84F2

****** END
|
007C8502   8BE5                   mov     esp, ebp
007C8504   5D                     pop     ebp
007C8505   C3                     ret

*)
end;

procedure TFrmImprGrill._PROC_007C856D(Sender : TObject);
begin
(*
007C856D   8BEC                   mov     ebp, esp
007C856F   33C0                   xor     eax, eax
007C8571   55                     push    ebp

* Possible String Reference to: 'È¢«√ˇÎ¯]√ã¿É-Ãı}'
|
007C8572   6891857C00             push    $007C8591

***** TRY
|
007C8577   64FF30                 push    dword ptr fs:[eax]
007C857A   648920                 mov     fs:[eax], esp
007C857D   FF05CCF57D00           inc     dword ptr [$007DF5CC]
007C8583   33C0                   xor     eax, eax
007C8585   5A                     pop     edx
007C8586   59                     pop     ecx
007C8587   59                     pop     ecx
007C8588   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-Ãı}'
|
007C858B   6898857C00             push    $007C8598
007C8590   C3                     ret


* Reference to: System.@HandleFinally;
|
007C8591   E9A2C7C3FF             jmp     00404D38
007C8596   EBF8                   jmp     007C8590

****** END
|
007C8598   5D                     pop     ebp
007C8599   C3                     ret

*)
end;

procedure TFrmImprGrill._PROC_007C859C(Sender : TObject);
begin
(*
007C859C   832DCCF57D0001         sub     dword ptr [$007DF5CC], +$01
007C85A3   C3                     ret

*)
end;

procedure TFrmImprGrill._PROC_007C85A4(Sender : TObject);
begin
(*
007C85A4   F0                     lock
007C85A5   857C0000               test    [eax+eax+$00], edi
007C85A9   0000                   add     [eax], al

*)
end;

end.