unit Impress;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DBCtrls, Mask, JvExMask, JvToolEdit,
  JvDBControls, ExtCtrls, Buttons, JvExControls, JvComponent, JvLabel;
type
  TFrmImpressoras=class(TForm)
    Panel1: TPanel;
    DBStatusLabel1: TJvDBStatusLabel;
    DBNavigator1: TDBNavigator;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbDesfaz: TSpeedButton;
    sbFecha: TSpeedButton;
    DBText1: TDBText;
    sbImprime: TSpeedButton;
    Label1: TLabel;
    Label2: TLabel;
    EdCodigo: TJvDBComboEdit;
    EdModelo: TDBEdit;
    Label3: TLabel;
    Label4: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    EdFonte10cpp: TDBEdit;
    EdFonte12cpp: TDBEdit;
    EdCourier: TDBEdit;
    EdRoman: TDBEdit;
    EdComprimido: TDBEdit;
    EdParaComprimido: TDBEdit;
    EdExpandido: TDBEdit;
    EdParaExpandido: TDBEdit;
    EdItalico: TDBEdit;
    EdParaItalico: TDBEdit;
    Label8: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    Label12: TLabel;
    Label13: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    EdSublinhado: TDBEdit;
    EdParaSublinhado: TDBEdit;
    EdIndice: TDBEdit;
    EdParaIndice: TDBEdit;
    EdExpoente: TDBEdit;
    EdParaExpoente: TDBEdit;
    Bevel1: TBevel;
    Bevel2: TBevel;
    EdParaRoman: TDBEdit;
    Bevel3: TBevel;
    Label16: TLabel;
    EdInicializa: TDBEdit;
    Label17: TLabel;
    EdEjeta: TDBEdit;
    sbReplicar: TSpeedButton;
    EdFonte17Cpp: TDBEdit;
    Label5: TLabel;
    procedure sbFechaClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure sbDesfazClick(Sender : TObject);
    procedure EdCodigoButtonClick(Sender : TObject);
    procedure sbReplicarClick(Sender : TObject);
    procedure DBNavigator1BeforeAction(Sender : TObject);
    procedure _PROC_007C7A34(Sender : TObject);
    procedure _PROC_007C7A64(Sender : TObject);
    procedure _PROC_007C7A6C(Sender : TObject);
    procedure _PROC_007C7DF2(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmImpressoras: TFrmImpressoras;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmImpressoras.sbFechaClick(Sender : TObject);
begin
(*
007C7744   55                     push    ebp
007C7745   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
007C7747   E874A9CEFF             call    004B20C0
007C774C   5D                     pop     ebp
007C774D   C3                     ret

*)
end;

procedure TFrmImpressoras.FormShow(Sender : TObject);
begin
(*
007C7750   55                     push    ebp
007C7751   8BEC                   mov     ebp, esp

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
007C7753   E8E464FEFF             call    007ADC3C
007C7758   5D                     pop     ebp
007C7759   C3                     ret

*)
end;

procedure TFrmImpressoras.sbAdicionaClick(Sender : TObject);
begin
(*
007C775C   55                     push    ebp
007C775D   8BEC                   mov     ebp, esp
007C775F   53                     push    ebx
007C7760   56                     push    esi
007C7761   8BF0                   mov     esi, eax
007C7763   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C7768   8B00                   mov     eax, [eax]
007C776A   8B8034010000           mov     eax, [eax+$0134]

* Reference to: DB.TDataSet.Last(TDataSet);
|
007C7770   E88F39D2FF             call    004EB104
007C7775   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C777A   8B00                   mov     eax, [eax]
007C777C   8B8034010000           mov     eax, [eax+$0134]

* Possible String Reference to: 'CodImpressora'
|
007C7782   BAE8777C00             mov     edx, $007C77E8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007C7787   E87824D2FF             call    004E9C04
007C778C   8B10                   mov     edx, [eax]
007C778E   FF5258                 call    dword ptr [edx+$58]
007C7791   8BD8                   mov     ebx, eax
007C7793   43                     inc     ebx
007C7794   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C7799   8B00                   mov     eax, [eax]
007C779B   8B8034010000           mov     eax, [eax+$0134]

|
007C77A1   E8FEF4FDFF             call    007A6CA4
007C77A6   84C0                   test    al, al
007C77A8   742F                   jz      007C77D9
007C77AA   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C77AF   8B00                   mov     eax, [eax]
007C77B1   8B8034010000           mov     eax, [eax+$0134]

* Possible String Reference to: 'CodImpressora'
|
007C77B7   BAE8777C00             mov     edx, $007C77E8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007C77BC   E84324D2FF             call    004E9C04
007C77C1   8BD3                   mov     edx, ebx
007C77C3   8B08                   mov     ecx, [eax]
007C77C5   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TFrmImpressoras.EdModelo : TDBEdit
|
007C77CB   8B862C030000           mov     eax, [esi+$032C]
007C77D1   8B10                   mov     edx, [eax]

* Reference to method TDBEdit.SetFocus()
|
007C77D3   FF92C4000000           call    dword ptr [edx+$00C4]
007C77D9   5E                     pop     esi
007C77DA   5B                     pop     ebx
007C77DB   5D                     pop     ebp
007C77DC   C3                     ret

*)
end;

procedure TFrmImpressoras.sbGravaClick(Sender : TObject);
begin
(*
007C77F8   55                     push    ebp
007C77F9   8BEC                   mov     ebp, esp
007C77FB   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C7800   8B00                   mov     eax, [eax]
007C7802   8B8034010000           mov     eax, [eax+$0134]

|
007C7808   E853F7FDFF             call    007A6F60
007C780D   5D                     pop     ebp
007C780E   C3                     ret

*)
end;

procedure TFrmImpressoras.sbApagaClick(Sender : TObject);
begin
(*
007C7810   55                     push    ebp
007C7811   8BEC                   mov     ebp, esp
007C7813   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C7818   8B00                   mov     eax, [eax]
007C781A   8B8034010000           mov     eax, [eax+$0134]
007C7820   B201                   mov     dl, $01

|
007C7822   E831FAFDFF             call    007A7258
007C7827   5D                     pop     ebp
007C7828   C3                     ret

*)
end;

procedure TFrmImpressoras.sbDesfazClick(Sender : TObject);
begin
(*
007C782C   55                     push    ebp
007C782D   8BEC                   mov     ebp, esp
007C782F   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C7834   8B00                   mov     eax, [eax]
007C7836   8B8034010000           mov     eax, [eax+$0134]

|
007C783C   E8F3FAFDFF             call    007A7334
007C7841   5D                     pop     ebp
007C7842   C3                     ret

*)
end;

procedure TFrmImpressoras.EdCodigoButtonClick(Sender : TObject);
begin
(*
007C7844   55                     push    ebp
007C7845   8BEC                   mov     ebp, esp
007C7847   83C4E4                 add     esp, -$1C
007C784A   33C9                   xor     ecx, ecx
007C784C   894DEC                 mov     [ebp-$14], ecx
007C784F   894DE8                 mov     [ebp-$18], ecx
007C7852   894DE4                 mov     [ebp-$1C], ecx
007C7855   33C0                   xor     eax, eax
007C7857   55                     push    ebp
007C7858   681A797C00             push    $007C791A

***** TRY
|
007C785D   64FF30                 push    dword ptr fs:[eax]
007C7860   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'CÛdigo'
|
007C7863   B830797C00             mov     eax, $007C7930
007C7868   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Impressora'
|
007C786B   B840797C00             mov     eax, $007C7940
007C7870   8945FC                 mov     [ebp-$04], eax
007C7873   8D45F8                 lea     eax, [ebp-$08]
007C7876   50                     push    eax
007C7877   6A01                   push    $01
007C7879   6A00                   push    $00

* Possible String Reference to: 'CodImpressora'
|
007C787B   B854797C00             mov     eax, $007C7954
007C7880   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Impressora'
|
007C7883   B840797C00             mov     eax, $007C7940
007C7888   8945F4                 mov     [ebp-$0C], eax
007C788B   8D55F0                 lea     edx, [ebp-$10]
007C788E   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRESS'
|
007C7893   B86C797C00             mov     eax, $007C796C

|
007C7898   E8B719E7FF             call    00639254
007C789D   84C0                   test    al, al
007C789F   745E                   jz      007C78FF
007C78A1   A1689F7D00             mov     eax, dword ptr [$007D9F68]
007C78A6   8B00                   mov     eax, [eax]
007C78A8   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODIMPRESSORA'
|
007C78AB   BA7C797C00             mov     edx, $007C797C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
007C78B0   E84F23D2FF             call    004E9C04
007C78B5   8D55E4                 lea     edx, [ebp-$1C]
007C78B8   8B08                   mov     ecx, [eax]
007C78BA   FF5160                 call    dword ptr [ecx+$60]
007C78BD   8B45E4                 mov     eax, [ebp-$1C]
007C78C0   8D55E8                 lea     edx, [ebp-$18]

* Reference to : TFrmInfoAtu._PROC_007A3B20()
|
007C78C3   E858C2FDFF             call    007A3B20
007C78C8   8B4DE8                 mov     ecx, [ebp-$18]
007C78CB   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'CODIMPRESSORA = '
|
007C78CE   BA94797C00             mov     edx, $007C7994

* Reference to: System.@LStrCat3;
|
007C78D3   E8D0DEC3FF             call    004057A8
007C78D8   8B45EC                 mov     eax, [ebp-$14]
007C78DB   50                     push    eax

* Possible String Reference to: 'CODIMPRESSORA'
|
007C78DC   687C797C00             push    $007C797C
007C78E1   6A01                   push    $01
007C78E3   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C78E8   8B00                   mov     eax, [eax]
007C78EA   8B8034010000           mov     eax, [eax+$0134]
007C78F0   B9B0797C00             mov     ecx, $007C79B0

* Possible String Reference to: 'IMPRESS'
|
007C78F5   BA6C797C00             mov     edx, $007C796C

|
007C78FA   E86901FEFF             call    007A7A68
007C78FF   33C0                   xor     eax, eax
007C7901   5A                     pop     edx
007C7902   59                     pop     ecx
007C7903   59                     pop     ecx
007C7904   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
007C7907   6821797C00             push    $007C7921
007C790C   8D45E4                 lea     eax, [ebp-$1C]
007C790F   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
007C7914   E8A7DBC3FF             call    004054C0
007C7919   C3                     ret


* Reference to: System.@HandleFinally;
|
007C791A   E919D4C3FF             jmp     00404D38
007C791F   EBEB                   jmp     007C790C

****** END
|
007C7921   8BE5                   mov     esp, ebp
007C7923   5D                     pop     ebp
007C7924   C3                     ret

*)
end;

procedure TFrmImpressoras.sbReplicarClick(Sender : TObject);
begin
(*
007C79B4   55                     push    ebp
007C79B5   8BEC                   mov     ebp, esp

* Possible String Reference to: 'Em desenvolvimento!'
|
007C79B7   B8CC797C00             mov     eax, $007C79CC

* Reference to: Dialogs.ShowMessage(AnsiString);
|
007C79BC   E863C2C7FF             call    00443C24
007C79C1   5D                     pop     ebp
007C79C2   C3                     ret

*)
end;

procedure TFrmImpressoras.DBNavigator1BeforeAction(Sender : TObject);
begin
(*
007C79E0   55                     push    ebp
007C79E1   8BEC                   mov     ebp, esp
007C79E3   56                     push    esi
007C79E4   8BF0                   mov     esi, eax
007C79E6   A1B0AA7D00             mov     eax, dword ptr [$007DAAB0]
007C79EB   8B00                   mov     eax, [eax]
007C79ED   8B8034010000           mov     eax, [eax+$0134]
007C79F3   8A809D000000           mov     al, byte ptr [eax+$009D]
007C79F9   04FE                   add     al, -$02
007C79FB   2C02                   sub     al, $02
007C79FD   7321                   jnb     007C7A20

* Reference to control TFrmImpressoras.sbGrava : TSpeedButton
|
007C79FF   8B8608030000           mov     eax, [esi+$0308]
007C7A05   8B10                   mov     edx, [eax]

* Reference to method TSpeedButton.GetEnabled()
|
007C7A07   FF5250                 call    dword ptr [edx+$50]
007C7A0A   84C0                   test    al, al
007C7A0C   7412                   jz      007C7A20

* Reference to control TFrmImpressoras.sbGrava : TSpeedButton
|
007C7A0E   8B8608030000           mov     eax, [esi+$0308]
007C7A14   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
007C7A18   E883CDC3FF             call    004047A0
007C7A1D   5E                     pop     esi
007C7A1E   5D                     pop     ebp
007C7A1F   C3                     ret

007C7A20   8B8610030000           mov     eax, [esi+$0310]
007C7A26   66BEEBFF               mov     si, $FFEB

* Reference to: System.@CallDynaInst;
|
007C7A2A   E871CDC3FF             call    004047A0
007C7A2F   5E                     pop     esi
007C7A30   5D                     pop     ebp
007C7A31   C3                     ret

*)
end;

procedure TFrmImpressoras._PROC_007C7A34(Sender : TObject);
begin
(*
007C7A34   55                     push    ebp
007C7A35   8BEC                   mov     ebp, esp
007C7A37   33C0                   xor     eax, eax
007C7A39   55                     push    ebp

* Possible String Reference to: 'È⁄“√ˇÎ¯]√ã¿É-ƒı}'
|
007C7A3A   68597A7C00             push    $007C7A59

***** TRY
|
007C7A3F   64FF30                 push    dword ptr fs:[eax]
007C7A42   648920                 mov     fs:[eax], esp
007C7A45   FF05C4F57D00           inc     dword ptr [$007DF5C4]
007C7A4B   33C0                   xor     eax, eax
007C7A4D   5A                     pop     edx
007C7A4E   59                     pop     ecx
007C7A4F   59                     pop     ecx
007C7A50   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-ƒı}'
|
007C7A53   68607A7C00             push    $007C7A60
007C7A58   C3                     ret


* Reference to: System.@HandleFinally;
|
007C7A59   E9DAD2C3FF             jmp     00404D38
007C7A5E   EBF8                   jmp     007C7A58

****** END
|
007C7A60   5D                     pop     ebp
007C7A61   C3                     ret

*)
end;

procedure TFrmImpressoras._PROC_007C7A64(Sender : TObject);
begin
(*
007C7A64   832DC4F57D0001         sub     dword ptr [$007DF5C4], +$01
007C7A6B   C3                     ret

*)
end;

procedure TFrmImpressoras._PROC_007C7A6C(Sender : TObject);
begin
(*
007C7A6C   B87A7C0000             mov     eax, $00007C7A
007C7A71   0000                   add     [eax], al

*)
end;

procedure TFrmImpressoras._PROC_007C7DF2(Sender : TObject);
begin
(*
007C7DF2   7C00                   jl      007C7DF4
007C7DF4   0D73624465             or      eax, $65446273
007C7DF9   7366                   jnb     007C7E61
007C7DFB   61                     popa
007C7DFC   7A43                   jp      007C7E41
007C7DFE   6C                     insb
007C7DFF   69636B1B005883         imul    esp, [ebx+$6B], $8358001B
007C7E06   7C00                   jl      007C7E08
007C7E08   1445                   adc     al, $45
007C7E0A   6449                   dec     ecx
007C7E0C   6D                     insd
007C7E0D   7072                   jo      007C7E81
007C7E0F   42                     inc     edx
007C7E10   61                     popa
007C7E11   7242                   jb      007C7E55
007C7E13   7574                   jnz     007C7E89
007C7E15   746F                   jz      007C7E86
007C7E17   6E                     outsb
007C7E18   43                     inc     ebx
007C7E19   6C                     insb
007C7E1A   69636B1B004884         imul    esp, [ebx+$6B], $8448001B
007C7E21   7C00                   jl      007C7E23
007C7E23   1445                   adc     al, $45
007C7E25   6443                   inc     ebx
007C7E27   6F                     outsd
007C7E28   644D                   dec     ebp
007C7E2A   61                     popa
007C7E2B   7061                   jo      007C7E8E
007C7E2D   42                     inc     edx
007C7E2E   7574                   jnz     007C7EA4
007C7E30   746F                   jz      007C7EA1
007C7E32   6E                     outsb
007C7E33   43                     inc     ebx
007C7E34   6C                     insb
007C7E35   69636B0D544672         imul    esp, [ebx+$6B], $7246540D
007C7E3C   6D                     insd
007C7E3D   49                     dec     ecx
007C7E3E   6D                     insd
007C7E3F   7072                   jo      007C7EB3
007C7E41   47                     inc     edi
007C7E42   7269                   jb      007C7EAD
007C7E44   6C                     insb
007C7E45   6C                     insb
007C7E46   0B00                   or      eax, [eax]
007C7E48   885644                 mov     [esi+$44], dl
007C7E4B   00A8C94400A8           add     [eax+$A80044C9], ch
007C7E51   BD500004F4             mov     ebp, $F4040050
007C7E56   47                     inc     edi
007C7E57   004CB450               add     [esp+esi*4+$50], cl
007C7E5B   00DC                   add     ah, bl
007C7E5D   51                     push    ecx
007C7E5E   44                     inc     esp
007C7E5F   00C8                   add     al, cl
007C7E61   16                     push    ss
007C7E62   61                     popa
007C7E63   00C4                   add     ah, al
007C7E65   F8                     clc
007C7E66   50                     push    eax
007C7E67   0038                   add     [eax], bh
007C7E69   226700                 and     ah, byte ptr [edi+$00]
007C7E6C   3423                   xor     al, $23
007C7E6E   61                     popa
007C7E6F   00C4                   add     ah, al
007C7E71   C3                     ret

007C7E72   50                     push    eax
007C7E73   00787E                 add     [eax+$7E], bh
007C7E76   7C00                   jl      007C7E78
007C7E78   07                     pop     es
007C7E79   0D5446726D             or      eax, $6D724654
007C7E7E   49                     dec     ecx
007C7E7F   6D                     insd
007C7E80   7072                   jo      007C7EF4
007C7E82   47                     inc     edi
007C7E83   7269                   jb      007C7EEE
007C7E85   6C                     insb
007C7E86   6C                     insb
007C7E87   B87A7C0038             mov     eax, $38007C7A
007C7E8C   B44A                   mov     ah, $4A
007C7E8E   005E00                 add     [esi+$00], bl
007C7E91   08496D                 or      [ecx+$6D], cl
007C7E94   7047                   jo      007C7EDD
007C7E96   7269                   jb      007C7F01
007C7E98   6C                     insb
007C7E99   6C                     insb
007C7E9A   0000                   add     [eax], al

007C7E9C   C3                     ret

007C7E9D   8D4000                 lea     eax, [eax+$00]
007C7EA0   55                     push    ebp
007C7EA1   8BEC                   mov     ebp, esp
007C7EA3   53                     push    ebx
007C7EA4   8BD8                   mov     ebx, eax
007C7EA6   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
007C7EA8   E88F5DFEFF             call    007ADC3C
007C7EAD   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7EB2   8B00                   mov     eax, [eax]
007C7EB4   8B8084000000           mov     eax, [eax+$0084]
007C7EBA   895844                 mov     [eax+$44], ebx

* Possible String Reference to: '√ç@'
|
007C7EBD   C740409C7E7C00         mov     dword ptr [eax+$40], $007C7E9C
007C7EC4   5B                     pop     ebx
007C7EC5   5D                     pop     ebp
007C7EC6   C3                     ret

007C7EC7   90                     nop
007C7EC8   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7ECD   8B00                   mov     eax, [eax]
007C7ECF   8B8084000000           mov     eax, [eax+$0084]
007C7ED5   33D2                   xor     edx, edx
007C7ED7   895040                 mov     [eax+$40], edx
007C7EDA   895044                 mov     [eax+$44], edx
007C7EDD   C3                     ret

007C7EDE   8BC0                   mov     eax, eax
007C7EE0   55                     push    ebp
007C7EE1   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
007C7EE3   E8D8A1CEFF             call    004B20C0
007C7EE8   5D                     pop     ebp
007C7EE9   C3                     ret

007C7EEA   8BC0                   mov     eax, eax
007C7EEC   55                     push    ebp
007C7EED   8BEC                   mov     ebp, esp
007C7EEF   33C9                   xor     ecx, ecx
007C7EF1   51                     push    ecx
007C7EF2   51                     push    ecx
007C7EF3   51                     push    ecx
007C7EF4   51                     push    ecx
007C7EF5   51                     push    ecx
007C7EF6   51                     push    ecx
007C7EF7   51                     push    ecx
007C7EF8   51                     push    ecx
007C7EF9   53                     push    ebx
007C7EFA   56                     push    esi
007C7EFB   8BD8                   mov     ebx, eax
007C7EFD   33C0                   xor     eax, eax
007C7EFF   55                     push    ebp

* Possible String Reference to: 'ÈíÕ√ˇÎÂ^[ãÂ]√'
|
007C7F00   68A17F7C00             push    $007C7FA1

***** TRY
|
007C7F05   64FF30                 push    dword ptr fs:[eax]
007C7F08   648920                 mov     fs:[eax], esp
007C7F0B   6A00                   push    $00
007C7F0D   8D45F0                 lea     eax, [ebp-$10]
007C7F10   50                     push    eax

* Possible String Reference to: 'CODIMPR'
|
007C7F11   B9B87F7C00             mov     ecx, $007C7FB8

* Possible String Reference to: 'IMPRGRILL'
|
007C7F16   BAC87F7C00             mov     edx, $007C7FC8
007C7F1B   33C0                   xor     eax, eax

|
007C7F1D   E8D226FEFF             call    007AA5F4
007C7F22   8D45F0                 lea     eax, [ebp-$10]
007C7F25   50                     push    eax
007C7F26   8D45E0                 lea     eax, [ebp-$20]
007C7F29   BA01000000             mov     edx, $00000001
007C7F2E   B101                   mov     cl, $01

|
007C7F30   E83B0BC5FF             call    00418A70
007C7F35   8D55E0                 lea     edx, [ebp-$20]
007C7F38   58                     pop     eax

* Reference to: System.@Initialize(Pointer;Pointer);
|
007C7F39   E86651C5FF             call    0041D0A4
007C7F3E   8D45F0                 lea     eax, [ebp-$10]

* Reference to: Variants.@VarToInteger(TVarData;TVarData):Integer;
|
007C7F41   E852D3C4FF             call    00415298
007C7F46   8BF0                   mov     esi, eax
007C7F48   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7F4D   8B00                   mov     eax, [eax]
007C7F4F   8B80EC0B0000           mov     eax, [eax+$0BEC]

|
007C7F55   E84AEDFDFF             call    007A6CA4
007C7F5A   84C0                   test    al, al
007C7F5C   7422                   jz      007C7F80
007C7F5E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
007C7F63   8B00                   mov     eax, [eax]
007C7F65   8B80F40B0000           mov     eax, [eax+$0BF4]
007C7F6B   8BD6                   mov     edx, esi
007C7F6D   8B08                   mov     ecx, [eax]
007C7F6F   FF91A8000000           call    dword ptr [ecx+$00A8]
007C7F75   8B8328030000           mov     eax, [ebx+$0328]

|
007C7F7B   E860E1FDFF             call    007A60E0
007C7F80   33C0                   xor     eax, eax
007C7F82   5A                     pop     edx
007C7F83   59                     pop     ecx
007C7F84   59                     pop     ecx
007C7F85   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[ãÂ]√'
|
007C7F88   68A87F7C00             push    $007C7FA8
007C7F8D   8D45E0                 lea     eax, [ebp-$20]

* Reference to object Variant
|
007C7F90   8B1524114000           mov     edx, [$00401124]
007C7F96   B902000000             mov     ecx, $00000002

* Reference to: System.@FinalizeArray(Pointer;Pointer;Cardinal);
|
007C7F9B   E8FCE0C3FF             call    0040609C
007C7FA0   C3                     ret

*)
end;

end.