unit MemFisc;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ExtCtrls, Buttons;
  
type
  TFrmLeituraMemoriaFiscal=class(TForm)
    Panel1: TPanel;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    pnData: TPanel;
    Label2: TLabel;
    Label3: TLabel;
    bmMeDataFim: TMaskEdit;
    bmMeDataIni: TMaskEdit;
    EdReduIni: TEdit;
    EdReduFim: TEdit;
    Label5: TLabel;
    Label4: TLabel;
    RgTipo: TRadioGroup;
    ckResumida: TCheckBox;
    Bevel1: TBevel;
    procedure RgTipoClick(Sender : TObject);
    procedure _PROC_00675874(Sender : TObject);
    procedure _PROC_006758A4(Sender : TObject);
    procedure _PROC_006758AC(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmLeituraMemoriaFiscal: TFrmLeituraMemoriaFiscal;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmLeituraMemoriaFiscal.RgTipoClick(Sender : TObject);
begin
(*
00675804   55                     push    ebp
00675805   8BEC                   mov     ebp, esp
00675807   53                     push    ebx
00675808   8BD8                   mov     ebx, eax

* Reference to control TFrmLeituraMemoriaFiscal.RgTipo : TRadioGroup
|
0067580A   8B8328030000           mov     eax, [ebx+$0328]

* Reference to field TRadioGroup.ItemIndex : Integer
|
00675810   8B8018020000           mov     eax, [eax+$0218]
00675816   83E801                 sub     eax, +$01
00675819   7204                   jb      0067581F
0067581B   742C                   jz      00675849
0067581D   EB51                   jmp     00675870
0067581F   B201                   mov     dl, $01

* Reference to control TFrmLeituraMemoriaFiscal.pnData : TPanel
|
00675821   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00675827   E8C0DDE1FF             call    004935EC
0067582C   33D2                   xor     edx, edx

* Reference to control TFrmLeituraMemoriaFiscal.EdReduIni : TEdit
|
0067582E   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00675834   E8C3DEE1FF             call    004936FC
00675839   33D2                   xor     edx, edx

* Reference to control TFrmLeituraMemoriaFiscal.EdReduFim : TEdit
|
0067583B   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00675841   E8B6DEE1FF             call    004936FC
00675846   5B                     pop     ebx
00675847   5D                     pop     ebp
00675848   C3                     ret

00675849   33D2                   xor     edx, edx
0067584B   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00675851   E896DDE1FF             call    004935EC
00675856   33D2                   xor     edx, edx
00675858   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0067585E   E86D87E8FF             call    004FDFD0
00675863   33D2                   xor     edx, edx
00675865   8B8310030000           mov     eax, [ebx+$0310]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
0067586B   E86087E8FF             call    004FDFD0
00675870   5B                     pop     ebx
00675871   5D                     pop     ebp
00675872   C3                     ret

*)
end;

procedure TFrmLeituraMemoriaFiscal._PROC_00675874(Sender : TObject);
begin
(*
00675874   55                     push    ebp
00675875   8BEC                   mov     ebp, esp
00675877   33C0                   xor     eax, eax
00675879   55                     push    ebp

* Possible String Reference to: 'éšôØÿëø]Ã‹Àƒ-˜é}'
|
0067587A   6899586700             push    $00675899

***** TRY
|
0067587F   64FF30                 push    dword ptr fs:[eax]
00675882   648920                 mov     fs:[eax], esp
00675885   FF0598E97D00           inc     dword ptr [$007DE998]
0067588B   33C0                   xor     eax, eax
0067588D   5A                     pop     edx
0067588E   59                     pop     ecx
0067588F   59                     pop     ecx
00675890   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-˜é}'
|
00675893   68A0586700             push    $006758A0
00675898   C3                     ret


* Reference to: System.@HandleFinally;
|
00675899   E99AF4D8FF             jmp     00404D38
0067589E   EBF8                   jmp     00675898

****** END
|
006758A0   5D                     pop     ebp
006758A1   C3                     ret

*)
end;

procedure TFrmLeituraMemoriaFiscal._PROC_006758A4(Sender : TObject);
begin
(*
006758A4   832D98E97D0001         sub     dword ptr [$007DE998], +$01
006758AB   C3                     ret

*)
end;

procedure TFrmLeituraMemoriaFiscal._PROC_006758AC(Sender : TObject);
begin
(*
006758AC   F8                     clc
006758AD   58                     pop     eax
006758AE   670000                 add     [bx+si], al
006758B1   0000                   add     [eax], al

*)
end;

end.