unit Mens;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, LMDBaseControl,
  LMDBaseGraphicControl, LMDBaseLabel, LMDCustomLabel, LMDLabel;
  
type
  TfrmMensagem=class(TForm)
    lbMensagem: TLMDLabel;
    procedure _PROC_0064E3C4(Sender : TObject);
    procedure _PROC_0064E3CC(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmMensagem: TfrmMensagem;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmMensagem._PROC_0064E3C4(Sender : TObject);
begin
(*
0064E3C4   832DBCDD7D0001         sub     dword ptr [$007DDDBC], +$01
0064E3CB   C3                     ret

*)
end;

procedure TfrmMensagem._PROC_0064E3CC(Sender : TObject);
begin
(*
0064E3CC   18E4                   sbb     ah, ah
0064E3CE   640000                 add     fs:[eax], al
0064E3D1   0000                   add     [eax], al

*)
end;

end.