unit Mesas;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DB, DBNumEdt, Grids, DBGrids,
  JvExDBGrids, JvDBGrid, ExtCtrls, DBCtrls, JvExMask, JvToolEdit,
  JvDBControls, Mask, Buttons, JvExControls, JvComponent, JvLabel;
  
type
  TfrmMesas=class(TForm)
    pnRodape: TPanel;
    sbAdiciona: TSpeedButton;
    sbGrava: TSpeedButton;
    sbApaga: TSpeedButton;
    sbDesfaz: TSpeedButton;
    sbFecha: TSpeedButton;
    sbImprime: TSpeedButton;
    edDescricao: TDBEdit;
    edCodMesa: TJvDBComboEdit;
    Label1: TLabel;
    rgStatus: TDBRadioGroup;
    Label7: TLabel;
    dsMesas: TDataSource;
    edPosX: TDBEdit;
    Label8: TLabel;
    edPosY: TDBEdit;
    Label9: TLabel;
    DBNavigator1: TDBNavigator;
    sbTodos: TSpeedButton;
    DBStatusLabel1: TJvDBStatusLabel;
    DBText1: TDBText;
    Label2: TLabel;
    grFunc: TJvDBGrid;
    GroupBox1: TGroupBox;
    Label3: TLabel;
    edAtendDia: TDBNumEdit;
    edAtendMes: TDBNumEdit;
    Label4: TLabel;
    GroupBox2: TGroupBox;
    Label5: TLabel;
    edVlrAcumDia: TDBNumEdit;
    edVlrAcumMes: TDBNumEdit;
    Label6: TLabel;
    DBNavigator2: TDBNavigator;
    Bevel1: TBevel;
    EdComanda: TDBEdit;
    Label10: TLabel;
    DBRadioGroup1: TDBRadioGroup;
    procedure edCodMesaButtonClick(Sender : TObject);
    procedure sbAdicionaClick(Sender : TObject);
    procedure sbGravaClick(Sender : TObject);
    procedure sbApagaClick(Sender : TObject);
    procedure sbFechaClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure sbTodosClick(Sender : TObject);
    procedure sbDesfazClick(Sender : TObject);
    procedure DBNavigator2Click(Sender : TObject);
    procedure grFuncEnter(Sender : TObject);
    procedure grFuncExit(Sender : TObject);
    procedure grFuncKeyDown(Sender : TObject);
    procedure _PROC_0069E8AD(Sender : TObject);
    procedure _PROC_0069E8C6(Sender : TObject);
    procedure _PROC_0069E907(Sender : TObject);
    procedure _PROC_0069E91F(Sender : TObject);
    procedure _PROC_0069EBB5(Sender : TObject);
    procedure _PROC_0069EBE6(Sender : TObject);
    procedure _PROC_0069ECAC(Sender : TObject);
    procedure _PROC_0069ECDC(Sender : TObject);
    procedure _PROC_0069ECE4(Sender : TObject);
    procedure _PROC_0069EF83(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  frmMesas: TfrmMesas;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TfrmMesas.edCodMesaButtonClick(Sender : TObject);
begin
(*
0069E614   55                     push    ebp
0069E615   8BEC                   mov     ebp, esp
0069E617   83C4E4                 add     esp, -$1C
0069E61A   33C9                   xor     ecx, ecx
0069E61C   894DEC                 mov     [ebp-$14], ecx
0069E61F   894DE8                 mov     [ebp-$18], ecx
0069E622   894DE4                 mov     [ebp-$1C], ecx
0069E625   33C0                   xor     eax, eax
0069E627   55                     push    ebp

* Possible String Reference to: 'éLfÖÿëë‹å]Ã'
|
0069E628   68E7E66900             push    $0069E6E7

***** TRY
|
0069E62D   64FF30                 push    dword ptr fs:[eax]
0069E630   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'código'
|
0069E633   B8FCE66900             mov     eax, $0069E6FC
0069E638   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Descrição'
|
0069E63B   B80CE76900             mov     eax, $0069E70C
0069E640   8945FC                 mov     [ebp-$04], eax
0069E643   8D45F8                 lea     eax, [ebp-$08]
0069E646   50                     push    eax
0069E647   6A01                   push    $01
0069E649   6A00                   push    $00

* Possible String Reference to: 'CodMesa'
|
0069E64B   B820E76900             mov     eax, $0069E720
0069E650   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'Descricao'
|
0069E653   B830E76900             mov     eax, $0069E730
0069E658   8945F4                 mov     [ebp-$0C], eax
0069E65B   8D55F0                 lea     edx, [ebp-$10]
0069E65E   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'MESAS'
|
0069E663   B844E76900             mov     eax, $0069E744

|
0069E668   E8E7ABF9FF             call    00639254
0069E66D   84C0                   test    al, al
0069E66F   745B                   jz      0069E6CC
0069E671   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0069E676   8B00                   mov     eax, [eax]
0069E678   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODMESA'
|
0069E67B   BA54E76900             mov     edx, $0069E754

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E680   E87FB5E4FF             call    004E9C04
0069E685   8D55E4                 lea     edx, [ebp-$1C]
0069E688   8B08                   mov     ecx, [eax]
0069E68A   FF5160                 call    dword ptr [ecx+$60]
0069E68D   8B45E4                 mov     eax, [ebp-$1C]
0069E690   8D55E8                 lea     edx, [ebp-$18]

* Reference to: SysUtils.QuotedStr(AnsiString):AnsiString;
|
0069E693   E830C2D6FF             call    0040A8C8
0069E698   8B4DE8                 mov     ecx, [ebp-$18]
0069E69B   8D45EC                 lea     eax, [ebp-$14]

* Possible String Reference to: 'CODMESA = '
|
0069E69E   BA64E76900             mov     edx, $0069E764

* Reference to: System.@LStrCat3;
|
0069E6A3   E80071D6FF             call    004057A8
0069E6A8   8B45EC                 mov     eax, [ebp-$14]
0069E6AB   50                     push    eax

* Possible String Reference to: 'CODMESA'
|
0069E6AC   6854E76900             push    $0069E754
0069E6B1   6A01                   push    $01
0069E6B3   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E6B8   8B00                   mov     eax, [eax]
0069E6BA   8B4068                 mov     eax, [eax+$68]
0069E6BD   B978E76900             mov     ecx, $0069E778

* Possible String Reference to: 'MESAS'
|
0069E6C2   BA44E76900             mov     edx, $0069E744

|
0069E6C7   E89C931000             call    007A7A68
0069E6CC   33C0                   xor     eax, eax
0069E6CE   5A                     pop     edx
0069E6CF   59                     pop     ecx
0069E6D0   59                     pop     ecx
0069E6D1   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹å]Ã'
|
0069E6D4   68EEE66900             push    $0069E6EE
0069E6D9   8D45E4                 lea     eax, [ebp-$1C]
0069E6DC   BA03000000             mov     edx, $00000003

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069E6E1   E8DA6DD6FF             call    004054C0
0069E6E6   C3                     ret


* Reference to: System.@HandleFinally;
|
0069E6E7   E94C66D6FF             jmp     00404D38
0069E6EC   EBEB                   jmp     0069E6D9

****** END
|
0069E6EE   8BE5                   mov     esp, ebp
0069E6F0   5D                     pop     ebp
0069E6F1   C3                     ret

*)
end;

procedure TfrmMesas.sbAdicionaClick(Sender : TObject);
begin
(*
0069E77C   55                     push    ebp
0069E77D   8BEC                   mov     ebp, esp
0069E77F   56                     push    esi
0069E780   8BF0                   mov     esi, eax
0069E782   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E787   8B00                   mov     eax, [eax]
0069E789   8B4068                 mov     eax, [eax+$68]

|
0069E78C   E813851000             call    007A6CA4
0069E791   84C0                   test    al, al
0069E793   0F8401010000           jz      0069E89A
0069E799   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E79E   8B00                   mov     eax, [eax]
0069E7A0   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'STATUS'
|
0069E7A3   BAA8E86900             mov     edx, $0069E8A8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E7A8   E857B4E4FF             call    004E9C04
0069E7AD   BAB8E86900             mov     edx, $0069E8B8
0069E7B2   8B08                   mov     ecx, [eax]
0069E7B4   FF91B0000000           call    dword ptr [ecx+$00B0]
0069E7BA   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E7BF   8B00                   mov     eax, [eax]
0069E7C1   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'NUMPESSOAS'
|
0069E7C4   BAC4E86900             mov     edx, $0069E8C4

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E7C9   E836B4E4FF             call    004E9C04
0069E7CE   33D2                   xor     edx, edx
0069E7D0   8B08                   mov     ecx, [eax]
0069E7D2   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E7D8   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E7DD   8B00                   mov     eax, [eax]
0069E7DF   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'ATEND_DIA'
|
0069E7E2   BAD8E86900             mov     edx, $0069E8D8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E7E7   E818B4E4FF             call    004E9C04
0069E7EC   33D2                   xor     edx, edx
0069E7EE   8B08                   mov     ecx, [eax]
0069E7F0   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E7F6   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E7FB   8B00                   mov     eax, [eax]
0069E7FD   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'ATEND_MES'
|
0069E800   BAECE86900             mov     edx, $0069E8EC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E805   E8FAB3E4FF             call    004E9C04
0069E80A   33D2                   xor     edx, edx
0069E80C   8B08                   mov     ecx, [eax]
0069E80E   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E814   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E819   8B00                   mov     eax, [eax]
0069E81B   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'VLR_ACUM_DIA'
|
0069E81E   BA00E96900             mov     edx, $0069E900

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E823   E8DCB3E4FF             call    004E9C04
0069E828   33D2                   xor     edx, edx
0069E82A   8B08                   mov     ecx, [eax]
0069E82C   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E832   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E837   8B00                   mov     eax, [eax]
0069E839   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'VLR_ACUM_MES'
|
0069E83C   BA18E96900             mov     edx, $0069E918

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E841   E8BEB3E4FF             call    004E9C04
0069E846   33D2                   xor     edx, edx
0069E848   8B08                   mov     ecx, [eax]
0069E84A   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E850   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E855   8B00                   mov     eax, [eax]
0069E857   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'POS_X'
|
0069E85A   BA30E96900             mov     edx, $0069E930

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E85F   E8A0B3E4FF             call    004E9C04
0069E864   33D2                   xor     edx, edx
0069E866   8B08                   mov     ecx, [eax]
0069E868   FF91A8000000           call    dword ptr [ecx+$00A8]
0069E86E   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E873   8B00                   mov     eax, [eax]
0069E875   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'POS_Y'
|
0069E878   BA40E96900             mov     edx, $0069E940

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069E87D   E882B3E4FF             call    004E9C04
0069E882   33D2                   xor     edx, edx
0069E884   8B08                   mov     ecx, [eax]
0069E886   FF91A8000000           call    dword ptr [ecx+$00A8]

* Reference to control TfrmMesas.edCodMesa : TJvDBComboEdit
|
0069E88C   8B8618030000           mov     eax, [esi+$0318]
0069E892   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvDBComboEdit.OFFS_00C4
|
0069E894   FF92C4000000           call    dword ptr [edx+$00C4]
0069E89A   5E                     pop     esi
0069E89B   5D                     pop     ebp
0069E89C   C3                     ret

*)
end;

procedure TfrmMesas.sbGravaClick(Sender : TObject);
begin
(*
0069E948   55                     push    ebp
0069E949   8BEC                   mov     ebp, esp
0069E94B   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E950   8B00                   mov     eax, [eax]
0069E952   8B4068                 mov     eax, [eax+$68]

|
0069E955   E806861000             call    007A6F60
0069E95A   5D                     pop     ebp
0069E95B   C3                     ret

*)
end;

procedure TfrmMesas.sbApagaClick(Sender : TObject);
begin
(*
0069E95C   55                     push    ebp
0069E95D   8BEC                   mov     ebp, esp
0069E95F   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E964   8B00                   mov     eax, [eax]
0069E966   8B4068                 mov     eax, [eax+$68]
0069E969   B201                   mov     dl, $01

|
0069E96B   E8E8881000             call    007A7258
0069E970   5D                     pop     ebp
0069E971   C3                     ret

*)
end;

procedure TfrmMesas.sbFechaClick(Sender : TObject);
begin
(*
0069E974   55                     push    ebp
0069E975   8BEC                   mov     ebp, esp

* Reference to: Forms.TCustomForm.Close(TCustomForm);
|
0069E977   E84437E1FF             call    004B20C0
0069E97C   5D                     pop     ebp
0069E97D   C3                     ret

*)
end;

procedure TfrmMesas.FormShow(Sender : TObject);
begin
(*
0069E980   55                     push    ebp
0069E981   8BEC                   mov     ebp, esp

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
0069E983   E8B4F21000             call    007ADC3C
0069E988   5D                     pop     ebp
0069E989   C3                     ret

*)
end;

procedure TfrmMesas.sbTodosClick(Sender : TObject);
begin
(*
0069E98C   55                     push    ebp
0069E98D   8BEC                   mov     ebp, esp
0069E98F   33C9                   xor     ecx, ecx
0069E991   51                     push    ecx
0069E992   51                     push    ecx
0069E993   51                     push    ecx
0069E994   51                     push    ecx
0069E995   51                     push    ecx
0069E996   51                     push    ecx
0069E997   33C0                   xor     eax, eax
0069E999   55                     push    ebp
0069E99A   684DEA6900             push    $0069EA4D

***** TRY
|
0069E99F   64FF30                 push    dword ptr fs:[eax]
0069E9A2   648920                 mov     fs:[eax], esp
0069E9A5   8D55FC                 lea     edx, [ebp-$04]
0069E9A8   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E9AD   8B00                   mov     eax, [eax]
0069E9AF   8B8004020000           mov     eax, [eax+$0204]
0069E9B5   8B08                   mov     ecx, [eax]
0069E9B7   FF5160                 call    dword ptr [ecx+$60]
0069E9BA   6A00                   push    $00

* Possible String Reference to: 'CODMESA'
|
0069E9BC   6860EA6900             push    $0069EA60
0069E9C1   6A01                   push    $01
0069E9C3   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E9C8   8B00                   mov     eax, [eax]
0069E9CA   8B4068                 mov     eax, [eax+$68]
0069E9CD   B970EA6900             mov     ecx, $0069EA70

* Possible String Reference to: 'MESAS'
|
0069E9D2   BA7CEA6900             mov     edx, $0069EA7C

|
0069E9D7   E88C901000             call    007A7A68
0069E9DC   84C0                   test    al, al
0069E9DE   744A                   jz      0069EA2A
0069E9E0   8D55F8                 lea     edx, [ebp-$08]
0069E9E3   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069E9E8   8B00                   mov     eax, [eax]
0069E9EA   8B8004020000           mov     eax, [eax+$0204]
0069E9F0   8B08                   mov     ecx, [eax]
0069E9F2   FF5160                 call    dword ptr [ecx+$60]
0069E9F5   8B45F8                 mov     eax, [ebp-$08]
0069E9F8   8B55FC                 mov     edx, [ebp-$04]

* Reference to: System.@LStrCmp;
|
0069E9FB   E8A86ED6FF             call    004058A8
0069EA00   7428                   jz      0069EA2A
0069EA02   A084EA6900             mov     al, byte ptr [$0069EA84]
0069EA07   50                     push    eax
0069EA08   8D45E8                 lea     eax, [ebp-$18]
0069EA0B   8B55FC                 mov     edx, [ebp-$04]

* Reference to: Variants.@VarFromLStr(TVarData;TVarData;AnsiString);
|
0069EA0E   E8B1A2D7FF             call    00418CC4
0069EA13   8D4DE8                 lea     ecx, [ebp-$18]
0069EA16   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EA1B   8B00                   mov     eax, [eax]
0069EA1D   8B4068                 mov     eax, [eax+$68]

* Possible String Reference to: 'CODMESA'
|
0069EA20   BA60EA6900             mov     edx, $0069EA60

* Reference to : TFrmInfoAtu._PROC_007A83F8()
|
0069EA25   E8CE991000             call    007A83F8
0069EA2A   33C0                   xor     eax, eax
0069EA2C   5A                     pop     edx
0069EA2D   59                     pop     ecx
0069EA2E   59                     pop     ecx
0069EA2F   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069EA32   6854EA6900             push    $0069EA54
0069EA37   8D45E8                 lea     eax, [ebp-$18]

* Reference to: Variants.@VarClr(TVarData;TVarData);
|
0069EA3A   E8395BD7FF             call    00414578
0069EA3F   8D45F8                 lea     eax, [ebp-$08]
0069EA42   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069EA47   E8746AD6FF             call    004054C0
0069EA4C   C3                     ret


* Reference to: System.@HandleFinally;
|
0069EA4D   E9E662D6FF             jmp     00404D38
0069EA52   EBE3                   jmp     0069EA37

****** END
|
0069EA54   8BE5                   mov     esp, ebp
0069EA56   5D                     pop     ebp
0069EA57   C3                     ret

*)
end;

procedure TfrmMesas.sbDesfazClick(Sender : TObject);
begin
(*
0069EA88   55                     push    ebp
0069EA89   8BEC                   mov     ebp, esp
0069EA8B   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EA90   8B00                   mov     eax, [eax]
0069EA92   8B4068                 mov     eax, [eax+$68]

|
0069EA95   E89A881000             call    007A7334
0069EA9A   5D                     pop     ebp
0069EA9B   C3                     ret

*)
end;

procedure TfrmMesas.DBNavigator2Click(Sender : TObject);
begin
(*
0069EA9C   55                     push    ebp
0069EA9D   8BEC                   mov     ebp, esp
0069EA9F   83C4E4                 add     esp, -$1C
0069EAA2   53                     push    ebx
0069EAA3   33DB                   xor     ebx, ebx
0069EAA5   895DE4                 mov     [ebp-$1C], ebx
0069EAA8   33C0                   xor     eax, eax
0069EAAA   55                     push    ebp

* Possible String Reference to: 'éÊaÖÿëð[‹å]Ã'
|
0069EAAB   6869EB6900             push    $0069EB69

***** TRY
|
0069EAB0   64FF30                 push    dword ptr fs:[eax]
0069EAB3   648920                 mov     fs:[eax], esp
0069EAB6   80F904                 cmp     cl, $04
0069EAB9   0F8594000000           jnz     0069EB53

* Possible String Reference to: 'Código'
|
0069EABF   B880EB6900             mov     eax, $0069EB80
0069EAC4   8945F4                 mov     [ebp-$0C], eax

* Possible String Reference to: 'Nome'
|
0069EAC7   B890EB6900             mov     eax, $0069EB90
0069EACC   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Apelido'
|
0069EACF   B8A0EB6900             mov     eax, $0069EBA0
0069EAD4   8945FC                 mov     [ebp-$04], eax
0069EAD7   8D45F4                 lea     eax, [ebp-$0C]
0069EADA   50                     push    eax
0069EADB   6A02                   push    $02
0069EADD   6A00                   push    $00

* Possible String Reference to: 'CODFUNC'
|
0069EADF   B8B0EB6900             mov     eax, $0069EBB0
0069EAE4   8945E8                 mov     [ebp-$18], eax

* Possible String Reference to: 'NOME'
|
0069EAE7   B8C0EB6900             mov     eax, $0069EBC0
0069EAEC   8945EC                 mov     [ebp-$14], eax

* Possible String Reference to: 'FANTASIA'
|
0069EAEF   B8D0EB6900             mov     eax, $0069EBD0
0069EAF4   8945F0                 mov     [ebp-$10], eax
0069EAF7   8D55E8                 lea     edx, [ebp-$18]
0069EAFA   B902000000             mov     ecx, $00000002

* Possible String Reference to: 'FUNCREPR'
|
0069EAFF   B8E4EB6900             mov     eax, $0069EBE4

|
0069EB04   E84BA7F9FF             call    00639254
0069EB09   84C0                   test    al, al
0069EB0B   7446                   jz      0069EB53
0069EB0D   A1689F7D00             mov     eax, dword ptr [$007D9F68]
0069EB12   8B00                   mov     eax, [eax]
0069EB14   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CodFunc'
|
0069EB17   BAF8EB6900             mov     edx, $0069EBF8

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0069EB1C   E8E3B0E4FF             call    004E9C04
0069EB21   8D55E4                 lea     edx, [ebp-$1C]
0069EB24   8B08                   mov     ecx, [eax]
0069EB26   FF5160                 call    dword ptr [ecx+$60]
0069EB29   8B55E4                 mov     edx, [ebp-$1C]
0069EB2C   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EB31   8B00                   mov     eax, [eax]
0069EB33   8B809C050000           mov     eax, [eax+$059C]
0069EB39   8B08                   mov     ecx, [eax]
0069EB3B   FF91B0000000           call    dword ptr [ecx+$00B0]
0069EB41   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EB46   8B00                   mov     eax, [eax]
0069EB48   8B80AC050000           mov     eax, [eax+$05AC]

* Reference to: DB.TField.FocusControl(TField);
|
0069EB4E   E811F4E3FF             call    004DDF64
0069EB53   33C0                   xor     eax, eax
0069EB55   5A                     pop     edx
0069EB56   59                     pop     ecx
0069EB57   59                     pop     ecx
0069EB58   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
0069EB5B   6870EB6900             push    $0069EB70
0069EB60   8D45E4                 lea     eax, [ebp-$1C]

* Reference to: System.@LStrClr(void;void);
|
0069EB63   E83469D6FF             call    0040549C
0069EB68   C3                     ret


* Reference to: System.@HandleFinally;
|
0069EB69   E9CA61D6FF             jmp     00404D38
0069EB6E   EBF0                   jmp     0069EB60

****** END
|
0069EB70   5B                     pop     ebx
0069EB71   8BE5                   mov     esp, ebp
0069EB73   5D                     pop     ebp
0069EB74   C3                     ret

*)
end;

procedure TfrmMesas.grFuncEnter(Sender : TObject);
begin
(*
0069EC00   55                     push    ebp
0069EC01   8BEC                   mov     ebp, esp

|
0069EC03   E838731000             call    007A5F40
0069EC08   5D                     pop     ebp
0069EC09   C3                     ret

*)
end;

procedure TfrmMesas.grFuncExit(Sender : TObject);
begin
(*
0069EC0C   55                     push    ebp
0069EC0D   8BEC                   mov     ebp, esp

|
0069EC0F   E844731000             call    007A5F58
0069EC14   5D                     pop     ebp
0069EC15   C3                     ret

*)
end;

procedure TfrmMesas.grFuncKeyDown(Sender : TObject);
begin
(*
0069EC18   55                     push    ebp
0069EC19   8BEC                   mov     ebp, esp
0069EC1B   6683390D               cmp     word ptr [ecx], +$0D
0069EC1F   0F8581000000           jnz     0069ECA6

* Reference to control TfrmMesas.grFunc : TJvDBGrid
|
0069EC25   8B8050030000           mov     eax, [eax+$0350]

* Reference to field TJvDBGrid.OFFS_0228
|
0069EC2B   8B8028020000           mov     eax, [eax+$0228]
0069EC31   83F804                 cmp     eax, +$04
0069EC34   7770                   jnbe    0069ECA6
0069EC36   FF24853DEC6900         jmp     dword ptr [$69EC3D+eax*4]
0069EC3D   51                     push    ecx
0069EC3E   EC                     in      al, dx
0069EC3F   690065EC6900           imul    eax, [eax], $0069EC65
0069EC45   79EC                   jns     0069EC33
0069EC47   69008DEC6900           imul    eax, [eax], $0069EC8D
0069EC4D   A1EC6900A1             mov     eax, dword ptr [$A10069EC]
0069EC52   8CA97D008B00           mov     word ptr [ecx+$8B007D], gs
0069EC58   8B80AC050000           mov     eax, [eax+$05AC]

* Reference to: DB.TField.FocusControl(TField);
|
0069EC5E   E801F3E3FF             call    004DDF64
0069EC63   EB41                   jmp     0069ECA6
0069EC65   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EC6A   8B00                   mov     eax, [eax]
0069EC6C   8B80AC050000           mov     eax, [eax+$05AC]

* Reference to: DB.TField.FocusControl(TField);
|
0069EC72   E8EDF2E3FF             call    004DDF64
0069EC77   EB2D                   jmp     0069ECA6
0069EC79   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EC7E   8B00                   mov     eax, [eax]
0069EC80   8B80B0050000           mov     eax, [eax+$05B0]

* Reference to: DB.TField.FocusControl(TField);
|
0069EC86   E8D9F2E3FF             call    004DDF64
0069EC8B   EB19                   jmp     0069ECA6
0069EC8D   A18CA97D00             mov     eax, dword ptr [$007DA98C]
0069EC92   8B00                   mov     eax, [eax]
0069EC94   8B80A0050000           mov     eax, [eax+$05A0]

* Reference to: DB.TField.FocusControl(TField);
|
0069EC9A   E8C5F2E3FF             call    004DDF64
0069EC9F   EB05                   jmp     0069ECA6

* Reference to : TFrmInfoAtu._PROC_007A600C()
|
0069ECA1   E866731000             call    007A600C
0069ECA6   5D                     pop     ebp
0069ECA7   C20400                 ret     $0004

*)
end;

procedure TfrmMesas._PROC_0069E8AD(Sender : TObject);
begin
(*
0069E8AD   53                     push    ebx
0069E8AE   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069E8C6(Sender : TObject);
begin
(*
0069E8C6   4D                     dec     ebp
0069E8C7   50                     push    eax
0069E8C8   45                     inc     ebp
0069E8C9   53                     push    ebx
0069E8CA   53                     push    ebx
0069E8CB   4F                     dec     edi
0069E8CC   41                     inc     ecx
0069E8CD   53                     push    ebx
0069E8CE   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069E907(Sender : TObject);
begin
(*
0069E907   4D                     dec     ebp
0069E908   5F                     pop     edi
0069E909   44                     inc     esp
0069E90A   49                     dec     ecx
0069E90B   41                     inc     ecx
0069E90C   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069E91F(Sender : TObject);
begin
(*
0069E91F   4D                     dec     ebp
0069E920   5F                     pop     edi
0069E921   4D                     dec     ebp
0069E922   45                     inc     ebp
0069E923   53                     push    ebx
0069E924   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069EBB5(Sender : TObject);
begin
(*
0069EBB5   4E                     dec     esi
0069EBB6   43                     inc     ebx
0069EBB7   00FF                   add     bh, bh
0069EBB9   FFFF                   DB  $FF, $FF  //      
0069EBBB   FF0400                 inc     dword ptr [eax+eax]
0069EBBE   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069EBE6(Sender : TObject);
begin
(*
0069EBE6   4E                     dec     esi
0069EBE7   43                     inc     ebx
0069EBE8   52                     push    edx
0069EBE9   45                     inc     ebp
0069EBEA   50                     push    eax
0069EBEB   52                     push    edx
0069EBEC   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069ECAC(Sender : TObject);
begin
(*
0069ECAC   55                     push    ebp
0069ECAD   8BEC                   mov     ebp, esp
0069ECAF   33C0                   xor     eax, eax
0069ECB1   55                     push    ebp
0069ECB2   68D1EC6900             push    $0069ECD1

***** TRY
|
0069ECB7   64FF30                 push    dword ptr fs:[eax]
0069ECBA   648920                 mov     fs:[eax], esp
0069ECBD   FF0510ED7D00           inc     dword ptr [$007DED10]
0069ECC3   33C0                   xor     eax, eax
0069ECC5   5A                     pop     edx
0069ECC6   59                     pop     ecx
0069ECC7   59                     pop     ecx
0069ECC8   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069ECCB   68D8EC6900             push    $0069ECD8
0069ECD0   C3                     ret


* Reference to: System.@HandleFinally;
|
0069ECD1   E96260D6FF             jmp     00404D38
0069ECD6   EBF8                   jmp     0069ECD0

****** END
|
0069ECD8   5D                     pop     ebp
0069ECD9   C3                     ret

*)
end;

procedure TfrmMesas._PROC_0069ECDC(Sender : TObject);
begin
(*
0069ECDC   832D10ED7D0001         sub     dword ptr [$007DED10], +$01
0069ECE3   C3                     ret

*)
end;

procedure TfrmMesas._PROC_0069ECE4(Sender : TObject);
begin
(*
0069ECE4   30ED                   xor     ch, ch
0069ECE6   690000000000           imul    eax, [eax], $00000000
0069ECEC   0000                   add     [eax], al

*)
end;

procedure TfrmMesas._PROC_0069EF83(Sender : TObject);
begin
(*
0069EF83   7043                   jo      0069EFC8
0069EF85   6C                     insb
0069EF86   69636B17002CFB         imul    esp, [ebx+$6B], $FB2C0017
0069EF8D   690010627450           imul    eax, [eax], $50746210
0069EF93   726F                   jb      0069F004
0069EF95   636573                 arpl    [ebp+$73], sp
0069EF98   7361                   jnb     0069EFFB
0069EF9A   7243                   jb      0069EFDF
0069EF9C   6C                     insb
0069EF9D   69636B160038FB         imul    esp, [ebx+$6B], $FB380016
0069EFA4   69000F736241           imul    eax, [eax], $4162730F
0069EFAA   6C                     insb
0069EFAB   7475                   jz      0069F022
0069EFAD   7261                   jb      0069F010
0069EFAF   55                     push    ebp
0069EFB0   7043                   jo      0069EFF5
0069EFB2   6C                     insb
0069EFB3   69636B180028FC         imul    esp, [ebx+$6B], $FC280018
0069EFBA   690011736241           imul    eax, [eax], $41627311
0069EFC0   6C                     insb
0069EFC1   7475                   jz      0069F038
0069EFC3   7261                   jb      0069F026
0069EFC5   44                     inc     esp
0069EFC6   6F                     outsd
0069EFC7   776E                   jnbe    0069F037
0069EFC9   43                     inc     ebx
0069EFCA   6C                     insb
0069EFCB   69636B170014FD         imul    esp, [ebx+$6B], $FD140017
0069EFD2   69001073624C           imul    eax, [eax], $4C627310
0069EFD8   61                     popa
0069EFD9   7267                   jb      0069F042
0069EFDB   7572                   jnz     0069F04F
0069EFDD   61                     popa
0069EFDE   55                     push    ebp
0069EFDF   7043                   jo      0069F024
0069EFE1   6C                     insb
0069EFE2   69636B190004FE         imul    esp, [ebx+$6B], $FE040019
0069EFE9   69001273624C           imul    eax, [eax], $4C627312
0069EFEF   61                     popa
0069EFF0   7267                   jb      0069F059
0069EFF2   7572                   jnz     0069F066
0069EFF4   61                     popa
0069EFF5   44                     inc     esp
0069EFF6   6F                     outsd
0069EFF7   776E                   jnbe    0069F067
0069EFF9   43                     inc     ebx
0069EFFA   6C                     insb
0069EFFB   69636B0F00F4FE         imul    esp, [ebx+$6B], $FEF4000F
0069F002   690008466F72           imul    eax, [eax], $726F4608
0069F008   6D                     insd
0069F009   53                     push    ebx
0069F00A   686F770C54             push    $540C776F
0069F00F   46                     inc     esi
0069F010   726D                   jb      0069F07F
0069F012   43                     inc     ebx
0069F013   61                     popa
0069F014   644D                   dec     ebp
0069F016   657361                 jnb     0069F07A
0069F019   7308                   jnb     0069F023
0069F01B   0004F4                 add     [esp+esi*8], al
0069F01E   47                     inc     edi
0069F01F   0070CF                 add     [eax-$31], dh
0069F022   44                     inc     esp
0069F023   00DC                   add     ah, bl
0069F025   51                     push    ecx
0069F026   44                     inc     esp
0069F027   00A82B4800D0           add     [eax+$D000482B], ch
0069F02D   186500                 sbb     [ebp+$00], ah
0069F030   2CFD                   sub     al, $FD
0069F032   58                     pop     eax
0069F033   00A0FC4700C4           add     [eax+$C40047FC], ah
0069F039   ED                     in      eax, dx
0069F03A   670040F0               add     [bx+si-$10], al
0069F03E   6900070C5446           imul    eax, [eax], $46540C07
0069F044   726D                   jb      0069F0B3
0069F046   43                     inc     ebx
0069F047   61                     popa
0069F048   644D                   dec     ebp
0069F04A   657361                 jnb     0069F0AE
0069F04D   7330                   jnb     0069F07F
0069F04F   ED                     in      eax, dx
0069F050   690038B44A00           imul    eax, [eax], $004AB438
0069F056   5E                     pop     esi
0069F057   0006                   add     [esi], al
0069F059   43                     inc     ebx
0069F05A   61                     popa
0069F05B   644D                   dec     ebp
0069F05D   657300                 jnb     0069F060
0069F060   008D4000558B           add     [ebp+$8B550040], cl
0069F066   EC                     in      al, dx
0069F067   33C9                   xor     ecx, ecx
0069F069   51                     push    ecx
0069F06A   51                     push    ecx
0069F06B   51                     push    ecx
0069F06C   51                     push    ecx
0069F06D   51                     push    ecx
0069F06E   51                     push    ecx
0069F06F   51                     push    ecx
0069F070   51                     push    ecx
0069F071   53                     push    ebx
0069F072   56                     push    esi
0069F073   57                     push    edi
0069F074   8BD8                   mov     ebx, eax
0069F076   8B3D8CA97D00           mov     edi, [$007DA98C]
0069F07C   33C0                   xor     eax, eax
0069F07E   55                     push    ebp

* Possible String Reference to: 'éÇYÖÿëë_^[‹å]Ã'
|
0069F07F   686CF36900             push    $0069F36C

***** TRY
|
0069F084   64FF30                 push    dword ptr fs:[eax]
0069F087   648920                 mov     fs:[eax], esp
0069F08A   33C0                   xor     eax, eax
0069F08C   55                     push    ebp
0069F08D   684AF36900             push    $0069F34A

***** TRY
|
0069F092   64FF30                 push    dword ptr fs:[eax]
0069F095   648920                 mov     fs:[eax], esp
0069F098   33C0                   xor     eax, eax
0069F09A   55                     push    ebp
0069F09B   6801F36900             push    $0069F301

***** TRY
|
0069F0A0   64FF30                 push    dword ptr fs:[eax]
0069F0A3   648920                 mov     fs:[eax], esp
0069F0A6   8BC3                   mov     eax, ebx

* Reference to : TFrmCadMesas._PROC_0069F924()
|
0069F0A8   E877080000             call    0069F924
0069F0AD   84C0                   test    al, al
0069F0AF   0F8442020000           jz      0069F2F7
0069F0B5   8B8308030000           mov     eax, [ebx+$0308]
0069F0BB   8B10                   mov     edx, [eax]
0069F0BD   FF92C8000000           call    dword ptr [edx+$00C8]
0069F0C3   84C0                   test    al, al
0069F0C5   7407                   jz      0069F0CE
0069F0C7   8BC3                   mov     eax, ebx

|
0069F0C9   E8F2040000             call    0069F5C0
0069F0CE   8B07                   mov     eax, [edi]
0069F0D0   8B4068                 mov     eax, [eax+$68]

* Reference to: DB.TDataSet.GetActive(TDataSet):Boolean;
|
0069F0D3   E8C899E4FF             call    004E8AA0
0069F0D8   84C0                   test    al, al
0069F0DA   750A                   jnz     0069F0E6
0069F0DC   8B07                   mov     eax, [edi]
0069F0DE   8B4068                 mov     eax, [eax+$68]

|
0069F0E1   E822741000             call    007A6508
0069F0E6   BE23000000             mov     esi, $00000023
0069F0EB   C745F823000000         mov     dword ptr [ebp-$08], $00000023
0069F0F2   8B8314030000           mov     eax, [ebx+$0314]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F0F8   E84B3CFBFF             call    00652D48
0069F0FD   85C0                   test    eax, eax
0069F0FF   0F8EDD010000           jle     0069F2E2
0069F105   8945F4                 mov     [ebp-$0C], eax
0069F108   C745FC01000000         mov     dword ptr [ebp-$04], $00000001
0069F10F   8D55EC                 lea     edx, [ebp-$14]
0069F112   8B45FC                 mov     eax, [ebp-$04]

* Reference to: SysUtils.IntToStr(Integer):AnsiString;overload;
|
0069F115   E84ABCD6FF             call    0040AD64
0069F11A   8B4DEC                 mov     ecx, [ebp-$14]
0069F11D   8D45F0                 lea     eax, [ebp-$10]

* Possible String Reference to: 'CODMESA = '
|
0069F120   BA84F36900             mov     edx, $0069F384

* Reference to: System.@LStrCat3;
|
0069F125   E87E66D6FF             call    004057A8
0069F12A   8B45F0                 mov     eax, [ebp-$10]
0069F12D   50                     push    eax
0069F12E   6A00                   push    $00
0069F130   6A01                   push    $01
0069F132   8B07                   mov     eax, [edi]
0069F134   8B4068                 mov     eax, [eax+$68]
0069F137   B998F36900             mov     ecx, $0069F398

* Possible String Reference to: 'MESAS'
|
0069F13C   BAA4F36900             mov     edx, $0069F3A4

|
0069F141   E822891000             call    007A7A68
0069F146   8B07                   mov     eax, [edi]
0069F148   8B4068                 mov     eax, [eax+$68]

* Reference to: DB.TDataSet.IsEmpty(TDataSet):Boolean;
|
0069F14B   E86CBDE4FF             call    004EAEBC
0069F150   84C0                   test    al, al
0069F152   0F84DA000000           jz      0069F232
0069F158   8B07                   mov     eax, [edi]
0069F15A   8B4068                 mov     eax, [eax+$68]

* Reference to: DB.TDataSet.Insert(TDataSet);
|
0069F15D   E86AC3E4FF             call    004EB4CC
0069F162   8B07                   mov     eax, [edi]
0069F164   8B8004020000           mov     eax, [eax+$0204]
0069F16A   8B55FC                 mov     edx, [ebp-$04]
0069F16D   8B08                   mov     ecx, [eax]
0069F16F   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F175   DB45FC                 fild    dword ptr [ebp-$04]
0069F178   83C4F4                 add     esp, -$0C
0069F17B   DB3C24                 fstp    tbyte ptr [esp]
0069F17E   9B                     wait
0069F17F   8D55E4                 lea     edx, [ebp-$1C]

* Possible String Reference to: '00'
|
0069F182   B8B4F36900             mov     eax, $0069F3B4

* Reference to: SysUtils.FormatFloat(AnsiString;Extended):AnsiString;overload;
|
0069F187   E8B0E3D6FF             call    0040D53C
0069F18C   8B4DE4                 mov     ecx, [ebp-$1C]
0069F18F   8D45E8                 lea     eax, [ebp-$18]

* Possible String Reference to: 'MESA '
|
0069F192   BAC0F36900             mov     edx, $0069F3C0

* Reference to: System.@LStrCat3;
|
0069F197   E80C66D6FF             call    004057A8
0069F19C   8B55E8                 mov     edx, [ebp-$18]
0069F19F   8B07                   mov     eax, [edi]
0069F1A1   8B8008020000           mov     eax, [eax+$0208]
0069F1A7   8B08                   mov     ecx, [eax]
0069F1A9   FF91B0000000           call    dword ptr [ecx+$00B0]
0069F1AF   8B07                   mov     eax, [edi]
0069F1B1   8B800C020000           mov     eax, [eax+$020C]
0069F1B7   BAD0F36900             mov     edx, $0069F3D0
0069F1BC   8B08                   mov     ecx, [eax]
0069F1BE   FF91B0000000           call    dword ptr [ecx+$00B0]
0069F1C4   8B07                   mov     eax, [edi]
0069F1C6   8B8028020000           mov     eax, [eax+$0228]
0069F1CC   8BD6                   mov     edx, esi
0069F1CE   8B08                   mov     ecx, [eax]
0069F1D0   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F1D6   8B07                   mov     eax, [edi]
0069F1D8   8B802C020000           mov     eax, [eax+$022C]
0069F1DE   8B55F8                 mov     edx, [ebp-$08]
0069F1E1   8B08                   mov     ecx, [eax]
0069F1E3   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F1E9   8B8328030000           mov     eax, [ebx+$0328]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F1EF   E8543BFBFF             call    00652D48
0069F1F4   8BD0                   mov     edx, eax
0069F1F6   8B07                   mov     eax, [edi]
0069F1F8   8B8088050000           mov     eax, [eax+$0588]
0069F1FE   8B08                   mov     ecx, [eax]
0069F200   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F206   8B8334030000           mov     eax, [ebx+$0334]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F20C   E8373BFBFF             call    00652D48
0069F211   8BD0                   mov     edx, eax
0069F213   8B07                   mov     eax, [edi]
0069F215   8B808C050000           mov     eax, [eax+$058C]
0069F21B   8B08                   mov     ecx, [eax]
0069F21D   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F223   8B07                   mov     eax, [edi]
0069F225   8B4068                 mov     eax, [eax+$68]
0069F228   8B10                   mov     edx, [eax]
0069F22A   FF924C020000           call    dword ptr [edx+$024C]
0069F230   EB76                   jmp     0069F2A8
0069F232   8B07                   mov     eax, [edi]
0069F234   8B4068                 mov     eax, [eax+$68]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0069F237   E8FCC1E4FF             call    004EB438
0069F23C   8B07                   mov     eax, [edi]
0069F23E   8B8028020000           mov     eax, [eax+$0228]
0069F244   8BD6                   mov     edx, esi
0069F246   8B08                   mov     ecx, [eax]
0069F248   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F24E   8B07                   mov     eax, [edi]
0069F250   8B802C020000           mov     eax, [eax+$022C]
0069F256   8B55F8                 mov     edx, [ebp-$08]
0069F259   8B08                   mov     ecx, [eax]
0069F25B   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F261   8B8328030000           mov     eax, [ebx+$0328]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F267   E8DC3AFBFF             call    00652D48
0069F26C   8BD0                   mov     edx, eax
0069F26E   8B07                   mov     eax, [edi]
0069F270   8B8088050000           mov     eax, [eax+$0588]
0069F276   8B08                   mov     ecx, [eax]
0069F278   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F27E   8B8334030000           mov     eax, [ebx+$0334]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F284   E8BF3AFBFF             call    00652D48
0069F289   8BD0                   mov     edx, eax
0069F28B   8B07                   mov     eax, [edi]
0069F28D   8B808C050000           mov     eax, [eax+$058C]
0069F293   8B08                   mov     ecx, [eax]
0069F295   FF91A8000000           call    dword ptr [ecx+$00A8]
0069F29B   8B07                   mov     eax, [edi]
0069F29D   8B4068                 mov     eax, [eax+$68]
0069F2A0   8B10                   mov     edx, [eax]
0069F2A2   FF924C020000           call    dword ptr [edx+$024C]
0069F2A8   8B8334030000           mov     eax, [ebx+$0334]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F2AE   E8953AFBFF             call    00652D48
0069F2B3   83C00A                 add     eax, +$0A
0069F2B6   03F0                   add     esi, eax
0069F2B8   81FEBC020000           cmp     esi, $000002BC
0069F2BE   7C16                   jl      0069F2D6
0069F2C0   BE23000000             mov     esi, $00000023
0069F2C5   8B8328030000           mov     eax, [ebx+$0328]

* Reference to : TJvValidateEdit._PROC_00652D48()
|
0069F2CB   E8783AFBFF             call    00652D48
0069F2D0   83C00A                 add     eax, +$0A
0069F2D3   0145F8                 add     [ebp-$08], eax
0069F2D6   FF45FC                 inc     dword ptr [ebp-$04]
0069F2D9   FF4DF4                 dec     dword ptr [ebp-$0C]
0069F2DC   0F852DFEFFFF           jnz     0069F10F
0069F2E2   6A00                   push    $00
0069F2E4   668B0DD4F36900         mov     cx, word ptr [$0069F3D4]
0069F2EB   B202                   mov     dl, $02

* Possible String Reference to: 'O cadastro de mesas foi concluído c
|                                om sucesso!'
|
0069F2ED   B8E0F36900             mov     eax, $0069F3E0

|
0069F2F2   E83548DAFF             call    00443B2C
0069F2F7   33C0                   xor     eax, eax
0069F2F9   5A                     pop     edx
0069F2FA   59                     pop     ecx
0069F2FB   59                     pop     ecx
0069F2FC   648910                 mov     fs:[eax], edx
0069F2FF   EB3B                   jmp     0069F33C

* Reference to: System.@HandleOnException;
|
0069F301   E9AA58D6FF             jmp     00404BB0
0069F306   0100                   add     [eax], eax
0069F308   0000                   add     [eax], al
0069F30A   40                     inc     eax
0069F30B   95                     xchg    eax, ebp
0069F30C   40                     inc     eax
0069F30D   0012                   add     [edx], dl
0069F30F   F3                     rep
0069F310   690089C36A00           imul    eax, [eax], $006AC389
0069F316   8B4B04                 mov     ecx, [ebx+$04]
0069F319   8D45E0                 lea     eax, [ebp-$20]

* Possible String Reference to: 'Erro ao executar o cadastro automát
|                                ico de mesas!'
|
0069F31C   BA18F46900             mov     edx, $0069F418

* Reference to: System.@LStrCat3;
|
0069F321   E88264D6FF             call    004057A8
0069F326   8B45E0                 mov     eax, [ebp-$20]
0069F329   668B0DD4F36900         mov     cx, word ptr [$0069F3D4]
0069F330   B201                   mov     dl, $01

|
0069F332   E8F547DAFF             call    00443B2C

* Reference to: System.@DoneExcept;
|
0069F337   E8745BD6FF             call    00404EB0

****** END
|
0069F33C   33C0                   xor     eax, eax
0069F33E   5A                     pop     edx
0069F33F   59                     pop     ecx
0069F340   59                     pop     ecx
0069F341   648910                 mov     fs:[eax], edx

****** FINALLY
|
0069F344   6851F36900             push    $0069F351
0069F349   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F34A   E9E959D6FF             jmp     00404D38
0069F34F   EBF8                   jmp     0069F349

****** END
|
0069F351   33C0                   xor     eax, eax
0069F353   5A                     pop     edx
0069F354   59                     pop     ecx
0069F355   59                     pop     ecx
0069F356   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
0069F359   6873F36900             push    $0069F373
0069F35E   8D45E0                 lea     eax, [ebp-$20]
0069F361   BA05000000             mov     edx, $00000005

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0069F366   E85561D6FF             call    004054C0
0069F36B   C3                     ret


* Reference to: System.@HandleFinally;
|
0069F36C   E9C759D6FF             jmp     00404D38
0069F371   EBEB                   jmp     0069F35E

****** END
|
0069F373   5F                     pop     edi
0069F374   5E                     pop     esi
0069F375   5B                     pop     ebx
0069F376   8BE5                   mov     esp, ebp
0069F378   5D                     pop     ebp
0069F379   C3                     ret

*)
end;

end.