unit Params;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ImgList, PBPrinterSetupDialog,
  JvComponentBase, JvBaseDlg, JvAddPrinter, Buttons, ToolEdit, DBCtrls,
  ExtCtrls, JvExMask, JvToolEdit, JvDBControls, Mask, ComCtrls;
  
type
  TFrmParametros=class(TForm)
    Label1: TLabel;
    PageControl1: TPageControl;
    TsGeral: TTabSheet;
    TsImpressao: TTabSheet;
    BitBtn1: TBitBtn;
    PageControl2: TPageControl;
    TabSheet6: TTabSheet;
    Label23: TLabel;
    Label26: TLabel;
    TabSheet7: TTabSheet;
    TabSheet8: TTabSheet;
    SpeedButton2: TSpeedButton;
    sbPadroes: TSpeedButton;
    GroupBox2: TGroupBox;
    Label12: TLabel;
    Label11: TLabel;
    Label9: TLabel;
    EdDtFiscal: TDBEdit;
    EdNumPDV: TDBEdit;
    EdNumCupom: TDBEdit;
    GroupBox1: TGroupBox;
    Label19: TLabel;
    Label18: TLabel;
    GroupBox3: TGroupBox;
    Label54: TLabel;
    Label55: TLabel;
    Label56: TLabel;
    Label57: TLabel;
    Label58: TLabel;
    Label59: TLabel;
    Label60: TLabel;
    Label79: TLabel;
    Label85: TLabel;
    Label87: TLabel;
    Label88: TLabel;
    Label89: TLabel;
    Label90: TLabel;
    Label91: TLabel;
    Label92: TLabel;
    Label93: TLabel;
    Label94: TLabel;
    Label95: TLabel;
    DBEdit1: TDBEdit;
    DBEdit2: TDBEdit;
    DBEdit3: TDBEdit;
    DBEdit4: TDBEdit;
    DBEdit5: TDBEdit;
    DBEdit6: TDBEdit;
    DBEdit7: TDBEdit;
    DBEdit8: TDBEdit;
    DBEdit9: TDBEdit;
    DBCheckBox11: TDBCheckBox;
    BitBtn2: TBitBtn;
    Label2: TLabel;
    Label3: TLabel;
    Bevel3: TBevel;
    DBCheckBox7: TDBCheckBox;
    Bevel2: TBevel;
    Bevel1: TBevel;
    EdLinhaAnt: TDBEdit;
    EdLinhasDep: TDBEdit;
    meCabecalho: TDBMemo;
    meRodape: TDBMemo;
    DlAddPrinter: TJvAddPrinterDialog;
    PrintSetup: TPBPrinterSetupDialog;
    Bevel4: TBevel;
    Label8: TLabel;
    CbImpressora: TDBComboBox;
    GroupBox4: TGroupBox;
    Label4: TLabel;
    EdTempoAlerta: TDBEdit;
    Label5: TLabel;
    Label7: TLabel;
    EdTempoAtualiza: TDBEdit;
    Label6: TLabel;
    cdModelo: TDBComboBox;
    TsVenda: TTabSheet;
    DBCheckBox5: TDBCheckBox;
    DBCheckBox6: TDBCheckBox;
    Bevel6: TBevel;
    Bevel7: TBevel;
    DBCheckBox1: TDBCheckBox;
    DBCheckBox4: TDBCheckBox;
    DBCheckBox3: TDBCheckBox;
    imParams: TImageList;
    GroupBox5: TGroupBox;
    Label14: TLabel;
    EdCodImpr: TJvDBComboEdit;
    EdImprDefault: TDBEdit;
    lbPadrao: TLabel;
    tsGaveta: TTabSheet;
    DBCheckBox17: TDBCheckBox;
    DBCheckBox2: TDBCheckBox;
    GrAcionamento: TDBRadioGroup;
    grSerial: TDBRadioGroup;
    GrModeloGav: TGroupBox;
    DBComboBox3: TDBComboBox;
    grImpressoraGav: TGroupBox;
    DBComboBox2: TDBComboBox;
    Label78: TLabel;
    EdTempoGav: TDBEdit;
    lbTempoGav: TLabel;
    gbBat: TGroupBox;
    Label48: TLabel;
    Label51: TLabel;
    Label50: TLabel;
    Label49: TLabel;
    EdDirGaveteiro: TDirectoryEdit;
    EdBatIni: TDBEdit;
    EdBatAber: TDBEdit;
    Bevel5: TBevel;
    DBCheckBox8: TDBCheckBox;
    rgImprComanda: TDBRadioGroup;
    DBCheckBox9: TDBCheckBox;
    GroupBox6: TGroupBox;
    Label15: TLabel;
    Label16: TLabel;
    EdReemissao: TEdit;
    EdSenha: TEdit;
    Label17: TLabel;
    EdNumPessoas: TDBEdit;
    RgPorta: TDBRadioGroup;
    Label20: TLabel;
    GroupBox7: TGroupBox;
    ckMesaAdic: TDBCheckBox;
    Label10: TLabel;
    EdPrcMesa: TDBEdit;
    Label13: TLabel;
    DBCheckBox10: TDBCheckBox;
    GroupBox8: TGroupBox;
    DBCheckBox12: TDBCheckBox;
    DBEdit10: TDBEdit;
    procedure BitBtn2Click(Sender : TObject);
    procedure SpeedButton2Click(Sender : TObject);
    procedure sbPadroesClick(Sender : TObject);
    procedure EdImpressoraButtonClick(Sender : TObject);
    procedure CbImpressoraChange(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure EdCodImprButtonClick(Sender : TObject);
    procedure EdDirGaveteiroChange(Sender : TObject);
    procedure GrAcionamentoClick(Sender : TObject);
    procedure EdSenhaExit(Sender : TObject);
    procedure EdReemissaoExit(Sender : TObject);
    procedure meCabecalhoEnter(Sender : TObject);
    procedure meCabecalhoExit(Sender : TObject);
    procedure meRodapeExit(Sender : TObject);
    procedure meRodapeEnter(Sender : TObject);
    procedure _PROC_0067495E(Sender : TObject);
    procedure _PROC_00674975(Sender : TObject);
    procedure _PROC_00674F5C(Sender : TObject);
    procedure _PROC_00674F8C(Sender : TObject);
    procedure _PROC_00674F94(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmParametros: TFrmParametros;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmParametros.BitBtn2Click(Sender : TObject);
begin
(*
00674664   55                     push    ebp
00674665   8BEC                   mov     ebp, esp
00674667   33C9                   xor     ecx, ecx
00674669   51                     push    ecx
0067466A   51                     push    ecx
0067466B   51                     push    ecx
0067466C   51                     push    ecx
0067466D   51                     push    ecx
0067466E   51                     push    ecx
0067466F   53                     push    ebx
00674670   8BD8                   mov     ebx, eax
00674672   33C0                   xor     eax, eax
00674674   55                     push    ebp
00674675   68A4476700             push    $006747A4

***** TRY
|
0067467A   64FF30                 push    dword ptr fs:[eax]
0067467D   648920                 mov     fs:[eax], esp
00674680   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmParametros.EdSenha : TEdit
|
00674683   8B83D0040000           mov     eax, [ebx+$04D0]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674689   E83EF0E1FF             call    004936CC
0067468E   837DFC00               cmp     dword ptr [ebp-$04], +$00
00674692   7452                   jz      006746E6
00674694   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674699   8B00                   mov     eax, [eax]
0067469B   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
0067469E   E8956DE7FF             call    004EB438
006746A3   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TFrmParametros.EdSenha : TEdit
|
006746A6   8B83D0040000           mov     eax, [ebx+$04D0]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
006746AC   E81BF0E1FF             call    004936CC
006746B1   8B45F4                 mov     eax, [ebp-$0C]
006746B4   8D55F8                 lea     edx, [ebp-$08]

* Reference to : TFrmInfoAtu._PROC_007A3758()
|
006746B7   E89CF01200             call    007A3758
006746BC   8B55F8                 mov     edx, [ebp-$08]
006746BF   A17CB37D00             mov     eax, dword ptr [$007DB37C]
006746C4   8B00                   mov     eax, [eax]
006746C6   8B80D8010000           mov     eax, [eax+$01D8]
006746CC   8B08                   mov     ecx, [eax]
006746CE   FF91B0000000           call    dword ptr [ecx+$00B0]
006746D4   A17CB37D00             mov     eax, dword ptr [$007DB37C]
006746D9   8B00                   mov     eax, [eax]
006746DB   8B4064                 mov     eax, [eax+$64]
006746DE   8B10                   mov     edx, [eax]
006746E0   FF924C020000           call    dword ptr [edx+$024C]
006746E6   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TFrmParametros.EdReemissao : TEdit
|
006746E9   8B83CC040000           mov     eax, [ebx+$04CC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
006746EF   E8D8EFE1FF             call    004936CC
006746F4   837DF000               cmp     dword ptr [ebp-$10], +$00
006746F8   7452                   jz      0067474C
006746FA   A17CB37D00             mov     eax, dword ptr [$007DB37C]
006746FF   8B00                   mov     eax, [eax]
00674701   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
00674704   E82F6DE7FF             call    004EB438
00674709   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TFrmParametros.EdReemissao : TEdit
|
0067470C   8B83CC040000           mov     eax, [ebx+$04CC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674712   E8B5EFE1FF             call    004936CC
00674717   8B45E8                 mov     eax, [ebp-$18]
0067471A   8D55EC                 lea     edx, [ebp-$14]

* Reference to : TFrmInfoAtu._PROC_007A3758()
|
0067471D   E836F01200             call    007A3758
00674722   8B55EC                 mov     edx, [ebp-$14]
00674725   A17CB37D00             mov     eax, dword ptr [$007DB37C]
0067472A   8B00                   mov     eax, [eax]
0067472C   8B8034020000           mov     eax, [eax+$0234]
00674732   8B08                   mov     ecx, [eax]
00674734   FF91B0000000           call    dword ptr [ecx+$00B0]
0067473A   A17CB37D00             mov     eax, dword ptr [$007DB37C]
0067473F   8B00                   mov     eax, [eax]
00674741   8B4064                 mov     eax, [eax+$64]
00674744   8B10                   mov     edx, [eax]
00674746   FF924C020000           call    dword ptr [edx+$024C]
0067474C   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674751   8B00                   mov     eax, [eax]
00674753   8B4064                 mov     eax, [eax+$64]
00674756   33C9                   xor     ecx, ecx
00674758   33D2                   xor     edx, edx

* Reference to: DBClient.TCustomClientDataSet.SaveToFile(TCustomClientDataSet;AnsiString;TDataPacketFormat);
|
0067475A   E8E52BE8FF             call    004F7344

* Possible String Reference to: 'Os par‚metros foram salvos...'
|
0067475F   B8B8476700             mov     eax, $006747B8

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00674764   E8BBF4DCFF             call    00443C24
00674769   33C0                   xor     eax, eax
0067476B   5A                     pop     edx
0067476C   59                     pop     ecx
0067476D   59                     pop     ecx
0067476E   648910                 mov     fs:[eax], edx

****** FINALLY
|
00674771   68AB476700             push    $006747AB
00674776   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.@LStrClr(void;void);
|
00674779   E81E0DD9FF             call    0040549C
0067477E   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
00674781   E8160DD9FF             call    0040549C
00674786   8D45F0                 lea     eax, [ebp-$10]
00674789   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
0067478E   E82D0DD9FF             call    004054C0
00674793   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.@LStrClr(void;void);
|
00674796   E8010DD9FF             call    0040549C
0067479B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
0067479E   E8F90CD9FF             call    0040549C
006747A3   C3                     ret


* Reference to: System.@HandleFinally;
|
006747A4   E98F05D9FF             jmp     00404D38
006747A9   EBCB                   jmp     00674776

****** END
|
006747AB   5B                     pop     ebx
006747AC   8BE5                   mov     esp, ebp
006747AE   5D                     pop     ebp
006747AF   C3                     ret

*)
end;

procedure TFrmParametros.SpeedButton2Click(Sender : TObject);
begin
(*
006747D8   55                     push    ebp
006747D9   8BEC                   mov     ebp, esp

* Reference to control TFrmParametros.DlAddPrinter : TJvAddPrinterDialog
|
006747DB   8B80F4030000           mov     eax, [eax+$03F4]
006747E1   8B10                   mov     edx, [eax]

* Possible reference to virtual method TJvAddPrinterDialog.OFFS_30
|
006747E3   FF5230                 call    dword ptr [edx+$30]
006747E6   5D                     pop     ebp
006747E7   C3                     ret

*)
end;

procedure TFrmParametros.sbPadroesClick(Sender : TObject);
begin
(*
006747E8   55                     push    ebp
006747E9   8BEC                   mov     ebp, esp
006747EB   53                     push    ebx
006747EC   8B1D7CB37D00           mov     ebx, [$007DB37C]
006747F2   8B03                   mov     eax, [ebx]

* Reference to field TFrmParametros.WindowText : PChar
|
006747F4   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
006747F7   E83C6CE7FF             call    004EB438
006747FC   8B03                   mov     eax, [ebx]

* Reference to field PChar.OFFS_0064
|
006747FE   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TMargem'
|
00674801   BA10496700             mov     edx, $00674910

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00674806   E8F953E7FF             call    004E9C04
0067480B   BA02000000             mov     edx, $00000002
00674810   8B08                   mov     ecx, [eax]
00674812   FF91A8000000           call    dword ptr [ecx+$00A8]
00674818   8B03                   mov     eax, [ebx]
0067481A   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TCodProd'
|
0067481D   BA20496700             mov     edx, $00674920

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00674822   E8DD53E7FF             call    004E9C04
00674827   BA09000000             mov     edx, $00000009
0067482C   8B08                   mov     ecx, [eax]
0067482E   FF91A8000000           call    dword ptr [ecx+$00A8]
00674834   8B03                   mov     eax, [ebx]
00674836   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TVolumes'
|
00674839   BA34496700             mov     edx, $00674934

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0067483E   E8C153E7FF             call    004E9C04
00674843   BA09000000             mov     edx, $00000009
00674848   8B08                   mov     ecx, [eax]
0067484A   FF91A8000000           call    dword ptr [ecx+$00A8]
00674850   8B03                   mov     eax, [ebx]
00674852   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TQuantidade'
|
00674855   BA48496700             mov     edx, $00674948

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
0067485A   E8A553E7FF             call    004E9C04
0067485F   BA09000000             mov     edx, $00000009
00674864   8B08                   mov     ecx, [eax]
00674866   FF91A8000000           call    dword ptr [ecx+$00A8]
0067486C   8B03                   mov     eax, [ebx]
0067486E   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TUnidMed'
|
00674871   BA5C496700             mov     edx, $0067495C

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00674876   E88953E7FF             call    004E9C04
0067487B   BA03000000             mov     edx, $00000003
00674880   8B08                   mov     ecx, [eax]
00674882   FF91A8000000           call    dword ptr [ecx+$00A8]
00674888   8B03                   mov     eax, [ebx]
0067488A   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TVlrUnit'
|
0067488D   BA70496700             mov     edx, $00674970

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00674892   E86D53E7FF             call    004E9C04
00674897   BA09000000             mov     edx, $00000009
0067489C   8B08                   mov     ecx, [eax]
0067489E   FF91A8000000           call    dword ptr [ecx+$00A8]
006748A4   8B03                   mov     eax, [ebx]
006748A6   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TVlrTotal'
|
006748A9   BA84496700             mov     edx, $00674984

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006748AE   E85153E7FF             call    004E9C04
006748B3   BA0C000000             mov     edx, $0000000C
006748B8   8B08                   mov     ecx, [eax]
006748BA   FF91A8000000           call    dword ptr [ecx+$00A8]
006748C0   8B03                   mov     eax, [ebx]
006748C2   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TDescricao'
|
006748C5   BA98496700             mov     edx, $00674998

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006748CA   E83553E7FF             call    004E9C04
006748CF   BA2A000000             mov     edx, $0000002A
006748D4   8B08                   mov     ecx, [eax]
006748D6   FF91A8000000           call    dword ptr [ecx+$00A8]
006748DC   8B03                   mov     eax, [ebx]
006748DE   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'TPagtos'
|
006748E1   BAAC496700             mov     edx, $006749AC

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006748E6   E81953E7FF             call    004E9C04
006748EB   BA1E000000             mov     edx, $0000001E
006748F0   8B08                   mov     ecx, [eax]
006748F2   FF91A8000000           call    dword ptr [ecx+$00A8]
006748F8   8B03                   mov     eax, [ebx]
006748FA   8B4064                 mov     eax, [eax+$64]
006748FD   8B10                   mov     edx, [eax]
006748FF   FF924C020000           call    dword ptr [edx+$024C]
00674905   5B                     pop     ebx
00674906   5D                     pop     ebp
00674907   C3                     ret

*)
end;

procedure TFrmParametros.EdImpressoraButtonClick(Sender : TObject);
begin
(*
006749B4   55                     push    ebp
006749B5   8BEC                   mov     ebp, esp
006749B7   53                     push    ebx
006749B8   8BD8                   mov     ebx, eax

* Reference to control TFrmParametros.PrintSetup : TPBPrinterSetupDialog
|
006749BA   8B83F8030000           mov     eax, [ebx+$03F8]
006749C0   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPBPrinterSetupDialog.OFFS_3C
|
006749C2   FF523C                 call    dword ptr [edx+$3C]
006749C5   84C0                   test    al, al
006749C7   743A                   jz      00674A03
006749C9   A17CB37D00             mov     eax, dword ptr [$007DB37C]
006749CE   8B00                   mov     eax, [eax]
006749D0   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
006749D3   E8606AE7FF             call    004EB438
006749D8   A17CB37D00             mov     eax, dword ptr [$007DB37C]
006749DD   8B00                   mov     eax, [eax]
006749DF   8B4064                 mov     eax, [eax+$64]

* Possible String Reference to: 'ImprWin'
|
006749E2   BA104A6700             mov     edx, $00674A10

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
006749E7   E81852E7FF             call    004E9C04

* Reference to control TFrmParametros.PrintSetup : TPBPrinterSetupDialog
|
006749EC   8B93F8030000           mov     edx, [ebx+$03F8]

* Reference to field TPBPrinterSetupDialog.OFFS_0310
|
006749F2   8B9210030000           mov     edx, [edx+$0310]
006749F8   8B5234                 mov     edx, [edx+$34]
006749FB   8B08                   mov     ecx, [eax]
006749FD   FF91B0000000           call    dword ptr [ecx+$00B0]
00674A03   5B                     pop     ebx
00674A04   5D                     pop     ebp
00674A05   C3                     ret

*)
end;

procedure TFrmParametros.CbImpressoraChange(Sender : TObject);
begin
(*
00674A18   55                     push    ebp
00674A19   8BEC                   mov     ebp, esp
00674A1B   6A00                   push    $00
00674A1D   6A00                   push    $00
00674A1F   53                     push    ebx
00674A20   8BD8                   mov     ebx, eax
00674A22   33C0                   xor     eax, eax
00674A24   55                     push    ebp
00674A25   689D4A6700             push    $00674A9D

***** TRY
|
00674A2A   64FF30                 push    dword ptr fs:[eax]
00674A2D   648920                 mov     fs:[eax], esp
00674A30   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmParametros.CbImpressora : TDBComboBox
|
00674A33   8B8304040000           mov     eax, [ebx+$0404]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674A39   E88EECE1FF             call    004936CC
00674A3E   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: 'bematech'
|
00674A41   BAB44A6700             mov     edx, $00674AB4

* Reference to: System.@LStrCmp;
|
00674A46   E85D0ED9FF             call    004058A8
00674A4B   0F94C2                 setz    dl

* Reference to control TFrmParametros.cdModelo : TDBComboBox
|
00674A4E   8B8324040000           mov     eax, [ebx+$0424]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674A54   E893EBE1FF             call    004935EC
00674A59   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TFrmParametros.CbImpressora : TDBComboBox
|
00674A5C   8B8304040000           mov     eax, [ebx+$0404]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674A62   E865ECE1FF             call    004936CC
00674A67   8B45F8                 mov     eax, [ebp-$08]

* Possible String Reference to: 'bematech'
|
00674A6A   BAB44A6700             mov     edx, $00674AB4

* Reference to: System.@LStrCmp;
|
00674A6F   E8340ED9FF             call    004058A8
00674A74   0F94C2                 setz    dl

* Reference to control TFrmParametros.lbPadrao : TLabel
|
00674A77   8B835C040000           mov     eax, [ebx+$045C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674A7D   E86AEBE1FF             call    004935EC
00674A82   33C0                   xor     eax, eax
00674A84   5A                     pop     edx
00674A85   59                     pop     ecx
00674A86   59                     pop     ecx
00674A87   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]√'
|
00674A8A   68A44A6700             push    $00674AA4
00674A8F   8D45F8                 lea     eax, [ebp-$08]
00674A92   BA02000000             mov     edx, $00000002

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00674A97   E8240AD9FF             call    004054C0
00674A9C   C3                     ret


* Reference to: System.@HandleFinally;
|
00674A9D   E99602D9FF             jmp     00404D38
00674AA2   EBEB                   jmp     00674A8F

****** END
|
00674AA4   5B                     pop     ebx
00674AA5   59                     pop     ecx
00674AA6   59                     pop     ecx
00674AA7   5D                     pop     ebp
00674AA8   C3                     ret

*)
end;

procedure TFrmParametros.FormShow(Sender : TObject);
begin
(*
00674AC0   55                     push    ebp
00674AC1   8BEC                   mov     ebp, esp
00674AC3   33C9                   xor     ecx, ecx
00674AC5   51                     push    ecx
00674AC6   51                     push    ecx
00674AC7   51                     push    ecx
00674AC8   51                     push    ecx
00674AC9   51                     push    ecx
00674ACA   51                     push    ecx
00674ACB   53                     push    ebx
00674ACC   8BD8                   mov     ebx, eax
00674ACE   33C0                   xor     eax, eax
00674AD0   55                     push    ebp
00674AD1   68A24B6700             push    $00674BA2

***** TRY
|
00674AD6   64FF30                 push    dword ptr fs:[eax]
00674AD9   648920                 mov     fs:[eax], esp
00674ADC   8BC3                   mov     eax, ebx

* Reference to : TFrmInfoAtu._PROC_007ADC3C()
|
00674ADE   E859911300             call    007ADC3C
00674AE3   8BD3                   mov     edx, ebx
00674AE5   8BC3                   mov     eax, ebx

* Reference to : TFrmParametros.CbImpressoraChange()
|
00674AE7   E82CFFFFFF             call    00674A18
00674AEC   8BD3                   mov     edx, ebx
00674AEE   8BC3                   mov     eax, ebx

* Reference to : TFrmParametros.GrAcionamentoClick()
|
00674AF0   E857020000             call    00674D4C
00674AF5   8D55FC                 lea     edx, [ebp-$04]
00674AF8   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674AFD   8B00                   mov     eax, [eax]
00674AFF   8B80D8010000           mov     eax, [eax+$01D8]
00674B05   8B08                   mov     ecx, [eax]
00674B07   FF5160                 call    dword ptr [ecx+$60]
00674B0A   837DFC00               cmp     dword ptr [ebp-$04], +$00
00674B0E   742E                   jz      00674B3E
00674B10   8D55F4                 lea     edx, [ebp-$0C]
00674B13   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674B18   8B00                   mov     eax, [eax]
00674B1A   8B80D8010000           mov     eax, [eax+$01D8]
00674B20   8B08                   mov     ecx, [eax]
00674B22   FF5160                 call    dword ptr [ecx+$60]
00674B25   8B45F4                 mov     eax, [ebp-$0C]
00674B28   8D55F8                 lea     edx, [ebp-$08]

* Reference to : TFrmInfoAtu._PROC_007A3638()
|
00674B2B   E808EB1200             call    007A3638
00674B30   8B55F8                 mov     edx, [ebp-$08]

* Reference to control TFrmParametros.EdSenha : TEdit
|
00674B33   8B83D0040000           mov     eax, [ebx+$04D0]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00674B39   E8BEEBE1FF             call    004936FC
00674B3E   8D55F0                 lea     edx, [ebp-$10]
00674B41   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674B46   8B00                   mov     eax, [eax]
00674B48   8B8034020000           mov     eax, [eax+$0234]
00674B4E   8B08                   mov     ecx, [eax]
00674B50   FF5160                 call    dword ptr [ecx+$60]
00674B53   837DF000               cmp     dword ptr [ebp-$10], +$00
00674B57   742E                   jz      00674B87
00674B59   8D55E8                 lea     edx, [ebp-$18]
00674B5C   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674B61   8B00                   mov     eax, [eax]
00674B63   8B8034020000           mov     eax, [eax+$0234]
00674B69   8B08                   mov     ecx, [eax]
00674B6B   FF5160                 call    dword ptr [ecx+$60]
00674B6E   8B45E8                 mov     eax, [ebp-$18]
00674B71   8D55EC                 lea     edx, [ebp-$14]

* Reference to : TFrmInfoAtu._PROC_007A3638()
|
00674B74   E8BFEA1200             call    007A3638
00674B79   8B55EC                 mov     edx, [ebp-$14]

* Reference to control TFrmParametros.EdReemissao : TEdit
|
00674B7C   8B83CC040000           mov     eax, [ebx+$04CC]

* Reference to: Controls.TControl.SetText(TControl;TCaption);
|
00674B82   E875EBE1FF             call    004936FC
00674B87   33C0                   xor     eax, eax
00674B89   5A                     pop     edx
00674B8A   59                     pop     ecx
00674B8B   59                     pop     ecx
00674B8C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√ã¿UãÏÉƒÏ3…âMÏ3¿Uh`Lg'
|
00674B8F   68A94B6700             push    $00674BA9
00674B94   8D45E8                 lea     eax, [ebp-$18]
00674B97   BA06000000             mov     edx, $00000006

* Reference to: System.@LStrArrayClr(void;void;Integer);
|
00674B9C   E81F09D9FF             call    004054C0
00674BA1   C3                     ret


* Reference to: System.@HandleFinally;
|
00674BA2   E99101D9FF             jmp     00404D38
00674BA7   EBEB                   jmp     00674B94

****** END
|
00674BA9   5B                     pop     ebx
00674BAA   8BE5                   mov     esp, ebp
00674BAC   5D                     pop     ebp
00674BAD   C3                     ret

*)
end;

procedure TFrmParametros.EdCodImprButtonClick(Sender : TObject);
begin
(*
00674BB0   55                     push    ebp
00674BB1   8BEC                   mov     ebp, esp
00674BB3   83C4EC                 add     esp, -$14
00674BB6   33C9                   xor     ecx, ecx
00674BB8   894DEC                 mov     [ebp-$14], ecx
00674BBB   33C0                   xor     eax, eax
00674BBD   55                     push    ebp

* Possible String Reference to: 'È”'
|
00674BBE   68604C6700             push    $00674C60

***** TRY
|
00674BC3   64FF30                 push    dword ptr fs:[eax]
00674BC6   648920                 mov     fs:[eax], esp

* Possible String Reference to: 'cÛdigo'
|
00674BC9   B8744C6700             mov     eax, $00674C74
00674BCE   8945F8                 mov     [ebp-$08], eax

* Possible String Reference to: 'Impressora'
|
00674BD1   B8844C6700             mov     eax, $00674C84
00674BD6   8945FC                 mov     [ebp-$04], eax
00674BD9   8D45F8                 lea     eax, [ebp-$08]
00674BDC   50                     push    eax
00674BDD   6A01                   push    $01
00674BDF   6A00                   push    $00

* Possible String Reference to: 'CODIMPR'
|
00674BE1   B8984C6700             mov     eax, $00674C98
00674BE6   8945F0                 mov     [ebp-$10], eax

* Possible String Reference to: 'DESCRICAO'
|
00674BE9   B8A84C6700             mov     eax, $00674CA8
00674BEE   8945F4                 mov     [ebp-$0C], eax
00674BF1   8D55F0                 lea     edx, [ebp-$10]
00674BF4   B901000000             mov     ecx, $00000001

* Possible String Reference to: 'IMPRGRILL'
|
00674BF9   B8BC4C6700             mov     eax, $00674CBC

|
00674BFE   E85146FCFF             call    00639254
00674C03   84C0                   test    al, al
00674C05   7443                   jz      00674C4A
00674C07   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674C0C   8B00                   mov     eax, [eax]
00674C0E   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
00674C11   E82268E7FF             call    004EB438
00674C16   A1689F7D00             mov     eax, dword ptr [$007D9F68]
00674C1B   8B00                   mov     eax, [eax]
00674C1D   8B4060                 mov     eax, [eax+$60]

* Possible String Reference to: 'CODIMPR'
|
00674C20   BA984C6700             mov     edx, $00674C98

* Reference to: DB.TDataSet.FieldByName(TDataSet;AnsiString):TField;
|
00674C25   E8DA4FE7FF             call    004E9C04
00674C2A   8D55EC                 lea     edx, [ebp-$14]
00674C2D   8B08                   mov     ecx, [eax]
00674C2F   FF5160                 call    dword ptr [ecx+$60]
00674C32   8B55EC                 mov     edx, [ebp-$14]
00674C35   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674C3A   8B00                   mov     eax, [eax]
00674C3C   8B80E8010000           mov     eax, [eax+$01E8]
00674C42   8B08                   mov     ecx, [eax]
00674C44   FF91B0000000           call    dword ptr [ecx+$00B0]
00674C4A   33C0                   xor     eax, eax
00674C4C   5A                     pop     edx
00674C4D   59                     pop     ecx
00674C4E   59                     pop     ecx
00674C4F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
00674C52   68674C6700             push    $00674C67
00674C57   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.@LStrClr(void;void);
|
00674C5A   E83D08D9FF             call    0040549C
00674C5F   C3                     ret


* Reference to: System.@HandleFinally;
|
00674C60   E9D300D9FF             jmp     00404D38
00674C65   EBF0                   jmp     00674C57

****** END
|
00674C67   8BE5                   mov     esp, ebp
00674C69   5D                     pop     ebp
00674C6A   C3                     ret

*)
end;

procedure TFrmParametros.EdDirGaveteiroChange(Sender : TObject);
begin
(*
00674CC8   55                     push    ebp
00674CC9   8BEC                   mov     ebp, esp
00674CCB   6A00                   push    $00
00674CCD   53                     push    ebx
00674CCE   56                     push    esi
00674CCF   8BD8                   mov     ebx, eax
00674CD1   33C0                   xor     eax, eax
00674CD3   55                     push    ebp

* Possible String Reference to: 'ÈˆˇÿˇÎ^[Y]√ç@'
|
00674CD4   683D4D6700             push    $00674D3D

***** TRY
|
00674CD9   64FF30                 push    dword ptr fs:[eax]
00674CDC   648920                 mov     fs:[eax], esp

* Reference to control TFrmParametros.EdDirGaveteiro : TDirectoryEdit
|
00674CDF   8B83A4040000           mov     eax, [ebx+$04A4]
00674CE5   66BEB5FF               mov     si, $FFB5

* Reference to: System.@CallDynaInst;
|
00674CE9   E8B2FAD8FF             call    004047A0
00674CEE   84C0                   test    al, al
00674CF0   7435                   jz      00674D27
00674CF2   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674CF7   8B00                   mov     eax, [eax]
00674CF9   8B4064                 mov     eax, [eax+$64]

* Reference to: DB.TDataSet.Edit(TDataSet);
|
00674CFC   E83767E7FF             call    004EB438
00674D01   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmParametros.EdDirGaveteiro : TDirectoryEdit
|
00674D04   8B83A4040000           mov     eax, [ebx+$04A4]

* Reference to: Mask.TCustomMaskEdit.GetText(TCustomMaskEdit):TMaskedText;
|
00674D0A   E82D92E8FF             call    004FDF3C
00674D0F   8B55FC                 mov     edx, [ebp-$04]
00674D12   A17CB37D00             mov     eax, dword ptr [$007DB37C]
00674D17   8B00                   mov     eax, [eax]
00674D19   8B800C020000           mov     eax, [eax+$020C]
00674D1F   8B08                   mov     ecx, [eax]
00674D21   FF91B0000000           call    dword ptr [ecx+$00B0]
00674D27   33C0                   xor     eax, eax
00674D29   5A                     pop     edx
00674D2A   59                     pop     ecx
00674D2B   59                     pop     ecx
00674D2C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]√ç@'
|
00674D2F   68444D6700             push    $00674D44
00674D34   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00674D37   E86007D9FF             call    0040549C
00674D3C   C3                     ret


* Reference to: System.@HandleFinally;
|
00674D3D   E9F6FFD8FF             jmp     00404D38
00674D42   EBF0                   jmp     00674D34

****** END
|
00674D44   5E                     pop     esi
00674D45   5B                     pop     ebx
00674D46   59                     pop     ecx
00674D47   5D                     pop     ebp
00674D48   C3                     ret

*)
end;

procedure TFrmParametros.GrAcionamentoClick(Sender : TObject);
begin
(*
00674D4C   55                     push    ebp
00674D4D   8BEC                   mov     ebp, esp
00674D4F   53                     push    ebx
00674D50   8BD8                   mov     ebx, eax

* Reference to control TFrmParametros.GrAcionamento : TDBRadioGroup
|
00674D52   8B836C040000           mov     eax, [ebx+$046C]

* Reference to field TDBRadioGroup.ItemIndex : Integer
|
00674D58   8B8018020000           mov     eax, [eax+$0218]
00674D5E   83E801                 sub     eax, +$01
00674D61   720A                   jb      00674D6D
00674D63   743F                   jz      00674DA4
00674D65   48                     dec     eax
00674D66   7473                   jz      00674DDB
00674D68   E9A2000000             jmp     00674E0F
00674D6D   33D2                   xor     edx, edx

* Reference to control TFrmParametros.gbBat : TGroupBox
|
00674D6F   8B8390040000           mov     eax, [ebx+$0490]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674D75   E872E8E1FF             call    004935EC
00674D7A   33D2                   xor     edx, edx

* Reference to control TFrmParametros.grSerial : TDBRadioGroup
|
00674D7C   8B8370040000           mov     eax, [ebx+$0470]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674D82   E865E8E1FF             call    004935EC
00674D87   B201                   mov     dl, $01

* Reference to control TFrmParametros.grImpressoraGav : TGroupBox
|
00674D89   8B837C040000           mov     eax, [ebx+$047C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674D8F   E858E8E1FF             call    004935EC
00674D94   33D2                   xor     edx, edx

* Reference to control TFrmParametros.GrModeloGav : TGroupBox
|
00674D96   8B8374040000           mov     eax, [ebx+$0474]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674D9C   E84BE8E1FF             call    004935EC
00674DA1   5B                     pop     ebx
00674DA2   5D                     pop     ebp
00674DA3   C3                     ret

00674DA4   33D2                   xor     edx, edx
00674DA6   8B8390040000           mov     eax, [ebx+$0490]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DAC   E83BE8E1FF             call    004935EC
00674DB1   B201                   mov     dl, $01
00674DB3   8B8370040000           mov     eax, [ebx+$0470]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DB9   E82EE8E1FF             call    004935EC
00674DBE   33D2                   xor     edx, edx
00674DC0   8B837C040000           mov     eax, [ebx+$047C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DC6   E821E8E1FF             call    004935EC
00674DCB   B201                   mov     dl, $01
00674DCD   8B8374040000           mov     eax, [ebx+$0474]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DD3   E814E8E1FF             call    004935EC
00674DD8   5B                     pop     ebx
00674DD9   5D                     pop     ebp
00674DDA   C3                     ret

00674DDB   B201                   mov     dl, $01
00674DDD   8B8390040000           mov     eax, [ebx+$0490]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DE3   E804E8E1FF             call    004935EC
00674DE8   33D2                   xor     edx, edx
00674DEA   8B8370040000           mov     eax, [ebx+$0470]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DF0   E8F7E7E1FF             call    004935EC
00674DF5   33D2                   xor     edx, edx
00674DF7   8B837C040000           mov     eax, [ebx+$047C]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674DFD   E8EAE7E1FF             call    004935EC
00674E02   33D2                   xor     edx, edx
00674E04   8B8374040000           mov     eax, [ebx+$0474]

* Reference to: Controls.TControl.SetVisible(TControl;Boolean);
|
00674E0A   E8DDE7E1FF             call    004935EC
00674E0F   5B                     pop     ebx
00674E10   5D                     pop     ebp
00674E11   C3                     ret

*)
end;

procedure TFrmParametros.EdSenhaExit(Sender : TObject);
begin
(*
00674E14   55                     push    ebp
00674E15   8BEC                   mov     ebp, esp
00674E17   6A00                   push    $00
00674E19   53                     push    ebx
00674E1A   8BD8                   mov     ebx, eax
00674E1C   33C0                   xor     eax, eax
00674E1E   55                     push    ebp

* Possible String Reference to: 'ÈŒ˛ÿˇÎ[Y]√ˇˇˇˇ%'
|
00674E1F   68654E6700             push    $00674E65

***** TRY
|
00674E24   64FF30                 push    dword ptr fs:[eax]
00674E27   648920                 mov     fs:[eax], esp
00674E2A   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmParametros.EdSenha : TEdit
|
00674E2D   8B83D0040000           mov     eax, [ebx+$04D0]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674E33   E894E8E1FF             call    004936CC
00674E38   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
00674E3B   E81C09D9FF             call    0040575C
00674E40   83F805                 cmp     eax, +$05
00674E43   740A                   jz      00674E4F

* Possible String Reference to: 'A senha necessita ter 5 caracteres.
|                                ..'
|
00674E45   B8784E6700             mov     eax, $00674E78

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00674E4A   E8D5EDDCFF             call    00443C24
00674E4F   33C0                   xor     eax, eax
00674E51   5A                     pop     edx
00674E52   59                     pop     ecx
00674E53   59                     pop     ecx
00674E54   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ˇˇˇˇ%'
|
00674E57   686C4E6700             push    $00674E6C
00674E5C   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00674E5F   E83806D9FF             call    0040549C
00674E64   C3                     ret


* Reference to: System.@HandleFinally;
|
00674E65   E9CEFED8FF             jmp     00404D38
00674E6A   EBF0                   jmp     00674E5C

****** END
|
00674E6C   5B                     pop     ebx
00674E6D   59                     pop     ecx
00674E6E   5D                     pop     ebp
00674E6F   C3                     ret

*)
end;

procedure TFrmParametros.EdReemissaoExit(Sender : TObject);
begin
(*
00674EA0   55                     push    ebp
00674EA1   8BEC                   mov     ebp, esp
00674EA3   6A00                   push    $00
00674EA5   53                     push    ebx
00674EA6   8BD8                   mov     ebx, eax
00674EA8   33C0                   xor     eax, eax
00674EAA   55                     push    ebp

* Possible String Reference to: 'ÈB˛ÿˇÎ[Y]√ˇˇˇˇ%'
|
00674EAB   68F14E6700             push    $00674EF1

***** TRY
|
00674EB0   64FF30                 push    dword ptr fs:[eax]
00674EB3   648920                 mov     fs:[eax], esp
00674EB6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TFrmParametros.EdReemissao : TEdit
|
00674EB9   8B83CC040000           mov     eax, [ebx+$04CC]

* Reference to: Controls.TControl.GetText(TControl):TCaption;
|
00674EBF   E808E8E1FF             call    004936CC
00674EC4   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.@LStrLen(String):Integer;
|
00674EC7   E89008D9FF             call    0040575C
00674ECC   83F805                 cmp     eax, +$05
00674ECF   740A                   jz      00674EDB

* Possible String Reference to: 'A senha necessita ter 5 caracteres.
|                                ..'
|
00674ED1   B8044F6700             mov     eax, $00674F04

* Reference to: Dialogs.ShowMessage(AnsiString);
|
00674ED6   E849EDDCFF             call    00443C24
00674EDB   33C0                   xor     eax, eax
00674EDD   5A                     pop     edx
00674EDE   59                     pop     ecx
00674EDF   59                     pop     ecx
00674EE0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ˇˇˇˇ%'
|
00674EE3   68F84E6700             push    $00674EF8
00674EE8   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.@LStrClr(void;void);
|
00674EEB   E8AC05D9FF             call    0040549C
00674EF0   C3                     ret


* Reference to: System.@HandleFinally;
|
00674EF1   E942FED8FF             jmp     00404D38
00674EF6   EBF0                   jmp     00674EE8

****** END
|
00674EF8   5B                     pop     ebx
00674EF9   59                     pop     ecx
00674EFA   5D                     pop     ebp
00674EFB   C3                     ret

*)
end;

procedure TFrmParametros.meCabecalhoEnter(Sender : TObject);
begin
(*
00674F2C   55                     push    ebp
00674F2D   8BEC                   mov     ebp, esp

|
00674F2F   E80C101300             call    007A5F40
00674F34   5D                     pop     ebp
00674F35   C3                     ret

*)
end;

procedure TFrmParametros.meCabecalhoExit(Sender : TObject);
begin
(*
00674F38   55                     push    ebp
00674F39   8BEC                   mov     ebp, esp

|
00674F3B   E818101300             call    007A5F58
00674F40   5D                     pop     ebp
00674F41   C3                     ret

*)
end;

procedure TFrmParametros.meRodapeExit(Sender : TObject);
begin
(*
00674F50   55                     push    ebp
00674F51   8BEC                   mov     ebp, esp

|
00674F53   E800101300             call    007A5F58
00674F58   5D                     pop     ebp
00674F59   C3                     ret

*)
end;

procedure TFrmParametros.meRodapeEnter(Sender : TObject);
begin
(*
00674F44   55                     push    ebp
00674F45   8BEC                   mov     ebp, esp

|
00674F47   E8F40F1300             call    007A5F40
00674F4C   5D                     pop     ebp
00674F4D   C3                     ret

*)
end;

procedure TFrmParametros._PROC_0067495E(Sender : TObject);
begin
(*
0067495E   6E                     outsb
0067495F   69644D6564000000       imul    esp, [ebp+ecx*2+$65], $00000064
00674967   00FF                   add     bh, bh
00674969   FFFF                   DB  $FF, $FF  //      
0067496B   FF08                   dec     dword ptr [eax]
0067496D   0000                   add     [eax], al

*)
end;

procedure TFrmParametros._PROC_00674975(Sender : TObject);
begin
(*
00674975   6E                     outsb
00674976   697400000000FFFF       imul    esi, [eax+eax+$00], $FFFF0000
0067497E   FFFF                   DB  $FF, $FF  //      
00674980   0900                   or      [eax], eax
00674982   0000                   add     [eax], al

*)
end;

procedure TFrmParametros._PROC_00674F5C(Sender : TObject);
begin
(*
00674F5C   55                     push    ebp
00674F5D   8BEC                   mov     ebp, esp
00674F5F   33C0                   xor     eax, eax
00674F61   55                     push    ebp

* Possible String Reference to: 'È≤˝ÿˇÎ¯]√ã¿É-ÄÈ}'
|
00674F62   68814F6700             push    $00674F81

***** TRY
|
00674F67   64FF30                 push    dword ptr fs:[eax]
00674F6A   648920                 mov     fs:[eax], esp
00674F6D   FF0580E97D00           inc     dword ptr [$007DE980]
00674F73   33C0                   xor     eax, eax
00674F75   5A                     pop     edx
00674F76   59                     pop     ecx
00674F77   59                     pop     ecx
00674F78   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-ÄÈ}'
|
00674F7B   68884F6700             push    $00674F88
00674F80   C3                     ret


* Reference to: System.@HandleFinally;
|
00674F81   E9B2FDD8FF             jmp     00404D38
00674F86   EBF8                   jmp     00674F80

****** END
|
00674F88   5D                     pop     ebp
00674F89   C3                     ret

*)
end;

procedure TFrmParametros._PROC_00674F8C(Sender : TObject);
begin
(*
00674F8C   832D80E97D0001         sub     dword ptr [$007DE980], +$01
00674F93   C3                     ret

*)
end;

procedure TFrmParametros._PROC_00674F94(Sender : TObject);
begin
(*
00674F94   E04F                   loopn   +$4F
00674F96   670000                 add     [bx+si], al
00674F99   0000                   add     [eax], al

*)
end;

end.