unit ReducaoZ;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, Mask, ExtCtrls, Buttons;
  
type
  TFrmReducaoZ=class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Panel1: TPanel;
    NbReducaoZ: TNotebook;
    bmCkAjustaRelogio: TCheckBox;
    pnDataeHora: TPanel;
    bmLbData: TLabel;
    bmLbHora: TLabel;
    BmMeData: TMaskEdit;
    BmMeHora: TMaskEdit;
    bmLbAviso: TLabel;
    Label7: TLabel;
    Label10: TLabel;
    Image1: TImage;
    Bevel1: TBevel;
    procedure bmCkAjustaRelogioClick(Sender : TObject);
    procedure _PROC_00675528(Sender : TObject);
    procedure _PROC_00675558(Sender : TObject);
    procedure _PROC_00675560(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmReducaoZ: TFrmReducaoZ;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmReducaoZ.bmCkAjustaRelogioClick(Sender : TObject);
begin
(*
00675454   55                     push    ebp
00675455   8BEC                   mov     ebp, esp
00675457   53                     push    ebx
00675458   8BD8                   mov     ebx, eax

* Reference to control TFrmReducaoZ.bmCkAjustaRelogio : TCheckBox
|
0067545A   8B8308030000           mov     eax, [ebx+$0308]
00675460   8B10                   mov     edx, [eax]

* Reference to method TCheckBox.GetChecked()
|
00675462   FF92C8000000           call    dword ptr [edx+$00C8]
00675468   84C0                   test    al, al
0067546A   7451                   jz      006754BD
0067546C   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.pnDataeHora : TPanel
|
0067546E   8B830C030000           mov     eax, [ebx+$030C]
00675474   8B08                   mov     ecx, [eax]

* Reference to method TPanel.SetEnabled(Boolean)
|
00675476   FF5164                 call    dword ptr [ecx+$64]
00675479   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.BmMeData : TMaskEdit
|
0067547B   8B8318030000           mov     eax, [ebx+$0318]
00675481   8B08                   mov     ecx, [eax]

* Reference to method TMaskEdit.SetEnabled(Boolean)
|
00675483   FF5164                 call    dword ptr [ecx+$64]
00675486   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.BmMeHora : TMaskEdit
|
00675488   8B831C030000           mov     eax, [ebx+$031C]
0067548E   8B08                   mov     ecx, [eax]

* Reference to method TMaskEdit.SetEnabled(Boolean)
|
00675490   FF5164                 call    dword ptr [ecx+$64]
00675493   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.bmLbHora : TLabel
|
00675495   8B8314030000           mov     eax, [ebx+$0314]
0067549B   8B08                   mov     ecx, [eax]

* Reference to method TLabel.SetEnabled(Boolean)
|
0067549D   FF5164                 call    dword ptr [ecx+$64]
006754A0   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.bmLbData : TLabel
|
006754A2   8B8310030000           mov     eax, [ebx+$0310]
006754A8   8B08                   mov     ecx, [eax]

* Reference to method TLabel.SetEnabled(Boolean)
|
006754AA   FF5164                 call    dword ptr [ecx+$64]
006754AD   B201                   mov     dl, $01

* Reference to control TFrmReducaoZ.bmLbAviso : TLabel
|
006754AF   8B8320030000           mov     eax, [ebx+$0320]
006754B5   8B08                   mov     ecx, [eax]

* Reference to method TLabel.SetEnabled(Boolean)
|
006754B7   FF5164                 call    dword ptr [ecx+$64]
006754BA   5B                     pop     ebx
006754BB   5D                     pop     ebp
006754BC   C3                     ret

006754BD   33D2                   xor     edx, edx
006754BF   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
006754C5   E8068BE8FF             call    004FDFD0
006754CA   33D2                   xor     edx, edx
006754CC   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Mask.TCustomMaskEdit.SetText(TCustomMaskEdit;TMaskedText);
|
006754D2   E8F98AE8FF             call    004FDFD0
006754D7   33D2                   xor     edx, edx
006754D9   8B830C030000           mov     eax, [ebx+$030C]
006754DF   8B08                   mov     ecx, [eax]
006754E1   FF5164                 call    dword ptr [ecx+$64]
006754E4   33D2                   xor     edx, edx
006754E6   8B8318030000           mov     eax, [ebx+$0318]
006754EC   8B08                   mov     ecx, [eax]
006754EE   FF5164                 call    dword ptr [ecx+$64]
006754F1   33D2                   xor     edx, edx
006754F3   8B831C030000           mov     eax, [ebx+$031C]
006754F9   8B08                   mov     ecx, [eax]
006754FB   FF5164                 call    dword ptr [ecx+$64]
006754FE   33D2                   xor     edx, edx
00675500   8B8314030000           mov     eax, [ebx+$0314]
00675506   8B08                   mov     ecx, [eax]
00675508   FF5164                 call    dword ptr [ecx+$64]
0067550B   33D2                   xor     edx, edx
0067550D   8B8310030000           mov     eax, [ebx+$0310]
00675513   8B08                   mov     ecx, [eax]
00675515   FF5164                 call    dword ptr [ecx+$64]
00675518   33D2                   xor     edx, edx
0067551A   8B8320030000           mov     eax, [ebx+$0320]
00675520   8B08                   mov     ecx, [eax]
00675522   FF5164                 call    dword ptr [ecx+$64]
00675525   5B                     pop     ebx
00675526   5D                     pop     ebp
00675527   C3                     ret

*)
end;

procedure TFrmReducaoZ._PROC_00675528(Sender : TObject);
begin
(*
00675528   55                     push    ebp
00675529   8BEC                   mov     ebp, esp
0067552B   33C0                   xor     eax, eax
0067552D   55                     push    ebp

* Possible String Reference to: 'ÈÊ˜ÿˇÎ¯]√ã¿É-êÈ}'
|
0067552E   684D556700             push    $0067554D

***** TRY
|
00675533   64FF30                 push    dword ptr fs:[eax]
00675536   648920                 mov     fs:[eax], esp
00675539   FF0590E97D00           inc     dword ptr [$007DE990]
0067553F   33C0                   xor     eax, eax
00675541   5A                     pop     edx
00675542   59                     pop     ecx
00675543   59                     pop     ecx
00675544   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-êÈ}'
|
00675547   6854556700             push    $00675554
0067554C   C3                     ret


* Reference to: System.@HandleFinally;
|
0067554D   E9E6F7D8FF             jmp     00404D38
00675552   EBF8                   jmp     0067554C

****** END
|
00675554   5D                     pop     ebp
00675555   C3                     ret

*)
end;

procedure TFrmReducaoZ._PROC_00675558(Sender : TObject);
begin
(*
00675558   832D90E97D0001         sub     dword ptr [$007DE990], +$01
0067555F   C3                     ret

*)
end;

procedure TFrmReducaoZ._PROC_00675560(Sender : TObject);
begin
(*
00675560   AC                     lodsb
00675561   55                     push    ebp
00675562   670000                 add     [bx+si], al
00675565   0000                   add     [eax], al

*)
end;

end.