unit Status;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls;
  
type
  TFrmStatus=class(TForm)
    Bevel1: TBevel;
    LbTexto: TLabel;
    procedure _PROC_00658454(Sender : TObject);
    procedure _PROC_0065845C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmStatus: TFrmStatus;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmStatus._PROC_00658454(Sender : TObject);
begin
(*
00658454   832D40DE7D0001         sub     dword ptr [$007DDE40], +$01
0065845B   C3                     ret

*)
end;

procedure TFrmStatus._PROC_0065845C(Sender : TObject);
begin
(*
0065845C   A884                   test    al, $84
0065845E   650000                 add     gs:[eax], al
00658461   0000                   add     [eax], al

*)
end;

end.