unit TDescon;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, DosMove, Buttons, ExtCtrls;
  
type
  TFrmTipoDesconto=class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    btDesconto: TBitBtn;
    btVoltar: TBitBtn;
    btFinaliza: TBitBtn;
    DosMove1: TDosMove;
    procedure _PROC_006B7584(Sender : TObject);
    procedure _PROC_006B758C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmTipoDesconto: TFrmTipoDesconto;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

procedure TFrmTipoDesconto._PROC_006B7584(Sender : TObject);
begin
(*
006B7584   832D88ED7D0001         sub     dword ptr [$007DED88], +$01
006B758B   C3                     ret

*)
end;

procedure TFrmTipoDesconto._PROC_006B758C(Sender : TObject);
begin
(*
006B758C   D8756B                 fdiv    dword ptr [ebp+$6B]
006B758F   0000                   add     [eax], al

*)
end;

end.